### ISSUE TITLE
Missing "turn screen on" option in osmand 3.3.4

### ISSUE THREAD

**Issue by bluescreen303** [osmandapp/Osmand#6675]
I recently upgraded both osmand (to 3.3.4) and android (to 9.0 pie) and can no longer find the "turn on screen before turn" feature in settings > navigation.

Should it still be there? Or was it moved?

**Comment by dmpr0** [comment]
Hello @bluescreen303!
The current release doesn't include this feature, we had to remove this option because of Google Play rules about the permission needed to that action. We are trying to find a solution to get it back.

**Comment by go4tidal** [comment]
Hope this feature can be restored as soon as possible. It's one of the best and most useful features in OSMAND navigation.

**Comment by bluescreen303** [comment]
Is the feature also disabled in the build on f-droid? since google's store rules aren't applicable there

**Comment by topas-rec** [comment]
I'm on 3.3.5 from fdroid and I'm missing the feature, too. That feature is one of the things I use when advertising for osmand.

- saves battery
- Makes you concentrate on the street when riding at night

**Comment by hvdwolf** [comment]
If it is an android permission, it has nothing to do with the Play Store or Fdroid.
In every new Android release some permissions change, are split up to make it more precise for the desired action, or completely removed. In Android 9 there some changes w.r.t. screen rotation also "touching" the lock screen. 
Maybe that is what they mean.

**Comment by bluescreen303** [comment]
@hvdwolf it appears (from #6721) that it really is about play store rules and not generic android permissions. The fact that latest osmand also doesn't show this option on android 7 and 8 is another indication it's not related to android permissions themselves.

Play store has additional rules about for what reasons certain permissions are meant/allowed and apparently the "device administrator" permission isn't meant for simple screen on/off management as it is somewhat overkill :) But as there is no obvious other permission that would give the desired functionality, I think google is somewhat overstepping by disallowing first, coming up with alternatives later. 

So it would be perfectly possible to just keep on using the device admin android permission and just not ship it through play store. However, maintaining 2 forks might not be something people are fond of.

**Comment by hvdwolf** [comment]
I see.

**Comment by bluescreen303** [comment]
another solution might be to just move the functionality to a plugin with needed permissions and then distribute that plugin as a manually-installable apk.

**Comment by hvdwolf** [comment]
That plugin apk could be downloadable and installable from inside OsmAnd as well. That is not too difficult.

Another option is to programmatically lower the screen brightness to its lowest value, and when neccessary (or when user touches the screen) to restore it to its original brightness. That would at least lower the energy consumption  a lot.

**Comment by skystis** [comment]
When riding with bicycle this feature is necessary.
Please make plugin, as workaround.

**Comment by mpotse** [comment]
Without this option osmand is unusable for cycling. With the screen continuously on the battery lasts only an hour or so; even with a hub dynamo it would lose charge. Leaving it off is not possible either: the spoken instructions are often ambiguous or misleading so a visual check is necessary. And manually switching it on at every turn is cumbersome and sometimes dangerous. Often the phone is locked by then. I downgraded to 3.2.

If this is going to be fixed it would be nice if another issue could also be solved: when something else turns on the screen during navigation, osmand will keep it on forever.

**Comment by mircozorzo** [comment]
So please also for car navigation it's very important.
Give it back, please.

**Comment by JohnnnyBeGoood** [comment]
I see two (or maybe three) issueshere:
1) How can Google impose on developers through "Play store rules" how they can/should develop apps
Why is nobody protesting? Why is everybody, and obviously osmand, just taking it?
2) Why don't developers, like osmand just move their software to some other store to avoid Google's diktat?
3) Why does osmand not tell us about removed features and lets us discover that ourselves like idiots?
Sorry for the idiot but that's how I feel when I have to browse through all the options just because someone "forgot" to mention that features are gone. And how about a plan for getting the functionality back?

Like the others said, for cycling osmand is almost unusable now, as with the screen permanently on the battery barely lasts 1.5 hours.

**Comment by pebogufi** [comment]
FULLY AGREE !!!

**Comment by fabriziobertocci** [comment]
Joining the voices here. This feature is very important for bikeriding. It allows to save batteries and at the same time allow for a visual validation of where you are going.

**Comment by burn2k** [comment]
With this option, my main reason for using the app while cycling is gone.
Please bring it back, in the main app, as plug in or over f-Droid-, but don't let Google destroy this awesome app for cycling. I use Osmand Plus 3.3.7

**Comment by prinf** [comment]
Voting for this as well. The super important feature that saves phone battery and doesn't allow my phone to overheat when navigating.

**Comment by mircozorzo** [comment]
One more voice for the return of this great feature.

**Comment by guillaumedc** [comment]
What about a dual build?
One compliant with Google Play Store rules and one another for F-droid?

At least, could you point out which commit remove this feature?
Or how it is possible to make our own build without this restriction?

**Comment by vshcherb** [comment]
The discussion will be locked in case it will be too many similar replies.
We are working on solution will be provided in 3.4 though most likely it will be a separate plugin.

**Comment by meden** [comment]
I hit this today, during a trip in motorcycle. Thanks for considering as high priority, and for setting the next release as milestone, but maybe this in not enough for all users (i.e. others than car drivers).

If it's just a Play Store rule, then please seriously consider a different build for it, leaving the application uncrippled in other stores (e.g. I bought the paid version on Amazon, and honestly I'm quite disappointed now...). And please, in the future state clearly such kind of "downgrades", blaming who has to be blamed and avoiding bad surprises to the users.

Thanks for your amazing work.

**Comment by vshcherb** [comment]
Please use free version alongside next to the paid version which you can downgrade https://download.osmand.net/downloads. You can use Share storage, so you will be able to download  maps through paid version

**Comment by lead-legs** [comment]
Hi, can someone please explain how to use the downgraded free version next to the paid version.
Whenever I try to manually set the folder to net.osmand.plus which has all the data in, I get the error message, unable to create maps folder.
Thanks.

**Comment by mpotse** [comment]
As far as I can see sharing between different apps is only possible with emulated storage which is always in the phone memory, not on sd card. My phone has too little memory for the maps I need so I just gave up on it and simply copied or moved map files with my phone's file manager.

On April 29, 2019 1:00:50 PM GMT+02:00, lead-legs <notifications@github.com> wrote:
>Hi, can someone please explain how to use the downgraded free version
>next to the paid version.
>Whenever I try to manually set the folder to net.osmand.plus which has
>all the data in, I get the error message, unable to create maps folder.
>Thanks.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/osmandapp/Osmand/issues/6675#issuecomment-487537912

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by stillmc** [comment]
What is the last version to include the "turn screen on" option? I know 3.2.7 has it (which I downgraded to), but do any of the 3.3.x versions include it? 

Also, any time frame on 3.4? 

TIA and great app!

**Comment by pebogufi** [comment]
Version from 2019-02-20 did it, was 3.3.0#26810 from nightly builds.

**Comment by pebogufi** [comment]
Version from 2019-02-20 did it, was 3.3.0#26810 from nightly builds. I could save it.

**Comment by darolek** [comment]
The last official version with this functionality is 3.2.7 from December 2018. Each subsequent version of OsmAnd did not have this function anymore.

**Comment by Sunbird** [comment]
@devs: Please please please include the removal of features in the changelog, too.

I felt the lack of this feature on my last bike trip and went nuts searching for this option after the update.

Will have to downgrade too as we're going on a bicycle trip tomorrow. :-(

**Comment by jnettels** [comment]
Can somebody help me?
I usualy use osmand plus from fdroid (which I am very grateful for). After discovering this issue I went to osmand.net/downloads and installed an older .apk manually. I had to copy all favourites and maps from osmand-plus to osmand, since I could not make them share a folder on my sdcard, but that is fine. I had the "turn screen on" option back, yay!

The problem: A day later Google PlayStore updated the osmand (free) version, all by itself. Now I have both "free" and "plus" installed, both with the same current (but partially unusable) version.

How can I install a downgraded version that does not update itself? Is there another way than disabling auto-updates in PlayStore?

**Comment by scaidermern** [comment]
> How can I install a downgraded version that does not update itself? Is there another way than disabling auto-updates in PlayStore?

Open PlayStore and navigate to the app. Tap on the three dot menu in the upper right corner. There is a checkbox to disable automatic updates for this particular app.

**Comment by jnettels** [comment]
Thanks, I should have found that myself. Hopefully this will help others, too!

**Comment by crimean** [comment]
Added by https://github.com/osmandapp/Osmand/commit/e9ae109ef8cf38b3cc2133b86787608c6d5ab3a1

**Comment by DrVanScott** [comment]
I am currently using 3.2.7. When will the plug-in be available?

**Comment by crimean** [comment]
@DrVanScott  Please update OsmAnd to latest version.

**Comment by phillord** [comment]
The option is there, but greyed out with no description about how to enable it. I guessed this is because there is a plugin to install, but I cannot find the plugin in the plugin menu either.

Confused.

**Comment by enricotagliavini** [comment]
Look at the following option, it's the time the screen will stay on, set it to any value other than zero and the feature will be enabled. Tried it the day it was out and it worked, I'm really glad.

Thank you very very much for implementing this feature again!

**Comment by flyinva** [comment]
Neither plugin nor option in OsmAnd 3.4 from f-droid.org :-(

**Comment by mircozorzo** [comment]
Downloading the development version from the app works great.

Mirco

Il sab 13 lug 2019, 15:14 Sylvain <notifications@github.com> ha scritto:

**Comment by Zahnstocher** [comment]
@DrVanScott 
@flyinva 
> Neither plugin nor option in OsmAnd 3.4 from f-droid.org :-(

3.4.2 is needed, 3.4.0 is too old.
"turn screen on" was integrated into OsmAnd, there is no plugin.

**Comment by Policjant** [comment]
So when we can expect the 3.4.2 version on the f-droid?

**Comment by phillord** [comment]
@enricotagliavini Thank you, that does indeed work.

**Comment by hvdwolf** [comment]
Note that the OsmAnd team has nothing to do with f-droid.
It is the f-droid team compiling the stuff.
Mostly they "deliver" 7-14 days later. So around 20 July till end of July
(I guess).



Op za 13 jul. 2019 om 22:17 schreef Loss <notifications@github.com>:

**Comment by Zahnstocher** [comment]
> So when we can expect the 3.4.2 version on the f-droid?

3.4.2 is available on F-Droid now.

**Comment by Policjant** [comment]
You are right but now when I am selecting the GPX file Osmand~ the program always crash and shut down.

**Comment by Zahnstocher** [comment]
> You are right but now when I am selecting the GPX file Osmand~ the program always crash and shut down.

This is a different issue.
Probably it will be fixed in 3.4.3:
https://github.com/osmandapp/Osmand/issues/7242
https://github.com/osmandapp/Osmand/issues/7233

**Comment by Policjant** [comment]
I see that the basic version has now update to 3.4.3 ;-) so we have to wait for f-droid ;-)

**Comment by Themanwithoutaplan** [comment]
Questions regarding F-Droid are totally irrelevant. Especially if you're using F-Droid you should be able to sideload an APK directly but otherwise all such enquiries should be directed to F-Droid.

Regarding the fix itself: works great, as does the proximity detection. Thanks very much guys!

**Comment by florian29** [comment]
I've tried it today with 3.4.2 from f-droid and it doesn't work the way it should. The screen turns on one time and stays on the whole time and not only the seconds which are set in the time option. You have to turn off the screen manually and the next time it goes on by itself and stays on again the whole time. In addition the navigation screen now misses the upper left part where has been the arrow for the next turn. There only appears the small box with the arrow for the second turn. This is useless.

**Comment by bluescreen303** [comment]
I'm using the normal play store version for osmand+ on a moto g6 plus
(android 9)

Turning the screen on works fine in portrait mode, but in landscape, I see
it light up portrait, instantly turn to landscape, which somehow triggers
the lock screen, blocking osmand from view.

So, great to at least have something working again, but not in full yet.

**Comment by enricotagliavini** [comment]
I also got the lock screen shown a couple of times on Android 9, and this was in portrait mode, not in landscape. I'm not sure what triggered it, I had the phone in my hands and I think I might have touched the screen or a button. Hard to say if it was that or phone trying to rotate due due accelerations making it believe to be in landscape mode.

**Comment by Themanwithoutaplan** [comment]
> I'm using the normal play store version for osmand+ on a moto g6 plus (android 9) Turning the screen on works fine in portrait mode, but in landscape, I see it light up portrait, instantly turn to landscape, which somehow triggers the lock screen, blocking osmand from view. So, great to at least have something working again, but not in full yet.

I've had that kind of screen-locking before and I think it's a separate issue. A lot of apps struggle when waking up in to landscape mode: they will start in portrait mode and then switch. Occasionally OsmAnd would start constantly switching between itself and lock mode and the only solution was to try and hit the home button at the right time. But I haven't had this for a while since I haven't had any predominantly East-West tracks and cannot currently mount my phone horizontally, and even then enabling the adaptive compass is usually the best solution.

It can, however, help to disable orientation switching.

**Comment by AndyGHenderson** [comment]
> I've tried it today with 3.4.2 from f-droid and it doesn't work the way it should. The screen turns on one time and stays on the whole time and not only the seconds which are set in the time option. You have to turn off the screen manually and the next time it goes on by itself and stays on again the whole time.

Seeing this too. Still not working right after installing bug fix releases (now on 3.4.4). See also thread in Google Groups.

Using Motorola G3 with Android 6.0.1

Andy

**Comment by lead-legs** [comment]
> I've tried it today with 3.4.2 from f-droid and it doesn't work the way it should. The screen turns on one time and stays on the whole time and not only the seconds which are set in the time option. You have to turn off the screen manually and the next time it goes on by itself and stays on again the whole time. In addition the navigation screen now misses the upper left part where has been the arrow for the next turn. There only appears the small box with the arrow for the second turn. This is useless.

I have exactly the same problem - I'm not using F-Droid, I'm using the Google Play version. I set the seconds but the screen turns on but doesn't turn off.

**Comment by phillord** [comment]
I also am not getting good functionality from this. It did seem to work initially, but it seems to fail on in car usage, partly I think because of the screen re-orientation. What actually happens: a lock screen notification comes up (in portrait, although in car I am in landscape), the screen unlocks shortly after in portrait, OSMand becomes visible in portrait, the screen re-orients which takes a second or two, then immediately falls back into lock screen. All this is a bit distracting, and the screen is not visible for long enough to see directions.

I also think that the timing options are a bit strange and too granular. In car, 10 seconds to 5 mins would be a better spread; at 5 mins, it would stay on in town, and switch off on motorway which would be good behaviour for me.

**Comment by florian29** [comment]
The issue isn't solved in version 3.4.5 yet. The screen turns on but doesn't turn off. At least the issue with the navigation panel is now solved.

**Comment by Policjant** [comment]
Yep, still the same problem. The screen wake up but do not dim again. On the old versions the application was asking  each time when I was enable this fuction for special permissions to manage screen... now does not do it and only waking up screen working without automatically turn off.

My navigation phone is using Android 5.0.1

**Comment by lead-legs** [comment]
I opened a new issue as this issue has apparently been closed.
[https://github.com/osmandapp/Osmand/issues/7315](url)

**Comment by florian29** [comment]
> 
> 
> I opened a new issue as this issue has apparently been closed.
> [https://github.com/osmandapp/Osmand/issues/7315](url)

The link is dead.

**Comment by scaidermern** [comment]
> > I opened a new issue as this issue has apparently been closed.
> > [https://github.com/osmandapp/Osmand/issues/7315](url)
> 
> The link is dead.

Probably a GitHub bug. See #7315.

**Comment by benaxe** [comment]
I have 3.4.6 installed. If you leave voice on and mute the volume on the phone the screen switches off properly.

**Comment by GunSmoker** [comment]
I believe other applications workaround this by creating icon in Android's notification area. Is there a reason why OsmAnd can't do the same?

**Comment by Chris2000SP** [comment]
Sorry to comment on old thread, but battery efficiency is at best if the android ROM has all drivers (graphics, gps, etc.) and is well configured (gps.conf etc.). Most of the time this is NOT found in Custom Roms! Yes, you can configure it well to be more efficient, but a good Manufacture has already well running Stock Roms with plenty battery efficiency. Custom Roms maybe get better after time but depends on good support of the Hardware driver side.

Second: After a period of time it's not a bad thing when old hardware has had its day. And buy something sustainable.

PS: If you have no more energy in your pocket, it is useful to learn using a good old compass + map navigation with Cross bearing. You can print OSM on paper, you know?

**Comment by Chris2000SP** [comment]
Sorry to be so harsh on custom roms but i am frustrated. That's all. Linus Torvalds sad something about good infrastructure on the x86 architecture. I know that linux on arm or riscv will get big, but to get big it needs developers with an open infrastructure. RiscV has it, mostly, and ARM, it depends.

**Comment by Themanwithoutaplan** [comment]
This has nothing to do with custom ROMs. If you have nothing to contribute to the issue, it's better to say nothing.

**Comment by mrt25** [comment]
i've wrestled with this quite a few times, and have forgotten the following, it may or not not apply to others here

my phone a sony xperia, has a 'auto backlight' function. this senses if you are looking at the screen and keeps it on.
this naturally interferes with the system timeout.

turning this off while cycling enables the screen to auto-off after 15 secs and turn on again with new navigation announcements
