### ISSUE TITLE
Wrong bicycle routing at crossing=no

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#6678]
OsmAnd has a problem with this short section in bicycle routing mode and calculates a huge detour:

![photo_2019-03-14_09-40-49](https://user-images.githubusercontent.com/1040784/54342636-4a006500-463d-11e9-9b2b-b1cff9d4709b.jpg)

Start: geo:51.05834,13.753294
End: geo:51.058567,13.753181

Route: [route.gpx.txt](https://github.com/osmandapp/Osmand/files/2965479/route.gpx.txt).

Problem does not occur in car and foot routing.

Problem does not occur with [OSRM](https://www.openstreetmap.org/directions?engine=fossgis_osrm_bike&route=51.05834%2C13.75329%3B51.05857%2C13.75318) and [GraphHopper](https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=51.05834%2C13.75329%3B51.05857%2C13.75318)

**Comment by vshcherb** [comment]
It doesn't say much about data equality cause OSRM could have a newer or older map, it would be great if the latest data could be verified

**Comment by scaidermern** [comment]
Yes. I already tried to verify it and as far as I know it looks good.

**Comment by scaidermern** [comment]
Problem does not occur with [brouter](http://brouter.de/brouter-web/#map=17/51.05856/13.75348/OpenStreetMap&lonlats=13.753294,51.05834|13.753181,51.058567) (which has quite up-to-date data).

**Comment by scaidermern** [comment]
Still exists with April maps. Still doesn't exist for OSRM, GraphHopper and brouter.

Can some developer take a look at the map data to identify which tag breaks bicycle routing here? Thanks!

**Comment by xmd5a2** [comment]
crossing=no without highway=traffic_signals breaks routing

**Comment by scaidermern** [comment]
> crossing=no without highway=traffic_signals breaks routing

Thanks. But why exactly? This applies to a crossing footway. It is not an access restriction or barrier of any kind. It shouldn't affect bicycle routing in this case.

**Comment by scaidermern** [comment]
There are lots of nodes tagged as `crossing=no` without `highway=traffic_signals`, see https://overpass-turbo.eu/s/HW4. Treating them as bicycle barriers breaks bicycle routing at many locations.

**Comment by xmd5a2** [comment]
@scaidermern Yes, but there are many nodes like this https://www.openstreetmap.org/node/258241463
where footway crosses the road. Simple removing crossing=no rule from bicycle routing will ignore these restrictions. But I think this tagging is confusing.

**Comment by scaidermern** [comment]
I agree, this tagging is rather sub-optimal.

Maybe the following generalization can be used: `crossing=no` applies only to the way of _lower_ or _lowest_ class.

I guess this is not easy to check for routers. However maybe OsmAnd can use a different approach by preventing routing if the *current* way is a footway/cycleway/path and ignore it if the *current* way is of higher class (i.e. motor vehicle road classes). Is this technically feasible?

**Comment by xmd5a2** [comment]
At this moment there is no easy way to make such a logic. I removed crossing=no rule

**Comment by scaidermern** [comment]
Not fixed in OsmAnd 3.4.0. Does this need new maps?

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/edc10e5063ef601483ae088157aadae094a8a43e
