### ISSUE TITLE
Feature request: support the comment and description tags in GPX files

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/OsmAnd#6683]
Please add support of the comment and description tags in GPX files, so it is possible to display them in the imported tracks and also be able to add/edit them directly in OsmAnd. 

Another suggestion is to change the sorting order of tracks in the list, introducing more sorting options. It would be really helpful to sort by date, length, etc.

**Comment by axd1967** [comment]
use case: I import GPX data via overpass turbo, and want to see the opening hours. showing data seems to work for points only, not for lines .

**Comment by dmpr0** [comment]
Added https://github.com/osmandapp/OsmAnd/issues/18342
