### ISSUE TITLE
Selecting 'previous navigation' forgets profile

### ISSUE THREAD

**Issue by pietervdvn** [osmandapp/Osmand#6684]
3.3.4

When selecting one of the 'previous route' in the navigation window, the profile used should be restored too - now it defaults to the first profile available. 

(BTW: the new layout is really great and offers a lot of neat, new features! There are a few last bugs though)

**Comment by sonora** [comment]
I think I had fixed this, can you please test 3.3.5?

**Comment by pietervdvn** [comment]
Tested on 3.3.5, indeed fixed there.
