### ISSUE TITLE
Totally custom routing settings are not shown in directions menu

### ISSUE THREAD

**Issue by pietervdvn** [osmandapp/Osmand#6685]
3.3.4

I'm working on custom ski routing, piggybacking on the 'boat' profile. However, they don't show up in the new GUI.

![Screenshot_20190314-205005_OsmAnd+](https://user-images.githubusercontent.com/1466478/54387197-0dfbed00-469b-11e9-9f26-754cffb6a181.png)
![Screenshot_20190314-205020_OsmAnd+](https://user-images.githubusercontent.com/1466478/54387198-0dfbed00-469b-11e9-870b-b908ef8c2edc.png)

**Comment by crimean** [comment]
Fixed
