### ISSUE TITLE
[Request] Allow custom statistics

### ISSUE THREAD

**Issue by pietervdvn** [osmandapp/Osmand#6686]
3.3.4

The new statistics are awesome! It would be even cooler to show custom statistics so that people can add their own (e.g.: how many % of the road is lit, what difficulty are the ski slopes, how much of it is aerialway, ...)

Would it be possible to add this to the routing.xml?

**Comment by vshcherb** [comment]
Today you can only customize existing statistics by rendering style but you can't add new extra statistics. It might be not difficult to implement but it certainly needs extra thoughts.

**Comment by vshcherb** [comment]
I think it is already implemented with
routeInfo_piste_difficulty
and 
routeInfo_piste_type

**Comment by pietervdvn** [comment]
Indeed, this has been implemented since then.
