### ISSUE TITLE
Problem with public transport navigation

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/Osmand#6687]
I know that public transport navigation is in beta but I write this issue because Osmand 3.3.3 generates best routes than Osmand Nightly 3.3.0#23568d and I think Osmand Nightly should calculate better routes because it is newer than Osmand 3.3.3. The same map (spain, 1 march 19) with the two versions.

Example 1:
From https://www.openstreetmap.org/node/2083801732 to https://www.openstreetmap.org/node/1439708980
Osmand 3.3.3 offers a route that takes 54 minutes (bus route 691) Osmand Nightly 3.3.0#23568d offers a route with 3 transfers that takes 1 hour 18 minutes.

Example 2:
From https://www.openstreetmap.org/node/3250877328 to https://www.openstreetmap.org/node/3250877317 Osmand Nightly 3.3.0#23568d offers a route where you have to walk on a section of route 680. If I change "from" and Osmand Nightly calculates a route from https://www.openstreetmap.org/node/2271033546 to  https://www.openstreetmap.org/node/3250877317 generated route do not include walking section. Osmand 3.3.3 calculates the same route In both cases (without walking section)

**Comment by vshcherb** [comment]
Tested both versions and it looks both of them are fixed now

**Comment by OpenSourceForEver** [comment]
Fixed. Thank you very much
