### ISSUE TITLE
Co-Ordinates missing

### ISSUE THREAD

**Issue by QuestionsForThose** [osmandapp/Osmand#6688]
Please see my issue in the next post

**Comment by QuestionsForThose** [comment]
I can no longer find the coordinates lat/long of My Favourites points. Also I can not read the position lat/long of the current location. This is only a recent change. Can this be fixed please

**Comment by scaidermern** [comment]
Is this a duplicate of #6672?

**Comment by QuestionsForThose** [comment]
Yes, exactly. I will close.
