### ISSUE TITLE
The "Add destination" screen should not have the "swap start and destination"  button

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#6691]
We can land on the **Add destination** screen (dialog) only from the **Route Editor**.

And the **Route Editor** already has the **Swap** button that interchange **start** and **destination** points. Therefore it makes no sense to have the same button on the "Add destination" dialog box (card) also. (This is unnecessary duplication)

**Comment by dmpr0** [comment]
@raindropsfromsky Hello! Thank you for the feedback.
We think it makes sense because in the Add Start/Destination bottom sheets the button is with the text label.
