### ISSUE TITLE
Screen always on in map-viewing mode

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6692]
The main screen in OsmAnd does not turn off in the map-viewing mode despite system settings of screen timeout. It always remains active. 
OsmAnd 3.3.4

**Comment by sonora** [comment]
It is by design. Use case is to have this running in your car, even without route, or with route but with no turn-by-turn guidance. If you want the system setting to take over, simply put OsmAnd in the background.

**Comment by LendoK** [comment]
Before it was much better. The screen turned off after system screensaver-time and turned on if there was an announcement. I used it in a car and it worked fine. Why not just adding an option to prevent the screen from turning off?

**Comment by sonora** [comment]
I am not aware we have changed this, ever.

**Comment by LendoK** [comment]
Also the lock screen-behavior changed for me. Previously in navigation the map was not blocked by the lock-screen. Osmand+ was overlaying the lock-screen and completely functional. Now I have to unlock every time I turn off the screen an on again. I'm not sure if there was a setting for this.

**Comment by scaidermern** [comment]
> Also the lock screen-behavior changed for me. Previously in navigation the map was not blocked by the lock-screen. Osmand+ was overlaying the lock-screen and completely functional. Now I have to unlock every time I turn off the screen an on again. I'm not sure if there was a setting for this.

This is a known issue. This requires the device administrator permission which had to be removed due to Google Play Store policies. It will come back at some time, see #6675.

**Comment by LendoK** [comment]
Ok thanks, I'm glad it will come back.
By the way, is there a decent build guide? I tried to build Osmand with AndroidStudio but failed. Seems like the resources needs to be placed in the buildtree /src/test/resources or something. A wiki page would be helpful.
