### ISSUE TITLE
Some OsmAnd strings switch back from changed locale to default phone locale upon rotation

### ISSUE THREAD

**Issue by hvdwolf** [osmandapp/Osmand#6695]
OsmAnd 3.3.4 and 3.3.5

My phone default locale is Dutch (NL_nl).
I always set OsmAnd to "system default" being Dutch in my case.

I did some comparisons in the GPX navigation options and for that I set the language to English. I completely closed OsmAnd and restarted it.

In the GPX menu/navigations options, when I rotate my phone, some of the strings switch back to Dutch.
"Calculate route between points" and "Reverse GPX direction" switch back to Dutch and then remain Dutch upon rotating back and forth.

**Comment by vshcherb** [comment]
I think it is long running issue and it actually depends on OS version it runs.  We will try to explore with details

**Comment by hvdwolf** [comment]
Sorry, I forgot to add that OS info.

Motorola G5Plus Android 8.1 Stock ROM.
