### ISSUE TITLE
Total traveled/walked in PT routes

### ISSUE THREAD

**Issue by IgorEliezer** [osmandapp/Osmand#6697]
Suggestion/Improvement.

I took some while to understand these values "13 min • On foot 16 min, 981 m"

![image](https://user-images.githubusercontent.com/4673289/54476491-d1d0a580-47dc-11e9-83f6-be57792d94b5.png)

I thought the first value (on the left of the  •, unspecified) was the total but how 16 min on foot would fit in 13 min in total? Later on I got the 1st value was the time traveled by vehicle.

It's intuitive to assume these values as a summary of the route, in other words, as totals. If I want to break it down into time and distance traveled (by vehicle) and time and distance on foot I would tap "Details".

My suggestion would be:
* Show only the totals: `29 min, 5.051 km` (*)
* Show only the totals with a string "Total": `Total 29 min, 5.051 km`

Alternatively, since the time and distance on foot are relevant for PT, show the totals and the time/distance on foot:
* `29 min, 5.051 km  • On foot 16 min, 981 m`
* `Total 29 min, 5.051 km  • On foot 16 min, 981 m`
* `Total 29 min, 5.051 km  • 🚶 16 min, 981 m`

\* - "29 min, 5.051 km" is the sum of the values shown in Details.

**Comment by vshcherb** [comment]
This is already fixed I guess (or will be Monday) please try night builds
