### ISSUE TITLE
Wrong parentheses for RTL languages

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6698]
![image](https://user-images.githubusercontent.com/40493090/54477198-3526fb80-480e-11e9-9da6-f25e5e16673f.png)

**Comment by yarons** [comment]
![Screenshot_2019-05-01-08-07-47-665_net osmand plus](https://user-images.githubusercontent.com/406826/57006430-6fdfca00-6be9-11e9-95dd-22b5e53ce8d9.png)

I can confirm that in OsmAnd 3.3.8 on Android from F-Droid.

**Comment by iriman** [comment]
Confirmed, happens with Persian, too.

**Comment by vshcherb** [comment]
https://www.openstreetmap.org/node/1803034759#map=17/32.45386/34.90321

**Comment by yarons** [comment]
I found another option:
מחלף רבין (שמריהו).
