### ISSUE TITLE
Exported tracks don't pass in Garmin Basecamp

### ISSUE THREAD

**Issue by ejain** [osmandapp/Osmand#6701]
Because the exported GPX files don't pass validation, some applications (like Garmin Basecamp) are unable to import them.

The problem appears to be a missing namespace for the "speed" extension element. This can be fixed by declaring the namespace e.g. with `xmlns:gpxtpx="https://wwww.garmin.com/xmlschemas/TrackPointExtensionv1.xsd"`, and prefixing the "speed" tags:

```xml
<trkpt lat="48.1417716" lon="-122.5134899">
  <ele>2</ele>
  <time>2019-03-17T21:06:53Z</time>
  <hdop>4</hdop>
  <extensions>
    <gpxtpx:speed>0.672</gpxtpx:speed>
  </extensions>
</trkpt>
```

**Comment by vshcherb** [comment]
This element is allowed by specification - https://www.topografix.com/gpx/1/1/#type_extensionsType. I assume, it is purely problem of Garmin Basecamp. 

Suggestion looks interesting and if we do something similar we need to be backward compatible with other programs.

**Comment by dmpr0** [comment]
Hello, @ejain! Our past investigation shows that Garmin Basecamp doesn't support <rte> tag, that OsmAnd adds while recording gpx.

**Comment by vshcherb** [comment]
We've tried all possible ways i.e.
```
xmlns:osm="https://osmand.net/GPXExtensions/1.0"
and 
xmlns:gpxtpx="https://wwww.garmin.com/xmlschemas/TrackPointExtensionv1.xsd"
 <gpxtpx:speed>0.672</gpxtpx:speed>
```

Though it didn't work in Garmin Basecamp at all and we could not open it. Since we need to store speed in GPX and it possible to convert it through  https://www.gpsvisualizer.com/. This issue couldn't be solved on our side
