### ISSUE TITLE
Wrong language of Wikipedia articles

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6706]
After downloading Wikipedia for  Germany Hamburg, some articles are only in French or Catalan. 
Example: https://osmand.net/go.html?lat=53.46585&lon=9.993954&z=16 
https://ca.m.wikipedia.org/wiki/Schiffsgraben

**Comment by pebogufi** [comment]
Article Schiffsgraben exists only in ca.
