### ISSUE TITLE
Measure distance: Boat profile doesn't work in Snap to Road mode

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/Osmand#6710]
Boat profile doesn't calculate route between points.

**Comment by treestryder** [comment]
I haveve been meaning to report this for almost a year. I think it broke around the time support for white water amenities was added.

Thanks for looking into this! Paddling season (in the north) is starting and this feature would be greatly missed.

**Comment by treestryder** [comment]
Thanks, @Chumva!

**Comment by ClayF** [comment]
I seem to be having a similar issue, I get a message saying "too far from road" or "route cannot be found from start point".

Unsure if I've done the route correctly 


![Screenshot_20201004-124515](https://user-images.githubusercontent.com/7761432/95021542-90624e00-063f-11eb-8839-a5048efe1335.png)
