### ISSUE TITLE
Show "hazard" in the POI details

### ISSUE THREAD

**Issue by IgorEliezer** [osmandapp/Osmand#6714]
I think it's interesting to add a "Hazard" field in the POI details if the selected object has a `hazard` tag.

Example: abandoned substation with `hazard=contamination`: https://www.openstreetmap.org/way/612146707

![image](https://user-images.githubusercontent.com/4673289/54652996-cceb4a80-4a97-11e9-8824-b103ccfc49c4.png)

I had to resort to using the `description` tag to specify the hazard type to warn ~stupid or dead~ tourists. (it's within a National Park, by the way) ;o)

![image](https://user-images.githubusercontent.com/4673289/54653151-6155ad00-4a98-11e9-8b93-bdad4831a16c.png)
(it reads: Old Varnhagen railway substation. WARNING: contaminated area.)

----

If you ask me if there wasn't a warning sign at the place by any chance, my answer will be "I don't know" because 200 m before there was a warning sign which read "Area with ticks. Check your clothes periodically" that was a deal-breaker. :o)

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/9df1187ecde43c3d9860a434fa0a8beeee55948a
