### ISSUE TITLE
Multipolygon tags are not shown

### ISSUE THREAD

**Issue by pietervdvn** [osmandapp/Osmand#6717]
3.3.0#27029m (nightly after 3.3.6, 2019-03-20)

When looking to a nature reserve which is shown as multi-polygon, the extra tags are not included. E.g. https://www.openstreetmap.org/relation/8188853 has plenty of information (e.g. wikipedia, website) but that does not show up. However, it does show up on a nature reserve which has been drawn as a normal way (such as https://www.openstreetmap.org/way/534673296).

I suspect that this is a general problem for any multipolygon.

![Screenshot_20190320-112944_OsmAnd+](https://user-images.githubusercontent.com/1466478/54684877-c26f9600-4b15-11e9-965a-59f03ee172ac.png)
![Screenshot_20190320-133338_OsmAnd+](https://user-images.githubusercontent.com/1466478/54684881-c4395980-4b15-11e9-942a-5a29cc5839aa.png)

**Comment by vshcherb** [comment]
We need to double check the POI information. In case you can find 2 POI's then issue is related to duplicate information, in case it is a single POI then the tags were not propagated from relation to area. 
Probably @xmd5a2  can comment how it works

**Comment by vshcherb** [comment]
Fixed

**Comment by pietervdvn** [comment]
:partying_face:
