### ISSUE TITLE
Osmand is not in Android Device Administrator list and "turn screen on" option is not present

### ISSUE THREAD

**Issue by shoustor2** [osmandapp/Osmand#6721]
I'm not able to find the "turn screen on" option in Osmand settings  (Android app).
In Android Device Administrator list there isn't Osmand.

**Comment by njohnston** [comment]
As explained in this [OsmAnd tweet](https://twitter.com/osmandapp/status/1101771221493002240), the developers had to remove this feature as Google temporarily removed OsmAnd from Google Play because of it.

Watch issue #6675 for a replacement solution.

**Comment by sonora** [comment]
Let's merge into #6675.
