### ISSUE TITLE
Improvement: choosing its own icons for marker - favorites

### ISSUE THREAD

**Issue by gignacnic** [osmandapp/Osmand#6722]
Like it can be done in other GPS navigation app products similar to OsmAnd (ex. Locus Map), would it be a big features to develop if the user would be able to choose from a list of icon its marker or favorites waypoint on the map?

**Comment by gignacnic** [comment]
If there is a simple way to pay for this development, I would look at contributing $.

**Comment by gignacnic** [comment]
We found a way to have icons on the map by using certain emoticons in the name of favorites points.

**Comment by vshcherb** [comment]
Cool ! We plan to have favorite / poi icons as emoticons but that is in the middle of our backlog though
