### ISSUE TITLE
Improvement: show marker name or favorites waypoint name on map

### ISSUE THREAD

**Issue by gignacnic** [osmandapp/Osmand#6723]
Like it can be done in other GPS navigation app products similar to OsmAnd (ex. Locus Map), would it be a big features to develop if the user would be able to show label of its marker name and favorites waypoint (name) on the map?

**Comment by njohnston** [comment]
You can already configure OsmAnd to show the label for favourites and waypoints in GPX files. Go to "Configure Map", and enable "POI overlay labels".

It doesn't work for markers.

**Comment by gignacnic** [comment]
Ok, I think it is fine, just to make marker as favorites, thanks! By the way, osmand is a very good open source project!!
