### ISSUE TITLE
Analyze track, switching to time seeks beyond file memory, crashes map display.

### ISSUE THREAD

**Issue by seahorse41** [osmandapp/Osmand#6728]
versions: Osmand plus 3.3.5
Pixel
android 8.0.0
Offline maps

From dashboard, choose a previously recorded track. scroll down and choose Analyze on map. The problem is easier to reproduce by zooming in. Tap the bottom graph to select a point in the middle of the trip.
Switch to time or time of day. Notice how the map display shifts, and usually the blue dot is left behind. The shift is not always the same. On a long track it was 14 minutes, on another track it was only 1 minute. Might be related to current zoom level, or position in the gpx file.

Also any switching from Distance to Time, loses the vertical line on the graph. The location of the blue dot becomes lost.

Switching back and forth shifts the map center. The shift in time along the track seems to be the issue. If a point very near the beginning of the track is selected in distance,
![OsmAnd335_20190321_102813_analyze-200ft](https://user-images.githubusercontent.com/14300304/54776136-b7c40800-4bcc-11e9-9dfa-1b750528cf42.png)
 then switch to time or time of day and it seeks beyond the file, into other memory, and in my case showing a blue ocean
![OsmAnd335_20190321_102819_blueOcean-200ft_analyze](https://user-images.githubusercontent.com/14300304/54776199-d5916d00-4bcc-11e9-804f-b6d5e2ca20e5.png)
that might as well be on some other planet. If I don't switch back to Distance first, before exiting, it stays on this blue ocean with no features, and attempting to determine location by holding for a marker, and choosing details, shows no results for coordinates. No address determined. I zoomed out to 1 mile scale, it found one orange line from somewhere.
![OsmAnd335_20190321_102926_blueOcean_mapMarker_noAddress](https://user-images.githubusercontent.com/14300304/54776338-21441680-4bcd-11e9-8057-4d99a4b55167.png)

The only way back to the real map is to turn on location and get a gps coordinate loaded.

If select a new point in time mode, and then switch to distance, the blue dot disappears and this time the map does not shift to the new point. Now I cannot select a point on the current graph again, blue dot stays off screen.

**Comment by Chumva** [comment]
I cannot reproduce it in the current app version.
