### ISSUE TITLE
Public Transit - Calculated Route is Empty

### ISSUE THREAD

**Issue by PrasannaVenkadesh** [osmandapp/Osmand#6731]
> What version of OsmAnd are you using, on what device and Android/iOS version?

**OsmAnd~ 3.3.5 in Android 7.1.2**

> Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

**Offline Map offered with OsmAnd app with OsmAnd Live.**

__*In case of wrong routing:*__

> Tell us whether you have used OsmAnd's in-app offline routing, or any online routing provider like YOURS, OpenRouteService or OSRM.

**Using OsmAnd's in-app offline routing.**

> What routing profile is chosen in OsmAnd app? (car, bike, pedestrian, fastest or shortest)

**Public Transport**

> Please specify as exactly as possible the start and end point of your route by telling us city name and street name so that we can find it via in-app address search easily. Also, a permalink from openstreetmap.org can be helpful.

**Start Point**: Puducherry Bus Stand
**End Point**: JIPMER Hospital
**City Name**: Puducherry, India

I have created a valid bus route via ID and JOSM editor. The stops, platforms and ways are in correct order. I have also checked with OSM Inspector tool and the link for the route I am referring to can be found [here](http://tools.geofabrik.de/osmi/?view=pubtrans_routes&lon=79.8087&lat=11.9376&zoom=15&overlays=ptv2_routes_valid,ptv2_error_,ptv2_error_ways,ptv2_error_nodes) and [here](https://www.openstreetmap.org/relation/9406833#map=15/11.9419/79.8085) is the OSM Relation of this bus route.

I have OsmAnd Live enabled for India Puducherry and I have received the changes (bus stops visible on the offline map). While trying to navigate from any stop to any other stop in this bus route, the calculated route is empty.

**Comment by PrasannaVenkadesh** [comment]
I guess, it is fixed in this merge request https://github.com/osmandapp/Osmand/pull/6617/commits

**Comment by contrapunctus-1** [comment]
You're right - at the moment, PT routing is only updated in the monthly updates.
