### ISSUE TITLE
Feature Request - Search function for Sub Categories in Custom Search

### ISSUE THREAD

**Issue by QuestionsForThose** [osmandapp/OsmAnd#6733]
Creating custom filters is great because it can be fine tuned. For example go to Setting | Search | Caregories | Custom Search | Administrative and then tap on the 3 dots to view Sub Categories. 

Unfortunately it can be difficult to find the item you want. For example I want to find the Japanese "Onsen". Is that in Tourism, Natural, Service, Leisure, Healthcare......

There is no feature for Onsen but there is for Spring adding to the difficulty.

Would be great to be able to search for a feature - type in say Spring and the screen would display in what major category that item can be found - something like...
         Natural
               |____Spring

Alternatively you could provide a category library in the help menu

**Comment by QuestionsForThose** [comment]
In fact now that I look at it the problem is far wider. Onsen is tagged as amenity=public_bath.

How can I search for Amenity?

**Comment by vshcherb** [comment]
Custom search is very technical and instead we should special filters on generic types like public_bath (onsen = yes)

**Comment by vshcherb** [comment]
In that case you will be able to use filters on public bath itself.
