### ISSUE TITLE
No options for navigation with truck

### ISSUE THREAD

**Issue by Spielmops** [osmandapp/OsmAnd#6735]
Osmand 3.3.5 and 3.3.6: If I start navigation for truck and want to change e.g. "shortest way" or "avoid motorway", then I tap on "options". It appears a scrollup with " settings" and "close" - nothing else. And the tap on "settings" does nothing. It should appear the same options-menue as in car or bike.

Spielmops

**Comment by scaidermern** [comment]
Duplicate of #6629 which got closed without a fix :/

**Comment by aknrdureegaesr** [comment]
Maybe someone with the powers to do so could please change the title spelling from "navigatuon" to "navigation"?

**Comment by dmpr0** [comment]
Currently, OsmAnd doesn't have a "Truck" profile for default, but it can be created based on the "Driving" profile all settings should be works fine.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/6629

**Comment by dmpr0** [comment]
We will add the "Truck" profile by default.

**Comment by Spielmops** [comment]
Much too late to answer ...
