### ISSUE TITLE
proposal: visible profile in settings

### ISSUE THREAD

**Issue by Spielmops** [osmandapp/Osmand#6738]
The settings-entry to chose, "which profiles to be visible" in Osmand is now (Osmand 3.3.6) in "developers options", which is normally not active. The choser, "which profile should be the default one" is in "general settings". Why? The choser "which profiles to be visible" should be added to "general settings" and be the first item. That would be logical.

Spielmops

**Comment by sonora** [comment]
Although this is primarily needed for navigation, and it is now very prominently in the first line of the 'Directions' screen in the 3 dots menu.

**Comment by vshcherb** [comment]
It is under development and it will be part of 3.4. Please comment once it is ready.
