### ISSUE TITLE
3D / 2.5D / Birdsview:  Will it come and when will it come?

### ISSUE THREAD

**Issue by hvdwolf** [osmandapp/Osmand#6747]
To repeate the title: "3D / 2.5D / Birdsview:  Will it come and when will it come?"
_(And I simply mentioned the several names for it. If you want to call it something else, I'm OK with it as well. I really don't want to get into that discussion about semantics)_

This has been requested multiple times, both in these github issue tickets as well as in the mailing group.
Victor himself even added a tag to one of the issues [here](https://github.com/osmandapp/Osmand/issues/6307#issuecomment-446390098).

It has also been announced, (or "promised" to some extent,) etc. etc.

So the question is: Can we expect this? And if so: Is there some planned milestone for it and when?
And I'm talking about Android of course.

**Comment by vshcherb** [comment]
As discussed before there is a temporarily build, it is planned but it is more than 2 releases away. We don't assign issues if they are more than 2 releases away.

**Comment by alex9099** [comment]
Any news on this one?

**Comment by Extarys** [comment]
@alex9099 @hvdwolf should come in 4.3 version
https://osmand.net/docs/versions/future-android/

**Comment by hvdwolf** [comment]
Yes, I am already testing it for a week or so. Thanks. It works quite nice and rendering is much faster than in the  "old" versions.
However, when testing in night view in simulation mode it didn't work very fluently. The route pointer was displayed next to the road and rocking back and forth.
It does work nicely though in day mode in simulation mode. 
I tested 2 (short) routes in both conditions.
I will continue testing.
Now: OsmAnd+ Beta 4.3.1 2022-11-29

**Comment by Extarys** [comment]
Simulation mode? Where can I enable that to test too? :D Can't wait for the release.

**Comment by sonora** [comment]
Simulation: Tap action  "_Navigation_" anywhere, then on the route config dialog hit the _Settings_ burton . The _Simulation_ option is at the very bottom of the subsequent _Route settings_ (formerly called _Route options_) screen.
