### ISSUE TITLE
OsmAnd Telegram: OsmAnd won´t open when tapping on a contact

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6748]
On Android 5.0.2, when tapping on an active contact sharing location to you (in the Live now section), OsmAnd won´t open. This is not reproducible on Android 8 devices.

**Comment by Chumva** [comment]
Fixed https://github.com/osmandapp/Osmand/pull/7017/commits/91866870048f46b4aec642ea3661ae8d1048e844
