### ISSUE TITLE
Car navigation ignores bike barrier

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6753]
Start point: Lat. 45.20119 Lon. 5.75817
End point: Lat. 45.20267 Lon. 5.75457
Location of the bike barrier: Lat. 45.20215 Lon. 5.75576

![image](https://user-images.githubusercontent.com/40493090/55170058-9049de00-517e-11e9-80f8-1d79738d0eaf.png)

**Comment by scaidermern** [comment]
This is the barrier in question: https://www.openstreetmap.org/node/4422652845. It is tagged as `barrer=cycle_barrier`, `bicycle=yes`. It clearly disallows car traffic.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-resources/commit/4852c44b4896d9083521926246f17584c54fed80

**Comment by scaidermern** [comment]
Caused by the changes introduced with #5170 and #6530.

**Comment by kreuzschnabel** [comment]
Same here. Requesting a car route from https://osm.org/go/0Dew3Gkr9?m= to https://osm.org/go/0Dew3HO2X?m=, OsmAnd takes the direct line via the footpath and railway crossing. Though the footpath itself is tagged access=permissive, which, strictly speaking, allows for any traffic, the two cycle_barrier should prohibit this. 

OsmAnd+ 3.3.6, maps as of March 1st (same result with latest Live-maps).

--ks

**Comment by aceman444** [comment]
@scaidermern is right, bugs like this are fallout from those 2 wrong fixes.
And the fix here at https://github.com/osmandapp/OsmAnd-resources/commit/4852c44b4896d9083521926246f17584c54fed80 is again wrong, or just incomplete, it solves cycle barrier (in the wrong way), but not other impassable barriers.
