### ISSUE TITLE
Two many duplicate platforms within

### ISSUE THREAD

**Issue by 532910** [osmandapp/Osmand#6763]
https://www.openstreetmap.org/node/3400447897
https://www.openstreetmap.org/node/3380839918
![image](https://user-images.githubusercontent.com/14617699/55296478-bc858900-5422-11e9-92c2-2f6edb4f0cba.png)
![image](https://user-images.githubusercontent.com/14617699/55296477-b8596b80-5422-11e9-959a-881600afb8ec.png)

**Comment by vshcherb** [comment]
Fixed in 3.3.7

**Comment by 532910** [comment]
I confirm it's fixed. Thank you!
