### ISSUE TITLE
gpx recording stops when screen switched off in new versions

### ISSUE THREAD

**Issue by hvdwolf** [osmandapp/Osmand#6766]
Motorola G5-plus, Android 8.1.0 OsmAnd 3.3.x

Since the option to make OsmAnd a  "device admin app" has been removed, the gpx tracking stops when I switch off the screen.
When hiking I want to record my track, but I do not need to see my screen so I switch it off.
Then the tracking stops until I switch on the screen again.
This is really an annoying bug.
In the mean time I tried other tracking apps and they simply continue tracking with the screen off, and they are not device admin app either.
I did check whether the app is in battery optimize mode, but it is definitely not.
 

Please repair this bug.
It makes OsmAnd unusable for me.

**Comment by sonora** [comment]
Areyou sure you are  not experiencing #5255? For me it has nothing to do with OsmAnd versions or device admin, I simply see this on all my Android 7, 8, and 8.1  devices. But e.g. Android 4.4.x devices work flawlessly, even with latest release and latest nightlies.

**Comment by hvdwolf** [comment]
All my track recordings are on 10 seconds, so the 30 second wake_lock should not be an issue.

But even so, the android permission for the wake_lock is  `<uses-permission android:name="android.permission.WAKE_LOCK" />`
maybe in combination with
`<uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS"/>`

Both have been enabled in the AndroidManifest.xml of OsmAnd.
However, **this wake_lock permission is disabled on my phone for OsmAnd and I can't enable it.**
(even though you can consider this as a "not desirable"  approach.)
If OsmAnd can't use them anymore, why are they still in?

Note that I do not want the 
`getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);`
I want the screen to switch off.

W.r.t. tracks which do not seem to be recorded properly, but do have all points: I did see that as well on previous versions and can indeed confirm that all points were recorded in those previous versions even though the "live track" on screen didn't show them.
But no longer in these new 3.3.x beta versions. It shows 3-4 points (or so) and it has captured 3-4 points.
What I didn't do so far is uninstall and do a fresh install. I just did that (and forgot to save my tracks :( ).
I will try again.

**Comment by hvdwolf** [comment]
Like I mentioned: I unistalled OsmAnd and reinstalled OmAnd.

Now it works fine. I do not know what it was, but it is solved.
