### ISSUE TITLE
OsmAnd shows only one bus in Public transport mode

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#6772]
When I choose **Public Transport** mode, OsmAnd offers only one bus route, although several routes exist (Google maps shows a lot of alternative direct routes).

![image](https://user-images.githubusercontent.com/9047168/55469498-43a14f80-5623-11e9-9c73-bd7b29dae797.png)
In this example, I saw only G2 route.

**Comment by vshcherb** [comment]
The description is not clear and it is not clear whether the data is correct or not.

**Comment by raindropsfromsky** [comment]
> The description is not clear and it is not clear whether the data is correct or not.

Actually I would like to know how OsmAnd collects this bus timetable and route data.
Then I can check whether the database itself is faulty.
If so, I will contact the bus agency in Bangalore.

**Comment by vshcherb** [comment]
The data is in OpenStreetMap, you can check our blog article how we collect & process data from OSM
