### ISSUE TITLE
Support traffic_signals:direction

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#6774]
OsmAnd has a penalty for traffic signals. However not every traffic signal applies to the current driving direction. Without support for `traffic_signals:direction` OsmAnd will apply too many penalties in areas where this tag is used heavily.

Currently `traffic_signals:direction` is [used](https://taginfo.openstreetmap.org/keys/traffic_signals:direction) about 86k times.

Related issues: #6539, #3368, #2737, #2625.

**Comment by vshcherb** [comment]
+ stop sign and + give_way signs

**Comment by OpenSourceForEver** [comment]
It would be nice to support speed cameras direction. Although the relationship has one "from" and one "to" nodes, OsmAnd announces speed cameras in both directions.

**Comment by aceman444** [comment]
Please do not mix speed cameras into the issue as they are different beast (please open new issue).
Supporting give_way and stop signs would be a great start.
Also there is an issue filed to make OsmAnd detect the direction automatically (to the nearest junction) when the direction=* is not given.

**Comment by vshcherb** [comment]
All pul requests merged so it's time to test hat it works correctly
