### ISSUE TITLE
Flooded areas in Ahvenanmaa / Åland island 

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6776]
https://www.openstreetmap.org/search?query=60.2336615%2C19.7580537#map=11/60.2272/19.7630
![image](https://user-images.githubusercontent.com/40493090/55484556-5d499380-5631-11e9-98f3-33fb3eef8c93.png)
![image](https://user-images.githubusercontent.com/40493090/55484565-633f7480-5631-11e9-81ee-8636d38fb3b0.png)

**Comment by vshcherb** [comment]
Map is flooded because of the bay - https://www.openstreetmap.org/relation/9048256#map=6/62.611/21.925

**Comment by vshcherb** [comment]
So either this bay should be excluded for rendering or Aland should be properly processed as island

**Comment by vshcherb** [comment]
Or probably Pohjanlahti - Bottniska viken should not included Aland
