### ISSUE TITLE
Support direction=forward and direction=backward in stop sign and give_way signs

### ISSUE THREAD

**Issue by Prusaker** [osmandapp/Osmand#6778]
It possible to used tags direction=forward and direction=backward in stop sign and give way signs ([used](https://taginfo.openstreetmap.org/tags/direction=forward#combinations) about 73k and 121k times) when calculating the route (set penalties depending on the direction of the road sign)?

**Comment by njohnston** [comment]
Possible duplicate of #4836.

**Comment by OpenSourceForEver** [comment]
I think this is planned. https://github.com/osmandapp/Osmand/issues/6774

**Comment by vshcherb** [comment]
Merged into #6774
