### ISSUE TITLE
Issue with switching from "Address A - Address B" to "My position - Address B"

### ISSUE THREAD

**Issue by oxxm** [osmandapp/Osmand#6780]
How to reproduce: 

Step 1: set up a route from a random address A to another address B
Step 2: wait until the route is calculated
Step 3: tap on "Address A" and switch to "My Position"

Actual behaviour: "Address A" is not replaced "My Position"

Checked with OsmAnd 3.3.6

**Comment by vshcherb** [comment]
Looks like already fixed

**Comment by oxxm** [comment]
The issue still exists in 3.3.8

**Comment by vshcherb** [comment]
My location could not be selected and doesn't change Adress A, B  if location could not be found!
