### ISSUE TITLE
Navigation ends about 100m far from destination

### ISSUE THREAD

**Issue by oxxm** [osmandapp/Osmand#6781]
As described in the title, OsmAnd announces that destination is reached sometimes about 100m far away from it and ends navigation.

**Comment by naoliv** [comment]
Maybe you just need configure it here?
![](https://user-images.githubusercontent.com/982338/55654129-eb0ab780-57c6-11e9-8761-f93db5f9c7ac.png)

**Comment by contrapunctus-1** [comment]
Didn't know that was configurable. Can we please have 'In the last meters' as the default?

**Comment by scaidermern** [comment]
> Can we please have 'In the last meters' as the default?

This is probably too late since you would have to stop immediately to not miss your destination.

How about announcing the remaining distance up to the destination? Then it becomes clearer that you still have to drive/walk a few meters.
