### ISSUE TITLE
Issues with the Kurdish language

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/OsmAnd#6782]
Osmand has a problem with the Kurdish language, namely, with the following characters (پ، چ، ژ، ڤ، گ، ڵ، ە، ۆ، ێ). 
The app does not connect those letters with the letters that come before or after them when they come in words. 
The example of the mistake is on the screenshot. The correct way is (دێگەڵە). 
![image](https://user-images.githubusercontent.com/40493090/55635114-99632c80-57c8-11e9-91ac-6faf43a4c35e.png)

**Comment by ivanPyrohivskyi** [comment]
<img width="500" src="https://user-images.githubusercontent.com/1040293/150677871-1726fc94-e0d8-49d6-86f5-8e1221704e7b.png" />
