### ISSUE TITLE
Voice instructions lost during GPX navigation

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6796]
While navigating a GPX created using brouter-web, turn-by-turn voice instructions disappear 50-100 km after a start point. 
In the attached GPX the last turn instruction is shortly after "Herdern".
https://www.dropbox.com/s/i8uzvq1xhw720oc/Kloten%20nach%20Hohentengen.gpx?dl=0

**Comment by vodie** [comment]
There is an error in the offset numbering off the turn instructions by BRouter. The numbering is startet again at every intermediate point. This is fixed in the next BRouter version.[https://github.com/abrensch/brouter/commit/02b82020014e57841976f7dfadec3ba99526fc4a](url)
