### ISSUE TITLE
Privacy issues with profile data on SD card

### ISSUE THREAD

**Issue by bugzillus** [osmandapp/Osmand#6797]
In case the external SD card is formatted as mobile / removable storage (FAT32) and not as encrypted/bound to the device, the SD card can be removed and read out by any attacker, thief, or finder of a device.

The unencrypted, XML-style Osmand profile data easily reveals the saved and used locations of the device owner: home and work location, favourite places, tracks, and potentially even data of related people. This is like address badges on your keys and not compatible with EU privacy law (GDPR).

So, Osmand should retain privacy-related profile data (locations history favourite places, home and work locations, settings, GPX tracks, navigation settings and cache) separate from large "bulk" data (maps, sounds, fonts, ...) and keep privacy-related information in internal storage and/or let the user choose where to save profile and map / bulk data independently.

**Comment by vshcherb** [comment]
Even though the issue you describe exists, I think there is no connection to EU privacy law (GDPR) cause this data is solely stored on user device and has no connection OsmAnd company. Software provided AS IS and it is hard to predict how it will be used on user device, so user should take separate precautions to avoid leak i.e. don't install 3rd party apps, use special security. 

I will vote against this issue cause it seriously harms usability between apps which user can control.

**Comment by bugzillus** [comment]
Thanks, but my main point was: Having personal information like names and home locations stored unencrypted and bound to the same directory if storage of the maps on external SD card is used, is a major threat in case of robbery or loss or unauthorized access to the SD card, especially as the user usually does not know that this information stored in plain text on SD card. Thus, the mandatory link between map storage and user data should be removed.

> I will vote against this issue cause it seriously harms usability between apps which user can control.

This I don't understand, neither technical (in terms of Android common practice or app interfaces) nor functional: The user is asked where to store the *maps*, not the *personal data* that is entered into Osmand. 

> I think there is no connection to EU privacy law (GDPR) cause this data is solely stored on user device and has no connection OsmAnd company.

GDPR and most other privacy laws cover all handling, storage, and protection of personal data, not only internet transmission. If a user saves data within favourites that reveals personal data of other people (e. g. name, geo location, relationship, reason of visiting, medical attributes of these people) within Osmand, and Osmand saves this on an exposed SD card without knowledge or consent of the user, there is indeed a GDPR issue that could be easily avoided, no matter if the Osmand company or the user could be legally held responsible for it. If the Osmand company knows about the issue but does not address it, this would be irresponsible to me.

**Comment by vshcherb** [comment]
There are "Data collectors" and "Data processors" in that case the phone is "Data collector" and "Data processor" cause the data doesn't leave the phone, so it is responsibility of the phone owner. OsmAnd company didn't take that data and didn't store, so it could not be responsible for it. Our Privacy policy only covers information which is processed in any form by the servers owned by us. 

Anyway I need to consult but it would be very stupid to make all Editors with Save As functionality legally responsible how the data stored. 

This issue is anyway doesn't make sense since Android 7 when applications don't have permission to access all files on the sd card.
