### ISSUE TITLE
Confusing or broken UI for following GPX track in reverse (workaround exists)

### ISSUE THREAD

**Issue by mikehgentry** [osmandapp/Osmand#6804]
I use QMapShack ( https://bitbucket.org/maproom/qmapshack/wiki/Home ) to design my bike routes on my computer, and have OsmAnd set to use Brouter as a routing engine.

If a track isn't a circuit, I tend to design it as a route from A to B, load it into OsmAnd as a GPX track, start navigation mode and then select it in "Displayed tracks". When I want to get back from B to A, I intuitively expect to be able to select it in "Displayed tracks", hit the button to swap start and end point, and have it follow the track back again. This doesn't work - sometimes the 'start' button is greyed out; sometimes I can hit it, but it only half seems to enter navigation mode (e.g. there's no icon for next turn in the top left corner); if I can persuade it to start navigating (not entirely sure what I did, but it happened at least once) it seems to route near the track (possibly a coincidence), but doesn't follow it precisely.

If, however, I hit 'Start' instead, then hit the navigation button, then hit the swap start / end point button, then hit continue, everything seems to work as expected.

OsmAnd+, 3.3.7, Moto G5

**Comment by scaidermern** [comment]
There is a separate option for reversing a GPX route.

- Tap the navigation button to open the navigation widget
- Select the GPX track from the list of displayed tracks (or open options to choose a GPX track if your track is not already displayed)
- Open options and choose "Reverse GPX direction" and maybe "Pass salong entire track"

![photo_2019-04-10_11-49-38](https://user-images.githubusercontent.com/1040784/55869509-ea876d80-5b86-11e9-8f4e-69d4e2d42386.jpg)

**Comment by vshcherb** [comment]
Should work with Reverse GPX

**Comment by Bubu** [comment]
For anyone as confused by this as me: the reverse toggle doesn't seem yo appear in custom routing profiles. At least in my brouter profile it was missing. Works as expected in the default osmand bike navigation.
