### ISSUE TITLE
Routing issue

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6808]
The part of the D83 road is always avoided. 
From 47.682, 6.9416 to 47.7086,7.0067
(https://www.openstreetmap.org/#map=14/47.682/6.9416)
![image](https://user-images.githubusercontent.com/40493090/55938508-35b38600-5c44-11e9-9162-6c968fb18ef6.png)

From 47.682, 6.9416 to 47.6937,6.9751
![image](https://user-images.githubusercontent.com/40493090/55938518-3c41fd80-5c44-11e9-9d44-5b873f43448e.png)

**Comment by naoliv** [comment]
The problem is this way https://www.openstreetmap.org/way/615285558 which has a wrong `oneway=yes` in a part where it should be `oneway=no`

**Comment by quax2712** [comment]
I corrected it in OSM
