### ISSUE TITLE
Unable to parse gpx with unencoded & in name field

### ISSUE THREAD

**Issue by james2432** [osmandapp/Osmand#6809]
![Screenshot_20190411-045218](https://user-images.githubusercontent.com/498547/55944303-db142d00-5c37-11e9-8f6d-c611d22a94bf.png)
Line 334:
  `  <wpt lat="45.4801558" lon="-75.5196618"><name>Place D'Orleans - Park & Ride 4A</name></wpt>
`
[missing.gpx.txt](https://github.com/osmandapp/Osmand/files/3067813/missing.gpx.txt)

**Comment by njohnston** [comment]
What produced the GPX file? Including a bare & character means that the file is not well-formed XML.

**Comment by james2432** [comment]
Pic4Review

**Comment by njohnston** [comment]
I'd suggest contacting the Pic4Review developer then, and point out the bug. Be sure to mention that the GPX file isn't even well-formed XML. (For example, LibXML's `xmllint` fails on it, as expected.)

**Comment by james2432** [comment]
closing here, opening in pic4review. Doesnt follow xml specification
