### ISSUE TITLE
English wikipedia is not english

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#6814]
Iceland:
![image](https://user-images.githubusercontent.com/1042025/55955050-a5376e80-5c60-11e9-881b-8c18e3491ad6.png)
![image](https://user-images.githubusercontent.com/1042025/55955081-b2545d80-5c60-11e9-9c69-6ac126ffcac3.png)

**Comment by alyonapinchuk** [comment]
The same issue is with Wikipedia German.
