### ISSUE TITLE
Search for chimney

### ISSUE THREAD

**Issue by HubMiner** [osmandapp/Osmand#6817]
Please add support for tag man_made=chimney

It is a valid tag: 
https://taginfo.openstreetmap.org/tags/man_made=chimney

**Comment by xmd5a2** [comment]
Added several years ago

**Comment by HubMiner** [comment]
Perhaps I reported a wrong issue.  I am not able to find chimneys in OsmAnd.

Test:
1) Zoom in to Indianapolis, Indiana (there are 4 chimneys)
2) Confirm one is there for a long time (not recently added)
https://www.openstreetmap.org/way/385649948#map=19/39.78540/-86.08974
3) Zoom in to the same area with OsmAnd
4) Try to search: chimney
Results:
a) No type=chimney found.
b) For a saved search, there is no "chimney" option under "man_made".

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/8ec2cabf332cec1f39a6a991cfc6b3c6a9a4b91c
