### ISSUE TITLE
Incorrect bicycle routing

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6823]
Start https://osmand.net/go.html?lat=51.19827&lon=11.864748&z=12 
End https://osmand.net/go.html?lat=51.198235&lon=11.96675&z=15
Expected Track:
Langendorfer Straße => Kreisel Schwedenstein => Friedrich Straße => 
Kreisel Niemöllerplatz
![image](https://user-images.githubusercontent.com/40493090/56085065-f3f22d80-5e45-11e9-8f72-c0122e9c2fe9.png)

**Comment by Zahnstocher** [comment]
Probably OsmAnd misinterprets bicycle=no on highway=crossing:
https://www.openstreetmap.org/node/3884698463
https://www.openstreetmap.org/node/3884694533

**Comment by quax2712** [comment]
I had a similar problem on another street. An intersection or a connecting route influences (I think in Special Situation) the other way object. The way to choose does not have this property. I am shure in tis case it is the TAG bicycle=no from pedestrian Crossing.

**Comment by vshcherb** [comment]
@Zahnstocher what do you mean,  should it accept "bicycle" v="no" on highway crossing?

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-resources/commit/fdcd5c2e780b797471eccf29c32cfdb9d720c7e4
