### ISSUE TITLE
Time problem on bus routes (public transport navigation)

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/Osmand#6827]
Sometimes, time on bus routes is wrong. I think problem is with motorways and trunk roads. 

Examples:
From https://www.openstreetmap.org/#map=19/40.63313/-4.00485 to https://www.openstreetmap.org/#map=18/40.43505/-3.71884 there are some bus routes that takes about 30 minutes, (by car it takes 25 minutes according to Osmand with a similar route) however Osmand shows that these bus routes takes 66 minutes.
Bus routes mentioned are: https://www.openstreetmap.org/relation/4422724 https://www.openstreetmap.org/relation/2684575 https://www.openstreetmap.org/relation/5581608 https://www.openstreetmap.org/relation/5595416#map=11/40.5646/-3.8813

From: https://www.openstreetmap.org/#map=19/40.64132/-4.00552 to https://www.openstreetmap.org/#map=19/40.70233/-4.00507 there is a bus route that makes the same route as a car but Osmand calculates that car takes 6 minutes and bus takes 14 minutes. Mentioned bus route is: https://www.openstreetmap.org/relation/5580303

I think time on other type of roads (streets, tertiary...) is ok because time on other sections of the mentioned routes are ok.

**Comment by vshcherb** [comment]
the bus speed is averaged to https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml#L2002 -  30kmh which is slow but it gives very good estimation in cities. Now we can't distinguish if it is a speed bus or it drives by motorway so there is no possibility to change it. Also bus is usually 20% + stop times slower than car.

**Comment by OpenSourceForEver** [comment]
"Also bus is usually 20% + stop times slower than car." 
Yes but examples I mentioned bus and car follow the same route and there is no bus stops and the difference is bigger than 20%.

I think the problem is, as you mentioned, bus speed that should be different depending on road type

**Comment by OpenSourceForEver** [comment]
Maybe the solution would be to establish bus speed depending on speed limit of the road. Bus speed would be 80% of road speed limit if this limit is 90 km/h or above  and 100% of speed limit if the limit is smaller than 90 km/h.

**Comment by vshcherb** [comment]
We need another fix for that, we need to save travelTime between stops for long routes with high speed - https://github.com/osmandapp/OsmAnd-resources/commit/1ccd89cd014871bd41d2fb197a399d5ed2f9df89#diff-cefa2cd533121fb882e4a5a6da428add4af398b34fcabd656f55dbf58e28cf61R436

**Comment by RZR-UA** [comment]
It is 32 minutes now with the proposed improvements.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/bfe500a1-dbaf-4b7a-84f4-4666ae1032cc"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
We need to start proper calculation or approximate calculation for the route during map preparation, later this information could be improved with proper intervalTime from GTFS
