### ISSUE TITLE
Pedestrian routing issue

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6832]
A pedestrian route is calculated using a road, although there is a footpath nearby.
Start 50.47623   30.49704 
End 50.47753   30.49662
![image](https://user-images.githubusercontent.com/40493090/56221602-351b5500-6073-11e9-8355-727069e7dfdd.png)

**Comment by katerynakocherhina** [comment]
A part of the route is still using the road instead of the footpath. 
![image](https://user-images.githubusercontent.com/50198677/57075913-ed423200-6cf0-11e9-8935-df029f995981.png)
