### ISSUE TITLE
Rendering bus stops

### ISSUE THREAD

**Issue by remontees** [osmandapp/Osmand#6833]
Hello!

Please excuse me if a issue has already been opened on this subject. For the last month, the bus stop displays have not worked. The station/bus stop pictogram is no longer displayed as before. If I try to click on the remaining pictogram, the app freezes and the screen with all the transport lines that stop at this station doesn't appear. This is a pity because this feature was very useful for me.
![Screenshot_2019-04-16-17-08-19-574_net osmand plus](https://user-images.githubusercontent.com/1620974/56228085-423a4300-6077-11e9-9690-beced60a6ae4.png)
Before entering an issue, please read the information below.
I use OsmAnd~ v. 3.2.7 with Android 8.1.0. I use of course the maps on download.

**Comment by OpenSourceForEver** [comment]
Try updating Osmand. Last version is 3.3.7

**Comment by remontees** [comment]
Oh sorry, it seems working with the last version.
Thanks a lot for spending me your time!
