### ISSUE TITLE
Error in poi_types.xml for name=brushless_no for carwash

### ISSUE THREAD

**Issue by DFyson** [osmandapp/Osmand#6836]
In poi_types.xml, [line 1545](https://github.com/osmandapp/OsmAnd-resources/blob/84dd781ab61d07c024c7960e18768c0f447787f5/poi/poi_types.xml#L1545) should be nested inside <poi_additional_category name="brushless">.

**Comment by xmd5a2** [comment]
This is not an error. poi_additional_category is a filter. Filtering by brushless=no is pointless.
