### ISSUE TITLE
Contour lines: text orientation

### ISSUE THREAD

**Issue by wanderfalk** [osmandapp/OsmAnd#6839]
The height level numbers on the contour lines are orientated towards the bottom of the device. For easier interpretation of the map their bottom should always face towards the valley as illustrated in the picture linked below.

https://geolinde.musin.de/fertigkeiten/hoehenlinie3.jpg

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/10005
