### ISSUE TITLE
Itinerary Route details windows - wrong unit for steepness % : km instead of m

### ISSUE THREAD

**Issue by serpico** [osmandapp/Osmand#6840]
What version of OsmAnd are you using, on what device and Android/iOS version?

**OsmAnd~ 3.3.7 from F-Droid, Samsung GT-I9195, Android 4.2.2**

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

**Offline maps**

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.

**France Normandy Apr 1, 2019**

Tell us whether you have used OsmAnd's in-app offline routing, or any online routing provider like YOURS, OpenRouteService or OSRM.

**in-app 

offline routing**

What routing profile is chosen in OsmAnd app? (car, bike, pedestrian, fastest or shortest)

**bike**

Please specify as exactly as possible the start and end point of your route by telling us city name and street name so that we can find it via in-app address search easily. Also, a permalink from openstreetmap.org can be helpful.

**Start https://osmand.net/go.html?lat=49.47198&lon=1.03767&z=15**
**End https://osmand.net/go.html?lat=49.46996&lon=1.03687&z=15**

Tell us your expected routing, and how OsmAnd routes, or add screenshots here.

Once the itinerary is generated, tap the Details button, go to Steepness, while the total distance is 261**m** both  5%...8%: 150 **km** and 9%...12%: 55.0 **km**, also notice the scale on the steepness horizontal bargraph **200000m**

![Screenshot_2019-04-18-19-07-53](https://user-images.githubusercontent.com/1227077/56379067-210c5a80-620f-11e9-88bd-fa6a1dad02b4.png)

**Comment by Chumva** [comment]
Fixed https://github.com/osmandapp/Osmand/commit/2f7bce87cc9bbd00bb977afb6f077635b243f227
