### ISSUE TITLE
Disregard railway platforms as public transport if they don't have 'public_transport' tag

### ISSUE THREAD

**Issue by IgorEliezer** [osmandapp/Osmand#6843]
We have some platforms that public passenger trains don't stop: touristic or preserved train platforms, freight platforms, re-purposed platforms (e.g. railway museums), disused and abandoned platforms. These are tagged with `railway=platform` but not with `public_transport=platform`, however OsmAnd is considering them as public transport elements.

Example:

![image](https://user-images.githubusercontent.com/4673289/56422376-67000780-627d-11e9-9c3b-f7a0dfd4cb85.png)

https://www.openstreetmap.org/way/537898826

Workaround: If the object has at least a roof, it's easy to remove the `railway=platform` tag; it still renders on OsmAnd and CartoCSS as building, as I did with [this touristic train platform](https://www.openstreetmap.org/way/535624873). The issue starts when it's a bare platform: removing `railway=platform` or using `disused:railway=platform` will make them invisible.

**Comment by hakuchi** [comment]
this platform is tagged with `disused:railway=platform` and `railway=platform`
this combination make no sense.
if you delete the `railway=platform` from OSM data the error should be fixed.

You edited this platform many time and you should know, as a user of OSM, that the combination of `disused:railway` and `railway` with the same value make no sense.
If the platform is in use -> `railway=platform`     
If the platform is not in use -> `disused:railway=platform`
A platform cannot be "in use" and "not in use" the same time.

The problem of OsmAnd is that `railway=platform` and `public_transport:platform` are using the same "bus" icon.
OsmAnd should use a similar symbol for `railway=platform/halt/etc.` as uses on `railway=station`.
A `railway=tram_stop` have its own icon, but not the `railway=platform`

**Comment by IgorEliezer** [comment]
> if you delete the railway=platform from OSM data the error should be fixed.

Well, as I pointed out:

>  (...) The issue starts when it's a bare platform: removing railway=platform or using disused:railway=platform will make them invisible.

I'm aware that combining `a=b` with `lifecycle:a=b` doesn't make much sense. The issue is that many times I used the life cycle scheme the feature stopped rendering, even if the feature was an important visual landmark, such as, an industrial plant, abandoned multi storey building, railway structures etc. I tried many attempts to get something satisfactory.

It's easy to get around the problem when it comes to, say, `building=yes + amenity=school`: I can use `building=yes + abandoned:amenity=school`. But if the only tag is `building=yes` (in analogy to having only `railway=platform`) the building vanishes if I use `abandoned:building=yes`.

I could use `railway=platform + disused=yes` but it is discouraged; or `railway=platform + disused:railway=yes` following [building=ruins and abandoned:building=yes scheme](https://wiki.openstreetmap.org/wiki/Key:ruins) but this doesn't sort out the issue of mapping something "not in use" as "in use" -- you have a point here. There's still a trick that some people use: map it as `highway=footway` area (it's a walkable area, after all), but it's an ugly solution in my opinion.

Back to OsmAnd, as you said, _"[t]he problem of OsmAnd is that railway=platform and public_transport=platform are using the same "bus" icon."_ So my initial question was why OsmAnd should flag a feature as public transport if it doesn't have a `public_transport` tag? Probably there would be a feature which doesn't have `public_transport` tag but still needs to be flagged as such. If this is not true, why not to restrict the public transport icon only to features with `public_transport` tag?

**Comment by xmd5a2** [comment]
There are thousands of objects with railway=platform and without public_transport=platform that are valid railway platforms. See http://overpass-turbo.eu/s/JyO
So disregarding railway=platform tag as you propose is not an option.
More adequate solution is to add support for disused:railway=platform and/or similar tags.

**Comment by IgorEliezer** [comment]
> So disregarding railway=platform tag as you propose is not an option.

No problem. I'm using `disused:railway=platform + highway=footway` since they became a mere walkable surface around/by the old railway stations. Thank you. :)
