### ISSUE TITLE
Hide route relations on nodes in cycle networks

### ISSUE THREAD

**Issue by footils** [osmandapp/Osmand#6844]
I would like to hide the text labels for route relations, that are rendered over nodes in cycle node networks, when display of cycle routes is enabled. Currently all route relations are rendered in addition to the node number (which **should** be rendered!). Cycle networks in Germany typically have a lot of route relations, so this will make the map unreadable in certain zoom levels. 

Here's a screenshot of the current Osmand 3.3 showing a typical map in Germany (Node [267535048](https://www.openstreetmap.org/node/267535048#map=21/50.95612/6.97429&layers=CD) in Cologne is shown among others)
![osmand-D12ZE-EX0AI_bUV](https://user-images.githubusercontent.com/279036/56454344-73549500-634f-11e9-8733-c0a86ccd9382.jpg)

Instead only the node number should be displayed, as it is on osm.org:
![osm-D12Z42qXQAAjzcJ](https://user-images.githubusercontent.com/279036/56454343-70f23b00-634f-11e9-99e2-e24a2dea0672.jpg)

Hiding network relations on nodes could be an option in the Settings, but actually I fail to see any use at all in displaying the relations as text labels. If cycle routes are rendered, the relations are already visible as lines between nodes, so labels are superfluous.

**Comment by xmd5a2** [comment]
Fixed
![Screenshot from 2019-04-22 15-09-27](https://user-images.githubusercontent.com/5829014/56499791-a5612500-6510-11e9-91f2-e62bd8b9a45c.png)

**Comment by footils** [comment]
Brilliant! I edited my render.xml manually like this and it works already. Thank you a lot.
