### ISSUE TITLE
Bug with online maps with 512px tile size (sqlitedb)

### ISSUE THREAD

**Issue by nnngrach** [osmandapp/Osmand#6847]
I noticed a bug that occurs when you add to the Osmand sqlitedb file with the source of the online map which has a tile size of 512 pixels. Large tiles are not displayed correctly. Here's a screenshot.

https://yadi.sk/i/JCIS7IFR_cjUYQ

At the same time, there is no such problem with 256-pixel tiles.

https://yadi.sk/i/wPJLJqoIjLWWRw

Here are two sqlitedb files that load the same map in different sizes.

https://yadi.sk/d/Jt0RqRua4NAN5Q
https://yadi.sk/d/D62Beglfs5ZXkg

(OsmAnd 3.3.7, Android 7.1.2)

**Comment by gpsvisualizer** [comment]
You can add "&px=256" to the Strava tile URL to get 256px versions. It doesn't fix OsmAnd's bug, but it may be a workaround for your specific case.

**Comment by nnngrach** [comment]
Thanks. But the idea was to fix this bug. The fact that the maximum zoom Strava maps - 15. It's quite small.  

And so I want to get it at the highest possible resolution, so that there are no artifacts when approaching. By the way, it is interesting that when you create a card using *.metainfo file this a bug does not occur. It is exist only when working with *.sqlitedb files.

**Comment by gpsvisualizer** [comment]
Yes, I noticed that although you can't "Define/Edit" a map source with 512px tiles, you can do it by manually editing the .metainfo file.  I suppose the lack of an interface for that is a separate but related bug.

**Comment by vshcherb** [comment]
fixed for sqliteonline tile source
