### ISSUE TITLE
Minor issue : wrong translation German

### ISSUE THREAD

**Issue by cepesko** [osmandapp/Osmand#6849]
Since im not a programmer and not familiar with github, I'd like to commit to the following file:
/OsmAnd/res/values-de/phrases.xml
line 1905 
name="poi_shelter_type_rock_shelter">Steinschlagschutz</string>

 "Steinschlagschutz" means protection from falling rocks whereas a cave-like rock is meant (https://wiki.openstreetmap.org/wiki/Key:shelter_type). 
Thanks for replacing line with:
name="poi_shelter_type_rock_shelter">Felsüberhang</string>

**Comment by hakuchi** [comment]
thx
fixed
should be updated in the next version

**Comment by cepesko** [comment]
That was fast. Thanks.
