### ISSUE TITLE
Feature request: Download all regions button

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#6854]
# Review 
- [x]  Don't show country name in for the maps: "Germany Bavaria"  > "Bavaria"
- [x] Add "Russia", "Canada", "USA".
# ToDo
- Skip Berlin by Bbox (if Brandenburg)
@vshcherb 
We countries and subregions we should show the group item with all maps of specified type if that map is not present in regionwide maps 

Example: 
> Germany in Regionwide maps section we should show:
- Wikipedia - 12 Files , Total size XX MB
- Standard Map -12 files, Total size XX MB
... 

-----------
Add button to the Download Map sections for downloading all regions (different type) maps by one tap.

**UI, [Figma](https://www.figma.com/file/TdY6CMX2JVicapzJPd91eU/Download-maps?node-id=1%3A118)**
![Снимок экрана 2020-12-01 в 16 02 45](https://user-images.githubusercontent.com/9365308/100750417-acd7f800-33ee-11eb-81d4-da1057386d68.png)

**Comment by wehkah** [comment]
+1 here!

It would also be nice, if a region would be marked as downloaded (green symbol), when each sub-region have been downloaded.

**Comment by nazar-kutz** [comment]
PR: https://github.com/osmandapp/OsmAnd/pull/10855

**Comment by Chumva** [comment]
This should be added here - https://github.com/osmandapp/OsmAnd/pull/10917.
