### ISSUE TITLE
Coordinate in DD°MM'SS"n/s/w/e format

### ISSUE THREAD

**Issue by sorcrosc** [osmandapp/Osmand#6858]
I would like to have a coordinate format of this type:
45° 23' 22'' N
11° 33' 29'' E

This request comes from my friend, an ambulance driver in Italy who also uses Osmand as an aid in his work. It is common for him and his colleagues to use this format when they need help from other vehicles like the emergency helicopter.

Thanks

**Comment by vshcherb** [comment]
I think we have such format in general settings and it is called DD'HH'MM.MMM, you don't need to specify after comma for minutes if you don't need.

**Comment by sorcrosc** [comment]
I saw that format, it looks like this:
Lat +/-45:23:22.12345 Lon +/-11:33:29:12345

I too find it difficult to read. I feel much more confident with what I propose, in my experience the more common mode to express coordinates (I think at Wikipedia articles right now)

The part after the comma is not the first problem, however I think it is a precision not needed by most Osmand users, maybe one digit is enough for all.

**Comment by vshcherb** [comment]
Got it. We need to make nicer formatting especially because this format was driven to be input by user, so it has simple characters to type. But it is not good for display

**Comment by sorcrosc** [comment]
Coordinates look good with the latest update.
Thank you!
