### ISSUE TITLE
Bicycle routing: huge penalty for entering cycleway

### ISSUE THREAD

**Issue by Famlam** [osmandapp/Osmand#6861]
OSM: 3.3.7 Unlimited
Android 5.1, LG
Offline map of The Netherlands, dated April 1 2019
Offline bicycle routing, balanced routing profile

1. Navigate (using the bike and balanced routing) from [here](https://www.openstreetmap.org/node/634093972) to [here](https://www.openstreetmap.org/node/1713323160) (i.e., [the offline-OSMAnd equivalent of this route](https://www.openstreetmap.org/directions?engine=fossgis_osrm_bike&route=51.8341%2C5.8694%3B51.8269%2C5.8686#map=16/51.8304/5.8694))
2. Notice the routing:
 a) Avoids the Heyendaalseweg hugely
 b) Prefers a long route over a footway rather than a few meters over a platform

![Screenshot_2019-04-23-22-20-40](https://user-images.githubusercontent.com/1315520/56613414-e04d8080-6616-11e9-97c4-aa1e6be89e51.png)

I believe this is the result of two issues in routing.xml:
a) The Heyendaalseweg consists of fragments of cycle tracks and lanes. Every time you leave the "lane"-part, you'll get a transition penalty of "50s" (70-20).
b) The speed on a platform is "2 km/h", whereas on a footway (where I wouldn't be allowed to cycle and thus have to walk, I can suddenly ~walk~ run "15 km/h". More realistic would be to use 2 for both, as for both I would have to walk with my bicycle at hand. 

Suggestions:
a) Decrease the transition penalty of a cycleway to 20s, equal to tertiary roads). 
(On a side note: which also makes me wonder: for a cyclist, is there a true transition time for moving from primary to secondary to tertiary to residential (etc), compared to just turning on same road types? Obviously, pedestrian roads require you to slow down, footways even more, but I don't have to slow down if I go from primary to residential, this only becomes relevant at living_streets and "lesser" road types)
b) Decrease the running speed on a footway to walking speed (or the priority to something way below the current 0.75)

**Comment by Famlam** [comment]
(Perhaps good to note: probably a comparable issue as a) will occur for unclassified roads, which also get a penalty of 70s. I don't have a real life case for this though)

**Comment by xmd5a2** [comment]
https://github.com/osmandapp/OsmAnd-resources/commit/af1208260b8b29f8b41e8b707977270967ccd3d4
