### ISSUE TITLE
Map rendering issue - Scotland

### ISSUE THREAD

**Issue by Boothy99** [osmandapp/Osmand#6862]
OsmAnd+ 3.3.7
Various android devices - same issue.
Offline Map of Europe / United Kingdom / Scotland - 1st April 2019 map.

When zooming out (from Max Zoom to ~ 11 to 12 clicks out), certain areas are rendered poorly with an overall blue background. Land / water features become indiscernible. One in particular here (around the Caledonian canal, Scotland) -
Lat 57.09087 Lon -4.74598

The issue remains in sight at the above mentioned zoom level for a reasonable distance arond this area, then reverts to correct view unless you scroll back again. Zooming above or below these levels appear as expected. Removing Hillshade, &/or Contour Lines has no effect on the issue.

Hopefully a temporary glitch until the next update? I have deleted the map, restarted OsmAnd+ & reinstalled the map, with the same issue remaining.

![SmartSelect_20190424-091107_OsmAnd+](https://user-images.githubusercontent.com/13983995/56643753-1f5cef80-6672-11e9-8610-0ce185792053.jpg)

**Comment by xmd5a2** [comment]
Can't reproduce

**Comment by vshcherb** [comment]
Probably gone with new maps

**Comment by Boothy99** [comment]
Sorry for late reply .... was away in Scotland :-\ 
Issue has resolved once new maps were uploaded.
Thanks for checking this out.
