### ISSUE TITLE
Multiple non-existent roundabout exits and unnecessary circumnavigation

### ISSUE THREAD

**Issue by Aiurek** [osmandapp/Osmand#6863]
Lenovo Moto G4 plus, Android 7.0
OsmAnd+ 3.3.7, released 2019-03-29
May style: OsmAnd
Map: Morocco (Apr 1, 2019) (Standard map + Contour lines + Hillshades)
Navigation service: OsmAnd (offline)

Not sure if this is just a mapping issue in OSM or if it needs to e adressed in OsmAnd:
Navigation tells you to take the 8th exit, although there are only 3 AND unnecessarily it circumnavigates the roundabout before taking the exit.

Location:
https://www.openstreetmap.org/#map=18/30.37185/-9.50460

![Bild1](https://user-images.githubusercontent.com/27865200/56650207-d8c5c000-6686-11e9-8570-65421a672261.jpg)

**Comment by scaidermern** [comment]
Map data looks fine to me.

**Comment by vshcherb** [comment]
With fresh OSM data the turn looks OK, so May maps should be good with this roundabout
