### ISSUE TITLE
Redundant use of ferries in pedestrian routing

### ISSUE THREAD

**Issue by Aiurek** [osmandapp/Osmand#6867]
Lenovo Moto G4 plus, Android 7.0
OsmAnd+ 3.3.7, released 2019-03-29
May style: OsmAnd
Map: Morocco (Apr 1, 2019) (Standard map + Contour lines + Hillshades)
Navigation service: OsmAnd (offline)

Car routing stays on the street, whereas pedestrian routing tells you to take 2 ferries and cross the river twice, which wouldn't make any sense. Is it of any help to add a penalty for ferries in order to avoid such detours?
Cars are blocked for those specific ferry route, but mby it'll bring up similar results for car ferries in other regions.

Location:
https://www.openstreetmap.org/#map=16/48.4296/13.8790

![Bild5](https://user-images.githubusercontent.com/27865200/56663666-ed19b500-66a6-11e9-8479-b62d96235519.png)

**Comment by scaidermern** [comment]
There should be a penalty for taking ferries. A fixed penalty is hard to choose but most ferries don't immediately start their journey if the user reaches them (even if they are present at the correct ferry port). Maybe add a penalty of 10 minutes?

**Comment by vshcherb** [comment]
Agree penalty should be at least 7 min + and it will be enough

**Comment by xmd5a2** [comment]
Issue is not reproducible anymore
![Screenshot_2019-06-10-15-35-00-717_net osmand plus](https://user-images.githubusercontent.com/5829014/59195800-8f2d2800-8b95-11e9-9b2c-e40f2c4c7e28.png)

**Comment by vshcherb** [comment]
Fixed with recent pedestrian changes
