### ISSUE TITLE
Navigation issue with Direction to Kerch

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6868]
Start  56.50302  60.80933
End   56.97247  60.57389
OsmAnd calculates a longer route 
![image](https://user-images.githubusercontent.com/40493090/56664585-07f12700-66b1-11e9-97bf-acf5de4d1bb2.png)
 
Start 45.21917  36.91083
End  44.48170  34.04491
![image](https://user-images.githubusercontent.com/40493090/56664598-0f183500-66b1-11e9-9f49-75e45e6a36c8.png)

**Comment by vshcherb** [comment]
Not longer reproducible
