### ISSUE TITLE
support access=permit

### ISSUE THREAD

**Issue by hakuchi** [osmandapp/Osmand#6874]
There are a lot of streets with a [access=permit](https://wiki.openstreetmap.org/wiki/Proposed_features/access%3Dpermit) tagging.

OsmAnd should change this to `access=no`, because the most user don't have a permit to access this area/street etc.

Examples:
https://www.openstreetmap.org/way/234823245 -> `access=permit` with no effect to foot navigation
https://www.openstreetmap.org/way/675998874 -> `motor_vehicle=permit` with no effect to car navigation

**Comment by vshcherb** [comment]
We should treat it the same as "private"
