### ISSUE TITLE
Special case navigation instructions for leaving motorway

### ISSUE THREAD

**Issue by martenjj** [osmandapp/Osmand#6875]
When leaving a motorway the navigation instructions just say "turn slightly left" as the junction is approached (UK driving direction; I assume they would say "turn slightly right" for the opposite case).  Some other car and mobile navigation systems (including Google Maps) explicitly state to leave the motorway and also give the junction number, which is more helpful and makes it clear that it is intended to leave the motorway and exactly where.

The instruction could say something like "Turn off in DISTANCE at junction REF NAME" or "Leave at junction REF NAME".

Leaving the motorway could be detected by either:
(a) passing over a node of type highway=motorway_junction (with name= the junction/destination name and ref= the junction number);
(b) if the junction is not tagged properly as above, a transition between highway=motorway and highway=motorway_link (also trunk => trunk_link and primary -> primary_link).

**Comment by martenjj** [comment]
Apologies for not noticing #1451.  Still a useful enhancement IMHO.

**Comment by OpenSourceForEver** [comment]
https://github.com/osmandapp/Osmand/issues/1347

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-resources/commit/85eacca068b6ca4826e7a51fa92cf2541c03f6fd
