### ISSUE TITLE
Take into account alt different to calculate GPX distance 

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#6879]
The question is open again and I couldn't find neither the commit it was reverted or introduced:

Can / should we take into account altitude difference between points when we calculated  distance between points.

**Comment by sonora** [comment]
Hello Victor, have you considered this sanity check https://github.com/osmandapp/Osmand/issues/4455#issuecomment-340374144 ?

The 3D effect on distance in real travel is negligible. Not worth the extra overhead. In addition, considering it would often overestimate the effect because the elevation data, at least in recorded tracks, is reletivelely noisy. And keep in mind that GPX analysis is often overestimating distance already due to a certain 2D noise already present in most recordings.

Overall, I believe we have more realistic results if we leave things as we have them today?

**Comment by sonora** [comment]
Just to provide some figures here: I have looked at some of the tougher mountain drives and hiking tours I saw recorded, and hardly any of them exhibits and pertained slope of 10% averaged over a meaningful distance.

Even for a constant 10% slope the effect of 2D distance vs. 3D distance for a km would be **1000 meters** vs. **1004.99 meters**. A marginal difference compared to other effects like e.g. the accumulated GPS measurement inaccuracies.

**Comment by TheSnoozer** [comment]
Sounds related to #10830 or #14923, perhaps the altitude is not significant enough for the overall route distance, but the route calculation estimates an unrealistic arrival time.

**Comment by sonora** [comment]
The world is just not "3D enough" for up and down to make any significant difference on the "projected 2D vs. actual 3D" distance of any hiking or biking tours. We have multiple calculated and actual examples for this, see e.g. https://github.com/osmandapp/OsmAnd/issues/4455#issuecomment-340374144. Using 3D-formulae to improve the 2D-distances by 3D corrections would burn significant battery and CPU time with no practical benefit.

Regarding hiking time, you have to select the Navigation flag "Use elevation data" and have the elevation data present on the device. This the uses Naismith's rule, i.e. add 20min hiking time for every 400m ascent, a rule which works exceptionally good in most scenarios, is a simple algorithm and easy on your CPU. Naismith underestimates in extremely steep terrain when things move towards scrambling or climbing. But the actual travel times needed then are so dependent on fitness and technical skills that a general estimate is fruitless anyway.

Similarly for bike tours, you can let OsmAnd routing take elevation changes into account, try the difference between applying and not applying the setting "Use elevation data". I do not currently remember the algorithm, but the remarks on individual fitness-dependencies surely apply as well with increasing slopes...
