### ISSUE TITLE
bus route does not adhere to road

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#6881]
Reporting for the latest OsmAnd~3.3.0#27256m (released on 27-4-2019)

**BUG:**
In **bus** (public transport) mode, the route does not adhere to the road. It follows the contour of the road approximately, but jumps from one point to another in straight line segments. Further, it may cross all lanes of a multi-lane highway, regardless of traffic direction (for some distance it goes opposite the traffic direction).

I had set route from Bellandur (12.9229, 77.6698) to BEL cross (13.04519, 77.5566) in Bangalore city.
The route shows the last bus stop as "BEL Circle" (13.04346, 77.55844), which is correct.
I am supposed to walk the rest of the distance.

The following screenshots show the faulty route. (In India, we drive on the left.)

![image](https://user-images.githubusercontent.com/9047168/56891518-5d0aaf80-6a9a-11e9-8633-af0e46ec151d.png)
These two screenshots are taken at Marathahalli (12.95693, 77.70105).
(Imagine the right image at the top of the left one.)

![image](https://user-images.githubusercontent.com/9047168/56891645-ca1e4500-6a9a-11e9-89d3-2ae3614858ab.png)
This screenshot shows the route almost mid-way, at (12.9985, 77.6724).
The left screenshot shows how the bus route leaves the road.
The images at right show close-up of the same.

![image](https://user-images.githubusercontent.com/9047168/56891737-1e292980-6a9b-11e9-8d62-2fd3b64dcfb5.png)
This screenshot shows the end of journey.

Note that the second-last point on the route is actually a bus stop that is meant for return journey (located on the opposite side of the dual carriageway) (13.04441, 77.56222)!

Not only this, but OsmAnd displayed a single route called 500.
This route does NOT go to this destination (see [list of routes](http://travel2karnataka.com/500_bus_route_timings.htm))!
The following routes go to my destination ("BEL circle"): 
500BA, 500DG, 500DM, 500QG, 500QK.

But OsmAnd fails to show a list of all those routes as alternatives.

**Comment by scaidermern** [comment]
This is not a bug in OsmAnd. There is not enough data in OSM.

These bus routes (e.g. [relation 9243765](https://www.openstreetmap.org/relation/9243765)) just consist of bus stops but not of roads. OsmAnd can't know which roads the bus will take because this data hasn't been mapped yet in OSM.

Feel free to improve these bus routes in OSM. See the [Guideline for public transport](https://osmand.net/blog/guideline-pt).

**Comment by raindropsfromsky** [comment]
Ok I get some idea, but if the bus route is defined as a collection of all bus stops along the way.
But then the bus is supposed to ply on the road. And these bus stops are nodes on the road.

Given this, can't the bus route be made to snap to the road, like what we have for the car mode?

**Comment by raindropsfromsky** [comment]
I went through the document  and then [this](https://wiki.openstreetmap.org/wiki/Relation).

IINW, the definition of the bus route consists of ordered list of the bus stops. It does NOT include the other nodes that define the way (polyline) that depicts the road. The definition also does **not** include the line segments. 

Therefore, I infer that the navigator app must figure out the way logically by connecting the bus stops along the polyline that represents the road. In other words, the OsmAnd is supposed to snap to the road as we proceed along the ordered list of bus stops.

And that is not what we see. (bug)

**Comment by scaidermern** [comment]
> I went through the document and then [this](https://wiki.openstreetmap.org/wiki/Relation).
> 
> IINW, the definition of the bus route consists of ordered list of the bus stops. It does NOT include the other nodes that define the way (polyline) that depicts the road. The definition also does **not** include the line segments.

No. Quoting from this page:

> **Bus route**
> Each variation of a bus route itinerary is represented by a relation with type=route, route=bus and ref=* and operator=* tags. The first members in the route relation are the nodes representing the stops. These are ordered in the way the vehicles travel along them. **Then the ways are added. In PT v2 the ways form an ordered sequence, along the stop nodes.**

**Comment by raindropsfromsky** [comment]
So are we supposed to make all the routes in PT V2 style? It started in
2014 (5 years ago), right?

Can OsmAnd handle both versions of PT routes?

**Comment by vshcherb** [comment]
Nope, only v2 is supported and we plan to come back with supporting v1 in 2-3 years to check if it still makes sense.
As for now public transport backlog is full of other features.
