### ISSUE TITLE
zoom buttons pan/slide after search

### ISSUE THREAD

**Issue by seahorse41** [osmandapp/Osmand#6882]
Version: Osmand plus 3.3.7
both Pixel android 8.0.0 and Galaxy android 6.0.1
Offline maps

When performing a search, after zooming in, panning around (to find familiar intersection), the zoom buttons stop working as expected.

To duplicate: Press Search, enter a road name or choose a favorite location. The resulting marker is shown on the map. Zoom in a few times, slide the map in any direction, northwest in this example. Press zoom out. The map jumps or slides or pans NW off the screen to new map tiles. zoom out again, it jumps further northwest.

The trigger for this bug is panning while zoomed in from the starting view/zoom.
If I pan NE, then pressing [-] goes NE , and pressing [+] pans the opposite direction, SW.

Also pinch to zoom back out also scrolls/pans more.

The amount it slides/pans away from the search target is relative to the distance from the search point/marker. It does not preserve or correctly calculate where the center of the screen, and center of zoom in/out is at.
It **is** zooming in or out, but by jumping off the screen, I lose track of where I was searching, and have to back out and start over.

**Comment by vshcherb** [comment]
Fixed now it should zoom in into center of the screen if the marker of context menu is not visible
