### ISSUE TITLE
Is there a way to turn my phone to landscape mode in the lock screen?

### ISSUE THREAD

**Issue by avanlare** [osmandapp/Osmand#6885]
I have had a Motorola Moto e4 for almost 2 years with relatively no problems. A few days ago, my phone's touch screen stops working in certain frequently pressed places on the screen. This proves to be mildly annoying, but manageable as I would just flip the phone to landscape to get past this (especially when typing). Unfortunately, my phone has finally died and after I charged it, it now asks for my password so I can log in. The thing is, I can't press one of the onscreen keyboard keys to enter my password completely, and thus cannot unlock my phone. I cannot use my fingerprint because every time my phone reboots it asks for the password. I know if I can get my landscape mode I can enter in the correct password but all my attempts (notification bar, lock screen camera) have all failed. Any help? :)

**Comment by scaidermern** [comment]
How is this related to OsmAnd?
