### ISSUE TITLE
Subway and train stations

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/Osmand#6894]
Clicking on subway/train stations (not wubway entrances or another POI but nodes taged as subway or train station) with more than one stop position, Osmand only shows train/subway routes that belongs to nearest stop position and not all routes of all stop positions.

Examples:
https://www.openstreetmap.org/node/2006607646#map=19/40.62645/-4.00754
https://www.openstreetmap.org/node/5301853067#map=19/40.41684/-3.70319

**Comment by OpenSourceForEver** [comment]
In addition, subway stations nodes are rendered differently depending on zoom level

**Comment by OpenSourceForEver** [comment]
If a subway entrance has the same name as the station to which it belongs subway routes are not properly shown but nevertheless If a subway entrance has different name as the station to which it belongs subway routes are properly shown

**Comment by OpenSourceForEver** [comment]
Complementing last message, if the name of a subway entrance has a part of the name of a nearest bus stop, subway entrance shows bus lines of bus stop.

Examples:
Subway entrance located in Lat 40.46411 Lon -3.69578 shows information about bus stop located in Lat 40.46479 Lon -3.69634
Here I think the problem is that the name of subway entrance is "Capitán Blanco Argibay" and bus stop is called "Capitán Blanco Argibay - Torrijos"

Subway entrance located in Lat 40.43367 Lon -3.71780 shows information about bus stop located in Lat 40.43405 Lon -3.71801
Here I think the problem is that the name of subway entrance is "Arcipreste de Hita" and bus stop is called "Arcipreste de Hita - Fernando el Católico"

There is a lot of subway entrances with this problem, these are only 2 examples.

**Comment by OpenSourceForEver** [comment]
Sorry for insisting on this issue but I think it's important. Information about subway/train routes should be displayed properly and in many cases it is not like that.

**Comment by vshcherb** [comment]
Different rendering is explained in another issue. 
OsmAnd display all transport in the expanded context menu and only the transport that stops exactly at that stop on top of the context menu.
So both of information is accessible but they don't mix with each other.

**Comment by OpenSourceForEver** [comment]
A stop area must contain transport stations and subway entrances as members of the relationship https://wiki.openstreetmap.org/wiki/Tag:public_transport%3Dstop_area

But subway/train stations and subway entrances that are members of a stop area with two or more routes display only one route (opposite way is displayed within nearest routes). Also there is a problem with some subway entrances depending on their name (messages 3 and 4)

**Comment by OpenSourceForEver** [comment]
Example: https://www.openstreetmap.org/node/5303173537#map=19/40.43525/-3.71963

On this station Osmand displays different information about subway routes depending on the different subway entrances although the information of all the subway entrances of this station is the same in all of them.

**Comment by OpenSourceForEver** [comment]
@vshcherb I do not know if I have explained this issue clearly, my english is not good. Do you understand the problems I want to explain? I think it is a important issue because info is not displayed properly

**Comment by vshcherb** [comment]
Yes but not all possible features are implemented now. We display only transport that belongs to the stop position on top and don't do any magic with stop area polygon. In contrast we display all transport that stops near by with "Range 150M". 
We plan to support transport that have exits i.e. subway have 1 stop position or polygon but it could have 2-12 different exits, so this should work fine in future. 
Though we don't plan to display any buses on subway mark or subway entrance.

**Comment by OpenSourceForEver** [comment]
> Though we don't plan to display any buses on subway mark or subway entrance.
With lastest image I want to show you there is a problem with some subway entrances because with lastest nightly build clicking on a subway entrance Osmand displays bus routes that are not taged on OpenStreetMap, This is not a feature, it is a bug

> We display only transport that belongs to the stop position on top and don't do any magic with stop area polygon
This subway entrance https://www.openstreetmap.org/node/3196280896#map=19/40.47584/-3.71561 is displayed with two subway routes (one per subway stop of the subway station). For this reason I thought it was a problem depending on the name of the subway entrance

**Comment by vshcherb** [comment]
Well I checked data but it is still hard.
So on subway_entrance only "SUBWAYS" should be displayed on top which are L3, L6 - everything should be displayed within range 150m.
I didn't find where route 16 and 61 is located, so I couldn't check whether it is an issue with map or program.

**Comment by OpenSourceForEver** [comment]
Routes 16 and 61 are in https://www.openstreetmap.org/node/1439704673#map=18/40.43496/-3.71771

But this problem is not only on this node, other examples are:
Arcipreste de Hita - Fernando El Católico
Ubicación: geo:40.433662,-3.7177777?z=20
https://osmand.net/go?lat=40.433662&lon=-3.7177777&z=20

Carranza - Gta. Ruiz Jiménez
Ubicación: geo:40.42971,-3.7053108?z=18
https://osmand.net/go?lat=40.42971&lon=-3.7053108&z=18

Gran Vía - Montera
Ubicación: geo:40.419933,-3.7019312?z=18
https://osmand.net/go?lat=40.419933&lon=-3.7019312&z=18

I think the problem is that the name of the subway entrance coincide with first word of the name of a nearby bus stop

**Comment by OpenSourceForEver** [comment]
OsmAnd Nightly 3.4.0#24454D.
It is not fixed, clickig on a subway entrance OsmAnd displays a bus stop without any route
![Screenshot_2019-07-04-10-38-20-484_net osmand dev](https://user-images.githubusercontent.com/12786225/60652178-fe6e0300-9e47-11e9-9cdd-58310d294719.png)

**Comment by vshcherb** [comment]
1) It is fixed cause it doens't display bus stops on it
2) With new maps it will display metro on subway_entrance cause entrance will be properly recorded in the maps. You can give it a try with this small map

[Map2.obf.zip](https://github.com/osmandapp/Osmand/files/3358548/Map2.obf.zip)

**Comment by OpenSourceForEver** [comment]
Sorry. Yes, it is fixed.Thank you very much.
