### ISSUE TITLE
Add rendering for AED

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#6896]
Currently there is no rendering for automated external defibrillator (AED, `emergency=defibrillator`).  You can search for them but they are not shown on the map. Please add an icon since these POIs can suddenly become very important.

**Comment by rbovard** [comment]
Please also add field [defibrillator:location](https://github.com/osmandapp/Osmand/issues/6970) in the same time.

Thanks!

**Comment by rbovard** [comment]
Thanks a lot @xmd5a2, it's working well!
