### ISSUE TITLE
Break down "Track" road type by track type in route detail section and show winter roads.

### ISSUE THREAD

**Issue by groschialeux** [osmandapp/Osmand#6899]
Hi,

The road types section in the route details is a valuable tool for people driving in logging roads but it would be even better if there was a way to break it down by track trype and also show winter roads separately.   

The details on a route I calculated recently show me 232 km of tracks which is usefull but not as much as if I could see at a glance how much of it is on each grade.

It would also be nice to see the distance on winter roads.  My route shows a portion that is on winter roads which obviously cannot be used in the summer.  Currently I have to examine the route from start to end to see if there is any portion on winter roads and add some intermediate destinations to avoid them.   I understand I will always have to do that when routes include winter roads but if the Road types section in route details showed winter roads I would know right away if I have to do it or not

**Comment by vshcherb** [comment]
Custom split is supported by user defined rendering style so you could try to implement that idea and make pull request

**Comment by groschialeux** [comment]
I could use a little help to point me in the right direction.  I can't figure out how make the tracktype tag recognized.  

The way I understand things is when a <case> evaluates to true then the subsequent <case> statements are not executed so I figured I need to check for track types as additional tags before the highway=track tag.

I am reusing existing attribute string values and only 2 track types while testing just to see if the split works

I started with this but it does not work.

```
<renderingAttribute name="roadClassColor">
	<case additional="tracktype=grade1" attrStringValue="highway_class_state_road"/>
	<case additional="tracktype=grade2" attrStringValue="highway_class_street"/>
	<case tag="highway" value="track" attrStringValue="highway_class_track"/>
</renderingAttribute>

```
Then I though maybe I need to split it inside the highwa=track tag so I tried this which also does not work.
```
<renderingAttribute name="roadClassColor">
	<case tag="highway" value="track">
		<case additional="tracktype=grade1" attrStringValue="higyway_class_state_road"/>
		<case additional="tracktype=grade2" attrStringValue="highway_class_street"/>
		<case attrStringValue="highway_class_track"/>
	</case>
</renderingAttribute>


```
Then I though maybe I need to check the tracktype as tags instead of additionals.  The following did not work either.
```

<renderingAttribute name="roadClassColor">
	<case tag="tracktype" value="grade1" attrStringValue="highway_class_state_road"/>
	<case tag="tracktype" value="grade2" attrStringValue="highway_class_street"/>
	<case tag="highway" value="track" attrStringValue="highway_class_track"/>
</renderingAttribute>
```

Does the code that display the route details info check for additional tags ?  I am wondering if splitting by track type is actually possible without some changes in the code.

**Comment by vshcherb** [comment]
Grade types are in additional
```
<case additional="tracktype=grade1" attrStringValue="highway_class_state_road"/>
```
Probably you can use just a name  attrStringValue="Grade 1"

**Comment by groschialeux** [comment]
The problem is not with the name, it's with the breakdown, it does not work.  The XML below is what I have in default.render.xml but when I calculate a route that goes on a mix of road tracks, the route detail info only shows track with the total distance on tracks, it does not show the distances for grade 1 and grade 2 tracks.

I even tried removing the line for tracks but I get the distance as undefined.
` <renderingAttribute name="roadClassColor"> 
		<case tag="highway" value="motorway" attrStringValue="highway_class_motorway"/>
		<case tag="highway" value="motorway_link" attrStringValue="highway_class_motorway"/>
		<case tag="highway" value="trunk" attrStringValue="highway_class_state_road"/>
		<case tag="highway" value="trunk_link" attrStringValue="highway_class_state_road"/>
		<case tag="highway" value="primary" attrStringValue="highway_class_state_road"/>
		<case tag="highway" value="primary_link" attrStringValue="highway_class_state_road"/>
		<case tag="highway" value="secondary" attrStringValue="highway_class_road"/>
		<case tag="highway" value="secondary_link" attrStringValue="highway_class_road"/>
		<case tag="highway" value="tertiary" attrStringValue="highway_class_road"/>
		<case tag="highway" value="tertiary_link" attrStringValue="highway_class_road"/>
		<case tag="highway" value="unclassified" attrStringValue="highway_class_road"/>
		<case tag="highway" value="residential" attrStringValue="highway_class_street"/>
		<case tag="highway" value="living_street" attrStringValue="highway_class_street"/>
		<case tag="highway" value="service" attrStringValue="highway_class_service"/>
		<case tag="highway" value="pedestrian" attrStringValue="highway_class_footway"/>
		<case additional="tracktype=grade1" attrStringValue="Grade 1"/>
		<case additional="tracktype=grade2" attrStringValue="Grade 2"/>
		<case tag="highway" value="track" attrStringValue="highway_class_track"/>
		<case tag="highway" value="road" attrStringValue="highway_class_undefined"/>
		<case tag="highway" value="footway" attrStringValue="highway_class_footway"/>
		<case tag="highway" value="bridleway" attrStringValue="highway_class_bridleway"/>
		<case tag="highway" value="steps" attrStringValue="highway_class_steps"/>
		<case tag="highway" value="path" attrStringValue="highway_class_path"/>
		<case tag="highway" value="cycleway" attrStringValue="highway_class_cycleway"/>
	</renderingAttribute>  `

**Comment by vshcherb** [comment]
So it doesn't display attrStringValue="Grade 1"/> ? 
It might be a bug.

**Comment by groschialeux** [comment]
No it does not.  If I have a route that is 10 km on grade 1 tracks and 15 km on grade 2 tracks, the route detail info still shows 25 km on tracks.   

I took a look at the code and I think (not sure because I am not a Java developer) that additional tags are not handled for tracks in this function.

**Comment by Chumva** [comment]
Fixed with https://github.com/osmandapp/Osmand/commit/a3957c150ddeb8c259f1f62103b02978b2245337

**Comment by groschialeux** [comment]
I tested with the latest nightly build.   It works great, I really like it, it's going to be a valuable tool for hiking and offroading.  I am going to make changes to default.render.xml and submit a pull request.

Thanks guys.
