### ISSUE TITLE
Wrong road names shown in Bavaria

### ISSUE THREAD

**Issue by cyclingcat** [osmandapp/Osmand#6900]
Hi there,

for some reason some letters at the beginning of German road names are omitted in the OsmAnd display. I suspect the intention behind this is to hide the common letters "B", "L" and K", which leads to two issues:

1. It's unusual! Noone here refers to "road 370" if "road L 370" is meant. If the name is written on a sign or a map, it's almost always shown as "L 370" ("Landesstraße" = secondary road), "K 4711" ("Kreisstraße" = tertiary road) and so on. The only exceptions are the "A" (for "Autobahn" = motorway) and "B" (for "Bundesstraße" = primary road), which is displayed on the blue or yellow road signs without the "B", but it's equally common to call them "A 8" or "B 311", e.g. in newspaper articles or daily talk. Consequently the OSM "ref" tag always contains the letters. There's no need to omit them IMHO.

2. (a real bug:) In Bavaria, the tertiary roads known as "Kreisstraße" don't have the numbering scheme "K _nnnn_" but "_ddd_ _nnnn_", where _ddd_ is a one- to three-letter district code (see the Wikipedia link [Kreisstraße](https://en.wikipedia.org/wiki/Kreisstra%C3%9Fe)). This leads to non-existings road numbers on the OsmAnd map display if the district code begins with the letters "K" or "L". For example, the road "LIF 2" is shown as "IF 2" (e.g. way 29187980), the road "KU 16" is shown as "U 16" (e.g. way 37387587). Moreover, some other roads of type "Kreisstraße", are shown correctly with all of its letters (Example: "BA 29", way 85479494) while others are displayed with an existing but wrong name ("A 21" instead of "LA 21", e.g. way 216050241, the real "A 21" is a motorway in the very north of Germany!)

So I'd strongly suggest to leave all the road numbers as they are, with all their leading letters (= the way they are displayed in www.openstreetmap.org or JOSM) - all those quirky road numbers will be gone.

(Perhaps it's related to the closed issue #3000?)

OsmAnd~ 3.3.8 on bq Aquaris M4.5, Android 5.1
Offline map Bavaria, version 1 April 2019

The cycling cat

**Comment by scaidermern** [comment]
Indeed irritating.

Looks like A (motorway) and S (for example secondary) are still displayed while B (usually primary or trunk), L and K (for example tertiary) are omitted.

**Comment by vshcherb** [comment]
I guess it was done to dipslay shields and now that code is not valid any more or may be it was optimistic, anyway @xmd5a2 will be able to check in 3.4 I guess

**Comment by vshcherb** [comment]
I think it is not part of the code and it is part how we create the map itself (configuration):
https://github.com/osmandapp/OsmAnd-resources/blob/master/obf_creation/rendering_types.xml

**Comment by sonora** [comment]
Yes, lines 1066f are buggy:
`<entity_convert pattern="tag_transform" from_tag="road_ref_*" if_region_name="$germany" if_starts_with_tag1="road_ref_*" if_starts_with_value1="k" to_substr1="1" to_tag1="road_ref_*" seq="1:10" apply_to="way" notosm="true"/> <!-- Remove prefix. No need to add white shield here because it is by default -->`
