### ISSUE TITLE
Only one of two "through" turn:lanes is highlighted.

### ISSUE THREAD

**Issue by 532910** [osmandapp/Osmand#6901]
https://www.openstreetmap.org/way/562349295

![image](https://user-images.githubusercontent.com/14617699/57172505-8bd1ae80-6e29-11e9-9bcb-67effe96f5d3.png)
![image](https://user-images.githubusercontent.com/14617699/57172507-955b1680-6e29-11e9-9fde-a04aa578ec07.png)
![image](https://user-images.githubusercontent.com/14617699/57172498-81afb000-6e29-11e9-95f2-1aa9f74e3fb6.png)

**Comment by vshcherb** [comment]
It works as desired cause it assumes to keep left before next turn left is coming
