### ISSUE TITLE
quick action button is dark in day view

### ISSUE THREAD

**Issue by 532910** [osmandapp/Osmand#6902]
![image](https://user-images.githubusercontent.com/14617699/57172660-9a20ca00-6e2b-11e9-97e3-2ed20d89ed82.png)

**Comment by Dima-1** [comment]
This issue has taken place with dark app theme and day map mode. Now quick action button looks as expected in all combinations app themes and map modes.  I think this issue can be closed.

**Comment by 532910** [comment]
Is it fixed?

**Comment by Dima-1** [comment]
I don't know which commit fix it, but now it's working well.
