### ISSUE TITLE
Osmand(telegram) Location sharing api documentation

### ISSUE THREAD

**Issue by aHVzY2g** [osmandapp/Osmand#6904]
Hey,

is there an api documentation, on the placement of the live location marker? I could not find anything in the general api documentation. I would like to avoid the use of telegram (bot) service, as in my use case I won't always have Internet. The location is retrived over differnt RF-Services. 

I hope I don't have to dig into the osmand-telegram appilication :D .

**Comment by vshcherb** [comment]
You can do it via aidl interface - https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/aidl/IOsmAndAidlInterface.aidl#L439
Here you can find some documentation

**Comment by vshcherb** [comment]
Telegram application just communicates via telegram channel, so it is not necessary to dig there much
