### ISSUE TITLE
Transport stop icons are too big

### ISSUE THREAD

**Issue by gagarine** [osmandapp/Osmand#6908]
Public transit stop are very big and make the map unusable. I think it would be better to have only blue dot and only display the icone in the few very last zoom level.

![Screenshot_20190505-200218_OsmAnd](https://user-images.githubusercontent.com/164074/57198246-ceea6980-6f70-11e9-88a6-80125154c795.jpg)

Even at medium zoom their are still to big.
![Screenshot_20190505-200238_OsmAnd](https://user-images.githubusercontent.com/164074/57198247-d0b42d00-6f70-11e9-807c-f7fececa3ddb.jpg)

Also when I do not display "transport stop" they are still their but with a different style (smaller icone).

**Comment by OpenSourceForEver** [comment]
But this is only when you select public transport on "configure map". This is not like this in default view

**Comment by gagarine** [comment]
Yes. But I'm wondering then what's the point of this configuration. Perhaps
is should be renamed "big icon for transport stop" ;).

**Comment by scaidermern** [comment]
The point is to show stops more prominently and at earlier zoom levels. Similar to other POIs. This is not really meant to be turned on all the time. Use it for searching jobs around a specific place.

**Comment by gagarine** [comment]
I see, so it's a problem of labeling. "Show" may imply that otherwise things are "hidden". 
![Screenshot_20190507-125924_OsmAnd](https://user-images.githubusercontent.com/164074/57294460-0e779980-70c8-11e9-8c62-ac51466fe8db.jpg)

I didn't explore the app enough to know how the other option in this menu works. Yet if the different entries of this panel are not a show/hide removing "show" will be less misleading. Then in each entry the action can be more precise like "Highlight transport". But I don't know the app enough to have a solid proposition, I can only tell you it's a bit misleading for a new user.

**Comment by vshcherb** [comment]
The icons are proper size to click on them and it is configurable layer so it is accepted to clutter the map to display the density.

**Comment by gagarine** [comment]
@vshcherb  I understand that now and agree. But their is still an issue about the panel' label "show". At least as a new user I didn't get it.

**Comment by vshcherb** [comment]
that's a good question, let me forward the wording question to @sonora

**Comment by sonora** [comment]
I think "Show" is ok as our overall headline for this functionality because it **ensures** that the selected features are in deed **show**n at any zoom level.

It is true that some features (in particular POIs) may under some circumstances (zoom levels) also be displayed when they are not explicitly selected as "Show", just because they are at that zoom level an integrated part of the map style you have selected. Hence, under some circumstances, "show" really acts as **"emphasize"**, while under other conditions it is really **"show"**. But I have no good wording idea how to make this much clearer.

**Comment by mikehgentry** [comment]
"Always show" maybe?

**Comment by sonora** [comment]
Yes, perhaps. But it sort of creates the 'inverse issue': Some items, like Favorites or GPX files, are in fact NEVER shown unless selected here. So then for these, "Always show" would actually be misleading? (In addition to being clumsier?)

**Comment by mikehgentry** [comment]
I see your point. Personally I think I'd find that case less confusing than the other though. 

Case 1) Sees an icon they want to get rid of. Finds a menu setting that seems to switch that on or off, but it's already set to off.

Case 2) Sees a menu item that implies that something might be visible in some circumstances, but doesn't ever see it.

Case 1 seems more like an actual frustration causing bug to me. Case 2 I'd probably just assume I hadn't triggered the right circumstances, and switch it on if I wanted to see it.

**Comment by sonora** [comment]
True. But counting the menu items which are affected by case 1, I think it is only "POIs" and "Transport", while all other >6 (depending on plugin config) items on that menu screen are case 2 where "Show" is truly appropriate.

Maybe someone still comes up with the perfect wording here ... :)

**Comment by scaidermern** [comment]
Maybe use "Highlight" but this doesn't really fit it either. While "Show" might be a little bit confusing for new users I think it is still appropriate and not too misleading.

**Comment by gagarine** [comment]
What about removing "show"?

![57294460-0e779980-70c8-11e9-8c62-ac51466fe8db](https://user-images.githubusercontent.com/164074/57446822-e1f18800-7255-11e9-9dc7-b707867f8ec2.jpg)

**Comment by sonora** [comment]
"Highlight" seems wrong for e.g. Contour lines or Map overlay, etc.

I am personally very open to using no header at all, if enough people like that and seriously think it solves any problem ...  ;)
