### ISSUE TITLE
Mapillary widget is always on

### ISSUE THREAD

**Issue by gagarine** [osmandapp/Osmand#6909]
I try to remove this widget without success. I check all over the settings and clicking on it only propose me to install mapillary.

![Screenshot_20190505-232121_OsmAnd](https://user-images.githubusercontent.com/164074/57200493-0ff07700-6f8d-11e9-8011-58e220c6d29e.jpg)

**Comment by njohnston** [comment]
Open the main menu and select "Configure screen". In the "Right panel" section, you can disable/hide the Mapillary widget.

**Comment by gagarine** [comment]
Thanks. I feel a bit stupid.
