### ISSUE TITLE
[Android] Directory called ".facebook_cache" containing map data

### ISSUE THREAD

**Issue by daanjderuiter** [osmandapp/Osmand#6911]
First off, sorry if this is the wrong repo to file this issue under. I recently stumbled across a hidden folder called ".facebook_cache" in the /sdcard-directory of my LineageOS Android phone. I found this weird, since Facebook is not installed on the device, although WhatsApp (being a Facebook-product) is. I then found PNG's in this folder which are apparently map fragments, and the creation timestamps on these files correspond to when I had earlier downloaded maps in OsmAnd. All well and good, but why would a folder like this have a name like facebook_cache?

**Comment by vshcherb** [comment]
We don't have anything related with facebook at all in latest 3.3 version
