### ISSUE TITLE
Crash while using 'Directions' with calculated PT route

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/Osmand#6916]
Device : k7_x210ds
Brand : lge
Model : LG-X210
Product : full_k7_x210ds
Build : O11019 test-keys
Version : 8.1.0
App Version : OsmAnd~
Apk Version : 3.3.7 337
[exception (23).log](https://github.com/osmandapp/Osmand/files/3156982/exception.23.log)

**Comment by vshcherb** [comment]
The crash due to the small version
