### ISSUE TITLE
Bicycle Routing strange

### ISSUE THREAD

**Issue by rriemann** [osmandapp/Osmand#6918]
Setup:

- latest Android Version from Google Play Store, Osmand+ 3.3.8
- Offline Maps of Belgium (Live updates from 7 May 2019 16:29)
- I used osmand bicycle routing with use of elevation data.

Osmand route:

![image](https://user-images.githubusercontent.com/111932/57405373-90f27d00-71de-11e9-8834-15bdf71cfdb4.png)

Expected route: [see openstreetmap](https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=50.8224%2C4.3897%3B50.8179%2C4.4048#map=16/50.8200/4.3945&layers=N)

Note that the pedistrian osmand routing looks accurate and like the openstreetmap+graphhopper result.

Tell us your expected routing, and how OsmAnd routes, or add screenshots here.

**Comment by vshcherb** [comment]
I think you selected "Use elevation data", so in case it is flat area the data still could be noisy and you see that deviation. The difference is not big and it is not reproducible without "Use elevation data"
