### ISSUE TITLE
cannot run the app. it is caused by the following

### ISSUE THREAD

**Issue by utsab-bbc** [osmandapp/Osmand#6920]
Cannot run and build that is 

Caused by: java.lang.RuntimeException at SearchCoreUITest.java:46

Caused by: java.io.FileNotFoundException at SearchCoreUITest.java:46

**Comment by vshcherb** [comment]
Issue is not related to the product. Developers could comment here in case it will be clear

**Comment by vshcherb** [comment]
For future refs: Please check - https://osmand.net/help-online#dev-environment

**Comment by Reiszecke** [comment]
What am I doing wrong? This is the third time trying to get this running:

`repo init -u https://github.com/osmandapp/Osmand -m /Users/Alex/Documents/readonly-manifest.xml`

- Import the project by selecting the .repo/manifests/build.gradle
- Set OsmAnd to freedevLegacyFatDebug and the -sample to fatDebug
- Run it on my API level 24 device

Get
```
        Caused by: java.lang.RuntimeException at SearchCoreUITest.java:46
            Caused by: java.io.FileNotFoundException at SearchCoreUITest.java:46
```

**Comment by vshcherb** [comment]
SearchCoreUITest is a test and not part of the app, unfortunately never saw such problem before
