### ISSUE TITLE
Part of the river and landuse is not displayed or only in one colour

### ISSUE THREAD

**Issue by Heiner-Sch** [osmandapp/Osmand#6924]
Location: https://www.openstreetmap.org/query?lat=49.9832&lon=7.8647#map=15/49.9866/7.8702

Version: OSMand~ 3.3.8
Map: Germany_rheinland-pfalz_europe.obf (01. May 2019)

With the zoom level maked with 1km, parts of the map change the colour and the river bed disappears.

It's the same area of the map like in Issue #5209 

But it's not the same error.
I checked the file rendering_styles/default.render.xml already.
There must be another error.

**Comment by Heiner-Sch** [comment]
I try to upload a screenshot, but it will not work. Sorry.

**Comment by Heiner-Sch** [comment]
![Screenshot_20190510-172651](https://user-images.githubusercontent.com/38109491/57540056-16e00680-734c-11e9-8edf-635134ebf2f1.png)

**Comment by Heiner-Sch** [comment]
And here the same area in a working zoom level:

![Screenshot_20190510-175133](https://user-images.githubusercontent.com/38109491/57540176-6292b000-734c-11e9-99c9-dfec12bdb202.png)

**Comment by vshcherb** [comment]
Probably self-intersecting polygon

**Comment by Heiner-Sch** [comment]
And again, if I switch to the "Topo" may style, no problem.
The error happens only with the "Touring" style.

![Screenshot_20190510-175853](https://user-images.githubusercontent.com/38109491/57540589-53f8c880-734d-11e9-92ee-c4e6d5c9f037.png)

**Comment by sonora** [comment]
What you see is this area https://www.openstreetmap.org/way/246602883, which is labeled tourism=yes.

We render tourism=yes in Mapnik, UniRS, and Touring styles, and it is useful e.g in cities like Rome to highlight / identify attraction areas. I have now added a transparency so it is less disturbing for the few cases where this is used in mapping for very large areas in the landscape, like the one in this issue.

Also related to #5593.
