### ISSUE TITLE
Choose which group(s) of favorites are displayed

### ISSUE THREAD

**Issue by serpico** [osmandapp/Osmand#6926]
Please give us the following information so that we can try to **reproduce** your issue:

In the **Configure map** screen ![Screenshot_2019-05-11-14-59-34](https://user-images.githubusercontent.com/1227077/57570035-fcfefc00-73fd-11e9-90dd-c3a4cd28c9f2.png)

when toggling **Favorites** to show favorites on the map, give the possibility to choose which **category of favorites**
![Screenshot_2019-05-11-15-08-05](https://user-images.githubusercontent.com/1227077/57570098-b9f15880-73fe-11e9-9d1e-cad5dd3a8fda.png) 

will be displayed, similar to the behavior when toggling **Poi overlay...** 
![Screenshot_2019-05-11-15-12-51](https://user-images.githubusercontent.com/1227077/57570165-777c4b80-73ff-11e9-9b36-54b1b159ba04.png)

instead of showing all favorites.

What version of OsmAnd are you using, on what device and Android/iOS version?

OsmAnd~ 3.3.8 from F-droid
Samsung GT-I9195
Android 4.2.2

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps? offline maps

**Comment by vshcherb** [comment]
We have global list of active / disabled favorites. In case you need granular management of each group, it is recommended to convert to GPX and select GPX files to use.

**Comment by scaidermern** [comment]
@serpico For each favorite group you can already choose whether to show them on the map. Maybe this is already sufficient for your?

**Comment by Sunbird** [comment]
+1 to the request. :)

It would be really helpful the show a favorites' subset depending on the selected profile. Actually I have to generally enable or disable the favorites to be able to include them in the routing.
