### ISSUE TITLE
Route details using wrong translation

### ISSUE THREAD

**Issue by IgorEliezer** [osmandapp/Osmand#6930]
3.3.8 release and nightly build r23915.

"Surface" and "Smoothness" sections of the routing details are not using the translation strings according to the locale set in the Options (i.e., "Device language", which is Portuguese (Brazil)), but the English translation, despite having the proper translations on the rest of the UI and available on Weblate.

![image](https://user-images.githubusercontent.com/4673289/57579448-396c3f80-7472-11e9-8f90-fd02a5244825.png)

![image](https://user-images.githubusercontent.com/4673289/57579443-32ddc800-7472-11e9-9a2c-305a51b62d77.png)

**_BTW, I loved the new routing UI/feature. Thank you!_** :+1: 

EDIT:
Maybe related, [the What's New on 3.3.8 release was also using English](https://user-images.githubusercontent.com/4673289/57579508-46d5f980-7473-11e9-9b15-efb360d49689.png) ([the nighlty was ok](https://user-images.githubusercontent.com/4673289/57579591-e6e05280-7474-11e9-9d3c-fdc78270da66.png)). I think it's a minor issue by now. ^^'

**Comment by franco999** [comment]
I noticed it a long time ago too and it seems that it has not yet been corrected.
I'm using OsmAnd~ 3.3.0#27602m (23-06-2019) version.
