### ISSUE TITLE
Missing POI overlay symbol for ATMs

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#6931]
When choosing ATMs for POI overlay there is no symbol for ATMs:

![IMG_20190512_123651](https://user-images.githubusercontent.com/1040784/57581105-05653e80-74b3-11e9-9df5-b3d961a30435.jpg)

Other POIs have an overlay symbol, e.g. Banks.

**Comment by scaidermern** [comment]
This also applies to the UI. There is no ATM symbol next to the results when tapping on the map:

![photo_2019-06-13_08-49-10](https://user-images.githubusercontent.com/1040784/59410209-8a948980-8db8-11e9-853a-fb0d2a0a1150.jpg)

**Comment by vshcherb** [comment]
We need to check that poi_type with "edit_tag" now have proper icon. The fix changed the logic to retrieve icon with edit_tag poi_type

**Comment by xmd5a2** [comment]
Not reproducible in current nightly version
![Screenshot_2019-07-04-10-13-52-661_net osmand plus](https://user-images.githubusercontent.com/5829014/60646653-8baf5880-9e44-11e9-9253-ad94b5c2f9c0.png)

**Comment by scaidermern** [comment]
Yep, also fixed in 3.4.0.

**Comment by vshcherb** [comment]
Bug was fixed with 3556205 but extra checks need to be done

**Comment by xmd5a2** [comment]
Other poi types with edit_tag checked. All is ok.
