### ISSUE TITLE
Routing details: "Walk {time}" string inverted in the 2nd walk

### ISSUE THREAD

**Issue by IgorEliezer** [osmandapp/Osmand#6933]
Nightly build r23936d.

Small string concatenation mistake in the Routing Details.

![57598513-ef469500-7529-11e9-8b25-2dcc52fe6832](https://user-images.githubusercontent.com/4673289/58598589-52873580-8253-11e9-84b1-ee425e8d7a6d.png)

First you see "**Walk 2 min**, 155 m". 

After "Exit at", you see "**~5 min Walk**, 322 m". I believe the correct is "**Walk ~5 min**, 322 m".

**Comment by IgorEliezer** [comment]
Updated the screenshot for clarity.

**Comment by MadWasp79** [comment]
fixed with https://github.com/osmandapp/Osmand/commit/daf851cfbf8bfa480c076df702892fc1226c51b9
