### ISSUE TITLE
Slow route calculation

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#6938]
OsmAnd 3.3.8 cannot calculate the route both for bike and car navigation.
Start: Lat. 43.72314 Lon. 3.22778 
End: Lat. 43.54606 Lon. 1.47489
All the required maps are installed.

**Comment by vshcherb** [comment]
180 km - https://www.openstreetmap.org/directions?engine=fossgis_osrm_bike&route=43.734%2C3.230%3B43.546%2C1.475#map=9/43.5535/2.6964

**Comment by xmd5a2** [comment]
My Xiaomi Redmi Note 4x calculates this route in car profile within 5 seconds. In bicycle profile (without using elevation data) process takes longer - around 5 minutes, but finally it was built. There is a warning in bicycle profile about slow calculation speed at long routes.

**Comment by pebogufi** [comment]
Same problem with slow calculation:
version 3.3.0#27339 needs 10-15 sec. for route of ~140km
version 3.3.0#27518 needs 80-100 sec. for same route

**Comment by xmd5a2** [comment]
@pebogufi what exactly route and routing profile? If bicycle, are you using elevation data?

**Comment by pebogufi** [comment]
From Lat 48.04264 Lon 7.87767
To. Lat 47.45256 Lon 6.58305
profile is car, derived in new profile technic, fast route.

**Comment by pebogufi** [comment]
Just tested with current version. 
After ~40 sec the progress bar was at about 98%, after total ~80sec the calc was finished.

**Comment by pebogufi** [comment]
With standart / internal profile car about the same time
After ~**50** sec the progress bar was at about 98%, after total ~80sec the calc was finished.

**Comment by vshcherb** [comment]
Tested on 2 extra phones: car 15 seconds, bicycle takes 3 min and 6 min though it produces almost 8 hours bicycle tour

**Comment by pebogufi** [comment]
With version 3.3.0#27617m I also have good speed, test with known examples see above.

**Comment by vshcherb** [comment]
Routing engine itself didn't change much at all since 2.0. So I think with new easy to setup routing profiles you can "revert" to routing.xml of 3.3.0#27339 (which I think was a month ago). If you can point at which routing.xml you've got such degradation it could help https://github.com/osmandapp/OsmAnd-resources/commits/master/routing/routing.xml

**Comment by pebogufi** [comment]
I keep current when updating app with the latest routing.xml, only with few personal changes, heuristic coefficent for car on 1.4, for my camping car/caravan lower speeds.
I am happy with calculation speed now.

**Comment by nvfl600d** [comment]
A route calculation for Berlin to Graz (950kms) takes about 5 minutes at the moment. I know that this may be quite difficult to process larger distances, but to make people make the switch to open source software, the key features should work the way there're supposed to do. I badly want a working alternative for Apple Maps and Google Maps and OsmAnd looked promising on first sight...

**Comment by vshcherb** [comment]
There is no much sense to keep it duplicate and open cause they are still searchable. We're aware of the issue for bicycle and hoping to get it addressed this or next year.
