### ISSUE TITLE
Add Mozilla Location Service 

### ISSUE THREAD

**Issue by Gitschubser** [osmandapp/OsmAnd#694]
Is it possible to add the Mozilla Location Service in osmand to get the position with wifi and cellid (save battery, get position without gps and google)? This could be a good option/feature.

**Comment by teohhanhui** [comment]
Was this ever implemented? I can't find it anywhere in the app.

**Comment by scaidermern** [comment]
I don't think so. Also, the Mozilla Location Service project seems to be pretty dead since contributing wifi / cell tower sources is not possible at the moment: https://discourse.mozilla.org/t/retiring-mozilla-stumbler/75206

**Comment by teohhanhui** [comment]
Oh well, there is still opencellid.org

**Comment by mnalis** [comment]
If one uses UnifiedNLP (like from [microG](https://microg.org/), there are several [backends](https://search.f-droid.org/?q=UnifiedNLP) which will provide location (to all apps, not just OsmAnd) from other sources if GPS/GNSS is not available (including one for [Mozilla Location Service](https://f-droid.org/en/packages/org.microg.nlp.backend.ichnaea))

**Comment by breversa** [comment]
> If one uses UnifiedNLP (like from [microG](https://microg.org/), there are several [backends](https://search.f-droid.org/?q=UnifiedNLP) which should provide location (to all apps, not just OsmAnd) from other sources if GPS/GNSS is not available (including one for [Mozilla Location Service](https://f-droid.org/en/packages/org.microg.nlp.backend.ichnaea))

FYI, microG is currently [undergoing internal changes](https://github.com/microg/GmsCore/releases/tag/v0.2.28.231657) and UnifiedNLP backends have been disabled with the exception of Mozilla Location Service which is now the sole default, integrated "backend": 

> The new location stack does not support UnifiedNlp modules anymore. This was a step necessary to take to get locations properly working on latest Android versions. This means that some features previously available through UnifiedNlp modules do no longer exist. The goal is to merge the most important of those features into GmsCore. For now, the new locations stack is relying exclusively on Mozilla Location Service for network based location.
