### ISSUE TITLE
Elevation and slope profiles for routes - does not work MapCreator generated maps

### ISSUE THREAD

**Issue by GallusMax** [osmandapp/Osmand#6940]
I just learned the hard way that the 2.6 feature "Elevation and slope profiles for routes" does not show up when routing on self-compiled maps. Instead even the String "Entfernung" and "Ankunftszeit" is cut in a half vertically.
 
When activating the downloaded map of the surrounding area (and after recalculating the route), all is fine again. But thats not the solution, as the routing may (and should) differ on the more recent map content of the self-compiled subset!

Maybe this is an issue of MapCreator?

**Comment by naoliv** [comment]
Maybe this is the same problem from https://github.com/osmandapp/OsmAnd-tools/issues/136 ?

**Comment by groschialeux** [comment]
The link to the raster files does not work anymore.   Is it closed permanently or is this just temporary ?

https://builder.osmand.net/terrain-aster-srtm-eudem/

**Comment by GallusMax** [comment]
> Maybe this is the same problem from [osmandapp/OsmAnd-tools#136](https://github.com/osmandapp/OsmAnd-tools/issues/136) ?

That seems so at first sight, meaning this issue is around for about two years? If its a MapCreator Issue, this one may be closed.

**Comment by groschialeux** [comment]
OsmAndMapCreator takes elevation from raster files.  They have to be 16 bit gray scale.   It is best to download them from the link I posted above because there is some requirements to match for the type of raster and the naming of the files.

When (if ever) the link works again, download the files you need, put them in a folder called srtm and recreate your map.   Make sure to set the directory_for_srtm_files="path_to_srtm" in batch.xml if you are using batch mode.

**Comment by vshcherb** [comment]
Link is restored

**Comment by vshcherb** [comment]
https://builder.osmand.net/terrain-aster-srtm-eudem/

**Comment by groschialeux** [comment]
> https://builder.osmand.net/terrain-aster-srtm-eudem/

Thanks:  👍

**Comment by Bernhard-Hiller** [comment]
"Link is restored
https://builder.osmand.net/terrain-aster-srtm-eudem/ "
404 Not Found.

**Comment by Bernhard-Hiller** [comment]
ViewFinderPanoramas is mentioned in linked site https://rutracker.org/forum/viewtopic.php?t=5393970 , but with 1'' files. What about the 3'' files from ViewFinderPanoramas? When unzipped, they rea named e.g. N05E097.hgt 
When placed into a sub-folder "srtm" in the working directory of the OsmAndMapCreator GUI tool, they seem to be ignored.

**Comment by vshcherb** [comment]
https://builder.osmand.net/terrain/

**Comment by Bernhard-Hiller** [comment]
Thanks, that new link works.
