### ISSUE TITLE
Streets  are in wrong town in Schaffhausen, Switzerland

### ISSUE THREAD

**Issue by MSenning** [osmandapp/Osmand#6941]
OsmAnd 3.3 (nighly built on May 14, 2019.
Offline Map Switzerland, version May 1, 2019
Android 9, Huawei P20 Pro

If I point on the OsmAnd map to the residential street "Weinsteig" in city of Schaffhausen, Switzerland, OsmAnd shows correctly that the street belongs to Schaffhausen. However, if I point to the street "Bergstrasse" (which is directly near the street "Weinsteig") OsmAnd shows that this street is located in the city "Dachsen", which is approx. 10 km from Schaffhausen. (Dachsen is not part of the city Schaffhausen, nor is it part of the canton Schaffhausen).

The same holds for the residential street "Weinbergstrasse" in Schaffhausen, which OsmAnd also locates in Dachsen.

I checked OpenStreetMap. The data in OSM are correct.

Similar issues:
https://github.com/osmandapp/Osmand/issues/2587
https://github.com/osmandapp/Osmand/issues/3959
https://github.com/osmandapp/Osmand/issues/5967

**Comment by xmd5a2** [comment]
Fixed in june maps

**Comment by MSenning** [comment]
No, I'm afraid, the issue is still open in the map of **June 1, 2019**:  
pointing to the street "Bergstrasse" (which is directly near the street "Weinsteig") OsmAnd still shows that this street is located in the city "Dachsen", as mentioned in my first comment above.

I use OsmAnd~ 3.3.0#27338, published 2019-05-14. 
The map of Switzerland is published 2019-06-01.
Android 9, Huawei P20 Pro

**Comment by vshcherb** [comment]
Map Switzerland_eastern_europe has all addresses in Schaffhausen correct. Though Switzerland_zurich_europe also has some streets Schaffhausen but it is very limited and this map has  complete coverage of Dachsen. 

Merged map has problems and merges Bergstrasse from Dachsen with Bergstrasse from Schaffhausen which is obviously a problem. Please use separate maps to avoid that problem until the bug is resolved.

**Comment by vshcherb** [comment]
Fixed with https://github.com/osmandapp/OsmAnd-tools/commit/567c7f478faab68b50f92c563387252150fc333e

The map is regenerated please try again
