### ISSUE TITLE
Trip Recording - Feature suggestion - Track name and description into GPX file

### ISSUE THREAD

**Issue by soniok** [osmandapp/Osmand#6942]
Hello OsmAnd Team,
I would like to suggest a feature for Trip Recording plugin available in OsmAnd android application.
Could it be possible to save inside a GPX file, a track name and track description? At this point, only a track name is written to the GPX. It's composed of the original start date/time and cannot be changed even if renaming the GPX file within favorites menu.
It would be great to be prompt when starting or ending a new recording. For me, the prompt should ask for a track name (eg: 2019-12-31 Bike Ride - Parc in Zululand) and also for a description (eg: Bike ride on muddy roads, dirt track and ended with gravel track...). And this information would be written to the GPX file and could altered at anytime if possible.

My goal is to have better meta data in order to be able to search through multiple gpx tracks which I would've previously imported to a selfhosted gpx map viewer.
Right now, the problem is I can only rename the gpx filename and that doesn't update the "< name >" element under "< metadata >". If it had at least updated the value in the gpx file, that would've have been fine. But maybe we could go a step further and had a description as well.

Have I given enough information regarding for suggestion?
Is this worth the pain? I would surely like to see this implemented.

---

```What version of OsmAnd are you using, on what device and Android/iOS version?```
OsmAnd 3.3.8, released: 201-04-23 - Android 7.1.2 - LineageOS 14.1

```Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?```
 Offline most of the time. Sometimes online like Mapnik.

```What routing profile is chosen in OsmAnd app? (car, bike, pedestrian, fastest or shortest)``` Bike profile for recording and geolocating bike rides (leisure and work).

**Comment by soniok** [comment]
Could we add extra info? It seems gpx standards have several elements that are ready to be used.

If it's possible, we could have two types of inputs form to fill in the info. One simple (Name, description..) and the other detailed/full/advance input form which would give user ability to fill in more info.

The data I would like to see, which also includes what I said in original post:
* Track name
* Track description
* Track Author
* Track Email (Optional)
* Track tags (Save tags for easy re-use on next recording)
* Track type/profile, I mean the profile used during the recording (car, bike, walk...)
* OsmAnd version
* Phone info (Phone model, phone name) (Optional but would be nice)

I'm open extra info. Hope this is not too much.

**Comment by soniok** [comment]
Any update on this?

**Comment by soniok** [comment]
I've had a though on this request.
Maybe we're missing an extra info, which would be the start date/time of track. Therefor we would have a track in GPX format that has info like: track date/time, track name, track description, track tags, track profile type...

After reading a feature request in #3745 , if we had all this data I mention above, we could display info of track line on map. Stuff like track name and date/time. Or use track profile type, or track tags/categories to set a specific line color.

**Comment by vshcherb** [comment]
Track name & description is properly saved

**Comment by Chumva** [comment]
Support was added for main metadata tags - https://github.com/osmandapp/Osmand/pull/7161/commits/3cb65019c03dd8f642e0813f1f19112e9aa172f9 but editing still in progress

**Comment by soniok** [comment]
Any progress on this?
If any help or testing is required, I would happily give my time.

**Comment by vshcherb** [comment]
2 new issues are created to split that issue
