### ISSUE TITLE
favorite collision

### ISSUE THREAD

**Issue by 532910** [osmandapp/Osmand#6946]
I have two favorite points:
1. `Кит`
2. `Кит, дача`

And sometimes osmand show just `Кит` for the second point:
![image](https://user-images.githubusercontent.com/14617699/57788199-5be6ad00-773f-11e9-8b79-73980d92c29c.png)

Moreover, the history is also wrong:
![image](https://user-images.githubusercontent.com/14617699/57788686-2ee6ca00-7740-11e9-9179-5d8302294ebb.png)

But it must look so:
![image](https://user-images.githubusercontent.com/14617699/57788358-a9fbb080-773f-11e9-9b2a-cd9cc81426a2.png)

**Comment by vshcherb** [comment]
Fixed

**Comment by 532910** [comment]
Possible it's another issue, let me know if I should open the separate one.

I moved `Даня` favorite to `Даня old` and added new `Даня` point. But in the History it shows both points in one place:

![image](https://user-images.githubusercontent.com/14617699/66230256-77e9eb80-e6ec-11e9-9828-7dd9c5782fde.png)
