### ISSUE TITLE
Change OsmAnd for a better name

### ISSUE THREAD

**Issue by gagarine** [osmandapp/Osmand#6951]
I guess it mean "open street map android".  But I'm not sure.

This is a bad name. Every time I speak about the app to someone, I have to repeat the name 3 times. It's possible to change the name to something a bit more shareable like "Open Map"?

Also today most app do provide offline map. On top of that, in UE most peoples have access to data plan in every countries. It's not the core selling point anymore.

But a serious selling point is OSMand do not track you, in term of person data protection it's massively better than google map. The other things being it's distraction free, you don't push things I didn't ask.

**Comment by groschialeux** [comment]
OSM Automated Navigation Direction

https://en.wikipedia.org/wiki/OsmAnd

**Comment by vshcherb** [comment]
Well, we don't consider to change the brand cause there are multiple links in internet pointing to this name. We even suppose to have a trademark on that name.
