### ISSUE TITLE
Bicycle routing  (traffic light penalty red_turn:right:bicycle)

### ISSUE THREAD

**Issue by rriemann** [osmandapp/OsmAnd#6954]
Setup:

-    latest Android Version from Google Play Store, Osmand+ 3.3.8
-    Offline Maps of Belgium (Live updates from 7 May 2019 16:29)
-    I used osmand bicycle routing with use of elevation data and without.

Osmand route:

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/111932/57988826-ea866180-7a92-11e9-9741-e64327b0d97a.png"  width="300" height="auto"/> </td>
  </tr>
</table>

from: Brussels, rue Jean Paquot 3

to: Café Caberdouche in Brussels

## Expected outcome:

- a much simpler way as found by OsmAnd pedestrian navigation or openrouteservice: https://maps.openrouteservice.org/directions?n1=50.838403&n2=4.371704&n3=15&a=50.827073,4.377828,50.849922,4.366694&b=1a&c=0&k1=en-US&k2=km

**Comment by vshcherb** [comment]
It might be just shorter and I guess there are cycleways on all roads and routing engine just doesn't put enough penalties on turns and we get back very curvy directions.

**Comment by bgamari** [comment]
I have also observed this. Osmand's bicycle navigation engine tends to produce extremely complex routes which are very annoying to follow. I would much rather travel an additional 0.1 km than have to make five turns in five minutes.

**Comment by scaidermern** [comment]
See also #7532 and #7534 for pretty similar issues possibly caused by the same problem.

**Comment by scaidermern** [comment]
> routing engine just doesn't put enough penalties on turns and we get back very curvy directions

There needs to be a (high enough) penalty for turns. Constant turning / acceleration with a bicycle requires physical strength and leads to significant slow downs. Also, curvy routes are not very intuitive and require constant attention to the smartphone.

In the current state bicycle routing is not very helpful in large cities.

**Comment by vshcherb** [comment]
This route is penalyze by extra 100 seconds - https://test.osmand.net/map/?start=50.827073,4.377828&finish=50.849531,4.366025&via=50.834682,4.372827&profile=bicycle#14/50.8374/4.3778. 

I think this route is a bug - https://test.osmand.net/map/?start=50.826867,4.382901&finish=50.838359,4.368696&profile=bicycle#15/50.8361/4.3722. It should be straight - https://www.openstreetmap.org/way/8382447.640625#map=17/50.83249/4.37678 as 
cycleway:both-shared-lane is fine for routing.

**Comment by xmd5a2** [comment]
It is 17 `crossing=traffic_signals` and 21 `highway=traffic_signals` on [this route](https://test.osmand.net/map/?start=50.826867,4.382901&finish=50.838359,4.368696&profile=bicycle#15/50.8361/4.3722). But in reality cyclist should wait for traffic signals only 10 times if I counted them correctly. If I remove all of them or lower penalty then route is built straight. 
![изображение](https://github.com/osmandapp/OsmAnd/assets/5829014/4f713e40-7de7-4205-906c-740189aceb42)

**Comment by vshcherb** [comment]
OsmAnd should support already [traffic_signals:direction](https://wiki.openstreetmap.org/wiki/Key:traffic%20signals:direction?uselang=en)	so it needs to be fixed or checked

**Comment by ivanPyrohivskyi** [comment]
Need to add support the tag [red_turn:straight:bicycle](https://wiki.openstreetmap.org/wiki/Key:red%20turn:straight:bicycle?uselang=en-GB)
Also need to map this tag, for example [node 4424659607](https://www.openstreetmap.org/node/4424659607) must to consist of this tag.

Also need to think how to support tag [red_turn:right:bicycle](https://wiki.openstreetmap.org/wiki/Key:red%20turn:right:bicycle?uselang=en-GB)

[traffic_signals:direction](https://wiki.openstreetmap.org/wiki/Key:traffic%20signals:direction?uselang=en) is working correct.

**Comment by vshcherb** [comment]
To do: add parameter avoid traffic signals

**Comment by ivanPyrohivskyi** [comment]
Fixed bicycle profile _short_way_ only

**Comment by DmitryAlexei** [comment]
Tested on web. Now bicycle routing on web (when _Short way_ option enabled) almost completely repeats Openrouteservice
- [Openrouteservice routing](https://classic-maps.openrouteservice.org/directions?n1=50.835575&n2=4.375095&n3=14&a=50.827073,4.377828,50.849922,4.366694&b=1a&c=0&k1=en-US&k2=km)
- [OsmAnd routing](https://osmand.net/map/navigate/?start=50.827073,4.377828&end=50.849531,4.366025&via=50.834682,4.372827&profile=bicycle&params=bicycle,short_way#14/50.8400/4.3610) Cost: 873

Only the difference that on the first section of the route OsmAnd prefers [this shortest road](https://www.openstreetmap.org/way/8384886) over [more longer one](https://www.openstreetmap.org/way/8382440)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/12eec4fe-32a8-40e2-932b-646dcb19383b"  width="500" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/033ec04b-ad3f-4a5a-8898-92d28bd9918f"  width="500" height="auto"/> </td>
  </tr>
</table>
