### ISSUE TITLE
Search for aerialway=zip_line

### ISSUE THREAD

**Issue by DFyson** [osmandapp/Osmand#6960]
Type in zip line or zipline in the search and the POI "[aerialway=zip_line](https://wiki.openstreetmap.org/wiki/Tag:aerialway%3Dzip_line)" doesn't appear as an option.

**Comment by xmd5a2** [comment]
Not reproducible. It doesn't have an icon but it is searchable
![Screenshot_2019-06-11-10-46-32-505_net osmand plus](https://user-images.githubusercontent.com/5829014/59253204-61e48680-8c36-11e9-94bb-6e32131ab6ca.png)
![Screenshot_2019-06-11-10-46-23-987_net osmand plus](https://user-images.githubusercontent.com/5829014/59253206-61e48680-8c36-11e9-9cca-b2a0e3c4d665.png)

**Comment by DFyson** [comment]
Ah I mis-diagnosed the problem. What I meant was when I select "show zip line on map", nothing shows up which is the problem I'm hoping to fix. But maybe that's just because it has no icon like you said. Is the procedure for adding an icon straight forward?
