### ISSUE TITLE
Osmand setup

### ISSUE THREAD

**Issue by SaifullahIlyas** [osmandapp/Osmand#6961]
kindly share the guide to use this project in android studio.it always giving a proxy error where everything is fine in a proxy setting and I am using no proxy. My question is how to configure proxy for this project.

**Comment by SaifullahIlyas** [comment]
how to setup proxy in this project.

**Comment by vshcherb** [comment]
Not sure I can help, I don't have any issue with proxy. And in OsmAndSettings and OsmAndApplication you can debug so the proxy is not enabled

**Comment by SaifullahIlyas** [comment]
Hello sir, i hope you are fine.
Sir is there any guide to import the project without any error in android studio. I tried to import it from android studio version control option. But its not work for me. Or is there any alternative repository for osmand.

**Comment by scaidermern** [comment]
> without any error

Please tell us the exact error. Otherwise we can't help you.

**Comment by SaifullahIlyas** [comment]
Hello sir, i hope you are fine. Sir is there any guide to import this project in android studio(window). I have followed many links but found no solution for window. Almost all solution was for Linux.

**Comment by vshcherb** [comment]
https://osmand.net/help-online#dev-environment
