### ISSUE TITLE
Routing goes out of the way, making a curve into two turns

### ISSUE THREAD

**Issue by ithink314** [osmandapp/Osmand#6966]
What version of OsmAnd are you using, on what device and Android/iOS version?

Latest, 3.3.8 from f-droid, on nexus 6 with microg lineage 16, pie.

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?
Offline maps, NC USA April 30, 2019.

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.

__*In case of wrong routing:*__

Tell us whether you have used OsmAnd's in-app offline routing, or any online routing provider like YOURS, OpenRouteService or OSRM.

Offline routing in app.

What routing profile is chosen in OsmAnd app? (car, bike, pedestrian, fastest or shortest)

Car. Same result with fastest or shortest.

Please specify as exactly as possible the start and end point of your route by telling us city name and street name so that we can find it via in-app address search easily. Also, a permalink from openstreetmap.org can be helpful.

Anywhere before and after turn shown in screenshot, Concord, NC.

https://www.openstreetmap.org/#map=17/35.39611/-80.61009

Tell us your expected routing, and how OsmAnd routes, or add screenshots here.

Expected to go directly along route curving to left. Not turning right, then turning left, making route longer.

![IMG_20190522_221202](https://user-images.githubusercontent.com/843769/58223338-39c4d000-7ce7-11e9-8936-b419e2608439.jpg)

**Comment by kylegates** [comment]
It's routing around because of the traffic signals.

**Comment by ithink314** [comment]
I believe there are more signals when going to right. But this could be a map problem too, maybe. Signals do not appear obvious on map, to me.

**Comment by kylegates** [comment]
I made some edits to the map with should resolve this issue.

**Comment by ithink314** [comment]
Thanks! I'll try to remember to verify it when the map update is available for download. Closing for now.

**Comment by ithink314** [comment]
Another oddity was seen in navigating past this intersection; see attached. Fortunately, the May 31 offline map update does not have these problems. 

![Screenshot_20190613-101542_OsmAnd~](https://user-images.githubusercontent.com/843769/59543923-00dddc80-8edc-11e9-9a42-54332f3a8bc4.png)
