### ISSUE TITLE
Restore last view in My Places when back button is pressed

### ISSUE THREAD

**Issue by contrapunctus-1** [osmandapp/Osmand#6967]
Menu > My Places > My Edits or Notes > tap on an edit or note (opening the map) > press Back button twice. My Places is opened, but it shows "My favourites", instead of the same tab and position as the one you were at.

OsmAnd v3.3.8 from F-Droid, Android v9

**Comment by MadWasp79** [comment]
implemented with https://github.com/osmandapp/Osmand/pull/7089

**Comment by crimean** [comment]
https://github.com/osmandapp/Osmand/commit/bd3f1a1a7347a3f40f63110c383decf57f16c946
