### ISSUE TITLE
poor tiles server performance

### ISSUE THREAD

**Issue by ezbik** [osmandapp/Osmand#6974]
I could not download many tiles on zooms 15+. For example:

```
 curl -o /dev/null -m10  https://tile.osmand.net/hd/16/37789/21087.png 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
curl: (28) Operation timed out after 10001 milliseconds with 0 bytes received
```

So it affects both Osmand Android app and https://osmand.net/ .
I even had to switch to Mapnik online tiles in  Osmand Android because of that issue.
![Screenshot_2019-05-23_19-11-45](https://user-images.githubusercontent.com/775614/58268882-fb82eb80-7d8e-11e9-9e38-228df30f980f.png)

**Comment by vshcherb** [comment]
Yes it is a known issue we are  working on it. Cause it requires server relocation and redesign of our plans how to maintain server side to avoid such issues it could take a while.
Situation now : 
- OSM Database update is enabled, happens every 6 hours
- Tiles zoom <= 15 serving with no delay
- Tiles zoom > 15, there is no queue to render but there are very strict limitation to request tiles. Basically average is 4 tiles a minute with an initial burst of 32. rendering metatile 8x8 takes  on average 20-25 seconds

Disclaimer: Cause it is non-related to our source code, the issue will be closed.
