### ISSUE TITLE
Wrong Direction in Roundabout

### ISSUE THREAD

**Issue by MAlfare** [osmandapp/Osmand#6977]
On a short trip in Switzerland navigation took wrong direction inside roundabouts. 3/5 where wrong, 2/5 where O.K
Before and including OsmAnd~3.3.0#2738
TrafficRegion is on "automatic"

Filenames of screen shots includes position data:
 1-BAD_47.47921_9.57885.png
 2_BAD_47.45107_9-63553.png
 3_GOOD_47.44608_9.64812.png
 4_BAD_47.43096_9.63440.png
 5_GOOD_4743029_9.64162.png

![1-BAD_47 47921_9 57885](https://user-images.githubusercontent.com/4406655/58326374-ee1c3e80-7e2c-11e9-904d-dac293be7e42.png)
![2_BAD_47 45107_9-63553](https://user-images.githubusercontent.com/4406655/58326376-ee1c3e80-7e2c-11e9-9f54-a487f1bab6e8.png)
![3_GOOD_47 44608_9 64812](https://user-images.githubusercontent.com/4406655/58326377-ee1c3e80-7e2c-11e9-9ce1-51b3fe4e58a2.png)
![4_BAD_47 43096_9 63440](https://user-images.githubusercontent.com/4406655/58326378-ee1c3e80-7e2c-11e9-8c98-7fae15b006ee.png)
![5_GOOD_4743029_9 64162](https://user-images.githubusercontent.com/4406655/58326379-ee1c3e80-7e2c-11e9-9256-0dde3e25e7bf.png)

**Comment by lightonflux** [comment]
Bad:
- https://www.openstreetmap.org/way/37765025
- https://www.openstreetmap.org/way/41209218
- https://www.openstreetmap.org/way/22513651

Good:
- https://www.openstreetmap.org/way/261520214
- https://www.openstreetmap.org/way/7955335

**Comment by aceman444** [comment]
Hi, and you are sure you are in the 'car' routing mode and you haven't modified your routing.xml file?

**Comment by vshcherb** [comment]
Was fixed in 3.4

**Comment by Aiurek** [comment]
@vshcherb I've encountered this issue a couple of days back with standard navigation settings in version 3.4.4.

https://www.openstreetmap.org/#map=19/43.48312/-1.50249

![Bild9](https://user-images.githubusercontent.com/27865200/62706367-a9498200-b9ef-11e9-9c85-91032c7f83a9.jpg)
