### ISSUE TITLE
OsmAnd Live status hour doesn't match the time from which the data is

### ISSUE THREAD

**Issue by tuxayo** [osmandapp/Osmand#6984]
This is a minor issue. Maybe the purpose of this info is just to get an approximation.

The in-app and [web](https://osmand.net/api/osmlive_status.php) status tells 2019-05-27 16:30 UTC
But I just updated, and the last change that was downloaded is from 15:40 UTC which could be correct. But a changeset from 16:28 UTC wasn't included in the data https://www.openstreetmap.org/changeset/70667820

I've seen that happening few time already.

Lately, I've seen a decrease in the latency of OsmAnd Live, this is very useful for me to help me double check what I map, I use this every day. So I'm very grateful for the latest improvements :)

**Comment by tuxayo** [comment]
Ok, I retried a bit later and the change came with the next update. status: 16:40

So might be a rounding error.

Feel free to close if this is hair-splitting.

**Comment by vshcherb** [comment]
It shouldn't match, the status is the latest processed status of the global map, if the map wasn't updated last 30 minutes, last edit time will be 30 min earlier
