### ISSUE TITLE
Network traffic with offline maps, to C rated site

### ISSUE THREAD

**Issue by ithink314** [osmandapp/Osmand#6985]
Two related issues, one in the form of a question and probably user error:
1. Net Monitor routinely reports traffic to osmand.net when expecting to be in offline mode. Did I miss a setting, or why is this network traffic needed? Is it for Nominatim address lookup when starting the app?

2. Net Monitor app and SSL Labs website reports C rating for osmand.net, with vulnerability to "POODLE" attack. (tile.osmand.net still gets an A)

https://www.ssllabs.com/ssltest/analyze.html?d=osmand.net

What version of OsmAnd are you using, on what device and Android/iOS version?

3.3.8 from f-droid, on Nexus 6, Android 9, Lineage 16 with no gapps. With Unified NLP using Deva Vu Location Service backend and Nominatim OSM API server.

Offline maps only, with offline routing is intended use.

Related previous issues: #5936 , #3525

**Comment by vshcherb** [comment]
To disable all comunication you need to disable option "Show messages in Settings". We are going to update server side later Q2-Q3.

**Comment by ithink314** [comment]
After changing the show messages setting, osmand still calls home to osmand.net every time it starts.

**Comment by ithink314** [comment]
FWIW, I see website grade is improved to A+. Also, disabling app's data (WiFi, cellular & VPN) in android 9 app settings seems to stop the network traffic, and make osmand startup much faster.
