### ISSUE TITLE
(Active) railway crossing rendered before railway looks odd

### ISSUE THREAD

**Issue by Famlam** [osmandapp/Osmand#6999]
OSM 3.3.8, LG, Android 5.1
Map: Gelderland (Netherlands), offline, version May 1 2019

A minor issue, but the preserved railroad https://www.openstreetmap.org/way/6308451 is rendered only zoom level 19*, whereas its [crossings](https://www.openstreetmap.org/node/906905347), [station ](https://www.openstreetmap.org/node/2640081853) and [the disused (and thus much less relevant) part of the railway nearby](https://www.openstreetmap.org/way/6308462) are already rendered at zoom levels 13 to 15*, resulting in an odd appearance between zoom levels 15 and 19. 

*These values are the ones shown in the left bottom corner when the debug plugin is enabled

![Screenshot_2019-05-30-16-45-06](https://user-images.githubusercontent.com/1315520/58641536-abaaa400-82fb-11e9-8a74-2ebf07b5d8d3.png)

**Comment by xmd5a2** [comment]
It is not possible to differentiate crossings on preserved railroads from crossings on regular railroads by rendering engine.

**Comment by Famlam** [comment]
@xmd5a2, my apologies for being unclear. My intention was not to stop rendering crossings, but rather to have the railway itself be rendered at a lower zoom level (at least similar to the disused railway). Perhaps this is actually possible?
