### ISSUE TITLE
Crashes on Samsung Galaxy S5

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7011]
Crash on Samsung Galaxy S5, Android 6, while installing a TTS voice announcement for navigation.
Version  OsmAnd+ 3.3.8
[exception.log](https://github.com/osmandapp/Osmand/files/3256516/exception.log)

**Comment by vshcherb** [comment]
https://stackoverflow.com/questions/26730082/illegalargumentexception-invalid-int-os-with-samsung-tts
It looks like TTS language is not available, we might need to do something and display toast when it is not available

**Comment by Chumva** [comment]
The same crash was here - https://github.com/osmandapp/Osmand/issues/6893

**Comment by MadWasp79** [comment]
fixed with https://github.com/osmandapp/Osmand/pull/7097
