### ISSUE TITLE
Search and "show on map" returns back to unresponse search screen

### ISSUE THREAD

**Issue by devillemereuil** [osmandapp/Osmand#7018]
On OSMAnd+ (v.3.3.8, but this is an old issue) on my system (Asus Zenfone Max 4, ASUS_X00ID, Android 8.1.0), there is a very annoying bug with the GUI, where showing a search on the map results in the map being shown for approx. 1s then an unresponsive Search interface is shown again. This makes it almost impossible to actually see searches on the map.

Steps to reproduce
-------------------------
- Start "Search"
- Enter anything to search for
- Either select a result of the search or click "Show on map"

Result
----------
The map is shown for ~1 second and then the GUI shows the "Search" interface again. Only, now, it's impossible to click on anything except the "Go back" arrow. Clicking on the arrow sometimes results in the map being shown again, sometimes it actually goes back in the search interface, making it impossible to see the search on the map.

Some other facts
----------------------
- This was also present when my phone was under Android 7.xx.
- On the off-chance this was due to me using SwiftKey as a keyboard, I tried using the system keyboard, the result was the same.
- I tried resetting OSMAnd+ data and reinstalling it, but to no avail.
- On my wife's phone (same version of OSMAnd+ and Android, but different device: Meizu Redmi Note 5), this is not happening at all. This possibly means that this bug is difficult to reproduce, but it is highly reproducible on my device. :/

**Comment by vshcherb** [comment]
Not reproducible on any of our dev devices
