### ISSUE TITLE
Osmand (offline) does not route over bridge that allows bicycles

### ISSUE THREAD

**Issue by lightonflux** [osmandapp/Osmand#7019]
OS: Android
Osmand version: 3.3.8
Data: Offline, Germany, Lower Saxony
Routing Information:
  * Bicycle
  * Osmand Offline Routing
  * Ignore: nothing
  * Allow highway: no
  * shortest path

### Expected route
**Via two bridges which explicitly allow bicycles.**

https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=52.9612%2C9.1449%3B52.9708%2C9.1581#map=15/52.9659/9.1526
![Bildschirmfoto von 2019-06-08 01-20-05](https://user-images.githubusercontent.com/1377943/59138160-cc25ce80-898b-11e9-98f8-fa4ea4d4b662.png)

### inconvenient osmand route

![img](https://user-images.githubusercontent.com/1377943/59138185-fc6d6d00-898b-11e9-9704-8bc8527147b2.png)
 
#### Added desired route in dashed orange, just in case because of the dark style 

![img2](https://user-images.githubusercontent.com/1377943/59138184-fc6d6d00-898b-11e9-926a-cb89138a5059.png)

**Comment by lightonflux** [comment]
Bridges: 
* https://www.openstreetmap.org/way/28746074
* https://www.openstreetmap.org/way/127236593

**Comment by lightonflux** [comment]
There is also a cycle_barrier [lin k](https://www.openstreetmap.org/node/3771555948#map=19/52.96476/9.15356) but i would assume that OSMAND routes through them. In this case they are just for slowing down bicyclist. And even with it being a blocker you could still route over the K9.

**Comment by vshcherb** [comment]
The problem was in May maps I couldn't find what exactly was wrong but in June maps everything is ok. It should also work with OsmAnd Live maps

**Comment by lightonflux** [comment]
Thank you very much. I just checked and can confirm it works with live maps.

But when disabling live maps and downloading the June maps it did not work. I did restart the app just in case of a caching issue but that did not work.
