### ISSUE TITLE
Routing issue with pedestrian 

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#7020]
![image](https://user-images.githubusercontent.com/1042025/59145389-e1324a00-89eb-11e9-8ebe-675a351f98a5.png)
![image](https://user-images.githubusercontent.com/1042025/59145394-f0b19300-89eb-11e9-9121-d5b78c451693.png)

Footways should be preferred if they are present next to highway roads.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-resources/commit/60a839cb8fc5a3c4ef4dae30466585253bfbecf0

**Comment by Famlam** [comment]
Just a quick question, shouldn't `foot=designated` (and possibly some others) and `sidewalk=left/right/both` be special-cased too, i.e., not get a 150s penalty either?

**Comment by vshcherb** [comment]
added foot designated, sidewalk is already an integral value

**Comment by scaidermern** [comment]
What about `highway=path`?

**Comment by vshcherb** [comment]
Please feel free to create pull request and test it, I think path doesn't have original problem cause path is usually in other areas where it doesn't collide much with highways

**Comment by scaidermern** [comment]
Unfortunately I don't have time to perform such a test. I was just wondering if path was just forgotten or intentionally left out.

I don't think it is true that path usually doesn't co-exist with highways dedicated for motor vehicles. Sadly OSM's data model is somewhat weird / broken regarding foot and bicycle routing. `highway=path` is commonly used in combination with both `foot=designated` _and_ `bicycle=designated`, see for example https://overpass-turbo.eu/s/JR3

**Comment by vshcherb** [comment]
I don't feel path should be part of it cause it is similar to "class change" for pedestrian, the penalty is rather small, so path road should be shorter.
BTW foot=designated is already fixed for all highway =*
