### ISSUE TITLE
Favourites export filename differs on iOS and Android

### ISSUE THREAD

**Issue by twenster** [osmandapp/Osmand#7028]
I'm using OSMAnd on android 7.0 and iOS 12. Booth using french language.
When I export a favourite place, the file is named differently depending of the OS. Where it shouldn't:
Android filename is favourites.gpx (UK english)
iOS filename is favorites.gpx (US english)

As booth app are set in french, it should be : favoris.gpx

I think this should be consistent (and would suggest using the UK english across the interface as default fallback language)

**Comment by vshcherb** [comment]
This is an IOS bug so will transfer it there.
