### ISSUE TITLE
upload impossible of poi changes when poi is area

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#7030]
When making changes on pois, where poi is way (area) i can't upload poi.
Error message:
Failed to upload
Error: unknown problem.

Black window which disappears after about 2 sec:
Commition node failed ...  precondion failed.

Uploading single node poi are successful.
version 3.3.0#27339

**Comment by xmd5a2** [comment]
https://www.openstreetmap.org/way/130343475
```
06-11 15:21:17.419 18459 19519 I net.osmand: OpenstreetmapRemoteUtil Response : OK
06-11 15:21:17.424 18459 19519 I net.osmand: OpenstreetmapRemoteUtil Sending request https://api.openstreetmap.org/api/0.6/changeset/71139237/upload
06-11 15:21:17.780 18459 19519 E net.osmand: OpenstreetmapRemoteUtil Сохранение объекта… , ошибка : Precondition Failed
06-11 15:21:17.780 18459 19519 D net.osmand: OpenstreetmapRemoteUtil null
```
