### ISSUE TITLE
Actions screen barely visible

### ISSUE THREAD

**Issue by Ceaus** [osmandapp/Osmand#7032]
The actions screen (see attachment for a screenshot) is only readable in dim light conditions. If there is even just a little bit of daylight directly on the screen, it is next to impossible to read what is on the screen. The action options should be a little bit more highlighted/accentuated.
![osmand-actions](https://user-images.githubusercontent.com/13982083/59295905-0db4c300-8c85-11e9-8c6d-f78322f27bc1.jpg)

OsmAnd 3.3.8

**Comment by vshcherb** [comment]
yes they should be consistent with 
![image](https://user-images.githubusercontent.com/1042025/59609344-826d7e80-9117-11e9-9be2-e8e1824109e6.png)

**Comment by crimean** [comment]
Fixed
