### ISSUE TITLE
Routing parameter for ski profile is not used correctly

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#7034]
https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml#L1772
Parameter "piste_type_downhill" (Alpine/downhill ski) is not "true" until it is turned off and on in navigation settings. By default, this parameter in the interface is displayed as "enabled", but in fact it is not.
![Screenshot_2019-06-12-11-33-57-914_net osmand plus](https://user-images.githubusercontent.com/5829014/59335865-1c8f8a00-8d06-11e9-8d7d-4663860e72e9.png)
Without this parameter routing won't build routes on piste:type=downhill which is most frequent piste type.

**Comment by MadWasp79** [comment]
it looks like everything is ok in fresh clean installs. Same if you wipe app data (not only cache) through android' application settings.
