### ISSUE TITLE
Offline Search: add support for extended format

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/Osmand#7040]
Calendars apps often contain addresses in the format like [street name, number, city name, Country, postal code]

**Comment by vshcherb** [comment]
"улица Олеся Гончара, 47-49, Киев, Украина, 02000" - no results

**Comment by vshcherb** [comment]
Works now - улица Олеся Гончара, 47-49, Киев, Украина, 02000 and gives exact result with "улица Олеся Гончара, 47/49, Киев, Украина, 02000"
