### ISSUE TITLE
Negative ETA during navigation

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7041]
Happened during navigation with a currently calculated route in the car profile.

Start - 65.74433 -19.63860 
Waypoint 1 - 65.60590 -20.63664 
Waypoint 2 - 65.60686 -20.89009 
End - 65.58401 -20.92192
![image](https://user-images.githubusercontent.com/50198677/59522094-83639d80-8ed6-11e9-8060-cecc502ac838.png)

![image](https://user-images.githubusercontent.com/50198677/59522101-88285180-8ed6-11e9-81d3-28c2af681dd4.png)

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/commit/312b4d7d4755433559699c2076edebf7c63f5e37
