### ISSUE TITLE
osmand live:   i/o error file not found

### ISSUE THREAD

**Issue by cart0** [osmandapp/Osmand#7043]
App: OsmAnd+ 3.3.8
OS: Android 9 / Android 7
Device: Samsung Galaxy S9 / Galaxy S4
Signed into osm with my account.  

Up until recently I was able to us the OSMAnd live feature to download my local area (Ireland).   Of at least the last 7 days if not more the downloads have been failing with an error `I/O error file not found` toast notification.     If I run it again I usually get a `no updates available` toast notification.

I've added another live area as a test (California) and get similar results although some times it look to have worked

I have tired moving storage from internal to external and vice versa.    I've also deleted the `live` storage directory.

In the current recreated `live` folder I have 3 files

```
Us_california_northamerica_19_16_16.obf
Us_california_northamerica_19_16_00.obf
Ireland_europe_19_00.obf
```

**Comment by MegaArthur** [comment]
I experience a similar error here, forcing the OSMAndLive download twice fixes it temporarily

**Comment by alex9099** [comment]
Same here

**Comment by vshcherb** [comment]
Is it fixed? Try to redownload please now

**Comment by cart0** [comment]
@vshcherb it is working in so much as I don't see the IO errors any more but it does not appear to download any updates.

Example:  https://www.openstreetmap.org/node/6553697764   I fixed a typo in the name tag 5 days ago and OsmAnd does not reflect that change

**Comment by vshcherb** [comment]
I just downloaded map enabled and it works. 
You probably need to clean all live updates and download them again because of the issue fixed recently.
![image](https://user-images.githubusercontent.com/1042025/59983036-f5e12580-961a-11e9-91da-25a6b914da8b.png)

**Comment by cart0** [comment]
@vshcherb  thanks I just noticed that other changes I made yesterday were showing up in live already so I guess it's as you say a hang over from problem
