### ISSUE TITLE
Routing anomaly: Routes through car park instead of staying on main road

### ISSUE THREAD

**Issue by martenjj** [osmandapp/Osmand#7044]
Routing engine: OsmAnd+ internal
Start point: 46:58:32.54883 Stanserstrasse, Stansstad, CH
End point: 46:58:29.51385 Stansstaderstrasse, Stansstad, CH
Profile: Car, fastest route, no height/weight limits
App version: 3.3.8
Offline map data file: UK Europe Switzerland, standard map, 1 May 2019

The logical route to follow between these points would be to stay on the yellow road and take the 2nd exit at the roundabout.  However, the calculated route as shown in the screenshot below leads through the car park, a left turn and back onto the roundabout.  OSRM on openstreetmap.org routes correctly.

![Screenshot_20190616-173217_OsmAnd+](https://user-images.githubusercontent.com/10631760/59566392-a49fc780-9057-11e9-8f92-68154b29ba17.jpg)

I can only guess, as possibly was the case in #5082, that the routing through the car park appears to be faster because the main roads and roundabout all have maxspeed=50, whereas the service=parking_aisle has none.

If this really is the case, then a suggestion to fix this issue would be to have a much lower desirability weighting for highway=service in general and for service=parking_aisle in particular.  If this is not possible then another fix could be to assume a very low maxspeed (say, for example, 10kph) for a service=parking_aisle which is not otherwise tagged with maxspeed.

**Comment by vshcherb** [comment]
Please check the map https://www.openstreetmap.org/relation/8349726 it looks restriction disallows this direction.

**Comment by martenjj** [comment]
That's a very odd turn restriction, especially as none exists on the ground at that point.  That node doesn't show any turn restrictions in the iD editor, so I suspect that the relation is not structured properly.  Should probably just delete the restriction relation.

**Comment by vshcherb** [comment]
If you now that area, please delete it. So the problem will be fixed

**Comment by martenjj** [comment]
Relation deleted on OSM.
