### ISSUE TITLE
iOS 64GB memory limit

### ISSUE THREAD

**Issue by WilfForrow** [osmandapp/Osmand#7053]
iOS version of OsmAnd map downloads limited to 64GB?

Version is OsmAnd iOS latest as at 19-Jun-2019.
Device is iPhone 6S, 128GB, latest version of iOS (12.3.1)
Do you use the offline maps offered within the OsmAnd app for download. Yes.

Map download shows Device memory as Free: 1.59 GB.
Actual Device memory shows as 61.4 GB free of 128 GB, (ie 66 GB free approximately).

Error message:  "Not enough space to update Netherlands - Map. 2.49 GB is needed.  Please free up some space."
I deleted another app to free up memory, and the map downloaded successfully.

I have screen images if you need them.

**Comment by vshcherb** [comment]
Moved

**Comment by PaulStets** [comment]
@WilfForrow Could you please attach a screenshot of the free memory on your device and a screenshot from OsmAnd's Maps & resources screen to the new issue?

**Comment by WilfForrow** [comment]
Does this mean it's been fixed?

Maybe I didn't explain - there's a bug in iOS OsmAnd app so it thinks my 128GB iPhone is only 64GB.

So the top 64GB of my phone is unusable, and I can't download any more OsmAnd maps without deleting other apps to get me below 64GB.

Many thanks

**Comment by PaulStets** [comment]
@WilfForrow It was just moved to the correct project. Please post further messages in https://github.com/osmandapp/OsmAnd-ios/issues/330

**Comment by WilfForrow** [comment]
OK, I didn't realise about the iOS project, thank you.

Images of OsmAnd app error message and iPhone storage attached.

![image](https://user-images.githubusercontent.com/2242419/59759341-c41d3700-9287-11e9-81e0-7bb4505a1cf0.png)

![image](https://user-images.githubusercontent.com/2242419/59759353-cbdcdb80-9287-11e9-917a-68ae0dbe6e12.png)

**Comment by PaulStets** [comment]
@WilfForrow Thanks for the screenshots. I will investigate the issue and report in the new thread.
