### ISSUE TITLE
Favorites and Markers History - Privacy Issue

### ISSUE THREAD

**Issue by lyndhurst** [osmandapp/Osmand#7055]
Hi, I use OsmAnd Exclusively the app on Android, version 3.3.8. 

I had a little application written in  Python on my computer to import Markers, Tracks, modify and delete them when I come back with new gpx data. I love the fact that folders and gpx files are easily accessible for import and programmatic modification.

A little while ago I would say around 3 month, my delete history routine stopped working for markers and favorites. Everything I delete always reappears after I open the application on the phone. 
I tried deleted the favourites backup archives in the backup folder, the ind.cache, the favourites.gpx file, nothing helps.

Markers are also kept in history even after the tracks they belonged to are deleted from the phone, and the only "clean up" method I found is quite tedious; Swiping them one by one in the history menu.
I would like to know if there is a way to programmatically delete all history from the application.

If not, would it be possible to add a simple way to delete all history (I am sorry if it already exists and did not find it).

Thank you for your help, and great gps application.

**Comment by vshcherb** [comment]
I think it is possible to delete from search history but not possible to delete visited points by GPX. We need to think how to provide such functionality cause the points are not visible when GPX is not enabled

**Comment by littlehelper** [comment]
Deleting all items from the search history works quite well. Thanks for the hint how to delete single map markers from the history by swiping.
Please add a similar option to delete all map markers from the history at once.

**Comment by vshcherb** [comment]
Closed with #8626 fix
