### ISSUE TITLE
Cross maps in Public transport profile

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7059]
It is impossible to calculate the route between Carvolth Exchange in Langley, BC and High Street Mall in Abbotsford, BC., despite the fact that there is a bus route with stops between these two places (bus route 66) in OsmAnd:
Lat 49.16037 Lon -122.66063
Lat 49.05901 Lon -122.38009

At the same time, route calculation works for the exact same route between:
Lat 49.03260 Lon -122.29291 
Lat 49.05901 Lon -122.38009

**Comment by xmd5a2** [comment]
Public transport routes crossing several maps are not yet supported

**Comment by vshcherb** [comment]
Supported in 3.7 fixed
