### ISSUE TITLE
[Feature request] GPX display

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7068]
When opening GPX tracks one-by-one, they all remain visible on the map. On the move, it would be convenient if there was a possibility to hide the previous GPX file while viewing the next one.

**Comment by ChristianKurz** [comment]
You need to be more clear. It is currently possible to selectively hide tracks. Do you want the tracks to automatically hide, once you have reached the endpoint?

**Comment by scaidermern** [comment]
The request is about going trough the list of GPX tracks, one by one. Upon opening a track it remains displayed on the map until you disable them again. As far as I understand tThe request is about disabling them again as soon as you open the next track.

**Comment by dmpr0** [comment]
Created by mistake.
