### ISSUE TITLE
Missing POI

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7070]
Some POIs are not displayed in OsmAnd despite the Live Subscription updates.

Berlin Map
52.51954 Lon 13.28057

In OSM the missing POI is displayed: 
https://www.openstreetmap.org/search?query=52.51954 13.28057#map=19/52.51958/13.28097

![image](https://user-images.githubusercontent.com/50198677/59857770-468a2180-9382-11e9-9e8c-cd8a01168df3.png)

**Comment by mbirth** [comment]
Although this location is in Berlin, the map used is "Germany Brandenburg" (which includes Berlin) and so are the Live updates for that map.

After doing "Update now", Live updates for this map show this:

```
Germany Brandenburg
Last map change: 20 Jun 2019 13:50
Last update: 20 Jun 2019 14:44
```

Yet the changes from Monday, 17 Jun are not shown. E.g. [this changeset](https://www.openstreetmap.org/changeset/71337186).

**Comment by mbirth** [comment]
Might be related to #7043 as I have that problem, too.

**Comment by mbirth** [comment]
Might also be related to #6572.

**Comment by scaidermern** [comment]
Really sounds like it could be caused by the same bug as #6572.

**Comment by mbirth** [comment]
I've now deleted the files from the `live` folder and also the `ind.cache` (all in `/sdcard/Android/data/net.osmand.plus/files/`) and after tapping "Update Now" again, my changes show up now.

Before, I had these files (from memory):
* `Germany_brandenburg_europe_19_06_00.obf` - ~6.6 MB
* `Germany_brandenburg_europe_19_06_19.obf` - some kB
* `Germany_brandenburg_europe_19_06_20.obf` - some kB

Now I have these:
* `Germany_brandenburg_europe_19_06_00.obf` - 8.0 MB
* `Germany_brandenburg_europe_19_06_21.obf` - 388 kB

**Comment by vshcherb** [comment]
Issue was identified. We've ran out some disk space on some servers and it was hard to trace some outdated files. Now everything should be consistent but it requires to redownload data
