### ISSUE TITLE
Support region with all OsmAnd Live subscriptions

### ISSUE THREAD

**Issue by rbovard** [osmandapp/OsmAnd#7073]
Hi there,

After an exchange with the support, I noticed that the support region feature is available only for the monthly subscription.

Is there a way to add this feature also for others subscriptions (3 months, annual) please?

Thanks in advance.

**Comment by vshcherb** [comment]
Well it affects the pricing because OsmAnd Annual Live has already 50% discount to the monthly subscription that's why it doesn't have OsmAnd Live Support program.
We consider to change subscription & pricing model .

**Comment by rbovard** [comment]
Okay, thanks for the feedback.
