### ISSUE TITLE
Maps unavailable for downloading

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7078]
In OsmAnd+ menu - Download maps - All downloads all the options for the downloads disappear except for Voice prompts.
Reinstallation does not help.
The issue occurs on Blackberry z30, Android 4 and Samsung Galaxy S 5, Android 6.

**Comment by vshcherb** [comment]
Internet is not available. That's the issue.

**Comment by katerynakocherhina** [comment]
Online tiles are available and displayed in both situations.
