### ISSUE TITLE
Add missing pictograms and remove redundant text in order to save space

### ISSUE THREAD

**Issue by Aiurek** [osmandapp/Osmand#7079]
I'd suggest adding a pictogram for the mobile no. and Instagram, while removing the wirtten text that eats up vertical space when it comes to the illustration of POI properties. Thereby, I'd say the smoking cigarette and toque are self-explaining and don't require additional text either.
Furthermore, what d'u think about adding an icon for "Access to toilets for wheelchair users" like illustrated in the image below?

![Bild1](https://user-images.githubusercontent.com/27865200/59926390-83b1ea80-943a-11e9-996f-3b0c4436c964.jpg)

**Comment by dmpr0** [comment]
Hello, @Aiurek! Thank you for the suggestion. I agree with you about adding new icons for fields unique fields without it, so I added the Instagram icon.
But I think that clarity of UI is important, and vertical space/scroll it's not a problem, icon works good, but not all the time, so I think we need to leave titles for Cuisine, Smoking, etc, but we can remove it for Instagram.

**Comment by vshcherb** [comment]
So, yes we are going to add 2 icons this release 3.4
