### ISSUE TITLE
Illustration of Hookah Lounges

### ISSUE THREAD

**Issue by Aiurek** [osmandapp/Osmand#7081]
There're a lot of hookah lounges here in Germany, but their tag is not yet illustarted at all in OsmAnd - as a result the spot is lillustrated empty, although the hookah lounge is tagged properly in OSM. 

Hookah lounges aren't normal bars since pretty often they do not own the license to serve alcoholic beverages - it's primarily a bar for smoking hookah (called Shisha in Germany).

https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dhookah_lounge

![Bild9](https://user-images.githubusercontent.com/27865200/59928643-7ba87980-943f-11e9-9897-06b375c29fe0.jpg)

**Comment by xmd5a2** [comment]
Added
