### ISSUE TITLE
OsmAnd Live Crashes in Turkish Language

### ISSUE THREAD

**Issue by omerfaruk-cakmak** [osmandapp/Osmand#7082]
As I stated in the title OsmAnd Live crashes in Turkish interface. At first entering to the OsmAnd Live there is no problem, but after doing some settings at OsmAnd Live and click OK (in Turkish: Tamam) app crashes. After app crashes when I try to enter to OsmAnd Live again app crashes again but when I change interface language to English there is no problem. I tried it on two phones and gave same result.

**Comment by MadWasp79** [comment]
fixed with https://github.com/osmandapp/Osmand/commit/e2fc259ddad1daac350291e031ad3508249eaa00
