### ISSUE TITLE
GPX recording stops when phone is locked while OsmAnd+ is not in foreground on Adroid 8.1

### ISSUE THREAD

**Issue by e-pirate** [osmandapp/Osmand#7083]
Hello.
I'm having problems with GPX recording on an Android 8.1 device. 
If device is locked with OsmAnd+ not in foreground, GPX recording will stop 5~10 seconds after power button was pressed. Navigation icon and corresponding GPX notice will despairer from the lockscreen as well. If OsmAnd+ app is in foreground when devices is locked, GPX recording work as expected.
As advised by Kate from support team, I have: background data usage enabled for OsmAnd+ in device settings (I have no clue how this affects navigation, this option is related to background Internet data transmission, but anyway). Besides, I have all of three Logging motion detection, Logging minimum accuracy and Logging minimum speed unset. Power/battery saving is off, Navigation is enabled explicitly for OsmAnd+.
I seems to me this issue is directly related to Android API level 26 as described [here](https://hackernoon.com/android-location-tracking-with-a-service-80940218f561).
OsmAnd+ version: 3.3.8
Smartphone: BlackView BV9500 Android (just a vanilla Android 8.1 with no manufacturer stuff at all).

**Comment by crimean** [comment]
We use "foreground service" already. You should see notification while gpx is recording.

**Comment by e-pirate** [comment]
I can see an "waypoint" icon in the notification area at the top left of the screen and a slide notice on the lock screen with the same waypoint pictogram showing the time of recorded GPX. They will disappear in 5-10 seconds if a lock the smartphone with OsmAnd+ not left in foreground.

**Comment by vshcherb** [comment]
Please check https://dontkillmyapp.com/

**Comment by sonora** [comment]
@vshcherb I think the fixes I had applied for #5632 are not in the latest release yet ... may be worth a 3.3.9 ?

**Comment by vshcherb** [comment]
@sonora working extremely hard to get beta of 3.4 end of this week. Probably if we don't make it some issues will be in 3.4.5 but beta still will be in June!

**Comment by e-pirate** [comment]
@vshcherb Information provided on dontkillmyapp does not help. Rooting the device is not an option either.
