### ISSUE TITLE
New profiles, options missing

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#7091]
In current version (3.3.0#27608 date 24/06/2019) with new profiles I am missing some options:
Profile is derived from default (auto OsmAnd-routing) or my own (with same mission options).

In Configure screen missing:
- Intermediate destination
- Intermediat arrival time
- Destination
- Arival time
Left panel
- Next turn
- Next turn (small)
- Second next turn

**Comment by vshcherb** [comment]
Default doesn't have these parameters and it should be banned to derive any routing profile. So we need to fix possibility to create it.

**Comment by IgorEliezer** [comment]
> Default doesn't have these parameters

I have similar issue, but with profile derived from a base profile.

At the current situation (3.3.0 24364d), if you use for example "Car" base profile to create another, the widgets "Next turn", "Next turn (small)" and "Second next turn" are not available in the Configure Screen > Left panel.

Car base profile:
![image](https://user-images.githubusercontent.com/4673289/60054462-03e18580-96b1-11e9-9de5-c462238eaa5d.png)

Profile derived from above:
![image](https://user-images.githubusercontent.com/4673289/60054456-fdeba480-96b0-11e9-81ef-e0e6c2ad3c54.png)

The others which @pebogufi mentioned are there.

**Comment by pebogufi** [comment]
In 3.3.0#27617m if is fixed. 
Thanks a lot.

**Comment by IgorEliezer** [comment]
> In 3.3.0#27617m it is fixed.

Just updated the nightly version, I was using a build from a few hours ago. Confirmed the fix. :+1:
