### ISSUE TITLE
Feature request: show altitude when measuring distance

### ISSUE THREAD

**Issue by rradar** [osmandapp/OsmAnd#7096]
Please add the feature to show altitude when the user draws lines by Measure distance tool.

Would be great to have the possibility to show (something) like this for the line measured by the distance tool. :+1: 
![image](https://user-images.githubusercontent.com/34582688/60099001-adc31f80-974e-11e9-8876-dc4de1ac3c71.png)

This is kind of an addition/extension for/of #6345

**Comment by vshcherb** [comment]
It will be possible only when it is snapped to road but I guess we could display it in bottom context menu.

**Comment by rradar** [comment]
Thank's @vshcherb for you feedback.
Actually I'm interested in the surface elevation without road. Idea is to have to points, measure distance and get an idea if there is a line of sight.

There is a implementation with google maps on this site here: https://www.solwise.co.uk/wireless-elevationtool.html

For my understanding all available data is in the (openstree)tmap - isn't it?

**Comment by vshcherb** [comment]
![image](https://user-images.githubusercontent.com/1042025/113915212-c5ae4b00-97de-11eb-94a7-d3ed03ca06f7.png)
