### ISSUE TITLE
Favorites not displayed on map

### ISSUE THREAD

**Issue by Dreykodoon** [osmandapp/Osmand#7101]
The favorites no longer appear as points on the map, even though Favorites is activated in the "Configure map" menu.

Specs:
OsmAnd+ 3.3.8
Android 9

**Comment by vshcherb** [comment]
You favorites are probably disabled, please check it in My Places -> Favorites

**Comment by Dreykodoon** [comment]
Under _My Places -> Favorites_ I have multiple categories I have created. For each one, in its settings menu (which opens when I press the "three vertical dots" button), there is a flag called _Show on map_. For all my categories, this flag is active (set to true).

Are you referring to that?

**Comment by vshcherb** [comment]
Yes, I'm referring to it though now I don't have any answer why are they missing

**Comment by Dreykodoon** [comment]
How I reproduced the problem:

- Rename a Favorites group to "Personal"

**Result**: all points in that group are added to map markers and the points are no longer visible.

If I go to the menu of that group and click "Remove from map markers", then the points are again visible on the map.

Hope this helps.

**Comment by vshcherb** [comment]
It is indeed confusing but you need to delete favorites from markers, so you need to go to Favorites and click on the group (3 dots) and click remove from markers. 

The issue: all poitns where marked as passed and where not displayed because they were in the history of map markers
