### ISSUE TITLE
Add big icons to profiles

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#7104]
![image](https://user-images.githubusercontent.com/1042025/60169437-f6d6aa80-9806-11e9-8d81-76107fd08fe4.png)

Currently only small icons are present in ApplicationMode, so it makes a wrong picture on a tablet screen

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/commit/5981f07990fc6f155f7f17c33a5ad65adfcb052a

**Comment by MadWasp79** [comment]
fixed with https://github.com/osmandapp/Osmand/pull/7105
![image](https://user-images.githubusercontent.com/13146346/60178817-f816d000-9824-11e9-9fc0-e2e173c3d35e.png)
