### ISSUE TITLE
Display description and travel card in tracks

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#7106]
![image](https://user-images.githubusercontent.com/1042025/60184295-17fbc300-9828-11e9-9be7-208f3ec61409.png)

**Comment by vshcherb** [comment]
![image](https://user-images.githubusercontent.com/1042025/60184426-585b4100-9828-11e9-84ff-e5776395355a.png)

**Comment by dmpr0** [comment]
Export tracks from "Travel" doesn't add a description to the gpx file.

**Comment by vshcherb** [comment]
The code looks like this: 
<metadata><desc><![CDATA[ ... html-code ... ]]></desc></metadata>
