### ISSUE TITLE
[Feature request] next POI always displayed during navigation

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7109]
It is a limited option available to select the distance, within the POI should be displayed.
It would be convenient if the next POIs on the route were always displayed, even beyond the 5 km limit.
![image](https://user-images.githubusercontent.com/50198677/60188562-2f42ac80-9838-11e9-8f64-c31edddb3e7d.png)

**Comment by vshcherb** [comment]
Within - is the radius and it is different from the point when the next waypoint will be displayed.

**Comment by jimmy6k** [comment]
Yes, I'm touring with my motorcycle and it would be very convenient for me if I could see every time the next fuel station on my trip "within" 200 m.
