### ISSUE TITLE
[bug?] [Pedestrian routing]: stop and traffic_calming announced through voice guidance

### ISSUE THREAD

**Issue by serpico** [osmandapp/Osmand#7118]
Please give us the following information so that we can try to **reproduce** your issue:

When using pedestrian routing, (at least some) traffic_calming ( I'm guessing either this [one](https://www.openstreetmap.org/node/6449004545) or that [one](https://www.openstreetmap.org/node/6449004546) ) and highway=stop ( I'm guessing this [one](https://www.openstreetmap.org/node/4881113365) )  are ( unnecessarily ) announced through voice guidance.

What version of OsmAnd are you using, on what device and Android/iOS version?
**OsmAnd~ 3.3.8 from F-Droid, Samsung SM-G361F and Android 5.1.1**

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?
**offline map**

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.
**France Normandie 1st June 2019**

__*In case of wrong routing:*__

Tell us whether you have used OsmAnd's in-app offline routing, or any online routing provider like YOURS, OpenRouteService or OSRM.
**OsmAnd's in-app offline routing**

What routing profile is chosen in OsmAnd app? (car, bike, pedestrian, fastest or shortest)
**Pedestrian**

Please specify as exactly as possible the start and end point of your route by telling us city name and street name so that we can find it via in-app address search easily. Also, a permalink from openstreetmap.org can be helpful.

start point : https://osmand.net/go.html?lat=49.45783&lon=1.04521&z=15
end point : https://osmand.net/go.html?lat=49.47642&lon=1.05262&z=15

Although I going through https://www.openstreetmap.org/way/448792699 and https://www.openstreetmap.org/way/123645161

Tell us your expected routing, and how OsmAnd routes, or add screenshots here.

I'm wondering if they should be announced, knowing that traffic lights and many other features are not announced in pedestrian routing.

**Comment by OpenSourceForEver** [comment]
You can dissable announces in settings ->navigation settings -> announce...

**Comment by serpico** [comment]
Thanks @OpenSourceForEver for pointing this out.
I checked the mentioned screens but it's not clear which one I should disable ( Traffic warnings seems to be the closest related but I haven't checked what disabling it gonna produce, I will and report back ).

Maybe with 3.4 shipping the custom profile feature, there's gonna be some change here too.

**Comment by OpenSourceForEver** [comment]
Traffic warnings should disable stops and traffic calming. Try it please
