### ISSUE TITLE
Online search not possible for places far away

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#7123]
Searching for places far away via online search is not possible. For example I'm trying to use online search for a large city about 1400 km away. There is a button for increasing the search radius but it dissapears after reaching 200 km. I guess it performs a global search now. However there are still just two unrelated results. Nominatim is quite good at global searches, however not when being called from OsmAnd?

![IMG_20190628_225249](https://user-images.githubusercontent.com/1040784/60370853-e6d1ed00-99f7-11e9-8733-ecfc97b2ed47.jpg)

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd/pull/11746

**Comment by vshcherb** [comment]
Now radius search increases from 20 km -> 100 km -> 500 km -> 10 000 km

**Comment by pebogufi** [comment]
Great !!!
