### ISSUE TITLE
Drinking water POIs disappeared

### ISSUE THREAD

**Issue by clementcontet** [osmandapp/Osmand#7124]
Recently, I can't search anymore for drinking water POIs. If I browse the map, they are still present (and when I click on one, the description is in English "Drinking water" where it used to be in French "Eau potable").
I think the bug came with the latest offline map updates, and not from an app update (but I'm not 100% sure).

I use the OsmAnd+ 3.3.8 with France offline maps from June 1st 2019. I tested the app both with French and English languages.

**Comment by Gniourf** [comment]
I'm having the same problem (and it put me into trouble last week with the heat wave we had in France). Like @clementcontet I suspect it comes from maps and not from the app. Can this be sorted out and fixed quickly, as there are some people relying on this feature?

**Comment by clementcontet** [comment]
It seems it was already reported:
https://github.com/osmandapp/Osmand/issues/7110

https://groups.google.com/forum/#!topic/osmand/64v-Mir33No

**Comment by xmd5a2** [comment]
drinking_water POI were moved from "Sustenance" to "Drinking water" category but until next release they will not be available for searching because category in new maps does not match category in current release. You can use nightly version or wait for release 3.4.
