### ISSUE TITLE
Show photos from Wikidata

### ISSUE THREAD

**Issue by jluttine** [osmandapp/Osmand#7131]
OsmAnd shows online photos from Mapillary. I think it'd be great to (also) show photos from Wikidata when `wikidata` tag is set. There are lots of good quality photos available in Wikidata.

**Comment by Adamant36** [comment]
Or maybe better Wikimedia Commons. Although it could be both.

**Comment by jluttine** [comment]
I had thought that all photos in Wikimedia Commons tagged to some object in Wikidata would show directly in Wikidata. But apparently not! Probably because of licensing issues (Wikidata requires CC0 but many photos in Wikimedia Commons are under CC-BY-SA). So thanks for the suggestion!

Wikidata provides a link to Wikimedia Commons page that contains those photos. So there should be no need for any additional tags. The "photo scanner" that scans based on the `wikidata` tag should recurse to the Wikimedia Commons page too if such link exists on the Wikidata page.

By using wikidata tag, Osmand could also provide links to Wikivoyage and Wikipedia pages (if separate `wikipedia` tag isn't set).

**Comment by njohnston** [comment]
There are many objects with a Wikidata ID but not the corresponding Wikipedia article, for example [Juanda International Airport](https://www.openstreetmap.org/way/312366913). (It has the Indonesian Wikipedia article but not in any other 21 languages.)

I'd also like to see general Wikidata data support. Perhaps this could be displayed as "quick facts", for example listing things like opening date, elevation, IATA code, ...

**Comment by jluttine** [comment]
Actually, I need to correct myself: It is very much possible that some objects use [`wikimedia_commons`](https://wiki.openstreetmap.org/wiki/Key:wikimedia_commons) tag and they don't have [`wikidata`](https://wiki.openstreetmap.org/wiki/Key:wikidata). This makes perfect sense in many cases (e.g., some object just happens to be visible in a photo but it's not worth a Wikidata page of its own or there's a Wikidata entry of some larger object that contains this object in the photo or people just don't put everything to Wikidata).

If `wikidata` tag given:

- Direct images from the Wikidata page (values of `image` statement).
- Images from the corresponding Commons Categories (values of `Commons category` statement) and then recurse as one would for `wikimedia_commons=Category:....` tag.
- Maybe images from the corresponding Commons Galleries (values of `Commons gallery` statement), but I'm not sure if this makes sense. Probably not?

If `wikimedia_commons` tag given:

- `File:....`: The image from the Commons File page. (If it's an image.)
- `Category:...`: All images from the Category page (and recursively of sub-categories?).

Finally, remove duplicates.

**Comment by pangoSE** [comment]
I suggest using this tool to fetch the images from wikidata where present. It only shows one/the preferred image though. https://tools.wmflabs.org/hub/
If you want all the images you can use the getclaims api. I have done that in a js project that I can share here if you want.

**Comment by pangoSE** [comment]
@nazar-kutz fantastic work! Was my code any help for you?

**Comment by nazar-kutz** [comment]
@pangoSE Yes! Thank you too much :)

**Comment by pyrog** [comment]
I don't see picture for https://www.openstreetmap.org/node/1572748364
Does something must be set in the preferences ?

**Comment by egils-consulting** [comment]
I suggest you open a new issue instead.

**Comment by pyrog** [comment]
Already done : https://github.com/osmandapp/OsmAnd/issues/9585
