### ISSUE TITLE
Wrong turn on the roundabout

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7135]
OsmAnd suggests turning left, while it is only clockwise turn available.

51.36764 6.19058 
51.32616 6.23993

Roundabout placement: 
51.34671 6.19216

OsmAnd
![image](https://user-images.githubusercontent.com/50198677/60440957-aacca100-9c1e-11e9-8866-59464b7096c7.png)

OpenStreetMap
![image](https://user-images.githubusercontent.com/50198677/60440689-03e80500-9c1e-11e9-9284-d0f56443de5f.png)

**Comment by scaidermern** [comment]
Did you cross the border during your drip? If so this could be related to #7061. However there is no country with a different driving direction nearby.

**Comment by vshcherb** [comment]
reproduced related only to roundabouts (C++ bug)

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-core/commit/8fa463b6c871abbc7690ed1391ab3d4451e5b5e6
