### ISSUE TITLE
3.4.0 Beta file routing.xml no longer used

### ISSUE THREAD

**Issue by quax2712** [osmandapp/Osmand#7137]
Since version 3.4.0 (last week) my Routing.xml file in the folder ... /files is no longer recognized.
I found a new folder ../files/routing. Copying my Routing.xml file to this folder has no effect too.

best regards
Rainer

**Comment by pebogufi** [comment]
now you need to create an app profile to use your routing file, you can do it in Settings > App Profiles > Add > Select base profile > Navigation type > Selecting an item from your custom file.
(above text copied from https://github.com/osmandapp/Osmand/issues/7001)

**Comment by quax2712** [comment]
thank you, it works. 
As on my version 3.3 beta routing.xml did work "old normal" I only looked at newer issues.
regards
Rainer
