### ISSUE TITLE
Currently selected app profile hardly / not visible on routing dialogs

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#7138]
The headline almost says it all: Ever since we changed our navigation / route definition screen to show blue app profile logos, the one actually selected is hardly visible in the light app theme, and not at all in the dark app theme. I guess we need to show a little underline bar or similar to highlight the selected one better.

![Untitled](https://user-images.githubusercontent.com/845735/60460742-dc586300-9c44-11e9-9fff-645b1812d0f4.png)

**Comment by pebogufi** [comment]
+1 !

**Comment by scaidermern** [comment]
I think it is better to show only the currently selected profile in blue and leave the other profiles in white/gray.

**Comment by vshcherb** [comment]
Profiles have different color and same icon so we need to fix it differently
