### ISSUE TITLE
Feature request: avoid paved roads

### ISSUE THREAD

**Issue by macintoshee** [osmandapp/Osmand#7148]
Lots of people are using OSMAND as navigation app/device for motorcycle riding, it is specially popular in enduro and off-road riders groups. Riding on pavement with small displacement motorcycle (125-450cc) is pain and very-very boring. Finding out by looking at map which route to take to avoid pavement is extremely time consuming and does not still warranty success. There is an option in settings "avoid unpaved roads". Can we have similar option for paved roads: "avoid paved roads (when possible)".

**Comment by hakuchi** [comment]
Maybe for this can be made a new aplication profile "Off-Road".
Then this can be used from car and motorcycle if you preffer to drive off road.
In normal car profile should not implemented a avoid paved roads or similar.

In the "Off-Road" profile maybe can be implemented some aditional function to avoid only ground, gravel, coblestone, asphalt etc.

**Comment by macintoshee** [comment]
> Maybe for this can be made a new aplication profile "Off-Road".

Based on that idea I would implement bit differnt way. I would use options below as completely forbidding paved roads (off) would not work. Options would be:
* prefer gravel roads
* allow tracks

In this case routing would be done using primarily those two road types and paved roads are used just when other road types are not available.

**Comment by jfburke3** [comment]
I was thinking something similar for those of us who do offroading.

Perhaps a simpler way to implement it might be "prefer unpaved roads" which simply gives a much higher weight to those, but wouldn't avoid paved ones entirely, if they were needed to get from one unpaved road to another.

**Comment by macintoshee** [comment]
> Perhaps a simpler way to implement it might be "prefer unpaved roads" which simply gives a much higher weight to those, but wouldn't avoid paved ones entirely, if they were needed to get from one unpaved road to another.

Its good idea but It solves probably half or problem. Still need somehow add unclassified, unsurfaced and tracks to the equation. CoPilot has so called preference list, where you can create profile with roads accoring your personal prefrence. You can select preference for every road type:
* strongly avoid
* avoid
* neutral
* favor
* strongly favor

**Comment by naoliv** [comment]
> > Perhaps a simpler way to implement it might be "prefer unpaved roads" which simply gives a much higher weight to those, but wouldn't avoid paved ones entirely, if they were needed to get from one unpaved road to another.

This would solve a lot cases here (and also offer a wider range of possibilities)
See https://github.com/osmandapp/Osmand/issues/3435#issuecomment-274919316

**Comment by vshcherb** [comment]
Here we could probably implement *4wd_only* tag requested above

**Comment by vshcherb** [comment]
. As I envision it, the "allow unpaved" setting would presumptively exclude roads also tagged "4wd_only=yes" and seriously handicap routes tagged "4wd_only=recommended" unless a separate "allow 4wd" setting is enabled.

**Comment by macintoshee** [comment]
1. Simplest would be "prefer unpaved roads" in witch case paved roads would be used as a last resort. 

2. Best and most flexible approach would  be add road profile to vehicle where you can override whatever roadtype you want and set preferences (strongly avoid, avoid, neutral, favor, strongly favor).  It also need to have "highway=path" considered. 

3. Add 4wd option for road profile options

**Comment by lbdroid** [comment]
I'm thinking that this feature probably should be thought of in a larger context; there are a number of different KINDS of prefer off road vehicles with different types of roads that they can use.

1) Bikes, preferably semi-hard surfaces, can be narrow paths,
2) ATV, semi-hard and soft surfaces, can be semi-narrow paths,
3) Automotive 4x4, semi-hard, full-width paths,
4) Trail snowmobiles, require groomed snowmobile paths,
5) Off-trail snowmobiles, prefer to climb the sides of mountains and use groomed trails just to get from mountain to mountain.
6) Amphibious vehicles like Argo or Sherp, prefer soft, swamp, and limited open water.

And while I don't suggest necessarily implementing all options simultaneously, the thought of expanding the feature to include more vehicle types should at least guide the development of the first one to avoid doing things twice.

**Comment by macintoshee** [comment]
> 1. Bikes, preferably semi-hard surfaces, can be narrow paths,
What you mean with "bikes"? Motorcycles or actual bikes i.e. bicycles?

**Comment by bhugh** [comment]
Gravel riding is a big and growing thing in the bicycle world.

It is probably a slightly different use case than, for example, 4 wheel drive off-roading because bicycles will often use or prefer soft-surface paths or trails to connect the gravel or soft-surface road options where available--whereas 4WD motor vehicles wouldn't be allowed on those, as a rule.

**Comment by xmd5a2** [comment]
Fixed by https://github.com/osmandapp/OsmAnd-resources/commit/d26f1d1ee2e85475be3b73289e31fce6cd1db6b8
and
https://github.com/osmandapp/OsmAnd-resources/commit/6d3f216973886cee1c7ccca84355862a9e1b7dee
