### ISSUE TITLE
Track split interval lost when editing track points

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#7150]
The split interval setting is lost when adding or removing points from the track. The track color **doesn't** get lost.

**Comment by vshcherb** [comment]
Can't reproduce, I still see that option after adding a point, probably track needs to reopened or refreshed.

Please attach screenshots

**Comment by scaidermern** [comment]
You can see the split marker vanishing after deleting a track point: https://imgur.com/a/pMCKRR5

**Comment by vshcherb** [comment]
Merged into #7501
