### ISSUE TITLE
AIDL API  showMapPoint  exception

### ISSUE THREAD

**Issue by fsbugreporter** [osmandapp/Osmand#7155]
I am not able to get any visible response on the following click sequence "Add layer", "Add point", "Show map point", "Refresh Map" within the OsmAnd API Demo.

adb shell logcat shows the following exception in the OsmAnd app:

```
07-04 18:38:39.348 27694 27707 I net.osmand: OsmandAidlService Request AIDL API for showMapPoint
07-04 18:38:39.349 27694 27707 E net.osmand: OsmandAidlService AIDL e.getMessage()
07-04 18:38:39.349 27694 27707 E net.osmand: java.lang.NullPointerException: Attempt to invoke virtual method 'double net.osmand.aidl.map.ALatLon.getLatitude()' on a null object reference
07-04 18:38:39.349 27694 27707 E net.osmand:    at net.osmand.aidl.OsmandAidlApi.showMapPoint(OsmandAidlApi.java:1177)
07-04 18:38:39.349 27694 27707 E net.osmand:    at net.osmand.aidl.OsmandAidlService$1.showMapPoint(OsmandAidlService.java:336)
07-04 18:38:39.349 27694 27707 E net.osmand:    at net.osmand.aidl.IOsmAndAidlInterface$Stub.onTransact(IOsmAndAidlInterface.java:557)
07-04 18:38:39.349 27694 27707 E net.osmand:    at android.os.Binder.execTransact(Binder.java:573)
```

What version of OsmAnd are you using, on what device and Android/iOS version?
Tested on following setup:

Android 7.0 (Samsung Galaxy Tab S2)
OsmAnd~ 3.4.0#11632mqta 2019-07-04
OsmAnd-API-demo.apk  2019-04-03

**Comment by fsbugreporter** [comment]
It seems that git commit 62a5d46be207866ab95e8d30432869951b066766 changed OsmAnd/src/net/osmand/aidl/maplayer/point/AMapPoint.java and broke AIDL API compatibility to the OsmAnd API Demo. The newly added String layerId does not exist in the API Demo. 

a quick fix would be to copy the new OsmAnd/src/net/osmand/aidl/maplayer/point/AMapPoint.java to 
osmand-api-demo/app/src/net/osmand/aidl/maplayer/point/AMapPoint.java

and update showMapPoint, addMapPoint  and updateMapPoint in 
osmand-api-demo/app/src/main/java/net/osmand/osmandapidemo/OsmAndAidlHelper.java

**Comment by vshcherb** [comment]
This commit is not compatible https://github.com/osmandapp/Osmand/commit/30b444bcd68b86e2b419126fa5d4011b42960718#diff-981936373e9294c3b591b13c9c21e0fbR114
