### ISSUE TITLE
[Feature request] Map legend in different languages

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd#7158]
It would be convenient for non-English speaking users to use Map legend in their language or at least in other international languages (Russian e.g.). Currently, the map legend is displayed in an image format, so it is impossible to copy description for map objects and use a translator as a workaround.

**Comment by letypequividelespoubelles** [comment]
And to have it offline too !  See #7441

**Comment by vshcherb** [comment]
Duplicate
