### ISSUE TITLE
Romania map

### ISSUE THREAD

**Issue by GabrielSebastianMoise** [osmandapp/Osmand#7164]
I want to let you know, that Romania map, has some big issues and the file needs to be recompiled.
Yesterday I've noticed that someone has introduced in the OpenStreeMap , new motorways in Romania, and I've sent a notification to DWG, and they reverted all changes made by that user, in our country and also in another two .
We managed to repair a very big multipolygon, and routing for another major road in our country, that were affected by mistake , by another two users.

Now all the things are good, and we want you to push an update for Romania Map, to help other users to receive de quality of the map as should be.

OsmAnd+ Android

Thanks !

![image](https://user-images.githubusercontent.com/5286676/60748105-3df53600-9f93-11e9-92e8-99a4c819af03.png)

**Comment by vshcherb** [comment]
Unfortunately we're quite limited cause our process of delta maps relies on the map to be built at 1st of July 00:00, so in that case we can either try to keep the old one of 1st June or wait till August with broken map.

OsmAnd Live maps should have last hour version
