### ISSUE TITLE
Feature request: Navigation profile to save Overlay,Underlay

### ISSUE THREAD

**Issue by seahorse41** [osmandapp/Osmand#7165]
I like the configurable idea for navigation in version 3.4.0. 
To make it better, it would be nice to save the Overlay map and Underlay map settings. 
I see it does save the Contour line setting. This is good. Is this a bug or missed part of the feature?

From Settings.. Application profiles.. pick one.. Setup profile it says Profile keeps it's own settings, suggesting this is a bug.

Also, if I select Configure map and then after changing anything or not, if I tap <-- back it does not go back, but instead closes the settings screen. So that I never get back to the Cancel/Save screen. Perhaps that is intentional, that it always saves immediately, but it does break the menu tree or natural expected flow.

**Comment by vshcherb** [comment]
Yes in our plans for 3.5
