### ISSUE TITLE
Explanations for translatable strings

### ISSUE THREAD

**Issue by comradekingu** [osmandapp/Osmand#7166]
https://hosted.weblate.org/translate/osmand/main/nb_NO/?checksum=a087e039ede4329e
DD.DDDDDD°

https://hosted.weblate.org/translate/osmand/main/nb_NO/?checksum=1aacc8ebd6d471f8
GPX file with note locations.

location notes?

https://hosted.weblate.org/translate/osmand/main/nb_NO/?checksum=c10efb27d882fc4d
"average"
Verb or noun?

https://hosted.weblate.org/translate/osmand/main/nb_NO/?checksum=14b94272dddc29d1
"Recording %1$s %3$s %2$s"
verb noun, what are the placeholders?

https://hosted.weblate.org/translate/osmand/main/nb_NO/?checksum=ad53cf604dba5bb2
and
https://hosted.weblate.org/translate/osmand/main/nb_NO/?checksum=c887eea6e7ae197
"Middle east"
Does this include Egypt or not?
Did the quality change?

https://hosted.weblate.org/translate/osmand/main/nb_NO/?checksum=9b36d7ec7690e962
"left-forward"
Is this a direction, one before the other?

https://hosted.weblate.org/translate/osmand/main/nb_NO/?checksum=f5ddf5d71a409c4b
"Specify the web address with parameter syntax: lat={0}, lon={1}, timestamp={2}, hdop={3}, altitude={4}, speed={5}, bearing={6}."

Are these meant to be translated? Both exist.

https://hosted.weblate.org/translate/osmand/main/nb_NO/?checksum=757e7843eee64a98 "Specify a time buffer to keep locations to send without connection"

What kind of connection, buffer seems redundant

**Comment by vshcherb** [comment]
- Degree format DD.DDDDDD
- GPX file with location notes.
- Middle East includes - nope quality is average on this area
- Average - noun 
- "Recording %1$s %3$s %2$s" - noun - placeholders are description, time, type
- Address should not be translatable
- Specify a time buffer to keep locations without internet connection
