### ISSUE TITLE
Translatable string fails RTL

### ISSUE THREAD

**Issue by comradekingu** [osmandapp/Osmand#7168]
https://hosted.weblate.org/translate/osmand/main/nb_NO/?checksum=49d6e755e62fd137

has route.xml left-aligned. Should be a placeholder so it can be placed anywhere.

Possibly it should be xml.routename, but not sure.

![bilde](https://user-images.githubusercontent.com/13802408/60761744-e87e5f00-a04e-11e9-8659-040133a803d6.png)

@yarons What do you think?

**Comment by yarons** [comment]
That's correct.

Can you try and take a screen shot of the Hebrew version?

Thanks!

**Comment by iriman** [comment]
If the variable was present on the translatable string, there was also some workarounds such as rewording, or using RLM at begining, so that the string begin with a right to left character. But the proper solution is what yarons mentioned.

**Comment by vshcherb** [comment]
Now you should be able translate as:
"%s can be imported as Favorites or a GPX file."
or 
"Can be imported as Favorites or a GPX file %s"
https://github.com/osmandapp/Osmand/commit/06fc69d0f3305e676c1f84a8d7611a3e299d3718
