### ISSUE TITLE
Cebuano Wikipedia articles mixed in with English

### ISSUE THREAD

**Issue by l0b0** [osmandapp/Osmand#7169]
#6814 is not yet fixed - Most of the articles I come across are Cebuano, not English.

What version of OsmAnd are you using, on what device and Android/iOS version?

**OSMAnd version 3.3.8 on a Nokia N6 with Android 9.**

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps? **Offline only**

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date. **Wikipedia Oceania from 2019-06-04**

Screenshot:

![60761893-b13b9c80-a0a6-11e9-9529-3939b469cd46](https://user-images.githubusercontent.com/168301/60761916-50609400-a0a7-11e9-8873-f9f36949a758.png)

**Comment by vshcherb** [comment]
Can't reproduce. Please select "Wikipedia English" as POI overlay and not "Wikipedia". We are planning to change UI to make it more transparent to select preferred languages

**Comment by vshcherb** [comment]
Tested in New Zealand with 3.4

**Comment by ColinLeath** [comment]
I have this problem and have had it for years. Why are there more wikipedia POIs in cebuano or whatever language it is than English? Really limits the effectiveness of wikipedia + osmand.

![Screenshot_20200906-090616_OsmAnd+](https://user-images.githubusercontent.com/12736628/92328802-8dfcdc00-f020-11ea-9657-cb7d4ac765a0.jpg)

![Screenshot_20200906-090647_OsmAnd+](https://user-images.githubusercontent.com/12736628/92328808-98b77100-f020-11ea-9157-67cadc78b288.jpg)

![Screenshot_20200906-090640_OsmAnd+](https://user-images.githubusercontent.com/12736628/92328811-9ead5200-f020-11ea-9db1-e8cc99467d9e.jpg)

**Comment by ColinLeath** [comment]
The issue appears to be that cebuano is the most popular language for location-based wikipedia POI info.

I just turned off "display nearest POIs" and now have only wikipedia turned on. So the wikipedia articles/pois that display now are all English, but there are far far fewer of them.

Frustrating that philipinos who speak cebuano have done a better job of indexing the world that English speakers.

If that is indeed what happened.

**Comment by ColinLeath** [comment]
Here's part of the answer:

https://www.reddit.com/r/WikiInAction/comments/8x82kl/cebuano_wikipedia/?utm_medium=android_app&utm_source=share

https://www.google.com/search?&q=cebuano+wikipedia

https://www.vice.com/en_us/article/4agamm/the-worlds-second-largest-wikipedia-is-written-almost-entirely-by-one-bot

**Comment by ColinLeath** [comment]
A solution would be to add a feature to remove non-[default language] POIs from appearing when "display nearest POIs" is selected.
