### ISSUE TITLE
wrong bicycle routing since 3.4 beta

### ISSUE THREAD

**Issue by quax2712** [osmandapp/Osmand#7176]
Here is a situation that has realy strange Routing behavier:
https://www.openstreetmap.org/#map=19/49.40046/8.57872
I think it is because of Intersection Tag.

**Comment by quax2712** [comment]
![Bicycle_routing_3 4_net osmand plus](https://user-images.githubusercontent.com/42236280/60771702-def70480-a0eb-11e9-9b74-ef7843da35ec.jpg)
Here the example

**Comment by vshcherb** [comment]
Couldn't reproduce it anymore the route is very small may be it worth to try other combinations though I tested all possibilities with today's map. Please try with OsmAnd Live

**Comment by quax2712** [comment]
Version 3.4.2 and 3.4.3 work.
Thank you
