### ISSUE TITLE
Suggest to download map in Search

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#7179]
# Reviev

- [x] Two items after tapping of "Increase search radius.

<table style="width:100%">
  <tr>
    <th><img src="https://user-images.githubusercontent.com/9365308/150101946-e9b65432-39ce-423c-be96-13f4337e943c.png"  width="200" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/9365308/150101950-9248d9ae-f557-4603-b327-66770382511d.png"  width="200" height="auto"/> </th>
  </tr>
</table> 

- - - - - 
- [ ] #13652
<table style="width:100%">
  <tr>
    <th><img src="https://user-images.githubusercontent.com/9365308/150102123-8f63f17b-f742-4a34-aae5-588f572b5e9c.png"  width="200" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/9365308/150102132-1f5b31aa-1d7f-4074-8ea1-3dc18dea92c3.png"  width="200" height="auto"/> </th>
  </tr>
</table> 

# ToDo
Suggest to download a map in Search
If a user searches for city/region or country name show download map item as first result similar to "Download Maps > Search"

First line: Map name
Second line: Size, Map type (always Standart), date.

# UI, [Figma](https://www.figma.com/file/UzancGtMEmAOenmAvhXueQ/Search?node-id=702%3A45119)
<img src="https://user-images.githubusercontent.com/9365308/145577007-7f0d0e21-5c5c-422c-bd38-03034c2eb24f.png"  width="300" height="auto"/>

**Comment by nazar-kutz** [comment]
Fix "Duplicates IndexItems and GpxTracks in search when increase radius": https://github.com/osmandapp/OsmAnd/pull/13641
