### ISSUE TITLE
OsmAnd doesn't display time based fee information

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#7184]
OsmAnd does not display any fee information at all if an interval (e.g., fee=Mo-Fr 08:00-13:00) is used w/ the fee key 
Example: 
http://www.openstreetmap.org/way/38424514 

Description of the fee interval in the OSM Wiki: 
http://wiki.openstreetmap.org/wiki/Key:fee

**Comment by aceman444** [comment]
Yes, adding fee=interval support (at least display the $ icons on such parkings) would be great. This is also mentioned in #4831.

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/111261dcfee60458e297fbdfd3c54b7717325e19
