### ISSUE TITLE
Add setting to increase precision

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#7185]
Add setting to increase precision for altitude, location, azimuth by 1-2 digit

**Comment by sonora** [comment]
Dabatable. What sensors are you using, what's your margin of error?

Last I did a corresponding adjustment to our code we reflected the highest precision sensor physics could deliver to a high end portable device. Scientifically, it of course makes no sense to report or record orders of magnitude more precision than you actually have. It is not only misleading, but also clutters your display or memory (in case of recordings) with useless data.

**Comment by sonora** [comment]
:)

No hard feelings, Victor. I just notice this issue had once been opened by you yourself. I am just keeping a watchful ey on us not introducing pointless complications. :)

**Comment by vshcherb** [comment]
No, I need to reopen it. There is a special request by emergency teams (don't know why) to have 1 extra digit, so we need to double check where, probably it could be part of the format

**Comment by vshcherb** [comment]
Ok, I will attach details once I have them
