### ISSUE TITLE
Wrong routing on the roudabout - into oncoming traffic

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7189]
The route goes on the wrong side of the road, while the directional arrow on the map display the right direction.

Location: Germany, 57234 Wilnsdorf, 
B 54, 
Standort: geo:50.821575,8.10857?z=16 
OsmAnd:
https://osmand.net/go?lat=50.821575&lon=8.10857&z=16
![image](https://user-images.githubusercontent.com/50198677/60815013-66518000-a19f-11e9-9be2-a8f6c434617a.png)

OSM: https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=50.82247%2C8.10714%3B50.82039%2C8.10866#map=19/50.82142/8.10869

**Comment by MAlfare** [comment]
Nobody seems to intereted in this problem.
I reported it on May, 24th already in issue  #6977, where 3 of 5 roundabouts was showed wrong, while the other 2 where O.K.

**Comment by pebogufi** [comment]
Have a look on
https://github.com/osmandapp/Osmand/issues/7135
lools like duplicate ?

**Comment by vshcherb** [comment]
Fixed same as https://github.com/osmandapp/Osmand/issues/7135
