### ISSUE TITLE
Island disappears while zooming out

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7191]
If you look at this island at this zoom level it is rendered wrong.
Nära Sandhamn - Nynäshamn (Nord/sydlinjen) 
Plats: geo:59.130497,18.437084?z=14 
https://osmand.net/go?lat=59.130497&lon=18.437084&z=14

**Comment by vshcherb** [comment]
@katerynakocherhina  Screenshot?

**Comment by katerynakocherhina** [comment]
A small island near Genbötsdjupet, Sweden
![1](https://user-images.githubusercontent.com/50198677/60948102-d0326c80-a2fa-11e9-84df-e5c0650eb121.jpeg)
![2](https://user-images.githubusercontent.com/50198677/60948105-d1639980-a2fa-11e9-9dea-82ec81534995.jpeg)

**Comment by vshcherb** [comment]
This is a minor issue for tiny islands on small zoom
