### ISSUE TITLE
Hiding overground objects breaks map rendering when on close zoom

### ISSUE THREAD

**Issue by agilob** [osmandapp/Osmand#7195]
Below two screenshots of the same location, first with showing overground objects, second with hiding them

![Screenshot_20190708-195346](https://user-images.githubusercontent.com/2544251/60835288-a1ad7800-a1ba-11e9-8836-df661b35270d.png)

![Screenshot_20190708-195356](https://user-images.githubusercontent.com/2544251/60835287-a114e180-a1ba-11e9-87ac-0a8ee2f0e96b.png)

OsmAnd~ 3.4.0 (latest FDroid)
Android 7.1.1

**Comment by xmd5a2** [comment]
"Hide overground objects" option does exactly what its name says. There are no underground objects at this location, so you got an empty screen.

**Comment by agilob** [comment]
Is road considered overground?

**Comment by vshcherb** [comment]
It works like that last 3 years, so it is backward compatible
