### ISSUE TITLE
Widget to display ascent

### ISSUE THREAD

**Issue by quax2712** [osmandapp/OsmAnd#7196]
OSMand offers many values ​​for the distance. Hikes and bike rides would also be very interesting to know, which climb you have to make until the end of the tour and which climb to the next waypoint.

So you do not need to change to the tour details to see the entire ascent.
The value to the next summit of a mountain could only be estimated at this time. Setting a waypoint at the top can solve this problem if there is information such as "Ascent to Next Waypoint".

greetings
Rainer

**Comment by Posteinwurf** [comment]
great idea!
for cycling in hilly aread, the remaing ascent can be as important as the remaining kilometres!

**Comment by vshcherb** [comment]
@angry010101

**Comment by vshcherb** [comment]
We plan to partially implement this feature with Altitude Widget Graph.

**Comment by quax2712** [comment]
I will test if implemented

**Comment by vshcherb** [comment]
Similar widget with graph was implemented in 4.1
