### ISSUE TITLE
New Settings colors are strange

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#7197]
So what's the deal with the new colors? Worse than the old ones ... ;)  It makes many settings screens look like they are completely grayed out. Plus, there is so little contrast now, it is hard to see in sunlight.

See comparison below: OsmAnd as of July 1, vs. OsmAnd new as of July 8, and for comparison the Android 4.4.2 default scheme (which had a well thought-through dark scheme, and which is also power-saving on OLED screens). Judge for yourself:

![1](https://user-images.githubusercontent.com/845735/60864664-88411600-a224-11e9-85f7-8f514f44ad8f.png)  ![2](https://user-images.githubusercontent.com/845735/60864668-8aa37000-a224-11e9-9772-562620e2fdca.png)  ![3](https://user-images.githubusercontent.com/845735/60864672-8c6d3380-a224-11e9-9b42-a2518fd60ccd.png)

**Comment by vshcherb** [comment]
I'm concerned if we can fix it in 3.4 unfortunately it requires lots of changes in settings fragment (it is deprecated what've used) and it is only for old Android versions. So probably it will be patched in 3.4

**Comment by MadWasp79** [comment]
closed with https://github.com/osmandapp/Osmand/commit/a0609c396aa44ebba0716c9ce38460661c5ec399

**Comment by sonora** [comment]
That's cool, thanks! Here's how it looks now on the same device:

![Screenshot_2019-07-10-21-45-00_](https://user-images.githubusercontent.com/845735/60999908-8da17c00-a35c-11e9-9a4d-0ab462cf2948.png)

I'd still prefer black as the background, for more contrast, and to save power and screen life, But the latter really only makes a difference on OLED displays, and then these OsmAnd screens are never displayed for too long anyway. ;)
