### ISSUE TITLE
feature request: making UI simple for new users

### ISSUE THREAD

**Issue by Rik44444** [osmandapp/OsmAnd#7201]
hi all,
i've been using Osmand for a while and i think it is a fantastic app. Amazing what it already can do, and the plans you have for the future (e.g. adding reviews to businesses). 
This is a feature request for the following: to make **starting** to use the app more simple. I know a lot of people who i think would be very enthusiastic about the app, but they never get past the first time use. What happens is this: they open the app for the first time, get asked to download maps, they then think "no i don't want to do that, i just want to have a look at the maps", they skip the download bit, get in the interface and then search for a place, e.g. Amsterdam, and find.... nothing. Because the maps are not downloaded and Osmand is based on offline maps. They then immediately delete the app, bc they think it's useless, since (in their view), it cannot even find Amsterdam. 
So here is my feature request:
1. To make the Osmand UI more like Google maps, in the sense that downloading maps is _optional_ but not a requirement for starting to use Osmand
2. if that is not possible (bc i'm probably not the first person suggesting this), i would recommend the following: that when Osmand installs, it AUTOMATICALLY installs the world map + the map of the country in which the person is based. This will allow people to immediately start using the app, it would make the first use much simpler and more intuitive. 
Perhaps, if this is not an option for the main version, it would be possible to create a fork that does this?

Again, I'm really a big fan of OSMand , this is a suggestion to make it easier for, e.g. my mom and dad to use it. I think it's a great app that deserves mainstream adoption. 
best,
Rik

**Comment by vshcherb** [comment]
Thanks, Yes it makes sense to work a bit on auto-downloading cause it really stops some users to get into it. I think we're going to spend some time on adoption UX soon

**Comment by TheAdventurer64** [comment]
Any progress? This would be great!

**Comment by unforgettableid** [comment]
@vshcherb:

I skipped downloading my local city's maps on purpose, to save space.

I would like for OsmAnd to ship with better default settings. This way, it will automatically show online maps if the offline maps have not been downloaded.

I believe this change might take no more than five or ten minutes for your team to implement. Am I correct?

**Comment by vshcherb** [comment]
I think we have no idea or any progress yet or we have no clear indication when process of simplification will be completed, so the issue will be closed as too broad in description

**Comment by unforgettableid** [comment]
I just filed a new, simpler issue:

#15050:  "If a new user skips downloading maps, OsmAnd fails to display online tiles by default".
