### ISSUE TITLE
Show max speed limit at all roads

### ISSUE THREAD

**Issue by aceman444** [osmandapp/OsmAnd#721]
Currently OsmAnd does not show the speed limit (in the widget on the right) if there is no maxspeed tagged on a road. 

I hope it does use the default maxspeeds from http://wiki.openstreetmap.org/wiki/OSM_tags_for_routing/Maxspeed#Default_speed_limits on untagged roads. However it does not display those limits (to aid the driver to slow down). It could indicate the maxspeed is implied (guessed) in some way (e.g. adding a question mark) to distinguish this case from a road where maxspeed is explicitly tagged.

If OsmAnd can't determine if the road is inside a 'place' (a residential area marked with the proper signs) as it looks complicated (see https://wiki.openstreetmap.org/wiki/Talk:OSM_tags_for_routing/Maxspeed) I propose to at least assume residential/service/living_street is always inside a place. Higher level roads (tertiary up to motorway) probably have their maxspeeds defined explicitly so there is not much of a problem.

**Comment by timokau** [comment]
Why is this not possible? For example a german "Spielstraße" marked as living_street always has the same speed limit (walking speed). The wiki explicitly suggests not setting a maxspeed value. As a result, osmand doesn't show anything.

**Comment by scaidermern** [comment]
> For example a german "Spielstraße" marked as living_street always has the same speed limit (walking speed). The wiki explicitly suggests not setting a maxspeed value. As a result, osmand doesn't show anything.

In this specific case OsmAnd should not display a speed information but a living street icon, in my opinion.

**Comment by timokau** [comment]
Why? Someone not living in Germany wouldn't know what that means.

**Comment by scaidermern** [comment]
Doesn't really matter IMHO. If a driver doesn't know this icon then he won't know the traffic sign either. If you drive in a foreign country you have to know the local signs and traffic laws. Apart from that, other countries have similar signs. So chances are high enough that users are able to recognize it.

**Comment by timokau** [comment]
I disagree. Having the correct speed limit can only help drivers, weather they already know it or not. Even if they already know it, it makes it possible to give an audible reminder if the driver accidentally drives too fast.

**Comment by scaidermern** [comment]
It is not possible to display a correct speed limit because unfortunately the law for "Verkehrsberuhigter Bereich" has only a vague definition "Schrittgeschwindigkeit" aka walking speed. This is actually around 3.6 km/h but could be up to 5 km/h or even 7 km/h according to https://de.wikipedia.org/wiki/Schrittgeschwindigkeit#Definition_im_Stra%C3%9Fenverkehr.

**Comment by timokau** [comment]
Yes but in that case we could still give an estimation and maybe make it configurable. In many other countries its clearer (I really would like to know whoever thought putting "Walking Speed" into law without defining it was a good idea).
