### ISSUE TITLE
[Feature request] kilometer marks visible with a bigger zooming out

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7213]
In nautical view, the kilometer marks can be displayed no further, than with the 100m zoom level. It is inconvenient for moving through rivers, e.g.on the Danube.

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/307e64e9ade8e56a3de3ff22007680612d17391d
