### ISSUE TITLE
[Feature request] Show POI category icons for Add POI quick action

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7224]
When creating or editing POI, it would be convenient for the map contributors to have POI categories suggested.

**Comment by dmpr0** [comment]
The issue is about Quick Action buttons for "Add POO" action, actions don't show POI category icon. Actions for Show/Hide POI show POI category icon.
![photo_2019-10-09 12 14 56](https://user-images.githubusercontent.com/9365308/66468178-6c047d80-ea8e-11e9-8b14-d546fd67c204.jpeg)
