### ISSUE TITLE
[Feature request] add directional arrow in GPX tracks

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd#7229]
In OsmAnd app, it is difficult to see the direction of the recorded GPX track. It would be useful to have a directional arrow through the route in Menu - My Places - Tracks - Analyze on map menu.

**Comment by dmpr0** [comment]
Current nightly builds have a new "Appearance" screen for each track file, where is possible to turn on the "Direction arrows" option and it will remain visible in Analyze screen.
