### ISSUE TITLE
Profile speed definition template revisited

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#7230]
This is not a strong issue, but a comment: I feel our implementation  of letting users define min speed, default speed, and max speed is nonsense. We do not explain anywhere how this is useful, or is used.

Default min speed for car seems 20 km/h, but I am clueless what this means or affects: When I have to stop at a stoplight, pedestrian crosswalk, or in a traffic jam, my ground truth min speed is zero. And when I am on a motorway, a concept of 20 km/h min speed seems absurd.

Similarly for 45 default speed. **Speeds for cars primarily correlate with road type.** A config dialog like we introduced seems awkward (?)

**Comment by scaidermern** [comment]
+1

I already wondered what min and max speed for bicycle and foot is supposed to be. Is it for uphill and downhill or something completely different?

**Comment by pebogufi** [comment]
I made some tests based on 3.4.0#27744 ( 10-Jul-2019 17:04 )
Min speed: don't understand what it is good for.

Default speed: with a version 2 days ago, is thought it was something like finetuning between fastest route and other route. With higher speed in setting faster roads are uses.
But with current version I can't reproduce it.

Max speed: I like it so much. I have a camping car / caravan, I drive slower than with a normal car. So with changing maxspeed the arrival time is much better.

**Comment by sonora** [comment]
Yes, max speed may probably make sense. But again, it could likely be implemented better by simply offering a 'van' profile, where things are reasonably predefined.

Overall, my feeling is we spend too much effort on complicated custom-features, and in the end make things more complex than useful for 95+% of users. "Simple is better": When you read app reviews, people want things to work - period. An overly complex UI is generally mentioned as a significant a minus. Meaning, we should invest effort in automating things and offering speaking profiles with well tested presets, rather than offering every customization possibility there could be.

**Comment by scaidermern** [comment]
A configurable max speed is very useful but three different speed settings are just too much.

**Comment by OpenSourceForEver** [comment]
I agree with everything

**Comment by lbdroid** [comment]
I'll agree with everything here. Those speed settings make no sense at all. In the very least, the controls should be properly described. The only explanation I see on the popup is "Used to calculate the expected arrival time during routing" -- but arrival time should be based on the speed of the roads used in the route. So what is that supposed to mean?

And further to complicate things, if all these settings are for is to calculate the time, then how come when I change some of those settings, is it completely unable to calculate a route?

**Comment by vshcherb** [comment]
The dialog is introduced for all profiles though it doesn't make sense for all, this release we tried not to affect routing settings but we think to change routing as well:
0. Average speed is useful for GPX tracks!
1. Car - none of settings is useful. Maxspeed is useful only for short route cause it overrides default max value of 60 kmh. 
2. Bicycle - min/max value is useful to optimize speed on the bicycle all the timing will be adjusted. Doesn't affect routing ! 
3. Pedestrian, Boat - only average speed is used. 

Of course it is possible to remove some options from some profiles but then it will be be a question why you can't change it. The settings have a generic impact on routing.xml

P.S. please note that yesterday was a major bug fix so some of the commets are not valid any more

**Comment by OpenSourceForEver** [comment]
> Of course it is possible to remove some options from some profiles but then it will be be a question why you can't change it. The settings have a generic impact on routing.xml

Removing some options from some profiles would be very good to simplify the interface. 
https://github.com/osmandapp/Osmand/issues/7328

**Comment by sicherist** [comment]
If I wanted a "just-works" navigation app without complex menus, I would chose something other than Osmand. I like that there are many options in Osmand.

I agree that the standard-speed setting might not be very useful for cars but it is great for bike, boat and walking. Except that it doesn't work yet ;) #7352  For the min and max speed I have no idea what those are supposed to do. Are they used for very steep hills?

**Comment by OpenSourceForEver** [comment]
In my opinion we are no talking about deleting functions. We are talking about some functions are not useful in some profiles

**Comment by vshcherb** [comment]
Options actually should be supported by navigation profile, so I feel explanation how it is going to affect should also come from navigation profile. 

Except we have GPX routing where Default speed is used. So in that sense default speed should be used in all profiles and specified exactly where it is going to be used as speed for routing.

With min/max it is tricky.... I think it requires more data from profile itself like car max is now 130kmh, so user can lower in case his car can't go > 130 kmh.

**Comment by aceman444** [comment]
@vshcherb: max speed for car shouldn't just override the default of 60kph, it should clamp all maxspeeds in the routing.xml file to this value at most. E.g. if user sets 100kph as his max speed, this will be used on motorways, even when routing.xml says 130kph by default (unless there is maxspeed tag), also if there is an explicit maxspeed tag on a way (e.g. maxspeed=200), it will be clamped to the user's 100kph. Of course, if routing.xml or maxspeed on way says e.g. 50kph, that is obeyed as it is lower than user's max speed.

This user's max speed must be honored in all calculations for route determination, not just ETA for driving time (but choosing route using routing.xml speeds). E.g. if user's car can only go 70kph, OsmAnd may determine it makes no sense to go onto a motorway and will take a shorter and faster more direct road through the countryside. Is this the current implementation?
