### ISSUE TITLE
Jenkins down?

### ISSUE THREAD

**Issue by pihug12** [osmandapp/Osmand#7234]
I'm sorry if it's not issues related, but I can't access to your Jenkins anymore to get the commit refs to build OsmAnd v3.4.2.

https://builder.osmand.net:8080/view/OsmAnd%20Builds/job/Osmand-release/

Is it unintentional? Are you working on bring it back?

**Comment by vshcherb** [comment]
Nope 
Couldn't reproduce https://builder.osmand.net:8080/view/OsmAnd%20Builds/job/Osmand-release/706/tagBuild/

**Comment by pihug12** [comment]
Ooops, I'm on vacation and I just find out it is blocked with my 3G/4G network. I can access it with another smartphone on another mobile phone operator. Sorry for the disturbance. :confused:
