### ISSUE TITLE
Support toll:conditional

### ISSUE THREAD

**Issue by TimMagee** [osmandapp/Osmand#7236]
In some places a road is only a toll road some of the time. These roads will have the tag `toll:conditional=yes @[opening hours syntax]`. Currently OsmAnd routes on these roads even when "Avoid Tolls" is checked. For an example, see Interstate 66 outside Washington DC.

https://www.openstreetmap.org/#map=11/38.9410/-77.2964

**Comment by vshcherb** [comment]
Reference issues:
#6271 
#1329

**Comment by vshcherb** [comment]
Fixed along with https://github.com/osmandapp/Osmand/issues/6271. Changes are already in master and will be polished / tested before 3.4

**Comment by TimMagee** [comment]
Thank you! I look forward to version 3.5!
