### ISSUE TITLE
Flooded area in a close zoom

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7238]
Charlottetown, Queens County, Prince Edward Island, Canada

46.2498/-63.1522
Water appears at 10m-50m zoom
![1](https://user-images.githubusercontent.com/50198677/61063125-145f6300-a408-11e9-936c-93dce4fb89f6.jpeg)
![5](https://user-images.githubusercontent.com/50198677/61063130-16292680-a408-11e9-8fd7-714bd1ef333e.jpeg)

OSM does not have this issue
https://www.openstreetmap.org/search?query=Charlottetown%2C%20Prince%20Edward%20Island%2C%20Canada#map=14/46.2498/-63.1522&layers=N

**Comment by vshcherb** [comment]
Not reproducible any more
