### ISSUE TITLE
Osmand 3.4.0 and BRouter (or alternate routing providers)

### ISSUE THREAD

**Issue by jej** [osmandapp/Osmand#7240]
Hi,
Osmand 3.4.0/Android misses the option to choose an alternate routing provider (for example BRouter for bicycle).
Is there a new way to do that on this version?
Thanks for your help.

**Comment by vshcherb** [comment]
Brouter should be available, please try configure it in your profile

**Comment by abrensch** [comment]
In the new version, BRouter can be configured for custome profiles (not for the base profiles)

see here (sorry, german, but look at the screenshots):

https://groups.google.com/forum/m/#!topic/osmand/neTFFbOCO3Y

**Comment by jej** [comment]
Ok I found it. Thanks for the tuto.

**Comment by OpenSourceForEver** [comment]
I can not find it on OsmAnd 3.4.3

**Comment by jlebleu** [comment]
I cannot find also this brouter option

**Comment by abrensch** [comment]
The BRouter option ia only displayed if the BRouter app is installed.
 
Might need to (really!, process-exit) restart OsmAnd after installing BRouter
