### ISSUE TITLE
A question about OSM Map data quantity

### ISSUE THREAD

**Issue by wangzi6578** [osmandapp/Osmand#7241]
Hi，there，
Today,I found a question about OSM map, i get road data from any  one city  in osm map, it about 100M, but i get total country's road data, it only abot 1G,however, it contains hundreds cities,that's incredible，is there any expert could solve my doubt

**Comment by Zahnstocher** [comment]
Which country and city map file you are talking about?
Without this information it is not possible to comment on this.
