### ISSUE TITLE
[Suggestion] Add map selection to profile.

### ISSUE THREAD

**Issue by groschialeux** [osmandapp/Osmand#7243]
Kudos on the new profile creation and management option.  One thing I would like to see added in a future version is the ability to specify which maps to show for each profile.

I use OsmAnd maps for normal navigation in cities and highways but when I go overlanding I disable all those maps and enable my own custom logging roads and hydrography maps along with OsmAnd's contours.

It would be nice to just tell OsmAnd which maps to show for each profile once instead of having to do this enabling/disabling each time.

**Comment by vshcherb** [comment]
Merged into https://github.com/osmandapp/Osmand/issues/7165
