### ISSUE TITLE
Earth icon in coordinates

### ISSUE THREAD

**Issue by oxxm** [osmandapp/Osmand#7250]
![osmand](https://user-images.githubusercontent.com/39620251/61176105-3f3de880-a5bb-11e9-8150-b22fdd28096c.PNG)

The earth icon of N coordinates is only the rotation of E, it should be like in this picture:

https://de.wikipedia.org/wiki/Mercator-Projektion#/media/Datei:Projection_cylindrique.jpg

**Comment by crimean** [comment]
Fixed https://github.com/osmandapp/Osmand/commit/d0098649014542fcdeef593e8fc2c84f3f3043d9
