### ISSUE TITLE
OsmAnd+ 3.4.2 (from F-Droid) crashes on start

### ISSUE THREAD

**Issue by zimbelstern** [osmandapp/Osmand#7254]
Just updated Osmand+ to 3.4.2 (from 3.3.8). The app crashes on start.
Android version: 8.1.0 (AOSP-Extended-v5.4)
Output of `adb logcat | grep osmand`:

> 07-14 17:57:18.821   589  1831 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=net.osmand.plus cmp=net.osmand.plus/.activities.MapActivity} from uid 10184
07-14 17:57:18.907   589  1831 I ActivityManager: Start proc 18333:net.osmand.plus/u0a201 for activity net.osmand.plus/.activities.MapActivity
07-14 17:57:18.990 18333 18333 I XLua.Xposed: Loaded net.osmand.plus:10201
07-14 17:57:19.038 18333 18333 W ContextImpl: Failed to ensure /data/user/0/net.osmand.plus/cache: mkdir failed: ENOENT (No such file or directory)
07-14 17:57:19.038 18333 18333 W ContextImpl: Failed to ensure /data/user_de/0/net.osmand.plus/code_cache: mkdir failed: ENOENT (No such file or directory)
07-14 17:57:19.076 18333 18333 W ContextImpl: Failed to ensure /data/user/0/net.osmand.plus/cache: mkdir failed: ENOENT (No such file or directory)
07-14 17:57:19.085 18333 18333 W ContextImpl: Failed to ensure /data/user/0/net.osmand.plus/files: mkdir failed: ENOENT (No such file or directory)
07-14 17:57:19.116 18333 18333 W ContextImpl: Failed to ensure /data/user/0/net.osmand.plus/shared_prefs: mkdir failed: ENOENT (No such file or directory)
07-14 17:57:19.120 18333 18333 I chatty  : uid=10201(net.osmand.plus) identical 1 line
07-14 17:57:19.129 18333 18333 W ContextImpl: Failed to ensure /data/user/0/net.osmand.plus/shared_prefs: mkdir failed: ENOENT (No such file or directory)
07-14 17:57:19.132 18333 18333 E SharedPreferencesImpl: Couldn't create directory for SharedPreferences file /data/user/0/net.osmand.plus/shared_prefs/activities.MapActivity.xml
07-14 17:57:19.133 18333 18333 I chatty  : uid=10201(net.osmand.plus) identical 3 lines
07-14 17:57:19.134 18333 18333 E SharedPreferencesImpl: Couldn't create directory for SharedPreferences file /data/user/0/net.osmand.plus/shared_prefs/activities.MapActivity.xml
07-14 17:57:19.134 18333 18333 E SharedPreferencesImpl: Couldn't create directory for SharedPreferences file /data/user/0/net.osmand.plus/shared_prefs/net.osmand.settings.xml
07-14 17:57:19.134 18333 18333 E SharedPreferencesImpl: Couldn't create directory for SharedPreferences file /data/user/0/net.osmand.plus/shared_prefs/net.osmand.settings.xml
07-14 17:57:19.135 18333 18333 W ContextImpl: Failed to ensure /data/user/0/net.osmand.plus/shared_prefs: mkdir failed: ENOENT (No such file or directory)
07-14 17:57:19.145 18333 18333 I chatty  : uid=10201(net.osmand.plus) identical 5 lines
07-14 17:57:19.146 18333 18333 W ContextImpl: Failed to ensure /data/user/0/net.osmand.plus/shared_prefs: mkdir failed: ENOENT (No such file or directory)
07-14 17:57:19.179 18333 18333 E SharedPreferencesImpl: Couldn't create directory for SharedPreferences file /data/user/0/net.osmand.plus/shared_prefs/net.osmand.settings.xml
07-14 17:57:19.189 18333 18333 E SharedPreferencesImpl: Couldn't create directory for SharedPreferences file /data/user/0/net.osmand.plus/shared_prefs/net.osmand.settings.xml
07-14 17:57:19.203 18333 18333 W System.err: Startup service net.osmand.plus.inapp.InAppPurchaseHelper took too long 12 ms
07-14 17:57:19.218 18333 18333 W System.err: Startup service net.osmand.plus.routepreparationmenu.RoutingOptionsHelper took too long 12 ms
07-14 17:57:19.237 18333 18333 I net.osmand: ResourceManager Bitmap tiles to load in memory : 144.0
07-14 17:57:19.238 18333 18333 W System.err: Startup service net.osmand.plus.resources.ResourceManager took too long 20 ms
07-14 17:57:19.244 18333 18333 W ContextImpl: Failed to ensure /data/user/0/net.osmand.plus/databases: mkdir failed: ENOENT (No such file or directory)
07-14 17:57:19.245 18333 18333 E SQLiteLog: (14) os_unix.c:35803: (2) open(/data/user/0/net.osmand.plus/databases/analytics) - 
07-14 17:57:19.246 18333 18333 E SQLiteDatabase: Failed to open database '/data/user/0/net.osmand.plus/databases/analytics'.
07-14 17:57:19.246 18333 18333 E SQLiteDatabase: 	at net.osmand.plus.AnalyticsHelper.getCollectedRowsCount(AnalyticsHelper.java:102)
07-14 17:57:19.246 18333 18333 E SQLiteDatabase: 	at net.osmand.plus.AnalyticsHelper.submitCollectedDataAsync(AnalyticsHelper.java:129)
07-14 17:57:19.246 18333 18333 E SQLiteDatabase: 	at net.osmand.plus.AnalyticsHelper.<init>(AnalyticsHelper.java:83)
07-14 17:57:19.246 18333 18333 E SQLiteDatabase: 	at net.osmand.plus.AppInitializer.onCreateApplication(AppInitializer.java:476)
07-14 17:57:19.246 18333 18333 E SQLiteDatabase: 	at net.osmand.plus.OsmandApplication.onCreate(OsmandApplication.java:183)
07-14 17:57:19.257 18333 18333 W ContextImpl: Failed to ensure /data/user/0/net.osmand.plus/databases: mkdir failed: ENOENT (No such file or directory)
07-14 17:57:19.257 18333 18333 E SQLiteLog: (14) os_unix.c:35803: (2) open(/data/user/0/net.osmand.plus/databases/poi_filters) - 
07-14 17:57:19.258 18333 18333 E SQLiteDatabase: Failed to open database '/data/user/0/net.osmand.plus/databases/poi_filters'.
07-14 17:57:19.258 18333 18333 E SQLiteDatabase: 	at net.osmand.plus.api.SQLiteAPIImpl.getOrCreateDatabase(SQLiteAPIImpl.java:27)
07-14 17:57:19.258 18333 18333 E SQLiteDatabase: 	at net.osmand.plus.poi.PoiFiltersHelper$PoiFilterDbHelper.openConnection(PoiFiltersHelper.java:448)
07-14 17:57:19.258 18333 18333 E SQLiteDatabase: 	at net.osmand.plus.poi.PoiFiltersHelper$PoiFilterDbHelper.getWritableDatabase(PoiFiltersHelper.java:433)
07-14 17:57:19.258 18333 18333 E SQLiteDatabase: 	at net.osmand.plus.poi.PoiFiltersHelper$PoiFilterDbHelper.doDeletion(PoiFiltersHelper.java:490)
07-14 17:57:19.258 18333 18333 E SQLiteDatabase: 	at net.osmand.plus.poi.PoiFiltersHelper.<init>(PoiFiltersHelper.java:61)
07-14 17:57:19.258 18333 18333 E SQLiteDatabase: 	at net.osmand.plus.AppInitializer.onCreateApplication(AppInitializer.java:488)
07-14 17:57:19.258 18333 18333 E SQLiteDatabase: 	at net.osmand.plus.OsmandApplication.onCreate(OsmandApplication.java:183)
07-14 17:57:19.258 18333 18333 E net.osmand: SQLiteAPIImpl unknown error (code 14): Could not open database
07-14 17:57:19.258 18333 18333 E net.osmand: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
07-14 17:57:19.258 18333 18333 E net.osmand: 	at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
07-14 17:57:19.258 18333 18333 E net.osmand: 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:210)
07-14 17:57:19.258 18333 18333 E net.osmand: 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:194)
07-14 17:57:19.258 18333 18333 E net.osmand: 	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:493)
07-14 17:57:19.258 18333 18333 E net.osmand: 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:200)
07-14 17:57:19.258 18333 18333 E net.osmand: 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:192)
07-14 17:57:19.258 18333 18333 E net.osmand: 	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:864)
07-14 17:57:19.258 18333 18333 E net.osmand: 	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:849)
07-14 17:57:19.258 18333 18333 E net.osmand: 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:750)
07-14 17:57:19.258 18333 18333 E net.osmand: 	at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:739)
07-14 17:57:19.258 18333 18333 E net.osmand: 	at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:724)
07-14 17:57:19.258 18333 18333 E net.osmand: 	at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:299)
07-14 17:57:19.258 18333 18333 E net.osmand: 	at net.osmand.plus.api.SQLiteAPIImpl.getOrCreateDatabase(SQLiteAPIImpl.java:27)
07-14 17:57:19.258 18333 18333 E net.osmand: 	at net.osmand.plus.poi.PoiFiltersHelper$PoiFilterDbHelper.openConnection(PoiFiltersHelper.java:448)
07-14 17:57:19.258 18333 18333 E net.osmand: 	at net.osmand.plus.poi.PoiFiltersHelper$PoiFilterDbHelper.getWritableDatabase(PoiFiltersHelper.java:433)
07-14 17:57:19.258 18333 18333 E net.osmand: 	at net.osmand.plus.poi.PoiFiltersHelper$PoiFilterDbHelper.doDeletion(PoiFiltersHelper.java:490)
07-14 17:57:19.258 18333 18333 E net.osmand: 	at net.osmand.plus.poi.PoiFiltersHelper.<init>(PoiFiltersHelper.java:61)
07-14 17:57:19.258 18333 18333 E net.osmand: 	at net.osmand.plus.AppInitializer.onCreateApplication(AppInitializer.java:488)
07-14 17:57:19.258 18333 18333 E net.osmand: 	at net.osmand.plus.OsmandApplication.onCreate(OsmandApplication.java:183)
07-14 17:57:19.258 18333 18333 E net.osmand: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
07-14 17:57:19.258 18333 18333 E net.osmand: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5745)
07-14 17:57:19.258 18333 18333 E net.osmand: 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
07-14 17:57:19.258 18333 18333 E net.osmand: 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:361)
07-14 17:57:19.258 18333 18333 E net.osmand: 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
07-14 17:57:19.258 18333 18333 E net.osmand: 	at android.app.ActivityThread.-wrap1(Unknown Source:0)
07-14 17:57:19.258 18333 18333 E net.osmand: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1657)
07-14 17:57:19.258 18333 18333 E net.osmand: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-14 17:57:19.258 18333 18333 E net.osmand: 	at android.os.Looper.loop(Looper.java:164)
07-14 17:57:19.258 18333 18333 E net.osmand: 	at android.app.ActivityThread.main(ActivityThread.java:6499)
07-14 17:57:19.258 18333 18333 E net.osmand: 	at java.lang.reflect.Method.invoke(Native Method)
07-14 17:57:19.258 18333 18333 E net.osmand: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:442)
07-14 17:57:19.258 18333 18333 E net.osmand: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
07-14 17:57:19.258 18333 18333 E net.osmand: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
07-14 17:57:19.260 18333 18333 E AndroidRuntime: Process: net.osmand.plus, PID: 18333
07-14 17:57:19.260 18333 18333 E AndroidRuntime: java.lang.RuntimeException: Unable to create application net.osmand.plus.OsmandApplication: java.lang.NullPointerException: Attempt to invoke interface method 'int net.osmand.plus.api.SQLiteAPI$SQLiteConnection.getVersion()' on a null object reference
07-14 17:57:19.260 18333 18333 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int net.osmand.plus.api.SQLiteAPI$SQLiteConnection.getVersion()' on a null object reference
07-14 17:57:19.260 18333 18333 E AndroidRuntime: 	at net.osmand.plus.poi.PoiFiltersHelper$PoiFilterDbHelper.openConnection(PoiFiltersHelper.java:449)
07-14 17:57:19.260 18333 18333 E AndroidRuntime: 	at net.osmand.plus.poi.PoiFiltersHelper$PoiFilterDbHelper.getWritableDatabase(PoiFiltersHelper.java:433)
07-14 17:57:19.260 18333 18333 E AndroidRuntime: 	at net.osmand.plus.poi.PoiFiltersHelper$PoiFilterDbHelper.doDeletion(PoiFiltersHelper.java:490)
07-14 17:57:19.260 18333 18333 E AndroidRuntime: 	at net.osmand.plus.poi.PoiFiltersHelper.<init>(PoiFiltersHelper.java:61)
07-14 17:57:19.260 18333 18333 E AndroidRuntime: 	at net.osmand.plus.AppInitializer.onCreateApplication(AppInitializer.java:488)
07-14 17:57:19.260 18333 18333 E AndroidRuntime: 	at net.osmand.plus.OsmandApplication.onCreate(OsmandApplication.java:183)
07-14 17:57:19.263   589  2320 W ActivityManager:   Force finishing activity net.osmand.plus/.activities.MapActivity
07-14 17:57:19.273   589  1273 I ActivityManager: Showing crash dialog for package net.osmand.plus u0
07-14 17:57:19.765   589  1272 W ActivityManager: Activity pause timeout for ActivityRecord{982cf49 u0 net.osmand.plus/.activities.MapActivity t8491 f}
07-14 17:57:19.898   589  1305 I WindowManager: Failed to capture screenshot of Token{350b04e ActivityRecord{982cf49 u0 net.osmand.plus/.activities.MapActivity t8491 f}} appWin=Window{116ce80 u0 Splash Screen net.osmand.plus EXITING} drawState=4

**Comment by Zahnstocher** [comment]
> Failed to ensure /data/user/0/net.osmand.plus/shared_prefs: mkdir failed: ENOENT (No such file or directory)

This is really strange.
You may backup your maps and favourites.gpx, then uninstall OsmAnd and reinstall it again.
Or you may wait if OsmAnd devs have an idea how to fix this.

**Comment by zimbelstern** [comment]
Indeed, strange things happen here. Android does not mount my SD card to internal storage anymore, so I guess the missing file error is not OsmAnd's fault.
