### ISSUE TITLE
Searching bug

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/Osmand#7258]
Osmand 3.4.3 ofline maps: comunity of Madrid (Spain) 1 july.

Searching for Calle de las eras (street name) 5, Navacerrada (town). If I write Calle de las eras 5 It appears properly (second option on first image) but if I write Calle de las eras 5, Navacerrada (like it appears on first image) the result is not the expected (second image).
PD. The same if I write town name at the beginning

![Screenshot_2019-07-15-13-14-14-231_net osmand](https://user-images.githubusercontent.com/12786225/61212764-761f1600-a703-11e9-9b38-e289b37f10a5.png)

![Screenshot_2019-07-15-13-16-24-523_net osmand](https://user-images.githubusercontent.com/12786225/61212776-820ad800-a703-11e9-9757-e2e9cb18595f.png)

**Comment by crimean** [comment]
Current search engine is not perfect, however you may use address search (address tab). Choose city first and then enter city name, building.

**Comment by OpenSourceForEver** [comment]
I know adress search, I only want to explain a bug

**Comment by max-klaus** [comment]
Looks like fixed already
