### ISSUE TITLE
speed limit not shown on private roads

### ISSUE THREAD

**Issue by jknockaert** [osmandapp/Osmand#7260]
The speed limit (the value of the maxspeed tag of a road) is not shown when driving on private roads (access=private). I'm not sure if the issue is with the app, or with the maps.

**Comment by lbdroid** [comment]
It probably has to do with your understanding of what it means for a road to be "private".

It comes down to this: if a road is private, then the owners of the land it runs on controls access based on whatever criteria they deem appropriate. If somebody they previously allowed to access the property goes "too fast", then they may be denied access, and subsequent access would be deemed trespassing.

And while police can't sit there with a speed gun to give you a speeding ticket, they can be called to remove and charge a trespasser.

In essence, private roads don't HAVE a speed limit.

**Comment by jknockaert** [comment]
Sorry for being unclear. By private roads I mean roads marked as such in openstreetmap (the value of the access tag is private). I didn't mean to imply any particular understanding of the concept of the private statute of a road. By speed limit I mean the speed limit of a road as registered in openstreetmap (the value of the maxspeed tag of a road). I didn't mean to imply any particular understanding of the concept of a speed limit nor any legal instrument to enforce any specific bylaw.
The issue I wanted to raise is that when the osmand app displays the value of the maxspeed tags (understood to be the speed limit) it fails doing so on roads for which the access tag is set to private. The app doesn't signal in any way the private status of the road, so the understanding of the access status of the road (and what it means) is left to the user anyway.

**Comment by lbdroid** [comment]
It's still a private road and therefore has no speed limit.

**Comment by jknockaert** [comment]
I don't understand your point. In essence no single road does have a speed limit. If you decide to drive faster then you can just do that. A road does not have a fysical ability to limit speed on it. A speed limit is no more than a rule for proper use of the road, and the rule may or may not be enforced. I am not sure how that would be different for private versus public roads. On public roads your driving license may be revoked when speeding, effectively barring further use of the road. That is not very different from a private road where the owner denies further access because of speeding.
But I am not sure why we need to have this discussion. If a road has a value set for maxspeed in openstreetmap, why hide it for subsets of roads in the app? After all, the user can decide to show/hide that value (or ignore it when shown).

**Comment by lbdroid** [comment]
Let me put it another way.

If you drive 300 kph on a public road in a school zone with a speed limit of 30 kph, what happens? You go to jail, because it is against the law.

If you drive 300 kph on a private road, what happens? Nothing, because it is not against the law.

Is it clear to you yet?

**Comment by jknockaert** [comment]
Roads on major industrial sites (such as chemical plants) are private but they typically do have signposted speed limits. For instance as an employee of a subcontractor you get access to the site. But when caught speeding, they may tell you to leave and not come back (and as a result your employer may fire you). That wouldn't have happened if you weren't speeding. That seems to meet the very definition of a speed limit: a rule that may result in a penalty for you when caught breaking the rule. I still don't see how that is different for public roads compared to private roads. You may get a penalty when driving faster than the limit and you will not get the penalty otherwise.

**Comment by lbdroid** [comment]
Putting a sign up on your driveway doesn't make it into law.

**Comment by jknockaert** [comment]
Thank you for your view on the matter. I didn't want to make a claim on the legal status of any speed limit anywhere in the world. The practical use of the concept of speed limit seems to me to be understood as a parameter in a decision rule actual_speed>speed_limit that results in the driver to get a less favourable treatment than he/she would have received otherwise. Such information is available in openstreetmap, and a mechanism is available to show it to the user. I just wanted to report here that this mechanism does not show the information when on a road that is defined as private in openstreetmap.
I am making no claim as to the legal status of any information contained in openstreetmap. More than once in a while it's off and still shown by Osmand. Even the access status (private vs public) may be misdefined in openstreetmap.

**Comment by vshcherb** [comment]
It is not clear why it doesn't, it should. It was probably a glitch though I don't know any limitation for private roads, in essence if "maxspeed" is specified it should be shown as a limit. Please give an example to test if you have

**Comment by jknockaert** [comment]
An example would be the Laboratoriumweg: https://www.openstreetmap.org/search?query=laboratoriumweg%2C%20velsen#map=19/52.47833/4.62440
I set the maxspeed tag in OSM some time in June 2019. Then I updated the NL map in Osmand to the July 2019 version, but I still don't get a maxspeed indication on that road.

**Comment by vshcherb** [comment]
I think it works during navigation (as I checked), probably it doesn't work in profile mode. If you have a setting "Allow private roads" then your problem will be fixed
