### ISSUE TITLE
with version 3.4.4, unable to set navigation settings to straight line anymore

### ISSUE THREAD

**Issue by gignacnic** [osmandapp/Osmand#7271]
Since release version 3.4.4, it is not possible to set navigation settings to straight line anymore.
Before we could choose the service to calculate your navigation route (walk, car). The services offered were:
- OsmAnd (offline)
- Straight line

**Comment by vshcherb** [comment]
It is possible now as well. This is part of OsmAnd Nvigation service and it is listed as a straight line

**Comment by gignacnic** [comment]
Yes, but it is only possible when creating a new profile. For example, when you select the Walking Base Profile it is not possible to change Walking Base Profile and to Set as Navigation Type = Straight line. It was the kind of change planned? In previous version, it was possible to change Navigation Type for Base Profile.

**Comment by vshcherb** [comment]
Yes it is planned to create new profiles

**Comment by Phyks** [comment]
Hi,

I am having a similar issue. I used to use BRouter navigation setting for my bike profile in OSMand, but cannot find how to set it in OSMand 3.4.5.

I cannot change it in the base profile and came across this issue where, if I understood correctly, I should be able to select it if I create a custom profile. I created a new profile based on bicycle base profile but no such options as "Navigation service" is shown in the navigation settings (same for walking or any other profile). No more straight line, BRouter or online routing for cars. Did I miss something?

Thanks! Best,

**Comment by sonora** [comment]
Same issue here, can't find it. Did we drop the option 'Navigation service', or just hide it very well?

Intuitevely, I think we should not force people to open a new profile before facilitating any kind of customization. The other way round makes maybe sense: Facilitate customization, and offer the option to save as a custom profile, if desired.

In addition to the use cases aalready mentioned, the use case I am often approached with is people owning small boats, so they are trying to customize our boat profile from using just the documented waterways (which seems to be the default) to using straight line (between points they manually specify). Somehow I cannot find how to achieve this in 3.4.x any mote?

**Comment by vshcherb** [comment]
It is a Navigation type in profile settings itself. It is not possible to change navigation type in Navigation settings only in navigation profiles. We would like to avoid that standard profiles will be with different Navigation routing for instance.
CC: @dmpr0

**Comment by sonora** [comment]
@vshcherb, @dmpr0 Looks to me like this concept is not easily understood by many users, see e.g also #7419 and #7374.

I suggest the more transparent concept would be we allow all configuration options for all profiles, including for base profiles, and instead clearly indicate which options are the default for each, and/or provide a 'Reset to profile defaults' button?

**Comment by dmpr0** [comment]
Those issues appear because we change the place where it was configurated. We disable navigation type change for default profile to prevent errors.
Now we are working on new UI for Settings, maybe we make some changes for this option.

**Comment by Logicuth** [comment]
Hi, please could somebody give a step by step tutorial, how to get to menu "Navigation Settings" like in version 3.2.7?

With 3.2.7 it was possible to change the navigation settings to use "BRouter" instead of "OsmAnd (offline)".

But now i updatet Osmand to 3.4.6 / 3.4.8 and in both i can not choose "Brouter", because i can not find the Navigation Settings menu.

I have already made a new profile, based on the bike profile. But even with the new profile, i can not switch to "Brouter", because i cant find the navigation settings.

1. How to use Brouter now?

2. Or somebody maybe has a link to f-droid OsmandPlus 3.2.7 ?

**Comment by Phyks** [comment]
Hi,

1. I've recently pushed some updated doc on how to use Brouter with OsmAnd in Brouter repo. You can find a guide in https://github.com/abrensch/brouter/blob/master/misc/readmes/osmand/README.md. Please feel free to create a merge request to add further details if you think these are needed. 

2. You can enable the F-Droid archive repository to downgrade OsmAnd version. But you should not need it to use BRouter. 

Best,
