### ISSUE TITLE
[BUG] Wrong distance text at radius ruler

### ISSUE THREAD

**Issue by Thunichgud** [osmandapp/Osmand#7280]
The distance text on the radius ruler shows wrong values: 100m > 200m > 100m > 200m instead of: 100m > 200m >300m > 400m.

**Comment by vshcherb** [comment]
Couldn't reproduce please attach screenshot

**Comment by Thunichgud** [comment]
I tried multiple times to attach a screenshot as .png, as .jpg and as .zip file but I got only the message: "Something went wrong, and we can't process that file. Try again." It isn't possible to upload a screenshot.

It is rather hard to reproduce this bug, but I found the way: Activate the radius ruler. Zoom the map to zoom factor 15 and switch the compas mode to "No rotation". Now zoom in to factor 16 and than tap one time on the compass icon to "Map rotation as moving direction" (blue compass arrow). Now the distance values are wrong.
