### ISSUE TITLE
brouter: missing turn instructions

### ISSUE THREAD

**Issue by DrVanScott** [osmandapp/Osmand#7286]
Osmand: 3.4.4
Android: 8.0.0
Phone: Huawei Mate 10 Light

If using the brouter engine, osmand sometimes does not generate important turn instructions. Example

(Germany)
From: "Nürnberg Rollnerstraße 72"
To: "Nürnberg Friedenstraße 63"

![o1](https://user-images.githubusercontent.com/1318728/61434552-8c60e800-a936-11e9-90a0-0a13983c620a.jpg)

After changing the "To" a little bit, the missing turn instruction suddenly appears:
To: "Nürnberg, Am Tucherturm 2"

![o2](https://user-images.githubusercontent.com/1318728/61434572-98e54080-a936-11e9-8dac-896b0b8b0619.jpg)

**Comment by abrensch** [comment]
Starting with OsmAnd 3.4.x + BRouter 1.5.x, the BRouter-generated TR's will be used. 

BRouter 1.5.x is not yet on PlayStore, but here: http://brouter.de/brouter/revisions.html

Or are you talking about BRouter 1.5.x, then maybe it's this issue where I got a PR for the BRouter repo: https://github.com/abrensch/brouter/pull/171 ?

**Comment by DrVanScott** [comment]
I am currently using play store version Brouter 1.4.11. I will try 1.5.3 and let you know here about my observations. As #171 is not yet part of 1.5.3, do you have a test case for this issue. That way I would be able to eventually distinguish both cases...

**Comment by DrVanScott** [comment]
The installation of brouter 1.5.3 did not help. The behaviour in above situation is just the same... If you would like I can also test pr 171, but I need you to provide a build...

**Comment by vodie** [comment]
My PR abrensch/brouter#171 fixes this issue and some other turn instruction issues with Osmand.

**Comment by abrensch** [comment]
I uploaded version 1.5.4 which contains https://github.com/abrensch/brouter/pull/171 :

http://brouter.de/brouter/revisions.html

**Comment by DrVanScott** [comment]
I can confirm that this issue is fixed in 1.5.4.  I now found another missing turn instruction using brouter. Should I report it here, in a new issue or in a new issue in the brouter project?

**Comment by abrensch** [comment]
I think the BRouter repo is the better place for that
