### ISSUE TITLE
Support offline search for user defined amenities that aren't buildings

### ISSUE THREAD

**Issue by Gittenburg** [osmandapp/Osmand#7290]
With OpenStreetMaps you can use [any tags you like](https://wiki.openstreetmap.org/wiki/Any_tags_you_like) and there are many interesting non-building [amenity values](https://taginfo.openstreetmap.org/keys/amenity#values) in use, e.g. [auditorium](https://taginfo.openstreetmap.org/tags/amenity=auditorium), [binoculars](https://taginfo.openstreetmap.org/tags/amenity=binoculars) or [piano](https://taginfo.openstreetmap.org/tags/amenity=piano). Instead of attempting to hardcode all of them into the app, generic offline search support for user defined amenities that aren't buildings, would be desirable.

Thanks for this app it's great!

**Comment by vshcherb** [comment]
They are not hardcoded but they need to be processed in the map. In case you specify a category during map creation with custom file (https://github.com/osmandapp/OsmAnd-resources/blob/master/poi/poi_types.xml) everything should be searchable by app.

We monitor and some categories and objects but it is ongoing and never-ending effort
