### ISSUE TITLE
Seasonal speed limits

### ISSUE THREAD

**Issue by ZeiP** [osmandapp/Osmand#7291]
In Finland we have seasonal speed limits similar to the ones mentioned in #1329, but there are no exact days defined for changing those. Instead many of us currently use the key maxspeed:seasonal:winter[1] (and a few also maxspeed:winter or seasonal:maxspeed:winter) to assign the speed limit in winter. There is also a similar notation "maxspeed:conditional=80 @ (winter)", but it is currently less used.

It would be very important to use these speed limits for routing and speed limit display in the winter time. I think the easiest way to do this would be a new setting controlling if normal or winter time maxspeed values are used; this way, the user can easily set which speed limits to use and change the setting when the limits are changed (this is announced in the local news).

1. https://wiki.openstreetmap.org/wiki/Key:maxspeed:seasonal:winter#Finland

**Comment by pebogufi** [comment]
Who should ifentify when is winter ?
The app needs a definition of a date range for such seasonal date based conditional speed limits.

**Comment by ZeiP** [comment]
I propose that the user selects in settings if the winter speed limits are in effect. At least in Finland there's no exact date range for them, so the user knows best.

**Comment by vshcherb** [comment]
I think it is part of #1329 with exception that we need to ask when is winter. Anyway there are similar examples in #1329
