### ISSUE TITLE
[BUG] Could not read GPX data

### ISSUE THREAD

**Issue by zugspitze** [osmandapp/Osmand#7292]
What version of OsmAnd are you using, on what device and Android/iOS version?
=> OsmAnd version 3.4.4, Android version: 9, Device Huawei P20 Lite

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?
=> Offline maps offered withing OsmAnd

I used to upload the GPX files to use it for offline navigation but after recent update in OsmAnd, it shows error: "Could not read GPX data". Can you please have a look. For the same files it worked in the past. I have uploaded such an gpx file [here](https://www.hiking-buddies.com/routes/routes_list/959/download/). Thanks

**Comment by crimean** [comment]
Sorry for the issue. Will be fixed in next release. Currently you may drop **email** tag or whole **author** section from the gpx to make it import successfully.
