### ISSUE TITLE
Detect that I already have a map for an area and stop displaying the download button for it

### ISSUE THREAD

**Issue by naoliv** [osmandapp/OsmAnd#7294]
Everytime I calculate a route OsmAnd displays a button to download the map of the area/region, like this:

![](https://user-images.githubusercontent.com/982338/61559827-041b3980-aa41-11e9-925a-692c09fd6646.png)

The problem is that I already have a map installed for this area.
While my own local map doesn't have the same name, it's coverage is the same:

![](https://user-images.githubusercontent.com/982338/61559831-05e4fd00-aa41-11e9-9fb0-20ceafccd551.png)

Could OsmAnd, somehow, detects that I already have a map installed for that area and stop displaying the download button?

**Comment by IgorEliezer** [comment]
I thought the message/button was due to lack of connection. OsmAnd keeps asking me to download the region when I'm out of Internet. This is also annoying.

**Comment by vshcherb** [comment]
That is not that simple cause OsmAnd can't detect whether it is a full map or overlay. It simply could be a SRTM map or a map with Seamark points or with any other extra information

**Comment by vshcherb** [comment]
Following name convention could really help to solve that issue.

**Comment by vshcherb** [comment]
Should b fixed now
