### ISSUE TITLE
[Improvement] Show hiking route networks when touching on a path 

### ISSUE THREAD

**Issue by Giant3** [osmandapp/OsmAnd#7299]
Often I use GPX tracks to hike, because of the navigation line, the name,number of the hikong route is covered and I dont know on which route I'm. So my suggestion is to show the hiking route information when setting the marker on a way. Sry for the bad English.

**Comment by scaidermern** [comment]
Additionally to showing hiking / cycling routes it would also be really great to use them directly for navigation. That is, route along a hiking / cycling route the same way as routing along a GPX track. This would be really awesome.

**Comment by vshcherb** [comment]
it is definitely a duplicate though I'm lazy to find it, so add it to future milestone for now. 
It is an important feature though we don't even now how to store it in our map files yet

**Comment by scaidermern** [comment]
Aren't you already storing route information in the map files? To display hiking, cycling and similar routes.

**Comment by Giant3** [comment]
#1721 #3969 are the duplicates.

**Comment by vshcherb** [comment]
@scaidermern it is much more complicated cause you can't select in efficient way, it will take quite some time to read whole map to find only 1 route. In case of public transport it is a separate section which we use only to store public transport routes

**Comment by vshcherb** [comment]
One of ideas we have is to "extend" public trasnport routes with hiking / cycling routes though these routes could be much longer :(

**Comment by scaidermern** [comment]
> it is much more complicated cause you can't select in efficient way, it will take quite some time to read whole map to find only 1 route.

I see. Can't you store a reference to the relations each way belongs to? And vice-versa. So that upon selecting a way you will immediately know which relations exist at this position in order to show them.

**Comment by snouup** [comment]
This would be an amazing feature even if not done in an efficient way. As of now, to follow a particular route, I have to search the web for a gpx file, download, import, recenter the map. If, for some reason, the gpx file is broken, or full of unneeded waypoints: rinse and repeat.
This process takes me so long I suspect even searching whole osmand database may be faster.
How about an extension to search screen that shows all nearby routes ordered by distance?

**Comment by pelderson** [comment]
Isn't there a way to convert a route relation (=a chain of ways) to a routing result (=a chain of ways) at the data level? I heard that e.g. brouter results can be transferrred to OsmAnd, so there must be a format for transport.

**Comment by vshcherb** [comment]
On data level OsmAnd doesn't have precise route relation information but it's possible with some tricks to reconstruct these information.

**Comment by pelderson** [comment]
1. What information do these tricks need in the OSM database?
2. What exactly is the result of these tricks? Is it a data construct or
only visible info?
Peter Elderson


Op ma 20 sep. 2021 om 12:07 schreef vshcherb ***@***.***>:

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-tools/pull/449
https://github.com/osmandapp/OsmAnd/pull/13269

**Comment by scaidermern** [comment]
I just tried it with the latest nightly. Looks great!

However, it doesn't work reliably. Sometimes the "Loading..." popup shows but then disappears again without showing anything. Somethings nothing happens at all when tapping on a route.
