### ISSUE TITLE
Feature request: setting for when switch to base map occurs

### ISSUE THREAD

**Issue by matthiasfeist** [osmandapp/Osmand#7301]
I'd like to request a setting for when the app switches from rendering the world base map to the more detailed maps.
Background is that when viewing complex coastlines the very coarse base rendering loses a lot of details.

See example:
Good level of detail:
![Screenshot_20190721-124404_OsmAnd+](https://user-images.githubusercontent.com/1589740/61590202-5da47500-abb5-11e9-9d1e-4c75fdef66d8.jpg)

One zoom level out and the rendering gets too coarse. This I would like to be able to influence even if it means more strain on the cpu
![Screenshot_20190721-124357_OsmAnd+](https://user-images.githubusercontent.com/1589740/61590209-83ca1500-abb5-11e9-96e9-ac800cf86ef5.jpg)

**Comment by sonora** [comment]
Issue is the detailed maps do not have the data included for zoom levels smaller than 10 or 11.

Maybe a workaround works for you: adjust the map zoom, either via menu/ Configure map, or by long-tapping one of the zoom buttons. There you can tweak the screen magnification, while the map rendering is unchanged.

**Comment by matthiasfeist** [comment]
Brilliant. I've just set my zoom level to 25% and that's exactly what I wanted! 
Thanks a lot!
