### ISSUE TITLE
Too much "keep left/right" instructions on straight route

### ISSUE THREAD

**Issue by mutipg** [osmandapp/Osmand#7304]
**OsmAnd Version: OsmAnd+ 3.4.4 (2019-07-15)**
**I'm using offline maps with OsmAnd Live daily updates.**
**Offline Map Poland Pomeranian (2019-07-01) + OsmAnd Live (2019-07-21, 10:26)**
**OsmAnd's in-app offline routing**
**Car fastest profile**
**Problematic route: [https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=54.3039,18.1469;54.2795,18.1001](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=54.3039,18.1469;54.2795,18.1001)**

I was updating in OpenStreetMap speed limits on road no. 228 in Poland so I have to divide this road to smaller parts. After that I have a problem with unnecessary navigation instructions. On the straight junctions there are a lot of keep left/keep right instructions. I don't know what is wrong. I'm sending gpx file with exported route from OsmAnd. 
[route.gpx.txt](https://github.com/osmandapp/Osmand/files/3416045/route.gpx.txt)

I also quote below list of navigation instructions shared from OsmAnd (it is in my native Polish language):
```
Całkowita odległość 3,31 km, czas podróży 0 h 3 min.
1.  Prosto 228 Kaszubska (963 m,  0:56)
2.  Skręć łagodnie w lewo i jedź 228 Kartuska (168 m,  0:10)
3.  Skręć łagodnie w prawo i jedź 228 Kartuska (166 m,  0:10)
4.  Skręć łagodnie w lewo i jedź 228 Kartuska (49 m,  0:03)
5.  Skręć łagodnie w prawo i jedź 228 Kartuska (406 m,  0:18)
6.  Trzymaj się prawej strony 228 Kartuska (489 m,  0:35)
7.  Trzymaj się lewej strony 228 Kartuska (76 m,  0:05)
8.  Trzymaj się lewej strony 228 Kartuska (70 m,  0:04)
9.  Trzymaj się prawej strony 228 Kartuska (199 m,  0:12)
10.  Trzymaj się prawej strony 228 Kartuska (27 m,  0:02)
11.  Trzymaj się prawej strony 228 Kartuska (183 m,  0:09)
12.  Trzymaj się lewej strony 228 Kartuska (505 m,  0:21)
13.   (0 m,  0:00)
```

**Comment by scaidermern** [comment]
There is still a bug in OsmAnd Live. Updated roads sometimes lead to false navigation instructions (keep left, keep right) and the lane widget shows a too large number of lanes (possibly twice the number of available lanes, not sure though).

**Comment by aceman444** [comment]
Yes, this seems to be the same I commented in issue #5003.
