### ISSUE TITLE
Car routing prefers roundabout instead of shortcut

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#7306]
Car routing prefers to route through a roundabout (primary, [way 293577833](https://www.openstreetmap.org/way/293577833)) instead of taking the shortcut (primary_link, [way 255224633](https://www.openstreetmap.org/way/255224633)).

geo:47.981888,11.312563?z=18
https://osmand.net/go?lat=47.981888&lon=11.312563&z=18
https://www.openstreetmap.org/?z=18#map=18/47.98189/11.31256

Left: actual behavior. Right: expected behavior.

![photo_2019-07-22](https://user-images.githubusercontent.com/1040784/61625667-8abb5b00-ac7b-11e9-9d9d-1cc07dc62696.jpg)

Both ways have no maxspeed set, so the default should apply. Is there a penalty for entering a roundabout? Maybe there should be a small penalty since with high traffic you can't enter it directly. Unsure which effect such a penalty has for other situations, though.

**Comment by kylegates** [comment]
If memory serves, there is a penalty when switching to (from?) a _link.
Is there a give_way when entering the roundabout? That would probably add enough penalty to route on the desired way.

**Comment by scaidermern** [comment]
> Is there a give_way when entering the roundabout? That would probably add enough penalty to route on the desired way.

give_way is implicit when entering a roundabout, at least in Germany and many other countries. The traffic inside the roundabout has priority.

**Comment by kylegates** [comment]
I suppose you could make the way entering the roundabout a primary_link as well since that's how it is functioning.

**Comment by vshcherb** [comment]
I think we removed all penalties between primary vs primary_link, so it is a strange case which need to be checked

**Comment by kylegates** [comment]
It looks like the only attribute in routing.xml where they are treated equally is speed. All other areas penalize the primary_link.

		<way attribute="penalty_transition">
			<if param="short_way">
				<select value="10" t="highway" v="primary"/>
				<select value="15" t="highway" v="primary_link"/>
			</if>
			<select value="50" t="highway" v="primary"/>
			<select value="60" t="highway" v="primary_link"/>
		</way>

		<way attribute="speed" type="speed">
			<select value="65" t="highway" v="primary"/>
			<select value="65" t="highway" v="primary_link"/>
		</way>

		<way attribute="priority">
			<select value="1.0" t="highway" v="primary"/>
			<select value="0.95" t="highway" v="primary_link"/>
		</way>

One other item of note:
The roundabout has maxspeed=100

**Comment by scaidermern** [comment]
> One other item of note:
> The roundabout has maxspeed=100

Which is correct but still rather odd... :/

**Comment by thuryn** [comment]
![Screenshot_OsmAnd+_20190726-215003](https://user-images.githubusercontent.com/11028346/61991155-5b766680-b04c-11e9-938a-8034d49ba1b8.png)

I have a simillar issue - tertiary road is prefered over tertiary link.

**Comment by vshcherb** [comment]
@MadWasp79 we should make sure that there is no any extra penalty between "X" and "X_link" road

**Comment by MadWasp79** [comment]
fixed with https://github.com/osmandapp/OsmAnd-resources/pull/588
