### ISSUE TITLE
highway with layer=2 is rendered beneath layer=1

### ISSUE THREAD

**Issue by iriman** [osmandapp/Osmand#7310]
Hi, I'm using OsmAnd~ 3.4.4 fdroid with the Iran offline map July, 1, 2019.

example:
![20190722_195810](https://user-images.githubusercontent.com/8467903/61645103-7c7a3880-ac95-11e9-935b-2cb88e59087a.jpg)

https://www.openstreetmap.org/way/303487110
https://www.openstreetmap.org/way/701190405

**Comment by iriman** [comment]
Screenshot is of Mapnik style, but I also tried other styles and it was the same.

**Comment by OpenSourceForEver** [comment]
I think this is because of type of road (trunk or trunk_link).

**Comment by xmd5a2** [comment]
We don't support multiple positive/negative layers. layer=2,3.. are linked to layer=1 in rendering style. Roads are displayed such way because order of "trunk" is lower than "trunk_link" so "trunk_link" is rendered first.

**Comment by xmd5a2** [comment]
Fixed by commits
https://github.com/osmandapp/OsmAnd-resources/commit/2fe9c04eea8af364d75b983b971b016d830b346c
https://github.com/osmandapp/OsmAnd-resources/commit/d8a166d794dd08c1b47785686293877dc7faf4a8
