### ISSUE TITLE
index not supported

### ISSUE THREAD

**Issue by sazearte** [osmandapp/Osmand#7313]
hello i install last version of osmand (3.4.4) and i download last world_base_map, french and italy map at :
https://download.osmand.net/list.php
i store map in sdcard (i configure osmand for use external storage)

but word_base_map and italy maps not work i have this error :
index not supported (for all italy maps and base world)

**Comment by vshcherb** [comment]
It is not very clear what hapened and it is better to do it via app to avoid some erorrs

**Comment by sazearte** [comment]
i store maps in osmand data folder
when i run osmand i have this error :
map italia toscana have not supported index
base world map have not supported index

i can not use gps in italia because map not loaded
