### ISSUE TITLE
details tab does not show properties / tags

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#7318]
- in details ist nothing but link to osm.
- when editing, main tag (amenity / tourism) in second line is empty, but exists.
Version 3.4.0#27824 (today)
maps France_bourgogne-franche-compte_europe.obf incl. live are both up to date.
![Camping Vert Auxois](https://user-images.githubusercontent.com/18628183/61731109-11a32d00-ad7b-11e9-92c1-2c40789270bf.jpg)

![Camping Vert Auxois01](https://user-images.githubusercontent.com/18628183/61731108-110a9680-ad7b-11e9-9f8a-a083186dda64.jpg)

**Comment by vshcherb** [comment]
I think it is duplicate but it still worth to investigate this, POI wasn't linked to the object displayed on the map, so no details are displayed. Workaround: search this poi or enable layer and open via search or tap on orange circle

**Comment by pebogufi** [comment]
Thanks for the hint with the workaround, and for working on the problem.

**Comment by scaidermern** [comment]
> I think it is duplicate

Yes, see #6497.
