### ISSUE TITLE
[feature request] store downloaded maps on SD Card

### ISSUE THREAD

**Issue by Wilker-a** [osmandapp/Osmand#7319]
hello \^-\^

i just wanted to make a request to make available the download and use of the maps and other data on the SD card, specially when i move the application itself to the SD card

and also move the ones already downloaded.

that's it :3 (thank you for reading and for making this app :3)

**Comment by Discostu36** [comment]
Go to settings --> global settings --> misc --> data folder (or similar, I'm using German version)

**Comment by Wilker-a** [comment]
that is exactly what i wanted, thank you \^-\^
