### ISSUE TITLE
OsmAnd shows "index not supported" error

### ISSUE THREAD

**Issue by sazearte** [osmandapp/Osmand#7320]
Reporting for OsmAnd 3.4.4

I am using Xiaomi Mi MIx 2 (Lineageos 16)

I have side-loaded the obf files (world overview, Italia) in the map folder.

Yet the maps do not get displayed on screen.
After a couple of seconds, the screenshows a list of errors in the following format:

The version of 'italia_toscana.obf' is not supported.
(This is followed by similar lines, each mentioning a different map fie name.)

I have same problem that this :
https://github.com/osmandapp/Osmand/issues/2783

but i not use live uptade, i only download map from Osmand Local Indexes List
https://download.osmand.net/list.php

**Comment by pietervdvn** [comment]
The .obf file is probably corrupted. Retry downloading and sideloading it.

**Comment by naoliv** [comment]
Today I did download an updated map for my area and, while decompressing it using the file manager, it created a folder inside osmand with the same name as the map (ie, instead directly decompressing it to `mymap.obf`, it created `mymap.obf/mymap.obf` inside the osmand directory)

With such wrong directory (named exactly like the map), osmand also gave me an index not supported error.

Maybe this could also be your case?

**Comment by sazearte** [comment]
i try to downloading and it's work, sorry for this post
