### ISSUE TITLE
Doubts and possible improvements for navigation settings with BRouter

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#7330]
When using BRouter, do `Offline calculation of OsmAnd route segment` and `Fastest route` apply only when we follow a GPX route?

![](https://user-images.githubusercontent.com/982338/61888981-023af580-aedb-11e9-9859-bd32784e128b.png)

If yes then, probably, both should be hidden and only enabled if we select a GPX to follow, right?
Otherwise it's confusing to have 4 combinations of Fuel-efficient + Fastest route, for example:

1. ❌ Fuel-efficient + ❌ Fastest route
1. ✔️ Fuel-efficient + ❌ Fastest route
1. ❌ Fuel-efficient + ✔️ Fastest route
1. ✔️ Fuel-efficient + ✔️ Fastest route

**Comment by Chumva** [comment]
`Offline calculation of OsmAnd route segment` and `Fastest route`  for BRouter works without selected GPX file.
