### ISSUE TITLE
Search for "internet access" categories broken

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#7331]
Searching for Internet access categories is broken. Searching for "Internet access: yes", "Internet access: wlan" etc. yields only very few results. Most POIs offering Internet access via wifi etc. aren't getting listed, such as [this one](https://www.openstreetmap.org/node/2078129368).

**Comment by scaidermern** [comment]
Can somebody reproduce this problem? This is an important POI for me.

Looks like this doesn' work correctly for POIs which have a main category (such as [shop=bakery](https://www.openstreetmap.org/node/2078129368)) but works for objects which don't have a main category (such as this [fitness center during construction phase](https://www.openstreetmap.org/node/1255905166)).

**Comment by vshcherb** [comment]
Fixed, though new maps will be needed cause all POI types are combined into one 1 internet access, so the interent_access is missing in data.

Though we also added beta-search for additional categories and now you could find more results via internet access type: *

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/commit/b540b5b2e75a833c214cb5c697cf5e52c6c2014f

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-resources/commit/5c297ee6770fc9b2d45a34e6ceb59863d44ac929
