### ISSUE TITLE
[Feature request] add option to select Wiki pages in several languages

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7333]
Many users are bilingual, therefore it may be useful to have a choice between Wikipedia articles in several languages apart from only display language or all of them.

**Comment by letypequividelespoubelles** [comment]
I think the best would be to ask which languages you want to DL Wikipedia, less data to DL.
Also, maybe many users don't know that there is Wikipedia inside OsmAnd. So when a map is proposed to he DL, it would be nice to show the different possible maps to DL : normal, Wikipedia, contour lines, hillshade. For the moment it just proposes to DL the normal map.

**Comment by vshcherb** [comment]
Implemented already in nightlies
