### ISSUE TITLE
Zoom going mad

### ISSUE THREAD

**Issue by Flexmaen** [osmandapp/OsmAnd#7334]
The zoom is going mad sometimes when zooming out.
This happens regularly (on an Android 8.1 in this case, but I already had this before and with older versions). OSMAnd version is 3.4.4.

What happens is, that OSMAnd zooms out as far as possible. You'll have to close the app and restart it again. I did not figure out why this happens but in the video it seems that I touched some sliding element on the side before. However this does not happen always when you touch other elements, so it happens regularly for me but I could not 100% reproduce why this happens.

Video:
[osmand_issue_video.zip](https://github.com/osmandapp/Osmand/files/3436209/osmand_issue_video.zip)

**Comment by vshcherb** [comment]
Wow it looks scary. I will forward it and keep an eye on our test devices

**Comment by Flexmaen** [comment]
Still using the same phone, but I didn't have this issue for a while now with the later versions of OSMAnd, while it appeared regularly when I opened the bug.

So maybe some code change fixed this issue?
In this case I guess we can close this bug.

**Comment by vshcherb** [comment]
I guess so
