### ISSUE TITLE
App Profile label texts hard to read

### ISSUE THREAD

**Issue by IgorEliezer** [osmandapp/Osmand#7341]
Setting > App profiles > Select a profile.

The label texts, e.g. "Profile name" and "Navigation type", are hard to read.

![image](https://user-images.githubusercontent.com/4673289/62013734-2c0b4b00-b16d-11e9-8417-907f1ea7270f.png)

**Comment by sonora** [comment]
Similar to #5113 and some other ossues.

Overall I have to say ee are an outdoor app and should opt for the maximum contrast possible to facilitaye reading things in e.g. bright sunshine or under vibration condotions. Also, black background gor menues in dark theme seems prudent, especially for AMOLED displays.
