### ISSUE TITLE
Shoreline still not conforming in Florida keys after update

### ISSUE THREAD

**Issue by Seaviator** [osmandapp/Osmand#7343]
The latest update fixed some problems but also introduced some new ones. On key West itself the same problem persists, that being the land disappearing underneath the buildings. But I have encountered a new problem. The land seems to extend past the shoreline, into the water at some points.  

Here is a link to some images that might help explain:

https://imgur.com/a/GFxfvwE

**Comment by xmd5a2** [comment]
Duplicate of https://github.com/osmandapp/Osmand/issues/6565
