### ISSUE TITLE
Can't set intermediate destination

### ISSUE THREAD

**Issue by gh88** [osmandapp/Osmand#7344]
Using latest OsmAnd (3.4.4, released 2019-07-15), I can't set any new intermediate destinations. When I try to add first or last intermediate destination (I use "My Places" to put it on the map), it always replaces my actual destination with that intermediate destination. In other words, I can't add any new intermediate destination without replacing my real destination.
It means, I can't create any more or less complex route with intermediate destinations in the middle of the rout. I have always create only one way trip... While it's possible, it's complete unacceptable. I have to create one way trip to my next intermediate destination. The after arriving to my first intermediate destination and sitting in my car, I have to create a new route to my next intermediate destination...
Please fix it ASAP!

**Comment by vshcherb** [comment]
I can't reproduce it .... It doesn't work only for My Places or other options like Select on The map.
