### ISSUE TITLE
With latest OsmAnd I can't hear any prompts at all

### ISSUE THREAD

**Issue by gh88** [osmandapp/Osmand#7345]
Using latest OsmAnd (3.4.4, released 2019-07-15), I suddenly can't hear any prompts anymore :(
I double checked all my current settings and everything is looking good to me. But while I had to drive with left hand keeping on the wheel, while keeping smart phone in the right to turn it on, off, on, off just to see my next direction. I certainly can't do it while riding my bike :(
Why is that???
Please fix it ASAP! Or I can't use OsmAnd as my navigation tool anymore :(

**Comment by vshcherb** [comment]
What language do you use? Do you think it is related to any specific situation or it doesn't work from start. Please try to use another TTS-engine or another language to test

**Comment by gh88** [comment]
It's English.
I don't think it's related to a specific situation.
What's wrong with this TTS-engine? It's "Google Text-to-speech Engine" (v3.18.14.261387622) and it's working very well with other apps (Google Translate, Google My Tracks, etc).

**Comment by vshcherb** [comment]
Sorry, We can't reproduce it: You can try to update Google TTS and reinstall OsmAnd.

**Comment by littlehelper** [comment]
Hi, I had the same issue some nightlies before. At my device the voice guidance output was changed somehow to Media audio which I have muted on my device. Switching manually back to Notification audio fixed it for me.
