### ISSUE TITLE
Standard speed is not taken into account for calculating arrival time

### ISSUE THREAD

**Issue by sicherist** [osmandapp/Osmand#7352]
In OsmAnd 3.4.4 there is a new setting for the standard speed (thanks a lot for implementing it by the way!). For example 10 km/h for bicycle routing. But when calculating a route the standard speed doesn't seem to be taken into account. For example today I calculated a route of 9,42 kilometers (slightly more uphill than downhill) but the estimated time displayed for the route is 26 minutes. I double checked in the options that the standard speed is set to the defaults of 3 / 10 / 33 km/h. With the standard speed of 10 km/h the estimated time should be closer to an hour for the 9,42 km route.

**Comment by sonora** [comment]
The implementation of min/max/standard speed is both unclear and mostly faulty, see #7230.
