### ISSUE TITLE
OsmAnd Live Subscription map updates

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7356]
The setting to update the map only on Wi-Fi does not affect the hourly map updates.

**Comment by scaidermern** [comment]
Probably the same cause as #7364.

**Comment by max-klaus** [comment]
Fixed by https://github.com/osmandapp/Osmand/commit/8f1e864bf3ffdb6c66a1631389aa7ceb52c2a6b0
