### ISSUE TITLE
Most of settings of OsmAnd Live cannot be changed

### ISSUE THREAD

**Issue by Rpnpif** [osmandapp/Osmand#7364]
To reproduce on OsmAnd 3.4.5.
For a map (as France Pays de la Loire)
Live update was set on.
Only download on Wi-Fi was checked.
Update Hourly changed to Daily.
Ok.
Restart OsmAnd.
Now update is on Hourly. It should be on Daily.

I note also that the notification of the indexing of the World_base map takes a long time.

**Comment by scaidermern** [comment]
This bug is even larger.

OsmAnd live is enabled for various maps on my device. If I disable them and restart OsmAnd they are enabled again. This setting is completely lost between app restarts.

OsmAnd 3.4.6.

**Comment by scaidermern** [comment]
Why has this been moved to a later milestone? It can't be so hard to fix this, can it? This is really annoying. The only feature requiring additional payment and it is broken for months now.

**Comment by vshcherb** [comment]
Confirmed settings are not saved between restarts!

**Comment by Rpnpif** [comment]
I noted that if I erase all the file and I reinstall OsmAnd fix this issue.
Parameter file may be perhaps corrupted by a early release ? Ind.cache or other ? It is only an idea to resolve this issue.
