### ISSUE TITLE
Problems with multi-region Public Transport

### ISSUE THREAD

**Issue by Famlam** [osmandapp/Osmand#7365]
OsmAnd 3.4.5 on LG, Android 8.1
Offline maps of Gelderland, Noord-Brabant and Limburg (all in the Netherlands, updated July 1)

Using (offline, build-in) public transport routing:
1. try to navigate from [this bus stop (Sint Canisiussingel, Nijmegen)](https://www.openstreetmap.org/node/1728910575) to [this bus stop (Sittarderweg / Kerk, Heerlen)](https://www.openstreetmap.org/node/4557635694). (Or nodes nearby)
2. notice that no route is generated: `"Unfortunately, OsmAnd could not find a route suitable for your settings. Try changing the settings"` (note: `number of changes` is set to `3`. Unfortunately I cannot try higher values as that setting isn't possible)

Expected routing, examples (as it depends on the time of the day, of course, which is possible/fastest)
1. [take bus 331 in direction Weezenhof to Nijmegen central station](https://www.openstreetmap.org/relation/3181607)
(alternative, walk to nearby bus stop Hunnerpark and take one of the many buses to Nijmegen station there)
2. take a train from Nijmegen central station to station 's Hertogenbosch (can be [this](https://www.openstreetmap.org/relation/4864) or [the other train line](https://www.openstreetmap.org/relation/5261971))
3. take [this](https://www.openstreetmap.org/relation/7835609) train from 's Hertogenbosch to station Heerlen
4. arrive at the destination by using [this](https://www.openstreetmap.org/relation/8129011) or [this](https://www.openstreetmap.org/relation/2680312) bus line

(i.e. 3 changes, so it should be possible...)

**Comment by vshcherb** [comment]
I think the issue is between different provinces i.e. different maps and that's what's not working yet

**Comment by vshcherb** [comment]
Bug with fix https://www.openstreetmap.org/relation/10329863#map=13/50.5027/30.8062
https://github.com/osmandapp/OsmAnd-tools/commit/151b9366a5288da838ebae6670dec0e64069c955

**Comment by vshcherb** [comment]
With May map and latest version you will be able to create a route of maximum 3 hours and you will get 1 alternative though not the route you mentionned. 
So I've created another spinoff to work on other issues https://github.com/osmandapp/Osmand/issues/8986.

Now multi-region transport routing is possible

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-tools/pull/353

**Comment by vshcherb** [comment]
I've tested now with temporarily fix of 8986 (could be done in routing.xml on the device) and it lists all alternatives 
from Point A to Den Bosch central station and from Den Bosch to Point B.  All the buses and trains you've mentionned.

Though it doens't list all alternatives from Point A to Point B, investigating it.
