### ISSUE TITLE
Nearby public transport stop information displayed instead

### ISSUE THREAD

**Issue by Famlam** [osmandapp/Osmand#7367]
OsmAnd 3.4.5 on LG, Android 8.1
Offline maps of Gelderland (the Netherlands, updated July 1)

1. Tap on the icon corresponding to https://www.openstreetmap.org/node/5156070902 to display the information of that railway yard.
2. Notice that it displays the information for the transport stop nearby (Hoogkamp/Tormentilstraat) instead
![Screenshot_2019-08-02-23-56-36](https://user-images.githubusercontent.com/1315520/62415904-c9fd8a80-b631-11e9-89a8-107194023547.png)

**Comment by vshcherb** [comment]
This is correct behavior as I don't see any routes using that node

**Comment by Famlam** [comment]
@vshcherb, correct about no routes using that node, but are you sure it's the expected behavior that the information displayed corresponds fully to another node? Wouldn't it be more logical to display "Arnhem Berg Opstelterrein" + "Nearby transport: Hoogkamp/...", as I explicitly selected "Arnhem Berg Opstelterrein"? (It's not like a platform of the other, it has completely different names). It looks quite odd for me to select A and get only information of B.
(On a side node: are train yards public transport stops at all?)

**Comment by vshcherb** [comment]
Yes it is correct cause it is very handy to see transport from other nodes in certain radius in case you want to make a transfer. Obviously these stops could be completely unrelated and have different names but it is more important to give user access to all public transport in certain radius
