### ISSUE TITLE
sidewalk transition penalty too strict for partially mapped sidewalks

### ISSUE THREAD

**Issue by Famlam** [osmandapp/Osmand#7369]
OsmAnd 3.4.5 on LG, Android 8.1
Offline maps of Gelderland (the Netherlands, updated July 1)

1. Use offline foot navigation (min-speed: 3, default: 5, max 6km/h) from [van Lyndenstraat 35](https://www.openstreetmap.org/node/2829342457) to [Prins Bernhardstraat 19](https://www.openstreetmap.org/node/2829341179) in Nijmegen (just an example)
2. Notice that OsmAnd will take a huge detour 

The cause is fairly simple. A [very small part](https://www.openstreetmap.org/way/346473012) of the "fast" route has a sidewalk=both tag, the remaining part of the route is not tagged for sidewalks. However, due to the sidewalk=both, there's a [150 seconds penalty](https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml#L1689) on the fast route, causing OSM to prefer to avoid the sidewalk altogether.

Obviously this is just an example. It would become much more horrible for a road which is only intermittently tagged with sidewalks. Consider for example going from [the cycleway next to this house](https://www.openstreetmap.org/node/6124742445) to [this house](https://www.openstreetmap.org/node/3008713482). Here the tertiary way (which has no sidewalk) is incorrectly preferred over the (safe, sidewalk tagged) direct way, only because OSMAnd tries to prevent the penalty. 

Perhaps it would be good to:
- lower the priority of sidewalk="no" a bit more (as there's explicitly stated there's no sidewalk)
- give sidewalk="no" a large transition_penalty (for example the current 2.5 minutes, I assume this wasn't arbitrarily)
- give sidewalk undefined (i.e. via the default, currently set to 150) only a moderate transition_penalty (for example the time needed to cross a road to a parallel cycleway, if present, where walking is often safer; let's say 30 seconds?)

p.s.: unrelated side note, currently, if a way is tagged as `foot=use_sidepath` + `sidewalk=no`, it'll get a priority of 0.9. I'd think that use_sidepath (which yields a way priority of 0.1) should be more important - it mainly states you shouldn't walk there - and thus be above the sidewalk priorities - which only state there's no separate sidewalk, not that you cannot walk there.

Edit: screenshots added
![1](https://user-images.githubusercontent.com/1315520/62425185-8dd13500-b6d8-11e9-99bf-01b9f210b265.png)
![2](https://user-images.githubusercontent.com/1315520/62425206-d38dfd80-b6d8-11e9-93bb-b40f5e6868e0.png)

**Comment by vshcherb** [comment]
Let's give a try with 90 seconds and added sideway=both.

**Comment by Famlam** [comment]
Thanks! I'll certainly improve many cases, as long as the fragmentation (sidewalk mapped-or-not) is not too big! Probably the `sidewalk=both` line won't have any effect though, as `sidewalk=both`'s are converted to `yes` @ https://github.com/osmandapp/OsmAnd-resources/blob/master/obf_creation/rendering_types.xml#L2094 , if I'm correct?
