### ISSUE TITLE
Routecalculation of a gpx-route ignores choosen routing profile

### ISSUE THREAD

**Issue by cannothing** [osmandapp/Osmand#7370]
Yesterday I tried to use a gpx-route for navigation. I was a little puzzeled that the result lead me to a street, which was forbidden for bicycles.

So I did some testing, I choosed the points from my gpx-route as destinantion and via points on the map. The result of the route calculation was very different compared to the route calculation based on the gpx-route. Although I used the same routing profiles.

Further investigation gave the result, that this problem exists since version 3.2.7

**Comment by scaidermern** [comment]
Is this about routing along an existing GPX track? If so, the current route "calculation" doesn't really take existing roads into account. It blindly follows the GPX track without looking at access or turn restrictions.

**Comment by cannothing** [comment]
I have used the word gpx-route not track. Der Unterschied ist dir bekannt?

 

Von: Alexander Heinlein <notifications@github.com> 
Gesendet: Montag, 5. August 2019 09:14
An: osmandapp/Osmand <Osmand@noreply.github.com>
Cc: cannothing <ich@stephan-zitzmann.de>; Author <author@noreply.github.com>
Betreff: Re: [osmandapp/Osmand] Routecalculation of a gpx-route ignores choosen routing profile (#7370)

 

Is this about routing along an existing GPX track? If so, the current route "calculation" doesn't really take existing roads into account. It blindly follows the GPX track without looking at access or turn restrictions.

**Comment by vshcherb** [comment]
GPX navigation doesn't take into account allowed / forbidden routes
