### ISSUE TITLE
Possible routing error: Preference of highway=footway over highway=residential

### ISSUE THREAD

**Issue by ltog** [osmandapp/Osmand#7372]
**Important note: https://www.openstreetmap.org/changeset/73198089 changed the situation described in this issue by adding stairs on the footway.**

OsmAnd~ 3.4.4 from F-Droid on Fairphone 2 running Android 7.1.2 using offline maps and in-app offline routing (cycling profile with all driving styles)

From: 8FVC7HG8+7H
To: 8FVC7HG9+95

Routing looks like this:

https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=47.27557%2C8.56648%3B47.27566%2C8.56822#map=19/47.27580/8.56732
(going over Holzgasse, a `highway=footway`)

![bad](https://user-images.githubusercontent.com/4726277/62486036-7ec4b280-b7be-11e9-942d-b54f2b9e9830.png)

but IMHO should look like this:

https://www.openstreetmap.org/directions?engine=fossgis_osrm_bike&route=47.27557%2C8.56648%3B47.27566%2C8.56822#map=18/47.27618/8.56703
(going the longer way over Hintere Bergstrasse, a `highway=residential`)

![good](https://user-images.githubusercontent.com/4726277/62486048-85532a00-b7be-11e9-84e2-dab5bd68fbae.png)

My understanding of ~~https://wiki.openstreetmap.org/wiki/Tag:highway%3Dresidential~~ https://wiki.openstreetmap.org/wiki/Tag:highway%3Dfootway is that bicycles should not be routed there unless there is also a `bicycle=yes` (which is not the case in this example).

**Comment by ltog** [comment]
I reported the seemingly incorrect behaviour on the OSM website at https://github.com/graphhopper/graphhopper/issues/1681 .

**Comment by scaidermern** [comment]
> My understanding of https://wiki.openstreetmap.org/wiki/Tag:highway%3Dresidential is that bicycles should not be routed there unless there is also a bicycle=yes (which is not the case in this example).

Where did you get that impression? As the wiki states, highway=residential implies bicycle=yes. Typical residential roads are perfect for bicycles.

**Comment by ltog** [comment]
@scaidermern : Sorry, I pasted the wrong link, I meant to say:

My understanding of https://wiki.openstreetmap.org/wiki/Tag:highway%3Dfootway is that bicycles should not be routed there unless there is also a bicycle=yes (which is not the case in this example).

**Comment by scaidermern** [comment]
> @scaidermern : Sorry, I pasted the wrong link, I meant to say:
> 
> My understanding of https://wiki.openstreetmap.org/wiki/Tag:highway%3Dfootway is that bicycles should not be routed there unless there is also a bicycle=yes (which is not the case in this example).

Oh. Yes, that's true. There are some countries where bicycle access on footways defaults to true but the default is to forbid bicycle access (see [access restrictions](https://wiki.openstreetmap.org/wiki/OSM_tags_for_routing/Access-Restrictions) for default and country-specific values).

**Comment by Posteinwurf** [comment]
if a footway is much shorter than the alternative, it makes sense, because you can always push the bike.

**Comment by Famlam** [comment]
Maybe, especially due to the regional differences, it might make sense here to have another setting in the 'avoid' menu, "avoid footways", here? If checked, a footway would get a priority of 0.1 (or so). (Fully excluding isn't a good idea I think as not all destinations can be reached without footways, but setting the priority so low would avoid them unless there really is no other option)

**Comment by ltog** [comment]
> if a footway is much shorter than the alternative, it makes sense, because you can always push the bike. so by totally excluding footways, some really great shortcuts would be missing.

If OsmAnd routes me over footways where we must assume there is no allowance for bicycles, I'd like to receive a corresponding announcement.

Note: The described situation was changed after I opened this issue by https://www.openstreetmap.org/changeset/73198089 .

**Comment by vshcherb** [comment]
I think it is better to indicate bicycle=yes cause it is globally preferrable
