### ISSUE TITLE
Railway not visible in all map styles

### ISSUE THREAD

**Issue by Heiner-Sch** [osmandapp/Osmand#7373]
What version of OsmAnd are you using, on what device and Android/iOS version?
OsmAnd~ 3.4.5
Android 8.1.0 last securityupdate 01. June 2019

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?
Offlinemaps
- Germany North Rhine-Westphalia 1 July 2019
- Germany Rhineland-Palatinate 1 July 2019

The railway is visible correct in the mapstyle Topo or Offroad.
Mapstyle OsmAnd has the error.

Here you see the part of the map I'm talking about:
https://www.openstreetmap.org/#map=15/50.5952/7.2756
The Kasbachbahn goes from the river Rhine to the north into the forest.
In mapstyle OsmAnd the hole railway is not visible.

Here the mapstyle OsmAnd:
![Screenshot_20190806-193704](https://user-images.githubusercontent.com/38109491/62563823-1809cc80-b884-11e9-85cb-0c00e0e67466.png)

And here the mapstyle Topo:
![Screenshot_20190806-193742](https://user-images.githubusercontent.com/38109491/62563951-44254d80-b884-11e9-8cef-37d7924e65f0.png)

And here the same place in the online map:
https://www.openstreetmap.org/#map=18/50.58081/7.26185

**Comment by xmd5a2** [comment]
Someone added railway:preserved=yes to these railways. Osmand treats them as railway=preserved https://wiki.openstreetmap.org/wiki/Tag:railway%3Dpreserved and renders only at high zooms because they are not commonly used.
