### ISSUE TITLE
routing.xml not recognized

### ISSUE THREAD

**Issue by Posteinwurf** [osmandapp/Osmand#7374]
the latest version of osmand does not seem to to reognize the routing.xml

I have put it in net.osmand.plus and alternatively in the routing subfolder. neither worked. have tried all sorts of variations (move routing subfolder up etc)

I have also reinstalled Osmand. Did not help either.

any ideas?

ps I need it because I want to continue working on the elevation values for bicycle mode (they still contain some errors)

**Comment by vshcherb** [comment]
Now you can create a profile and put it in a specified folder (change it in profile settings to apply for a specific profile).

**Comment by 7tonin** [comment]
I also had a personalised routing.xml file, but it not working anymore.

This is what I can read in OsmAnd+3.4.6 > Application profiles > Walking (like in any other else)
"You can add your own modified version of the file routing.xml in ..osmand/routing"

I don't understand what I should guess to make it work again.
I used to have a switch to allow/disallow private highway access (like in car default profile).

**Comment by Zahnstocher** [comment]
@7tonin 
Copy your *.routing.xml into the ..osmand/routing/ folder.

Then follow these screenshots, instead of "BRouter (offline)" select your routing.xml from the list:
https://groups.google.com/d/msg/osmand/neTFFbOCO3Y/Bg6FkO09DwAJ

**Comment by 7tonin** [comment]
Thank you very much @Zahnstocher :
1. once routing.xml copied in osmand/routing folder,
2. go to menu "Parameter" > "Application profiles" > choose one of your crafted profile > "Navigation type" and finally
3. choose one of the navigation type set in your routing.xml (hidden at the bottom of the list)

NB : it is not possible to change "Navigation type" of built in profiles .
