### ISSUE TITLE
Restaurant POI completely covered by misaligned parking symbol at higher zoom level

### ISSUE THREAD

**Issue by Aiurek** [osmandapp/Osmand#7382]
Lenovo Moto G4 plus, Android 7.0
OsmAnd+ 3.4.xx, before the play store release 2019-08-03
May style: OsmAnd
Map: Provemce-Alpes-Côte d'Azur (June 1, 2019) 

Due to the misalignment of the parking symbol (related to #5440, but a very special case), the POI of the fast food restaurant get's completely covered by the parking symbol at higher zoom levels, which makes the restaurant not properly clickable anymore. Would it make sense for e.g. restaurant POIs to draw over parking POis?

https://www.openstreetmap.org/#map=19/43.31712/6.63123

![Bild1](https://user-images.githubusercontent.com/27865200/62703449-9469f000-b9e9-11e9-964b-ed85557b2624.jpg)

**Comment by vshcherb** [comment]
Not really I think, so it is a duplicate #5440 which need to be fixed.
Workaround: POI Layer
