### ISSUE TITLE
Flooded area Côte d'Azur (France)

### ISSUE THREAD

**Issue by Aiurek** [osmandapp/Osmand#7384]
Lenovo Moto G4 plus, Android 7.0
OsmAnd+ 3.4.xx, before the play store release 2019-08-03
May style: OsmAnd
Map: Provemce-Alpes-Côte d'Azur (June 1, 2019)

https://www.openstreetmap.org/#map=17/43.27328/6.57663

![Bild5](https://user-images.githubusercontent.com/27865200/62704772-6df98400-b9ec-11e9-936e-3a9e187c4b79.jpg)

**Comment by vshcherb** [comment]
Not reproducible any more
