### ISSUE TITLE
Wrong turn while navigating

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7385]
OsmAnd suggests the wrong turn while navigating from
-27.4551200, 153.0358740
to
-27.4711250, 153.0079210
The only way to change the route is to use the Avoid road option.
![image](https://user-images.githubusercontent.com/50198677/62705239-ac477100-b9f5-11e9-912c-98122240badb.png)

**Comment by scaidermern** [comment]
This would be the correct route: https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=-27.45169%2C153.03103%3B-27.45174%2C153.02613#map=18/-27.45284/153.02858

There might be a missing u-turn restriction in OSM. Nevertheless OsmAnd should not suggest such u-turns if other possibilities exist.

**Comment by vshcherb** [comment]
https://www.openstreetmap.org/relation/58224
