### ISSUE TITLE
ATM search shows nuclear explosion sites

### ISSUE THREAD

**Issue by Aiurek** [osmandapp/Osmand#7387]
Lenovo Moto G4 plus, Android 7.0
OsmAnd+ 3.4.6, released 2019-08-03

A little weird that the search result for atms, shows you the atm POI followed only by different types of nuclear explosion sites (airdrop, balloon, rocket,...)^^

![Bild10](https://user-images.githubusercontent.com/27865200/62706663-4b696a00-b9f0-11e9-999e-e59e4c444c8c.jpg)

**Comment by nhfo** [comment]
@Aiurek I think it's because of substring matches. What happenes when you tap first one?

**Comment by scaidermern** [comment]
You have to hit the search button or write a space at the end of your search string. Otherwise OsmAnd performs partial matches. "atmospheric" starts with "atm".

**Comment by vshcherb** [comment]
It is partial matches not complete, click button search
