### ISSUE TITLE
Small suggestion for the start screen

### ISSUE THREAD

**Issue by Aiurek** [osmandapp/Osmand#7389]
Feel like it'd be better to replace the capital P with a small p and remove the dot at the end

![Bild13](https://user-images.githubusercontent.com/27865200/62708520-e0219700-b9f3-11e9-88e6-7914f4c84cde.jpg)

**Comment by OpenSourceForEver** [comment]
Perhaps more contrast could be added to make the words look better

**Comment by dmpr0** [comment]
Done https://github.com/osmandapp/Osmand/commit/86077b2d657d033b0d1ff8d67ff4a840f3aaf65d
