### ISSUE TITLE
Visibility of yellow colored lines in night mode navigation

### ISSUE THREAD

**Issue by Aiurek** [osmandapp/OsmAnd#7393]
Lenovo Moto G4 plus, Android 7.0
OsmAnd+ 3.4.xx, before the play store release 2019-08-03
May style: OsmAnd
Navigation service: OsmAnd (offline)

With night mode switched on I feel like it's pretty hard to distinguish between yellow streets and yellow guidance line, especially when you're driving in a city. It takes me always a little longer to spot the route due to lack of contrast, compared to day mode. Same applies to the arrows at the top, showing you the next action and lane guidance.
I really feel like it's a necessity to change the colors here in order to be able to differentiate all the lines more easily.

![Bild18](https://user-images.githubusercontent.com/27865200/62714488-fe40c480-b9fe-11e9-94df-c2d8df8563b9.jpg)

**Comment by sonora** [comment]
Yes, I never liked that. But it is overall not easy to find an generally good color set, may want to check out what we have been using in OsmAnd's Touring view Map style, for many years stable now.

**Comment by vshcherb** [comment]
Solution to strip down all road colors to  only 2 colors and make other features selected by user. So I think in future default (street) rendering style will be like that

**Comment by sonora** [comment]
PS: It looks like you are using Map style 'OsmAnd' and the there available Road style 'German road atlas'.

@vshcherb A typical example of complication by over-engineering: Users cannot only select 'Map styles', which are overall engineered packages providing optimized contrast for the entire feature set including routes and tracks. Users can also separately adjust 'Road styles', which leads to not optimized combinations, and subsequently support cases. May be a target point for us when simplifying the UX.

**Comment by vshcherb** [comment]
Too many dimensions, simplification will lead to cut features out, so we just need clear separation "Advanced" or "Simple" use. For "Advanced" we need even more features to be possible to adjust (may be specific road color even from UI) and for Simple we will need to test it thoroughly.

**Comment by scaidermern** [comment]
Maybe the above example can be fixed by adding/changing the casing of the drawn route to improve contrast.

**Comment by sonora** [comment]
I would think we can kill the dimension road style in favor of map style, without much loss of functionality.

**Comment by bunk3m** [comment]
Hello. 
Has anyone done anything about this?  I've been trying for some time to get a view at night where I can actually see the route.  This yellow route on a yellow street is very bad for someone like myself with older eyes.   I can't see the arrows so the directions are useless.
How can I set the road to white or grey and the route to blue?

**Comment by sonora** [comment]
Have you tried this:

Go to Menu / Configure map: There either select Map style =Default, but then make sure that option Road style is also set to Default. This makes all roads ar night gray, the route remains yellow.

Alternatively , if you need to have the colored roads, simply try Map style = Touring view, and this uses a blue line for the route not overlapping so much with the road colors.

**Comment by bunk3m** [comment]
Thank you @sonora . I presume by "Map style=Default" you mean Map style = Osmand?  That one is better.  I'll try that for a bit.  I think I've tried each but they have many different varients so after a while I got lost.

The Touring style is better in general in my view but the major highways are so strong (yellow & red) that it becomes difficult to see the yellow route when driving along or across the highway.  The touring view has a lot of detail that I find is a distracting.

It would be really nice if we could just have grey for all roads.  I've used Google Maps for some time before Osmand+ and it does have a very clean navigation view.  It doesn't have much in terms of distractions and shows detail only on the route.  It would be really cool if we could get a theme to look similar to Google Map navigation.  

Anyway, thanks so far.  I'll try the default style and road for a bit and see how that works for me during evening drives.

**Comment by sonora** [comment]
Ok, thanks for the feedback!

Yes, I meant OsmAnd style when referring to Default,  we show that as its display name.

And yes, it is intentional for Touring view to be rather rich in showing detail (to facilitate discovering things), and to show major highways rather strong, to facilitate moving in unfamiliar terrain, also with bigger rigs like RVs or trucks.

The navigation line, however, should show in dark blue (day) or neon blue (night) in Touring view. If that's not the case for you please let me know.

**Comment by dmpr0** [comment]
In the current nightly builds, we implemented the option to change the appearance of the route line: color separately for day and night map modes (will be added in few days), ability to change line width.
The option can be found in "Settings – Profile – Profile appearance – Customize route line".
