### ISSUE TITLE
more settings in the navigation

### ISSUE THREAD

**Issue by martin-scholtes** [osmandapp/Osmand#7395]
Hello everybody,

I have already used the search and unfortunately found no suitable issue that fits my topic.

Having created in the last or penultimate version the possibility of specifying own navigation profiles and in particular the setting of minimum, maximum and average speed; Would I like to set the following parameters individually:
Length, width, height, weight, axle load
This would make it easier for professional drivers to navigate. But also for me private, it is quite pleasant.
The previous settings options with default values does not always meet my expectations.

It is only a wish.

**Comment by vshcherb** [comment]
It is coming in next few weeks in nightly build, please give it a try cause it sounds as already implemented.
