### ISSUE TITLE
Alerts are displayed after passed by

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7403]
The alerts are still displayed even after passed by for several kilometers.
Example 
From http://osmand.net/go.html?lat=48.69256&lon=3.18031 
To http://osmand.net/go.html?lat=48.69852&lon=3.27277
The speedcam is displayed after it is passed: http://osmand.net/go.html?lat=48.69253&lon=3.18728&z=17

**Comment by IgorEliezer** [comment]
Related? https://github.com/osmandapp/Osmand/issues/6790#issuecomment-481959145

**Comment by dremelts** [comment]
I have also observed this behavior while following a route.  It will warn of a railroad crossing or pedestrian crossing and then the symbol will stay on the screen and the voice guidance will keep giving audible alerts for many miles.  I have disabled all traffic alerts for this reason.

**Comment by max-klaus** [comment]
Looks like fixed already
