### ISSUE TITLE
Nautical map view: link map and navigation settings with profile

### ISSUE THREAD

**Issue by Sim0nb** [osmandapp/Osmand#7405]
Nautical navigation usually requires different settings than road maps for distance and speed (knots and nautical miles instead of kph/mph and km/mi); unless mistaken, those two settings are general and apply to all profiles instead of profile per profile (using boat profile).
Is there a possibility to change that?

Before entering an issue, please read the information below.

```GitHub is a main development tool for developers. There are hundreds requests a month and there are only few developers. So by opening an issue, please know that your issue will be sent out to all developers and acknowledge that it could be closed without explanation or with a brief message. Comments on the closed issues are also sent to all developers, so you will definitely will be heard. However, there is no guarantee that a developer will pick up the issue to work on it.```

In case you are not sure to open issue or not, please send your request to support support@osmand.net. For **general questions** about OsmAnd, please use the [Google group](https://groups.google.com/forum/#!forum/osmand).

Please be sure to have read our [FAQ](http://osmand.net/help-online) before creating an issue here. (Also, tell us in Google Groups when the FAQ is wrong or outdated.)

The best way to get help about an OsmAnd issue is to create a valid and detailed issue content.
Please give us the following information so that we can try to **reproduce** your issue:

What version of OsmAnd are you using, on what device and Android/iOS version?

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.

__*In case of wrong routing:*__

Tell us whether you have used OsmAnd's in-app offline routing, or any online routing provider like YOURS, OpenRouteService or OSRM.

What routing profile is chosen in OsmAnd app? (car, bike, pedestrian, fastest or shortest)

Please specify as exactly as possible the start and end point of your route by telling us city name and street name so that we can find it via in-app address search easily. Also, a permalink from openstreetmap.org can be helpful.

Tell us your expected routing, and how OsmAnd routes, or add screenshots here.

**Comment by sonora** [comment]
Settings under 'Navigation settings' are usually profile specific, so speed should work. I guess 'Unit of distance' may not work, as it is under 'General settings'. Coukd be changed, but would likely create confusion with many non-boating users, because mostly the unit of distance would be considered general for most other profiles.

**Comment by Sim0nb** [comment]
Hi Sonora, thanks for the update.
Indeed, speed in navigation settings has to be assigned to a specific profile; two issues though:
1. it is not possible to select the general profile (world icon)
2. switching between profiles does not or erratically update(s) the speed format (cache related?).
As for the general setting about distance, perhaps a work-around would be to add a quick action option enabling to change those formats?

**Comment by vshcherb** [comment]
We are planning to make measurement units profile specific with clear default option, so it will be possible to override it just for 1 profile

**Comment by Sim0nb** [comment]
Sounds great!
Thanks for the move.
