### ISSUE TITLE
Opens at is not handled correctly

### ISSUE THREAD

**Issue by Lukas458** [osmandapp/Osmand#7406]
Hi,
please have a look at https://www.openstreetmap.org/node/480375354

the opening_hours are: Mo-Fr 08:00-12:00, Mo,Tu,Th 15:00-17:00; PH off

where the very first comma (=additive comma) should be placed  correctly as I see it, also https://openingh.openstreetmap.de/evaluation_tool/ says that.

But OsmAnd version 3.3.5 says: "Opens at Monday at 3:00 PM (=15:00)

**Comment by vshcherb** [comment]
It is a problem of only nearest time, parser handles situation correctly

**Comment by Lukas458** [comment]
okay, I see.
