### ISSUE TITLE
Brouter no more supported in version 3.4.6 ?

### ISSUE THREAD

**Issue by tomdereub** [osmandapp/Osmand#7419]
Hi,
I just udpated to 3.4.6, and I don't find any more how to choose the routing service. I'm used to Brouter, wich I find superior on bicycle routing calculation and faster than osmand's in-app routing service (I'm speaking about offline routing only).

Is it a strategy choice or an issue ? I didn't find discussions about it in the issues.

Thanks for the work !

Osmand 3.4.6 on LineageOS 14.1 (Android 7.1.2)

**Comment by naoliv** [comment]
It seems that now you have to go to `Settings` → `Application profiles` → `Add`, select the profile type and at the `Navigation type` choose BRouter.

At least this is what I had to do to select BRouter for driving (and I didn't find an easier way for this).

**Comment by dmpr0** [comment]
Hello! Yes, in the current version, we disable the ability to change navigation type in the default profiles, you need to create custom to use external services and customized routing.xml.

**Comment by tomdereub** [comment]
Ok thanks, that's working well !

**Comment by rgbimport** [comment]
The problem still exist in version 3.5. It is not possible to select other routing mechanism.
Is this a problem or just a design decision?

**Comment by dmpr0** [comment]
@rgbimport Hello! In 3.5.5 you need to create custom profile and that select Brouter as navigation type. In current nightly builds, you can set navigation type in any profile.

**Comment by rgbimport** [comment]
I see it. Thanks
