### ISSUE TITLE
OsmAndMapCreator doesn't contain OsmAndMapCreator.jar

### ISSUE THREAD

**Issue by FoliniC** [osmandapp/Osmand#7420]
On latest nightly relase of OsmAndMapCreator-main.zip there's no OsmAndMapCreator.jar file.
I also tried opening archive with 7zip.

**Comment by vshcherb** [comment]
It is regulary tested and I think it is there, it is in the root folder I think

**Comment by FoliniC** [comment]
On 7-zip the file isn't shown, unzipping on a directory revealed the file! The "problem" is that this file has a path prefix of ".\", whether the others (say "OsmAndMapCreator.Bat") has blank

**Comment by vshcherb** [comment]
hm... need to be checked on our side
