### ISSUE TITLE
Wrong route in the bicycle profile

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7421]
OsmAnd suggests crossing the river in the cycling profile despite there are no bridges. The issue does not occur in the OSM
Start: 
49.74896° N, 11.04340° E
Stop: 
49.76975° N, 11.03506° E
![image](https://user-images.githubusercontent.com/50198677/63011473-172ef700-be91-11e9-9720-3539c55e723a.png)

**Comment by vshcherb** [comment]
There is no route close to location so it found the location across the river which is obviously wrong.
