### ISSUE TITLE
Bug report: Dasboard

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7425]
In OsmAnd menu - Dashboard - Current route section after taping on the Info button, it opens in the background and duplicates itself after multiple tapping. 
![1](https://user-images.githubusercontent.com/50198677/63081106-74877e80-bf4b-11e9-8ed4-8b29826040b9.jpeg)

**Comment by dmpr0** [comment]
Fixed in the new version.
