### ISSUE TITLE
Number of lines does not match the OSM data

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7426]
At this point: 44.995934,20.207544 OsmAnd displays 6 lines, while there are no more than only 3 of them.

**Comment by vshcherb** [comment]
Is OsmAnd live enabled?

**Comment by BrackoNe** [comment]
Yes of course!

**Comment by scaidermern** [comment]
Duplicate of #7304 and #5003.

**Comment by xmd5a2** [comment]
Duplicate of https://github.com/osmandapp/Osmand/issues/7518
