### ISSUE TITLE
Make application profiles user sortable in navigating/routing screen

### ISSUE THREAD

**Issue by hvdwolf** [osmandapp/OsmAnd#7429]
The new possibility to make your own application profiles in 3.3.x and up is really excellent. 

One "nice to have" is the option to change the display order of those profiles in the routing/navigation screen. (Sorting in the "Application profiles" maintenance screen would also be nice, but is a much lower priority "nice to have").

I created a caravan profile and an extra car profile. Now they are added at the end and on one of my smaller phone screens they "drop off" the screen.
Please make it possible for the user to change the position (going from left to right)

**Comment by dmpr0** [comment]
Implemented.
