### ISSUE TITLE
Slow route calculation

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7432]
Route for 175 km was calculated more than in 3 minutes. Placing intermediate waypoints and changing the navigation settings did not affect the calculation time. 
From: 45.47681 N, 7.94720 E
To: 44.41093 N, 8.91350E

**Comment by jej** [comment]
Did you try BRouter engine?

http://brouter.de/brouter/

**Comment by kuba-orlik** [comment]
I'm also experiencing very slow route calculation in recent versions, even for short distances (3km takes around a minute)

**Comment by vshcherb** [comment]
To notice, we've introduced new metric which is stable across multiple measurements - roads per second.

How many roads will be processed depends on the route itself:
1) map data
2) routing configuration

We consider 3 type of devices:
1. Top devices > 15K roads per second
2. Medium devices 10-15K roads per second
3. Budget / slow < 10K roads per second

Sometimes reinstall could help to optimize Android App. If you notice that a small route requires too many roads to be observed than it is *Map issue* or *Configuration issue*

**Comment by kuba-orlik** [comment]
How can I measure the roads-per-second score?

**Comment by vshcherb** [comment]
@MadWasp79 probably could comment.
With latest version and development plugin, once calculation is finished it prints information how many roads visited, how much did it take time and etc.

We are actively working to make it faster each individual method

**Comment by dbojan** [comment]
I am getting slow route calculation on android device with snapdragon 665 cpu.

Banja Luka, Bosnia, to Trebinje, Bosnia, distance 327km
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=44.77198%2C17.18989%3B42.71734%2C18.33941#map=8/43.753/17.736

Dismissed osmand calculation after 3 minutes.
--
Banja Luka, Bosnia, to Foca, Bosnia, distance 274km
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=44.772%2C17.190%3B43.515%2C18.784#map=9/44.1484/17.9971

Dismissed osmand calculation after 2 minutes.

When trying other programs like Maps.me (uses OSM, open source), or Magic Earth (uses OSM, closed source), both other programs were able to calculate the route under 10 seconds.

Perhaps check how other program are doing it?
--
Banja Luka, Bosnia, to Doboj, Bosnia, distance 106km
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=44.7720%2C17.1899%3B44.7314%2C18.0847#map=10/44.8255/17.6404

Route calculated after ~15 seconds.

Thanks.
