### ISSUE TITLE
POI Details missing, perhaps due to complex opening_hours

### ISSUE THREAD

**Issue by carstenhag** [osmandapp/Osmand#7435]
POI Details like opening hours, cuisine details etc are missing sadly. See the image below. 

https://www.openstreetmap.org/node/3168902404

https://www.openstreetmap.org/way/21846437 is shown as osm URL, but it's wrong for some reason. Note: I'm currently in Spain and selected the POI on the map. 

![Screenshot_20190817-205246](https://user-images.githubusercontent.com/3776997/63216128-2338e400-c131-11e9-919a-8db9b1944ca9.jpg)

What version of OsmAnd are you using, on what device and Android/iOS version?
OsmAnd 3.4.6, One Plus 5, Android 9. 

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

Osmand live, offline tiles.

https://www.openstreetmap.org/node/3168902404

**Comment by carstenhag** [comment]
Possibly a duplicate of https://github.com/osmandapp/Osmand/issues/6497, but it may be something else. No clue.

**Comment by scaidermern** [comment]
Yes, looks like the same issue

**Comment by vshcherb** [comment]
Nope, the issue is different, the other one is only related to polygon objects and this is one a point object.

**Comment by stalker314314** [comment]
I just tried this out (F-Droid, 3.4.8, xiaomi, android 9) and it works (cannot repro). Drop down menu is bigger than this, but screenshoting it in same position as Carsten, so it can show difference:

![pic](https://user-images.githubusercontent.com/188751/65378016-5aeffa00-dca2-11e9-9362-e3f265167e44.png)

**Comment by carstenhag** [comment]
Hmm, some days ago I removed the live updates for Baden-Württemberg (where Otantik is inside).

So currently it's using the map state from 01.08.19 for me, and it seems to work just like you posted @stalker314314.

Possinly osmand live related?
