### ISSUE TITLE
Move screenshots and metadata for app stores upstream

### ISSUE THREAD

**Issue by PanderMusubi** [osmandapp/Osmand#7437]
For automated adding of screenshots and metadata to app stores, several mechanisms exist such as metadata and fastlane. This saves the maintainer a lot of manual work uploading screenshots to app stores when new screenshots are available. This is a widely used mechanism helping releasing new versions of apps.

For the F-Droid app store, screenshots and metadata have been created to facilitate this. These can be found at https://gitlab.com/fdroid/fdroiddata/tree/master/metadata/net.osmand.plus/en-US

The request is to move this data upstream from the F-Droid repo to this repo. If it is desired, I can make a pull request for this. Let me know if this is welcomed. This will move screenshots to a more generic location allowing maintenance in one place for the benefit of all app stores.

**Comment by PanderMusubi** [comment]
This issue is part of an effort to remove custom screenshots from the F-Droid data repo, see also https://gitlab.com/fdroid/fdroiddata/issues/1413#note_193403754

**Comment by IzzySoft** [comment]
For details, please also see: https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#in-the-apps-source-repository

Note that this gives you a bunch of advantages as a welcome side effect:

* you can easily update/replace screenshots without the need of opening MRs at fdroiddata
* you can easily maintain app descriptions (including multi-locale) directly in your app's repo
* you can use the same for F-Droid and Google Play (so no redundant double-work)
* you can also include per-release changelogs (`changelogs/<versionCode>.txt`) which are displayed inline with the app description on both, F-Droid and Google Play – which in the F-Droid client make your app appear on the featured tab (still called "new") if you have screenshots along those changelogs

Thus resulting in a clear win-win-win (less work for you, less work for us, better information for the user). So this move is strongly encouraged :wink:

**Comment by vshcherb** [comment]
Yes it sounds good, though we use 2 different repos for images and for text / translations. Though for sure it would be good to be maintained by us

**Comment by PanderMusubi** [comment]
Super. Let us know when you have support for this, so that metadata can get removed from the F-Droid repo.

**Comment by vshcherb** [comment]
@PanderMusubi please create pull-request to this repo (https://github.com/osmandapp/Osmand-misc) to one of the subfolder

Concern: if you have automation and audience that can translate the app name / descriptions that probably will lack temporarily.

Once you create pull-request we will know that you are ready to support that location and we will take over.

**Comment by PanderMusubi** [comment]
Please see https://github.com/osmandapp/Osmand/pull/8047

**Comment by PanderMusubi** [comment]
Ah, also see screenshots in https://play.google.com/store/apps/details?id=net.osmand but could not find those in any of the repos mentioned here.

**Comment by dmpr0** [comment]
I added images and changelog for current version https://github.com/osmandapp/OsmAnd-misc/tree/master/fastlane

**Comment by IzzySoft** [comment]
Thanks @dmpr0 – but as they are in a separate repo, they won't show up e.g. at F-Droid, which would look for Fastlane data in the source repo (which would be here). Currently, we have [the entire tree in the F-Droid metadata repo](https://gitlab.com/fdroid/fdroiddata/tree/master/metadata/net.osmand.plus), where it was last updated in 2018. You might wish to grab it from there, push it in here, and update it. When done and covered by a tag, we should remove them at F-Droid so they are taken from here.

@PanderMusubi this is also the reason why you didn't find them here :wink:

**Comment by vshcherb** [comment]
Done https://github.com/osmandapp/OsmAnd-misc/tree/master/fastlane/metadata/android/en-US

**Comment by IzzySoft** [comment]
@vshcherb ahem… thanks, but: first, it's still in a separate repo (so F-Droid won't pick it up; not sure if it is possible to include that as git submodule here) – and second, I spotted at least 2 file names not matching [Fastlane file structure](https://gitlab.com/snippets/1895688): `summary.txt` should be `short_description.txt`, and `description.txt` should be `full_description.txt`. Further, there's a redundant `phoneScreenshots` directory (this belongs inside `images/`, the other one is wrong).

**Comment by Korb** [comment]
Still no screenshots in F-Droid:

![Screenshot_2023_0826_065352_org fdroid fdroid](https://github.com/osmandapp/OsmAnd/assets/3509797/3c72ac62-0ee4-4e23-9dbc-0a7779970cee)

**Comment by DmitryAlexei** [comment]
@Korb this question is better address to the F-droid team

**Comment by PanderMusubi** [comment]
@IzzySoft

**Comment by IzzySoft** [comment]
I'm not "the F-Droid team", but yes, a member of it. I still don't see where the screenshots should come from. Was Fastlane set up? I cannot see it. Or was Triple-T? Cannot find that either. So where should they magically appear from? And what do you expect the F-Droid team to do about it? We can only include what is provided,

**Comment by vshcherb** [comment]
Not sure what it means fastlane setup. We've put the documentation was referenced in fastlane folder https://github.com/osmandapp/OsmAnd-misc/tree/master/fastlane and that's it.

**Comment by IzzySoft** [comment]
And was that added to the repo where F-Droid builds the app from – e.g. as git submodule? Otherwise it cannot be found. F-Droid does not support custom Fastlane locations (other than my repo, where those are possible). It requires that the Fastlane structures are found in one of the defined locations **inside the source repo.** That can be achieved as a git submodule, or by establishing the structures directly.

**Comment by yurtpage** [comment]
Please move the fastlane into the main repo. You may ignore translations of changelogs to minimize amount of files. I guess new releases have nothing really important in the changelogs except of "bug fix".

Then you'll need to add the Fastlane metadata into the Weblate so that it can be easily translated. This is especially for F-Droid because it doesn't offer an auto-translation.

So please go to the https://hosted.weblate.org/projects/osmand/
On left click on plus "Add new translation" component.

- Name: metadata
- Version control system: "GitHub with Pull Request"
- Source code repository: use `weblate://osmand/main`
- **Optional** Key filter: `^(?!changelogs/.*$).+$` to exclude changelog from translation
- Press Continue and select the metadata folder.
