### ISSUE TITLE
[Feature Request] Possibility to have both local and our language name

### ISSUE THREAD

**Issue by letypequividelespoubelles** [osmandapp/Osmand#7439]
I think it would be so nice to have all the names in both local and our language. Particularly useful while in country with different alphabet. 
I think the best would be to have local names, and just after in parentheses the traduction in our language, when available. 
More,  we could have a preferable system for the traduction. Let say my mother tongue is rare, so not so many traduction, but I can speak english too.
If English and my language available, we should see local name (rare language name)
If only English is available : local name (English name)
If no traduction available, we should just see the local name.

**Comment by letypequividelespoubelles** [comment]
Similar of #7399 with just something more

**Comment by carstenhag** [comment]
Hey, could you please delete the standard text of your issues?

**Comment by vshcherb** [comment]
Merged #7399
