### ISSUE TITLE
Osmand doesn't show amenity=drinking_water as POIs sufficiently

### ISSUE THREAD

**Issue by volter** [osmandapp/Osmand#7440]
I'm using Osmand~ 3.4.6 from fdroid on Android. I'm trying to find amenity=drinking_water POIs (https://wiki.openstreetmap.org/wiki/Tag:amenity%3Ddrinking_water). Entering "trinkw" into my German-localized osmand search yields "Trinkwasser -- von Menschenhand". I guess this translates to something man_made, probably https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dwater_tap. Unfortunately only a subset of the POIs I expect to find shows up. For instance, https://www.openstreetmap.org/node/2440029242 is missing from it.

I expected to find all occurrences of amenity=drinking_water like this.

Remotely related to issue #5828

**Comment by Discostu36** [comment]
When I search for "Trinkwasser - von Menschenhand" I also get amenity=drinking water without sub-tags. I can also find your example. Interestingly, it is not listed in the search results. It is only shown when I click on "Trinkwasser auf der Karte anzeigen". But the other POI on the same parking lot is shown in the list. I guess that search results are filtered somehow to avoid listing multiple results that are very close to each other.
