### ISSUE TITLE
Underlays without polygons

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd#7443]
Underlay map layer with "Show polygons - Off" is displayed some artifacts. Only during the navigation.
The issue occurs in the latest nightly build.
https://www.openstreetmap.org/search?query=51.6046%2033.4041#map=12/51.5914/33.4482
![image](https://user-images.githubusercontent.com/50198677/63250561-9c8d1f80-c274-11e9-9879-5a1a19c9ef88.png)

**Comment by vshcherb** [comment]
Probably fixed in 4.3
