### ISSUE TITLE
PT Navigation

### ISSUE THREAD

**Issue by Fish31** [osmandapp/Osmand#7445]
To improve Public Transport navigation:

1. Osmand should take into account the frequency of passage of public transport routes (interval=*) for a better indication of the time needed to reach the destination.

2. Osmand should take into account opening_hours, especially thinking about night routes, so that Osmand does not offer them during the day in public transport navigation.

**Comment by vshcherb** [comment]
It is a bug duplication but it is exactly 2 issues we have in our priority list for PT

**Comment by vshcherb** [comment]
Merged with #6700

**Comment by sonora** [comment]
Regarding opening_hours: It may be better to somehow just display these for participating routes but not use them as a filter, because PT routing is often used to generally check out PT transportation options in advance, meaning it is not necessarily used at the time you want to travel.
