### ISSUE TITLE
Magnetic direction error

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7453]
The magnetic direction displayed indicating the magnetic direction towards a waypoint is incorrect in California, USA. A sign error in the algorithm appears to be present in applying the magnetic variation, as the error is equivalent to twice the magnitude of magnetic variation. 
For instance, in areas where 12 degrees of variation should be applied, M = T - 12. In the app, it is utilized the following way: M = T + 12.

**Comment by EugeneZmeuk** [comment]
https://www.ngdc.noaa.gov/geomag/calculators/magcalc.shtml 

![image](https://user-images.githubusercontent.com/44466116/67558037-e08e1c00-f71e-11e9-9f7e-bc3532b8b965.png)
In OsmAnd for iOS   geoNorth and magnetic North is one same, but it's not true.
![image](https://user-images.githubusercontent.com/44466116/67558147-1af7b900-f71f-11e9-96e8-6eda10f1658d.png)

**Comment by max-klaus** [comment]
Fixed by https://github.com/osmandapp/OsmAnd-ios/commit/c23114e4dc9187f2800734533e6dec3eb02c463b
