### ISSUE TITLE
OsmAnd skips a part of a highway

### ISSUE THREAD

**Issue by danielsjf** [osmandapp/Osmand#7454]
I tried to route from Xiahe, Gansu to Kanbula national park east entrance. Somewhere 3 quarters in, the route suggestion leaves the highway and gets back on it at the next ramp. When I navigate via the service station on route, the route is both shorter and quicker. Why is this piece of highway skipped?

**Comment by Discostu36** [comment]
Can you give us the exact locations? There are at least three Xiahe in Gansu.

**Comment by danielsjf** [comment]
Sure, you can try from Xiahe (35.19822, 102.51967) to Kanbula (36.1129, 101.8473). The error happens on this stretch (35.9906, 102.0511). That's also the service station via which I can plan a correct route that is quicker. Below you can also find the screenshots. I'm using the latest version with the latest version of the map (OsmAnd Live).

![Screenshot_20190822-183358__01](https://user-images.githubusercontent.com/6696142/63532855-eb081b80-c50b-11e9-9983-33ba09e851e4.jpg)
![Screenshot_20190822-183423__01](https://user-images.githubusercontent.com/6696142/63532856-eba0b200-c50b-11e9-8e1d-d245cda34323.jpg)
![Screenshot_20190822-183436__01](https://user-images.githubusercontent.com/6696142/63532857-eba0b200-c50b-11e9-88b5-43c37dd2b71b.jpg)
![Screenshot_20190822-183350__01](https://user-images.githubusercontent.com/6696142/63532858-eba0b200-c50b-11e9-9982-dd527ff9a24b.jpg)

**Comment by pl71** [comment]
Like that: [openrouteservice](http://bit.ly/2ZgYigo)?

**Comment by danielsjf** [comment]
@pl71 yes exactly, but that is actually an older version of the map without the service station. There is also a gap in the road there which I've fixed (you will see that adding a third point in the middle still doesn't help while it does is OsmAnd). In the latest version on OsmAnd this should be fixed. The route is exactly what I mean though.

**Comment by Discostu36** [comment]
That's interesting. [OSM Inspector](http://tools.geofabrik.de/osmi/?view=routing&lon=102.01251&lat=36.03442&zoom=18) still reports the issue that you have already fixed.

Graphhopper has the same mistake that Osmand has. OSRM is routing correctly.

**Comment by danielsjf** [comment]
It's especially strange since using an intermediate point fixes the problem. This means that ultimately, all the information is present. Is there a different version of the updates for the routing and for viewing the map?

**Comment by vshcherb** [comment]
Cause it is reproducible in other routing engines most likely it is going to be fixed with map updates
