### ISSUE TITLE
[Feature request] change the winery POI icon

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7457]
It would be more appropriate to use a barrel symbol for a winery POI rather than a pair of scissors.

**Comment by Discostu36** [comment]
![Screenshot_20190822-161626_OsmAnd](https://user-images.githubusercontent.com/30999326/63522284-52b46b80-c4f8-11e9-9e70-9d5271d63400.jpg)
2 out of 3 symbols are correct 😄
