### ISSUE TITLE
Datum bei access:conditional wird nicht berücksichtigt

### ISSUE THREAD

**Issue by PT-53** [osmandapp/Osmand#7459]
Hallo,
ich habe eine kurzfristige Sperrung der Ziegelhüttenstraße in Riedlingen am 14.Aug.2019 mit vehicle:conditional=no @ (2019 Aug 19-2019 Aug 30) eingetragen:
https://www.openstreetmap.org/way/601111540/history
Bei einem Test am 16. Aug. 2019 in OSMand+ 3.4.6 wurde die Ziegelhüttenstraße im auto-routing aber bereits gemieden, obwohl die Sperrung ja erst ab dem 19. Aug. gültig ist.
Das Datum in vehicle:conditional=no @ (2019 Aug 19-2019 Aug 30) wird anscheinend nicht ausgewertet.
Siehe hierzu auch https://forum.openstreetmap.org/viewtopic.php?pid=759157#p759157
Mit freundlichen Grüßen

**Comment by vshcherb** [comment]
594/5000
Hello,
I entered a short-term blocking of Ziegelhüttenstraße in Riedlingen on 14.Aug.2019 with vehicle: conditional = no @ (2019 Aug 19-2019 Aug 30):
https://www.openstreetmap.org/way/601111540/history
In a test on Aug. 16, 2019 in OSMand + 3.4.6, the Ziegelhüttenstraße was already avoided in auto-routing, although the blocking is only valid from 19 Aug.
The date in vehicle: conditional = no @ (2019 Aug 19-2019 Aug 30) does not appear to be evaluated.
See also https://forum.openstreetmap.org/viewtopic.php?pid=759157#p759157
Yours sincerely
