### ISSUE TITLE
[FR] When editing bus_stop node, shelter tag is replaced by covered

### ISSUE THREAD

**Issue by Hellohat** [osmandapp/Osmand#7461]
On OpenStreetMap, if the bus_stop contain the tag shelter=yes, this tag is replaced by covered=yes in OSMand. And in OpenStreetMap, if the tag covered exist, it isn't displayed by OSMand when editing.

I tried this with many bus_stop in France and it's the same problem :-/

**Comment by scaidermern** [comment]
Sounds like a serious bug instead of a feature request.

**Comment by Chumva** [comment]
Can you give more details? What OsmAnd version are you using? And an example of bus_stop with this behaviour.

**Comment by max-klaus** [comment]
Not confirmed. Closing for now.
