### ISSUE TITLE
Have option to show only one bus line

### ISSUE THREAD

**Issue by EmmanuelMess** [osmandapp/Osmand#7465]
If you are traveling on bus it would be very useful to see only the line you are traveling on, without having to have a bus stop selected.

**Comment by vshcherb** [comment]
You can use 1) PT navigation or 2) Select route with context menu and do show on map

**Comment by EmmanuelMess** [comment]
> 1) PT navigation 

Crashes because of RAM overflow, so I couldn't test that feature.

> 2) Select route with context menu

Shows an appbar and a bottom bar that aren't hideable.

Note: I have just now realized you can open profiles and return to map to hide the bottom bar, but that isn't as intuitive as it would need to be, it seems like a bug.
