### ISSUE TITLE
Motorcar routing avoids hw=motorway in favour of parallel hw=motorway_link

### ISSUE THREAD

**Issue by kreuzschnabel** [osmandapp/Osmand#7470]
OsmAnd version: OsmAnd+ 3.4.8
Map data: as of this morning (Live maps)
Device: OnePlus 5T, LineageOS 16.0 (Android 9)

When calculating a route which passes Montabaur (https://www.openstreetmap.org/#map=15/50.4449/7.8378) on the A3 motorway in a westward direction, OsmAnd routing leaves the main carriageway at https://www.openstreetmap.org/node/378146 to follow the parallel motorway_link instead, which acts as a distribution lane for several sub-junctions, joining the main carriageway again at https://www.openstreetmap.org/node/378118. 

IMHO the penalty for leaving a motoway for a motorway_link should be increased.

Some years ago, a similar behaviour could be observed at the "Limburg Nord" junction a few miles to the east when passing eastwards there, but in that place it does no longer occur.

--ks

**Comment by cheweytoo** [comment]
Exactly the same thing happens here:

https://www.openstreetmap.org/directions?engine=graphhopper_car&route=49.41775%2C8.54742%3B49.40107%2C8.54482#map=15/49.4094/8.5464

and here:

https://www.openstreetmap.org/directions?engine=graphhopper_car&route=49.15433%2C8.56397%3B49.13854%2C8.55406

In fact, OSM.org's current GraphHopper router does it too, as can be seen (at time of posting) at those links.

In both cases, routes leave "motorway" to follow "motorway_link" - and rejoin the exact same "motorway" they just left.

This is obvious nonsense and can be _really_ confusing when driving on a road one is unfamiliar with.

Does Osmand use GraphHopper? Should this be a GraphHopper bug instead?

**Comment by cheweytoo** [comment]
Just FYI, I've filed https://github.com/graphhopper/graphhopper/issues/1836 as well.

Since both Osmand and GraphHopper are affected, this should be a valid bug in both places.

**Comment by pieleric** [comment]
> In both cases, routes leave "motorway" to follow "motorway_link" - and rejoin the exact same "motorway" they just left.
@cheweytoo, in both examples you've picked, the map (at the current time) indicates that the motorway_links have a higher (maximum) speed than the motorway. In the first case that's 80 km/h vs 100 km/h. In the later case that's none vs 80 km/h. It's probably an error (either on the map or by the road authorities), and the routing algorithms just try to pick the "fastest way".

That said, I'm pretty sure I'm seen similar issue on places without differences of maximum speed, but I think that was in some curves, where the link was inside the curve, making it slightly shorter.
Maybe putting some extra penalty on the `motorway_links` would solve most of the cases?

**Comment by vshcherb** [comment]
I think it is a problem of https://www.openstreetmap.org/way/143974127#map=17/49.41044/8.54738 (80 kmh) where motorway link has 100 kmh limit, so it prefers faster way (it is a mapping error)
