### ISSUE TITLE
Problem running sample app, APK is limited to architecture arm64-v8a

### ISSUE THREAD

**Issue by tulssinep** [osmandapp/Osmand#7474]
I cannot find any documentation on how to set up the project. I've `git`ed the project into IDEA, let gradle do some magic and am now trying to run the app. Building works fine but simulator as well as actual device cannot run the app,

`Device supports armeabi-v7a, armeabi, but APK only supports arm64-v8a`

I found this link https://osmand.net/help/docs/TechnicalArticles_Wiki-orig.txt but can't much of that working, is it outdated? I can't find any documentation on how to include the other flavors

**Comment by max-klaus** [comment]
You need to adjust Build variant in the Android studio.

**Comment by tulssinep** [comment]
Just in case it's grayed out for anyone else - that was the issue for me; I've had the module's build.gradle opened which disables the "Select Build Variant" button. Thank you for your help.
