### ISSUE TITLE
Mark "Monday-Friday" by default while adding "opening hours" during POI creation [Feature request]

### ISSUE THREAD

**Issue by F5System** [osmandapp/Osmand#7478]
It can be useful if days from "Monday" to "Friday" would be marked by default during "add opening hours" dialog at POI creation, because [as I think] most POI works at least this days. And also it will help people to mark correct days, because now in English version the first day is "Sunday" and a lot of people who start the week from Monday can accidentally think "the first mark is Monday".

**Comment by scaidermern** [comment]
Is this really a good idea? If there are three different opening hours for Mo-Fr, Sa & Su that means I have to:

- Add the first time span. Mo-Fr is preselected. Fine.
- Add the second time span. Mo-Fr is preselected. I have to tap 5 times to unselect Mo-Fr, then another tap for selecting Sa.
- Add the third time span. Mo-Fr is preselected. I have to tap 5 times to unselect Mo-Fr, then another tap for selecting Su.

This feels wrong.

How about either:
- Only preselect Mo-Fr if there are no opening hours yet, or
- Add an unselect all button

**Comment by scaidermern** [comment]
Thanks!
