### ISSUE TITLE
Searching for bouldering, then choosing the yes option, shows no results

### ISSUE THREAD

**Issue by carstenhag** [osmandapp/Osmand#7480]
Basically, search "boulder" or similar. Then tap the boulder yes item. Now, the "Kletterarena Heilbronn" POI should show up, but it doesn't. When tapping the show on map button, it shows up properly.

Current location: Wilhelmstr. 30, 74072 Heilbronn

Desired POI: https://www.openstreetmap.org/way/35336638

I tagged `climbing:boulder=yes` there. Should be enough, I think?

Using osmAnd 3.4.8 with OsmAnd live subscription. I tried redownloading the map but it didn't help.

**Comment by carstenhag** [comment]
![Screenshot_20190827-232133](https://user-images.githubusercontent.com/3776997/63809403-8a6d4a00-c922-11e9-848e-727fc5b80602.jpg)
![Screenshot_20190827-232146](https://user-images.githubusercontent.com/3776997/63809406-8c370d80-c922-11e9-8337-220c989c99b9.jpg)

**Comment by xmd5a2** [comment]
Dev note: issue is reproducible with august Germany_baden-wuerttemberg_europe_2.obf map and Germany_baden-wuerttemberg_europe_19_08_00.obf diff

**Comment by scaidermern** [comment]
I wonder whether this is caused by the same bug as #7331. Sounds very similar.

**Comment by MadWasp79** [comment]
Can't reproduce on October's map with (and without) Live.

**Comment by MadWasp79** [comment]
Can't reproduce the bug on October's map with live (and without it).  
![image](https://user-images.githubusercontent.com/13146346/68109435-3028d080-fef3-11e9-8592-720989ec2c8e.png)

**Comment by MadWasp79** [comment]
Can't reproduce the issue in beta with October map (with and without live). 
![image](https://user-images.githubusercontent.com/13146346/68109664-c957e700-fef3-11e9-9ed0-762841545c58.png)

**Comment by MadWasp79** [comment]
Issue couldn't be reproduced with current maps, we didn't backup monthly maps, only live diffs. 
I found an unmarked (on OSM) climbing center near my location, add it to OSM with similar changes to a building (same tags) and in 30 minutes, after downloading a fresh live update, found it via search without any problems. 
If you encounter similar issues in the future, please notify me.

**Comment by carstenhag** [comment]
Thanks, works now!
