### ISSUE TITLE
App builds, can't run: Caused by: java.lang.RuntimeException at SearchCoreUITest.java:46

### ISSUE THREAD

**Issue by Reiszecke** [osmandapp/Osmand#7481]
What am I doing wrong? This is the third time trying to get this running:

`repo init -u https://github.com/osmandapp/Osmand -m /Users/Alex/Documents/readonly-manifest.xml`

- Import the project by selecting the .repo/manifests/build.gradle
- Set OsmAnd to freedevLegacyFatDebug and the -sample to fatDebug
- Link the debug.keystore in all manifests
- Run it on my API level 24 device

Get
```
        Caused by: java.lang.RuntimeException at SearchCoreUITest.java:46
            Caused by: java.io.FileNotFoundException at SearchCoreUITest.java:46
```

**Comment by vshcherb** [comment]
Answered in the other issue

**Comment by redshirt2** [comment]
What other issue?  Do you have a link?
