### ISSUE TITLE
incorrect rendering for man_made=embankment

### ISSUE THREAD

**Issue by Al-Hun** [osmandapp/Osmand#7485]
Hi !
embankment=yes is different from man_made=embankment
First one, applied to highways/waterways/etc, implies **2 sided** "spikes" while the second is directional as natural=cliff : top on the left side and bottom on the right side of the way (closed or not). Spikes must be **only on one side**. standard osm rendering is ok, as well as JOSM's one.

Thanks,
Alain.

**Comment by xmd5a2** [comment]
Not possible to fix in tile-based default rendering engine. Fixed for OpenGL (primarily iOS).

**Comment by Al-Hun** [comment]
I'm not sure to understand (english...)
"tile-based default rendering engine" means "Osmand (online tiles)" or "offline vector maps" when choosing map source ? I mainly use offline.
Osmand for Android doesn't use openGL for offline vector maps ? I'm not developper...

offline vector rendering is correct for cliffs on my Android phone : it's not possible to do the same for embankment ?

Sorry to insist but I'm not very good in english and make intensive use of dictionnary to write this message...

**Comment by xmd5a2** [comment]
I mean offline vector maps. OpenGL for android is not ready actually and not used by default.
No, cliffs on android are not rendered correctly
![Screenshot from 2019-10-02 18-15-31](https://user-images.githubusercontent.com/5829014/66057021-b04cc680-e540-11e9-8679-b7ba6f85bb66.png)

**Comment by Al-Hun** [comment]
Sorry, I was certain it was ok. Probably Alzheimer...  :(((
Is OpenGL planned for Android ?

**Comment by xmd5a2** [comment]
You can try it by activating developer plugin and activating corresponding option in plugin settings

**Comment by Al-Hun** [comment]
Fine !
I try it immediatly and I stop disturbing you.
Thanks for the job !

**Comment by aceman444** [comment]
It is strange this would depend on the renderer and cannot be done in the current OsmAnd rendering.
The current OpenGL rendering enabled int he OsmAnd development plugin does not solve this in anyway (still spikes on both sides). So what did you mean to say, xmd5a2 ?

**Comment by xmd5a2** [comment]
@aceman444 OpenGL on Android works not on every device. OpenGL rendering looks like this:
![Screenshot from 2019-12-27 10-36-00](https://user-images.githubusercontent.com/5829014/71507340-3dc85a00-2895-11ea-81bd-6f2073727b50.png)

**Comment by aceman444** [comment]
The sample image looks nice. How to determine on which device the OpenGL renderer works? Can OsmAnd tell?

**Comment by vshcherb** [comment]
OpenGL is not released yet to Android
