### ISSUE TITLE
Wrong route calculation

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7486]
OsmAnd suggests making a big detour 
from 55.23666 45.96704  
to 55.23666 45.96704  
while in OSM the route is direct:
https://www.openstreetmap.org/directions?engine=graphhopper_car&route=55.2371%2C46.0915%3B55.2233%2C46.4092#map=11/55.2437/46.3523

![1](https://user-images.githubusercontent.com/50198677/63851175-60f20400-c99e-11e9-8fd7-d8c7b49b2a3b.jpeg)

**Comment by MadWasp79** [comment]
![Screenshot_2019-10-15-10-22-29-258_net osmand plus](https://user-images.githubusercontent.com/13146346/66809510-2afce500-ef36-11e9-85c3-bff85f568b2b.png)
![Screenshot_2019-10-15-10-22-00-819_net osmand plus](https://user-images.githubusercontent.com/13146346/66809511-2afce500-ef36-11e9-8842-d67d74e02465.png)

It seems already fixed. With live and without, for car and pedestrian.
