### ISSUE TITLE
Moving to a far away location leads to empty map

### ISSUE THREAD

**Issue by Discostu36** [osmandapp/Osmand#7491]
OsmAnd: 3.4.8 (Beta 2019-08-20)
Samsung Galaxy A7 (2018)
Android 9

When I move from my current location to a location several thousand kilometers away, the map is empty and zoom is locked. It makes no difference if the map of each location is downloaded or not.

Steps to reproduce:
1. Navigate to New York City
2. Search for "Madrid"
3. Tap onto "Madrid"
4. See an empty map. You can't zoom in or out.

**Comment by Discostu36** [comment]
![Screenshot_20190828-202219_OsmAnd](https://user-images.githubusercontent.com/30999326/63887668-910cc780-c9dd-11e9-88cf-6997d216ac16.jpg)
![Screenshot_20190828-202231_OsmAnd](https://user-images.githubusercontent.com/30999326/63887675-979b3f00-c9dd-11e9-890d-3f078324fcaf.jpg)
![Screenshot_20190828-202239_OsmAnd](https://user-images.githubusercontent.com/30999326/63887692-9e29b680-c9dd-11e9-93d3-c09e35078fa7.jpg)
![Screenshot_20190828-202246_OsmAnd](https://user-images.githubusercontent.com/30999326/63887699-a4b82e00-c9dd-11e9-878f-7a9ed68af0d5.jpg)

**Comment by scaidermern** [comment]
Can confirm. The zoom buttons are locked, but zooming with fingers is still possible.

**Comment by scaidermern** [comment]
Not only happens with search results but also with GPX waypoints far away. Seems to be caused by the animation which zooms out, pans the map to the destination and tries to zoom in.

**Comment by sonora** [comment]
Yes, looks like for operations like this we end up with the map screen well below the min zoom level, so that tapping either zoom button just tells you so without changing tge zoom Looks like a missing check when performing the zoom animation. Not sure yet which commit caused it. I also notice that recently tapping on the name of a place/favorite etc. on its context card does not zoom in onto it any more, maybe the same faulty commit also removed that capability.

**Comment by sonora** [comment]
Obvious suspicion is this one: https://github.com/osmandapp/Osmand/commit/2e884057ab3e8334742f38515a44bba48398a890

**Comment by scaidermern** [comment]
> I also notice that recently tapping on the name of a place/favorite etc. on its context card does not zoom in onto it any more, maybe the same faulty commit also removed that capability.

Yes, I already reported this at #7468.

**Comment by max-klaus** [comment]
> Obvious suspicion is this one: [2e88405](https://github.com/osmandapp/Osmand/commit/2e884057ab3e8334742f38515a44bba48398a890)

Thanks! It was there. Fixed.

**Comment by sonora** [comment]
Great, thanks! Confirmed working.

But the second issue #7468 is still not fixed, not sure it stems from the same commit.
