### ISSUE TITLE
World base map empty at zoom 12+ (near baltic sea)

### ISSUE THREAD

**Issue by Discostu36** [osmandapp/Osmand#7492]
OsmAnd: 3.4.8 (Beta 2019-08-20)
Samsung Galaxy A7 (2018)
Android 9
World_basemap.obf (2019-07-16)

When I navigate to north-eastern Germany or northern Poland, I get an empty world basemap at zoom levels 12 and up. Re-downloading the map didn't change the problem. "Hide overground objects" is not selected. Other regions are not affected.

**Comment by Discostu36** [comment]
![Screenshot_20190828-203848_OsmAnd](https://user-images.githubusercontent.com/30999326/63888552-7c313380-c9df-11e9-9545-fdfd5c091072.jpg)
![Screenshot_20190828-203914_OsmAnd](https://user-images.githubusercontent.com/30999326/63888575-83584180-c9df-11e9-88cd-48a9114a8029.jpg)

**Comment by vshcherb** [comment]
New September maps are going to fix the problem
