### ISSUE TITLE
Render Bug, Thick streets, 

### ISSUE THREAD

**Issue by Jan-Braun** [osmandapp/Osmand#7493]
On OsmAnd+ all streets are rendered very thick. About 4mm wide. All details is lost. The App is unusable. Deinstalled; accidantly installed normal OsmAnd it was fine. Reinstalled OsmAnd+ problem was there again. 
It seems to render for a smaller screen-size or a lower zoom level as I'm actually in.

Redmi Note 5
Android 9 PKQ1.180904.001

**Comment by scaidermern** [comment]
Can you show us a screenshot? Did you change the rendering style, e.g. from the default style to touring style where roads are rendered with a larger width?

**Comment by Jan-Braun** [comment]
I am an idiot. It was just the map magnification. No clue how missed that. Sorry for wasting your time. Maybe a "reset everything" button would be nice, hence reinstalling does not do that ;-)

**Comment by scaidermern** [comment]
You are welcome :)
