### ISSUE TITLE
Navigation on the next turn one turn early

### ISSUE THREAD

**Issue by jkufner** [osmandapp/Osmand#7496]
Using OsmAnd's in-app offline routing, I encountered the following situation:

![Screenshot_2019-08-29-10-18-59](https://user-images.githubusercontent.com/16572/63939931-b266c580-ca68-11e9-9f7d-0fe666cbd030.png)

I was navigating using default car profile. OsmAnd was telling me to turn right, but the route is to go straight. There was a small not that I should turn right in one kilometer, but that is very little number under a very big arrow.

Expected behavior: OsmAnd should be quiet at the moment and show a straight arrow. Once I get pass the crossroad, it should tell me to turn right.

OsmAnd's current behavior is ok for areas with many crossroads and traffic lights. But when there is major crossroad ahed, it should not tell me to turn in one kilometer.

**Comment by vshcherb** [comment]
I think this is acceptable to let user prepare in 1 km turn, that's why visuals are also important to indicate when turn will happen
