### ISSUE TITLE
Quick way to select default map profile

### ISSUE THREAD

**Issue by jej** [osmandapp/OsmAnd#7497]
Hi,
When using OsmAnd, I switch often from bike to walk (when crossing and visiting a town for example) or walk to car (if travelling by car and visiting a town by walk). If I quit OsmAnd and launch again, most of time the default map profile is not adequate...
I would like to suggest a way to easily select the default map profile by a long press on the desired default profile. Example: a long press on the "car" profile on this screen:

![Screenshot_20190829-172932](https://user-images.githubusercontent.com/33821/63954728-168e8700-ca73-11e9-9247-5da869513107.png)

 
would switch the map to the "car" profile (_Voiture_) and select it as default profile in general parameters:
 

![Screenshot_20190829-172950](https://user-images.githubusercontent.com/33821/63954777-2b6b1a80-ca73-11e9-9bf7-31057b193dd0.png)

Hope to see it one day! Maybe an alternative already exists, but I don't know it.
Thanks for this great app anyway.

**Comment by pebogufi** [comment]
In settings you can select your personal default profile. Does this help ?

**Comment by jej** [comment]
No sorry... Read again my proposal.

**Comment by pebogufi** [comment]
No, I don't, there is no need for.
Programmers don't have the capacity to follow every nice idea to make special adaption. At some they will do if the find them worthy, but most ideas will never be realized.
So I recommended a workaround, hoping it could help you a bit. 
But of course you can hope, that your idea will be the one of a thousand which will be realized.

**Comment by jej** [comment]
I understood that it's possible to change the default profile in the general settings. I propose a quick way to do it.

**Comment by naoliv** [comment]
Click here and you should be able to quickly select another profile:
![](https://user-images.githubusercontent.com/982338/63965150-ecd36100-ca6e-11e9-8ff4-6e7258e9839d.png)

**Comment by jej** [comment]
Yes, it's possible to change profile but the choice is not saved. After quitting the app, the profile after startup is the one selected in settings.

Example: I use car profile (and car as default), then switch to pedestrian because I stop and walk in a town. Then I quit osmand because I don't need it for few time. If I start osmand again then default profile is car.

**Comment by jej** [comment]
Now there is an option to set the "default profile" to the last used. It makes this concept a nonsense to me... A user has just to select the profile he wants as default and that's all... No need for an option, and no need to have to choose a default profile.
Like you, I don't understand this implementation.

![Screenshot_20220429-112548_OsmAnd~](https://user-images.githubusercontent.com/33821/165919387-1e7b1629-c7fb-40d2-af15-0fbbf5188449.jpg)
