### ISSUE TITLE
Track split interval lost when opening track settings

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#7501]
The split interval setting is lost when opening the track settings again under My Places.

Steps to reproduce:
- Set a track split interval in My Places -> Tracks -> MyFancyLemuriaTrack
- The Map will now show the track with the configured split interval
- Open the track again via My Places -> Tracks -> MyFancyLemuriaTrack
- The split interval setting is reset to `None` and the map doesn't show a split interval anymore.

Possibly related to #7150.

**Comment by vshcherb** [comment]
You can see the split marker vanishing after deleting a track point: https://imgur.com/a/pMCKRR5

**Comment by vshcherb** [comment]
The split interval setting is lost when adding or removing points from the track. The track color doesn't get lost.
