### ISSUE TITLE
Multimedia notes: Don't grab multimedia keys unless explicitly enabled

### ISSUE THREAD

**Issue by jkufner** [osmandapp/Osmand#7502]
Multimedia plugin currently grabs multimedia keys. Therefore, if I'm listening to music, the player does not get the next/prev song keys because OsmAnd's multimedia notes plugin get's them instead, and thus, I cannot control music player using my little bluettoh keyboard (it has 5 keys volume up/down, next/prev song, and play/pause toggle). The key events go to the last application with focus which handles them and Osmand is have the focus all the time.

It would be nice, if the multimedia notes plugin had a checkbox in the options to enable this grab. Alternatively, there could be a separate trigger plugin which would grab the keys and let multimedia notes plugin know when a key gets pressed. This way it would be possible to use both the multimedia notes and to control the music player.

It is about `android.intent.action.MEDIA_BUTTON` — see https://github.com/osmandapp/Osmand/pull/5412.

**Comment by vshcherb** [comment]
Yes we should follow and enable it similar to Keyboard settings
