### ISSUE TITLE
Resolve openstreetmap.org way URLs

### ISSUE THREAD

**Issue by MayeulC** [osmandapp/Osmand#7505]
### Example URL
`https://www.openstreetmap.org/way/55071957`

And maybe also notes and other URL types:
`https://www.openstreetmap.org/note/998678`

### Context

I often put Openstreetmap.org "way" URLs in my calendar events, and I would like to be able to open them using OsmAnd.

Currently, opening one such link (using Simple Calendar as my calendar application) only results in the URL being copied to the search field, and OsmAnd doesn't know how to deal with this.

I wouldn't be against a quick lookup to openstreetmap.org if that could help. The related file seems to be [this one](https://github.com/osmandapp/Osmand/blob/61493e1c1d9f74c0f5d639e1aab1bddeb926d66f/OsmAnd-java/src/test/java/net/osmand/util/GeoPointParserUtilTest.java).

**Comment by vshcherb** [comment]
I think it is not possible today cause OsmAnd doesn't have index of way ids, it is better to move a bit map and get url like https://www.openstreetmap.org/way/55071957#map=19/45.76766/4.83339
