### ISSUE TITLE
osmand ignores no u turn restriction (again)

### ISSUE THREAD

**Issue by Discostu36** [osmandapp/Osmand#7507]
I have a similar issue like #5645

Osmand ignores this u turn restriction:

https://www.openstreetmap.org/relation/1812522

For example when routing from
https://www.openstreetmap.org/node/448705005
To

https://www.openstreetmap.org/way/9408975

**Comment by Discostu36** [comment]
OsmAnd: 3.4.8 (Beta 2019-08-20)
Samsung Galaxy A7 (2018)
Android 9
Germany_schleswig-holstein_europe.obf from 2019-08-01
Germany_schleswig-holstein_europe_19_09_01.obf

**Comment by MadWasp79** [comment]
fixed in new (1.10) maps
