### ISSUE TITLE
<name> tag for building:part is not displayed

### ISSUE THREAD

**Issue by Prusaker** [osmandapp/Osmand#7508]
At the moment, the name tag for building:part is not displayed.
For fix this issue I propose added one string to default.render.xml:

`<!-- Buildings -->`
			`<switch textHaloRadius="$buildingTextHaloRadiusDay">`
				`<switch minzoom="16">`
....
`<case tag="building:part" value="" nameTag=""/> <!-- New string for building:part -->`
...

**Comment by xmd5a2** [comment]
As a rule, the polygon with the tag building:part are located inside the building polygon, on which the name is placed. In what cases may you need to display a name from building:part polygons?

**Comment by Prusaker** [comment]
If the building is divided into several parts, each of which may have its own name. For example:
https://www.openstreetmap.org/way/41434677
The building is divided into three parts - two dormitores (https://www.openstreetmap.org/way/557439720 , https://www.openstreetmap.org/way/557439722 ) and apartments part. Both dormitores has a name.
