### ISSUE TITLE
access:conditional doesn't work

### ISSUE THREAD

**Issue by Discostu36** [osmandapp/Osmand#7509]
OsmAnd: 3.4.8 (Beta 2019-08-20)
Samsung Galaxy A7 (2018)
Android 9
Germany_schleswig-holstein_europe.obf from 2019-08-01
Germany_schleswig-holstein_europe_19_09_02.obf

A conditional restriction I've entered does not work. 

access:conditional=no @ (2019 Sep 2 07:30-24:00; 2019 Sep 3-2019 Sep 6 00:00-24:00)
https://www.openstreetmap.org/way/4071741

For example when routing from:
https://www.openstreetmap.org/node/986819935

to:
https://www.openstreetmap.org/way/678151502

**Comment by naoliv** [comment]
Maybe the map that you are using still doesn't have this recent change?

**Comment by Discostu36** [comment]
I've got the current Osmand live map.

**Comment by MadWasp79** [comment]
Yes, it seems we have a bug in a native library which ignores this kind of conditional restriction.

**Comment by Discostu36** [comment]
This one is ignored as well
https://www.openstreetmap.org/changeset/74740824
