### ISSUE TITLE
Route calculation issue

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7511]
The segment of the road is avoided by OsmAnd, so the route calculation suggests to leave a road and turn back to the same road. The issue occurs with the car and cycle navigation profiles.
From: 35.0810273, 33.8734007 
To: 35.10459° N, 33.92606° E

**Comment by MadWasp79** [comment]
There is a obstacle = gate on road. https://www.openstreetmap.org/node/5644469223#map=16/35.0879/33.8903
