### ISSUE TITLE
Inconsistency of displayed road names in Germany

### ISSUE THREAD

**Issue by cyclingcat** [osmandapp/Osmand#7513]
Hi there,

there is some inconsistency of the displayed German road names on the OsmAnd map, notably in lower zoom levels. Sometimes the road names are still shown without the leading letter "A" (for "Autobahn" = motorway) and "B" (for "Bundesstraße" = primary road) respectively.

See the following screenshot:

![Screenshot_OsmAnd](https://user-images.githubusercontent.com/32601012/64201786-c7d85700-ce8f-11e9-8035-c1742b28e35d.png)

(note the different yellow labels "96"/"B 96" and the blue labels "111"/"A 10"!) Maybe it's related to #6900 which has been closed and concerned a similar bug?

OsmAnd~ 3.4.6 from F-Droid on bq Aquaris M4.5, Android 5.1
Offline maps of Germany/Berlin and Germany/Brandenburg, version 1 August 2019.

The cycling cat

**Comment by scaidermern** [comment]
Regression of #6900?

**Comment by xmd5a2** [comment]
Fixed by https://github.com/osmandapp/OsmAnd-resources/commit/831f10543c763ad5423525457b5e19c41f6450d8
Another cause of inconsistencies is the fact that world basemap is outdated on our server. Work is underway on it, and the problems will be corrected after its update.
