### ISSUE TITLE
Custom POIs description issue

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7516]
The full description is not available afer tapping on the custom POI if opening the POI on the GPX track.
Additionally, the links in the description are not active, while they were active in the previous OsmAnd version.
![1](https://user-images.githubusercontent.com/50198677/64246389-635fdb00-cf15-11e9-982f-6b124ff05017.jpeg)
![2](https://user-images.githubusercontent.com/50198677/64246393-64910800-cf15-11e9-91f9-521359525c00.jpeg)
When opening the POI's in OsmAnd menu - My Places - Favorites, the description is displayed fully, but the links are not active.
![3](https://user-images.githubusercontent.com/50198677/64246604-be91cd80-cf15-11e9-8e83-3b5891358cee.jpeg)
![4](https://user-images.githubusercontent.com/50198677/64246606-bfc2fa80-cf15-11e9-8818-ff6275a28fda.jpeg)

**Comment by Chumva** [comment]
Fixed with https://github.com/osmandapp/Osmand/pull/7718
