### ISSUE TITLE
Support addr2:* scheme

### ISSUE THREAD

**Issue by SviMik** [osmandapp/Osmand#7523]
Some buildings have more than one address. There's a nice tagging scheme called [addrN](https://wiki.openstreetmap.org/wiki/Proposed_Features/addrN), which solves literally all cases with multiple addresses, including the most complicated ones (see example below).

Right now the tag usage is >10K, which is a good reason to finally implement it:
<img src="http://svimik.com/osmaddrnusage.png">
Now, an example. In Estonia there are building that have quite a few addresses, like:
`Logi tn 2 // 4 // Lootsi tn 13 // 14 // Sadama tn 21 // 25 // Uus-Sadama tn 19`
This bizarre thing is an official record, which assigns 7 addresses to a single land area.
It is easy to transform it into the addrN scheme:
```
addr:street = Uus-Sadama
addr:housenumber = 19
addr2:street = Lootsi
addr2:housenumber = 14
addr2:housenumber2 = 13
addr3:street = Sadama
addr3:housenumber = 21
addr3:housenumber2 = 25
```

**Frequently asked questions:**
- Why not to use address nodes?
1. Several nodes may create an illusion that different addresses belong to different parts of the building, which is not the case. There is no way to make it clear that all the addresses do belong to the whole building.
2. In Estonia (and I believe many in other countries too) an address is assigned to a land property or some other area, it is never a point. The idea of address nodes in OSM is a workaround for the cases when you don't know the exact extent of the address, or don't have enough time/motivation to map it. But a node is never a replacement for a polygon, because it does not contain the important geometry information.
3. Remember that we do not map specifically for OsmAnd. A simplification can be done at map generation stage. It should not be done directly in OSM.

- Why not to use associatedStreet relation?
1. It does not solve the problem with having multiple house numbers for the same street. We would go back to the square one when we still need a tag like `housenumber2`.

**Comment by vshcherb** [comment]
#7521 Merged
