### ISSUE TITLE
[Feature request] support interpolation by alphabet

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd#7525]
It would improve the search results if Osmand could support alphabetical interpolation is such areas of the map, like here: 
https://www.openstreetmap.org/edit?way=685278389#map=20/44.39872/7.53156

**Comment by vshcherb** [comment]
https://www.openstreetmap.org/way/685278389
https://www.openstreetmap.org/way/651532386

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd-resources/pull/666
https://github.com/osmandapp/OsmAnd/pull/10564
