### ISSUE TITLE
Start Navigation button empty/text and icon missing sometimes

### ISSUE THREAD

**Issue by carstenhag** [osmandapp/Osmand#7528]
**Repro steps:**

1. Start the app
2. Tap a point, tap the navigation button
3. Sometimes, the start navigation button will be empty. There will also be no styling at all, the icon is missing.

**What version of OsmAnd are you using, on what device and Android/iOS version?**

OsmAnd 3.4.8 on an OnePlus 5 running Android 9.

**Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?**

I'm using OsmAnd Live / Offline tiles, yes. Doubt it's related to that though.

**Video of the bug:** https://youtu.be/Sm8wiTTSc1g

**Comment by carstenhag** [comment]
I doubt this is a regression. I first installed the app 4 weeks ago and the bug appeared then too.

**Comment by carstenhag** [comment]
I can reproduce this in the current nightly build 3.4.0#24824d  from 2019-09-06.

**Comment by nazar-kutz** [comment]
Fixed with https://github.com/osmandapp/Osmand/commit/7dc3a56ba743f246b6462d0c24869eb6dcd5347d

**Comment by carstenhag** [comment]
Lovely, thanks!
