### ISSUE TITLE
KML import: LineString is not always parsed

### ISSUE THREAD

**Issue by vuvova** [osmandapp/Osmand#7529]
For importing, KML is converted to GPX using `kml2gpx.xslt`

This xslt only recognizes a LineString inside a MultiGeometry. But this is not required by the specs, e.g. in https://developers.google.com/kml/documentation/kmlreference#linestring there is an example of a LineString directly under a Placemark, without a MultiGeometry

In case you're curious, these KLMs are generated by https://sightsafari.city (would be nice to have a plugin for that in OsmAnd, btw :) and gpsbabel can convert them just fine.

**Comment by vuvova** [comment]
Also, it looks like OsmAnd doesn't support `<csvattributes>` in gpx. So a list of kml coordinates has to be split into a sequence of `<trkpt>`

**Comment by nicbou** [comment]
This is still an issue with the KML files generated by uMap. Here's an example map: https://umap.openstreetmap.fr/de/map/morocco-2022_737853
