### ISSUE TITLE
Car routing omits street, making a detour

### ISSUE THREAD

**Issue by carstenhag** [osmandapp/Osmand#7530]
**What version of OsmAnd are you using, on what device and Android/iOS version?**

OsmAnd 3.4.8 on an One Plus 5 with Android 9.

**Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?**

Offline maps./OsmAnd Live

**If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.**

Deutschland Baden-Württemberg 07.09.2019  22:55

__*In case of wrong routing:*__

**Tell us whether you have used OsmAnd's in-app offline routing, or any online routing provider like YOURS, OpenRouteService or OSRM.**

OsmAnd's offline routing.

**What routing profile is chosen in OsmAnd app? (car, bike, pedestrian, fastest or shortest)**

Car. AFAIK I've made no changes.

**Please specify as exactly as possible the start and end point of your route by telling us city name and street name so that we can find it via in-app address search easily. Also, a permalink from openstreetmap.org can be helpful.**

Start: Charlottenstraße, Heilbronn  
End: Wilhelmstraße 30, Heilbronn

**Tell us your expected routing, and how OsmAnd routes, or add screenshots here.**

It should have routed over "Innsbrucker Straße". Possibly it went the other route because it may think there are less traffic lights or else there, but it seems rather unintuitive.

![Screenshot_20190907-234319](https://user-images.githubusercontent.com/3776997/64480564-3a1ba500-d1ca-11e9-9c8a-fc2eb81501ec.jpg)

**Comment by Discostu36** [comment]
For the record:
OSRM is routing over Insbrucker Straße
Graphopper is routing over the service highway of the Lidl parking

**Comment by carstenhag** [comment]
Yeah, it's totally possible to route via the Lidl parking, but it's not the best route I'd say :P (just because it's a private road, there are no gates or something)

**Comment by scaidermern** [comment]
[OSRM route](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=49.1248%2C9.2174%3B49.1352%2C9.2187#map=16/49.1305/9.2190)
[GraphHopper route](https://www.openstreetmap.org/directions?engine=graphhopper_car&route=49.1248%2C9.2174%3B49.1352%2C9.2187#map=16/49.1301/9.2189)

**Comment by MadWasp79** [comment]
In default car profile "residental" street you want it to navigate (Innsbrucker Straße) has a large penalty transition vs "primary" (177 vs 50). You could change it in routing.xml if you want (<way attribute="penalty_transition">), but expect to have more detours in routing.
