### ISSUE TITLE
German TTS reads each digit separately

### ISSUE THREAD

**Issue by davidak** [osmandapp/Osmand#7531]
See this video: [2go.zip](https://github.com/osmandapp/Osmand/files/3587127/2go.zip)

---

OsmAnd~  3.4.6, 3.4.4 and earlier from F-Droid
on Android 8.1.0 (Lineage OS 15.1)
on Xiaomi Redmi Note 4

**Comment by sonora** [comment]
See https://github.com/osmandapp/Osmand/issues/7379. I don't think there is anything OsmAnd can do about it, you just have to find and install a TTS engine which performs as you expect.
