### ISSUE TITLE
Offline routing makes unnecessary turns

### ISSUE THREAD

**Issue by homocomputeris** [osmandapp/Osmand#7532]
OsmAnd 3.4.6, pedestrian and bike

![1](https://user-images.githubusercontent.com/7422433/64488822-9c1cee80-d24c-11e9-9020-c903b4c57924.PNG)
![2](https://user-images.githubusercontent.com/7422433/64488823-9c1cee80-d24c-11e9-8442-a758ae96581f.PNG)
![3](https://user-images.githubusercontent.com/7422433/64488825-9c1cee80-d24c-11e9-96ac-8f6ba1682aae.PNG)
![4](https://user-images.githubusercontent.com/7422433/64488826-9c1cee80-d24c-11e9-8b83-9bcefe89fb88.PNG)
![5](https://user-images.githubusercontent.com/7422433/64488827-9cb58500-d24c-11e9-854e-bc2961a34197.PNG)
![6](https://user-images.githubusercontent.com/7422433/64488828-9cb58500-d24c-11e9-97a5-36effc7c60dc.PNG)
![7](https://user-images.githubusercontent.com/7422433/64488829-9cb58500-d24c-11e9-874f-2cd4a676e9fd.PNG)
![8](https://user-images.githubusercontent.com/7422433/64488830-9cb58500-d24c-11e9-872b-9298f0bae259.PNG)
![9](https://user-images.githubusercontent.com/7422433/64488831-9d4e1b80-d24c-11e9-840f-8d297857a125.PNG)
![10](https://user-images.githubusercontent.com/7422433/64488832-9d4e1b80-d24c-11e9-9e71-05d397ae9105.PNG)
![11](https://user-images.githubusercontent.com/7422433/64488833-9d4e1b80-d24c-11e9-8d79-a80f62e5ce7d.PNG)
![12](https://user-images.githubusercontent.com/7422433/64488834-9d4e1b80-d24c-11e9-8d52-b49abc115054.PNG)
![13](https://user-images.githubusercontent.com/7422433/64488835-9de6b200-d24c-11e9-879c-1f17170128f2.PNG)

**Comment by Discostu36** [comment]
What are your routing settings? Have you activated that the app should prefer minor roads?

**Comment by scaidermern** [comment]
Bicycle routing in OsmAnd is sometimes pretty broken, see also #7534.

**Comment by homocomputeris** [comment]
@Discostu36 

> Have you activated that the app should prefer minor roads?

I can't even find this setting in Bike and Pedestrian modes.

- nothing checked in the Avoid roads menu
- use SRTM, ASTER, EU-DEM is checked
- Consider temporary limitations is checked (first screenshots are older, there was no such function at that time)

**Comment by scaidermern** [comment]
> I can't even find this setting in Bike and Pedestrian modes.

In OsmAnd 3.4.8 it is located under Options -> Driving Style. You will find this setting **only** in the navigation card (when pressing the navigation button) but _not_ in Settings -> Navigation Settings. I guess this is a bug. @vshcherb?

**Comment by homocomputeris** [comment]
> In OsmAnd 3.4.8 it is located under Options -> Driving Style. 

For Bike I have Balanced; for Pedestrian it doesn't exist in 
```
App Version : OsmAnd~
Apk Version : 3.4.6 346
```

**Comment by vshcherb** [comment]
Fixed https://github.com/osmandapp/Osmand/issues/7534 so this one might be fixed as well (too many requests in same issue)
