### ISSUE TITLE
Bad bicycle routing with unnecessary detours

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#7534]
Bicycle routing from 47.81100, 13.04659 to 47.81029, 13.03580 makes unnecessary detours in OsmAnd, independent from the selected driving style. This makes bicycle routing in cities pretty useless.

Balanced:
![photo_2019-09-09_10-05-19](https://user-images.githubusercontent.com/1040784/64513747-83164b00-d2e9-11e9-8c06-daa8bab9fcc8.jpg)

Shorter routes (leading to an even longer route!):
![photo_2019-09-09_10-05-28](https://user-images.githubusercontent.com/1040784/64513772-92959400-d2e9-11e9-800d-dbf50e06676d.jpg)

Prefer byways:
![photo_2019-09-09_10-05-26](https://user-images.githubusercontent.com/1040784/64513790-99bca200-d2e9-11e9-9a07-40d343b4d630.jpg)

Use elevation data is _disabled_.

[GraphHopper](https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=47.81100%2C13.04659%3B47.81029%2C13.03580) and [OSRM](https://www.openstreetmap.org/directions?engine=fossgis_osrm_bike&route=47.81100%2C13.04659%3B47.81029%2C13.03580#map=17/47.81056/13.04118) choose a significantly better route by just going straight through:

![foo](https://user-images.githubusercontent.com/1040784/64514014-1baccb00-d2ea-11e9-8b06-c6b3187ec06c.png)

See also #6954 and #7532.

**Comment by scaidermern** [comment]
Does OsmAnd have a problem with [cycleway=shared_lane](https://www.openstreetmap.org/way/62074085)?

**Comment by MadWasp79** [comment]
Tweaked params in routing.xml, increasing the priority of shared_lane and the penalty for turns, so now it builds more straight routes, especially for speed mode, where the speed for all major (motorway-trunk-primary-secondary-tertiary and links) roads are equal.
