### ISSUE TITLE
Destination icon stay on the map after navigation in finished

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/Osmand#7539]
After navigation is finished, the destination icon is visible on the map.
First case: If close finish dialog by tapping on the close button or on the map.
Second case: if the screen was turn off, navigation ended in the background without the dialog.
![Screenshot_20190911-112336](https://user-images.githubusercontent.com/9365308/64682390-0e2e4700-d48a-11e9-8af0-905a103db606.png)

**Comment by vshcherb** [comment]
Probably fixed by @crimean
