### ISSUE TITLE
Unicode characters shown incorrectly if 1st letter is latin font

### ISSUE THREAD

**Issue by Gollam** [osmandapp/Osmand#7541]
![image](https://user-images.githubusercontent.com/765342/64696332-6ff8ac00-d49e-11e9-9944-620b6168acca.png)

Android 9, Osmand+ 3.4.8

These are the offline maps of Hungary. I don't know which layer of it that is, I cannot find the same route on openstreetmap.org. This is the location of it: https://www.openstreetmap.org/#map=17/47.71621/18.90701

**Comment by xmd5a2** [comment]
Looks like if label starts with ★ character then font without unicode symbols is used. Screenshot from OsmAndMapCreator
![Screenshot from 2019-09-26 16-21-24](https://user-images.githubusercontent.com/5829014/65691562-b7279500-e079-11e9-8c05-da645c4d3fe8.png)

**Comment by Gollam** [comment]
@xmd5a2 hi, any ideas how we can move this forward? I downloaded osmand map creator to check it myself, but I haven't been able to open that view. Can you help me?

**Comment by vshcherb** [comment]
![image](https://user-images.githubusercontent.com/1042025/84051445-78d7c900-a9af-11ea-8056-0a315cb8d7bb.png)
Looks like it works for new android systems at least

**Comment by Gollam** [comment]
@vshcherb thanks, is that android 10?

Another issue with this route, is that the sign for it should be white, with a horizontal blue line in the middle, instead of a full blue square. It should look like this:

![image](https://user-images.githubusercontent.com/765342/84109167-58952200-aa22-11ea-8d7f-ec799d317196.png)

Do you think that is a rendering problem, or an issue with the map source? Where is that route info defined? I couldn't find it so far. If it is an issue with the map source, it could be corrected.

**Comment by Gollam** [comment]
Ok, finally I've found the definition of the E4 route, in which the osmc:symbol tag contains the `blue:blue::★4:yellow` definition. I don't feel that star belongs there, so I replaced the text with E4.
