### ISSUE TITLE
appMode="default" condition doesn't function properly on device

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#7545]
Line
```
<apply_if appMode="default" maxzoom="16" order="-1"/>
```
is skipped by renderer
https://github.com/osmandapp/OsmAnd-resources/blob/master/rendering_styles/default.render.xml#L2608
OsmAndMapCreator tile-based rendering engine accepts this condition

**Comment by vshcherb** [comment]
Delete this bad-bad-bad code - https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/OsmandSettings.java#L2777
+ Make 1 extra parameter "baseAppMode". 
Calculate appMode dynamically during rendering and baseAppMode should represent baseAppMode of the application

**Comment by vshcherb** [comment]
Once it is done @xmd5a2 will use baseAppMode="car" to display car related features

**Comment by xmd5a2** [comment]
Fixed
