### ISSUE TITLE
TTL voice speak "1.ogg" for 1 hour in russian language

### ISSUE THREAD

**Issue by RussianFox** [osmandapp/Osmand#7546]
After recalculating the route if the time is 1 hour ttl says "1.ogg"

**Comment by sonora** [comment]
The fix proposed is not the right one, it would remove the capability to announce "1 hour" completely.

Please look at e.g. the English file: What you have to do is introduce the equivalent of
`dictionary["1_hour"] = tts ? "one hour " : "1_hour.ogg";`
then use
```
function hours(minutes) {
	if (minutes < 60) {
		return "";
	} else if (minutes < 120) {
		return dictionary["1_hour"];

```

Trouble here is that the Russian non-TTS voice will also have to provide a corresponding file `1_hour.ogg`. Either this is missing, which would be a bug from when it was created, or you may somehow be able to concatenate it from the pool of existing files `1.ogg`, `hour.ogg`, `hours_a.ogg` and `hours_ov.ogg`, I cannot tell.

@PaulStets Maybe you can take a look here?

**Comment by PaulStets** [comment]
@sonora The issue was caused by a missing space between the file names. Should be ok now.

**Comment by sonora** [comment]
Hey Paul, yes, that's part of the issue. But it still looks weird, because in the '2 and more hours' case 3 lines below there is a !tts? switch, and in the 1 hour case there is not. Have not looked at details, but I guess it could still need an overall check and test, both for the tts and recorded cases.

**Comment by RussianFox** [comment]
@sonora I was check my commit

![image](https://user-images.githubusercontent.com/11329995/64944974-41048080-d878-11e9-82b9-fafaaee160c2.png)

![image](https://user-images.githubusercontent.com/11329995/64944985-46fa6180-d878-11e9-90b6-87924bca5636.png)

**Comment by RussianFox** [comment]
The wrong code was added in this commit (https://github.com/osmandapp/OsmAnd-resources/commit/3ef060275f3b891d350e498e3beaa2fe53159f21), similar to English

**Comment by RussianFox** [comment]
And now bug is not fixed :(

**Comment by PaulStets** [comment]
@RussianFox You are right, after further investigation, I found out that the lines were indeed redundant. I removed them with https://github.com/osmandapp/OsmAnd-resources/commit/d634118fed6ef5cf00c314050c4bd38a7575345c
