### ISSUE TITLE
lake's name strange visibillity

### ISSUE THREAD

**Issue by 532910** [osmandapp/Osmand#7547]
https://www.openstreetmap.org/way/32947787

The name is visible only at 13 zoomlevel and not on more higher.
![image](https://user-images.githubusercontent.com/14617699/64842751-cf27ff00-d60b-11e9-8eac-ea250f6c796d.png)
![image](https://user-images.githubusercontent.com/14617699/64842756-d18a5900-d60b-11e9-9e15-efa7e82c4828.png)

**Comment by xmd5a2** [comment]
Name is being superseded by street names. It is visible at zoom 17+ but in place of the centroid of the lake which lies outside of water polygon. It is a known issue.
![Screenshot from 2019-10-09 10-36-24](https://user-images.githubusercontent.com/5829014/66460994-b7b02a80-ea80-11e9-8312-3b93a5567dce.png)

**Comment by 532910** [comment]
Is it fixed?

**Comment by xmd5a2** [comment]
No. Duplicate of https://github.com/osmandapp/Osmand/issues/4692
