### ISSUE TITLE
[Feature request] Option to enable announcing of "continue straight on..." for headless (bicycle) routing

### ISSUE THREAD

**Issue by chau-intl** [osmandapp/OsmAnd#7553]
I'm using this app to navigate *headless* when bicycling (I have my phone in a pocket and a headset to get the announcements). Since I can't see the screen it would be nice to have the app tell me to just "continue straight on *name-of-current-road*" and maybe announce which road I should cross. I think this feature should be an option you could turn on/off and could be used for all kinds of transportation. 

This feature would help to ensure me, that I am still following the route when the route is just going straight and thus the time between announcements gets longer.

**Comment by vshcherb** [comment]
Suggested: setting will have timing by "X min" announce "Continue to go YYY XXX m".

We need to check if it works the same as "Repeat navigation instruction"

**Comment by vshcherb** [comment]
I think we already have "Repeat navigation instruction", please test it.

**Comment by chau-intl** [comment]
Sorry for the late reply, I have been off for the holidays. 

I think the "Repeat navigation instruction" is an approximation and I currently have it set to the lowest possible value. 

When I don't have a screen to look at the message "continue straight on _name-of-current-road_" or "continue crossing _name-of-intersecting-road_" is almost as important a message as turn left or right.

I guess using the app headless requires a different level of announcements and maybe even more detailed announcements to give me the same understanding of where I am and where I should go.

**Comment by sonora** [comment]
The way I understand this request is to enhance the trurn prompts by an additional variant "_straight ahead on XX_", which would be triggered for every intersection where you do not have to turn?

**Comment by chau-intl** [comment]
> The way I understand this request is to enhance the trurn prompts by an additional variant "_straight ahead on XX_", which would be triggered for every intersection where you do not have to turn?
In its most basic form, yes.
Maybe this could be limited to _major_ roads, or only do it with roads which completely intersects and not T-intersections.

But it might not be the best solution. The issue I would like to see a solution to is when I drive by car I can look at the screen and I can verify that I am following the route. When I ride my bike and use the app _headless_ I only get an indication of if I am on the right path, if I get an announcement.

If I get a turn announcement I normally get a road name reference. Where I live the road names are usually difficult to read while driving, so I expect the road name reference is a help for either jugging up my memory of the road network or for recognising the road on the map. A more useful reference would be something visual, ex. _turn left on XX just after McDonalds on the right_ or something similar - if a POI is just next to the road _and_ the intersection I think it would be more useful for navigation.

It is of course outside the scope of this feature request, just pondering.
