### ISSUE TITLE
Foreign streets listed as part of the city

### ISSUE THREAD

**Issue by Famlam** [osmandapp/Osmand#7554]
What version of OsmAnd are you using, on what device and Android/iOS version?
Version 3.4.8 (unlimited) on LG Q7
Offline map of Gelderland (updated 1-9-2019)

1. Plan a route by using the option "search a street in Nijmegen" (or first choose Nijmegen, then a street in Nijmegen)
2. Notice that, in the list of streets in Nijmegen, there are also streets listed that are located in Germany. For example Zyfflicher Straße, which is actually located in Kranenburg, Germany (i.e. https://www.openstreetmap.org/way/255617600 )

Expected result is of course to only see streets in Nijmegen. (And if I see streets outside Nijmegen, I expect to see the true city name, rather than Nijmegen). Examples:
![Screenshot_2019-09-13-16-54-52](https://user-images.githubusercontent.com/1315520/64872667-e553b080-d647-11e9-8e5c-dd2d7a959a72.png)

**Comment by xmd5a2** [comment]
Fixed
