### ISSUE TITLE
Search for bicycle pump only partly working

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#7561]
Search for "pump (bicycle store)" only returns the combination `shop=bicycle` + `service:bicycle:pump=yes`. It doesn't return other combinations such as `amenity=bicycle_repair_station` + `service:bicycle:pump=yes` which is also pretty common and important for cyclists.

**Comment by vshcherb** [comment]
hm... agree the whole category could be renamed and changed to  "pump (bicycle)"

**Comment by xmd5a2** [comment]
I've added a filter to bicycle_repair_station https://github.com/osmandapp/OsmAnd-resources/commit/76b13f0c9860de3c6b706c96ae97c1343a05f2af?diff=split
It is possible now to create a custom filter but it is still unavailable for direct search ("pump" lists only shop=bicycle but not amenity=bicycle_repair_station)
