### ISSUE TITLE
Maps overlapping

### ISSUE THREAD

**Issue by dew54** [osmandapp/Osmand#7562]
Hello, i'm looking for making a road unaccessible  just importing a little .obf file in wich i specify the tag "  access = 'no'  " on a single node of a way, overlaying the unaccessible node to the rest of the nodes/ways (Specified in another  imported .obf file) . Is it possible? How could i do that?
Thanks a lot! 
Bye, Davide

**Comment by vshcherb** [comment]
Yes it is possible, if you have the right name of the obf file and in your file you will have road with same id, it will become inaccessible. We do exactly the same when we use Live Maps. So you just need to have proper file name and same id of the node or way

**Comment by dew54** [comment]
Hi vshcherb! First, thanks for your reply!
Uhm..  you said

>  So you just need to have proper file name

Please, could you explain what do you mean with "proper file name"?

Thanks a lot, 
Davide

**Comment by vshcherb** [comment]
try different names like osmand live and it should work. Sorting by name algorithm is in the code.

**Comment by dew54** [comment]
Hello, vshcherb,  sorry for the late reply, i've tried to name the new file like both "AAA.obf" and "ZZZ.obf" and it doesnt seem to work :/  anyway, i've checked that the node id is right, and it is.
So i still don't inderstand :( .. Please could you give me some help?
Thanks a lot, Davide

**Comment by vshcherb** [comment]
Did you try otherwize ZZZ.obf and AAA.obf? We have 1 issue going with osmand live data but it is mostly related with route result preparation. 
Typically patches are called and sorted (the last one is the most important patch):
```
Map.obf (full)
Map_19_09_00.obf (patch for 09 month overrides full map)
Map_19_09_13.obf (patch for 09-13 day overrides 09 month patch)
```
