### ISSUE TITLE
mobile tag excluded from OsmAnd's taginfo project 

### ISSUE THREAD

**Issue by pyrog** [osmandapp/Osmand#7573]
Hi,

`contact:mobile` and `phone:mobile` tags are listed in [taginfo.json](https://builder.osmand.net:8080/view/WebSite/job/OsmAndTagInfo/ws/taginfo.json), but `mobile` and `phone` are missing.

See also https://github.com/osmandapp/OsmAnd-tools/issues/319

These tags are listed in [osmandapp/OsmAnd-resources/obf_creation/rendering_types.xml#L524](https://github.com/osmandapp/OsmAnd-resources/blob/master/obf_creation/rendering_types.xml#L524) and processed by ` processEntityConvert()` in [osmandapp/OsmAnd-tools/obf-generation/taginfo.groovy](https://github.com/osmandapp/OsmAnd-tools/blob/master/obf-generation/taginfo.groovy).

Does `processEntityConvert()` could add `to_tag1` key to solve this issue ?

```xml
<entity_convert pattern="tag_transform" from_tag="contact:mobile" if_not_tag1="mobile" to_tag1="mobile" map="no"/>
<entity_convert pattern="tag_transform" from_tag="phone:mobile" if_not_tag1="mobile" to_tag1="mobile" map="no"/>
```

`opening_hours`, `mobile` and `phone`  are listed in [osmandapp/OsmAnd-resources/poi/poi_types.xml](https://github.com/osmandapp/OsmAnd-resources/blob/master/poi/poi_types.xml)

```xml
<poi_additional name="phone" tag="phone" type="text" order="82"/>
```

**Comment by vshcherb** [comment]
Well it might not be correct cause to_tag1 means artificial tags, so it is unclear whether it is ok or not.
It should be added from poi_types.xml: https://github.com/osmandapp/OsmAnd-resources/blob/master/poi/poi_types.xml#L24
cause it doesn't have attribute no_edit

**Comment by vshcherb** [comment]
Fixed
