### ISSUE TITLE
Conditional access: foot:conditional on barrier gets ignored

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#7576]
OsmAnd seems to ignore `foot:conditional` on a `barrier=gate`.

The [route](https://www.openstreetmap.org/directions?engine=graphhopper_foot&route=51.05585%2C13.77257%3B51.05335%2C13.77248#map=18/51.05460/13.77256) is from 51.05585, 13.77257 to 51.05335, 13.77248.

There are two gates ([node 6805271701](https://www.openstreetmap.org/node/6805271701), [node 961476573](https://www.openstreetmap.org/node/961476573)) both tagged with:

```
barrier=gate
foot=yes
foot:conditional=no @ (Jan 16:30-08:00; Feb 17:00-08:00; Mar 18:00-08:00; Apr 19:00-08:00; May-Aug 20:00-08:00; Sep 19:00-08:00; Oct 18:00-08:00; Nov 17:00-08:00; Dec 16:30-08:00)
```

Nevertheless OsmAnd always routes through it, even during night time.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/pull/7714

**Comment by scaidermern** [comment]
Works fine now, thanks!
