### ISSUE TITLE
Map details disappear

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7578]
In Kenilworth forest, Australia, the forest becomes blank while on the closer zoom levels. Starting from the 5 km zoom level, the forest is displayed in green.
![1](https://user-images.githubusercontent.com/50198677/65240958-166e2e00-daeb-11e9-9087-7ade3b206b8d.jpeg)
![2](https://user-images.githubusercontent.com/50198677/65240959-1706c480-daeb-11e9-8ec4-23c689d96683.jpeg)

**Comment by aslanosm** [comment]
The issue is not in OsmAnd. 
On [OpenStreetMap](https://www.openstreetmap.org/edit?editor=id#map=16/-26.6746/152.6503)  the forest mapped via relation. But it must be via polygon.
It must be fixed on OpenStreetMap

**Comment by scaidermern** [comment]
> The issue is not in OsmAnd.
> On [OpenStreetMap](https://www.openstreetmap.org/edit?editor=id#map=16/-26.6746/152.6503) the forest mapped via relation. But it must be via polygon.
> It must be fixed on OpenStreetMap

Why?

Mapping a wood area as relation is completely fine. [Bellthorpe National Park](https://www.openstreetmap.org/relation/8278071) is already tagged with `natural=wood`.

**Comment by aslanosm** [comment]
>
 But is not as polygon, it is as line. You can check the forest that tagged with polygon is ok in OsmAnd.

**Comment by naoliv** [comment]
The relations https://www.openstreetmap.org/relation/8278071 and https://www.openstreetmap.org/relation/1506584 are fine and valid in OSM.
There is no need to map them as a simple polygon (with tags in the ways).

**Comment by xmd5a2** [comment]
I can't reproduce this but world overview map does not have details at zoom 12+. You need to download detailed map.
![Screenshot_2019-10-07-10-20-06-245_net osmand plus](https://user-images.githubusercontent.com/5829014/66292304-aafacd80-e8ec-11e9-83f2-6e0224de7c83.png)
