### ISSUE TITLE
Unnecessary turn during the navigation

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7582]
The issue occurs on the route in Hungary in the custom and car base navigation profiles. Changing the navigation settings does not affect the route calculation results. The issue does not occur in OSM either.
from: 47.60112° N, 19.36006° E
to: 47.60188° N, 19.37207° E
![image](https://user-images.githubusercontent.com/50198677/65329082-708cf300-dbc0-11e9-8bb0-29f3325eafd9.png)

**Comment by aslanosm** [comment]
Hi,
the primary road has tag maxspeed=50, but residential roads don not have any limits.
Did you try to set in Navigation setting "Fuel-efficient way"?
Or need to set speed limit on OSM for closest residential roads, if there is such.

**Comment by vshcherb** [comment]
It is pedestrian routing so it might be better route if the mapping is not good for sidewalk
