### ISSUE TITLE
minor settings (alpha) problem

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#7587]
after changing language you need a close and clear cache for change of menu language.
version 3.4.0 #28073

... and please make the version info in Help / About copieable to clipboard on a loong press. That helps providing that info.
Thanks Peter

**Comment by Chumva** [comment]
Can you please add more info? Does after changing language nothing happens?

**Comment by pebogufi** [comment]
The language of menus stays unchanged. With "old" setting i get a message that i have to restart the app and the screen is refreshed, and everything is with new language.

**Comment by Chumva** [comment]
Could you tell your android version?

**Comment by pebogufi** [comment]
Samsung Tab A (2016)
Model : SM-G930F
Android : 8.1.0
Only changed language.
currently i could see if after changing languge, if i wait for several seconds, i see the change.
but if i change, then leave this point with System-back, or with back-arroe in top line, i don't see any change.
So it only happens if i am impatient.
