### ISSUE TITLE
time consiming [bug] in creating screen after start

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#7589]
After close and clear cache restart of osmand, no touching of screen, only regarding what happens:
- first favourites  becomes visible
- hillshade layer  becomes visible
- map with more and more details  becomes visible
- map **disappears**, only favourites and hillshade layer stay visible
- map reappears 
...
Version 3.4.0 #28073

**Comment by scaidermern** [comment]
Does this always happen? A disappearing map happens while updating maps via OsmAnd live. The map appears again after the update has been processed. Is this what you are experiencing?

**Comment by pebogufi** [comment]
more tests now this morning:
first refresh of all live maps manually, then start of test allways starting with clear cache.
1 - same as reported, but i watched and could see in system reporting in top line download some obf.
2 - same as reported, but i watched and could see in system reporting in top line download some more obf.
3 - same as reported, but i watched and could see in system reporting in top line download some more obf.
4 - no more obf, no more "unnecessary refresh"
5 - no more obf, no more "unnecessary refresh"
So it is clear, but i am astonished about often dnl of files within 2 or 3 minutes.
sorry.
Close thread now ?

**Comment by vshcherb** [comment]
If you make it - After close and clear cache.

It tries to reindex all files, reindexing 1 file could take 1-5 seconds and it ends up in a long run. Also it is possible issue that same file is reindexed twice for different needs routing, poi, map.

**Comment by vshcherb** [comment]
Once cache is built, restart should be fast enough.

**Comment by pebogufi** [comment]
When automatic downloading multiple files for live one after an other after app start in the morning (they are set to dnl in the morning), it lools like that refresh of map is made for each of downloaded file.  I will pay attention to that, but i can test only once in a day...

**Comment by pebogufi** [comment]
After latest test, it is ok.
