### ISSUE TITLE
Ski routing: add height profile and difficulties to the route details

### ISSUE THREAD

**Issue by pietervdvn** [osmandapp/Osmand#7593]
When cycling, a neat height profile and surface graph show up. Not so with skiing.

Please add these or provide guidance on how to enable this.

**Comment by pietervdvn** [comment]
Ok, I'll play with it later on... I still have quite some packed days ahead of me.

 Is adding a '<rendering_attribute name="routeinfo_ski_difficulty>'-block enough to have them at the details view? Or is additional work needed?

**Comment by vshcherb** [comment]
should be enough. you can copy paste and it also should work

**Comment by pietervdvn** [comment]
I added such a block to skimap.render.xml and copied this over to my phone (net.osmand.plus/files/render/skimap.render.xml), but nothing happened. Do I perhaps have to build the app to have this show up?

**Comment by vshcherb** [comment]
Probably @xmd5a2  could give it a try, anyway it is inside our repository so we can try to fix it on our side

**Comment by pietervdvn** [comment]
The code I tried in skirendering to make @xmd5a2 's life easier:

Also: height profiles would be a big plus. I suspect that somewhere, a flag must be enabled to generate ski pistes with height information.

````
    <renderingAttribute name="routeInfo_surface"> <!-- Used in route details info -->
		<case additional="piste:difficulty=novice" attrColorValue="$pisteAreaDifficultyNoviceColor" attrStringValue="novice"/>
        <case additional="piste:difficulty=easy" attrColorValue="$pisteAreaDifficultyEasyColor" attrStringValue="easy"/>
        <case additional="piste:difficulty=intermediate" attrColorValue="$pisteAreaDifficultyIntermediateColor" attrStringValue="intermediate"/>
        <case additional="piste:difficulty=advanced" attrColorValue="$pisteAreaDifficultyAdvancedColor" attrStringValue="advanced"/>
        <case additional="piste:difficulty=expert" attrColorValue="$pisteAreaDifficultyExpertColor" attrStringValue="expert"/>
        <case additional="piste:difficulty=freeride" attrColorValue="$pisteAreaDifficultyFreerideColor" attrStringValue="freeride"/>
        <case additional="piste:difficulty=extreme" attrColorValue="$pisteAreaDifficultyExtremeColor" attrStringValue="extreme"/>
        <case additional="piste:difficutly=undefined" attrColorValue="#e8e8e8" attrStringValue="difficulty_undefined"/>
	</renderingAttribute>
````

**Comment by xmd5a2** [comment]
Fixed
https://github.com/osmandapp/OsmAnd-tools/commit/f784db2c699f08e712d168f819ee5f0ec276eddf
https://github.com/osmandapp/OsmAnd-resources/commit/ba67d4f87ad9dbf3814ce6f7c8bbb12d02a7ba77

**Comment by pietervdvn** [comment]
God damn it - still have to wait till tomorrow to try the nightly :wink:

**Comment by xmd5a2** [comment]
Elevation profiles will work with november maps and beyond. Elevation data is embedded in maps and they must be regenerated.

**Comment by xmd5a2** [comment]
![Screenshot_2019-10-07-15-27-28-441_net osmand plus](https://user-images.githubusercontent.com/5829014/66382191-6aba4e80-e9c3-11e9-887e-0fdc50b8869e.png)
![Screenshot_2019-10-07-14-59-31-471_net osmand plus](https://user-images.githubusercontent.com/5829014/66382192-6b52e500-e9c3-11e9-8dd0-68da9fa4c3b7.png)

**Comment by pietervdvn** [comment]
Yeah, I suspected that - but the info on ski piste difficulty and type should already work tomorrow right?

Anyway, really thanks for the fix! Skiing is gonna be awesome!

**Comment by xmd5a2** [comment]
Yes, difficulty and type should work

**Comment by pietervdvn** [comment]
Haha, thanks! But I'm afraid there aren't that much ski pistes in Belgium XD

If you feel like it, Auvergne-Rhône-Alpes (more specifically [here](https://www.openstreetmap.org/#map=14/45.5059/6.6593)) is the region where I always test cause I went there last year and'll be returning.
