### ISSUE TITLE
[bug] swimming pool vs sport center

### ISSUE THREAD

**Issue by letypequividelespoubelles** [osmandapp/Osmand#7594]
Sportcenter with tag sport=swimming isn't shown as an swimming pool. It could be good!

**Comment by xmd5a2** [comment]
I think that sports center tagged as leisure=sports_centre + sport=swimming should not be rendered as swimming pool because usually it is a building.

**Comment by letypequividelespoubelles** [comment]
? And so?  While searching a public place to swim, what is the difference between swimming pool and sport center where I can swim?
In osmand French, it's the case while searching "piscine".  And the big one doesn't appear because they are tagged as sport center.

**Comment by xmd5a2** [comment]
It is possible to make such objects searchable as POI "swimming pool" but rendering a building as open water is not an option

**Comment by letypequividelespoubelles** [comment]
Yes, I agree, it's not good for the rendering. But what I suggested is just to show both when we search for POI " swimming pool ".  Sorry if I was unclear.

**Comment by letypequividelespoubelles** [comment]
So is it possible to reopen it as we agreed?  Thx

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/c112bd472d66a8b0e855515a37901a4dcf1f1871

**Comment by letypequividelespoubelles** [comment]
Thx. I'll need to put a nose in the code to be able to do it next time 😋
