### ISSUE TITLE
Add CyclOSM - a free & open cycling oriented OSM render

### ISSUE THREAD

**Issue by mikehgentry** [osmandapp/Osmand#7595]
https://github.com/cyclosm/cyclosm-cartocss-style

Not sure if you can borrow any style ideas (or even code) from these guys, but the maps are really quite nice in my opinion, and I'd say it'd definitely be worth adding as an online tile source.

Note: I am not affiliated with the project, and haven't asked whether they thought it'd be a good idea or anything - not really sure what the protocol is for things like this. These are the people providing the main tileserver: https://www.openstreetmap.fr/

**Comment by vshcherb** [comment]
Great, though we don't support cartocss styles, so we will need to add at the raster style to our server first.

**Comment by mikehgentry** [comment]
Here's a video with some detail about their design decisions. One of the devs even mentions using the tiles in OsmAnd (at about the 25:30 mark).

https://media.ccc.de/v/sotm2019-1280-cyclosm-a-bicycle-oriented-render-for-every-cyclist

**Comment by mikehgentry** [comment]
Now added, see here.

https://github.com/osmandapp/Osmand/issues/7650
