### ISSUE TITLE
Wrong keep right

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/Osmand#7599]
35.38033 24.58107
![photo_2019-09-11_14-53-08](https://user-images.githubusercontent.com/9365308/65689138-0919ec00-e075-11e9-9b58-ae4b7f25c670.jpg)

**Comment by MadWasp79** [comment]
1) there is no actual road on the right, its mapping error. Fixed in OSM.
2) Added "tertiary" roads to list with "_link", "unclassified" etc. in highwaySpeakPriority()
