### ISSUE TITLE
Support night mode

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/Osmand#7606]
![image](https://user-images.githubusercontent.com/9365308/65695413-315b1800-e080-11e9-9564-ebc314598490.png)

**Comment by dmpr0** [comment]
After theme change restart is needed, also fix font color.
![photo_2019-10-28 16 30 30](https://user-images.githubusercontent.com/9365308/67687045-594fdb00-f9a0-11e9-95a5-5698234ab72d.jpeg)

**Comment by max-klaus** [comment]
https://github.com/osmandapp/Osmand/commit/9d50cf4f15d063cffb32023f5d9daa1533383899#diff-a45db21bcc1343ffaed091d2b2b61438R105
