### ISSUE TITLE
OsMo plugin communicates via cleartext HTTP

### ISSUE THREAD

**Issue by pmocek** [osmandapp/OsmAnd#761]
When sharing the seemingly-otherwise-private code for location tracking to another user via SMS, a URI with HTTP scheme (cleartext; without SSL) is generated for a resource at z.osmo.mobi.

Information about users' locations should be encrypted in transit.  If this is not feasible, they should be warned that the information will be communicated in an insecure manner.

**Comment by n1trux** [comment]
Does this happen in HTTPS now? Since the OsMo site uses Let'sEncrypt, it seems the devs are aware of that issue.

People defending plaintext data transfer ITT are not that smart…

**Comment by GaMsh** [comment]
OsMo plugin has been removed in future OsmAnd releases
