### ISSUE TITLE
"poi_types.xml" is missing in the resources

### ISSUE THREAD

**Issue by Dmitry-Borodin** [osmandapp/Osmand#7610]
I'm trying to build the project
./gradlew --refresh-dependencies clean assembleFullLegacyFatDebug triggers 
SearchCoreUITest.java:46 to run, which is failing, because there is no "poi_types.xml" file in resources and anywhere in the project.
What am I missing? How does it work on CI?

**Comment by vshcherb** [comment]
https://osmand.net/help-online/faq#dev-environment

**Comment by a-elhaddad** [comment]
Same bug, how to setup development environment needed? @vshcherb
