### ISSUE TITLE
Rendering bug: not all custom lines are shown

### ISSUE THREAD

**Issue by Bernhard-Hiller** [osmandapp/Osmand#7615]
Using OsmAndMapCreator, I created an obf file containing additional lines with the tags 
 bcontourtype and bcontour. I used inspector and josm to prove that those lines are present in the obf file.
I tried to show them with a custom render.xml. It works partially. Mostly, the lines are shown, but some are not. 
See also https://github.com/osmandapp/OsmAnd-tools/issues/328#issuecomment-536270022 which shows some problems encountered on my way here, but the effect is still the same: the lines are missing north-east of Niebla, but are present south of it. And with the tag_transform operations, I want to exclude that any "native" rendering interferes.

The BERNIE.render.xml can be obtained from https://drive.google.com/file/d/19RzK8d8SXMrTaVlbnou985By97PGKt8b/view?usp=sharing
rendering_types.xml from https://drive.google.com/file/d/1jSXITGwml7nuiitGMiTh9VbWyjxgU1D2/view?usp=sharing
SurChico.obf file from https://drive.google.com/file/d/1Pm2VAs0RQS6WwDAFoCu-FSXVID0pqJz4/view?usp=sharing

**Comment by vshcherb** [comment]
Indeed it is quite strange

**Comment by xmd5a2** [comment]
@Bernhard-Hiller 
I see strange huge objects id's
original_id=-1841616395699466
osmand_id=-235726898649531525
Maybe it is a cause of issue. Can you try to check that or provide contours source?

**Comment by Bernhard-Hiller** [comment]
Thanks for your efforts, xmd5a2. The data were generated with Srtm2Osm, as described in a comment in the linked OsmAndMapCreator issue. But all Ids were positive, though close to 2^63.
Since I wanted to use a larger area in my Garmin map, I created the elevation data again for a larger area, but now with smaller Ids (some 2^40 for nodes, less for ways), a smaller maximum length for ways (319), and used a fresh Geofabrik extract also.
Now, all Ids stayed constant during the process (I checked the original Id in Josm for one object, and the final Id after OsmAndMapCreator process for the same object: 137,439,087,617).
The issue prevails.

But I found a new hint: lines which are shown are open, while lines which are not shown are closed. Oddly, this does not happen with building and islands consisting of circular ways.

Is there some "flag" required to treat closed ways as lines instead of e.g. areas?

**Comment by Bernhard-Hiller** [comment]
I modified the source code of Srtm2Osm such that no closed ways are produced; instead, the first node gets duplicated to become the last node.
E.g. [code]	<node id = '528822' version='1' lat='-39.229744' lon='-73.07376' />
	<node id = '528823' version='1' lat='-39.230423' lon='-73.07292' />
	<node id = '528824' version='1' lat='-39.229576' lon='-73.07361' />
	<node id = '528825' version='1' lat='-39.228745' lon='-73.07333' />
	<node id = '528826' version='1' lat='-39.2283' lon='-73.07376' />
	<node id = '528827' version='1' lat='-39.228447' lon='-73.074585' />
	<node id = '528828' version='1' lat='-39.228745' lon='-73.07479' />
	<node id = '528829' version='1' lat='-39.229576' lon='-73.074585' />
	<node id = '528830' version='1' lat='-39.229744' lon='-73.07376' />
<way id = '528831' version='1'>
	<tag k='ank_type' v='ank' />
	<tag k='rsw_type' v='rsw_min' />
	<tag k='hmz' v='525' />
	<tag k='original_id' v='137439176915'/>
	<tag k='osmand_id' v='17592214645155'/>
	<nd ref = '528822'/>
	<nd ref = '528823'/>
	<nd ref = '528824'/>
	<nd ref = '528825'/>
	<nd ref = '528826'/>
	<nd ref = '528827'/>
	<nd ref = '528828'/>
	<nd ref = '528829'/>
	<nd ref = '528830'/>
</way>[/code] (Not sure if pasting that part of the resulting file worked - Github does not like my browsers)
The final rendering was the same - the rendering engine of OsmAnd somehow recognizes those lines still as closed lines, and refuses to render the line as a line (I think that's the difference to "building": the latter one is rendered as an area),
