### ISSUE TITLE
GPX Waypoint description it's no longer opens in the new screen

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/Osmand#7616]
Version 3.4.8
OsmAnd shows part of the description it the context menu, taping on it should open the separate screen with a full description, but it doesn't work, in 3.4.1 it works.

**Comment by vshcherb** [comment]
Make sure that waypoint and favorites descriptions are consistent. Should be properly visually tested after fix

**Comment by Chumva** [comment]
Fixed with #7718
