### ISSUE TITLE
Elliptic Mercator option issue

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7617]
While using Online maps plugin and enabling the Yandex Satellite RU online tiles as a map source, saving map works in different ways, depending on Elliptic Mercator option. 
If this option is enabled, the Download map option in the Context menu saves the required part of the map. But if the option is disabled, the downloaded maps do not fit the selected coordinates. The downloaded area is shifted.

**Comment by vshcherb** [comment]
Fixed
