### ISSUE TITLE
"Can not read GPX data" when opening a GPX file out of Signal messenger Duplicate of #6598

### ISSUE THREAD

**Issue by jensMF** [osmandapp/Osmand#7624]
I would have preferred to continue in #6598 but it did get not reopened.

OsmAnd+ 3.4.8 and OsmAnd 3.4.8
in various devices from Android 6 to Android 9
i.e. Samsung Galaxy S4 Mini, Moto G5 plus, OnePlus 5T and others

We all use Offline Maps.
  
When one tries to open a gpx file from within the Signal messenger app,  the error message "Could not read GPX data" is shown and it does not get imported nor shown.

For the apps "The Mantrailing App" or "GPX Viewer", it is possible to open the GPX-files directly out of the Signal messenger app.

**Comment by jensMF** [comment]
In this open source app it works, maybe it is possible to use some of their code: https://github.com/andreynovikov/trekarta or at least find out more about the error and the solution?

**Comment by vshcherb** [comment]
@jensMF would be great if you create pull request cause it is a bit hard to understand the whole logic.

Thanks!
