### ISSUE TITLE
Analyze screen, route distance dot’s issue

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7626]
After editing the track and rotating the device, the issue occurs.

![image](https://user-images.githubusercontent.com/50198677/66033684-6f3cbe00-e510-11e9-8e3e-45b33773e3c6.png)

The device is heading to the north (in compass mode), and the elevation points are displayed along the track.

![image](https://user-images.githubusercontent.com/50198677/66033696-749a0880-e510-11e9-98a7-d603143e4eba.png)

After turning the device, the track and the points rotate separately from each other and they do not coincide.

**Comment by dmpr0** [comment]
The described issue also reproduces in Navigation > Build Route > Details > Analyze on map.
