### ISSUE TITLE
[Translation] Not enough context or missing a sample

### ISSUE THREAD

**Issue by ldmpub** [osmandapp/Osmand#7627]
Hi,

The following string "Get %1$d %2$s at %3$s off." can not be translated by several translators, see Weblate discussion here: https://hosted.weblate.org/translate/osmand/main/fr/?checksum=604815f3fd1e01f4

Thanks for your help,

**Comment by max-klaus** [comment]
There are samples:
Get 3 months at 50% off.
Get 1 month at 50% off.

**Comment by ldmpub** [comment]
Thanks! With your help translation done for french.
