### ISSUE TITLE
Route calculation issue in Munich

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7629]
The route from Marienplatz to the Angermaier clothing store for the walking navigation profile is much more complicated than in OSM. 
From: 48.13787° N, 11.57528° E
To: 48.13532° N, 11.57410° E

**Comment by MadWasp79** [comment]
This is what open street map builds (OSRM/GH both) and osmand. Our route is 537m vs osm's 590m and seems more straightforward . How it's more complicated?

![munich_osmand](https://user-images.githubusercontent.com/13146346/84376014-10742c00-abe9-11ea-8cd3-cfeecf2de3b2.jpg)

![munich_osm](https://user-images.githubusercontent.com/13146346/84376019-11a55900-abe9-11ea-8f21-e5ed4fdb8929.png)

**Comment by sonora** [comment]
Our route is superior, I think this shoulde be closed with no action.
