### ISSUE TITLE
Search: The same postcode is repeated twice

### ISSUE THREAD

**Issue by SviMik** [osmandapp/Osmand#7631]
When a postcode is found both on boundary=postal_code and addr:postcode tags, the search displays this postcode twice:

<img src="http://svimik.com/Screenshot_2019-10-03-03-08-00.png" width="270">

The first one offers only buildings having addr:postcode tag, and the second one offers all buildings within the boundary=postal_code area.

**Comment by vshcherb** [comment]
https://www.openstreetmap.org/way/729147700#map=15/59.4410/24.8802
This is postal code

**Comment by vshcherb** [comment]
By the code it shouldn't happen especially for 1 city, it is probably the problem of invisible characters.

Right now there is no duplicate cause there is no duplicate tag any more. Please comment if it comes back
