### ISSUE TITLE
Feature Request: add option to display street lighting only at night

### ISSUE THREAD

**Issue by camelCaseNick** [osmandapp/Osmand#7634]
The option to display street lighting is great for cycling at night, but if neither thinking about cycling at night nor doing it, it is to much detail on the map, hence like there is the map mode something similar would be beneficial to this way to use OsmAnd.

**Comment by xmd5a2** [comment]
@camelCaseNick please describe your use case. This is not clear what is wrong with this option. It can be turned on and off.

**Comment by camelCaseNick** [comment]
@xmd5a2, the option for displaying street lighting can be turned on and off. Yes!

The map (day/night) mode can be turned on and off, or be automatically adjusted depending on either sunrise/sunset calculations or the light sensor.

Since street lighting is much more use at night, it would be beneficial/convenient to have similar options or the options on, off and at night mode for street lighting.

Does this clarify my feature request?

**Comment by vshcherb** [comment]
Yes, it is an interesting point. It assumes if we can combine options for night / day, on the other hand we also encourage to use different profiles to customize Day / Night

**Comment by Discostu36** [comment]
I think this should be indented to show that it belongs to the option above.

![Screenshot_20200210-144043_OsmAnd~](https://user-images.githubusercontent.com/30999326/74154924-dfbcbf80-4c13-11ea-8740-ca524466664d.jpg)

**Comment by vshcherb** [comment]
The UI is going to be different and have option combined

**Comment by vshcherb** [comment]
The UI is not ready, so once it is refactored this option will be reenabled in rendering style. For some who is unpatient you can simply revert this change in a custom style https://github.com/osmandapp/OsmAnd-resources/commit/037cf6d1a8d437ab172d92a3c03034f2b4b61075

**Comment by vshcherb** [comment]
![image](https://user-images.githubusercontent.com/1042025/74169903-5bc30180-4c2c-11ea-928e-4d6e91211a3a.png)
