### ISSUE TITLE
Contour lines cannot be updated

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7635]
Both in Android and iOS OsmAndversions, the contour lines can no longer be updated: 
Italy Aosta, 
Lombardy, 
Piedmont, 
Frisul, 
Trentino Alto Adige, 
Veneto, 
Slovenia, 
France Occitania
After removing the maps and downloading them back they are displayed as updated, but after restarting OsmAnd, they are required to be updated again.

**Comment by katerynakocherhina** [comment]
- Italy Friuli
 - Venezia Giulia;
- South Tyrol

**Comment by zekooooo** [comment]
I've had the same issue with Slovenia contours since last month's update batch. Don't have the other maps. I wonder if it has something to do with the SLO contour map being dated to 6th Sept, while all other maps I have are dated to the 1st of the month, regardless of when I was notified of the update.

**Comment by sirius-c** [comment]
I do have the same issue since some weeks (and still persisting) with the contours for 'France Occitanie' and 'Slovenia' - I have many other contour maps, which don't have this problem.

It would be useful if OsmAnd would display a message as to why the update failed.

**Comment by zekooooo** [comment]
Still having this issue on OsmAnd 3.5.3

**Comment by pebogufi** [comment]
@vshcherb 
Please reopen. 4 Contour map of Italy aren't updatable. Deleted them, then new dnl, old one comes up again, shows in register for updates. This is unchanged since months.

**Comment by sirius-c** [comment]
For completeness, the contours for 'France Occitanie' and 'Slovenia' have now been updated, and for these two maps, the issue is not currently seen anymore.
