### ISSUE TITLE
Address not found

### ISSUE THREAD

**Issue by contrapunctus-1** [osmandapp/Osmand#7639]
OsmAnd v3.4.8 from F-Droid

1. Search text - "2, B-6, Vasant Vihar" (Delhi, India)

   Correct result - geo:28.567337,77.16198

   I've also tried "2/B-6 ..." and "B-6/2".

2. Search text - "421, Sector 15A, Hisar" (Haryana, India)

   Correct result - geo:29.134863,75.71857

In both cases, online search returns the correct address, but offline search does not.

Please consider documenting the offline search and/or making a search debug tool, so mappers can test their addresses and fix them if necessary.

**Comment by contrapunctus-1** [comment]
Re: #2, here's what I get when I search with the map focused over Delhi -

![Screenshot_20191008-155421](https://user-images.githubusercontent.com/8513118/66448977-11105d80-ea71-11e9-876e-daabf0ffddc6.png)

With the map focused in Hisar, though, it's slightly better - Sector 15A turns up after some irrelevant results -

![Screenshot_20191008-155746](https://user-images.githubusercontent.com/8513118/66448996-208fa680-ea71-11e9-82f1-d55a6b527373.png)

But it doesn't list '422', even after hitting 'increase search radius' a few times. It does list other houses in Sector 15A :\

**Comment by vshcherb** [comment]
1. Result finds only locality Visant-Vahar

Correct location is here http://www.openstreetmap.org/#map=17/28.566866/77.161415

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-tools/commit/4572e71b09bc87ee46ae41188e197e95c4c9249e

**Comment by vshcherb** [comment]
With new maps it will be possible to search "B-6, 2" or "2, B-6" though it will locate it to another address Ramakrishna Puram cause we don't index  locality.
2-nd issue is fixed by adding Sector to common words. So it is searchable.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/commit/63f67248593c49f0901738085b5f41d22b992f62

**Comment by vshcherb** [comment]
In order to make 1st search complete, please change Vasant Vihar to "town" / "suburb" and create a boundary.
