### ISSUE TITLE
Pausing navigation

### ISSUE THREAD

**Issue by morray** [osmandapp/OsmAnd#764]
When having an active navigation with sub-destiantions or just driving around as a tourist there should be a possibility to pause navigation, so one can walk around at a point without having the navigation going crazy because one left his route

**Comment by StyXman** [comment]
I think this a valid request again. Dismissing the route removes the destination (maybe only if there are other markers, which I have) and I have to set it again. Also, from the user's perspective, it's not evident that one can pause by dismissing. I understand that you have screen state constrains, but maybe you can squeeze a button between Dismiss and Continue.
