### ISSUE TITLE
[Feature request] Default profile: add same as previously used

### ISSUE THREAD

**Issue by goldfndr** [osmandapp/OsmAnd#7642]
I suggest [adding](https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/activities/SettingsGeneralActivity.java#L95) an option to the Default profile list of "Same as previously used" (or similar wording; "Same as" phrase is also used in the Screen orientation choices list).

UI path: menu, Settings, General settings, Default profile

Related but different request that shares my use case (there are days when I'm only driving and days when I'm only walking): #7497.

**Comment by Lotus815** [comment]
#7497

**Comment by goldfndr** [comment]
Duplicated by #10346 and resolved by associated commits.
