### ISSUE TITLE
routing in circles when on starting highway

### ISSUE THREAD

**Issue by ristein** [osmandapp/Osmand#7647]
hello,
i've found an issue with routing in Osmand~ 3.4.8 on Android 9 (with microG instead of g-play services):
it happened some times when starting navigating while driving on a highway that the **suggested route leaves the highway at the next possibility and routes back to the last ramp to go onto the same highway again**. this only happens when routing from "my position".
example picture was routing from 51.62933° N, 11.86178° E to 52.14674° N, 10.66710° E in Germany on Oct 06th, 2019, Base-Profile = Driving, Fastest route = check, no changes in default speeds.
I guess its using offline-navigation since it takes a while for calculating. but i cant find a setting for this in navigation-settings like in former versions.
(all offline maps downloaded in the area)
![Screenshot_20191006-152925](https://user-images.githubusercontent.com/55446611/66375330-6be08100-e9ad-11e9-9ef7-7fcd5a901273.jpg)

**Comment by Famlam** [comment]
Not sure if relevant to the above case, but I see this sometimes when it has to recalculate the route while moving (fast). It seems that it sometimes wants to go back to the last point of the 'old' route, even if that goes against the direction of driving towards the destination. Sometimes, like above, it indeed literally lets you drive a circle.

**Comment by vshcherb** [comment]
Not reproducible anymore
