### ISSUE TITLE
Add CyclOSM to the list of available online tiles

### ISSUE THREAD

**Issue by Phyks** [osmandapp/Osmand#7650]
Hi,

When using the "Online tiles" plugin, there is a link to "Install more", opening a window with a long list of tile providers.

Would it be possible to add CyclOSM in the list? CyclOSM is a new bicycle-oriented render which is also free-software (code is living at https://github.com/cyclosm/cyclosm-cartocss-style/). It is currently hosted by OSM-France (the French local chapter of the OSM foundation) and tiles are available from `https://dev.{a,b,c}.tile.openstreetmap.fr/cyclosm/{z}/{x}/{y}.png`.

I looked into writing a pull request for this but I could not figure out where the current list of available online tiles was defined :/

Thanks!
Best,

**Comment by vshcherb** [comment]
It is possible to do manually and we are working to spread it in different ways

**Comment by Phyks** [comment]
> It is possible to do manually

Do you mean by setting your own through the form within the app? This is really great, but is mainly for advanced / tech-savvy users who know about a "tile URL" etc.

In OSMAnd, I see a "Install more" item in which there are tons of different online maps (from Microsoft maps to Fire Hydrants and many other OSM-based maps). But I could not find the content of this list anywhere in the repo.

Thanks

**Comment by goldfndr** [comment]
https://github.com/osmandapp/osmandapp.github.io/blob/master/website/tile_sources.xml is probably the file to edit.

**Comment by Phyks** [comment]
Indeed, it seems to match! I created a PR there https://github.com/osmandapp/osmandapp.github.io/pull/158.
