### ISSUE TITLE
How to reproduce OsmAnd driving directions

### ISSUE THREAD

**Issue by HubMiner** [osmandapp/Osmand#7651]
I recently used OsmAnd for driving through countryside and at some point I get nonsensical instructions.  I would like to try to debug map in that area.  https://www.openstreetmap.org directions were perfectly reasonable between the same two points.  Can I reproduce the same directions on a computer?

**Comment by mikehgentry** [comment]
One option might be to run it on Android x86 on virtualisation software (Virtualbox or something?)

**Comment by sonora** [comment]
In OsmAnd itself, you can set up any route (set destination AND start point, then in OsmAnd's settings under Development plugin (enable it for that) chose 'Simulate my position', specify to use the rcalculated oute when asked. Is that what you need?

**Comment by vshcherb** [comment]
You can also use OsmAndMapCreator and calculate route, zooming in you will see all turns that will be announced
