### ISSUE TITLE
maxspeed:conditional: snow/wet -> false

### ISSUE THREAD

**Issue by mpele** [osmandapp/Osmand#7652]
I have faced the similar behavior like it was described in #5198 
On motorway https://www.openstreetmap.org/way/681082296#map=17/44.61339/20.64163 OsmAnd recognize max speed as 60 (instead of 130) and the routing is, as expected, not reasonable.

**Comment by mpele** [comment]
@vshcherb I think this should be treated as bug, not a "Nice to Have". 
It looks that there are two bugs:

1. The conditional speed should not be considered as temporary limitation
2. The conditional speed is accepted even the condition could not be confirmed

**Comment by scaidermern** [comment]
I can confirm. This is a regression of #5198. Values like "maxspeed:conditional=80 @ wet" aren't interpreted correctly. The condition always evaluates to true.

Example from geo:51.454063,12.213502?z=14 to geo:51.460953,12.216457?z=14
OsmAnd displays a speed limit of 100 but [way 215848071](https://www.openstreetmap.org/way/215848071) is tagged as `maxspeed=none` + `maxspeed:conditional=100 @ wet`.

![photo_2020-02-05_10-17-55](https://user-images.githubusercontent.com/1040784/73828038-e3f67080-4800-11ea-8fa6-c4b3ea19fb35.jpg)


This is not a "nice to have", this is the same bug as from #5198 again. Maybe add a unit test?

**Comment by max-klaus** [comment]
Fixed by https://github.com/osmandapp/OsmAnd-core/commit/6d83d8b71e3338f352b49f7b4f4f47ac39e07644
