### ISSUE TITLE
Improvement for "Add destination: Sort Favorites"

### ISSUE THREAD

**Issue by IgorEliezer** [osmandapp/Osmand#7654]
Two suggestions for "Add destination" > "Favorites" > "Favorites: Sort by Distance||Name":

![image](https://user-images.githubusercontent.com/4673289/66447009-18a91580-ea23-11e9-92fa-67c846c239de.png)

1. Add a `sort by folder` as a sorting option.

2. Instead of "**Favorites**; _Sort by distance_" (on the left) and "SORT BY NAME {icon}" (on the right), make it simpler, i.e. less repetitive and shorter for translations:
"**Favorites**; Sorting by: Name||Distance||Folder {icon}".

**Comment by serpico** [comment]
Related to #5468 #6925
