### ISSUE TITLE
UI overhaul, overall Look And Feel product management

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#7655]
I think it is about tine we unify our look and feel a bit across the app. The way we have it now we e.g. use different mechanisms to leave screens: Sometimes you just have to tap the device's back button to leave a screen and changes will be remembered  (e.g. Configure screen and Configure map). On others we use a Dismiss button, e.g. under Map mode. Yet on others you have to explicitly Apply or Cancel a configuration , e.g. under Map style. Under Configure maps/GPX files we use explicit Cancel or Ok. On yet other screens we have 'Leave' arrows top left, or a confirmation check mark top right.

Also, on the latter screen we use tick boxes to make tracks visible, while we mostly use sliding switches for similar functionality elsewhere.

Our screen My places / Tracks uses sliders for already visible tracks, but no visibility selection mechanism at all for not yet selected tracks. Instead you have to either tap on a track's name then chose actions on the subsequent screen, or select a track's 3 dots menu, which in turn offers all sorts  of actions but is missing the very one that gets you to the screen you would reach when tapping the track name.

All this grew historically in recent years, via different designers and developers. I suggest here we now apply some overall product managment and governance to put OsmAnd in the league of a managed product with a distinct, uniformly applied, ergonomic look and feel, and not just a collection of dozens of functionality and options screens all working slightly or even notably different.

**Comment by pietervdvn** [comment]
I'm gonna chime in here to encourage you guys. This is very much needed, but as someone who is using the nightlies as daily driver, I have to say that I am very impressed with the work you guys are doing right now. I see the UI growing and getting better every time I update. The automatic, big 'download current area' for example is a great addition.

So, go for it!

**Comment by vshcherb** [comment]
Well it will take a lot of effort to consolidate, it looks like it is easy but it is not easy at all. There are so many screens and functionality that even checking all fonts / sizes took us 2 weeks. Changing user interaction and consolidating is even more complex task.

What I can say for sure, that My Places and especially My tracks going to be refactored by another reason. We're going to enable plugins that can add new functionality to tracks etc, so we need redesign how we:
1) select items
2) search items
3) perform single action over item
4) perform batch action over items
5) provide generic statistics over group of items

I really hope to address it in 2019. Though it has at least 6 group of items: Favorites, Markers, Tracks, AV Notes, OSM Edits,  Avoid roads (?)

**Comment by sonora** [comment]
I guess we could slice the elephant before eating it ... :)

The basis would be to define a sort of standard style or style guide, it would suffice to pick one selection screen and/or one settings screen as our model. Then all developers could successively work on evolving other screens accordingly as they see fit, have time, or touch them by working on related funcionality anyway. In this fashion it does not need not be a huge dedicated activity?

**Comment by macintoshee** [comment]
As a UI-UX designer I find OSMAND navigation specifically painful, confusing and inconsistent. Lots of part behave, look and feel like designed by engineers.  Design systems are popping up everywhere and OSMAND would benefit from one considerably. You don't have to refactor whole system at once but it could be done step-by-step over longer period of time following a UI.UX roadmap.

**Comment by grravity** [comment]
+1 to this, would like to see this

**Comment by scaidermern** [comment]
> As a UI-UX designer [...]

Since you are a UI-UX designer maybe you can provide some _specific_ suggestions for UI improvements? This would be really helpful.

**Comment by NotSoImportant** [comment]
Linking an open issue about the menu structure https://github.com/osmandapp/OsmAnd/issues/10244, because I think this also falls into the same category of UX improvement.

**Comment by NotSoImportant** [comment]
menu strucuture discussion is also here: https://github.com/osmandapp/OsmAnd/issues/9047

**Comment by NotSoImportant** [comment]
regarding navigation: multiple users I brought to OsmAnd were not able to find how to stop a running navigation (click in the map, click the blue navigation arrow, click on "Dismiss", "Are you sure" -> "yes").

**Comment by NotSoImportant** [comment]
Another thing that caused confusion was that you can choose different profiles for navigation and display of the map.
So while navigation you might e.g. see a car icon in the top left of the map, but actually doing pedestrian navigation.

**Comment by NotSoImportant** [comment]
The thing that still confuses me is the difference between "configure map" and "configure screen". When I am on it I more or less understand the difference by I find myself always thinking 3 times which I need to click and maybe still end up with the wrong one.

**Comment by macintoshee** [comment]
Whole OSMND UI navigation needs restructuring. Best would be start from card sorting. Pretty low level, simple and  always reliable.

**Comment by NotSoImportant** [comment]
@macintoshee which card sorting are you referring to? Would you mind providing some simplistic mockups?

**Comment by macintoshee** [comment]
Card sorting as methodology. Research tool for building better UI. We need UI/UX research plan or  UI/UX research project. Either way I'm not up to it til late autumn or early winter. 


https://www.usability.gov/how-to-and-tools/methods/card-sorting.html

**Comment by Lee-Carre** [comment]
Usability resources:
* [The Art of Unix Usability](http://www.catb.org/esr/writings/taouu/) (sequel to [The Art of Unix Programming](http://www.catb.org/esr/writings/taoup/)).
* [N&N Usability Articles](//www.nngroup.com/articles/); a wealth of informative guides & advice.

**Comment by Lee-Carre** [comment]
> The thing that still confuses me is the difference between "configure map" and "configure screen".

This may be a case of terminology. Although I'm unlikely the imagined audience, less-ambiguous synonyms which come to mind are
* configure rendering
* configure UI

However, these terms won't be familiar to non-technical users.

I imagine your confusion stems from them *both* being different aspects of what's displayed.

**Comment by Lee-Carre** [comment]
@scaidermern

> Since you are a UI-UX designer maybe you can provide some *specific* suggestions for UI improvements? This would be really helpful.

While I understand where this comes from, it's not quite that simple, unfortunately. What makes for good usability is often (if not always) highly dependent on context & intended audience (target user-group).

Just like with technical considerations, decisions about UX often come down to trade-offs.

The only consistent advice would be principles & guidelines. How to apply them is usually different for each context, for a variety of reasons.

Compare asking for specific advice about making a killer app, or designing & implementing quality software. It depends on a whole lot of factors. There are entire sections of libraries filled with books trying to address that. Same with interaction-design (and even more so with design in the broader sense).

**Comment by Lee-Carre** [comment]
Since cross-referencing didn't happen automatically (🤷‍♂️); another scenario which would benefit from some interaction-design attention: #11846.
