### ISSUE TITLE
Unnecessary turning left-right in road without crossings using OsmandLive

### ISSUE THREAD

**Issue by cpina** [osmandapp/Osmand#7661]
I'm using OsmAnd+ 3.4.8. The issue happened all over Romania with Osmand Live enabled but below there is an example.
Romania map (full map): September
OsmandLive updated up to the same day of the issue (5th October). Note that I've been seeing this issue weeks before but never properly look, it seems a generic issue. 

In a road without intersections (also for what I could see in the editing mode in openstreetmap.org) Osmand suggested "Keep left and go ..." (staying in the same road).

See this image:

![osmand](https://user-images.githubusercontent.com/489071/66519064-36dc4780-eaef-11e9-910a-912d141ae4a5.jpg)

This was reproduced using the start and end points:
Starting point: 45.1498337,25.9894218
Destination: 45.188782,25.953548

The issue didn't happen with any router in www.openstreetmap.org

It was discussed here:
https://groups.google.com/forum/#!topic/osmand/ubJje6tAgNQ

Where other users seem to have experienced a similar problem when using Osmand Live.

Disabling OsmandLive it was working fine, enabling again it was failing again.

Note that zooming in a lot with Osmandlive I could see the "route lines" not being exactly in the same place as the route - but I didn't have any screenshot of this and I had thought that was just a user interface problem.

Please let me know if I can provide any other useful information.

Thanks very much

**Comment by vshcherb** [comment]
This bug is fixed in 3.5 and beta is already out. We are polishing 3.5 version so there are might be some glitches
