### ISSUE TITLE
Subway should be displayed as icon (not M letter)

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#7662]
Subway should be displayed as icon (not M letter)

**Comment by vshcherb** [comment]
Make sure and comment where the style is not the same i.e. context menu, map icon, poi layer

**Comment by OpenSourceForEver** [comment]
Subway stations are rendered on zoom 15 and higher diferently than 14 and lower. On zoom 14 and lower subway stations are shown with a icon of a bus and on zoom 15 and higher are shown with a icon of a train


https://user-images.githubusercontent.com/12786225/47046391-499a9580-d195-11e8-8268-51c674855897.png

https://user-images.githubusercontent.com/12786225/47046414-54552a80-d195-11e8-9041-df8c41bc5f6b.png

**Comment by vshcherb** [comment]
![image](https://user-images.githubusercontent.com/1042025/68133072-0a65f080-ff20-11e9-96e5-335d01bb9fbd.png)
![image](https://user-images.githubusercontent.com/1042025/68133083-0df97780-ff20-11e9-9e1e-7f1f3eeb276f.png)

**Comment by vshcherb** [comment]
1. Amsterdam - not right icon
2. Minsk Empty icon

**Comment by xmd5a2** [comment]
>     1. Amsterdam - not right icon

Fixed https://github.com/osmandapp/OsmAnd-resources/commit/d2f84b6bdf6b61e49ff8a5721767507ee9d061e5
