### ISSUE TITLE
Metro station name disappear in some cases

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/Osmand#7664]
After enabling "Subway routes" in Configure Map > Transport. OsmAnd starts show routes with stops, but the name of some stops overlapping with other objects.
![photo_2019-10-10 11 50 12](https://user-images.githubusercontent.com/9365308/66553609-21e5cf80-eb54-11e9-8bcf-df787b59c0ec.jpeg)
![Uploading photo_2019-10-10 11.50.11.jpeg…]()

**Comment by vshcherb** [comment]
<img width="268" alt="Intersections" src="https://user-images.githubusercontent.com/1042025/72825810-02dcfa80-3c78-11ea-8bc3-9f9f3b6e5081.png">
Problem with text priority, metro icon is under street name and on certain zooms / positions street hides the metro name. Probably metro should be on top of the streets

**Comment by vshcherb** [comment]
Should be fixed in nightlies
