### ISSUE TITLE
GPX track not cached nor saved, when battery is left to die. Tracks become lost.

### ISSUE THREAD

**Issue by anto-1** [osmandapp/Osmand#7666]

**Comment by scaidermern** [comment]
I also lost tracks upon an OsmAnd crash. Saving data from time to time would be nice.

**Comment by SviMik** [comment]
I can confirm that I cannot understand when it keeps the data and when not. My battery doesn't die, but usually on the next day the track is gone. Writing data directly to file like most loggers do would be a more straightforward approach (the file can be deleted if user decides not to keep the track).

**Comment by vshcherb** [comment]
All the data is kept in the local database, so the track would be recreated after app restart. Local database is committed every 5 min, in case the crash was fatal it is possible that database gets cleaned but it is unlikely.
Most likely, you still gets your track and they will be saved on the next day or when the button save track is clicked

**Comment by vshcherb** [comment]
I opened different issue to double check couple of scenarios https://github.com/osmandapp/Osmand/issues/7712
