### ISSUE TITLE
Roundabout preview wrong in Mauritius for left-handed traffic

### ISSUE THREAD

**Issue by kerosin** [osmandapp/Osmand#7668]
Hey,

the following occured on a left-handed traffic country (Mauritius):

![Screenshot_20191012-185043 943](https://user-images.githubusercontent.com/804836/66705068-7048c900-ed22-11e9-9486-6916923a1613.png)

The routing itself is correct, but the preview of the roundabout (upper left) is generated as it would be a right-handed country.

Route through roundabout in Mauritius (screenshot):
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=-20.02182%2C57.58291%3B-20.02060%2C57.58143

Using the following OSMAnd version:
**OsmAnd+ 3.4.8** on Android (Nokia 8 Sirocco)

Using the following offline maps:
- Germany Hamburg 01.10.2019
- Mauritius 01.10.2019
- World overview 16.07.2019
- World basemap mini 22.08.2019

The Osmand setting "traffic region" was set to automatic.

Everything else was working fine except the roundabout direction preview 😃

**Comment by xmd5a2** [comment]
Confirmed
