### ISSUE TITLE
Show polygons in Underlay map switches to enabled when starting navigation

### ISSUE THREAD

**Issue by rrooggiieerr** [osmandapp/Osmand#7670]
When I'm in non navigation mode and enable an Underlay map, for instance Microsoft Earth, and have Show polygons to off, and then start navigation Show polygons gets enabled. Show polygons should keep it's state between navigation and non-navigation mode

**Comment by vshcherb** [comment]
In a new design, all settings are profile dependent, so you need to configure it navigation mode too.
