### ISSUE TITLE
Wrong exceeded speed shown

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#7671]
I drive in Germany, so I have speed in km/h.
In example maxspeed is shown in widget (upper right corner) as 80 (km/h).
When I drive a bit too fast I get an information 
- visual in lower left corner as (50)
- vocal as 50

Is there a problem in that warning of using wrong unit
- or something else ?
Maybe related to https://github.com/osmandapp/Osmand/issues/7430 ??

Version 3.4.0#28169 of 2019-10-12
Edit: typo

**Comment by franco999** [comment]
I'm in Argentina and something similar happens to me.
![1](https://user-images.githubusercontent.com/12088580/66937914-a46c0480-f016-11e9-8e91-da6a234229af.jpg) ![2](https://user-images.githubusercontent.com/12088580/66937915-a46c0480-f016-11e9-80a5-24bd2c7792a2.jpg)

**Comment by Goran88** [comment]
Same here, today's nightly. Can also be reproduced in simulated navigation.
