### ISSUE TITLE
Add cash_withdrawal key to ATM search

### ISSUE THREAD

**Issue by amilopowers** [osmandapp/Osmand#7673]
Hello

Recently a new tag called "cash_withdrawal" has been approved.

Could you add it to searches for "ATM" and the like? I think this would be very handy for a lot of users and give OSMAnd a unique feature.

Documentation is here: https://wiki.openstreetmap.org/wiki/Key:cash_withdrawal
It is being used more than 2200 times already, mainly within Switzerland: https://taginfo.openstreetmap.org/keys/cash_withdrawal#overview

**Comment by Riksu9000** [comment]
This tag is apparently about "debit card cashback" and not intended for ATMs.
