### ISSUE TITLE
Missing turn instruction when road has a turn and you go semi-straight ahead

### ISSUE THREAD

**Issue by Famlam** [osmandapp/Osmand#7681]
OsmAnd 3.4.8, offline bicycle routing
Map of Gelderland (The Netherlands), updated Oct 1 2019
Android 8.1 on LG Q7

Navigate from Beeldhouwerstraat (where it crosses Oude Velperweg) to Plattenburgerstraat in Arnhem by bicycle ([on openstreetmap.org](https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=51.98818%2C5.93582%3B51.98783%2C5.93721#map=19/51.98798/5.93649)).

The start of your navigation is on the Beeldhouwerstraat. After a few tens of meters, the Beeldhouwerstraat continues to the right. Going left, however, will get you on the Plattenburgerweg. OsmAnd will not tell me that I have to leave the Beeldhouwerstraat and instead continue on the Plattenburgerweg, so I can only know if I have to follow the street or the direction by looking at the screen (rather than following the audio, which is silent).

![1](https://user-images.githubusercontent.com/1315520/66940376-2410c800-f045-11e9-8ada-884d99e970ae.png)
![2](https://user-images.githubusercontent.com/1315520/66940377-2410c800-f045-11e9-9a19-9f689834e14a.png)

**Comment by SviMik** [comment]
Does the map actually represents how the junction is made? Because from your screenshot I see that the right turn is quite sharp, and the other is almost straight. Why would you choose the sharp turn if there is no instructions?

I would find 'continue on the Plattenburgerweg' extremely confusing, because usually I don't know the names of the streets I'm driving through. The phrase can be as well 'look at the screen, I've failed to give you a decent voice instruction'. Maybe some different phrase would be better, like 'keep left' or something like that?

**Comment by Famlam** [comment]
Keep left (or keep left and continue on Plattenburgerweg) would indeed be perfectly fine too, and indeed more helpful than just the street name.

I actually managed to take the wrong turn there; in reality it's more like a Y turn, and as there's (fake speed bump) markings on the ground at the start of Plattenburgerweg it appears the straight route is the rightmost one.

**Comment by Famlam** [comment]
(Top down view from BAG)
![BAG](https://user-images.githubusercontent.com/1315520/67066833-73a1e180-f174-11e9-9341-576bef619626.png)

**Comment by SviMik** [comment]
That's tricky, but I think it is possible to edit this junction to give equal respect to all directions:
<img src="http://svimik.com/plattenburgerweg1.png">
This way it will be more like Y-junction rather than T-junction.

**Comment by Famlam** [comment]
I made some small modifications to make it look closer to the real situation, I'll update next month if it is fixed. https://www.openstreetmap.org/changeset/75873540
(Someone with OSMAnd Live may be able to check this earlier)

**Comment by Famlam** [comment]
Seems resolved by the edit. For the inversed route there is still no notification that you turn right onto another road, but that is another issue I guess, and less likely results into confusion
