### ISSUE TITLE
Custom Profile Issues

### ISSUE THREAD

**Issue by oxxm** [osmandapp/Osmand#7682]
With a custom profil added (Ex: BRouter) the app always defaults to this profile after startup.

The world profil is not shown as default anymore.

Another issue is, after calculating a route and swiping upwards to show route info (like distance, duration etc..), they (the info) are not updated for the custom profil after switching from default car or default pedestrian profile. The route info of the last shown profil (default car, default pedestrian) are still shown.

Osmand 3.4.8

**Comment by vshcherb** [comment]
For the first issue, it is not reproducible, please check General Settings Default profile if you didn't change to B-Router profile

**Comment by oxxm** [comment]
There was nothing preselected in the General Settings Default profile. Maybe this happens after the creation of a custom profile?

**Comment by OpenSourceForEver** [comment]
"Settings" ->"Manage app profiles"> x profile.

Dismissing changes (Osmand ask me "exit without saving?" and I tap "ok") Osmand takes this profile as base profile. Is it a bug?

**Comment by vshcherb** [comment]
Yes, we will fix it

**Comment by Chumva** [comment]
It should be fixed with b3fe91019357d9fcf7616b12fd8d46e9b3c5661f and 25bdbfc502409d5e3bad98d300d333b8ae326c7b.
