### ISSUE TITLE
Flooded: Terneuzen

### ISSUE THREAD

**Issue by Famlam** [osmandapp/Osmand#7689]
OsmAnd 3.4.8
Map of Zeeland (The Netherlands), updated Oct 1 2019, only roads
Android 8.1 on LG Q7

At zoom level 12, the city of [Terneuzen ](https://www.openstreetmap.org/search?query=terneuzen#map=12/51.3060/3.8356)is flooded.
![Screenshot_2019-10-17-20-55-14](https://user-images.githubusercontent.com/1315520/67039159-16c90b80-f121-11e9-80c1-f14b303dc518.png)

**Comment by ferdinand0101** [comment]
oh no the dam broke 

this is a data issue so there is probably an issue in the data itself so that's not an OSMAND issue
so you'll probably have to wait a month

**Comment by Famlam** [comment]
Fortunately the dam is fine on osm as well as the other zoom levels ;). Are you sure it's a data (osm) issue? Then all zoom levels should be equally affected, right?

**Comment by ferdinand0101** [comment]
no excately the data you have is a snapshot
since this is a big region it probably got fixed quickly but it was broken at the point the snapshot of the data was made
also osm has a plugin that makes it so things like that don't nessicarely appear

**Comment by xmd5a2** [comment]
Not reproducible
