### ISSUE TITLE
Roads disappear from 15 zoom level with "Hide - Overground object" option enable

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/Osmand#7697]
![photo_2019-10-18 11 00 36 (1)](https://user-images.githubusercontent.com/9365308/67076783-89280300-f196-11e9-9142-24af5bd60e22.jpeg)
![photo_2019-10-18 11 00 36](https://user-images.githubusercontent.com/9365308/67076784-89280300-f196-11e9-9aa6-0a636908c061.jpeg)

**Comment by ferdinand0101** [comment]
Isn't that the whole point of hide overground objects

**Comment by vshcherb** [comment]
No, it is not the original idea. Overground needs to be hidden for Sattellite imagery, though roads still need to be present. There is no meaningful request to display layer=-1 objects, in that case we need to follow request and display each Level separately

**Comment by xmd5a2** [comment]
This option does exactly as it is named and there was such a request to view only underground objects. It can be useful to observe underground subway stations and tunnels to entrances.

**Comment by xmd5a2** [comment]
Fixed

**Comment by ossilator** [comment]
why are roads treated differently from "lesser" ways when hiding overground objects? this is really confusing, as it makes it hard to guess what this option is really meant to do.

**Comment by vshcherb** [comment]
This is way option has more usage for many users and it's very useful with satellite imagery, second option is very specific and probably needs to have custom rendering style
