### ISSUE TITLE
Setting for route calculation: OsmAnd, Online or "bee flight" has disappeared

### ISSUE THREAD

**Issue by hvdwolf** [osmandapp/Osmand#7703]
Osmand+ 3.4.8

Observed in the mailing group.

The setting to calculate the route using "OsmAnd", "Online" or "straight line", is no longer available.
I think it disappeared when the navigation profiles were introduced.

**Comment by pebogufi** [comment]
Straight line:
create new profile with type aircraft, which has straight line as default

**Comment by hvdwolf** [comment]
That helps, but does not solve the issue for "normal" calculations for car or bike as you can no longer choose OsMand or Online.

**Comment by vshcherb** [comment]
This issue is postponed to 3.6 there are some technical difficulties to implement it. Workaround is to create ne wprofile.

**Comment by hvdwolf** [comment]
Can you please explain that workaround? As that is exactly what I tried: I created a new CAR profile to see if that initial create option would enable the "OsmAnd" or "online"option for route calculation, but I could not find it.
And modifying it later does not enable it either.

**Comment by vshcherb** [comment]
There is no online option any more, only offline version like B-Router

**Comment by hvdwolf** [comment]
It is now tagged as "Future Milestone".
If it doesn't come back, which is totally fine with me, this ticket can be closed.

**Comment by vshcherb** [comment]
So far we have ongoing discussion whether you can change or not base profiles. We definetely have B-Router, bee flight in custom profile and we're going to readd some online options though we want to make it more flexible so we can update it faster than each release. 
So it is in our roadmap to add other offfline and online routers

**Comment by vshcherb** [comment]
straight route is back to routing options with several extra features
