### ISSUE TITLE
Separate node network tagging scheme has been implemented

### ISSUE THREAD

**Issue by pelderson** [osmandapp/Osmand#7705]
This issue is to inform OsmAnd that a new tag has been implemented for all recreational node networks: network:type=node_network. It is documented on https://wiki.openstreetmap.org/wiki/Key:network:type

Node networks existed in Nederland, Belgium and Germany. They were tagged als network=rcn, rwn and a few other rYn-variants. In the new scheme, network=rYn on a route relation just means that the route is a regional route.
The new convention is: If a route is part of a node network, the tag network:type=node_network must be present in the route relation.
Nodes belonging to a node network will have an XYn_ref tag and the network:type=node_network tag, where X is the geographica scope (l, r, n or i) and Y is the transport mode (c, w, p, i, h and a few others).

Waymarkedtrails have adapted their rendering (zoom levels, line width and colour) of node networks. I imagine some adaptations of OsmAnd's rendering are in order. The specific problem at the user side is that with the current rendering, regular regional routes are obscured by all the node network routes.

**Comment by vshcherb** [comment]
Thanks for feedback

**Comment by xmd5a2** [comment]
Fixed by
https://github.com/osmandapp/OsmAnd-resources/commit/59c9e945719f9edb8c071bba9b66b5dc73c33f2d
https://github.com/osmandapp/OsmAnd-resources/commit/c100e6d64435126c4ffd6409ff491bf510156821

**Comment by pelderson** [comment]
Thnx!
