### ISSUE TITLE
Train mode (profile) 

### ISSUE THREAD

**Issue by williamdes** [osmandapp/OsmAnd#7706]
Hello, 
I have a feature request, I would like to have a way to say that I am a train and so follow train tracks. 

Currently with car mode it is always calculating new routes as the train goes forward.

**Comment by vshcherb** [comment]
It is possible to create a profile for train but there is no routing present so far. So it is needed to create ```routing.xml``` rules for train, not sure it is doable today but probably the data is there.

**Comment by dmpr0** [comment]
Done, available starting 4.5 release

**Comment by williamdes** [comment]
Thank you so much!!!!

**Comment by williamdes** [comment]
Done in  #16896
