### ISSUE TITLE
Weird public route calculation between points.

### ISSUE THREAD

**Issue by Steinhagen** [osmandapp/Osmand#7707]
What version of OsmAnd are you using, on what device and Android/iOS version?
Version: 3.4.8 (latest available)

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?
Offline

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.

__*In case of wrong routing:*__

What routing profile is chosen in OsmAnd app? (car, bike, pedestrian, fastest or shortest)
Fastest

Please specify as exactly as possible the start and end point of your route by telling us city name and street name so that we can find it via in-app address search easily. Also, a permalink from openstreetmap.org can be helpful.
City: Galați, Galați, Romania
Point 1: 45.42376 N, 28.01710 E
Point 2: 45.48427 N, 28.03256 E

Tell us your expected routing, and how OsmAnd routes, or add screenshots here.
The fastest route should either be: Walk to Casa Minion station -> take Bus 28, get off at Bariera Traian -> walk to another close station also called Bariera Traian station -> take Bus 12 to the destination.
Another good route would be: Walk to Minion -> take Bus 9/ Trolley 104 to Romtelecom - Bănci -> walk to Hotel Sofin station -> take Bus 12 to the destination

Osmand wrong calculated route: Walk to Minion -> take Bus 9 that somehow starts going into the oposite direction(???), then completely ignores the route and goes through every building until it reaches a point in the street near Centru station (that point is not the bus station!!!), then somehow it automatically changes the course in the opposite direction (this time following the road) until it passes 'Agenția de Voiaj C.F.R.) by a bit, then does a u-turn (on the same 1 way street) back to the station then continues like you are on the Bus 12 to the destination (even though you never switched busses!).

**Comment by Steinhagen** [comment]
![Screenshot_20191023-083132_OsmAnd+](https://user-images.githubusercontent.com/4029937/67360923-da0d7200-f56f-11e9-82f0-6dbeff7bd620.jpg)

**Comment by MadWasp79** [comment]
It seems like a data issue. Builds correctly with the latest version of Osmand and a fresh map. Gave me a choice of 4 different routes. 
![image](https://user-images.githubusercontent.com/13146346/72715534-50267280-3b79-11ea-82a7-23a2402d1acb.png)
