### ISSUE TITLE
[Translation] "voltage" tag name should be translated "tension" in French language 

### ISSUE THREAD

**Issue by Rpnpif** [osmandapp/Osmand#7709]
In French language, the word "voltage" is an Anglicism.
It should be translated by "tension" or, better, by "tension électrique".

**Comment by scaidermern** [comment]
You can change the translation yourself at https://hosted.weblate.org/projects/osmand/

**Comment by Rpnpif** [comment]
@scaidermern Thank you very much. It is done.
Fixed.
