### ISSUE TITLE
Lake Malawi disappears at zoom level 12 or above

### ISSUE THREAD

**Issue by fredekr** [osmandapp/Osmand#7710]
I was recently on the shore of Lake Malawi and observed that Lake Malawi would disappear at zoom levels of 12 or above. In the attached screenshots, one is at zoom level 11, the next is at zoom level 12. Where did the lake go?!

![Screenshot_20191020-170306 - zoom level 11](https://user-images.githubusercontent.com/56795542/67161554-005ac400-f35c-11e9-8ee7-059d3e115e10.png)

![Screenshot_20191020-170259 - zoom level 12](https://user-images.githubusercontent.com/56795542/67161553-ffc22d80-f35b-11e9-9df3-57f810124df5.png)

**Comment by MadWasp79** [comment]
Seems OK with the latest maps. Try to update.
![image](https://user-images.githubusercontent.com/13146346/72363400-783b4f00-36fd-11ea-8455-13022866d006.png)
