### ISSUE TITLE
National Park is absent in OsmAnd, but present in OSM

### ISSUE THREAD

**Issue by SergeyP2** [osmandapp/Osmand#7719]
OsmAnd doesn't show some nature protected areas, but shows some another. I noticed this while I was in Montenegro -- National Park Durmitor is absent in OsmAnd app, but I can see it when looking OSM web site.

OsmAnd -- No NP:
![OsmAnd 1 - No NP](https://user-images.githubusercontent.com/22505250/67285382-bbf43300-f4d7-11e9-939d-565557937ce8.jpg)
![OsmAnd 2 - No NP](https://user-images.githubusercontent.com/22505250/67285424-d4fce400-f4d7-11e9-9141-f44d42590ee8.jpg)

OSM Web -- Has NP:
![Web OSM 1](https://user-images.githubusercontent.com/22505250/67285445-ddedb580-f4d7-11e9-9cf8-3ba01379eea9.jpg)
![Web OSM 2](https://user-images.githubusercontent.com/22505250/67285458-e514c380-f4d7-11e9-8112-22f528e4eaab.jpg)

**Comment by xmd5a2** [comment]
Fixed by https://github.com/osmandapp/OsmAnd-tools/commit/172fa30b6808878a5bcc35656aa0b31df9a0e143
