### ISSUE TITLE
string misalignment in rtl scripts

### ISSUE THREAD

**Issue by iriman** [osmandapp/Osmand#7721]
For the strings that start with [this](https://hosted.weblate.org/translate/osmand/main/fa/?checksum=b52ba810de315195) word, coordinate format would be misaligned in right-to-left languages, like this example:

<div dir="rtl">
مثال: 49° 25.121' E, 34° 44.344' N
</div>

If we use the following template for the hardcoded `: coordinate` problem will be solved:

`:<SPACE><LRE><COORDINATE><PDF>`

that gives us:

<div dir="rtl">
مثال: &#x202A;49° 25.121' E, 34° 44.344' N&#x202C;
</div>

**Comment by vshcherb** [comment]
Please translate - R.string.ltr_or_rtl_combine (so you can control better join between 2 strings via ':'). Fix https://github.com/osmandapp/Osmand/commit/3fa17b599719f401bd9890b2402bae8ae1f40b12
