### ISSUE TITLE
Some settings were lost after updating

### ISSUE THREAD

**Issue by SviMik** [osmandapp/Osmand#7723]
After updating to a version with new profile system, some settings were lost.
Namely:
1. GPX logging
2. Fullscreen mode
3. Animate My Position

Probably it affected all settings that were moved to individual profiles, but I'm not certain.

What I expected:
The old settings that were global could be copied to profile settings before deleting them.

**Comment by Chumva** [comment]
After the update, those settings will be copied to browse map profile which is a default for general preferences.
