### ISSUE TITLE
A road sign gets stuck on the screen after the route dismissal

### ISSUE THREAD

**Issue by SviMik** [osmandapp/Osmand#7725]
Steps to reproduce:
1. Dismiss the route while driving
2. Park your car
3. Notice a road sign is still at the screen corner

<img src="http://svimik.com/Screenshot_2019-10-22-12-19-02.png" width="270">

**Comment by vshcherb** [comment]
The profile didn't change to Browse Map, so all these widgets are expected. You can manually change profile.
This feature works for last 3 years and it was designed to work like that. Probably your default profile now is set to CAR which leads to that issue
