### ISSUE TITLE
[Feature request] Make yes/no buttons larger and farther apart

### ISSUE THREAD

**Issue by SviMik** [osmandapp/OsmAnd#7726]
These small buttons placed close to each other are unreasonably unfriendly for the touch screen devices, especially when driving:

<img src="http://svimik.com/Screenshot_2019-10-22-20-55-12.png" width="270">

My proposal is to make a layout like this:

<img src="http://svimik.com/osmandyesno1.png" width="270">

**Comment by as4tik** [comment]
When you are driving it is critical to pay as less attention to the device as possible. So big buttons are really needed. I have not realise it before. But now I do.

**Comment by jfburke3** [comment]
I'll have to +1 this request. The button sizes and positioning have long been an annoyance to me. I've just been focused on other issues.

**Comment by dmpr0** [comment]
![Снимок экрана 2020-11-27 в 11 19 10](https://user-images.githubusercontent.com/9365308/100432517-627b1200-30a2-11eb-8004-f6dd76d84890.png)

**Comment by as4tik** [comment]
That's cool. Keep this way.

**Comment by SviMik** [comment]
I find 'Dismiss' really confusing, like dismiss the route or dismiss the message? It's like putting 'No' and 'Cancel' into the same dialogue. The old text (Yes/No) was okay, I can't think of anything better. Maybe Stop/Cancel would work too?

Also, *if* possible, the distance between buttons could be increased a little.

**Comment by mikehgentry** [comment]
Perhaps:

Stop navigation?

Stop | Resume

**Comment by sonora** [comment]
Can I suggest that that dialog is entirely obsolete and we should drop it?

If you have an ongoing navigation, it already takes 3 deliberate taps in a row to get there (e.g. tap the screen to get the nav button displayed, then tap the nav button, then tap 'Dismiss').

Why afterwards again have one more confirmation? It is always a waste of time (**any additional tap we require is a safety risk while driving!**), and the dialog is a remainder from when we still had a different UI.

And now, even if you really somehow got there by accident, we have the history function on the route dialog where you can always just re-use the last route.

I vote for removing the dialog. (@vshcherb, @dmpr0)

**Comment by travisfw** [comment]
@sonora is absolutely right, the **dialog does more harm than good**. But if the devs decide further input is somehow necessary, why not use a widget like what comes up when you finish navigation? Those buttons are large and easy to manage.

**Comment by Chumva** [comment]
This should be added here - https://github.com/osmandapp/OsmAnd/pull/10306

**Comment by sonora** [comment]
So what happened to the suggestion to simply drop the dialog?

**Comment by pebogufi** [comment]
And it would be nice, if the recording stops exactly in the moment, when any button is pressed (NOT earlier), see screenshot of @travisfw above.

**Comment by vshcherb** [comment]
suggestion to drop dialog needs to  be verified, navigation is a special mode which probably can change UX, so accidental tap could stop navigation.
Dialog doesn't appear if you didn't start navigation and simply dismiss route.
