### ISSUE TITLE
From the rendering style it is impossible to determine the presence of subway entrances

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#7729]
Issue needs to be resolved to fix https://github.com/osmandapp/Osmand/issues/7662
From OSM point of view it is possible using stop_area relation like this https://www.openstreetmap.org/relation/7664178
Each railway=station+station=subway should have an tag like "with_exits=yes/no" for internal use (no real connection to OSM tags).
We already have subway entrances data in transport map section but it is not available from rendering style.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-tools/commit/6f7d442b9a7e2651532623749c7c58864b00e03d

**Comment by vshcherb** [comment]
@xmd5a2  dont' forget to add to rendering types something like
```
<type tag="with_exits" value="yes" minzoom="13" additional="true" poi="false"/>
```

**Comment by xmd5a2** [comment]
Ok. It works
```xml
Point types [railway-station (19)] add_types [subway-yes(23), layer--2(8), color_blue(41), with_exits-yes(21), station-subway(22)] Names [name(1) - Бауманская, name:en(9) - Baumanskaya, name:be(10) - Баўманская, name:ru(3) - Бауманская, name:uk(11) - Бауманська, operator(6) - ГУП «Московский метрополитен»] id 31045933652 osmid 242546356
```
