### ISSUE TITLE
Imported GPX track line weight properties hidden / hard to find

### ISSUE THREAD

**Issue by macintoshee** [osmandapp/OsmAnd#7732]
Imported GPX track line weight properties could be hard to find if user has scrolled down to colors section. As selector "remebers" scrolling position by last selection (color) there is no indication that someting is hidden behind upper part of dropdown.  
Suggestion: split color and weight to different dropdown or make clear indication that weight properties are hidden. Preferred solution would be to have 2 settings: 
1. Line weight
2. Color

If you look here you can understand how confused I was. There is no line weight anywhere. As default is usually first in list teher is no point to scroll down.  In this case it's not true.

![Screenshot_2019-10-23-22-39-41-494_net osmand](https://user-images.githubusercontent.com/11297610/67428386-b46f7f80-f5e6-11e9-8ab1-22ec0d6b11fe.png)

After consulting with few users, someone explained to me, that he has line weight followed by colors. I naturally scrolling down revealed line weight properties. But you have to remember it from first usage, if you don, you will never find it. 

![Screenshot_2019-10-23-22-39-50-553_net osmand](https://user-images.githubusercontent.com/11297610/67428399-b9ccca00-f5e6-11e9-9833-b6898c763bfa.png)

**Comment by macintoshee** [comment]
Found another dialog/dopdown place for the same purpose  (My places > Tracks > Import > Selec track properties > Color) but bit different. Line weight properties are missing, you can choose only color. Should be consistently the same as Configure map > GPX files... > Appearance.

**Comment by dmpr0** [comment]
With the new track context menu, the track can be selected on the map. Cotext menu has an "Appearance" button.
