### ISSUE TITLE
Advertisments in Osmand+

### ISSUE THREAD

**Issue by Suncatcher** [osmandapp/Osmand#7733]
Is it normal that ads are showed in paid version? I paid not for seeing the ads, but to eliminate them.

![photo_2019-10-23_17-34-30](https://user-images.githubusercontent.com/6388034/67436035-79a42200-f5bb-11e9-9ff2-e48c9929c800.jpg)

What version of OsmAnd are you using, on what device and Android/iOS version?
**3.4.8 Android**
Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?
**Yes**
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.
**No**

**Comment by dmpr0** [comment]
Hello! You can disable them by open Menu - Settings - General settings - Don't show startup messages.
