### ISSUE TITLE
localizing MB, GB, etc

### ISSUE THREAD

**Issue by iriman** [osmandapp/Osmand#7735]
Please let us to localize other instances of MB, GB, etc.
Currently there are some of them available, but seems some other are in code.

Screenshot from download page of OsmAnd Nightly 3.4.0#25051d 24-10-2019 with Persian locale.

![20191024_125746](https://user-images.githubusercontent.com/8467903/67472514-bb2ae080-f640-11e9-92a3-a4cb8f9f28aa.jpg)
![20191024_125718](https://user-images.githubusercontent.com/8467903/67472532-c251ee80-f640-11e9-8751-98e2683d3ac4.jpg)

For some reasons I translated MB, GB, etc everywhere, but these ones remained untranslated.

**Comment by sonora** [comment]
This request surprises me to a degree: MB is not a word but an SI symbol, and as such per SI convention not to be translated in any  language or script, or am I wrong?

**Comment by iriman** [comment]
This is a workaround invented :) to overcome some problems with bidirectional texts.  On the first screenshot you can see that the string is not well displayed. In the middle part it says "_day_ 1.6" and then "MB _month year_". To solve this I decided to localize these SI units. However, unlike the way I described the issue in the first message it's not a translation (i.e. a pure Persian word) and actually I could say they are the same SI units but with Persian alphabet (and with same pronunciation). Maybe transcription is better for describing what is done. That help to make a correct order of words.

**Comment by iriman** [comment]
Also to avoid this type of localization I know two other ways:
1. Using control characters like LRM, LRE, etc in localized version. With this way, we still need to access those remaining MB, GB, ... Although future edits could be hard for someone who doesn't know about these characters.
2. Using the idea of [Breadcrumbs_(navigation)](https://en.wikipedia.org/wiki/Breadcrumb_(navigation)) to isolate ltr parts as ltr without affecting other parts of the whole string (here rtl string), or sth like this html piece of code that is equivalent to the issue of first screenshot:
```
<p dir=rtl>
  <span>نقشه استاندارد</span> • <span dir=ltr>1.6 MB</span> • <span>۸ ژوئیهٔ ۲۰۰۵</span>
</p>
```
<p dir=rtl>
<span>نقشه استاندارد</span> • <span dir=ltr>1.6 MB</span> • <span> ۸ ژوئیهٔ ۲۰۰۵ </span>
</p>

**Comment by vshcherb** [comment]
@sonora here is the problem as I see that MB are not part of string translation, so they always added to the end and it creates problems with LTR

**Comment by sonora** [comment]
@iriman Can you specify if just the placement is the issue?

**Comment by iriman** [comment]
Yes, it is the problem and caused I transcript them and this transcription was a simple workaround. If you'll choose to keep MB, GB, etc please make these `<number> <SI unit in English>` patterns left-to-right and independent of surrounding strings.

**Comment by vshcherb** [comment]
@iriman I think problem comes of joining strings in the code, we don't plan to localize it and we would like to keep it in English. 
As a solution I think to introduce "patterns" how to join lines i.e.
ltr_or_rtl_join_via_colon = "%1$s: %2$s"
ltr_or_rtl_join_via_space = "%1$s %2$s"

Here you will be able to translate them as "%2$s %1$s" and it should give enough control. Any concerns?

**Comment by iriman** [comment]
Seems this should work. I can then change order of those pairs as your suggestion or use control characters.

**Comment by iriman** [comment]
Thank you. Probably these two cases should be via_space?

https://github.com/osmandapp/Osmand/commit/74f73e2cf3f7186cf0761b29d9879ccd937a0617#diff-70ae0cbf74d886e6fb2298b2c843fdd5R237

https://github.com/osmandapp/Osmand/commit/74f73e2cf3f7186cf0761b29d9879ccd937a0617#diff-fa042b8f1c8d0277cae42e48a425e5a4R92

screenshot from nightly 3.5.6#25688d, 18-01-2020
![۲۰۲۰۰۱۱۸_۱۵۴۰۰۱](https://user-images.githubusercontent.com/8467903/72663547-1d5d6c80-3a09-11ea-9e87-a3593cd3ed2e.jpg)
