### ISSUE TITLE
[Feature request] Custom vehicle icon

### ISSUE THREAD

**Issue by SviMik** [osmandapp/Osmand#7742]
<img src="http://svimik.com/osmand_vehicle_icon.png">

Would be nice to have an option to upload a custom vehicle icon to osmand folder.
Even better, if the icon size and center point (offset) could be set too (for example, in the file name).

The idea was inspired by Garmin:
<img src="http://svimik.com/garmin_icons_4.png" width="278">

**Comment by LLlypuk82** [comment]
Присоединяюсь к предыдущему оратору :)

**Comment by vshcherb** [comment]
1 icon added already to the nightlies

**Comment by summoner001** [comment]
Couldn't you make it so that if I paste an image into a folder, it uses that image as a pointer icon?

It would be really nice if my own image could be scanned by the renderer and used.
