### ISSUE TITLE
Generate new detailed basemap

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#7756]
Fix bug with Africa coastline

**Comment by sonora** [comment]
There is currently also a flodding issue for south-east Italy on zoom level 9, most easoly reproduced if you center the map on or near the town of Gioia del Colle in Puglia.

**Comment by vshcherb** [comment]
Zoom level 9 won't belong most likely to basemap any more, so it might the issue of detailed maps

**Comment by sonora** [comment]
Have we created a backwards compatibility issue here? After updating the basemap (but my many regional maps are still older) I now seem to have gaps everywhere for zoom levels between 9 and 11, where I guess I see only the locality data, likely coming from the basemap_mini?

**Comment by vshcherb** [comment]
All maps from August have 9-11 zooms covered, so once maps are updated there is no issue with compatibility
