### ISSUE TITLE
[feature request] GPX or CSV export 

### ISSUE THREAD

**Issue by Lukilink** [osmandapp/Osmand#7757]
Would be nice to be able to export gpx or csv file of a calculated route.

**Comment by scaidermern** [comment]
GPX export is already possible. Calculate a route, open the navigation menu, open details, tap the save or share icon in the upper right corner.

**Comment by soniok** [comment]
To add to what @scaidermern , you can also use the "Move" button in details context menu on a selected recorded track. You should be able to move the GPX file to another location.

**Comment by Lukilink** [comment]
Is there any way to read the calculated route live? 
I would like to export an gpx or csv or something into an other application while using the OsmAnd app. 

Maybe the calculated rout is stored in a directory?

**Comment by pebogufi** [comment]
@Lukilink What about reading comment of scaidermern.
Why do you post a second question to that topic in #7766 ?
It is already anwered - or not ??
Is there a misunderstanding what you want ?

**Comment by Lukilink** [comment]
I want to have the route without exporting it. Kind of live. When I take an other way while navigation is running, it calculates a different rout automatically.
I am looking for a way to get a file, which updates automatically, when this happens.

**Comment by vshcherb** [comment]
Connect to #7766
