### ISSUE TITLE
Routing for bicycles on one way roads

### ISSUE THREAD

**Issue by martinhamel** [osmandapp/Osmand#7760]
The routing does not take into consideration the oneway:bicycle key when routing for bicycle. Since the osm data uses that tag everywhere, it makes the routing very unreliable for bicycle. 

An old bug was fixed on the same issue in 2013 (https://github.com/osmandapp/Osmand/pull/433).

The fix back then was to just add oneway:bicycle to routing.xml. I looked quickly and routing.xml does not seem to exists anymore. 

It must be close to GeneralRouter.java -> isOneWay(). But I stopped looking there.

**Comment by xmd5a2** [comment]
I can't reproduce that. For example on this way https://www.openstreetmap.org/way/437325050 bicycle routing correctly avoids direction of oneway:bicycle
![Screenshot_2019-10-29-09-59-30-001_net osmand plus](https://user-images.githubusercontent.com/5829014/67744558-f0fe0980-fa32-11e9-903d-46958bb398d1.png)

**Comment by Zahnstocher** [comment]
@martinhamel 
routing.xml looks good:
```
<select value="0" t="oneway:bicycle" v="no"/>
<select value="1" t="oneway:bicycle" v="yes"/>
```
https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml#L1010

**Comment by 3v1n0** [comment]
I also get directions to go in oneway roads, how can I tune my routing.xml to avoid it to get me into such roads?

**Comment by vshcherb** [comment]
You can add line
```
<select value="1" t="oneway" v="yes"/>
```
Though it will be generally incorrect I guess
