### ISSUE TITLE
Light them issue with popup message of coordinate widget

### ISSUE THREAD

**Issue by iriman** [osmandapp/Osmand#7761]
Tap on coordinate bar to pop up message at bottom. 

with **Dark theme** (white text on grey bg):

![photo_2019-10-28_01-16-07](https://user-images.githubusercontent.com/8467903/67642464-43e79c00-f921-11e9-8813-9506bef39545.jpg)

with **Light theme** (black text on grey bg):

![photo_2019-10-28_01-16-11](https://user-images.githubusercontent.com/8467903/67642465-44803280-f921-11e9-92ef-cfa92fa2d054.jpg)

**Comment by Dima-1** [comment]
Issue with dark message text in light theme  on all snackbars was fixed in the 7eed0c04e3b8719fbf5b59e081e405bd8c481092 commit. I think this issue can be closed.

**Comment by max-klaus** [comment]
@Dima-1 you are right, fixed already. Thank you!
