### ISSUE TITLE
Track screen's folder tick marks do not refllect selected gpx file status

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#7763]
How to reproduce:
1. Orgamize some of your gpx files in folders (under OsmAnd's 'tracks' folder)
2. On the My places / tracks screen, then tap the 'Show on map' button near the bottom center of the screen, this will produce selection tick marks in front of all gpx files and folders.
3. Select the tick mark in front of one of the subfoldets. This will correctly select and display all tracks contained.
4. Now leave the screen and later return to it: The tickmark of the selected folde remains empty, although all contained files are corrently selected.

 The folder tick mark must correctly dhow the display status of selected gpx tracks, preferably even indicate by perhaps gray vs. lack checkmark color if all or just some contained files are selected to be displayed.visible.

**Comment by sonora** [comment]
Also: related issue: It seems that selecting or deselecting a group of say 50 contained tracks in one subfolder in this fashion will take an extended period of time to complete in the background (possibly 30 seconds or so), but  there is no indication in the UI when this operation has finished. If you leave the dialog screen before it has finished, not all tracks have correctly changed there status, you may e.g. end up with 27 visible tracks instead of the intended 50 or zero.

**Comment by Dima-1** [comment]
Victor's comment:
1. We don't save selections on folder cause it doesn't treat "Folder as selected"
So currently it works as expected.
Do you want to automatically display tracks added to the Folder if "Folder" would be selected .

**Comment by sonora** [comment]
I suggest the question of a track being added to a selected folder later is a secondary one. I would agree we leave this as is, i.e. that selecting/deselecting the tick mark in front of a folder is not a remembered state per folder, but merely performs the action of selecting/deselecting all tracks contained in the folder **at that time**.

This is how we already have it, and what this issue refers to: The code selecting/deselectibg all tracks seems to take a long time to run, and runs invisibly in the background, so users are not aware when it is finished. And when you leave the screen before it does, the selection/deselection of tracks will only have happened partially.

The fix should investigate why it takes so long to mark the list of tracks contained in one folder as selected, we must somehow have an expensive operation in this code.

**Comment by vshcherb** [comment]
Proper fix will be probably in 3.7
