### ISSUE TITLE
Simplify app settings

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#7764]
In the effort to make as many as possible settings profile-specific, we have created a bit of a chaos where to set which setting, when it will automatically apply to all profiles, when it will apply to just one, and when(unfortunately only after setting it) youwill be asked where you want to apply it.

Also there are now redundant Settings in the drawer directly and under Configure profile. Possibly with different application scope? But this is not clear.

Is this still work in progress? I think what is urgently needed is to clean this up and make things very simple and transparent before the next release. Do we need a concept, or do we have one?

**Comment by dmpr0** [comment]
All settings will be, and most already profile depended. For 3.5 release, only in General settings for the profile, we will ask every time, if the user wants to change it for the selected profile or for all profiles.
The concept is, make each profile hold its own settings.

Drawer:
**Settings** > opens global application settings, that affected all profiles.
**Configure profile** > opens settings section for the selected profile and will apply only for the selected profile.

In a future release, we plan to make a mechanism that allows with less effort change settings for all profiles or only for few.

**Comment by sonora** [comment]
Ok, that sounds good!

But is is not clear to the user, I think. We may want to find a way to perhaps categorize the Drawer for now in
- Configure profile (we already have that headline)
- Configure App-wide settings
- Actions (or something), this would contain the remaining buttons for Directions, My places etc.?

**Comment by vshcherb** [comment]
Well it is a first release big refactoring and we still need to finish concept of "profile" specific settings that will be easy to apply to "all profiles" (or some) immediately i.e. settings of GPX recording interval. 
Obviously some settings will be global but the idea is to make each profile look like separate configurable app.

I think only next release will be possible to say that we reached the end of initial design but we are open to collect feedback as much as possible

**Comment by sonora** [comment]
Looking at our latest nightlies: I guess we should now simply remove the 'Configure map', 'Configure screen', 'Settings', and 'Plugin' entries from the drawer? All of these are now available under 'Configure profile' and there they are well presented, so this would make things a lot clearer?

**Comment by pebogufi** [comment]
Only in Settings there is a "osmand setting, Affect the entire app". Please pay attention not to lois that if you remove Settings.
![Settings](https://user-images.githubusercontent.com/18628183/67844280-c2009a00-fafd-11e9-965c-eafa7a8775ac.jpg)

**Comment by vshcherb** [comment]
No it is too early to remove, definitely not this release. Configure Map & Configure Screen are going to be joint somehow but we still need to come up with good design
