### ISSUE TITLE
[Feature request] last stop display for the public transport navigation

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7765]
When using public transport routing, it would be nice if the individual lines' (e.g. bus line) final destination would show in the route details. 
It would be useful for users who are not sure if they catch the bus in the right direction.

**Comment by OpenSourceForEver** [comment]
final destination must be included in the name of the bus route. https://wiki.openstreetmap.org/w/index.php?oldid=625726

**Comment by vshcherb** [comment]
As of today we display it in the shield (so we take name and name contains start->end). So it should work for most cases already

**Comment by vshcherb** [comment]
3 actually sounds cool
