### ISSUE TITLE
Where is the calculated route stored? 

### ISSUE THREAD

**Issue by Lukilink** [osmandapp/Osmand#7766]
Not an issue but a question.
I would like to read the calculated route as an CSV, GPX file or something, to use it in a different application. 
Is there like a path where I can finde the calculated route from osmand app?

**Comment by pebogufi** [comment]
After having calculated a route open Details. Then on top in the right corner look for download symbol. Press, the file will be in tracks folder.
Does this fit your needs ?

**Comment by Lukilink** [comment]
@pebogufi its a Different request. 

I do not want to export a gpx or csv file or something. 
I want to have the current route information without exporting it. Kind of live. When I take an different way while navigation is running, it calculates a corrected route automatically.
I am looking for a way to get a file, which updates automatically, when this happens.

**Comment by vshcherb** [comment]
Unfortunately it is not possible without programming.
