### ISSUE TITLE
The route is not re-calculated when changing the routing settings

### ISSUE THREAD

**Issue by SviMik** [osmandapp/Osmand#7773]
When the route is already calculated, and I go to the profile settings and enable or disable the "Fuel-efficient way" setting to see if maybe I get a better route, it doesn't even try to re-calculate the route.

Expected result: changing the routing settings of the current profile must trigger re-calculation of the route with new settings.

**Comment by dmpr0** [comment]
Hello! Did you use one of the base profiles or custom created?

**Comment by SviMik** [comment]
Base profile for car. And it was nightly build yesterday.
