### ISSUE TITLE
Need an option to turn off online map checks

### ISSUE THREAD

**Issue by SviMik** [osmandapp/Osmand#7783]
<img src="http://svimik.com/osmandonlinecheck1.png" width="270">

There's no option to turn off the online map checks. The reason I want to turn it off is because I've converted the map myself, the exact area I need. This message just keeps annoying, because I know better which areas I need.

[attaching external discussion for reference]

Victor Shcherb:
you need to call map exactly as on server to avoid that mesage like "estonia_europe.obf"

me:
I can't. I decided to cut Estonia into counties (the first-level administrative subdivisions of Estonia). The osmand server does not have it, it offers the whole Estonia only, so there is no counterpart on the server.

**Comment by vshcherb** [comment]
They are offline checks but indeed we need to have a solution for that.

**Comment by vshcherb** [comment]
New option added to settings
