### ISSUE TITLE
Trip recording stops after switching profile 

### ISSUE THREAD

**Issue by Chumva** [osmandapp/Osmand#7789]
If I enable recording plugin in new settings for car profile and after start recording switch to profile, which doesn't have this plugin enabled, recording stops. It continues only after enabling the plugin or switching back to the previous profile.

**Comment by sonora** [comment]
It looks like after https://github.com/osmandapp/Osmand/commit/4b702b6ea0e08a1dd534f68313c9ca2e5ef0c735 all the settings of the Recording Plugin still remain profile dependent, but that makes no sense either?

**Comment by vshcherb** [comment]
All the settings of Recording Plugin will be profile dependent. Though recording shouldn't stop because it is a global "setting" (it is not visible as a setting to user).

**Comment by sonora** [comment]
Then we should maybe make it transparent which settings count: Will always the ones of the profile you had active when you started thd recoding be used, or will they change on the fly when the profile changes later?

**Comment by vshcherb** [comment]
That's a good and tricky question cause I don't have the answer yet. I assume most of the settings will be applied on the fly, though we need to make sure that confusing settings like "Folder name" should be Global. We will have special indication for Global Settings to make it clear

**Comment by sonora** [comment]
I was talking trip recording here, in particular, since you said you did not want to make its settings global.
