### ISSUE TITLE
App gets stuck in fullscreen

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#7806]
After the recent settings refactoring, I encounter this bug with our latest nightlies: Default profile Browse map, fullscreen toggle is off for both Browse map and Dtiving base profiles.

Fresh start of the app - use the top left widget to  switch to the Driving profile - Use the same widget to switch back to Browse map.

Now all buttons/ widgets on the map screen have disappeared (as if in fullscreen mode). It is unclear how to get them back, reliably only via an app restart.

**Comment by sonora** [comment]
I still reproduce the issue with builds containing https://github.com/osmandapp/Osmand/commit/a671b3908a1f215e64f8809840f777563c233d96.

**Comment by Chumva** [comment]
I still can't reproduce it on my phone. Tapping on screen, enabling the fullscreen toggle for the selected profile or screen rotation doesn't do anything?

**Comment by sonora** [comment]
My phone is set to to screen rotation=off, OsmAnd's Default profile is set to "Browse map", and "Browse map's"screen orientation is set to "Same as device".

When I start the app, the map screen comes up ok, and all controls are present. Then I use the top-left widget **on the map screen** (not the one in the Drawer, this is important, other methods of switching the profile work ok!) to switch to "Driving". Everything is fine, Driving profile is shown ok with map controls present on the screen. Then I again change profiles back to "Browse map" using the same top-left widget **on the map screen**, the map switches back to Browse map mode, but all controls vanish...

Please let me know if you still cannot reproduce - maybe it depends on  more parameters. But it is 100% reproducible for me ever since nightlies  a few days ago.

**Comment by Chumva** [comment]
Please try to check it after this fix - https://github.com/osmandapp/Osmand/pull/7879. There was a UI bug with `do_not_use_animations` preference

**Comment by sonora** [comment]
Yes, can confirm it fixed now ! Thx!
