### ISSUE TITLE
Many Dark theme radio buttons still invisible

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#7807]
We still need to adjust the color of the selection radio buttons on many screens,  e.g. for the Configure profile / General settings' App theme, Map orientation, Screen orientation, Units of length etc. dialog screens.

(Some others already have the visible orange color, e.g. Driving region, Coordinate format).

**Comment by Chumva** [comment]
Can you please add some screenshots? And what android version do you have?

**Comment by sonora** [comment]
Vitaliy, I just checked it affects Android 4.4.x devices,  and it looks like there all selection screens which contain the Close and Apply buttons at the bottom, like e.g. Screen orientation, Units of length, Angular units, Unit of speed, etc. See here:

![Screenshot_2019-11-07-02-16-02](https://user-images.githubusercontent.com/845735/68352059-85d4c700-0105-11ea-82db-1444c0535170.png)

**Comment by max-klaus** [comment]
Fixed by https://github.com/osmandapp/Osmand/pull/7939/commits/e564603bbe12c46de91923d6396aa6734a4a7790
