### ISSUE TITLE
Glich with coastline in Northern Crimea. 

### ISSUE THREAD

**Issue by MadWasp79** [osmandapp/Osmand#7825]
![IMG_20191102_140427](https://user-images.githubusercontent.com/13146346/68070661-bde0b080-fd79-11e9-87f8-2707e37f8050.jpg)
![IMG_20191102_140423](https://user-images.githubusercontent.com/13146346/68070662-bde0b080-fd79-11e9-8034-a8bc75441774.jpg)

**Comment by xmd5a2** [comment]
Fixed
