### ISSUE TITLE
No more voice announcements without active navigation?

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#7829]
On the new profile-specific "Voice announcements" settings screen we now state "Voice announcements only happen during navigation".

So far we could also have voice announcements when just driving around in the Browse map profile, i.e. without calculated route (if your voice engine was initialized), which could be used for e.g. an acoustic warning if you were over the speed limit, or for a "POI alarm" if driving around took you in the vicinity of a displayed POI.

Is it by design we kill this functionality, or is the info text wrong?

**Comment by vshcherb** [comment]
It is by design we don't support it in non-navigation profile. So voice announcement should work only in Driving profiles.

**Comment by sonora** [comment]
Yes, but only during navigation, like our info text now says?
