### ISSUE TITLE
Grammar/spelling strings for reworked 8

### ISSUE THREAD

**Issue by comradekingu** [osmandapp/Osmand#7838]
Current untacled issues:

- [x] **[1]** **Old changelogs are comments for the strings below them**, should be commented out.
_sonora: Yes, we do a cleanup of unused strings every once in while._

-> No action for now.

- [x] **[2]** **Move strings around where they seemingly belong**? "Left-hand traffic" is not close to "Right-hand traffic" etc.
_sonora: The file as such is unstructured, the only recommendation I have published it to put new strings to the top so they can be spotted easily before releases_

-> No action .

- [x] **[3]** **Uppercase N in Notes**: I can't find anywhere that suggests this is anything but a note. Would make sense to keep calling them "OSM notes", so as to differentiate them from personal notes.
- https://wiki.openstreetmap.org/wiki/Notes
- https://github.com/osmlab/osm-note
- https://wiki.openstreetmap.org/wiki/Key:note
**Uppercase F in Favorites**, my preference is lowercase, because it ends up in translations, and it is similar to a bookmark.
_sonora: Capitalization denotes defined expressions and features and as such distinguishes from the common meaning of a term. That is how "Favorites" (the point least featured in OsmAnd) is different from "favorites", or OSM's note feature is distinguished from just your personal note-taking: In the same sense, 'Notes' is a set feature of OSM, see https://wiki.openstreetmap.org/wiki/Notes._

-> Already changed it seems. Yes, notes, favs and markers are are also generic features not specific to OSM or OsmAnd, so if you feel capitalization has no value here, I will stop arguing the case.

- [ ] **[4]** **Descriptions not/or ending with a dot**. Not consistent currently.
**Descriptions not/or ending in colon**. Not consistent currently.
_sonora: Yes, should be fixed._

-> PR welcome.

- [x] **[5}** **TTS/voice Guidance or (voice) announcement**. Need a word that works with all strings. Find all instances and decide.
_sonora: Announcement is just a lot clumsier in English than prompt, which is commonly used in most other nav systems I have cross-checked. We also do not have enough space in many dialogs for the longer expression. I think it is fine as it is now, if you find spots where you would like to make it more consistent, please suggest._

-> We will stay with prompts to refer to navigation instructions. Announcements is more general, like e.g also refers to traffic warnings.

- [x] **[6]** **point of departure, starting point** Same as above
_sonora: Please note that there are different use cases: In case of public transport, or maybe less so also a navigation, you may talk about "departure", but in case of e.g. a touring suggestion in a commercial track "start" is more appropriate. We have to clearly look at the use cases and avoid making things consistent which are not the same. :)_

-> No action, is fine as is. Departure would be awkward for some use cases, like e.g. for the trailhead of a  of a hiking trip .

- [x] **[7]** GPX tracks as files / GPX waypoints. This is not consistent, and does not work well for all strings. Example of confusion:
<string name="add_group_descr">Import groups from Favorites or GPX waypoints.</string>
_sonora: GPX files are used to store POIs/Favorites/Routes/Recorded/Tracks/Associated waypoints etc. We need to be careful, the wording to be used is case specific._

-> Let us postpone, I see no immediate improvement. We will change the way we handle GPX data in the UI, than we should revisit.

- [x] **[8]** <string name="index_name_other">Worldwide and topic maps</string> Whatdoes this mean? Hillshade is topical?
_sonora: I guess the heading is intended for all sorts of "special" maps someone could come up with, like climate change, precipitation, terrain slopes, etc._

->No action for lack of any better wording.

- [x] **[9]** <string name="public_transport_warning_title">Public transport navigation is currently in beta testing, expect errors and inaccuracies.</string>
Is it still?
_sonora: not currently sure, think yes._

->  Still no native code for PT routing. No action

- [x] **[10]** <string name="osm_editors_ranking">OSM cartographer ranking</string>
Is it called OSM editor? (currently in use)
_sonora: Have not checked recently, but from what I remember OSM calls them "editors", not "cartographers"_
Kingu: _True, but an OSM editor I would think of as software, "JOSM, or Vespucci, ID, etc." This needs to be distinguished if going with "OSM editor"._

-> I could live with contributors, I think that's what we have already.

- [ ] **[11]** <string name="consider_turning_polygons_off">It is recommended to turn off polygon rendering.</string>
What exactly is this?
_sonora: Set term used in OSM mapping, I guess._

-> I think this refers to an sub-option of Hide option in the Configure map menu. If you like, you can  check if that is meant and make a PR to specify it more precisely.

- [x] **[12 ]** <string name="distance_moving">Distance corrected</string> 
does that mean "traveled"? Some kind of GPS jitter?
_sonora: Sort of allows for GPS noise, yes. The correction I apply in this value only counts the data for which your GPS chipset reports it was recorded while your device was in motion. "Distance traveled", would not really reflect this correction well, with "Distance corrected" whoever is interested is alerted and can find what I explained in our tech articles._

-> I guess we have not found a more speaking term.

- [x] **[13]** <string name="display_zoom_level">Display zoom level: %1$s</string>?
This can mean a lot of things. Problematic.
_sonora: From what I see it is in the SRTM plugin, need to check the use case._

-> Looks like no better suggestion here, so no action.

- [x] **[14]** <string name="poi_cannot_be_found">Could not find node or waypoint.</string>
Can the word "node" be avoided?
_sonora: Node is a set expression in mapping. If this string is used in OSM edit portions of our code it must be left in place_ 
Kingu: _Could be "OSM node"? That would distinguish it from things like "Favourites"(?)_

-> Could be that map nodes are meant, so OSM nodes could be misleading. We cannot change without knowing.

- [x] **[15]** <string name="first_usage_greeting">Offline directions and discovery</string>
Cant remember why I was confused by this. What is discovery, Mapillary, Wikipedia etc.?
_sonora: I guess any method the app offers to "discover" new places. :)_

-> No action without for lack of suggestion how to improve.

- [x] **[16]** <string name="failed_to_upload">Could not upload</string>
This does not roll of the tongue.

-> No action.

- [x] **[17]** <string name="choose_audio_stream_descr">Choose loudspeaker for voice guidance
What does this mean exactly?
_sonora: A device usually has different channels for sound output, a smartphone would e.g. have one where it normally plays the phone ringtone, another one where it plays the call when you put the device to your ear, another one where it would play sound in hands-free mode.... Any better expression - please suggest._
Kingu: _Output device? Depends if it is a soft sink(?), or actual hardware output._

-> No better suggestion, no action

- [ ] **[18]** <string name="go_back_to_osmand">Go back to map</string>
Feeling there is a saving or improvement to be had or made here. "Back to map" or "Go back to the map"
Edit: "Return to map".

-> Yes, that would work for me.

- [x] **[19]** routing_attr_avoid_unpaved_name
Kontekst: avoid_unpaved
avoid_ferries
Kontekst: routing_attr_avoid_ferries_name
These two are duplicated, I think it is possible to mark up two strings in one.
_sonora: Needs a check in the code_

-> Probably. But then we mix strings we use in menu and for our routing_attr code (where wse depend on the string bane starting with routing_attr), I see no value in risking it.

- [x] **[20]** <string name="quick_action_add_first_intermediate_desc">Tapping this button centers in on the first intermediate destination.</string>
first or primary
_sonora: first_

-> No action

- [x] **[21]** <string name="remove_the_tag">REMOVE THE TAG</string>
Is this meant to be removed?
_sonora_ sounds again like OSM editors' lingo, would not touch it._

-> No action

Feel free to comment inline in italics or similar.

**Comment by sonora** [comment]
I have taken the liberty to number your points and commented some , please see above.

**Comment by comradekingu** [comment]
[22] OpenStreetMap can be written "OSM" to comply with "OSM notes", it also works as OSM.org, thereby not needing to spell out the full variant everywhere. Could also be "OSM (OpenStreetMap) if need be.

**Comment by sonora** [comment]
Thanks for the questiions and suggestions.

I have ticked off the ones where I see too little value to do the research and change. For the ones I left unchecked, I am open for a pull request.

In general, I have a feeling what you do is sift through the strings file and evaluate the existence, order, and content of strings in that file, out of context. While there is value in doing this every once in a while, in particular if you know our code or know how to research the usage of strings, this is also rather tedious. Some of the items you raise indicate you have not or not completely researched how a string is used in the app, and are then asking other people to do that research, drawing little or no response.

Maybe the better approach is to use the app systematically, and evaluate strings as they occur in context during that exercise?

**Comment by sonora** [comment]
PS: From what I see, a good number of the strings mentioned above are not in use any more in the latest UI, which supports my point about a context oriented approach.
