### ISSUE TITLE
the icon absents

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/Osmand#7845]
We have only the name of the icon. The icon absents.
![image](https://user-images.githubusercontent.com/44466116/68134880-d1377b80-ff33-11e9-86e2-07446cca3a0c.png)

**Comment by xmd5a2** [comment]
Why do we need tourism=attraction icon on the map? This tag doesn't have clearly meaning and often coexists with another tags that are rendered as icons (ruins, archaeological_site, viewpoint etc.)

**Comment by xmd5a2** [comment]
"This tag may be added to object to indicate that the place is interesting for tourists. Note that tagging just tourism=attraction is not enough - this tag should be used only as addition to main tag describing the feature. "
https://wiki.openstreetmap.org/wiki/Tag:tourism=attraction?uselang=en

**Comment by EugeneZmeuk** [comment]
I added the building (the Hut). This is a season build.

**Comment by pebogufi** [comment]
@xmd5a2 
You are right, tourism=attraction does **often** coexist with other tags but not always. There are lots of objects which are NOT perfectly created with recommended additional tags, but nevertheless they describe nice and important touristic onjects.
So, please don't remove tourism=attraction.

**Comment by xmd5a2** [comment]
@pebogufi I have no intention to remove this tag. Often it is useful even if used without main tag.
