### ISSUE TITLE
Settings issue 3.5.1

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#7849]
Based on #7813
- [x]  Configure profile / General settings / No animations / Apply to all profiles does not work
- [x]   Setting'External input device is missing the option to revert to 'None'
- [x]  Changing the Coordinate format and selecting any of the Apply confirmations does not leave the selection screen.
- [x]  On top of the Coordinate format selection screen we still state "The selected format will be applied throughout the app", but then we allow selection per profile.
- [x]  When selecting a Driving region other than "Automatic", the stati for units of length and speed on their respective settings screens do not reflect any change, not sure this is by design or a bug?
- [x] When tapping on the setting caption (text, not the toggle to its right) of any setting under Configure profile / General settings / Other (like e.g. the Kaiman filter setting), then change the setting on the subsequent dialog (which shows its description), then confirm the setting either for all or just the current profile, you are put back on the previous description dialog (instead of it being closed and you get back to the settings screen.)

**Comment by Chumva** [comment]
1 - do_not_use_animations should be made to general preference (dependent on browse map profile)
2 - it should set this option if the toggle is off

**Comment by dmpr0** [comment]
I propose to change the logic of "do_not_use_animations" settings, change UI text to "UI Animations" with On/Off state (On by default).
Also remove "Use.." word from settings like "Kalman filter", "Magnetic sensor".

**Comment by max-klaus** [comment]
"When selecting a Driving region other than "Automatic", the stati for units of length and speed on their respective settings screens do not reflect any change" - looks like fixed already

**Comment by sonora** [comment]
Is this really vlosed?

I just checked the following:

(1) Setting the Driving region to 'United States': The settings for length and speed remain showing metric (kilometers/meters, etc.)

(2) The selection dialog 'External input device' still only shows 3 entries, but does not offer the 'None' option?

(3) In addition: For the dark theme, at least on Android 4.4 devices, the radio buttons of all selection screens which contain the Close and Apply buttons at the bittom, like e.g. Screen orientation, Units of length, Angular units, Unit of speed, etc. have an invisible color schene (black on dark gray)

**Comment by sonora** [comment]
Let me re-open this so it does not get lost :)

**Comment by max-klaus** [comment]
@sonora (2) The selection dialog 'External input device' still only shows 3 entries, but does not offer the 'None' option?
Why do you need this option? You may just tun off the switch.

**Comment by Chumva** [comment]
2) It sets this option under the hood if you turn off the switch - https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/settings/GeneralProfileSettingsFragment.java#L106

**Comment by sonora** [comment]
Regarding (2) @max-klaus, @Chumva Ah, that's right! I overlooked this because for all the other settings in this 'Other' section you can always tap on their name and you have the option to turn off if they are on, but for this one it does not work because tapping the name only gives you the 3 selections and turning off only works if you directly tap on the switch. But it's ok, I guess, my oversight. Should more users encounter this we can always revisit.

That leaves (1), or do I misunderstand anything about how (1) is supposed to function?

Another question: Have not checked our code, but what does 'Show startup message' do? Seems unclear to me, maybe I have to find more speaking wording for it.

**Comment by max-klaus** [comment]
(1) fixed by https://github.com/osmandapp/Osmand/commit/600871a94391efa37656cf3c0cd84a9d92194869

Start-up message related to show/hide blue discount banner.
