### ISSUE TITLE
Changing of order for Navigation profiles

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/Osmand#7850]
It will be more useful to change an order of navigation profiles in 3.5. 
When I created my profile for a car I use Base car profile seldom.
![12](https://user-images.githubusercontent.com/44466116/68142234-237e9980-ff40-11e9-9413-9021ffbea107.jpg)

**Comment by Athoss9** [comment]
Thank you, I was about to make the same ticket. I use hiking mode more often than public transport or nautical but since it is a cutom profile it appears at the end. It would be useful to customise the order.

**Comment by vshcherb** [comment]
It works though it is not choosing navigation correctly

**Comment by lmamane** [comment]
For people getting here by search: reordering happens in settings / "Edit profile list".
