### ISSUE TITLE
Use different options set for different profile.

### ISSUE THREAD

**Issue by s8321414** [osmandapp/Osmand#7853]
When I enable something in "Configure map"→"Show" section, I will expect I can get different settings in different profiles just like other sections in "Configure map", but it seems settings in this section is shared in different profiles, could you fix this? Or this is correct behaviour?

What version of OsmAnd are you using, on what device and Android/iOS version?
3.4.8, Sony XZ1 (G8342) on Android 9
Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?
Offline maps

**Comment by dmpr0** [comment]
Hello, @s8321414!
We fixed this behavior in the current nightly and beta builds.
You can get beta here:
https://play.google.com/apps/testing/net.osmand
https://play.google.com/apps/testing/net.osmand.plus
