### ISSUE TITLE
Search show few similar street

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/Osmand#7855]
Works with November maps both on iOS and Android.
![photo_2019-11-05 10 21 39](https://user-images.githubusercontent.com/9365308/68190454-1d2b0480-ffb6-11e9-9aba-4e1d09d818ed.jpeg)
![photo_2019-11-05 10 21 43](https://user-images.githubusercontent.com/9365308/68190460-1ef4c800-ffb6-11e9-88c9-38c1d42f9d2b.jpeg)
![photo_2019-11-05 10 21 51](https://user-images.githubusercontent.com/9365308/68190474-24521280-ffb6-11e9-98de-b59a2f3a255d.jpeg)

**Comment by vshcherb** [comment]
Fixed by not indexing place=borough
