### ISSUE TITLE
Recording Layer missing from all profiles except Browse Map

### ISSUE THREAD

**Issue by jfburke3** [osmandapp/Osmand#7883]
What version of OsmAnd are you using, on what device and Android/iOS version?

OsmAnd+ Play store beta release 3.5.1, 2019-11-04

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

Offline maps

What routing profile is chosen in OsmAnd app? (car, bike, pedestrian, fastest or shortest)

All default profiles tested

Not sure which release this happened in, but at least as of a couple of Play store beta releases ago, it was working.  In the latest beta (and nightly builds), the Recording Layer setting is missing from all profiles except Browse Map.

**Comment by scaidermern** [comment]
Looks like the plugins are now profile-specific, which is rather weird for such a basic plugin.

**Comment by scaidermern** [comment]
@vshcherb How about
 * Migrating plugin settings to all profiles when upgrading from the previous version
 * Asking whether to enable/disable a plugin for all profiles whenever changing this setting

**Comment by vshcherb** [comment]
@scaidermern That's was a bug for beta users, for all users with release version it shouldn't be a case cause we migrated all settings.

**Comment by vshcherb** [comment]
We have issue with layers and with plugins, so they need to be enabled once again in new version in specific profiles

**Comment by vshcherb** [comment]
We're going to fix it by migrating though it could be buggy for people who used beta

**Comment by Chumva** [comment]
Fixed with ff7ab9bc2d12fa3e81fb9f2b678a707809b1d454.
