### ISSUE TITLE
New GPX Track every new day

### ISSUE THREAD

**Issue by mega-stoffel** [osmandapp/Osmand#7889]
Hej there,
I'm using Osmand+ in the latest version from f-droid mainly to record all my tracks I'm cycling in the city.
Even though I have not checked the option to create new tracks on new days, there's always a new track created when I ride home and continue the existing track after midnight.
Is this a misbehavior or do I need to do something else than leaving this option unchecked?
Thanks for everything! :-)

**Comment by SviMik** [comment]
Probably related to #7712

**Comment by vshcherb** [comment]
That's an option in Navigation Settings to create track for each Navigation session.

**Comment by mega-stoffel** [comment]
sorry for bothering again, but I'm afraid, my issue is not solved, yet.
I know about this option and - as I mentioned before - I have not set it, see the last attached picture. Or are you talking about a different option? Then: where could I find that?
On the first picture you can see the complete tour, which I started on Dec 23 14:39. I cycled around with several breaks and came to a party 6:35h later, at around 21:10 (see the third picture). There I stopped the recording, but kept the app open.
I went home (on the next day) at 0:48 and continued the still open track in the app. On the first picture you can see the whole track, after I stopped the recording and just before I saved it at home.
After I saved the track it created a new one, with the timestamp of Dec 24, 00:48.
The creation of that new track, i.e. ending up with two tracks for one tour, is not what I'd expect without checking the mentioned option in the last picture.
![Shot_1](https://user-images.githubusercontent.com/25298441/71427051-d7381600-26b3-11ea-98b8-8aa9e2356e2f.jpg)
![Shot_2](https://user-images.githubusercontent.com/25298441/71427052-d7381600-26b3-11ea-972a-576846a5d336.jpg)
![Shot_3](https://user-images.githubusercontent.com/25298441/71427053-d7381600-26b3-11ea-8f39-4ffb9772a992.jpg)
![Shot_4](https://user-images.githubusercontent.com/25298441/71427054-d7d0ac80-26b3-11ea-84c4-fa8bd0c1e068.jpg)

**Comment by vshcherb** [comment]
Yes, application creates separate tracks for different days.
