### ISSUE TITLE
Regression: Plugin screen is incorrectly initialized

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#7890]
Here is one moe glitch we have introduced: My default profile is Browsw map. After each start of the app, the set of plugins allegedly activated is displayed falsely: I e.g. do not have  Nautical map view, Ski map view and Parking position active. But after each start of the app they are shown as active, both on the Configure Profile and on the (redundant, I think) Menu button / Plugin screen. The display is only correct after I manually switch to the e.g. Driving profile and then change back to Browse map.

**Comment by Chumva** [comment]
Fixed with b932b629c4f0e626a3baeebda14164721e28ac37

**Comment by sonora** [comment]
Screen  `(Menu button) / Configure profile` seems fixed now, but screen `(Menu button) / Plugins` is still wrong?

Also: What was the point hiding the nautical and ski map view plugins form the first, but not the second screen?

**Comment by Chumva** [comment]
Those four market plugins enable themselves (if they are installed or app has live updates/dev build) if they were not disabled by the user. The same behaviour was before at 3.4 and earlier. 
This was applied for them after every app startup -https://github.com/osmandapp/Osmand/blob/r3.4/OsmAnd/src/net/osmand/plus/OsmandPlugin.java#L173
You can disable them in each profile. Nautical and ski plugins are partly obsolete they just add new visible profile.

**Comment by sonora** [comment]
Yeah, your' right, it seems only in dev version. Just wanted to make sure we do not have an overall bug here.

Regarding Nautical and Ski: I guess if we removed them from the `Configure Profile` screen, we should also remove them from the `Menu / Plugins` screen for consistency?

**Comment by Chumva** [comment]
I have checked it, looks ok, but It might be useful to test plugins which became profile dependent a little bit more. 

Agree with you about Nautical and Ski, but probably this will be done with removing whole menu/plugins screen in next release or vshcherb might decide to remove them now.

**Comment by Chumva** [comment]
Also, we added description dialogs which show info after plugins were installed.

**Comment by sonora** [comment]
Ok, cool! I hope Victor will agree to remove all the extra screens and Drawer entries, it would simplify our UI. I had told him elsewhere. :)

**Comment by vshcherb** [comment]
@sonora Yes, Configure Map/Screen items will be merged, Settings will be removed (accessible via Configure Profile), other screens will be put into Plugins which might be renamed to Addons or something to separate it from Plugin / Profile functionality cause Add-on might provide a plugin to an existing profile or provide new profile type itself

**Comment by sonora** [comment]
@vshcherb  Yes, I like 'Add-ons', I think it makes sense!

**Comment by vshcherb** [comment]
@sonora We just discussed and it looks we kind of going to revert concept of Plugin before 3.5. So plugin will be enabled once for the whole application! Also in Profile Settings you will see suggestions to enable certain widgets i.e. layer, widget, drawer item from plugin though you will be able to do it via other menu items as well.

**Comment by sonora** [comment]
Victor, I think that's a good idea. As I had already stated elsewhere, having that profile-specific actually caused quite some confusion ... :)

**Comment by Chumva** [comment]
@sonora I reverted fix for #7789, other fixes probably will remain.
