### ISSUE TITLE
Allow to disable en transliteration

### ISSUE THREAD

**Issue by Bernhard-Hiller** [osmandapp/OsmAnd#7891]
With the map of Thailand, I prefer the English names over Thai names because of their easy readability. OsmAnd offers additional transliteration in case that English names are not available. But with Indian alphabets, the syllable is the conceptual item of the script, and it consists of a "vocal carrier" (mostly a consonant) plus diacritic signs for the vocal / diphthong which may be above, below, left, right, or combined around the vocal carrier; with Thai, additional diacritic signs for the tone may be present. The transliteration for such alphabets is very bad, so I prefer to see the Thai version instead. 
Hence I switched the auto-transliteration feature of.
OsmAnd still uses the transliteration.

**Comment by Bernhard-Hiller** [comment]
Screenshots showing my settings, the transliterated name despite ttransliteration switched off, and the the local name, are available at Google Photos:
https://photos.app.goo.gl/CYXTKScJvUYF2H3t7
The "correct" transliteration of "สถานีรถไฟพัทลุง" should be "Sathani Roth Fai Pathalung" instead of "sthaanirthaifphathlung".

**Comment by alanorth** [comment]
I observe the same thing with Arabic names in Jordan. OsmAnd version 3.5.5. Link to [screenshots](https://imgur.com/a/7xX6CNP) showing the poor transliteration despite transliteration being turned off.

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd/pull/10906
https://github.com/osmandapp/OsmAnd-core/pull/205

**Comment by vshcherb** [comment]
- [ ] For backward compatilbility: Android UI should enable transliterate option automatically if you choose English Names
- [ ] This request should be merged after 4.0 -> merged to 3.9 cause it needs to be properly tested.
