### ISSUE TITLE
live routing ignores motor_vehicle=no

### ISSUE THREAD

**Issue by iriman** [osmandapp/Osmand#7892]
Position: https://osmand.net/go?lat=34.065&lon=49.784946&z=17
Routing mode: car

Problem with live data:
Offline map: Iran > Markazi province
Map date: October 2019 with live data

![20191110_190207](https://user-images.githubusercontent.com/8467903/68546616-2a8a2980-03d0-11ea-9d9e-3196c9835efb.jpg)

No problem with new offline map:
Offline map: Iran > Markazi province
Map date: November 2019 without live

![20191110_190714](https://user-images.githubusercontent.com/8467903/68546630-62916c80-03d0-11ea-9391-f9234dee300d.jpg)

OsmAnd~ 3.4.8 fdroid

**Comment by iriman** [comment]
In another case it's working as expected but with newer version 3.5.2:

Position: https://osmand.net/go?lat=34.1053&lon=49.679146&z=18

Offline map: Iran > Markazi province
Map date: November 2019 with live data
![20191204_142117](https://user-images.githubusercontent.com/8467903/70136603-3d68e480-1684-11ea-8c5b-8b10afe05b75.jpg)


Without live data:
![20191204_141904](https://user-images.githubusercontent.com/8467903/70136657-5376a500-1684-11ea-9052-f63affda7056.jpg)

**Comment by vshcherb** [comment]
We had an important fix in 3.5 so it is probably related
