### ISSUE TITLE
Night theme: hard to read text

### ISSUE THREAD

**Issue by Famlam** [osmandapp/Osmand#7893]
What version of OsmAnd are you using, on what device and Android/iOS version?
Android 8.1
OsmAnd 3.5.1

Measure distance -> add some points -> exit without saving
The text with the switch is hardly readable in night mode.
![Screenshot_2019-11-10-22-23-47](https://user-images.githubusercontent.com/1315520/68551259-4b23a500-040b-11ea-8487-f24443612782.png)

**Comment by vshcherb** [comment]
Fixed
