### ISSUE TITLE
german tts package not working

### ISSUE THREAD

**Issue by TheRealDarklord** [osmandapp/Osmand#7897]
A while ago the voice instructions for navigation stopped working. Last weekend I finally sat down and tried to determine what is the cause for this behaviour. It seems that just the german tts package is corrupted. At least for my 2 devices.

I switched to the english tts package and I got voice instructions as usual. Switching back to german -> nothing. I already removed the german tts package and reinstalled it, but this did'nt help. I also tried the different output channels like media, notifications or calls but that didn't help too.

What version of OsmAnd are you using, on what device and Android/iOS version?
version 3.4.8 from F-Droid Store
Xiaomi Mi 9T Pro MIUI 11 on Android Q
OnePlus 1 LineageOS 16 on Android P

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?
offline maps

**Comment by sonora** [comment]
The last change to related files happened 1 year ago ... I just tested on one of my devices and find no issue.

Can you please enable the OsmAnd development plugin, then go to its settings, use the button "Test voice prompts", and test de-tts?

**Comment by TheRealDarklord** [comment]
I enabled the dev plugin and tapped on every entry in the de-tts section. None of them got played. I went back in the menu and tested en-tts and they got played. All of them.
And as I got impatient while one instruction was played I tapped another one several times and then this one got played as many times. Funny though :)

**Comment by TheRealDarklord** [comment]
Thank you, that was a good hint. At least for my Xiaomi Mi 9T Pro. I went to the system's tts settings and removed and downloaded the german voice files again. From then on I could play the voice instructions in the OsmAnd app again.

Unforntunately this did not work on my OnePlus 1 device. I need to test further on this device, but I wanted to let you know that you pointed me in the right direction :)

**Comment by sonora** [comment]
Ok, please keep me posted here!

@vshcherb google Pllay does in deed show updata date November 11, 2019, but indicates version 3.4.8. A mistake?

**Comment by TheRealDarklord** [comment]
Well, I still can't get it to work on my OnePlus 1 device. In the system tts settings every selectable tts package works fine. I can play any of the available languages and their voices. If I switch to OsmAnd and use the dev plugin to test the installed tts packages, none of them works. Even the english tts package does not work here. As it worked on my Xiaomi device I did not try if english works on my OnePlus device as well. I assumed it does...

Here is the requested section 11.1
![osmand-dev-voiceinfo](https://user-images.githubusercontent.com/20637771/68960768-25aee680-07d1-11ea-9cc9-13f075c45b01.jpg)

**Comment by sonora** [comment]
Thanks for the debug output. It seems to show your device's engine is correctly initialized and the voice is available. I would hence suspect you have accidentally set some mute setting in OsmAnd. Can you please check https://github.com/osmandapp/Osmand/issues/7813#issuecomment-549113634 to see if this is the issue?

**Comment by TheRealDarklord** [comment]
That was the culprit! Thank you very much. It's working again. Even though I cannot remember when I disabled audio at the routing stage.

**Comment by sonora** [comment]
@vshcherb We have at least 2 separate mute settings, should combine all. From what I see, we have at least VOICE_MUTE, which is set on the route dialog screen, another one in the  navigation settings (SPEAK_ROUTING_ALARMS, I think), and maybe AIDL_MUTE_NAVIGATION is a third one?

**Comment by Chumva** [comment]
Yes, those preferences are very similar, VOICE_MUTE influences all sound, while SPEAK_ROUTING_ALARMS only voice messages. AIDL_MUTE_NAVIGATION changes only VOICE_MUTE.
