### ISSUE TITLE
[Feature request] Render cyclestreets bicycle_road

### ISSUE THREAD

**Issue by pietervdvn** [osmandapp/Osmand#7909]
In Flanders, the Netherlands and Germany, cyclestreets are becoming more and more important and frequent features within cities, with over [2.5k cyclestreets mapped worldwide[(https://taginfo.openstreetmap.org/search?q=cyclestreet%3Dyes). 

For context, a cyclestreet (in Belgium) is a street where cars are _not_ allowed to take over cyclists and where a speed limit of 30km/h is enforced. In the Netherlands, the rules aren't as strict, but they encourage to do the same.

(Note that there also is the `bicycle_road`, which does not allow cars at all).

It would be nice to have OsmAnd support those, by showing these. I've attempted onto rendering them, but I've failed... However, I'll glady update the routing profile for cyclists once they are rendered.

**Comment by xmd5a2** [comment]
https://github.com/osmandapp/OsmAnd-resources/commit/3c582c3e59b8f940288ac10e6e72fe5036d04caf

**Comment by pietervdvn** [comment]
Awesome and really cool for the quick addition! I'm looking forward to the next monthly updates :smile: :heart_eyes:
