### ISSUE TITLE
Map data for zoomlevel 9-10 completely missing from roads_only maps

### ISSUE THREAD

**Issue by hvdwolf** [osmandapp/Osmand#7917]
This is an extension of issue #6645 (Zoomlevel 13 and lower inconsistent between normal maps and roads_only maps)

Since 1-2 months map data zoomlevels 9-10 are completely missing from the roads_only maps.

See attached image where the top half is the **full map** of the Netherlands and the bottom half is the **roads-only map** of Belgium with the "big city" of Antwerpen (image reduced in size)
![roads_only_vs_full](https://user-images.githubusercontent.com/4520361/68525562-57a4e200-02d3-11ea-95a7-8bbbf9f329eb.jpg)

**Assumption:** I have the idea that roads_only maps are no longer directly generated anymore. I do think it is done via the "utilities.sh  extract-roads-only <full map>" command.
I downloaded the full Netherlands map and the roads_only Netherlands map (and then did the same for Belgium) and created a roads_only map from the full_map using the utilties script. Then I did a "diff" on the downloaded and created roads_only map. They were equal on byte level.

I spent quite some hours looking through the code and scripts and ended up in the OsmAnd-tools repository.
The routing, poi and address data is in the the roads_only map. 
I do think that the utilities script does not extract the map data in zoom level 9-10 ( Map level minZoom = 9, maxZoom = 10) from the full map.
Disabling a roads_only map in zoom level 9-10 gives the exact same map view as enabling it: You only see the world-map.
**So, there is no map data on zoom level 9-10 in the roads_only maps.**

Unfortunately I lack the skills to fix this. I simply can't find where it goes wrong.
Please fix.

See also the image for routing from full map Netherlands over roads_only map Belgium
![routingOnEmptyMap](https://user-images.githubusercontent.com/4520361/68750096-a322fd00-05ff-11ea-97e3-5c5037afb20e.jpg)

**Comment by hvdwolf** [comment]
I compiled OsmAndMapcreator to have a fresh copy and downloaded the Belgium-latest.osm.pbf from Geofabrik.

I did run an osmfilter on the data using `osmfilter --keep="highway=*" --drop-author`
From that data (and after some osmconvert steps), I created a Belgium-highway.obf.
That one does contain the roads data for zoomlevel 9-10.
See attached image, and please compare it with the first image of post 1.
![Created_roads_only_map](https://user-images.githubusercontent.com/4520361/68752580-d9fb1200-0603-11ea-9a57-4795603f94c8.jpg)

The OsmAndMapCreator app does correctly create the map and the data is correctly displayed. 
So I still think that my first assumption that the conversion from full map to roads_only map is going wrong.

**Comment by vshcherb** [comment]
Yes, it was overlooked though the problem is rather difficult cause we don't want to distirbute huge basemap.

**Comment by hvdwolf** [comment]
I do not understand what you mean with "distribute huge basemap"?
The data is missing from the roads-only maps in the zoom level 9-10. That data (plus more) is in the full map on zoom level 9-10. As I assume the same basemap data is used for the full maps as the roads-only maps, especially if the roads-only maps are created from the full map via the utilities to a roads-only map. I do not understand why it would increase the size of the basemap.

**Comment by MadWasp79** [comment]
Meaning that they are missing since we removed 9-10 zooms from the basemap to make it smaller. And overlooked the need to add those zoom levels to road-only maps. Our mistake, we will fix it until the next monthly maps update.

**Comment by vshcherb** [comment]
Fixed should be ok with new maps

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-tools/commit/9dca96ca77aed882ee5d1e59d78bc019e6eab4a5

**Comment by hvdwolf** [comment]
Are you sure?
I just compiled the latest java-tools (via repo). I downloaded two osm.pbf files from geofabrik and simply created maps. From those maps I created roads_only maps using `./utilities.sh extract-roads-only Overijssel-latest.obf`.
But still nothing at zoomlevel 9-10.

**Comment by vshcherb** [comment]
I downloaded full map and extracted road only, so now it includes roads, before that fix it was only areas included. We will double check that issue tomorrow on device though as I see the full data is present now

**Comment by hvdwolf** [comment]
I just did the same, but still have nothing on zoomlevel 9-10.
I removed the code and did again a fresh repo build and did the same again: Same result. No roads on zoomlevel 9-10.

But I also found a strange difference in the OsmAndMapCreator.zips. The nighly builds are ~70MB and mine is ~45 MB.
Mine is missing the following two files:
```
 19132112  2019-11-21 21:31   lib/libOsmAndCoreWithJNI_standalone.so
 21609354  2019-11-21 21:31   lib/libOsmAndCore_ResourcesBundle_shared.so
```
From the jenkins builder log:
```
Copy binaries linux amd64
+ cd tools/java-tools/OsmAndMapCreator/
+ cp /var/www-download/binaries/amd64-linux-gcc/libOsmAndCoreWithJNI_standalone.so lib-native/
+ cp /var/www-download/binaries/amd64-linux-gcc/libOsmAndCore_ResourcesBundle_shared.so lib-native/
+ cp /var/www-download/binaries/amd64-linux-gcc/OsmAndCore_JavaSample1.jar lib-gl/OsmAndCore_jni.jar
```
So I copied these libraries (from the nightly zip), after the repo init and sync, to the correct folders and rebuilt OsmAndMapCreator.
Now the libs are in the zip and I assume the libs are also linked into the jars (swig?)
However, still no roads at zoomlevel 9-10.

I'll see if I can find that and in the mean time I will await the new maps.

**Comment by MadWasp79** [comment]
Now it definitely fixed, double checked in map creator and on the device

**Comment by hvdwolf** [comment]
Confirmed.
Both with nightly-download and local built version.
