### ISSUE TITLE
Could not calculate route: Not clear how it could be used with native

### ISSUE THREAD

**Issue by SviMik** [osmandapp/Osmand#7923]
I'm using nightly build, and recently I started to see this error a lot:
```
Could not calculate route:
Not clear how it could be used with native
```
It appears probably half of the time when recalculation must be done.
Probably a regression because I've never seen this error in past.

<img src="http://svimik.com/Screenshot_2019-11-13-20-31-54.png" width="270">

**Comment by vshcherb** [comment]
Confirmed

**Comment by JonnyTech** [comment]
I just experienced this on v3.5.3 from F-droid when trying to calculate a pedestrian route

**Comment by MadWasp79** [comment]
@SviMik are you still experiencing those glitches? If yes, please provide us coordinates between which you weren't able to build a route.

**Comment by SviMik** [comment]
I could not reproduce this error on purpose.

**Comment by vshcherb** [comment]
No we definitely know it was connected to another bug which is in progress now. 
This one was fixed and caused another issue https://github.com/osmandapp/Osmand/issues/8164
