### ISSUE TITLE
Wrong route when street is one-way for cars, but two-way for psv

### ISSUE THREAD

**Issue by Janjko** [osmandapp/Osmand#7924]
OsmAnd 3.4.8 on Android 9, offline maps, offline public transport routing.

From: 45.81820 16.01309
To: 45.82690 15.99762

The route is good, but the red line that shows the route goes good until one road, and there it starts going in a straight line. That road is a bit strange because it is one-way for regular traffic, but it's two-way for psv traffic (busses). Here is that way:

https://www.openstreetmap.org/way/576910009

And here is the bus route:

https://www.openstreetmap.org/relation/1765727

I'm guessing OsmAnd is trying to route to the next stop, but is not taking into account the one-way:psv=no tags or something like that.

![Screenshot_20191113-220205](https://user-images.githubusercontent.com/1537131/68804442-02195e00-0662-11ea-99d8-861afd4579de.jpg)

**Comment by Janjko** [comment]
It routes throu this road fine:

https://www.openstreetmap.org/way/691608274

It has access=no and access:psv=yes

**Comment by vshcherb** [comment]
Nope, I think there is a problem with transport relation, OsmAnd doesn't route for Public transport to display roads and it uses roads which are specified in relation itself
