### ISSUE TITLE
Also respect the folder per month/day setting for the import of gpx tracks.

### ISSUE THREAD

**Issue by jensMF** [osmandapp/OsmAnd#7926]
I think it would be a great Idea to also respect the setting, where to save gpx tracks when importing them, not only when tracking them. But I think, most people who heavily use the import feature for gpx tracks, also use the tracking. So I think, leaving the setting, whether to save in monthly or daily folders could stay in the plugin settings.

**Comment by vshcherb** [comment]
Definitely it could be an option, though it is not clear whether people can't select files by name?
Also having import folder per each day might lead to many folders which is overall not good for FS performance.

Also this feature request might be overlapping with request to sort files in folder, so user can see and sort files by last modified date or by date inside GPX folder.  Overall it is hard to manage hierarchical structures than flat views

**Comment by vshcherb** [comment]
This is going to redesign as we're going to have dynamic filters instead of folders
