### ISSUE TITLE
Request: add bus station section in the PT guidelines

### ISSUE THREAD

**Issue by IgorEliezer** [osmandapp/Osmand#7927]
Not about the app, but about the PT guidelines: https://osmand.net/blog/guideline-pt

The text is excellent, but I've had some issues to get bus stations to work properly on OsmAnd. For instance, this one here (https://www.openstreetmap.org/relation/3959274) I had to edit and move tags  so many times. In one of them, OsmAnd started to use the name of a random platform as bus station name.

It would like to suggest to add a section about bus stations and [way platforms](https://www.openstreetmap.org/relation/10287048).

**Comment by Janjko** [comment]
How do you use these stop_areas in PT routing? You still put only the public_transport=platform node or way in the route relation?

**Comment by IgorEliezer** [comment]
> How do you use these stop_areas in PT routing?

[Stop_areas](https://wiki.openstreetmap.org/wiki/Tag:public_transport%3Dstop_area) are not used in PT routing, but to put together all objects that belong to a stop/station/terminal, which may include buildings, roof, bathrooms, taxi, entrances and exits, etc.

> You still put only the public_transport=platform node or way in the route relation?

I put both `public_transport=stop_position` and `public_transport=platform`.
