### ISSUE TITLE
Map objects missing

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7929]
In Somalia, there are some buildings missing from the offline vector map. Example: 6.84921,47.41408. 
In the online OsmAnd map, this data is present.
![image](https://user-images.githubusercontent.com/50198677/68842752-98379d80-06cf-11ea-8b4c-fa2f68ba01f3.png)

![image](https://user-images.githubusercontent.com/50198677/68842720-89e98180-06cf-11ea-9bcb-685b190b44b3.png)

**Comment by vshcherb** [comment]
Duplicate from Pieter

**Comment by scaidermern** [comment]
... which is here: #7910
