### ISSUE TITLE
indicate fords on the map

### ISSUE THREAD

**Issue by aceman444** [osmandapp/OsmAnd#793]
E.g. on way 293116290, OsmAnd does not display that it is a ford. Also when showing all POIs, clicking this way (the orange circle) shows some properties of it (e.g. weir and surface), but not that it is a ford, which is critical information. There is some light change of rendering on that way compared to the surrounding roads, but that is not visible very well. Is that meant to indicate a ford?

**Comment by Velomeloman** [comment]
Could you reopen this issue?

![Screenshot_20230711_170518_net.osmand.plus.jpg](https://github.com/osmandapp/OsmAnd/assets/109347561/3295c9b0-f4bc-4290-8981-31db0ba27802)

![Screenshot_20230711_170528_net.osmand.plus.jpg](https://github.com/osmandapp/OsmAnd/assets/109347561/36daf755-7f1d-4fda-9116-c568404f3a39)

![Screenshot_20230711_170512_net.osmand.plus.jpg](https://github.com/osmandapp/OsmAnd/assets/109347561/47a496bc-84e9-4bfa-8795-a3d26bb650a9)

**Comment by xmd5a2** [comment]
Fixed. Ford to test: https://www.openstreetmap.org/way/416583147
Map: Luxembourg (check after 1 hour after this post or later)
New maps required
**Legacy engine:**
![Screenshot_2023-07-25_09-59-37](https://github.com/osmandapp/OsmAnd/assets/5829014/238d2ea8-1a81-4441-8918-f0c19be1ecaf)

**OpenGL engine:**
![Screenshot_2023-07-25_09-59-47](https://github.com/osmandapp/OsmAnd/assets/5829014/12d8d455-a870-48a3-9c08-509367919066)
