### ISSUE TITLE
[Feature request] support external devices ANT+

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd#7934]
Some OsmAnd users also use external devices to get and display their heart frequency life while cycling. It may be convenient if OsmAnd had a plugin which supported this kind of devices via Bluetooth or ANT+ connection protocols.

**Comment by scottbmc** [comment]
we already discussed something similar here:
https://github.com/osmandapp/Osmand/issues/7295
There is a basic support for external devices but sadly it doenst work like expected.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/11324

**Comment by Frazco-s** [comment]
I think this is a (very) long-standing request. Osmand doesn't need much to become the ideal bike computer. A "sensors, ANT+..." plugin would be welcome. Unfortunately, I don't have the skills to build this.

**Comment by nakic** [comment]
It'd be useful to support additional built-in sensors, as well: I'd like to map surface smoothness using osmand, but can't see a way to easily merge accelerometer and GNSS data into a single GPX file (the way e.g. Garmin Virb does that by default).

**Comment by crankc** [comment]
ANT+/BLE sensor support would be highly appreciated, i currently use a dedicated sports tracking app in order to see my HR from a BLE sensor, but of course that app (or others like it) don't have tile support, overlays, customizable UI, navigation, track planning to follow.. etc etc.

**Comment by vshcherb** [comment]
Initial implementation is already merged, so it's possible to test with nightly builds

**Comment by webnetxpress** [comment]
Has this feature been released?  I would like to do the same - have OSMAND+ receive/record my Tempe sensor data in the GPX. I can't find the feature listed in any of the OSMAND settings....

**Comment by vshcherb** [comment]
It's available in nightly build will be released in 4.3

**Comment by RunningSucks** [comment]
> It's available in nightly build will be released in 4.3

I see the plugin in the nightly build, but does it support only ANT+ sensors or Bluetooth as well?

**Comment by RunningSucks** [comment]
> Only ANT+ so far

Thanks! Do you know if there are any plans for bluetooth sensors? (I know that this issue is about ANT+, but other bluetooth issues, e.g #8769 was merged into this one)
