### ISSUE TITLE
The new gpx naming option contains the directories names when monthly or daily directories are activated

### ISSUE THREAD

**Issue by jensMF** [osmandapp/Osmand#7936]
Version: 3.5 nightly (18.11.2019)
The new renaming field popping up when saving a gpx track contains the directory names of monthly/daily folder and does not allow renaming because of illegal characters.
![Screenshot_OsmAnd_Nightly_20191119-014350](https://user-images.githubusercontent.com/1620034/69107027-69734b80-0a70-11ea-83c0-7f9e5620e002.png)

**Comment by jensMF** [comment]
OsmAnd+ 3.5.3 is released with this error, but luckily there is a fix. Some more pictures of this:
![Screenshot_OsmAnd+_20191121-133737](https://user-images.githubusercontent.com/1620034/69338829-490be280-0c64-11ea-8e74-6af8a1747b78.png)
This is the problem.
![Screenshot_OsmAnd+_20191121-133749](https://user-images.githubusercontent.com/1620034/69338847-50cb8700-0c64-11ea-9d2e-375906579bec.png)
Here you can see, that, if I remove the '/' the error message disappears ...
![Screenshot_OsmAnd+_20191121-133831](https://user-images.githubusercontent.com/1620034/69338870-5923c200-0c64-11ea-9bf5-9f01f7c8266c.png)
... and here you can see, that the Track is saved in the daily directory under the chosen name.
Fix is in PR #7937

**Comment by vshcherb** [comment]
As I know folder name wasn't displayed on purpose in this dialog, so in case we show it for editing, obviously we should support renaming folder as well. Though obviously it might break some UX-observations, cause in this place there are 2 new features met that are not designed together. So, probably, we need to pull feature from 3.5 and put in nightly builds, so we have enough time to review daily/monthly directories. Sorry for late reply, this is quite confusing for now.
