### ISSUE TITLE
OsmAndMapcreator.zip contains hidden path. Windows zip doesn't recognise that

### ISSUE THREAD

**Issue by hvdwolf** [osmandapp/Osmand#7938]
I just created an issue in OsmAnd-tools, but looking at the dates I do not think these issues are taken care off.

So I'm sorry for cross-posting, but I will post it here and I will close issue [336](https://github.com/osmandapp/OsmAnd-tools/issues/336) in OsmAnd-tools.

The created (nightly) OsmAndMapCreator-`<something>`.zip contains below mentioned path.
```
        0  2019-11-12 18:45   ./
  2947510  2019-11-12 18:45   ./OsmAndMapCreator.jar
```

The default zip tools on Windows do not recognise that. It means the OsmAndMapCreator.jar is not unzipped, resulting in errors because not one single .bat will start.
Using 7zip does unzip OsmAndMapCreator.jar and puts it in the main OsmAndMapCreator folder.

The repo/gradle build script should add it without preceding dot.
`  2947510  2019-11-12 18:45   OsmAndMapCreator.jar`

**Comment by scaidermern** [comment]
This is the same bug as #7420. Unfortunately #7420 got closed although the issue hasn't been fixed.

Note that this is not a Windows-only bug. Gnome's Archive Manager file-roller also doesn't list this file (but is able to extract it anyway).

**Comment by vshcherb** [comment]
Try latest https://github.com/osmandapp/OsmAnd-tools/commit/a889ab21f827019cb63245ea1348139798394787

**Comment by hvdwolf** [comment]
Confirmed. Is OK now. thanks
