### ISSUE TITLE
Fernando de Noronha island not included in Brazil map

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/Osmand#7942]
https://www.openstreetmap.org/relation/303650#map=9/-3.6532/-32.1075
![photo_2019-11-18 14 10 24](https://user-images.githubusercontent.com/9365308/69051510-3e0b4500-0a0d-11ea-9d73-fec01ffd1f76.jpeg)

**Comment by xmd5a2** [comment]
Fixed. Poly osm-extract/south-america.poly on server was out of date
