### ISSUE TITLE
[Feature request] Add islands names to the map

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7949]
In the Azores, there are many islands, which are not named on any map zoom level (37.7628, -25.5597). It would be convenient for the users to see not only the city names but also the names of the islands

**Comment by xmd5a2** [comment]
Which islands do not have names? I see names on all major Azores islands 
![Screenshot from 2019-11-26 11-11-56](https://user-images.githubusercontent.com/5829014/69610944-dcb32980-103d-11ea-9f83-640cb4962af0.png)
![Screenshot from 2019-11-26 11-11-43](https://user-images.githubusercontent.com/5829014/69610947-dd4bc000-103d-11ea-92be-cc385ed6983a.png)
![Screenshot from 2019-11-26 11-11-36](https://user-images.githubusercontent.com/5829014/69610948-dd4bc000-103d-11ea-9282-108336329bc3.png)
