### ISSUE TITLE
NPE when setting min/max speed options

### ISSUE THREAD

**Issue by slarti-zak** [osmandapp/Osmand#7955]
I get a NPE crash after updating to 3.5.3 and trying to change the standard speed options (regardless of the profile). I have attached the logfile:

[exception.log](https://github.com/osmandapp/Osmand/files/3865140/exception.log)

This happened on an LG G6 device with android 7.

**Comment by Chumva** [comment]
Fixed with defff46e4cd6d14a5209af17db74f4137e93dbbb
