### ISSUE TITLE
Trip recording notification reappears with Stop/Pause options after Stop

### ISSUE THREAD

**Issue by azrdev** [osmandapp/Osmand#7961]
The "Trip recording" notification displayed (on the lockscreen) while recording a GPX track offers two options: "Stop" and "Pause". After pressing "Stop" it vanishes, however it instantly re-appears in the previous state showing "Stop" and "Pause", whereas I'd expect it to disappear and not come back until I start GPX recording anew (from the app).

OsmAnd~ 3.4.8 from f-droid
Android 9 from https://lineage.microg.org/

If you need more information, please tell me what to provide.

**Comment by jensMF** [comment]
For me it shows "Record" and I really like this behavior and regularly make use of it it.

**Comment by sonora** [comment]
I think I may have fixed this a few weeks ago, had not known this issue, though. Could anybody check if this is still an issue?
