### ISSUE TITLE
Scale bar text missing

### ISSUE THREAD

**Issue by tinus-github** [osmandapp/Osmand#7963]
On iOS 13.2.2 on an iPhone XR, using OsmAND 3.0.0.

On the bottom of the screen there is a scale bar. This used to have numbers showing the scale. These numbers have disappeared, only the bar remains.

This has been this way for quite some time; rebooting the app or phone does not help.

![DE15A7F0-5A79-4FF8-BFF9-B50885B931CF](https://user-images.githubusercontent.com/215730/69285299-d281cd00-0bf0-11ea-95e6-c4c99bdcac24.jpeg)

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-ios/issues/495
