### ISSUE TITLE
Unit of speed setting issue (Settings template)

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7968]
Changing the "Unit of speed" option for the "Pedestrian" profile from "Minutes per kilometer" to "Kilometers per hour - Apply - Apply to all profiles” does not affect the settings. If choosing "Apply to the current Pedestrian profile" it will only succeed for this profile.

**Comment by Chumva** [comment]
There is a problem with the profile default value for speed_system preference - https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/OsmandSettings.java#L1343 because it overrides the base method and does not use general values from browse map mode.

**Comment by vshcherb** [comment]
This issue will be solved when we properly introduce templates instead of "Shared settings"

**Comment by vshcherb** [comment]
Fixed
