### ISSUE TITLE
2 popups suggesting to download a region map

### ISSUE THREAD

**Issue by aceman444** [osmandapp/Osmand#7971]
On the world map when you tap a spot in a country that you haven't yet downloaded you get a suggestion which map (country/region) you can download to get this area. In OsmAnd 3.5 there was a new suggestion popup added that comes from the top of the screen. However, there is still the dialog coming from the bottom, that has basically the same content. Visually the new popup is uglier than the old one (like totally alien icon), but anyway having 2 popups makes no sense when they have the same content. They do not appear simultaneously, but tapping any area makes one of them appear, seemingly randomly.

**Comment by vshcherb** [comment]
From which bottom? can you share the screenshot please

**Comment by aceman444** [comment]
When you click a blank space on the world map, you get a dialog from the top. If you click a city on the world map, you get a dialog from the bottom. They both offer to download the same region map.

The bottom one looks more in the style of the rest of OsmAnd. Can you preserve that one, or fix the new one (from top) to look as the bottom one?

**Comment by pebogufi** [comment]
In both cases the Download option is not allways the best one. If I have the map deactivated in backup folder, the suggestion should be Activate instead of Download (which works often in case of the described bottom message).

**Comment by pebogufi** [comment]
@vshcherb here is bottom dialog
![bottom dnl dialog](https://user-images.githubusercontent.com/18628183/69713326-40039100-10fc-11ea-8c52-aee67c794f02.jpg)

**Comment by vshcherb** [comment]
The top suggestion could be disabled in General Settings. Also top one is not 100% accurate cause it tracks whole screen to detect area to download

**Comment by aceman444** [comment]
The top one was added in OsmAnd 3.5. So what is it good for if it just duplicates the bottom one with less presicion?
