### ISSUE TITLE
Error (Android): Import of profiles (3.5.3)

### ISSUE THREAD

**Issue by BY-GitHub** [osmandapp/Osmand#7975]
Does anyone have experience with the import of profiles (3.5.3)?
Exporting a profile to App "FX" creates the file share.data. I have to rename this file to share.osf (the way OsmAnd is assigned to this file type). If you now want to open this file with OsmAnd, the following error message appears:

"Error
_The selected app does not support opening this item using a "Content URI". As of late 2018 Google has required apps to only use Content URIs for opening files. You may need to update the target application or contact its developer._"

**Comment by max-klaus** [comment]
Looks like FX's issue. How do you try to open .osf?

**Comment by BY-GitHub** [comment]
As I wrote: I selected the file (share.osf) and tried to open it with the now released OsmAnd-Icon.
