### ISSUE TITLE
No Microsoft-Earth with Osmand 3.5.3 and Lineage 16 (Pie)

### ISSUE THREAD

**Issue by Spielmops** [osmandapp/Osmand#7976]
My devices: 
Samsung Tab S2, Huawei Mediapad T2, Wileyfox Swift - all of them with LineageOS 16.0 (Pie)
Cubot Max, Samsung Galaxy J3 with LineageOS 14.1 (Nougat)

Version of Osmand: 3.5.3, downloaded from Fdroid

On all of those devices Osmand runs fine. All use my home-net via wifi and I have a fiber-connection to home. All those devices are setup similar, the Blokada-app is active.

Issue: if I change the map-source from vector-map to Microsoft-Earth, the Earth-map is instantly shown on the devices with LineageOS 14 but not on those with Lineage 16. If I set the source to online-tiles, the regarding maps are shown on all devices. I made shure, that no cache-files are involved by selecting small areas, which where never shown by Osmand and by deleting downloaded tiles. 

I have a transfer-speed-display within the status-line of all devices and thus can see, that in case the Microsoft-Earth-source is selected, not one byte is coming in on Pie-devices. If I chose online-tiles the display shows the regarding traffic. Blokada shows no blocking (I even tried all that with Blokada deactivated with no difference).

Addition: on the Samsung Tab S2 the Lineage-Pie-version has been installed since spring this year and I could use the Microsoft-source with the previous-version of Osmand (3.4.5and 3.4.2 ?) a lot (two week-long journeys).

**Comment by Spielmops** [comment]
Further exploration:On the Huawei-Mediapadwith LinageOS 16:  I made a backup of Osmands datas, renamed the files-folder and installed Osmand 3.4.8, restored the datas, rerenamed the files-folder and startet Osmand.

I could again see the Microsoft-Earth-maps! So the Issue has to do with the 3.5-version of Osmand ...

Spielmops

**Comment by pebogufi** [comment]
I had the same problem.
Solution:
renaming folder files/Mircosoft Earth to xxx.
then restart app,  access to mic earth, 
then moving contens of renamed folder xxx to new created folder Mircosoft Earth.
That was it. 
Version 3.5.0#28457

**Comment by Spielmops** [comment]
Sorry, but that does not work. I deleted the folder Microsoft Earth and installed this source anew. Nothing!

Spielmops

**Comment by max-klaus** [comment]
The issue is related to OsmAnd 3.5 and Android 9+ devices. Sorry for that. 
It fixed already and will work ok in the next release (next week I think)
