### ISSUE TITLE
[Translation / Android only ?] "Action strings" used instead of "Status strings"

### ISSUE THREAD

**Issue by ldmpub** [osmandapp/Osmand#7977]
Hi,

In screen "routing preferences" the description behind each option is wrong ... the strings should be "a status" and not "an action verb".

Please see screen shot attached (sorry it's in french, "Activer / Désactiver" is similar to "Activate/Desactive" which is wrong => "Enabled/Disabled" should be displayed instead).
![OsmAnd](https://user-images.githubusercontent.com/1452146/69494697-fa0db980-0ebe-11ea-9a58-7e6ce0c24a1b.jpg)

I had a short look to the source code but I'm not a developper and can not tell where "called strings" should be changed.

For info here are the strings which should not be used in this place :
https://hosted.weblate.org/translate/osmand/main/fr/?checksum=d2d6e5cd1a823f39
https://hosted.weblate.org/translate/osmand/main/fr/?checksum=2d435ec5f5f05561
https://hosted.weblate.org/translate/osmand/main/fr/?checksum=f6c67e8c65b92607
https://hosted.weblate.org/translate/osmand/main/fr/?checksum=68b51a10a7007b0b

Note: I'm the main translator of the Android App for french and can confirm it's not a translation error but rather a "wrong string usage in the app" which may lead to the same confusing screen in all languages.

**Comment by Spielmops** [comment]
Addition for the German version: 
"Schummerungsebene" instead of "Reliefanzeige" ...

Aua!

Spielmops

**Comment by pebogufi** [comment]
> Addition for the German version:
> new "Schummerungsebene" instead of old: "Reliefanzeige" ...
> ...

Please revert that, it is horrible.
"Reliefanzeige" was quite a good term.

**Comment by ldmpub** [comment]
@pebogufi @Spielmops please be constructive: don't give german samples no one can understand and try to suggest clearly what impovment should be done now and why (instead of just telling something like "it was better before").

Thanks,

**Comment by pebogufi** [comment]
Sorry.
Please return to "Reliefanzeige" in Configure Map for english term "hillshade layer".

**Comment by Spielmops** [comment]
Is there any URL where we can talk about translation issues?

Spielmops

**Comment by vshcherb** [comment]
On weblate it is possible to put notes to translation, probably it is a better place

**Comment by ldmpub** [comment]
@vshcherb , can you please reopen this issue?

The problem can not be solved in weblate but rather by using correct existing weblate strings in the app because the strings we are talking about are "shared" strings already OK in weblate.

In other words: in weblate good strings are already available and current request is to use "status" strings in this context ... and I don't think neither dev nor translator needs to create and use new strings because everything is already there in weblate.

**Comment by Spielmops** [comment]
So, its not possible to change anything?
