### ISSUE TITLE
width tag is not considered in routing of ver 3.5 even issue #7555 is closed

### ISSUE THREAD

**Issue by TomSH75** [osmandapp/Osmand#7978]
@MadWasp79 

Hello, I just opened pull request 598 in OsmAnd-resources [(routing.xml).](https://github.com/osmandapp/OsmAnd-resources/pull/598) However the routing without routing.xml as well does not consider the width tag (should be solved in Version 3.5 with issue #7555). Example is a route from 43.55477° N, 6.16697°W to 43.56010°N, 6.18916° W. Road 202318433 has a width of 2.2m only.

Could you please have a look at it? Best regards, Tom

wrong routing
![wrong routing](https://user-images.githubusercontent.com/55321799/69495364-8ec7e580-0ec6-11ea-8cf9-0a9ac5a8b188.jpeg)

settings done
![settings done](https://user-images.githubusercontent.com/55321799/69495372-a56e3c80-0ec6-11ea-95d5-0f56e58b323d.jpeg)

expected routing (done with adapted routing.xml - pull request 598 in OsmAnd-resources [(routing.xml).](https://github.com/osmandapp/OsmAnd-resources/pull/598)
![expected routing, done with adapted routing_xml](https://user-images.githubusercontent.com/55321799/69495387-cd5da000-0ec6-11ea-8200-b0fcf9c03503.jpeg)

**Comment by vshcherb** [comment]
I think we merged already
