### ISSUE TITLE
Coordinates widget omits coordinates accuracy, inconsistent with elsewhere in the App

### ISSUE THREAD

**Issue by AnotherElk** [osmandapp/Osmand#7979]
What version of OsmAnd are you using, on what device and Android/iOS version?

**OsmAnd+ 3.5.3** on devices Fairphone 2 running LineageOS 16.0 (Android 9.0) and Fairphone 3 running Android 9.0.

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

Offline maps, but not important for the issue ...

**Issue:**

Example ... Settings - Browse map - General settings - Coordinate format is set to "DDD MM.MMM".
If I point to some place in the map, the respective info for the place displays the coordinates in the DDD MM.MMM format, as expected.
The Coordinates widget, however, displays the coordinates in the DDD MM.MM format, there's one decimal place missing compared to the set format and to the format used elsewhere in the App.

Another expample ... If the format is set to DDD MM SS.S and displayed in place info as such, the Coordinate widget displays DD MM SS instead, again omitting a decimal place.

If this is an available space/ font size issue, could the font size used in the widget be made smaller to prioritise info consistency and (before perhaps following this logic decimal places elsewhere in the App would get cut) more accuracy here?

It seems the widget font size matches the font size in the panels (GPS info, Current time, etc.), so I can kind of understand the design choice, but the widget lacks practical benefit when every other GPS or navigation tool you work with uses e.g. DDD MM.MMM and the widget could fit in nicely into your workflow or use case, but just omits one decimal place, so you rather can't use it.
If matching the panel font size is important, perhaps the panel/widget font size could be made selectable to be smaller in the settings?

**Comment by vshcherb** [comment]
We will discuss what's possible to do here and test on different devices
