### ISSUE TITLE
In General settings of profile some text can't be read

### ISSUE THREAD

**Issue by TatianaRud** [osmandapp/Osmand#7980]
_What version of OsmAnd are you using, on what device and Android/iOS version?_
OsmAnd 3.5.3 on device  Samsung s9+ (Android 9.0).
_Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?_
Offline maps, I guese.
_Issue:_
I selected the base profile, then clicked to Configure profile, then chose the General settings, and I got the next screen where some text can't be read.
![image](https://user-images.githubusercontent.com/54069247/69614945-bb057280-103c-11ea-91f6-1f8abbf61d82.png)
![image](https://user-images.githubusercontent.com/54069247/69615337-5b5b9700-103d-11ea-9679-2a99368719b5.png)

**Comment by max-klaus** [comment]
Fixed by https://github.com/osmandapp/Osmand/pull/8261
