### ISSUE TITLE
Динамічне оновлення локалізацій | Localizations dynamic update

### ISSUE THREAD

**Issue by Lyttym** [osmandapp/Osmand#7989]
Можна зробити динамічне оновлення локалізацій. Щоб нові перекладені рядки оновлювалися наприклад раз у день, або як карти/TTS чи за допомогою кнопки.
Це дуже б покращило UX-складову.

You can do a localizations dynamic update. For new translated lines to be updated, let’s say once a day, either as maps/TTS or using the button.
This would greatly improve the UX component.

**Comment by vshcherb** [comment]
You can dynamically update your locations. To keep the new translated lines updated, for example, once a day, either as cards / TTS or with a button.
This would greatly improve the UX component.

You can do a localization dynamic update. For new translated lines to be updated, let's say once a day, either as maps / TTS or using the button.
This would greatly improve the UX component.

**Comment by vshcherb** [comment]
We have nightly builds to check new localization. That should be enough for now probably.
