### ISSUE TITLE
show similar objects equally on the same zoom level

### ISSUE THREAD

**Issue by 532910** [osmandapp/Osmand#7996]
I'd prefer to see all entrances equally on the same zoom level or not to see them at all:

![image](https://user-images.githubusercontent.com/14617699/69751081-63135c80-115f-11ea-9f53-34132a01f2f3.png)
![image](https://user-images.githubusercontent.com/14617699/69751088-6575b680-115f-11ea-90c2-ded9eaab8e7a.png)

**Comment by vshcherb** [comment]
@xmd5a2  I think we should disable app numbers because they are hiding other entrances or display only on the next zoom level

**Comment by 532910** [comment]
@EugeneZmeuk, is it fixed?

**Comment by EugeneZmeuk** [comment]
18 зум -  номера подъездов, 19 зум - подъезды и квартиры. 
Касательно перекрытия номером дома номера подъезда, то это немного другой баг, уже работаем.

**Comment by 532910** [comment]
v3.6.3 still not fixed

![image](https://user-images.githubusercontent.com/14617699/79271101-ebdd2b80-7ea7-11ea-89e0-e65b590f4f08.png)
![image](https://user-images.githubusercontent.com/14617699/79271110-ee3f8580-7ea7-11ea-80c8-bdb691dfa257.png)
![image](https://user-images.githubusercontent.com/14617699/79271115-f0094900-7ea7-11ea-8c76-2a23184fb599.png)
