### ISSUE TITLE
[Feature request] add turn-by-turn audio signal

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd#7998]
In the Accessibility plugin settings, there is an Audio directions option available. It would be useful to add an opportunity to enable a sound signal for each turn.

**Comment by sonora** [comment]
We meanwhile have the various"beep" patterns available under Maps&Resources > Downloads > Voice prompts, does thar fulfil this request?

**Comment by TimoKramer** [comment]
I will certainly test this. Really good to know about this.
