### ISSUE TITLE
Provide a useful World Overview Map again!

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#7999]
In the 3.5.x release we have changed our map structure to only provide overview zooms 2-9 in a new (about 90MB download size) World Overview Map, and detailed zooms 10+ are now part of the regional standard maps. This led to a number of issues, not the least of which is once you updated your world overview map, you now have to re-download also all your regional maps, or else you are faced with a gap at zooms 9-10 on your device.

Another issue is that a world overview map only containing up to zoom 9 is pretty useless. The former (about 400MB) download containing up to zoom 11 could actually serve as an emergency map to get around if you had no regional map present, The new world overview map can not!

In order to solve both the issue of not burdening our users to have to download a large world overview map, but to still provide a reasonably sized and useful world overview to who needs it, I propose the following strategy:

1. In each regional map, include **all** zoom levels (2 and up, or whatever you need as the addition to the world basemap mini). The increase in file size for each regional map by adding zooms 2-9 will be negligible (less than 1 MB each). In connection with the World basemap mini, already included in our apk, this will serve the majority of users who mostly work with a few regions and do not need a world map.
2. Provide a **useful** World map, of a download size comparable to the larger regional maps, say 500MB. This will serve all users who frequently need to check things on a global level, and can also serve as an emergency orientation for where no regional maps are present on the device.
3. We may need a small change in our code making sure that if this new world map is present, zoom levels overlapping with any regional map are ignored from the regional map, so we do not render things twice, but this should be easy.

What do you think?

**Comment by scaidermern** [comment]
Sounds great (from a user's point of view :)).

The new world overview map indeed became pretty useless in some use-cases (see #7904). With the current behavior the user is left alone in emergency situations if the regional map is missing. It is not always possible to download the regional map instantly, e.g. if internet access is not available, too slow or too expensive. In such cases OsmAnd must provide a workaround by falling back to the world overview map. After all, OsmAnd is an app for offline navigation.

**Comment by dmpr0** [comment]
@scaidermern User will be left alone in an emergency situation if didn't download world overview too.

**Comment by scaidermern** [comment]
> @scaidermern User will be left alone in an emergency situation if didn't download world overview too.

Yes, of course. It should be a strong recommendation to download this map. However I already managed it a few times to suddenly be stranded in a location without regional map, usually a few kilometers behind the border of an existing regional map. OsmAnd doesn't warn when planning such a route (see #2525, #5734 and similar requests).

**Comment by vshcherb** [comment]
Yes, it was in our roadmap to provide detailed basemap where we will not be limited by size for most typical use cases.

**Comment by vshcherb** [comment]
Detailed map is provided (legacy to zoom 11). We're still working to add tertiary roads so it will be updated soon

**Comment by scaidermern** [comment]
Great! So I guess the "world basemap mini" is no longer needed if the "world basemap detailed" is installed?

**Comment by sonora** [comment]
@vshcherb Yes, before we consider this solved, can we please shed some light on how we expect users to act now, or can we maybe automatically delete  the not needed less detailed world maps? I now had 3 world maps present and active on my device, and it seems I should deactivate or delete the2 smaller of them now?

**Comment by vshcherb** [comment]
Only 1 is active, other 2 are deactivated. I would create another issue cause I would like to keep the issue in release i.e. 3.7 they are resolved. Though it is possible to put feedback here and read it and it is always possible to create a spin off. 

If map provided is not good enough is one thing and another it is not provided that means we need to reopen and fix that issue again.
