### ISSUE TITLE
Simulation with prepared routing does not work anymore

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#8003]
I prepare a navigation with defined start and end.
Then I open simulation. There I am offered to use a track for the simulation, which I don't need because the prepared navigation should be used.
version 3.5.0#28482m (2019-11-28)

![start simulation](https://user-images.githubusercontent.com/18628183/69807619-0ad36d80-11e6-11ea-94bd-0fef457d3136.jpg)

![List_of_available_tracks](https://user-images.githubusercontent.com/18628183/69807630-10c94e80-11e6-11ea-9ef7-4a17b8cc1f7a.jpg)

**Comment by dmpr0** [comment]
Hello, @pebogufi! 
What version of OsmAnd do you use? From what place of the app you launch simulation?
Please try to open Menu - Navigation - Options - Simulation turn on.

**Comment by pebogufi** [comment]
Version, see above posting.
Launch with Dashboard / start simulation. I always started it like that. But now it looks like that this is obsolete.
Your proposal, how to start, works.
So I think the access via dashboard can / should be removed, or is it good for something different?
Thanks for your VERY fast response.

**Comment by hvdwolf** [comment]
Version 3.6.2
I can't find the "Menu - Navigation - Options - Simulation turn on."

Using the option from the Dashboard -> Start Simulation does not work correctly anymore.
I really have to select a gpx route before it continues, but that is obviously not what I want. 

Next to that: When specifying a start and end point, it does not use that. It always routes from my current postion.

This is definitely buggy.

**Comment by pebogufi** [comment]
This is navingatuon / options
version nightly #2915 / 2020-03-08

![Screenshot_20200308-175318_OsmAnd~~01](https://user-images.githubusercontent.com/18628183/76167334-1da2fa00-6166-11ea-9cd3-1f9838db1577.jpg)

**Comment by hvdwolf** [comment]
Oh, it's a nightly build. That was not mentioned. I specifically mentioned 3.6.2 to show that I'm on the latest release.

However, I just downloaded the latest nightly, but the build mentions 26148d of 2020-03-08.
And that menu is not in there. With or without the development plugin enabled.

**Comment by pebogufi** [comment]
It worked with a nightly of Nov 28, see my posting above and proposal of dmpr0, same date.

**Comment by hvdwolf** [comment]
Your posting above says "version nightly #29165 / 2020-03-08".
Is that image above now from the 28 Nov or 8 March version?

And if it now has been removed from the nightlies, it really should be pushed as bug.

**Comment by pebogufi** [comment]
The screenshot is from version nightly #29165 / 2020-03-08 (today),
but the posting of dmpr0, my test and my response to it are from nov 28 where it worked like current nighly.  In the last weeks i used simulation quite often.
That means, this change is in souce from at least nov 28 to current version.
Nov 28 could be release 3.5.5, if i search for that date in https://download.osmand.net/releases/.
If you run a release >= 3.5.5 it should be available.
If i can help you further, please tell me...

**Comment by polarbearing** [comment]
Im running nightly _3.7.0#30422m (2020-08-28)_ and I still have the problem as described in the first post. 
Further, when presented the box with recorded trips as in the 2nd screenshot, the first item is called "map markers", and when I tap it, the app crashes. 
When I tap the "rec" ones, it just does not work. 
When I tag outside that selection box, it disappears, but just does not work .

**Comment by polarbearing** [comment]
Hm it seems that simulation from a GPX file and simulation from a calculated route is now started from different settings in osmand. GPX is via dashboard, while simulating from a calculated route is from the 'options' in the navigation settings. 
That's confusing, and even when using the switch in the navigation settings the dashboard switch changes to "stop stimulation", so they are somehow connected. But I cannot change the speed of the simulation in this case.

**Comment by pebogufi** [comment]
Fixed
