### ISSUE TITLE
Screen freeze issue

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8004]
After creating the track by Measure distance tool and using it for the navigation, the Navigation menu freezes, while tapping on the area occupied by this menu is not prevented from using the buttons behind the navigation menu (GPS and Navigation buttons). Rotating the device made the navigation menu disappear.
![image](https://user-images.githubusercontent.com/50198677/69810703-28f49a00-11f5-11ea-9f16-3d1fe8dc494e.png)

**Comment by nazar-kutz** [comment]
I cannot reproduce it for now
