### ISSUE TITLE
gpx_database issues

### ISSUE THREAD

**Issue by jensMF** [osmandapp/Osmand#8008]
Version: current master
The changes to the 'getFileDir' method changes what gets inserted to the fileDir column in the gpx_database for new gpx files. For old gpx files the values in this column does not change.
I wrote a really fast migration, but I realized, that I had a lot of unnecessary entries (I had over 4100) probably because of the wrong entries in the fileDir column. I deleted my database so it got recreated and now I have approximately 250 to 260 entries. (I tested the migration with the over 4100 entries and it took only a few seconds.)
So I thought, whether we could clear the database and readd all files in the tracks directory and it's subfolders.
We could use my helper function I wrote for the migration to find all of these files:
```
private List<File> updateFileDir(File lookupDir) {
    File[] lookupArray = lookupDir.listFiles();
    List<File> dirList = new ArrayList<>();
    if (lookupArray != null) {
        for (File toCheck : lookupArray) {
            if (toCheck.isDirectory()) {
                dirList.addAll(updateFileDir(toCheck));
            }
            else {
                dirList.add(toCheck);
            }
        }
    }
    return dirList;
}
```

**Comment by max-klaus** [comment]
I would suggest to delete all records with which have unexisting dir/file.

**Comment by vshcherb** [comment]
I think recreating track database is a good solution

**Comment by jensMF** [comment]
I thought about the the problem with the database entries without existing file.
Because OsmAnd allows the user, to have the tracks in a directory where the user has full access and can delete files manually, I think there should be a cleanup regularly. Maybe every time the App starts or stops.
I implemented a function for that and am calling it every time "openConnection" is run, but I don't know whether this could be to often.
And because of this I am not doing the cleanup during migration.

**Comment by jensMF** [comment]
I thought about the migration again and decided to backup and update the entries for existing files. Delete all entries in the table and then restore the backups.
I think this is the best method because:
 - there are a lot of duplicates in the db that would all be updated otherwise
- all data in the entries are kept

**Comment by sonora** [comment]
Thinking out loud about when to perform this: Would it maybe suffice if we perform a cleanup
1. upon the first app start after an OsmAnd version update installation
2. Have a database status debug info in the developer plugin settings, tapping  on which would manually perform this cleanup? (Similar to how I did it for the A-GPS refresh?)

If I am not mistaken, a regular user not playing with changing gpx files in the file system, i.e. just dealing with track recording and manipulation in the OsmAnd app itself, would not need such regular cleanup, and we can avoid the CPU cycles and associated battery consumption?

**Comment by max-klaus** [comment]
I do not think we need even cleanup since we do not read all the records at once anymore. The possible scenario - is check how much records in db at app startup. If db.count > 5000 for example, then compare it with number of gpx files in tracks folder and do cleanup db (or cleanup records pointing to unexisting files) if gpx.count < db.count.

**Comment by jensMF** [comment]
I read a few issues where people have written about syncing tracks with other apps. So I thought it would be important to do this regularly.
But doing it only if gpx.count < db.count or gpx.count < db.count + 500 or something like that would also be enough, I think.
