### ISSUE TITLE
Fuel-efficient way option issue

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8010]
During the navigation 
from: 40.45605 N - 15.01228 E
to:     40.38931 N - 15.02830 E,
OsmAnd suggests u-turns at 50.4361° N, 30.5063° E
![image](https://user-images.githubusercontent.com/50198677/69855386-11b8b980-1294-11ea-9d5d-762a615c4af5.png)
Enabling the Fuel-efficient way option fixes it.

**Comment by pebogufi** [comment]
Please add a turn restriction at this turn point (if it is legally correct ) and check again after the next map update.

**Comment by vshcherb** [comment]
Looks like a map data issue
