### ISSUE TITLE
Upper Sorbian as map/display language for iOS app

### ISSUE THREAD

**Issue by juliannyca** [osmandapp/Osmand#8016]
Hello. Upper Sorbian (hsb) has been a map and display language in the Android app for 3 years now. Is there a chance to open translation for the iOS app on Hosted Weblate as well? There are some other three-letter-code languages already implemented. Also: Would it be possible to allow Upper Sorbian as map language in the iOS app?

**Comment by max-klaus** [comment]
Hello, done via https://github.com/osmandapp/OsmAnd-ios/commit/005d6d79a7ed1e28e9263456a56cb3a19e7072ae and https://github.com/osmandapp/OsmAnd-ios/commit/efbbe49f8b28c006550a321310bf134369904a1b
