### ISSUE TITLE
Offer coordinates widget per type of transport

### ISSUE THREAD

**Issue by PanderMusubi** [osmandapp/Osmand#8021]
What version of OsmAnd are you using, on what device and Android/iOS version? 3.5.3 on Android 9

Please offer the setting 'Coordinates widget' in 'Configure screen' per type of transport and not for all types of transportation as it is not. Most like, people will use this only when hiking or when using the nautical map, so best to leave this up to the user, like many other widgets are already configurable per transportation type.

**Comment by vshcherb** [comment]
Coordinates widget is selectable for each profile as I see today.

**Comment by PanderMusubi** [comment]
Yes, my version has it too now. Thanks.
