### ISSUE TITLE
Text does not fit Voice Guidance Output setting

### ISSUE THREAD

**Issue by omawnakw** [osmandapp/Osmand#8025]
Device model: Galxy Note 9 (SM-N960F)
Android 9
Osmand +3.5.5
Does not affect tablets at least it is ok on Samsung Galaxy Note 10.1 (SM-P605)
Presumably in any language because english text is too long
Looks the same in FHD, FHD+, WQHD resolution in both screen orientations.
Configure profile  ->  Navigation Settings -> Voice prompts -> Voice Guidance Output 
In Russian: "Поток голосовых звонков (также п"
In English: "Phone call audio (to interrupt car Blue.-"

UPD: Looks like the text was fit the old style popup menu which did not stick to the bottom, left and right. See the last screenshot from 3.3.8

Is there some notions or guidelines for translators and devs  about the text length limitation (general or specific dialogs) in OSMAnd?

P.S. ~~Sorry for giant pictures~~. I've removed embedding. Is there any way to set img size in github issues markdown?

https://user-images.githubusercontent.com/4603332/69917318-931b7200-1475-11ea-8d8e-955ed71d24b9.jpg
https://user-images.githubusercontent.com/4603332/69917319-93b40880-1475-11ea-970b-ad3888bd13a4.jpg
https://user-images.githubusercontent.com/4603332/69917320-93b40880-1475-11ea-8f42-7cb30f456412.jpg

On tablet:
https://user-images.githubusercontent.com/4603332/69917425-f4901080-1476-11ea-8fad-44abc1f283a9.jpeg

OsmAnd 3.3.8:
https://user-images.githubusercontent.com/4603332/69923629-5f613c00-14b7-11ea-9b84-a4754c24e275.jpeg

**Comment by sonora** [comment]
Regarding picture size: I always resize to 50% or 30% before uploading.

Regarding the actual string: Would be good if we could somehow get it to display completely. It is somewhat of an explanatory string for the use case of this item, would not know how to reliably shorten in all languages.

**Comment by max-klaus** [comment]
Fixed by https://github.com/osmandapp/Osmand/pull/8261
