### ISSUE TITLE
How can users tell about incorrect translations?

### ISSUE THREAD

**Issue by Spielmops** [osmandapp/Osmand#8026]
Spielmops

**Comment by omawnakw** [comment]
If there is a bug in UI (text doesn't fit, not readable etc.) you can submit a correct bug report here specifying the version of OsmAnd (you can find it in Help section of the app) or in app properties in Android, your Anroid version, your device model, attach screenshots. 
If you want to help with translation the work takes place here https://hosted.weblate.org/projects/osmand/main/
