### ISSUE TITLE
Details view: road type gets confused over 'abandoned railway'

### ISSUE THREAD

**Issue by pietervdvn** [osmandapp/Osmand#8029]
When a cycleway is tagged both as 'abandoned railway' and 'highway=cycleway', the 'Road type' does not understand that this is a cycleway and gives 'undefined'.

An example of such a road can be found here https://www.openstreetmap.org/way/41601646#map=15/51.1976/4.1231

**Comment by pietervdvn** [comment]
Thanks for fixing! And thanks for the awesome app!

**Comment by vshcherb** [comment]
@pietervdvn please test it :-)

**Comment by pietervdvn** [comment]
I did test the nightly, it works fine now.
Met vriendelijke groeten,
Pieter Vander Vennet
