### ISSUE TITLE
House numbers sometimes are far from building polygons

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#8030]
If the building has a complex shape, the house number can be displayed outside the building and overlap other objects.
![изображение](https://user-images.githubusercontent.com/5829014/70047861-f7574680-15d9-11ea-9373-31837998f2ce.png)

**Comment by scaidermern** [comment]
I think this is the same as #5440. This problem exists for house numbers, POI icons, names & labels and similar things on complex shapes. The solution suggested in #5440 to use the _visual_ center of the polygon for icon / label placement also applies here.
