### ISSUE TITLE
Customize FAV and GPX icons.

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#8032]
Favorites and GPX File
1. Add Editor to change icon / color 
2. Add Editor to change shape

**Comment by dmpr0** [comment]
UI:
bg_point_circle
bg_point_rhomb
bg_point_square

Map:
Apply color for  **_center
map_bg_point_circle_top.png
map_bg_point_circle_center.png
map_bg_point_circle_bottom.png


map_bg_point_rhomb_top.png
map_bg_point_rhomb_center.png
map_bg_point_rhomb_bottom.png

map_bg_point_square_top.png
map_bg_point_square_center.png
map_bg_point_square_bottom.png

**Comment by pebogufi** [comment]
@vshcherb 
Very nice !
How can I change icon, background of a complete group ?
At the menu, where i can change color, or group name it is missing.

**Comment by pebogufi** [comment]
There is a workaround for change group:
- export (share)  group to gpx file
- make changes with a editor
- reimport gpx file
+ flag <icon> is ok
+ flag <color> is ok
+ flag <background is NOT ok -> unchanged
