### ISSUE TITLE
Option: for keep screen on or not

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#8034]
When Osmand app is active it prevents the screen to turn off. Whether it just shows the map, any settings screen, in navigation mode or not - the screen never turns off automatically.
There is NO problem with screen locking or turning screen off manually using power/lock button.
If I turn off screen manually and then turn it on Osmand shows instead of the lock screen. It prompts password or unlock id when trying to switch to another app or open system settings etc - seems to work properly.
Also there is NO problem with background process: when osmand is not the active app and home screen, settings or another app is currently active even when navigation currently active screen turns off automatically according to system timeout setting. Voice prompts works properly even id screen is turned off.
In 3.5.5 I can't find the option to toggle OsmAnd appearing above the lock screen - was it removed?

Expected behavior:
screen turns off automatically by default (modern phones keeps it on according to face sensor and accelerometer and use time-out only when the phone is at rest)
OsmAnd shows up above/instead of lock screen by default
there is an option to turn on "keep screen always on" in OsmAnd settings
there is an option to turn off "show OsmAnd instead of lock screen" in OsmAnd settings
P.S. For sure defaults are of my personal preference and should be guided by some observation like usage statistics, survey or voting.

Upd.: Looks like it's done with xml layout files so it need to be reworked with flags to have an option to turn it off https://github.com/osmandapp/Osmand/search?q=keepScreenOn&unscoped_q=keepScreenOn.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/issues/7315

**Comment by Themanwithoutaplan** [comment]
What's the best way to help with this? AFAIK OsmAnd doesn't do its own logging. I've already done `./adb logcat V:*` and filtered on OsmaAnd and sent this support (for obvious reasons I don't want to post such logs publicly). I can test with a Samsung S5 and a Samsung S10e, though the S5 doesn't seem to have the problem.

The interaction with the lock screen has also changed with the new setting "turn screen on" in the base profile. I did follow instructions from your support but, just in case I'm being completely stupid, can you provide step by step instructions for the setup and test?

**Comment by vshcherb** [comment]
This feature is not supported yet and I've copied the text from another soruce

**Comment by EssBee59** [comment]
Hello,

I got some days ago a new smartphone and the feature "automatic Scren on/off" did not longer run under Android 10 as previously under Android 8.1: 
the voice was ok after a turn instruction, the screen turned also on, but instead OSMAND the "scren lock" was displayed..
I am not sure, the same Problem is discussed here, but I try here to describe the solution I am using under Android 10:
Remember, app´s are not longer allowed to get "Administrator Rights"... 
So, if you wisch the screen turns on/off automatically during navigation you have to deactivate yourself any security check on the phone:
As exemple on my Xiaomi (Android 10) i do the following for bike navigation:
- I activated the "developper options" (click on build number 11 times or so in settings)
- in Settings, select the now available "developper options"
- activate the option "Skip screen lock"    

hope it helps Osmand users!
Ess Bee
