### ISSUE TITLE
Weird exit numbering on roundabouts with multiple exit lanes

### ISSUE THREAD

**Issue by Zireael07** [osmandapp/Osmand#8036]
The app seems to calculate exits poorly when there are multiple lanes involved. (Google Maps has the same issue, but MAPS.ME, also using OSM data, does not, it correctly announces the exit as the 2nd, so I don't think it's a matter of map data)

Route: https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=52.3114%2C21.1420%3B52.2602%2C21.1429#map=16/52.2932/21.1375
On the second roundabout at 52.2945,21.1382, the app incorrectly calculates the exit straight ahead as 3rd, when it's the second. 
It's not unique to that one roundabout, but that one's on my route so I could reproduce it reliably over the past week.

**Comment by vshcherb** [comment]
It is actually 3rd exit, it is quite poorly mapped. 
1 exit. https://www.openstreetmap.org/way/391655606
2 exit. https://www.openstreetmap.org/way/318002534#map=19/52.29437/21.13798
3 exit. https://www.openstreetmap.org/way/292331114

I would change roundabout layout So 318002534 will be part roundabout
