### ISSUE TITLE
[Request] Add a dark splash screen for global dark app theme

### ISSUE THREAD

**Issue by Gymcap** [osmandapp/OsmAnd#8040]
The only downside to the awesome dark theme is that the initial opening of the app is a blinding array of white pixels tearing through my fragile retinas. This is a joke, but the white splash screen can be anything from annoying and blinding while walking, to distracting and dangerous while driving.

I think it would be beneficial to a lot of people to add a dark splash screen, especially for those who use OsmAnd as a dashboard navigator.
_______________________________
I'm on mobile so I can't check if this has already been discussed, but I figured with these latest UI improvements, it might as well be time I ask.

**Comment by Chumva** [comment]
This should be fixed here - https://github.com/osmandapp/OsmAnd/pull/9760

**Comment by dmpr0** [comment]
**Review:**
- [ ]  Dark theme background color should be **list_background_color_dark**
- [ ]  Status bar should be **status_bar_color_dark**
- [ ]  Dark splash should appears in two cases: first if app theme set to "system deault" and systeme theme currenly dark, second if osmand app theme set to "Dark" no matter what theme is set in Android system settings.

**Comment by nazar-kutz** [comment]
It looks like dark splash screen for the second case "osmand app theme set to 'Dark'" is quite hard to accomplish because it loads by the system from resources based on selected theme in the android system. At this moment no code in-app is executed and it is impossible to get what theme is saved in osmand.
