### ISSUE TITLE
Support for "url" tag

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/Osmand#8043]
I think the "url" tag should be supported (it should be shown in the details of the POI).

**Comment by xmd5a2** [comment]
Already supported
![Screenshot_2019-12-17-16-14-29-878_net osmand plus](https://user-images.githubusercontent.com/5829014/70998429-6b204580-20e8-11ea-919b-a38071816773.jpg)

**Comment by OpenSourceForEver** [comment]
I meant this tag https://wiki.openstreetmap.org/wiki/Key:url
