### ISSUE TITLE
Tags for the selected point (railway=station, public_transport=station) are taken from the nearest public transport stop

### ISSUE THREAD

**Issue by Prusaker** [osmandapp/Osmand#8049]
If there is a public transport stop near the bus station or railway station, then when you view the properties of the station, the application displays tags not stations, but stops.

For example issue present for following places:
https://www.openstreetmap.org/way/59966100#map=19/53.84318/27.51833
https://www.openstreetmap.org/node/5255773884#map=19/53.83881/27.69248

Steps for reproduce issue:
1) Start Osmnad
2) Select bus station, tags is correct!
3) Move the map
4) Select bus station again. Tags in incorrect. You can see the tags not of the station, but of the stop located nearby

Video with reproduce issue you can see here: http://zxbyte.ru/issue.mp4
(this is temporary link, at future file will be deleted)

Issue observed at builds 3.4 and 3.5. OsmAnd 3.3 works correctly.

Thanks in advance.

**Comment by OpenSourceForEver** [comment]
The same thing happens to me but without the need to move the map (steps 2 and 3 are not needed)

**Comment by IgorEliezer** [comment]
The same is happens here: I select this bus stop (https://www.openstreetmap.org/node/7009911945#map=19/-23.66516/-46.50817) but OsmAnd shows the bus lines of this stop (https://www.openstreetmap.org/node/7003823138#map=19/-23.66516/-46.50817). Region Brazil-SaoPaulo.

**Comment by vshcherb** [comment]
This is correct behavior (what I see in the original bug report) because it has indication that transport doesn't stop at this stop and actually it stops nearby (around 150m ).

This is done on purpose to avoid some poor mapping in some areas.
