### ISSUE TITLE
Access all Settings via One Top-Level Menu

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#8051]
Users expect to find **one** menu item 'Settings'. Even in the most feature-rich apps.

The way we currently fragment and separate accessing settings according to whether they are global, or profile dependent, or plugin-relevant, is developer thinking, but spoils user experience.

**I suggest we combine all settings under one top level menu item 'Settings'**, in one logical but complete hierarchy.
- The direct profile selector and 'Configure Profile' short cut on top of the Drawer may remain, but must also become part of the 'Settings' menu.
- All other Drawer items we have now leading to settings in any fashion should disappear, as there are 'Configure map', 'Configure screen', and 'Plugins'.
- I even propose we could think about moving 'OsmAnd Live' and 'Download maps' under 'Settings'.  This would clean up the Drawer to feature only the app **actions for everyday use**.

**Comment by pebogufi** [comment]
Moving Confogure map+screen and plugins to new position is already done, so it can be removed from main menu.

>I even propose we could think about moving 'OsmAnd Live' and 'Download maps' under 'Settings'. This would clean up the Drawer to feature only the app actions for everyday use.

But it would need one more step to find it.

**Comment by IgorEliezer** [comment]
I'd take a different approach: a search bar that filters/shows the matching options. E.g. type in "Map" and everything that has the word "map" in the option names or description appears.

**Comment by OpenSourceForEver** [comment]
I agree with Sonora on everything except the matter of "Osmand Live" and "downloads" because these two items areare not purely part of settings.

**Comment by vshcherb** [comment]
I replied here - https://github.com/osmandapp/Osmand/issues/8045. But I also going to add that I would like to make it configurable. So I would definitely say that *we are not going to remove Download Maps* but it is important that people could configure it and hide what's not needed
