### ISSUE TITLE
Open keyboard on "Actions --> Create POI"

### ISSUE THREAD

**Issue by rene78** [osmandapp/Osmand#8052]
Until recently when creating a new POI for OSM (Long press somewhere on map --> Actions --> Create POI) the keyboard automatically opened up on the preselected name field. This behaviour stopped.

I tend to add POI's while cycling and use the phone one-handedly in those occasions. Without the auto-opened keyboard there is one extra move of my thumb up on those huge ass screens needed. Soon I'll drop my phone, if the keyboard doesn't come back automatically again... 😉

![Screenshot_2019-12-08-12-20-02-292_net osmand plus](https://user-images.githubusercontent.com/36115705/70388694-863ad900-19b5-11ea-925b-fb57851003ec.jpg)

**Comment by pebogufi** [comment]
Which version do you use ?
in 3.5.0#28526 from 2019-12-06 it works as expected.

**Comment by rene78** [comment]
Hmmm... strange. Maybe related to my OS?

OsmAnd+ 3.5.5
Android 9 with MIUI Global 11.0.3

**Comment by vshcherb** [comment]
Confirmed for me as well

**Comment by rene78** [comment]
Thanks very much!
