### ISSUE TITLE
Validate user ID error

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8057]
The issue reoccurs with a few users who have purchased a monthly OsmAnd Live subscription. REinstallation does not help.
![image](https://user-images.githubusercontent.com/50198677/70433991-20714e80-1a94-11ea-94fa-0e74d385bd55.png)

**Comment by max-klaus** [comment]
Looks like fixed with right Google Account logged in or restored connection to Google / OsmAnd server.
