### ISSUE TITLE
failed processing manifest

### ISSUE THREAD

**Issue by LonelyPluto** [osmandapp/Osmand#8061]
`org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':OsmAnd:processFreeLegacyArm64DebugResources'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:597)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
Output:  warn: removing resource net.osmand:string/colleted_data without required default value.
warn: removing resource net.osmand:string/commiting_way without required default value.
warn: removing resource net.osmand:string/description without required default value.
warn: removing resource net.osmand:string/download_detaile_map without required default value.
warn: removing resource net.osmand:string/gpx_description_txt without required default value.
warn: removing resource net.osmand:string/legacy_search without required default value.
warn: removing resource net.osmand:string/new_route_calculated_dist without required default value.
warn: removing resource net.osmand:string/no_update_info without required default value.
warn: removing resource net.osmand:string/no_update_info_desc without required default value.
warn: removing resource net.osmand:string/osmo_group_description without required default value.
warn: removing resource net.osmand:string/plugin_description_title without required default value.
warn: removing resource net.osmand:string/poi_additional_atm_yes without required default value.
warn: removing resource net.osmand:string/poi_amenity_atm without required default value.
warn: removing resource net.osmand:string/poi_bedding without required default value.
warn: removing resource net.osmand:string/poi_building_poi without required default value.
warn: removing resource net.osmand:string/poi_car_wash_self_service without required default value.
warn: removing resource net.osmand:string/poi_conservation without required default value.
warn: removing resource net.osmand:string/poi_counselling_type_nutrition_no without required default value.
warn: removing resource net.osmand:string/poi_dishes without required default value.
warn: removing resource net.osmand:string/poi_error_poi_not_found without required default value.
warn: removing resource net.osmand:string/poi_furnace without required default value.
warn: removing resource net.osmand:string/poi_general_tourist_attraction_yes without required default value.
warn: removing resource net.osmand:string/poi_generator_source_biomass without required default value.
warn: removing resource net.osmand:string/poi_health_facility_type_clinic without required default value.
warn: removing resource net.osmand:string/poi_health_facility_type_health_centre without required default value.
warn: removing resource net.osmand:string/poi_health_facility_type_hospital without required default value.
warn: removing resource net.osmand:string/poi_health_facility_type_pharmacy without required default value.
warn: removing resource net.osmand:string/poi_health_facility_type_rehabilitation without required default value.
warn: removing resource net.osmand:string/poi_health_specialty_radiotheraphy_yes without required default value.
warn: removing resource net.osmand:string/poi_historic_monastery without required default value.
warn: removing resource net.osmand:string/poi_information_wildlife without required default value.
warn: removing resource net.osmand:string/poi_level_crossing without required default value.
warn: removing resource net.osmand:string/poi_medical_system_unknown_yes without required default value.
warn: removing resource net.osmand:string/poi_mill_pond without required default value.
warn: removing resource net.osmand:string/poi_payment_none without required default value.
warn: removing resource net.osmand:string/poi_sanitary_dump_station_customers without required default value.
warn: removing resource net.osmand:string/poi_stars_6 without required default value.
warn: removing resource net.osmand:string/poi_stars_7 without required default value.
warn: removing resource net.osmand:string/poi_team_handball without required default value.
warn: removing resource net.osmand:string/poi_tourism_attraction without required default value.
warn: removing resource net.osmand:string/release_3_0 without required default value.
warn: removing resource net.osmand:string/release_3_1 without required default value.
warn: removing resource net.osmand:string/release_3_2_pre without required default value.
warn: removing resource net.osmand:string/release_3_3 without required default value.
warn: removing resource net.osmand:string/release_3_3_7 without required default value.
warn: removing resource net.osmand:string/search_no_results_description without required default value.
warn: removing resource net.osmand:string/show_legacy_search without required default value.
warn: removing resource net.osmand:string/show_legacy_search_desc without required default value.
warn: removing resource net.osmand:string/swap_start_and_destination without required default value.
warn: removing resource net.osmand:string/zoom_by_wunderlinq without required default value.
warn: removing resource net.osmand:string/zoom_by_wunderlinq_descr without required default value.
E:\android\workspace\Osmand\OsmAnd\build\intermediates\merged_manifests\freeLegacyArm64Debug\processFreeLegacyArm64DebugManifest\merged\AndroidManifest.xml:86: error: resource string/app_name_free (aka net.osmand:string/app_name_free) not found.
E:\android\workspace\Osmand\OsmAnd\build\intermediates\merged_manifests\freeLegacyArm64Debug\processFreeLegacyArm64DebugManifest\merged\AndroidManifest.xml:1104: error: resource string/osm_live (aka net.osmand:string/osm_live) not found.
error: failed processing manifest.

Command: C:\Users\Administrator\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\51bf10b44de05fb59d88ee3d7f6f7743\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
        E:\android\sdk\platforms\android-28\android.jar\
        --manifest\
        E:\android\workspace\Osmand\OsmAnd\build\intermediates\merged_manifests\freeLegacyArm64Debug\processFreeLegacyArm64DebugManifest\merged\AndroidManifest.xml\
        -o\
        E:\android\workspace\Osmand\OsmAnd\build\intermediates\processed_res\freeLegacyArm64Debug\processFreeLegacyArm64DebugResources\out\resources-freeLegacyArm64Debug.ap_\
        -R\
        @E:\android\workspace\Osmand\OsmAnd\build\intermediates\incremental\processFreeLegacyArm64DebugResources\resources-list-for-resources-freeLegacyArm64Debug.ap_.txt\
        --auto-add-overlay\
        --java\
        E:\android\workspace\Osmand\OsmAnd\build\generated\not_namespaced_r_class_sources\freeLegacyArm64Debug\processFreeLegacyArm64DebugResources\r\
        --proguard-main-dex\
        E:\android\workspace\Osmand\OsmAnd\build\intermediates\legacy_multidex_aapt_derived_proguard_rules\freeLegacyArm64Debug\processFreeLegacyArm64DebugResources\manifest_keep.txt\
        --custom-package\
        net.osmand.plus\
        -0\
        apk\
        -0\
        qz\
        --output-text-symbols\
        E:\android\workspace\Osmand\OsmAnd\build\intermediates\symbols\freeLegacyArm64\debug\R.txt\
        --no-version-vectors
Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0
Output:  warn: removing resource net.osmand:string/colleted_data without required default value.
warn: removing resource net.osmand:string/commiting_way without required default value.
warn: removing resource net.osmand:string/description without required default value.
warn: removing resource net.osmand:string/download_detaile_map without required default value.
warn: removing resource net.osmand:string/gpx_description_txt without required default value.
warn: removing resource net.osmand:string/legacy_search without required default value.
warn: removing resource net.osmand:string/new_route_calculated_dist without required default value.
warn: removing resource net.osmand:string/no_update_info without required default value.
warn: removing resource net.osmand:string/no_update_info_desc without required default value.
warn: removing resource net.osmand:string/osmo_group_description without required default value.
warn: removing resource net.osmand:string/plugin_description_title without required default value.
warn: removing resource net.osmand:string/poi_additional_atm_yes without required default value.
warn: removing resource net.osmand:string/poi_amenity_atm without required default value.
warn: removing resource net.osmand:string/poi_bedding without required default value.
warn: removing resource net.osmand:string/poi_building_poi without required default value.
warn: removing resource net.osmand:string/poi_car_wash_self_service without required default value.
warn: removing resource net.osmand:string/poi_conservation without required default value.
warn: removing resource net.osmand:string/poi_counselling_type_nutrition_no without required default value.
warn: removing resource net.osmand:string/poi_dishes without required default value.
warn: removing resource net.osmand:string/poi_error_poi_not_found without required default value.
warn: removing resource net.osmand:string/poi_furnace without required default value.
warn: removing resource net.osmand:string/poi_general_tourist_attraction_yes without required default value.
warn: removing resource net.osmand:string/poi_generator_source_biomass without required default value.
warn: removing resource net.osmand:string/poi_health_facility_type_clinic without required default value.
warn: removing resource net.osmand:string/poi_health_facility_type_health_centre without required default value.
warn: removing resource net.osmand:string/poi_health_facility_type_hospital without required default value.
warn: removing resource net.osmand:string/poi_health_facility_type_pharmacy without required default value.
warn: removing resource net.osmand:string/poi_health_facility_type_rehabilitation without required default value.
warn: removing resource net.osmand:string/poi_health_specialty_radiotheraphy_yes without required default value.
warn: removing resource net.osmand:string/poi_historic_monastery without required default value.
warn: removing resource net.osmand:string/poi_information_wildlife without required default value.
warn: removing resource net.osmand:string/poi_level_crossing without required default value.
warn: removing resource net.osmand:string/poi_medical_system_unknown_yes without required default value.
warn: removing resource net.osmand:string/poi_mill_pond without required default value.
warn: removing resource net.osmand:string/poi_payment_none without required default value.
warn: removing resource net.osmand:string/poi_sanitary_dump_station_customers without required default value.
warn: removing resource net.osmand:string/poi_stars_6 without required default value.
warn: removing resource net.osmand:string/poi_stars_7 without required default value.
warn: removing resource net.osmand:string/poi_team_handball without required default value.
warn: removing resource net.osmand:string/poi_tourism_attraction without required default value.
warn: removing resource net.osmand:string/release_3_0 without required default value.
warn: removing resource net.osmand:string/release_3_1 without required default value.
warn: removing resource net.osmand:string/release_3_2_pre without required default value.
warn: removing resource net.osmand:string/release_3_3 without required default value.
warn: removing resource net.osmand:string/release_3_3_7 without required default value.
warn: removing resource net.osmand:string/search_no_results_description without required default value.
warn: removing resource net.osmand:string/show_legacy_search without required default value.
warn: removing resource net.osmand:string/show_legacy_search_desc without required default value.
warn: removing resource net.osmand:string/swap_start_and_destination without required default value.
warn: removing resource net.osmand:string/zoom_by_wunderlinq without required default value.
warn: removing resource net.osmand:string/zoom_by_wunderlinq_descr without required default value.
E:\android\workspace\Osmand\OsmAnd\build\intermediates\merged_manifests\freeLegacyArm64Debug\processFreeLegacyArm64DebugManifest\merged\AndroidManifest.xml:86: AAPT: error: resource string/app_name_free (aka net.osmand:string/app_name_free) not found.
    
E:\android\workspace\Osmand\OsmAnd\build\intermediates\merged_manifests\freeLegacyArm64Debug\processFreeLegacyArm64DebugManifest\merged\AndroidManifest.xml:1104: AAPT: error: resource string/osm_live (aka net.osmand:string/osm_live) not found.
    
error: failed processing manifest.
Command: C:\Users\Administrator\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\51bf10b44de05fb59d88ee3d7f6f7743\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
        E:\android\sdk\platforms\android-28\android.jar\
        --manifest\
        E:\android\workspace\Osmand\OsmAnd\build\intermediates\merged_manifests\freeLegacyArm64Debug\processFreeLegacyArm64DebugManifest\merged\AndroidManifest.xml\
        -o\
        E:\android\workspace\Osmand\OsmAnd\build\intermediates\processed_res\freeLegacyArm64Debug\processFreeLegacyArm64DebugResources\out\resources-freeLegacyArm64Debug.ap_\
        -R\
        @E:\android\workspace\Osmand\OsmAnd\build\intermediates\incremental\processFreeLegacyArm64DebugResources\resources-list-for-resources-freeLegacyArm64Debug.ap_.txt\
        --auto-add-overlay\
        --java\
        E:\android\workspace\Osmand\OsmAnd\build\generated\not_namespaced_r_class_sources\freeLegacyArm64Debug\processFreeLegacyArm64DebugResources\r\
        --proguard-main-dex\
        E:\android\workspace\Osmand\OsmAnd\build\intermediates\legacy_multidex_aapt_derived_proguard_rules\freeLegacyArm64Debug\processFreeLegacyArm64DebugResources\manifest_keep.txt\
        --custom-package\
        net.osmand.plus\
        -0\
        apk\
        -0\
        qz\
        --output-text-symbols\
        E:\android\workspace\Osmand\OsmAnd\build\intermediates\symbols\freeLegacyArm64\debug\R.txt\
        --no-version-vectors
Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0
	at com.android.build.gradle.internal.res.Aapt2ErrorUtils.rewriteException(Aapt2ErrorUtils.kt:97)
	at com.android.build.gradle.internal.res.Aapt2ErrorUtils.rewriteLinkException(Aapt2ErrorUtils.kt:73)
	at com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask.invokeAaptForSplit(LinkApplicationAndroidResourcesTask.java:527)
	at com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask.doFullTaskAction(LinkApplicationAndroidResourcesTask.java:275)
	at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
	... 33 more
Caused by: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
Output:  warn: removing resource net.osmand:string/colleted_data without required default value.
warn: removing resource net.osmand:string/commiting_way without required default value.
warn: removing resource net.osmand:string/description without required default value.
warn: removing resource net.osmand:string/download_detaile_map without required default value.
warn: removing resource net.osmand:string/gpx_description_txt without required default value.
warn: removing resource net.osmand:string/legacy_search without required default value.
warn: removing resource net.osmand:string/new_route_calculated_dist without required default value.
warn: removing resource net.osmand:string/no_update_info without required default value.
warn: removing resource net.osmand:string/no_update_info_desc without required default value.
warn: removing resource net.osmand:string/osmo_group_description without required default value.
warn: removing resource net.osmand:string/plugin_description_title without required default value.
warn: removing resource net.osmand:string/poi_additional_atm_yes without required default value.
warn: removing resource net.osmand:string/poi_amenity_atm without required default value.
warn: removing resource net.osmand:string/poi_bedding without required default value.
warn: removing resource net.osmand:string/poi_building_poi without required default value.
warn: removing resource net.osmand:string/poi_car_wash_self_service without required default value.
warn: removing resource net.osmand:string/poi_conservation without required default value.
warn: removing resource net.osmand:string/poi_counselling_type_nutrition_no without required default value.
warn: removing resource net.osmand:string/poi_dishes without required default value.
warn: removing resource net.osmand:string/poi_error_poi_not_found without required default value.
warn: removing resource net.osmand:string/poi_furnace without required default value.
warn: removing resource net.osmand:string/poi_general_tourist_attraction_yes without required default value.
warn: removing resource net.osmand:string/poi_generator_source_biomass without required default value.
warn: removing resource net.osmand:string/poi_health_facility_type_clinic without required default value.
warn: removing resource net.osmand:string/poi_health_facility_type_health_centre without required default value.
warn: removing resource net.osmand:string/poi_health_facility_type_hospital without required default value.
warn: removing resource net.osmand:string/poi_health_facility_type_pharmacy without required default value.
warn: removing resource net.osmand:string/poi_health_facility_type_rehabilitation without required default value.
warn: removing resource net.osmand:string/poi_health_specialty_radiotheraphy_yes without required default value.
warn: removing resource net.osmand:string/poi_historic_monastery without required default value.
warn: removing resource net.osmand:string/poi_information_wildlife without required default value.
warn: removing resource net.osmand:string/poi_level_crossing without required default value.
warn: removing resource net.osmand:string/poi_medical_system_unknown_yes without required default value.
warn: removing resource net.osmand:string/poi_mill_pond without required default value.
warn: removing resource net.osmand:string/poi_payment_none without required default value.
warn: removing resource net.osmand:string/poi_sanitary_dump_station_customers without required default value.
warn: removing resource net.osmand:string/poi_stars_6 without required default value.
warn: removing resource net.osmand:string/poi_stars_7 without required default value.
warn: removing resource net.osmand:string/poi_team_handball without required default value.
warn: removing resource net.osmand:string/poi_tourism_attraction without required default value.
warn: removing resource net.osmand:string/release_3_0 without required default value.
warn: removing resource net.osmand:string/release_3_1 without required default value.
warn: removing resource net.osmand:string/release_3_2_pre without required default value.
warn: removing resource net.osmand:string/release_3_3 without required default value.
warn: removing resource net.osmand:string/release_3_3_7 without required default value.
warn: removing resource net.osmand:string/search_no_results_description without required default value.
warn: removing resource net.osmand:string/show_legacy_search without required default value.
warn: removing resource net.osmand:string/show_legacy_search_desc without required default value.
warn: removing resource net.osmand:string/swap_start_and_destination without required default value.
warn: removing resource net.osmand:string/zoom_by_wunderlinq without required default value.
warn: removing resource net.osmand:string/zoom_by_wunderlinq_descr without required default value.
E:\android\workspace\Osmand\OsmAnd\build\intermediates\merged_manifests\freeLegacyArm64Debug\processFreeLegacyArm64DebugManifest\merged\AndroidManifest.xml:86: error: resource string/app_name_free (aka net.osmand:string/app_name_free) not found.
E:\android\workspace\Osmand\OsmAnd\build\intermediates\merged_manifests\freeLegacyArm64Debug\processFreeLegacyArm64DebugManifest\merged\AndroidManifest.xml:1104: error: resource string/osm_live (aka net.osmand:string/osm_live) not found.
error: failed processing manifest.

Command: C:\Users\Administrator\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\51bf10b44de05fb59d88ee3d7f6f7743\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
        E:\android\sdk\platforms\android-28\android.jar\
        --manifest\
        E:\android\workspace\Osmand\OsmAnd\build\intermediates\merged_manifests\freeLegacyArm64Debug\processFreeLegacyArm64DebugManifest\merged\AndroidManifest.xml\
        -o\
        E:\android\workspace\Osmand\OsmAnd\build\intermediates\processed_res\freeLegacyArm64Debug\processFreeLegacyArm64DebugResources\out\resources-freeLegacyArm64Debug.ap_\
        -R\
        @E:\android\workspace\Osmand\OsmAnd\build\intermediates\incremental\processFreeLegacyArm64DebugResources\resources-list-for-resources-freeLegacyArm64Debug.ap_.txt\
        --auto-add-overlay\
        --java\
        E:\android\workspace\Osmand\OsmAnd\build\generated\not_namespaced_r_class_sources\freeLegacyArm64Debug\processFreeLegacyArm64DebugResources\r\
        --proguard-main-dex\
        E:\android\workspace\Osmand\OsmAnd\build\intermediates\legacy_multidex_aapt_derived_proguard_rules\freeLegacyArm64Debug\processFreeLegacyArm64DebugResources\manifest_keep.txt\
        --custom-package\
        net.osmand.plus\
        -0\
        apk\
        -0\
        qz\
        --output-text-symbols\
        E:\android\workspace\Osmand\OsmAnd\build\intermediates\symbols\freeLegacyArm64\debug\R.txt\
        --no-version-vectors
Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0
	at com.android.builder.internal.aapt.v2.Aapt2DaemonImpl.doLink(Aapt2DaemonImpl.kt:177)
	at com.android.builder.internal.aapt.v2.Aapt2Daemon.link(Aapt2Daemon.kt:103)
	at com.android.builder.internal.aapt.v2.Aapt2DaemonManager$LeasedAaptDaemon.link(Aapt2DaemonManager.kt:176)
	at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:823)
	at com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask.invokeAaptForSplit(LinkApplicationAndroidResourcesTask.java:525)
	... 50 more

`

**Comment by Chumva** [comment]
Try to call updateNoTranslate task in Gradle and build again.
