### ISSUE TITLE
Beanshell tiles are gone

### ISSUE THREAD

**Issue by pricewatermouse** [osmandapp/Osmand#8066]
All my highly beloved beanshell tile sources fail to download in v 3.5.5. I know that other users experience the same issue. Please fix.

If I downgrade the app to v 3.5.1, the tiles download without any problems. I use Android 9 (AospExtended ROM).

**Comment by vshcherb** [comment]
Yes, we've introduced new template language (extended version of standard) and removed beanshell. It caused troubles for some devices with Android 9 and further more we can't support iOS version though we plan to do it to provide same experience.

**Comment by vshcherb** [comment]
Please consider to migrate and share the difficulties if it is not possible to do it.

**Comment by pricewatermouse** [comment]
Could you please point me to the documentation for the **extended** template language?

I have to leave in expedition in less than a week and having those beanshell tiles was part of the navigation plan. Rolling back the version helps, however removing the core functionality without prior notice is always a big pain for the users.

**Comment by pricewatermouse** [comment]
https://github.com/osmandapp/Osmand/blob/master/OsmAnd-java/src/main/java/net/osmand/map/TileSourceManager.java

**Comment by vshcherb** [comment]
@pricewatermouse it was necessary move cause we had problems with Beanshell on Android 9 anyway. The old versions of OsmAnd are still available and the old apps are compatible with new maps.

Sorry for inconvenience.
