### ISSUE TITLE
Map update issue

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8067]
The OSM updates added over 2 months ago are not present in the latest OsmAnd map.
Example: https://www.openstreetmap.org/way/732905879

![image](https://user-images.githubusercontent.com/50198677/70597765-dd2cf200-1bf1-11ea-92cb-1ff0293e5326.png)

**Comment by vshcherb** [comment]
![image](https://user-images.githubusercontent.com/1042025/70926616-b75a7f80-202d-11ea-83c7-8919334a30f2.png)
Looks fine for me
