### ISSUE TITLE
Navigational issue: junctions

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8075]
While navigating from: 48.2258282, 6.4322586
to: 48.2262592, 6.4308488,
the instruction before the `highway=motorway_junction` node is to stay on N 57, but the destination of N 57 is not displayed before the junction, only after because only the way after the junction (https://www.openstreetmap.org/way/31109340#map=18/48.22683/6.43025) is tagged with `destination=Nancy;Thaon les Vosges;Charmes`

**Comment by MadWasp79** [comment]
can't see any problems with routing. 
The vehicle is already moving along N57 and allowed lanes are correctly marked in the widget. Don't understand what the matter of issue.
