### ISSUE TITLE
Nautical navigation issue

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd#8081]
When navigating from: 54.57542° N, 8.54118° E 
to: 54.63149° N, 8.38156° E
OsmAnd cannot build a route.
The issue occurs in the released OsmAnd and Nightly version.

**Comment by MadWasp79** [comment]
There is no corresponding OSM data to use for navigation (waterway=fairway) in that region.

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/8022
