### ISSUE TITLE
Bad routing with turn ramps

### ISSUE THREAD

**Issue by Hello71** [osmandapp/Osmand#8082]
OsmAnd~ 3.5.5

Offline car routing from 40.86965, -74.64238 to 40.86640, -74.63808:

![bad](https://user-images.githubusercontent.com/351006/70762472-8e45a080-1d48-11ea-9036-5239293e6563.png)

it seems that OsmAnd wants to cheat by going through the red light, but this maneuver is almost certainly slower (you need to wait for oncoming traffic in both directions) and probably also illegal.

I adjusted this intersection in changeset 78342823 to work around the issue, but there are a lot of these in New Jersey, so it would be good to have it fixed in the code.

**Comment by OpenSourceForEver** [comment]
I think this is a map problem and not Osmand. The problem will be solved by adding the link speed limit and editing the crossing to establish the prohibition of turning at the conflicting crossing

**Comment by Hello71** [comment]
seems like same problem
