### ISSUE TITLE
Lanes in the GPX route file

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8083]
While navigating with the GPX route from: 41.38140° N, 2.09668° E, to: 41.37658° N, 2.07678° E, the number of lines is either different from the real number or the line is not selected by OsmAnd.

**Comment by scaidermern** [comment]
Various features are currently missing when using a GPX track for navigation. See #3908.

**Comment by vshcherb** [comment]
Duplicate as it mentionned
