### ISSUE TITLE
Never ending alerts after navigation

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#8092]
After the navigation is completed (not interrupted), the last active alert (crosswalk, traffic warning) remains on the screen and is periodically duplicated by the voice.

Default profile: Browse map
Profile for navigation: Driving (base)

![image](https://user-images.githubusercontent.com/1042025/70912491-583c4100-2014-11ea-84a9-916ed749bfc4.png)

**Comment by RussianFox** [comment]
Напишу по-русски, а то боюсь не смогу донести мысль на английском.
Заканчиваем навигацию в точке с дорожной неровностью или пешеходным переходом с профилем "Автомобиль". Жмем кнопку "Завершить навигацию" и включается профиль "Обзорная карта" и на ней появляется алерт, который к тому же дублируется голосом.
Сейчас, в ночной сборке от 03.02.2020, если подвигать карту, алерт пропадает. Раньше такого не было.

**Comment by vshcherb** [comment]
Такая ситуация возможна как мы начали изменения с профилями, возможно это не повторяется если переставить приложение с 0. Будем изучать

**Comment by RussianFox** [comment]
Yes! Resetting the default settings for the profile helped solve the problem!
