### ISSUE TITLE
Show icons HOME and WORK on map

### ISSUE THREAD

**Issue by RussianFox** [osmandapp/Osmand#8094]
Pls, add the ability to display the system icons HOME and WORK on the map

**Comment by vshcherb** [comment]
They will be same favorites this release.

**Comment by RussianFox** [comment]
This feature is present in the nightly build.
But there are nuances. The full address is displayed on the map and it is very large for the map. And the address itself is wrong.
![photo_2020-01-09_19-00-54](https://user-images.githubusercontent.com/11329995/72083308-a0e4d280-3312-11ea-9edb-5be76a348c86.jpg)

![photo_2020-01-09_19-01-01](https://user-images.githubusercontent.com/11329995/72083175-6a0ebc80-3312-11ea-87f4-2305b6a4b1d8.jpg)

**Comment by vshcherb** [comment]
Yes it is going to be fixed

**Comment by vshcherb** [comment]
Fixed
