### ISSUE TITLE
Show road icons over navigation line

### ISSUE THREAD

**Issue by RussianFox** [osmandapp/OsmAnd#8095]
Pls, add the ability to display road icons (traffic lights, signs, cameras, walk crossings and other) over navigation line

**Comment by chereskata** [comment]
Second this

**Comment by chereskata** [comment]
@RussianFox  this should be fixed already in 4.3.0.7 <br>
![out](https://user-images.githubusercontent.com/87526889/188320041-c075ea9e-ffdd-43b8-9ac4-78d18bdf0a17.png) <br>
@vshcherb

**Comment by vshcherb** [comment]
It's already implemented in Opengl rendering android
