### ISSUE TITLE
Delete segments from the track by selecting start / end point 

### ISSUE THREAD

**Issue by jensMF** [osmandapp/Osmand#8099]
I was wondering why none of my tracks has any point in the Points tab. I realized that all my tracks where tracks and not routes and contained no waypoints. The route points for routes and waypoints are shown correctly.
But then I edited a track (that was not a route and had nothing shown in its "Points" tab) and had the possibility to unfold a list with all points and delete them an move them around.
Now I am wondering, what Points should be shown in the Points tab?

**Comment by njohnston** [comment]
The points tab shows waypoints. If you record a track and add waypoints manually, they appear there.

**Comment by jensMF** [comment]
Well it actually shows route points and waypoints but not track points and my question is: Is that the intended behavior?
Why am I asking this?
This Points tab is the only place where deletion of multiple points at once is possible. So track points can only be deleted one by one and that not even very fast, see  #8101.

**Comment by vshcherb** [comment]
Of course for waypoints only, we plan to have a trimmer to cut/extract segments from the track and we plan 3.6 or 3.7. So you can visually select start/end point and cut segment
