### ISSUE TITLE
Routing not from my location

### ISSUE THREAD

**Issue by RussianFox** [osmandapp/Osmand#8106]
Routing use my location as start If i set start point in other place

![photo_2019-12-18_12-02-45](https://user-images.githubusercontent.com/11329995/71071811-55fdf200-218e-11ea-8638-f52b7d4ea5e0.jpg)

**Comment by sonora** [comment]
Yes, naturally. :) Turn-by-turn guidance takes your true position as the reference for upcoming turns.

If you really want an emulation of turn-by-turn guidance (the common use case is testing) please calculate the route from an arbitrary start point, and then before statting the turn-by-turn guidance use the option 'Simulate navigation' under the routing options.
