### ISSUE TITLE
River over bridge

### ISSUE THREAD

**Issue by RussianFox** [osmandapp/Osmand#8111]
On default map style river and label is drawing over bridge area

![photo_2019-12-18_12-25-33](https://user-images.githubusercontent.com/11329995/71073468-7f6c4d00-2191-11ea-9b70-c34f59e50fce.jpg)

![photo_2019-12-18_12-28-17](https://user-images.githubusercontent.com/11329995/71073688-e68a0180-2191-11ea-8019-7325cebf5d30.jpg)

Points on image:
59.97845 30.28330
59.94880 30.26852

**Comment by xmd5a2** [comment]
Fixed river line. River text over bridge is not easy to fix.
