### ISSUE TITLE
A polygon of communication mast should be rendered

### ISSUE THREAD

**Issue by Rpnpif** [osmandapp/Osmand#8115]
A node of man_made=mast, tower:type=communication is well rendered on the OsmAnd map.
But a polygon with the same keys and values is not rendered.

A such polygon should also be rendered with the same icon.

Regards.

**Comment by xmd5a2** [comment]
![Screenshot from 2019-12-20 17-27-21](https://user-images.githubusercontent.com/5829014/71261286-0b2ad880-234e-11ea-9583-c04272f328ae.png)
Can't reproduce
