### ISSUE TITLE
Han character transliteration in Japan, Hong Kong, Macau

### ISSUE THREAD

**Issue by c933103** [osmandapp/Osmand#8119]
Han characters, otherwise known as Chinese characters, are used in multiple languages outside Chinese, including for example Japanese.
In Japan where Japanese is being spoken, and in Hong Kong and Macau where Cantonese are being spoken, when place name need to be transliterate into latin characters, their pronunciation in Japanese/Cantonese are usually being used.
However, in OSMAnd, place names with Chinese characters in these places are transliterated using pronunciation of those characters in Mandarin Chinese, which make the transliteration result virtually useless in these places.
Some other OSM-based projects which have place name transliteration feature, like https://github.com/giggls/mapnik-german-l10n , have already supported transliteration of Japanese name in Japan using Japanese rules.

**Comment by vshcherb** [comment]
Merged to #6292
