### ISSUE TITLE
Routing.xml not found. Map not loading.

### ISSUE THREAD

**Issue by deftsoftiphone** [osmandapp/Osmand#8122]
Hello All,

Can any one please help us by providing the routing.xml file.
We are able to compile the code but maps are not loading. 
According to us, the issue is with the missing routing.xml file.

Thanks in advance!!!!!!!!

**Comment by naoliv** [comment]
https://raw.githubusercontent.com/osmandapp/OsmAnd-resources/master/routing/routing.xml

But maybe something else is wrong and you are seeing only a side effect?

**Comment by vshcherb** [comment]
Please follow instructions on website help
