### ISSUE TITLE
Live subscription issue

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8123]
There was a notification about unsubscribing from the monthly Live subscription, although the unsubscribing was not initiated by the user. In Google Play, the subscription is identified as charged and active, but in OsmAnd menu - OsmAnd Live, there is a notification to purchase the subscription.
![image](https://user-images.githubusercontent.com/50198677/71244678-bf5f3b80-231b-11ea-8476-87283a361236.png)

**Comment by vshcherb** [comment]
There will be more information next release which could later provided to us and we can investigate it in a private order
