### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by deftsoftiphone** [osmandapp/Osmand#8124]
Hi All,

I am compiling the code and found some missing files in the OSM_And.
Please tell about the following files as it's not located in the packages.

Resource files 
Mx_highway_speed_camera
Mx_barrier_border_control
Mx_toll_booth
Mx_user_defined
Mx_name_finder
Mx_public_transport
Mx_route_bus_ref
Mx_route_ferry_ref
Mx_route_funicular_ref
Mx_route_light_rail_ref
Mx_route_monorail_ref
Mx_route_railway_ref
Mx_route_share_taxi_ref
Mx_route_train_ref
Mx_route_tram_ref
Mx_route_trolleybus_ref
mx_subway_station

Algo files
Poi_types.xml
Rendering_styles.xml
Regions.ocbf
routing.xml

C++ native libs.
libc++_shared.so

Packages (inside libc++)
Arm64-v8a
Armeabi-v7a
X86
x86_64

Fonts
Roboto-Medium.ttf
Roboto-Regular.ttf

**Comment by vshcherb** [comment]
Please dev build instructions on the website

**Comment by Vivekburada** [comment]
Hi @deftsoftiphone Can you please tell me how you resolved it? I'm new to android.
