### ISSUE TITLE
Routing crash issue

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8128]
When building a route from Hamburg, Finksweg 44 to 
Hamburg, Nissenstraße 4, there is an error appears "Fast route calculation failed (Index 3720, Size 3719), fallback to slow calculation. Then "Could not calculate route.: Index 3720, Size 3719"

**Comment by katerynakocherhina** [comment]
Te same issue occurs while building a route
From: 51.24265, 22.51487
To: 51.23391, 22.50421

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-core/commit/da0ec04e4ad8d8d25f1314db789f455c10f99888
