### ISSUE TITLE
Route building issue

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8130]
When building a route between:
2.80365, 101.74726 (https://www.openstreetmap.org/#map=19/2.80365/101.74726) to 2.80644, 
and 
101.75307 (https://www.openstreetmap.org/#map=19/2.80644/101.75307),
OsmAnd suggests the U-Turn.

**Comment by xmd5a2** [comment]
There was no turn restriction in OSM. Fixed.
![Screenshot from 2019-12-24 11-25-17](https://user-images.githubusercontent.com/5829014/71403391-a66ac900-2640-11ea-82e7-2bac32a6d4fe.png)
