### ISSUE TITLE
Rename and make "Plan Route" instead of Measure distance

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd#8131]
Many users do not know that the Measure distance tool is also used for route planning. Adding the route planning name to the measure distance tool menu section would help the users broaden their opportunities with OsmAnd.

**Comment by GrzegorzWidla** [comment]
Indeed I wasn't aware and switched to Locus Maps mainly for that feature. Now that I've noticed this issue and checked measure distance tool it's nearly as feature rich as Locus' route planner tool.

I'd say it's highly important and not only "nice to have" to rename and reposition measure distance tool in the menu.
