### ISSUE TITLE
[feature request] Use networks location service

### ISSUE THREAD

**Issue by Bogdan107** [osmandapp/Osmand#8138]
Osmand 3.5.5, Android.

В настройках андроида в разделе "Location services" выбрано "Use both networks and GPS".
Гугл-аккаунт настроен, интернет включён.

Прошу внедрить поддержку системы определения местоположения устройства по сигналам сотовой сети.

Сейчас Osmand использует только сигналы GPS для определения координат устройства и в случае отсутствия сигнала GPS, выполняет роль электронной карты. И только после определения координат по сигналам GPS превращается в навигатор.

Вот типичные условия, в которых вместо Osmand лучше использовать альтернативы:
- устройство без поддержки AGPS (из-за холодного старта при каждом использовании gps, ждать 2-3 минуты старта навигации при 10-минутном маршруте - перебор);
- погодные условия (gps-сигнал слабый и с помехами);
- городские условия (парковки, гипермаркеты, офисные центры, где gps-сигнал вообще отсутствует).

Т.е. в случае использования навигатора в условиях полного отсутствия сигнала GPS, либо его частого прерывания, Osmand без поддержки определения координат по сигналам сотовых сетей - всего-лишь электронная карта.

К примеру, альтернативные программы навигации, использующие сигналы сотовой сети для определения приблизительного местоположения, на том же самом устройстве без поддержки AGPS, сразу после запуска отображают положение устройства хотя-бы в пределах микрораёна.

**Comment by vshcherb** [comment]
OsmAnd использует данные сотовой связи, но не использует их для навигации. Данные показываются сразу после запуска. Так же OsmAnd не использует данные google play services что связаны с ограничениями по лицензии
