### ISSUE TITLE
[feature request] profile inheritance

### ISSUE THREAD

**Issue by lpirl** [osmandapp/Osmand#8140]
Dear OsmAnd community,

thanks a lot for this incredibly powerful app!

I was thinking if it would be useful to have some kind of profile inheritance. The reason is, that users might want to have largely the same settings across profiles and only specific things (e.g., map zoom and announcement time) altered in specific profiles. At least, that is true for me. :)

UI-wise, users might select a "base profile" (or alike) in the settings dialog of a specific profile. When a base profile is set, all configuration options offer the value "unchanged" (or alike), which means the configuration from the base profile will be used.

Alternatively, there could be *one* hard-coded base profile which all profiles inherit from unconditionally. This appears to be less powerful, but maybe also less complex for users to grasp.
In any case, the non-base profiles should still make explicit which configuration values are overridden and which are not (i.e., offer the value "unchanged" or alike).

Cheers.

**Comment by lpirl** [comment]
relates a bit to #4750

**Comment by vshcherb** [comment]
We plan to have special dialog to suggest copying on changing 1 value in each profile

**Comment by lpirl** [comment]
Thanks for the reply.
Not sure I understand: so I'd change an option in profile B to a value as in profile A and OsmAnd would suggest to copy profile A to B all the way?

**Comment by vshcherb** [comment]
Yes, for every change in the setting there will be a dialog (permanent or snackbar) to do changes in other profiles. We've found profile inheritance too complicated and cumbersome for some use cases. 
We already have a test version in nightlies

**Comment by lpirl** [comment]
Alright, cheers, looking forward to try this out.
