### ISSUE TITLE
Navigation issue - grids on cycle routes

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8144]
In bicycle or pedestrian modes, OsmAnd does not suggest route over a cattle grid.

The isue may be checked here
Position: geo:42.60982,2.0607626?z=22 
https://osmand.net/go?lat=42.60982&lon=2.0607626&z=22

**Comment by xmd5a2** [comment]
There is bicycle=no tag on cattle grid in OSM data. I don't know was it done intentionally or not, so fix is not possible.
