### ISSUE TITLE
Shorten "route recalculated" voice announcement if turn follows 

### ISSUE THREAD

**Issue by Famlam** [osmandapp/Osmand#8146]
Android 9, LG Q7
OsmAnd 3.5.5
Dutch language
Map of Gelderland, NL

1. Plan a route in an area with many streets (i.e., city center or so)
2. Take a wrong turn (which can be corrected by another turn after ~100m) while cycling ~20km/h
3. Get "The route has been recalculated. Time until destination is approximately 10 minutes." directly followed by "After 70 meters, turn right" (but in Dutch...)
4. Notice that in the 8-10 seconds during which the (Dutch) voice is talking, you are already almost at the crossing.

Expectation: 
1. OsmAnd should use the actual distance until the turn-to-be-made in the announcement, rather than the distance to the turn as it was when the voice started talking
2. OsmAnd should either shorten the voice prompt _when a turn is approaching_ (i.e., leave out the ETA), or first announce the turn, then the route-recalculated-message.

**Comment by sonora** [comment]
I had originally solved this at some point by just announcing "Route recalculated."

It looks like at some point we reverted to also announcing distance and time. In English it is short enough, I have not observed this to be an issue. But I just tested Dutch and it looks like the prompt sounds a lot longer ...

In any case, the easiest workaround may be this: You can edit the `nl_tts.js` file sitting in the `(osmand-data-folder/)voice/nl-tts` on your device. Shorten the line containing `return dictionary["route_calculate"]` to just `return dictionary["route_calculate"] + (tts ? ". " : "");`.

**Comment by vshcherb** [comment]
Suggestions and pull requests are welcome - https://github.com/osmandapp/OsmAnd-resources/blob/master/voice/nl/nl_tts.js#L253.

**Comment by Famlam** [comment]
Unfortunately I don't see any place in the code where the time until the next voice command is considered, so even if I shorten it a bit (which is only possible for the "new route calculated" part, Dutch numbers are just longer, i.e. twenty-five vs. (literally) "five and twenty"), the underlying cause wouldn't be tackled if you are closer to the next turn.

However, as a bandaid (without dropping distance or time), "Nieuwe afstand berekend" instead of "Afstand is opnieuw berekend" would save a tiny bit.

**Comment by RussianFox** [comment]
It is not need full information about route after recalculation.

**Comment by sonora** [comment]
Fixed via https://github.com/osmandapp/OsmAnd-resources/commit/20895b3fb1adf470d47ac43ab379cc0b1d02b216. Please post a pull request for that file if you suggest better wording instead of dropping the info.
