### ISSUE TITLE
GPX renderer cuts corners

### ISSUE THREAD

**Issue by SviMik** [osmandapp/Osmand#8151]
An example how a track is displayed in OsmAnd (recorded by OsmAnd itself):
<img src="http://svimik.com/osmgpx1.png" width="410">

Though when I pull it out of the phone and open with JOSM, it clearly has much more details:
<img src="http://svimik.com/osmgpx2.png" width="400">
<img src="http://svimik.com/osmgpx3.png" width="440">

Steps to reproduce:
1. Use an external GPS receiver with 4Hz or more update rate
2. Put it on a car and try to make some turns
3. Observe OsmAnd recording all the points but displaying overly simplified version of the track

**Comment by vshcherb** [comment]
We should stop simplification from certain zoom (probably 16 or 17)
