### ISSUE TITLE
Multipolygon parks don't show details properly

### ISSUE THREAD

**Issue by IgorEliezer** [osmandapp/Osmand#8158]
OsmAnd Nightly 3.5.0 # 25486d

Example: City park: https://www.openstreetmap.org/relation/10000021
Map region: Brazil - São Paulo

![image](https://user-images.githubusercontent.com/4673289/71596263-9dd13180-2b1d-11ea-8435-57628fb0c8f5.png)

With POI overlay on: You get the details; the overlay icon isn't aligned with the POI icon.
With OSM Editing plugin on: the generated OSM link is invalid (`/node/` instead of `/relation/`).

![image](https://user-images.githubusercontent.com/4673289/71596340-ebe63500-2b1d-11ea-9938-8e248f86a1d9.png)

**Comment by vshcherb** [comment]
Dupilcate of #5440 and #6497
