### ISSUE TITLE
[bug] altitude/slope (Altopiano di Asiago area - Veneto, Italy)

### ISSUE THREAD

**Issue by BG2311** [osmandapp/Osmand#8169]
Hi,
I was drawing a track on the footpath 845 in the Altopiano di Asiago area (Veneto, Italy) and I've found this bug:

![Screenshot_20200103_105609_net osmand plus](https://user-images.githubusercontent.com/59471800/71718871-e2f6ab80-2e1c-11ea-89b7-260035cc645f.jpg)

![Screenshot_20200103_100735_net osmand plus](https://user-images.githubusercontent.com/59471800/71718976-20f3cf80-2e1d-11ea-85ae-5d7b393104f8.jpg)

On the way up to Castelloni di San Marco there is a strange bug happening, altitude/slope go crazy to 2100/1200m despite being around 1650m a.s.l.

Any idea?
File .gpx attached

[2020-01-03_09-55_Fri.gpx.zip](https://github.com/osmandapp/Osmand/files/4018796/2020-01-03_09-55_Fri.gpx.zip)

Thanks
Claudio

**Comment by BG2311** [comment]
Hi,
just to add that I found a similar bug in the same area, tracking the famous Alta Via 11: it's the same latitude, I think the bug is related to the same strange lines you can see in the screenshot.
File .gpx attached, thanks for your support!
Claudio

![Screenshot_20200111_234131](https://user-images.githubusercontent.com/59471800/72224893-8fecc900-357f-11ea-846d-dbde975a2992.jpg)

![Screenshot_20200111_234504](https://user-images.githubusercontent.com/59471800/72224896-954a1380-357f-11ea-99d5-5664e2e4d4d4.jpg)

[Alta Via 11.zip](https://github.com/osmandapp/Osmand/files/4051349/Alta.Via.11.zip)

**Comment by MadWasp79** [comment]
Fixed. Glich will be gone in new maps (March)
