### ISSUE TITLE
Support for "url" tag not fixed

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/Osmand#8172]
I think https://github.com/osmandapp/Osmand/issues/8043 is not solved. 

Osmand nightly 3.5.0#25591d Map: Spain->Comunity of Madrid (January map)

At https://www.openstreetmap.org/way/230359023#map=19/40.70736/-4.06628&layers=D and https://www.openstreetmap.org/way/230359021#map=17/40.73716/-4.06515&layers=D Osmand do not show "url" tag

**Comment by max-klaus** [comment]
![Screenshot_1578214001](https://user-images.githubusercontent.com/53395422/71777439-1702d580-2fb1-11ea-8fc5-ae421459f60c.png)

**Comment by max-klaus** [comment]
Looks like we have website but not url. https://www.openstreetmap.org/way/230359023

**Comment by OpenSourceForEver** [comment]
Exactly

**Comment by xmd5a2** [comment]
Fixed. I was not aware that "url" can be used together with "website" tag

**Comment by OpenSourceForEver** [comment]
Osmand does not show link to "url" but shows link to url of the object in OSM.

**Comment by xmd5a2** [comment]
Please wait for february maps. Commit was done 14 january but maps are built starting from first day of the month.

**Comment by OpenSourceForEver** [comment]
Ok..Sorry
