### ISSUE TITLE
Build from sources gives an app that not render areas

### ISSUE THREAD

**Issue by goatchurchprime** [osmandapp/Osmand#8173]
I've done a fresh build from sources with [these instructions](https://github.com/3nigm4/osmand_build-instructions-how-to) and I consistently get a map that is as if the Configure options -> Map rendering -> Hide -> [] Polygons, [] Buildings have been checked.  

![image](https://user-images.githubusercontent.com/677254/71773014-7cbd7600-2f4d-11ea-9d05-c5ff7e0e995c.png)

With a lot of debugging, I have chased this problem up from the functions `OsmandRenderer.drawPolygon()` to `OsmandRenderer.drawObject()` and into `OsmandRenderer.generateNewBitmap()`, and then back down into the function `sortObjectsByProperOrder(..., pointsArray, polygonsArray, linesResArray)` which was not filling the `polygonsArray` with actual polygons (which are supposed to have `objectType==3`).  

I am not sure exactly what is going on in this code, but the bit that caught my eye was around [line 485 of OsmandRenderer.java](https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/render/OsmandRenderer.java#L485) where the code did this:

```Java
    mapObj.objectType = objectType;
    mapObj.order = order;
    mapObj.typeInd = j;
    mapObj.obj = o;
    if(objectType == 3) {
        MapDataObjectPrimitive pointObj = mapObj;
        pointObj.objectType = 1;
        double area = polygonArea(mapObj, mult);
```
In other words, as soon as it has a polygon (objectType 3) it sets it back to a point (objectType 1) because the object is not copied.  

Now, I can fix this problem if I replace the line `MapDataObjectPrimitive pointObj = mapObj;` with:

```Java
    MapDataObjectPrimitive pointObj = new MapDataObjectPrimitive();
    pointObj.order = order;
    pointObj.typeInd = j;
    pointObj.obj = o;
```

so that the `objectType` value is not over-written when the pointObj variable is made.

Clearly this fix cannot be right, because this [OsmandRenderer.java](https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/render/OsmandRenderer.java) file hasn't been touched in two years, and the recent releases of Osmand wouldn't have been any good.   

It looks like I'm on the right branch and everything (there have been edits two days ago).  What's going on?

**Comment by vshcherb** [comment]
You are going too far. This is done on purpose to distinguish non-native versions (wrong code).
1. You need to setup NDK and follow full instructions to build from source code
2. You can download apk and unzip already prepared arm, x86 libraries into libs folder

**Comment by vshcherb** [comment]
Cause you already did good investigation, please make a pull-request :-) It would be good to have a fix finally though we were not updating to keep it a bit different.

**Comment by goatchurchprime** [comment]
I am *very* confused now. I can find no build-from-source instructions (NDK-based or otherwise), other than this:  https://github.com/3nigm4/osmand_build-instructions-how-to

How is this polygonsArray bug not in the release product?  I cannot see how a different way of building from the code would make it go away.  Are you deliberately leaving certain source code files behind?  

When I fixed this line the app seems to work perfectly.  

I can pull-request this fix, no problem, but I would be doing it in the dark, because I don't understand how it is not showing up for you and have not looked at all the side-effects.  If this bug is meant to be there, then it should not be fixed.

**Comment by vshcherb** [comment]
https://osmand.net/help-online#dev-environment

**Comment by goatchurchprime** [comment]
I don't know how I missed that in the FAQ.  Sorry.  

Some notes I needed to help me compile it:

export ANDROID_SDK=/home/julian/Android/Sdk
export ANDROID_NDK=/home/julian/executables/android-ndk-r17b
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

* cd android/OsmAnd
* edit ../gradle.properties to uncomment org.gradle.jvmargs (for more heap space) and android.enableD8
* ../gradlew cleanNoTranslate assembleFreedevLegacyFatDebug
