### ISSUE TITLE
Map style issue in the Night map mode

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd#8188]
The offroad map style is displayed in the day mode while the night mode is turned on.

**Comment by vshcherb** [comment]
We don't have nightmode yet for offroad map style

**Comment by The-First-King** [comment]
Would it be added into any projects in future?

Also there is a bug in this mode - GPX files are not displayed with correct color. Default red shown as purple.

**Comment by The-First-King** [comment]
In the 3.9.8 release the offroad map style is unusable during nighttime when auto day/night display map mode (that is using sunrises and sunsets) is selected.

Workaround is to switch to day map mode.

**Comment by xmd5a2** [comment]
Fixed
