### ISSUE TITLE
Display place of worship & christian as Christian Church

### ISSUE THREAD

**Issue by mfbehrens99** [osmandapp/OsmAnd#8194]
Whenever there is a node/area with the _amenity=place_of_worship_-tag, a _religion=*_-tag and no name tag it is displayed just as "Place of Worship". However it should rather be displayed as Mosque, Church or others.

**Comment by comradekingu** [comment]
Could you provide an example. Some things are shared, and it is a bit difficult understanding what you are proposing.

**Comment by mfbehrens99** [comment]
![Screenshot_20200116-153501_OsmAnd~](https://user-images.githubusercontent.com/58851724/72551321-8ff50d80-388c-11ea-9c9f-25b09d1ef787.jpg)
![Screenshot_20200116-153431_OsmAnd~](https://user-images.githubusercontent.com/58851724/72551327-908da400-388c-11ea-9108-48ab5d19cf54.jpg)

**Comment by comradekingu** [comment]
Somehow this strikes me as an OSM-tagging issue(?)
That building might be a church, but places of worship aren't always buildings.

**Comment by vshcherb** [comment]
This has nothing to do with churches probably, we have different poi types man_made=building with name and separate for place_of_worship and yes buildings don't have icon on top of it.
