### ISSUE TITLE
[Feature request] Quick action, remove waypoint

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8195]
When missing the waypoint, OsmAnd insists on turning back to it, during the navigation. It would be useful to have an option to remove the closest waypoint on the go, without recalculating the whole route and missing the rest of the waypoints.

**Comment by vshcherb** [comment]
We need to make Quick Action
"Delete first destination point". If it is a final destination, then dialog of Finish Navigation should appear.

**Comment by vshcherb** [comment]
- после удаление последней, и запуска навигации заново, навигация запускается в состоянии ожидание конечной точки, а не на экане с work/home, history
#8195
