### ISSUE TITLE
Incorrect instruction: roundabout exit count too low

### ISSUE THREAD

**Issue by Famlam** [osmandapp/Osmand#8197]
This issue is the opposite of issue 8069; in this case roundabout exits are simply ignored rather than too many exits counted

Android 9, OsmAnd 3.5.5
Offline routing (bicycle), map: Gelderland, The Netherlands (map of 1-1-2020)

1. Follow this route using OsmAnd, using a bicycle profile https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=51.97794%2C5.91552%3B51.97813%2C5.91398#map=19/51.97823/5.91519&layers=N
2. Get the instruction to leave the roundabout at the first exit
![Screenshot_20200108-224359](https://user-images.githubusercontent.com/1315520/72019015-1ac08180-3269-11ea-9e4c-b4f2247802a3.png)

The arrow in the instruction does point in the correct direction, but the instruction to leave at the 'first exit' is obviously wrong. It's the third exit.

**Comment by TriumphST765** [comment]
Hi Famlam

The graphical progress on the route is correct, but the voice command is incorrect in a considerable number of occurrences.

I want to use OsmAnd for voice turn-by-turn on my motorcycle as I don't want to have to look at my phone, so this is a potential deal-breaker for using this app.

This app is a great piece of kit and it would be a shame that this issue  is not fixed.

**Comment by f6fvy** [comment]
+1

Even when driving a car, this bug is really annoying and error-prone. Hope the fix won't be too long....

**Comment by vshcherb** [comment]
![image](https://user-images.githubusercontent.com/1042025/72836606-45f59880-3c8d-11ea-9178-60868310d77d.png)
Looks it is fixed
