### ISSUE TITLE
track point editor works slow on scrolling down

### ISSUE THREAD

**Issue by 532910** [osmandapp/Osmand#8199]
It's impossible to scroll down till the end as the scrolling become extremely slow starting from about 1k point.

Steps to reproduce:
1. Select track, open it
2. `Edit`
3. Scroll down

![image](https://user-images.githubusercontent.com/14617699/72020701-65e48f80-327d-11ea-956b-2eab8f9e7e55.png)

**Comment by vshcherb** [comment]
That's just too many points it could handle. For split/join tracks we plan to have different simple editor

**Comment by 532910** [comment]
> plan to have different simple editor

Is there an issue for this?

**Comment by vshcherb** [comment]
Yes in 3.6
