### ISSUE TITLE
base profiles oddities

### ISSUE THREAD

**Issue by 532910** [osmandapp/Osmand#8200]
The concept with base profiles is complicated for understanding.

The base profiles are preinstalled. OK.
But they are undeletable. Why, are they read-only?
No, I can modify its settings!
But not color or icon, why?

Base profiles should be:
0. preinstalled (as now)
1. removeable.
2. completely coatomizable, color, icon, and even navigation type.

**Comment by dmpr0** [comment]
Hello, @532910! Thank you for the feedback. You can try to use latest nightly builds https://download.osmand.net/latest-night-build/OsmAnd-design.apk, we already do all the changes you are mentioned.

**Comment by 532910** [comment]
It's wonderful! (: I'll check it (and confirm) as soon as it will become available on F-Droid.

**Comment by saliman43** [comment]
plz tell me how to make Undeletable APK with metasploit 
how make metasploit APK Undeletable plz
