### ISSUE TITLE
Speed limit not displayed

### ISSUE THREAD

**Issue by mhtrinh** [osmandapp/Osmand#8209]
I cannot make the speed limit to display in OsmAnd Plus. Is there an option hidden somewhere to make it display Speed limit ? Does it need a special mode ? 
I can display my current speed, GPS tracking, GPS status, etc ... I am using OsmAnd Plus 3.5.4 on Android 5.1
Example of road I am driving on : https://www.openstreetmap.org/way/228183006#map=17/-37.77334/175.27415
I can see `maxspeed` tag which is correct

**Comment by pebogufi** [comment]
use in your profile menu "Configure Screen", have a look on the options.

**Comment by Discostu36** [comment]
It's this one:
![Screenshot_20200110-123445_OsmAnd](https://user-images.githubusercontent.com/30999326/72150344-a2130f80-33a5-11ea-822f-ded0a759125d.jpg)

**Comment by mhtrinh** [comment]
Oh. I was only using the other mode. So speed limit only show in Driving mode.
Thank you for you help.
