### ISSUE TITLE
map tilt mode

### ISSUE THREAD

**Issue by 532910** [osmandapp/OsmAnd#8211]
Really it should be **pitch**: https://en.wikipedia.org/wiki/Aircraft_principal_axes, but looks like it's known as **tilt**. Anyway I'm talking about angled view that is shown on the right picture: ![image](https://i.stack.imgur.com/H3gND.jpg)

I hate it! It's useless and annoying. But it has one advantage that I just realised and I can't live without tilt view anymore! The point of **tilt view** is the scale gradient: When you see the same number of details in both modes, in the normal mode all details will have the same scale, while in the tilt view the nearest objects will be bigger than far ones. **Tilt view** is useless and annoying but for map exploring mode (the same way as Norh is not on the top). But it's a must have feature for a driving mode (the same way as the map orientation by movement direction.)

**Comment by 532910** [comment]
More samples with the same scale but different tilt:
![image](https://user-images.githubusercontent.com/14617699/72586375-860df180-3902-11ea-8df7-4d70f55bdd9b.png)![image](https://user-images.githubusercontent.com/14617699/72586380-89a17880-3902-11ea-8cea-32c00f0be135.png)

![image](https://user-images.githubusercontent.com/14617699/72586384-8efec300-3902-11ea-92eb-5a2cc6ec03a0.png)![image](https://user-images.githubusercontent.com/14617699/72586386-91611d00-3902-11ea-9ebb-c46bf82b6220.png)

**Comment by 532910** [comment]
OsmAnd-iOS has it!!!

**Comment by Ahmadhosseinbor** [comment]
>  OsmAnd-iOS has it!!!

OsmAnd-Android ?!!!

**Comment by 532910** [comment]
It looks like this is implemented!
