### ISSUE TITLE
Support image tag

### ISSUE THREAD

**Issue by pangoSE** [osmandapp/Osmand#8215]
I just added a lot of image= tags to external photos for amenity=shelter in Sweden.

Could we add support for this? They are unfortunately not in Wikimedia Commons.
A downside to just loading any external image is that some photos are quite large.

I'm aware of wikidata and the plan to support photos through that. There OsmAnd can choose the smallest resolution by default.

**Comment by vshcherb** [comment]
I really think that we have a similar issue already though keep this one open.

**Comment by vshcherb** [comment]
It is already supported. We've tested on this node https://www.openstreetmap.org/node/7117830664

Please share details if it doesn't work
