### ISSUE TITLE
Show a confirmation when disabling osmand navigation from the notification menu

### ISSUE THREAD

**Issue by matjon** [osmandapp/Osmand#822]
Hello,
it is quite easy to disable osmand by accident by pressing the position "Disable the navigation service" (or whatever it is called in English).
A confirmation dialog would be welcome.

**Comment by OpenSourceForEver** [comment]
It would be a good idea

**Comment by sonora** [comment]
I think the pressing issue is more people having the service on without noticing rather than the other way round. Let me close tis, as there were no other tickets or feedback about this anywhere from what I can see.
