### ISSUE TITLE
Give rendering priority to traffic light icons

### ISSUE THREAD

**Issue by zekooooo** [osmandapp/Osmand#8227]
There's a minimum zoom level below which icons for traffic lights and pedestrian crossing stick figures don't render. However, at zoom levels where they do, traffic light symbols don't seem to have priority.

This is a problem, since to me it seems like the most information from any of those icons is gained by knowing whether the intersection is signalled. Dividing intersections by whether they have traffic signals creates more different and unifirm categories than whether they have marked crosswalks or tram rails.

Furthermore signalled intersections will obviously almost always have marked crossings and other such features. Unfortunately, that means there will be a bunch of these other icons too, which further lessens the chance of rendering the traffic lights icon.

Linking an [example screenshot](https://postimg.cc/0zS5VctV) (location: 45.814,15.994) where I've circled 4 intersections with traffic lights, but on two of them the only things rendered are one of the crosswalks and one of the road/tram crossings.

I'm using UniRS style with high contrast roads, text size & map magnification both at 100%. OsmAnd~ 3.5.5 (latest from F-Droid) on Android 7.

**What happens now**

At zoom levels where icons for traffic lights, crosswalks etc get rendered, they all have the same priority. You have to zoom in a few levels extra to be sure if an intersection is signalled or not.

**What should happen**

When rendering an intersection at such zoom level, if there isn't enough space for all icons, traffic lights icons should get precedence.

**Comment by Discostu36** [comment]
Are only talking about `highway=traffic_signals` or also about `crossing=traffic_signals`?

**Comment by zekooooo** [comment]
@Discostu36 Yeah I think both should have priority over other icons. I imagine plenty of people would want to either seek out or avoid such crossings no matter whether they're walking, driving, cycling etc.

Between those two I'd say the highway ones should have priority over the crossing ones. If an intersection has highway=traffic_signals and is accessible to pedestrians it can be implied in 99%+ of cases that there are crossing=traffic_signals, whether the mappers bothered to draw them or not. OTOH some residential unsignalled intersections in my city do have a single push-button crossing on one of the roads, so the inference doesn't go the other way. Altho it's surely a tiny share %-wise, so if you give them equal priority it's not that important.
