### ISSUE TITLE
Navigation issue: Pedestrian traffic is not permitted

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8231]
Although in Berlin, there is a pedestrian road available, there is no way to build a pedestrian route along Treskowallee: 52.47535/13.52222.
https://www.openstreetmap.org/note/2055091#map=19/52.47535/13.52222

**Comment by Discostu36** [comment]
Can you explain more precisely what doesn't work? I can route along Treskowallee
