### ISSUE TITLE
Inconsistent graph ranges for track analysis with separate segments

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#8236]
Carry over from #7084. May not be a big thing, but for the "Day 2" test track Victor provided in that issue, I see the following graphs:

For "Join segments=OFF", distance is now correctly shown as 56.4km, but the scale of the left hand graph still seems just 43km (right hand is ok):

![Screenshot_2020-01-14-23-37-34](https://user-images.githubusercontent.com/845735/72389117-e5fc7080-3727-11ea-8dad-39662175bb93.png) ![Screenshot_2020-01-14-23-37-38](https://user-images.githubusercontent.com/845735/72389122-e8f76100-3727-11ea-9d12-ce29b23d6fae.png)

For "Join segments=ON", distance is now correctly shown as 63.7km, but the scale of the left hand graph still seems just 43km (right hand is ok):

![Screenshot_2020-01-14-23-37-29](https://user-images.githubusercontent.com/845735/72389125-ec8ae800-3727-11ea-8075-b34ab9d8a412.png) ![Screenshot_2020-01-14-23-37-49](https://user-images.githubusercontent.com/845735/72389130-ee54ab80-3727-11ea-9f41-a3b27ea07651.png)

**Comment by vshcherb** [comment]
This is a buggy track and second segment doesn't have altitude that's why graph is not changing and there is no information. Please try thi sone
[3.gpx.zip](https://github.com/osmandapp/Osmand/files/4065582/3.gpx.zip)

**Comment by sonora** [comment]
Yeah, I know. It just bogged me that the altitide graph behaved wrong, while the altitude+slope graph is perfectly fine. :)
