### ISSUE TITLE
Dear developers

### ISSUE THREAD

**Issue by C00gan** [osmandapp/Osmand#8237]
I really love your app but recently i get more and more frustrated with it.

1. Turn off screen function is not working for ages now

2. Car navigation is a complete mess since the 2 last updates: widgets and voice make wrong annoucements only directions work properly

3. The app drains my battery like crazy: yes I have the animations deactivated and yes it was galaxies better about 2-3 years ago even without the working turn off screen function

So instead of working on new designs or improving minor details nobody really cares about, please eliminate the mentioned issues which are really important before I have to downgrade to a version from 5 years ago.

**Comment by vshcherb** [comment]
1. Turn off screen function is not working for ages now
There is a separate thread about, we've introduced using different API, so there are certain restrictions with new function. And we can't use old API anymore, so you can use an old version
2. So far we didn't hear any issue about that, please report an issue and if possible attach video or screenshots somehow, so we know which language to check and in which conditions
3. It is hard to check though it could be related to the battery age itself

**Comment by C00gan** [comment]
1. Will this work again in the near future? In which version did this function work before you changed the API?
2. #8164
3. Phone is about a year old. In the past i had about 2/3 battery remaining after 3 hours drive with the screen on all time, now it is after 1 hour drive.

**Comment by jypma** [comment]
@C00gan On your point (3), try to disable some of the newer map details. They'll take time (and battery) to draw. Also, to get a fair comparison, please do a battery capacity test using an external device, to see what your phone's battery capacity is after the one year. It's normal for a phone's battery capacity to drop a fair bit if being charged daily.

**Comment by vshcherb** [comment]
1. It was a change relased in March 2019 before that it worked as before.
2. The issue you are referring indeed happens though under very weird circumstances so far we didn't manage it reproduce it over 100 runs.
3. So your phone batter is 9 hours with active screen usage, it is not great and it is not bad. Good numbers are 10-12 hours for new phone though 9 hours is a pretty good as well especially with screen on.
