### ISSUE TITLE
Remove submodes of the navigation mode.

### ISSUE THREAD

**Issue by matjon** [osmandapp/Osmand#824]
Hello,
In the navigation mode there are 2 possibilities:
 - either at the bottom of the screen there are four buttons: menu, "i", "+", "-" or five buttons: menu, "X", "road sign", "car", "blue arrow".
This is confusing to the user. Please move the buttons into the menu as the end user would additionally not know what these buttons are for. The labels are very confusing.

I have been playing with osmand for quite some time and still don't understand how these two submodes differ.

**Comment by vshcherb** [comment]
this is going to be redesigned
