### ISSUE TITLE
Issue with visualization of favourite

### ISSUE THREAD

**Issue by airon90** [osmandapp/Osmand#8244]
This GIF explains everything: favourite are not "projected" when changing visualization of the map causing a wrong placement of favourite badge

**Comment by airon90** [comment]
I am using latest QT-ARM nightly version of OsmAnd

![ezgif-2-68bd36737d81](https://user-images.githubusercontent.com/139841/72538617-5ddcaf00-387e-11ea-87fb-4005375760ff.gif)

**Comment by vshcherb** [comment]
All layers don't function yet with OpenGL
