### ISSUE TITLE
[Cosmetic] Slightly disconnected tram track junctions

### ISSUE THREAD

**Issue by zekooooo** [osmandapp/Osmand#8248]
At deep zoom I've noticed a place where tram tracks appear to be disconnected at some Y junctions in OsmAnd~ even though they seem connected in OSM editor.

Coordinates: 45.805, 15.966 - [OSM.org](https://openstreetmap.org/#map=19/45.80500/15.96600) - [OsmAnd Screenshot](https://postimg.cc/XGtrCv5F)

Using OsmAnd~ 3.5.5 (F-Droid) on Android 7, UniRS style with high contrast roads

**Comment by vshcherb** [comment]
<img width="1120" alt="Screen Shot 2020-01-21 at 18 52 27" src="https://user-images.githubusercontent.com/1042025/72829505-32433580-3c7f-11ea-94f2-d5f1e7a5e96b.png">
Indeed it looks suspious

**Comment by vshcherb** [comment]
We need to try "BUTT" and disabling simplification - https://github.com/osmandapp/OsmAnd-tools/blob/master/java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/BinaryMapIndexWriter.java#L687

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-tools/commit/2fe8411def13824cff7467be4a531d20226830b9
