### ISSUE TITLE
Bike path road calculation issue with 2 ways marked roads

### ISSUE THREAD

**Issue by martinhamel** [osmandapp/Osmand#8259]
When I ask for this routing on OSM, it is correct. That road is one way but the bike path on it is marked as 2 ways. No problem there.

https://www.openstreetmap.org/directions?engine=fossgis_osrm_bike&route=45.49525%2C-73.57994%3B45.49754%2C-73.57810#map=18/45.49638/-73.57897&layers=C

If I ask for the OsmAnd in-app routing, it does not want me to go that way and asks me to go on side streets as showed on this picture: 
![OsmAnd wrong routing](https://lh3.googleusercontent.com/_YlmjOvKZuyHQ4a6o7ym80OX_4MlFLH-kb8BijV8pzu4kyELNGoEeXXPLq-qgzDfAyBS4ApnG9zoNTzr7qSI2i3Yj2EQMAekV-Ys9cpoHBtw-8J_LV0uI-tdZVewgg1KBk7Ii3xzIBjfI2FZfmXI_GnXuLJ0WJZXGT_gs4-HXucf2kxvM3IE-C0Mu7RwUiXN-JhszQ0qzgHq2MRJq7r_erDcbK0_0zqQ0_lOmvgDidU4hl9z86ZZtvf8JJTZqW1UdcdPFTThfCOlMkra0g5sWc0LF4W351L0dPDPlx_StR8-w8atLPnQ0rm9sIIGNYpaoRV_fDnalO-ek_NHLuazSDIodr2ucc4XlMMjndqgR8lfvwQD7Qoi73eF3ktcSJMvrYco4KMHCdQu-ra0DpWbQLtyFcyFk9PP88i5qXsoJcfDCh7Kyk-z-V1cjVlf7DZTP1-xgWI4UFNCKAItLUoMgpci5MfCsndLcoj6ii2gqIn0IxOPDyROL6fyHMvUpjUlY_jPfKMKNNgIU3_rC1FpsvEnrl9IL2B1y_Lnt7I0o0rvuReqZl_oUViQ4bBOIs5j3YWDgFMKBBrE5Ni0G_hMRdLpxroTxXwOlrPR5Y3UW9nwNgeowYtxtBc3O3_zyhISd4M6E6g3xLY6bUJXSZ2xqy45wSUesyhqjKT7KXftLtakdUqS9voeIyWTUyGB4LKK53FOU1913rJZxJHV6wqH9-uvqQ0XVgpL84W-Vig9R29ez7CKTA=w477-h979-no )

I suspect is has to do with the handling of the oneway:bicycle | no

**Comment by vshcherb** [comment]
![image](https://user-images.githubusercontent.com/1042025/77825827-1b501200-710c-11ea-888b-1a9a2b02536b.png)
Now the situation is better though it still pushes the route to secondary road cause there is a cycleway:left = track there.
