### ISSUE TITLE
Feature request: Route planing tool

### ISSUE THREAD

**Issue by Mannshoch** [osmandapp/Osmand#826]
Many times I use a routeplaner at first to plan my route. How long do I need, wich way an where should I meet others and more on my phone. The problem is, I could not enter a startpoint. If I do plan a route from an other startlocation then my current or If I'm in a House, I'm not able to plan the route with Osmand.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/issues/1164
