### ISSUE TITLE
Speed alarm in background as plugin

### ISSUE THREAD

**Issue by mhtrinh** [osmandapp/Osmand#8260]
Hi

I am trying to implement a plugin that alert user when exceeding speed limit, but when the screen is off. The plugin will work similarly to the gpx recording plugin.

Can someone give me some advice on how to achieve this ? 

Looking in the Osmand code, I can see that the NavigationService can provide Location in background, which the gpx recording plugin use. The problem is the current maxspeed provided normally by WaypointHelper seems to be disabled/frozen when the screen is turn off. 
NavigationService also provide location for background navigation, but I don't see anywhere the speed limit check when running in background.

I don't if github issue is the right place to ask this sort of question, please let me know if somewhere else would be more appropriate.

**Comment by vshcherb** [comment]
This is quite tricky, you need to combine Service with Alarm Notification mechanism. It happens in the widget but you need basically copy or call the widget's code from the background running service.
