### ISSUE TITLE
Adding a line for end point of route

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/Osmand#8266]
There is a problem with endpoint for a route where is not a graph for routing.
![1a](https://user-images.githubusercontent.com/44466116/72728599-cbe6e600-3b9e-11ea-8e04-061ffc95e80d.jpg)

I propose to add a line like for start point.
![2a](https://user-images.githubusercontent.com/44466116/72728622-d73a1180-3b9e-11ea-9c8b-3f8c879aeb0d.jpg)

**Comment by vshcherb** [comment]
We should use the same approache for end point as we use for start point (similar threshold).
