### ISSUE TITLE
Wrong bus station names in Israel

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8280]
the part of the string with the number of the station is written in LTR while the rest of the string is in RTL which makes parentheses wrong direction.
Example: 32.78343 35.01514
![image](https://user-images.githubusercontent.com/50198677/72801122-82a39e80-3c51-11ea-9d9e-7ac563d41425.png)

**Comment by vshcherb** [comment]
Duplicate
