### ISSUE TITLE
Crash while building a route 

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8281]
In Israel, while building a public transport route long the bus stations, the crash appears or the route cannot be built at all. 
the issue occurs at 32.78343 35.01514

**Comment by MadWasp79** [comment]
The crash cannot be reproduced.  And problems with route building are from unsupported route relation format - OsmAnd doesn't support older PTv1 format (only PTv2). It should be fixed on OSM.
