### ISSUE TITLE
No maps found

### ISSUE THREAD

**Issue by mmjoshi** [osmandapp/Osmand#8289]
I downloaded the latest version from F-Droid on my Nokia 6.1 running Android 10. However, do not find any maps in the Download maps section. It ssys "Downloading list of available regions" but no regions are showed.

**Comment by sonora** [comment]
The region list is downloaded, and this will take a few seconds depending on your Internet connection. Did you maybe refuse network access for the app by any chance, please check the app permissions.

**Comment by mmjoshi** [comment]
Thanks for pointing out. My firewall was not allowing internet access. Things ate fine once that was taken care of.

Another question. If I download the map of California do I still need to download individual regions like San Francisco, Los Angeles etc. separately?
-- 

Sent from my mobile.

22-Jan-2020 1:54:21 am Hardy <notifications@github.com>:

**Comment by sonora** [comment]
Ok, glad we got it sorted out! :)

No, the metropolitan maps are meant for users who do not want to download an entire country or state. The California standard map does contain the details for the entire state, including all cities. Extra/special maps you may want to consider in addition are only hillshades and contour lines (if you have that plugin), the Wikipedia POIs (if you use the paid version of OsmAnd), and special topic maps like the nautical.
