### ISSUE TITLE
Use original rotation from Wikimedia Commons images

### ISSUE THREAD

**Issue by IgorEliezer** [osmandapp/Osmand#8290]
The image viewer should (or should not, when improper) rotate an image from Wikimedia Commons.

![image](https://user-images.githubusercontent.com/4673289/72862692-d68fa100-3cac-11ea-9dcc-8f72ce5a250e.png)

The original image is straight: https://commons.wikimedia.org/wiki/File:Wiki_Takes_Santana_de_Parna%C3%ADba_(Jul_2019)_178.jpg

**Comment by vshcherb** [comment]
Couldn't reproduce, could you please provide location from latest maps if it is still there
