### ISSUE TITLE
cycling routes issue

### ISSUE THREAD

**Issue by MiroslavKocian** [osmandapp/Osmand#8293]
Hello, 
I am a paid user of the app and I am very satisfied, thanks for the support! However, there is 1 thing that would help so much. Can you fix how the cycling routes are displayed, please?
All the routes are pink and it is impossible to know where I am quickly. 
It would be great to have a different colors of C next to the routes as in mapy.cz
https://en.mapy.cz/turisticka?x=17.0789045&y=48.2060434&z=15 
as on the image below.
Thanks!

Miro 
![image](https://user-images.githubusercontent.com/10284585/72889345-c9f06480-3d0f-11ea-800c-d17ce04e5d30.png)

**Comment by ligfietser** [comment]
Since I have updated the maps, I noticed the cycle routes are not rendered the same anymore. What is changed? BTW I maintain the Openfietsmap style, but there seems that something has changed in the country data (Netherlands_europe_2.obf) lately?

**Comment by ligfietser** [comment]
![old map without cycle routes](https://user-images.githubusercontent.com/9638726/73010716-330cd080-3e13-11ea-96b8-148e7e76dc91.jpg)
This is the old version of Netherlands_europe_2.obf (March 2019)
Openfietsmap Style, cycling mode, cycle routes are not selected. It shows blue dashed lines where the cycle routes are.

![old map with cycle routes](https://user-images.githubusercontent.com/9638726/73010822-6e0f0400-3e13-11ea-86bb-c4a4f8beb08e.jpg)

This is the old version of Netherlands_europe_2.obf (March 2019)
Openfietsmap Style, cycling mode, cycle routes are selected. It shows blue dashed lines where the cycle routes are, plus a pink "Osmand style" color on top of the cycle routes

![new map without cycle routes](https://user-images.githubusercontent.com/9638726/73010892-9139b380-3e13-11ea-9293-6d76ebdc6792.jpg)

This is the latest version of Netherlands_europe_2.obf (January 2020)
Openfietsmap Style, cycling mode, cycle routes are not selected. It does not show the blue dashed lines where the cycle routes are anymore!

![new map with cycle routes](https://user-images.githubusercontent.com/9638726/73010981-baf2da80-3e13-11ea-8eab-3f7e9bac07a6.jpg)

This is the latest version of Netherlands_europe_2.obf (January 2020)
Openfietsmap Style, cycling mode, cycle routes are selected. It does not show the blue dashed lines, plus it shows a brownish color where the cycle routes are. This is hardly visible anymore, what happened to the raw data?

**Comment by vshcherb** [comment]
@ligfietser it is quite easy to inspect the tags with binaryInspector.sh and check what's going there the colors usually encoded in the lanes. Probably something has changed though I don't see any changes how we process OSM: https://github.com/osmandapp/OsmAnd-resources/commits/master/obf_creation/rendering_types.xml (convert type from OSM - > OBF)

Also Inspector can do transformation from OBF -> OSM, so you can explore tags in JOSM for example

**Comment by ligfietser** [comment]
Thanks for the quick reply. Those blue dotted lines are rcn cycle routes, nothing has changed in the OSM data. So it must be something hard coded, because it does not matter wich xml style version I use (old or latest, default.xml also shows now brown lines with the latest map data.

**Comment by ligfietser** [comment]
Just noticed that the August 2019 maps still shows the pink route color, but gone are my blue dotted lines. So between March and August some changes were made that made my style incompatible, and between August and January the route colors were changed. Any idea where I can find those changes or how to fix this?

**Comment by ligfietser** [comment]
I found out where the brown color comes from: https://github.com/osmandapp/OsmAnd-resources/blob/c6391708a8f0a4e72dd9bd59bbbffdaf636ce7c5/rendering_styles/default.render.xml#L1175

Must be introduced mid 2019, is not an improvement at all.

**Comment by xmd5a2** [comment]
@ligfietser I can't figure out source of blue dotted lines and can't reproduce it. Please note that a new option was added to "Configure map" - "Routes": "Show node network cycle routes". Regular long distance cycle routes are now separated from short node network cycle routes.

**Comment by ligfietser** [comment]
> 
> 
> @ligfietser I can't figure out a source of blue dotted lines and can't reproduce it. Please note that a new option was added to "Configure map" - "Routes": "Show node network cycle routes". Regular long distance cycle routes are now separated from short node network cycle routes.

Thanks for your reply @xmd5a2 
I already fixed it in my styles. I still can't figure out how and where you separate the short from the long distance cycle routes in the code. Can you point me to which lines in the default.renderer.xml these are coded?

**Comment by xmd5a2** [comment]
There were massive changes. See this commit https://github.com/osmandapp/OsmAnd-resources/commit/c100e6d64435126c4ffd6409ff491bf510156821
