### ISSUE TITLE
Enhance the search feature

### ISSUE THREAD

**Issue by Marenz** [osmandapp/Osmand#8294]
I searched around a bit and couldn't find any "meta" issue that collects all the problems and suggestions with the offline search so I am creating this now.

After talking with a few people using osmAnd the consensus seems to be that the search feature could use a lot of enhancements. I want to collect all the suggestions and cases here.

Please post additional problems/cases here.

* https://github.com/osmandapp/Osmand/issues/4491 - Searching for "Guy's" does not find "Guys"
* Searching for "southbeach" will not find "south beach"
* ..

**Comment by scaidermern** [comment]
* #5469
* #6233
* #6317
* #7123

**Comment by vshcherb** [comment]
I don't see a reason to have generic issue that might not help easier to use tags or something similar

**Comment by Marenz** [comment]
Well, I wanted to use it for a bug bounty..

**Comment by vshcherb** [comment]
:-) I'm not against it thought collecting all into 1 could be very big issue by itself which never going to be fixed

**Comment by yaomtc** [comment]
The other day, I did a search for `Stand Up Burgers`, but I didn't find it, because it was actually `Stand-Up Burgers`. Whether I use a hyphen or not should not make or break the search results.
