### ISSUE TITLE
Integrate OsmAnd to Relive

### ISSUE THREAD

**Issue by cotangente** [osmandapp/Osmand#8296]
Hello,  I wanted to import a gpx file track from OsmAnd (using trip recording plugin) to [Relive](relive.cc) but last one says that I have wrong (or none) timestamps.

OsmAnd output file (the one not accepted in Relive) looks like [this](https://pastebin.com/XKnwhaD4)
while a sample gpx file from a previous Relive activity looks like [this](https://pastebin.com/kpVemr2X)

Is it possible to make a Relive compatible output file from OsmAnd?

OsmAnd Version: 3.5.5
Android.

Thanks for your time!

**Comment by vshcherb** [comment]
The OsmAnd output file is not recorded GPX but a file with instruction for the future route. You need to use Recording Plugin
