### ISSUE TITLE
OsmAnd+ shows only number of GPS/GLONASS satellites and no Galileo, Beidou,..

### ISSUE THREAD

**Issue by keynator** [osmandapp/Osmand#8298]
OsmAnd+ (3.5.5 from PlayStore) on a smartphone (using Android 10) with support for several GNSS like GPS, GLONASS, Galileo, Beidou does **only show the number of used (and possible) satellites of GPS and GLONASS satellites**.

I know that this should not decrease the GNSS accuracy but this information of the widget seems to be wrong. This bug is show in the following image: In the upper part is OsmAnd+ and in the lower part is GPSTest (https://play.google.com/store/apps/details?id=com.android.gpstest&hl=de). As you can the that number of the widget corresponds only to the GPS and GLONASS satellites. There are several other satellites in the lower part not displayed but you can see at least 6 Galileo satellites.

![osmand-and-satellites-number](https://user-images.githubusercontent.com/28760548/72913632-b956e300-3d3d-11ea-87d7-53fd93f9b9b1.png)

I know that there are enough (displayed) number of satellites in this case. But sometimes I see a number of 4 satellites and wonder about the accuracy of the position and then I see that a lot more satellites are really used.

**Comment by vshcherb** [comment]
There is a different API provided for devices since Android N, so it could be fixed only for these devices
