### ISSUE TITLE
Wrong city shown for address

### ISSUE THREAD

**Issue by chrismacr** [osmandapp/Osmand#8300]
OsmAnd version: 3.5.5
Android version: 9
Phone: Samsung Galaxy S8

Offline maps used. Map file used: Canada Alberta. Date shown: Dec 31, 2109
I also went to updates and manually updated map on Jan 22, 2020

There are several locations on the map that have the wrong town displayed on OsmAnd. They are correct on openstreetmap.org as far as I can tell.

<img src="https://i.imgur.com/daihLKT.jpg" alt="" class="GeneratedImage">

[https://www.openstreetmap.org/way/167996254](url)

This supermarket should be listed as city Lloydminster but it displays Lashburn. There are a few places in this area that are like that.

**Comment by vshcherb** [comment]
![image](https://user-images.githubusercontent.com/1042025/82230989-c8852080-992c-11ea-9835-15beca3ce029.png)
New maps have it correct
