### ISSUE TITLE
'General logging interval / Always ask' is broken

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#8303]
The 'Always ask' selection seems not accepted when selected, i.e. it does not reset if you had once selected the 'Remember my choice' checkbox for the logging interval.

**Comment by sonora** [comment]
PS: Looks like the menu in its new location under Configure Profile / Trip recording is still missing the Always ask option entirely.

**Comment by dmpr0** [comment]
Yes, we lost "Always ask" option in Loggin interval dialog. 
We will need to get it back, then rename "Remember my choice" to "Always ask" in the dialog that appears after taping on GPX Rec widget and show this selection in Login interval dialog in plugin settings.
