### ISSUE TITLE
Night build issue: arriving at an intermediate destination, announced I had arrived at my previous destination

### ISSUE THREAD

**Issue by jfburke3** [osmandapp/Osmand#8317]
What version of OsmAnd are you using, on what device and Android/iOS version?

Night build 3.5.6#28803m, released 2020-01-22.

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

Your offline maps

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.

US Georgia, US Florida, dated 31-Dec-2019, with OSMLive enabled (this is my "test everything" phone)

__*In case of wrong routing:*__

Tell us whether you have used OsmAnd's in-app offline routing, or any online routing provider like YOURS, OpenRouteService or OSRM.

Your in-app offline routing

What routing profile is chosen in OsmAnd app? (car, bike, pedestrian, fastest or shortest)

Car profile

-----

I set up a route with multiple intermediate destinations, the last of which was a gas station in Tifton, Georgia.  When I arrived at it, OsmAnd announced that I had arrived at my intermediate destination "East Seward Street," which was my *previous* intermediate destination in Tampa, Florida.

I don't think the specific locations are necessary to reproduce this, but I'll go get you OSM links if you really want them.

What might be relevant, though, is this:  I'd set up the route before starting to drive, with 4 or 5 intermediate destinations.  After arriving at the 2nd one (I think), I added a new intermediate destination to go to next.  I somehow added it as my final destination instead, at first.  I changed my final destination back to where I was going, but forgot that OsmAnd doesn't clear intermediate destinations when you change the final one, so I then re-added all of my remaining intermediate destinations from my search History.  Off the top of my head, I don't recall if I added them  in reverse order as new First Intermediate destinations, or in forward order as new Last Intermediate destinations.  I realized what I'd done when OsmAnd announced that my trip was now 1,400+ miles, instead of just under 500 miles.  I then cleared out the duplicate intermediate destinations--I *think* I removed them from the beginning of the list rather than from the end.

Clearly, somewhere in the drive, OsmAnd didn't remove one of my intermediate destinations from the array, but I'm not sure if there's just a simple bug that caused that, or if my adding/deleting intermediate destinations revealed a more complex issue.

**Comment by vshcherb** [comment]
That's quite tricky situation which caused probably by limitation of long routes. Probably we are going to use "help" points instead of "intermediate" so user can help to calculate route faster instead of dealing with intermediate points on the road

**Comment by jfburke3** [comment]
Just a note that I haven't seen this happen again.
