### ISSUE TITLE
GPX files issue

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8325]
GPX routes, created in Basecamp, cannot be used for navigation. 
[Casa a Sabic Innovative Plastics (2).gpx.zip](https://github.com/osmandapp/Osmand/files/4115882/Casa.a.Sabic.Innovative.Plastics.2.gpx.zip)
[Torla-Ordesa a Gavarnier (2).gpx.zip](https://github.com/osmandapp/Osmand/files/4115883/Torla-Ordesa.a.Gavarnier.2.gpx.zip)
[Casa a Albarracín (2).gpx.zip](https://github.com/osmandapp/Osmand/files/4115885/Casa.a.Albarracin.2.gpx.zip)

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/Osmand/issues/8284
