### ISSUE TITLE
Map language issue in Hebrew

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd#8326]
When searching for the places in Hebrew, the English option is displayed.

צומת הערבה 

<img src="https://user-images.githubusercontent.com/50198677/73157570-11993680-40ea-11ea-8d0e-9fe18337756b.png"  width="300" height="auto"/>

**Comment by dmpr0** [comment]
Fixed

<img src="https://github.com/osmandapp/OsmAnd/assets/9365308/91a5b930-e699-41c2-a371-28bc084f1149"  width="300" height="auto"/>
