### ISSUE TITLE
[Feature request] Add Red Light Camera Alert

### ISSUE THREAD

**Issue by CarlosBrys** [osmandapp/OsmAnd#8339]
Can you add an alert to warn of the presence of red light cameras, just like it does with radars?
The red light control cameras are mapped with relations just like radars.
It would be important to receive an alert about it.

**Comment by breversa** [comment]
Just for my information, what’s a red light camera ?

**Comment by CarlosBrys** [comment]
> Just for my information, what’s a red light camera ?

A camera that takes a picture when a vehicle crosses a intersection with traffic signal that is with red light.

**Comment by CarlosBrys** [comment]
![image](https://user-images.githubusercontent.com/6495550/75284184-09204280-57f3-11ea-8815-14ee65368fee.png)

**Comment by breversa** [comment]
Of course, silly me. Thank you !

**Comment by Duglof** [comment]
There is no progress on this subject,
to get an alert for a red light camera, the best solution is to put a relation of a speed camera with OpenStreetMap ...

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/4291

**Comment by jfburke3** [comment]
> There is no progress on this subject, to get an alert for a red light camera, the best solution is to put a relation of a speed camera with OpenStreetMap ...

Except they aren't speed cameras.  They solely enforce red-light violations.  We don't need a "speed camera" alert when that isn't it.  It would only confuse a driver.

**Comment by Duglof** [comment]
@jfburke3 
I understand, but:
1 - How should you tag them on openstreetmap ?
2 - Will we have an alert with OsmAnd ?
P.S. A bad alert is better than no alert
