### ISSUE TITLE
Speed limits dissappear

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd#8353]
This issue occurs along the US 70 road when driving from Smithfield to Clayton. 
E.g at
35.51623° N, 78.35634° W
35.51860° N, 78.35817° W
35.52920° N, 78.36552° W
35.53242° N, 78.36941° W

**Comment by raycock** [comment]
I have done some testing along this road and have found a pattern to this issue. If you are just driving without a route to destination put into the GPS, the speed limit displays correctly. Once a route is put in the GPS, the speed limit disappears and does not display. This is occurring on IOS 13.3 on IPhone XS Max. This issue needs to be addressed.

**Comment by katerynakocherhina** [comment]
The speed limit is displayed until the route is built. 
The issue occurs from 35.606859 -78.359034 to 35.627582 -78.399160

**Comment by JustACasual** [comment]
Hi, using the app on android and in  Germany, so not sure if this is the exact same issue, but my speed limit display is also gone.
Had it fixed by uninstalling, reinstalling, importing settings -> speed limits are shown again
But after a short time, they are gone again :(

Can I help in investigation somehow? The speed limits are currently gone, should I reinstall or keep the situation for debugging?

Thanks for your great work!

**Comment by sonora** [comment]
When you say "the speed limit display is gone", do you mean
- the speed limit widget does not show (top right or top left, wherever you configured it to be visible), or
- there is no pop-up warning (lower left corner) once you are above the speed limit,

or both?

Also, does this happen primarily on long stretches of straight highway?

**Comment by JustACasual** [comment]
Both do not display, but I especially miss the speed limit widget in the right panel.
I think it is gone for good, does not matter how long the route I am traveling.

**Comment by scaidermern** [comment]
Are you using the native navigation or are you following a third party GPX track?

**Comment by JustACasual** [comment]
Ah now I found something. As you were focusing on the navigation so much, I tried switching the navigation method. 
And if I use the offline navigation, the speed limits are displayed!
I indeed switched to online routing at some point but didn't make the connection.
I thought the speed limits were in the map material and not the routing data?

Thanks already @scaidermern

**Comment by scaidermern** [comment]
> I thought the speed limits were in the map material and not the routing data?

With online routing the offline maps are mainly used for rendering but not so much for other things. 

You could download the online calculated GPX track and let OsmAnd attach it to the roads. Afterwards it should feel like native routing.

**Comment by vshcherb** [comment]
I think this issue need to be closed cause it's outdated... 
> ticket to attach tracks from online routers to the roads. 
We only support it with GPX routing actually, no it was never requested actually. So new ticket should be open in that case.

**Comment by scaidermern** [comment]
> > ticket to attach tracks from online routers to the roads.
>
> We only support it with GPX routing actually, no it was never requested actually. So new ticket should be open in that case.

-> #15139
