### ISSUE TITLE
OsmAnd very slow map rendering on Pixel 3a (GrapheneOS)

### ISSUE THREAD

**Issue by qubecub** [osmandapp/Osmand#8355]
Hi,
I've recently flashed Google Pixel 3a (2019) with the latest release of GrapheneOS.
The first app I tested on the new OS was OsmAnd maps. To my surprise map rendering was painfully slow, much slower than on older Samsung S7 phone (2016!).

For high-density urban areas/cities Zooming-in and zooming-out takes up between 5-10s just to respond and start drawing lines and shapes. I have to admit this comes as unexpected surprise considering the Pixel 3a is 2019 model. 

Is there anything that could be done to accelerate zooming in/out on OsmAnd on Pixel 3a?

**Comment by vshcherb** [comment]
Obviously 5-10s is really slow and comparing to S8-S10 it is on average 10x times slower. Please check that you are not running it in Safe mode, that Zoom Magnifier is 100% and there are no unexpected settings. Probably reinstall should fix it. You can also enable Debug information and check how much slower it is comparing to S7 for instance.

On our side we didn't experience any degradation recently
