### ISSUE TITLE
Cebuano wikipedia in English articles

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8356]
In 3.5.5, the Cebuano wikipedia articles appear as English ones. The issue occurred in Ireland, 52.11528, -9.75194. Wikipedia: https://ceb.wikipedia.org/wiki/Dromin_Hill.

**Comment by rcurtin** [comment]
This also occurred in the US Arizona region, point of interest: https://ceb.m.wikipedia.org/wiki/Historic_Railroad_Avenue_Park

**Comment by rcurtin** [comment]
I was able to work around the issue by using the Wikipedia English overlay instead of the Wikipedia overlay. :+1:

**Comment by xmd5a2** [comment]
These articles doesn't contains english versions, only cebuano and other.
