### ISSUE TITLE
Release the OsmAnd apk file here on GitHub 

### ISSUE THREAD

**Issue by USB3-2-10Gbit** [osmandapp/Osmand#8357]
Hello thank you for the great app.

When you release a new version. Can you add the apk file under GitHub releases?
https://github.com/osmandapp/Osmand/releases

**Comment by USB3-2-10Gbit** [comment]
i find it clearly comfortable because i use a GitHub client on Android.

**Comment by dmpr0** [comment]
We store release version on our server, you can find all releases here with release notes https://osmand.net/downloads or here only links https://download.osmand.net/osm-releases/

**Comment by USB3-2-10Gbit** [comment]
@dmpr0 
thanks but many users do not know the site you can add these links to readme

So at the very front of the main page.
