### ISSUE TITLE
GrapheneOS - no navigation voice on Google Pixel 3a 

### ISSUE THREAD

**Issue by qubecub** [osmandapp/Osmand#8362]
Following my 'OsmAnd slow performance on Pixel 3a running GrapheneOS' - #8355

I've came across another isssue: There is no OsmAnd navigation voice on Pixel 3a with GrapheneOS. 

I've got all default OsmAnd settings, and double checked that TTS voices are properly selected and sound enabled, OsmAnd doesn't do navigation voice at all. Just keeps silent.

**Comment by dmpr0** [comment]
Hello! Does it have TTS Engine installed?

**Comment by qubecub** [comment]
I suppose so. This is full paid version of OsmAnd+ and as installation comes with everything as a package - including TTS engine. 
I didn't have to install it on other phones I used so I'm guesssing TTS engine is installed by default. 
Please advise if that's not a case.

**Comment by dmpr0** [comment]
By default, devices OS has TTS Engine installed, in most cases if TTS doesn't work, we recommend to install Google TTS Engine.

**Comment by qubecub** [comment]
Thank you for your comment. I think that's probably the case. GrapheneOS might not come with preinstalled TTS engine to synthesize navigation voices. 

Any suggestion of open source TTS eninge I could use? (in place of google one?)

But I though OsmAnd also comes with pre-recorder navigation voices, as opposed to text-to-speach-synthesized. 
How can I enable it instead?

**Comment by qubecub** [comment]
OsmAnd "Voice prompt recorded" is not available as an option on my Pixel 3a phone? 
But is it on my other phone, same version of OsmAnd. 
How to enable recorded prompts on Pixel 3a?

**Comment by enyaw-wang** [comment]
Fellow grapheneOS user here. I don't see the voice navigation panel either and I installed Google TTS
