### ISSUE TITLE
Enable "direct to" navigation for boat profile. 

### ISSUE THREAD

**Issue by StrikeLines** [osmandapp/Osmand#8374]
When using OSMand in boat mode, the "directions" navigation always fails with the message "Could not calculate route: Point of departure too far from the nearest road." 

Direct-to-point navigation is a critical and frequently used feature for marine users. 

The traditional behavior of marine GPS units is to draw a navigation line from the position at the start of navigation, to the specified destination point for the user to follow. That line does not move during the course of navigation, and it serves as a reference line for the user to follow, correcting for drift from current or wind. 

During navigation, the GPS typically calculates ETA, time to destination, distance to destination, and course to destination based on the current speed and heading of the boat.

**Comment by vshcherb** [comment]
Now new Routing service (Direct-to-point) is enabled to test
![image](https://user-images.githubusercontent.com/1042025/74680937-63e9e680-51c2-11ea-9335-b9de2277720c.png)

**Comment by vshcherb** [comment]
The point on the line is a virtual point to show the distance (it is not a projection on the line) but a point that has the same distance as current location to the finish point. 
So it is easy to measure the progress and it is possible to use measurements tool to get correct distance
