### ISSUE TITLE
Feature request: Add more Infos about an object.

### ISSUE THREAD

**Issue by Mannshoch** [osmandapp/Osmand#838]
Two Ideas to get them:
- Add a Underline to get a description about lines and symbols I see.
- Tap on an Object and pop the Title of them on the right sight of the Compass on top-left in. Give it the ability to get more Information if I tab on the title.

Last time I had to use Osmand I got the Problem that I do not know what the meaning of a Line was. And an other Time I wished to get the Name of a Bus-Station.

**Comment by DFyson** [comment]
Being able to select objects to get more information would be really handy. Objects can contain alot more useful data than is displayed. For example phone number, opening hours, website, and description for buisnesses.

As for symbols, the user should be able to pull up a map legend for the displayed map style while offline. Currently it appears the user has to go to the website to see it and only for the default style.

**Comment by sakudo** [comment]
As a "quick" solution, it would be nice if in the help section (settings), the map legend (of the Osmand default style) would be stored offline. Currently, you need to be online to retrieve the map legend.

**Comment by therob84** [comment]
I do also vote to include an offline legend, most optimal adjusted only to elements used in the current displayed map and the current rendering style.

Each serious map/routing-software should provide inline-explanation of the used symbols, as also every print-map provides it!

About more infos of the objects I would also link to #2232

**Comment by homersimpsons** [comment]
+1

**Comment by Torvin** [comment]
This drives me crazy. I couldn't believe there's no way to view object's properties rather then search for it first.

**Comment by sonora** [comment]
Fixed in latest releases.
