### ISSUE TITLE
Miscalculated layout height (2 issues)

### ISSUE THREAD

**Issue by MadWasp79** [osmandapp/Osmand#8380]
https://www.openstreetmap.org/way/146062330#map=17/48.03313/9.10500
![image](https://user-images.githubusercontent.com/13146346/73653699-79bfbd80-4692-11ea-8c0b-e489127f6202.png)

**Comment by vshcherb** [comment]
![image](https://user-images.githubusercontent.com/1042025/74143260-cbb89400-4bfa-11ea-9ac3-07c00e55f1bc.png)
