### ISSUE TITLE
Strange crossroads lanes display when navigating

### ISSUE THREAD

**Issue by RussianFox** [osmandapp/Osmand#8390]
![photo_2020-02-05_15-15-59](https://user-images.githubusercontent.com/11329995/73841132-f2f21880-482a-11ea-8560-9aceb8d3dfff.jpg)
![photo_2020-02-05_15-16-02](https://user-images.githubusercontent.com/11329995/73841133-f4234580-482a-11ea-86ee-dbe65c8510f0.jpg)

Coordinates: 59.95412 30.34748

I think it would be better if it looked like this
![Untitled](https://user-images.githubusercontent.com/11329995/73922451-3bb4da80-48da-11ea-801b-e012cdd8ea83.png)

**Comment by naoliv** [comment]
How is the data in OSM?
Maybe this part is represented in OSM with 4 straight ahead lanes.

**Comment by RussianFox** [comment]
This place in real
![image](https://user-images.githubusercontent.com/11329995/73921344-3060af80-48d8-11ea-9e8d-8ed1aa8ed603.png)

Link to node in OSM https://www.openstreetmap.org/node/230312

Directly road is mapped with **lanes=3**, link is mapped with **lanes=1**. Without **turn:lanes**

**Comment by petersohn** [comment]
Adding proper turn:lanes tags to the map would solve this issue. This is an error in the map, not the app.

**Comment by naoliv** [comment]
> Adding proper turn:lanes tags to the map would solve this issue. This is an error in the map, not the app.

But there are no arrows, as you can see at the picture above.
Adding `turn:lanes=none|none|none" shouldn't help at all, I guess.

**Comment by petersohn** [comment]
I think that `turn:lanes=through|through|through;right` or something similar would help, depending on the traffic signs.

**Comment by naoliv** [comment]
`turn:lanes=through|through|through;right` would be the logical choice, yes, but I wouldn't include values that are not present either on the highway or on signs.

@RussianFox are there any signs before this exit that include some directions?

**Comment by RussianFox** [comment]
@naoliv No, there aren't

**Comment by vshcherb** [comment]
I would disagree and put "turn:lanes=through|through|through;right" to OSM, assumption "Truth on the ground" doesn't say it should be only on signs, it could be also validated by real traffic control. 
We don't have any tag "routing:turn:lanes" so we could safely use it (same applies to maxspeed logic, we don't need to see sign to assume which maxspeed the road has).
