### ISSUE TITLE
Make full support for Navigation of OsmAnd-GPX 

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#8404]
We need to support all features that provides OsmAnd Offline routing with OsmAnd GPX Navigation if GPX is created by OsmAnd i.e.:
1. Turn lanes widget
2. Max speed limit alert
3. Give way / Stop signs
4. Exit / Destination / Ref information
5. Proper turn announcements
6. To be defined

**Comment by scaidermern** [comment]
Is this the same as #3908? Or does this only apply to GPX tracks created by OsmAnd but not for third-party GPX tracks?

**Comment by vshcherb** [comment]
@scaidermern this is different issue cause here we will just save / load special data "OsmAnd GPX"
