### ISSUE TITLE
API Issue on Android: START_GPX_REC/STOP_GPX_REC

### ISSUE THREAD

**Issue by ShelleyLake** [osmandapp/Osmand#8406]
Dear developers, I have a problem with one of your APIs (OsmAnd+ 3.5.5 Android).

I would like to create two shortcuts on the start screen to quickly start and stop recording GPS data.
In the browser I've added two favorites with the URIs indicated below and pinned them to the start.
```
osmand.api://START_GPX_REC
osmand.api://STOP_GPX_REC
```

So far so good: tipping on the links, the browser opens shortly and it fires the corresponding _intent_ which start/pauses the recording of GPS data.

My issue is: when STOP_GPX_REC is called, the recording is PAUSED and there is no way for me to really STOP and SAVE the recorded data: I still have to manually click the corresponding button in the OSMAND notification...

Could you pls tell me where I am wrong? Or is it missing an API (something like SAVE_GPX_REC) ?

Many thanks.

**Comment by vshcherb** [comment]
We need to add SAVE_GPX / CLEAR_GPX intent
