### ISSUE TITLE
Crash with latest tts-voices

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#8411]
We introduced a bug in some tts-voices, lately, I suspect https://github.com/osmandapp/OsmAnd-resources/commit/65279538d7daf0fe42ea8002985e55735e984f9e. 

Looks like an issue passing exit numbers somehow: [exception.log.txt](https://github.com/osmandapp/Osmand/files/4172261/exception.log.txt)

**Comment by sonora** [comment]
Yes, the commit I referenced is faulty, see `function take_exit`, argument needs to be `exitString`.

@vshcherb : Can anyone re-do it, or should I?

Also: For all js-files we now newly upgraded to support exit numbers, could we please also upgarde the funtion header I had once introduced to reflect https://github.com/osmandapp/OsmAnd-resources/blob/a4ea1a1a1e14b19afc23fb2946f437c28f26cff4/voice/en/en_tts.js#L10

**Comment by sonora** [comment]
I fixed the main issue, i.e. the argument mismatch crashes, in https://github.com/osmandapp/OsmAnd-resources/commit/e98a727acee13ef7ccbdd2975cbef34c1470b176.

I leave this issue open so we test now.

There are definitely further issues, I e.g. still get "undefined" sounds in some languages. I also notice the code we use for exit prompts uses "on"/ "onto" etc., but I do not think all of these are in the dictionary section of every language.

**Comment by sonora** [comment]
en and de fixed ok now, see https://github.com/osmandapp/OsmAnd-resources/commit/951032911a49f75199781f705d900505ee96b77e

**Comment by sonora** [comment]
I have tested this is a number of languages I can judge and it works great. At least no crashes or obvious 'undefined' errors anymore. I guess we can close this issue now, the rest is country-specific fine-tuning.

**Comment by vshcherb** [comment]
Thanks @sonora
