### ISSUE TITLE
Incorrect German translation in update confirmation dialog

### ISSUE THREAD

**Issue by cyclingcat** [osmandapp/Osmand#8414]
Hi there,

the German update confirmation dialog shows the misleading word "Aktualisierungsintervall" (which means "Update interval") instead of "Aktualisieren" ("Update"). The "Update" button itself shows the correct word "Aktualisieren". See the screenshots below.

This translation quirk has probably been introduced just recently, perhaps with the latest app update. Being a long-term OsmAnd user I have never seen this before, but it's reproducible on both my Android 5.1 smartphone and my Android 8.0 tablet (OsmAnd~ 3.5.5 from F-Droid).

English:
![Update_English](https://user-images.githubusercontent.com/32601012/74081655-c9ff9c80-4a51-11ea-8232-28cb2a8e85fe.png)

German:
![Update_German](https://user-images.githubusercontent.com/32601012/74081794-3202b280-4a53-11ea-8549-63973004ea4b.png)

The cycling cat

**Comment by sonora** [comment]
Looks like it's fixed?

**Comment by cyclingcat** [comment]
No, it's not:

The German "Aktualisieren" means "Update"
The German "Aktualisierungsintervall" means "Update interval"

So I'd suggest to simply replace "Aktualisierungsintervall" with "Aktualisieren" in the German version of this confirmation dialog (the string the arrow points to). The English dialog doesn't show "Update interval" but "Update" either!

The cycling cat

**Comment by sonora** [comment]
Yeah, it's fixed, I just checked. Should be in the next release. - Thx
