### ISSUE TITLE
Alternative Control Scheme for Trip Recording

### ISSUE THREAD

**Issue by Ungoose** [osmandapp/Osmand#8415]
Currently, after trip recording starts, three options are available to the user: Stop GPX logging”, Start new segment, and Save current track. So when I am done recording, I go the following route: tap menu-tap Stop GPX logging-tap menu-tap Save current track. And when I want to cancel recording, I go the same route + delete the file afterwards. 

I suggest the following options instead:

Save (stops recording and saves GPX file)
Pause (works like Stop GPX logging)
Cancel (stops recording and does not save GPX file)

or

Finish (stops recording and saves GPX file)
Save (stops recording and does not save GPX file)
Pause (works like Stop GPX logging)
Cancel (stops recording and does not save GPX file)

In any case the new menu simplifies the process of saving and canceling and uses fewer words for menu entries.

**Comment by vshcherb** [comment]
This is a duplicate issue of "Clear current recording track" which is coming this release 3.6

**Comment by Ungoose** [comment]
This does indeed solve the issue of clearing the current recording track. However, what I'm primarily after is reducing the procedure of saving the track from two interactions with the menu to one. Controlling the plugin is already a little inconvenient (since menus are positioned in different parts of the screen), and having to go do it twice makes things worse, especially when on the move. Tapping the menu a second time may be necessary to unpause a paused recording, but why make users go this route twice for other actions actions like saving or canceling?

**Comment by scaidermern** [comment]
I agree. It would be nice to have _one_ action for stopping recording _and_ saving the track. This is a very frequent action.

**Comment by Ungoose** [comment]
There are a couple of other advantages to the proposed scheme. 
First, “Save-Pause-Cancel” is far less wordy, which would declutter the screen. It would also allow substituting the descriptions for recognizable symbols (e.g. IEC 60417 media control symbols) and make the app less language-dependent. 
Second, it would allow using one menu instead of two by changing “Pause” to “Unpause” when the recording is stopped. 

I would also suggest relocating the controls from the center to the right side of the screen (below the widget). Together with the “two taps instead of four,” this change will be a tremendous advantage for one-handed use of the app. Here is an excellent example of such a scheme from Omni Notes menu, which allows for both a clearly visible icon and a concise description without obstructing the display:
![Screenshot_20200309-151301_1](https://user-images.githubusercontent.com/59472193/76617013-febdb280-652d-11ea-93ec-b7b03d2c3f47.jpg)
![Screenshot_20200309-151305_1](https://user-images.githubusercontent.com/59472193/76617019-02513980-652e-11ea-9ef6-11fd63d24fe2.jpg)
