### ISSUE TITLE
Osmand Live and Subway entrance

### ISSUE THREAD

**Issue by 532910** [osmandapp/Osmand#8416]
The Subway entrance https://www.openstreetmap.org/node/2061520416 was marked improperly:
![image](https://user-images.githubusercontent.com/14617699/74099264-cbed5c80-4b32-11ea-8fc8-ee5c438d5f0d.png)

Should look so:
![image](https://user-images.githubusercontent.com/14617699/74099258-b841f600-4b32-11ea-8ab3-8b652db934f4.png)

I've corrected en error, data was fetched via Live update, but the icon was not updated:
![image](https://user-images.githubusercontent.com/14617699/74099293-0eaf3480-4b33-11ea-9da8-d85d48c33fb1.png)

But LightRS looks fine:
![image](https://user-images.githubusercontent.com/14617699/74099345-8b421300-4b33-11ea-81d7-d59ca2a3d754.png)

Right now, after full map update it shows the entrance correctly.

**Comment by xmd5a2** [comment]
Issue is related to unsupported in OSM Live instructions like
```<entity_convert pattern="tag_transform" from_tag="railway" from_value="subway_entrance" **if_region_name="leningradskaya,sankt-peterburg"** to_tag1="railway" to_value1="subway_entrance" to_tag2="subway_region" to_value2="spb"/>
```

**Comment by xmd5a2** [comment]
Fixed
