### ISSUE TITLE
TTS speech rate

### ISSUE THREAD

**Issue by 532910** [osmandapp/OsmAnd#8418]
My TTS speech rate is fast enough:
![image](https://user-images.githubusercontent.com/14617699/74099492-70709e00-4b35-11ea-9e3a-0890bb329d31.png)

But when I start Osmand it ignores this setting and says messages with normal speed. To fix it, I need to kill it (with the long back) and start it again. After restart it works fine. Some version ago it works fine. Device LNGOS 16 on android 9 op3t, Osmand 3.5.5 from f-droid.

**Comment by comradekingu** [comment]
Probably it prefers the system TTS settings, like for apps that have equalizers.

**Comment by sonora** [comment]
Can you please test a new version of OsmAnd, there were some changes in recent months which may behave fixed this.

In principle OsmAnd's code has no interface to set the pitch or the speech rate, neither does it touch any of these. The system settings should be obeyed, but they are likely only read when OsmAnd initializes the TTS engine, i.e. upon the first use of TTS in each app session, or when you change the TTS language in OsmAnd. You can test the latter e.g. via the development plugin's 'Test voice prompts' setting.

**Comment by sonora** [comment]
This is an old thread, but for what it's worth: The accessibility plugin in OsmAnd has its own speech rate setting, which is observed while its active, I think. May ne a useful solution where needed.
