### ISSUE TITLE
Sometimes turns are not shown

### ISSUE THREAD

**Issue by 532910** [osmandapp/Osmand#8419]
![image](https://user-images.githubusercontent.com/14617699/74099716-9ac35b00-4b37-11ea-8cca-eaeff35ea109.png)

Trying to simulate it work fine:
![image](https://user-images.githubusercontent.com/14617699/74099730-bb8bb080-4b37-11ea-8db0-7bddcc1d4e31.png)

**Comment by scaidermern** [comment]
Possibly a duplicate of #8164?

**Comment by 532910** [comment]
Looks so.
