### ISSUE TITLE
buggy campsite in Portugal

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#8468]
- no osm link, no other details
- actions: can't "EDIT poi", only "CREATE poi" menu present
For me it lools like buggy map creation.
map Portugal january

https://www.openstreetmap.org/relation/1728415
https://osmand.net/go?lat=40.53432207839902&lon=-7.275749444961548&z=17
40.53432° N, 7.27575° W
campsite data look ok.
Following dara are copied from vespucci:

name=Parque de Campismo Municipal da Guarda
stars=2
tourism=camp_site
type=multipolygon

![Screenshot_20200214-193251_OsmAnd~~01](https://user-images.githubusercontent.com/18628183/74557791-3c481380-4f61-11ea-8275-5612bdb56258.jpg)

**Comment by scaidermern** [comment]
Looks very similar to #6497 which should be fixed in the newest version.

**Comment by pebogufi** [comment]
@scaidermern @MadWasp79 
The tests above are made with version 2020-02-14.
MadWasp79 closed https://github.com/osmandapp/Osmand/issues/6497 14 days ago, so it should have been already ok.
With version of totay (2020-02-17) 3.5.6#29011 i tested again, no change: type is **textual** shown as location instead as campsite, but icon shows campsite. This is funny - most campsites are shown ok.

**Comment by scaidermern** [comment]
> type is **textual** shown as location instead as campsite, but icon shows campsite.

This is the same behavior as in #6497, see [your post](https://github.com/osmandapp/Osmand/issues/6497#issuecomment-546690296) and [my post](https://github.com/osmandapp/Osmand/issues/6497#issuecomment-499073474). So it looks like #6497 is still not fixed.

**Comment by vshcherb** [comment]
This is totally different issue that requires editing "Multipolygons"

**Comment by MadWasp79** [comment]
Yes, there was an issue with finding the correct POI coordinates for multipolygon relations, which should be fixed in new (March) maps.

**Comment by vshcherb** [comment]
Fixed
