### ISSUE TITLE
USA Maine: Address not found by search

### ISSUE THREAD

**Issue by blackboxlogic** [osmandapp/Osmand#8471]
To reproduce:
Open OsmAnd, download map for "USA Maine", search, by address, for "48 Free Street Portland Maine".

Expect to find https://www.openstreetmap.org/node/7171975988
(I have verified that this node exists on my device and has the correct tags)
 
Result:
Search results don't show that address.

More details:
I do find the node I'm looking for if I change my search to "48 Free Street" (without the city). It looks like you're using something to determine the municipality instead of the addr:city tag. Maybe that something else could be a fallback only when addr:city is missing?

Question:
Is this a data error? A search algorithm error? Or user error?

Thank you,
-Alex

**Comment by vshcherb** [comment]
Problem with this commit https://github.com/osmandapp/Osmand/commit/78e7bb4d3d7ae61759c68be3eea8cdc7d27d60a4. It should be added to the tests and fixed.

**Comment by vshcherb** [comment]
Without it "48 Free Street Portland" will work and "48 Free Street Portland Maine" will still fail to identify trying to identify "Maine Street"

**Comment by blackboxlogic** [comment]
I looked at the change. it seems you do not expect the user to include the state when searching for an address. I'll keep that in mind.
Thank you for fixing this issue!

**Comment by vshcherb** [comment]
@blackboxlogic sorry it is not yet fixed, we've just identified 1 reason. Yes, that issue will be split in 2: 1) support state as part of request (another issue) 2) fix "48 Free Street Portland" (it is a regression cause it was working in 3.3 I guess)
