### ISSUE TITLE
Unable to calculate route when OsmAnd Live is enabled

### ISSUE THREAD

**Issue by travnick** [osmandapp/Osmand#8472]
OsmAnd~ 3.5.5, Xiaomi Redmi 4x, offline routing.

Since yesterday, I observed that OsmAnd is unable to calculate route - longer than 7km, as far as I was able to test. It fails every time, so I find this bug quite critical, since the navigation app is not able to navigate.
One thing I observed once - after the phone restart, it succeeds to calculate route but only once (didn't test further restarts).

There is a log from the exact try to calculate one (I hope it's enough).
I used car profile.
```
02-15 17:37:01.242 17146 20329 I net.osmand: RouteProvider Start finding route from Location[mProvider=map,mTime=0,mLatitude=50.27577590942383,mLongitude=18.654178619384766,mHasAltitude=false,mAltitude=0.0,mHasSpeed=false,mSpeed=0.0,mHasBearing=false,mBearing=0.0,mHasAccuracy=false,mAccuracy=0.0,mHasVerticalAccuracy=false,mVerticalAccuracy=0.0 to Lat 50.133495 Lon 18.541338 using OsmAnd (offline)
02-15 17:37:01.243 17146 20329 W net.osmand: RouteProvider Use 294 MB Free 1.1432495 of 75.12676 max 384.0
02-15 17:37:01.385  2541  4371 W MiuiPerfServiceClient: interceptAndQueuing:17146|net.osmand.plus|174|112|unknown|null|net.osmand.plus/net.osmand.plus.activities.MapActivity|19509732622608|Slow handle traversal|3
02-15 17:37:01.443 17146 20329 I net.osmand:native: Start point was found 33916450 [Native]
02-15 17:37:01.474 17146 20329 I net.osmand:native: End point was found 529504759 [Native]
02-15 17:37:01.860  2541  4371 W MiuiPerfServiceClient: interceptAndQueuing:17146|net.osmand.plus|338|286|unknown|null|net.osmand.plus/net.osmand.plus.activities.MapActivity|19518234922866|Slow main thread|2
02-15 17:37:12.967 17146 20329 W net.osmand:native: [Native] Result visited (visited roads 27193, visited segments 55279 / 44012 , queue sizes 881 / 563 ) 
02-15 17:37:12.967 17146 20329 W net.osmand:native: [Native] Result timing (time to load 2.292, time to calc 11.492, extra timer 0.000, loaded tiles 1083) 
02-15 17:37:12.967 17146 20329 W net.osmand:native: [Native] Memory occupied (Routing context 38646 Kb, search 2349 Kb)
02-15 17:37:13.130 17146 20329 I net.osmand:native: Routing calculated time distance 1413.089233
02-15 17:37:13.876 17146 20329 I net.osmand: RoutePlannerFrontEnd Native routing took 12.502 seconds
02-15 17:37:13.922 17146 17146 I Toast   : Show toast from OpPackageName:net.osmand.plus, PackageName:net.osmand.plus
02-15 17:37:14.023 17146 20329 I net.osmand:native: Start point was found 33916450 [Native]
02-15 17:37:14.054 17146 20329 I net.osmand:native: End point was found 529504759 [Native]
02-15 17:37:25.734 17146 20329 W net.osmand:native: [Native] Result visited (visited roads 27193, visited segments 55279 / 44012 , queue sizes 881 / 563 ) 
02-15 17:37:25.735 17146 20329 W net.osmand:native: [Native] Result timing (time to load 2.290, time to calc 11.681, extra timer 0.000, loaded tiles 1083) 
02-15 17:37:25.735 17146 20329 W net.osmand:native: [Native] Memory occupied (Routing context 38646 Kb, search 2349 Kb)
02-15 17:37:25.897 17146 20329 I net.osmand:native: Routing calculated time distance 1413.089233
02-15 17:37:26.643 17146 20329 I net.osmand: RoutePlannerFrontEnd Native routing took 12.672 seconds
02-15 17:37:26.646 17146 20329 I net.osmand: RouteProvider Finding route contained 0 points for 25404 ms
02-15 17:37:26.659 17146 17146 I Toast   : Show toast from OpPackageName:net.osmand.plus, PackageName:net.osmand.plus
02-15 17:37:26.896 17146 17146 I net.osmand: SearchUICore Start shallow search <> API=<SearchHistoryAPI>
02-15 17:37:26.896 17146 17146 I net.osmand: SearchUICore Preparing search phrase <>
02-15 17:37:26.901 17146 17146 I net.osmand: SearchUICore Search phrase prepared <>
02-15 17:37:26.902 17146 17146 I net.osmand: SearchUICore Add search results resortAll=true removeDuplicates=true Results=196 Current results=0
02-15 17:37:26.902 17146 17146 I net.osmand: SearchUICore Sorting search results <> Results=196
02-15 17:37:26.902 17146 17146 I net.osmand: SearchUICore Search results sorted <>
02-15 17:37:26.902 17146 17146 I net.osmand: SearchUICore Filter duplicate results <> Results=196
02-15 17:37:26.904 17146 17146 I net.osmand: SearchUICore Duplicate results filtered <> Results=173
02-15 17:37:26.904 17146 17146 I net.osmand: SearchUICore Search results added. Current results=173
02-15 17:37:26.904 17146 17146 I net.osmand: SearchUICore Finish shallow search <> Results=196
```

**Comment by vshcherb** [comment]
There is 3.6.0 beta released today, please give a try . We don't reporduce that issue yet.

**Comment by travnick** [comment]
Is there anything I can help you with tracking this issue down?
Logs, debugging, code review of the part, where it may happen, other things?

**Comment by vshcherb** [comment]
It is really hard to tell, you can try to find when it start to happen https://download.osmand.net/night-builds/ (master-nb or default-nb) builds. So we can potentially identify which commit is responsible for that.

Though it will be hard to fix if we can't reproduce it. Usually we don't fix these issues unless we have like 10 different reporters

**Comment by travnick** [comment]
I've played around with the issue and I isolated one place:
this calculates correctly: https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=50.23763%2C18.63993%3B50.23740%2C18.63974#map=19/50.23752/18.63983
this one not: https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=50.23740%2C18.63974%3B50.23763%2C18.63993
this also causes an error: https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=50.23745%2C18.63978%3B50.23736%2C18.63971

I've OsmAnd Live enabled (not sure if it's possible to clear updated maps to check if some map update breaks the navigation)

**Comment by travnick** [comment]
@vshcherb I guess I finally got it:
The issue appears only when OSM Live is active:

1. Download Poland map Silesia
2. Route (the one mentioned in previous comment) calculates properly each time
3. Enable OsmAnd Live for Poland Silesia
4. When maps are downloaded the route calculation fails each time
5. When OsmAnd is disabled for Poland Silesia (so files in `live` directory are *removed*) route is calculated correctly back again.

@vshcherb please let me know if you are able to reproduce it now.

**Comment by travnick** [comment]
I've tested this scenario in OsmAnd~ 3.6.3
Currently, it's working. I'm unable to say if the fix arrived with code, or it's working because map updates.
