### ISSUE TITLE
Missing some street names in the detailed route

### ISSUE THREAD

**Issue by alrega** [osmandapp/Osmand#8476]
# Title

Missing some street names in the detailed route. The empty street names are also displayed in the top of the screen during navigation.

# Problem

The detailed route doesn’t display street names that follow roundabout exits. See turns at **1.59 km** and at **2.11 km** in image below.
Route is attached as file [2020-02-16.gpx.zip](https://github.com/osmandapp/Osmand/files/4210528/2020-02-16.gpx.zip)

![2020-02-16 Problem](https://user-images.githubusercontent.com/45489174/74610070-f3c75c00-5100-11ea-9e50-524538af1142.png)

# Reason

Let’s have a look at the roundabout at **1.59 km** from start point. In the below screenshot we can see the roundabout exits to one way road.

![2020-02-16 Roundabout](https://user-images.githubusercontent.com/45489174/74610073-f88c1000-5100-11ea-8c21-19d9ed75e49a.png)

I opened **OpenStreetMap** site (https://www.openstreetmap.org/edit#map=18/55.74180/37.86592) and selected roundabout exit to view its attributes. The selected object (https://www.openstreetmap.org/way/24686799#map=19/55.74197/37.86569) has no name (name is indicated using red box). 

![2020-02-16 Openstreetmap](https://user-images.githubusercontent.com/45489174/74610075-fde95a80-5100-11ea-800e-a57c8c14e71c.png)

# Resolution

Street name is evaluated in net.osmand.plus.routing.RouteCalculationResult#convertVectorResult, by checking the segment that follows a turn (in our case the roundabout exit). 

Why not to try to detect street name by checking several segments after turn? This approach is implemented in my fork of repo. I'll provide link after publishing changes. 

After applying the new approach I captured screenshot with detailed route once again.

![2020-02-16 Resolution](https://user-images.githubusercontent.com/45489174/74610078-02157800-5101-11ea-8031-1bfd25b1c71d.png)

**Comment by vshcherb** [comment]
This algorithms as discussed in Pull-Request should be definitely limited to look-ahead name probably with max to 50-80 meters
