### ISSUE TITLE
Mapillary illustration bug (increase resource limit?)

### ISSUE THREAD

**Issue by Aiurek** [osmandapp/Osmand#8481]
Lenovo Moto G4 plus, Android 7.0
OsmAnd+ 3.5.5, released 2019-11-28
May style: OsmAnd

Just switched on the mapillary layer and saw this pretty weird, jumpy behavior of vanishing and reoccurring mapillary footage lines. Haven't seen this before, whereby I'm using the mapillary layer frequently.

![video-2020-02-17-11-25-18](https://user-images.githubusercontent.com/27865200/74646247-be128980-5179-11ea-980d-33b3867ea855.gif)

**Comment by vshcherb** [comment]
Looks like you've used too many layers on your device, probably you can disable hillshade layer and get it working.

**Comment by Aiurek** [comment]
Just now I switched off hillshade layer and contour lines, but nothing changed :/ It still looks like in the GIF

**Comment by scaidermern** [comment]
I encountered the same issue recently without any overlay or underlay maps enabled.

**Comment by max-klaus** [comment]
Fix will be applied automatically after upgrade to the next version of the OsmAnd. In the meantime you may fix it manually: Go to Download Maps > Local > Online and cached tile maps and delete Mapillary raster / vector tiles. Then restart OsmAnd and these tile sources will be recreated with correct data.
