### ISSUE TITLE
Missing support for sport tag in bars/pubs

### ISSUE THREAD

**Issue by Aiurek** [osmandapp/Osmand#8482]
Currently there seems to be only the sport=10pin supported as a non-physical tag in combination with a physical tag like amenity=bar, amenity=pub or amenity=restaurant.
Darts, Table soccer, billiards,... are missing. At least those tags are not illustrated in OsmAnd, although present in the OSM data.
It'd be really nice to use OsmAnd search as a tool to find bars offering a certain type of sport, e.g. darts, more easily in an unknown city.

There are webpages which do have a fair amount of data, that can be implemented in OSM and illustrated in OsmAnd. Description tag can be used to add more info, like type of table soccer:
https://www.tischfussball.de/index.php?page=adressen

Would be really great and valuable. Was craving for a easy tool to find proper bars multiple times, until I realzied it'd be perfect to have OsmAnd for that :) 

E.g.: https://www.openstreetmap.org/#map=19/48.80782/9.54089
https://wiki.openstreetmap.org/wiki/Tag:sport=darts
https://wiki.openstreetmap.org/wiki/Tag:sport%3Dtable_soccer
https://wiki.openstreetmap.org/wiki/Tag:sport%3Dbilliards
What else is missing?

**Comment by vshcherb** [comment]
Will be fixed with #8483
