### ISSUE TITLE
Sport tag and multivalued (similar to cuisine)

### ISSUE THREAD

**Issue by Aiurek** [osmandapp/OsmAnd#8483]
![Bild1](https://user-images.githubusercontent.com/27865200/74654985-cecbfb00-518b-11ea-8cb5-18d11914af01.jpg)

Somehow related to #5192
Initially, proper tag support is required: #8482

Thx! :)

**Comment by vshcherb** [comment]
@xmd5a2  I think we should have already working approach with Suggestion #1 (similar to cuisine tag)

**Comment by Aiurek** [comment]
#6459

**Comment by ivanPyrohivskyi** [comment]
Test map:
[Poi_test2.obf.zip](https://github.com/user-attachments/files/16030073/Poi_test2.obf.zip)

Coordinates 48.8079423 9.5406507

**Comment by ivanPyrohivskyi** [comment]
Test only with new maps July 2024

**Comment by vshcherb** [comment]
bug in context menu - @dmpr0 provide more details please

**Comment by dmpr0** [comment]
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/d374469f-ac76-473b-a419-15c90eb88d37"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/b05f3e3a-9308-4c0b-8a1a-a3250a6888df"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/58f5a8c9-88fe-4568-b645-3b88846f2f24"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by ivanPyrohivskyi** [comment]
Map data is fine:
sport: sports_centre BeachMitte Lat 52.53342 Lon 13.385012 osmid=2214235474944  [ sport='soccer;beachvolleyball' ]  poi_additional:[ wheelchair_limited='limited'website='http://www.beachberlin.de/'phone='+49 177 2806861'wikidata='Q115744351' ] 
sport: beachvolleyball;soccer BeachMitte Lat 52.53342 Lon 13.385012 osmid=2214235474944  [ sport='sports_centre' ]  poi_additional:[ wheelchair_limited='limited'website='http://www.beachberlin.de/'phone='+49 177 2806861'wikidata='Q115744351' ]

**Comment by ivanPyrohivskyi** [comment]
No bug.
[Sport centre BeachMitte ](https://www.openstreetmap.org/relation/14855683) produce two POI with same ID and type (sport):
sport: sports_centre BeachMitte (leisure:sport_centre)
sport: beachvolleyball;soccer BeachMitte (sport:beachvolleyball;soccer)

We **do not show POI with same ID and type (sport)** [here in the code](https://github.com/osmandapp/OsmAnd/blob/6963f4a6c6e124e65830f4e855ec848f3181188d/OsmAnd-java/src/main/java/net/osmand/search/core/SearchCoreFactory.java#L641)

Even miss this filter, we also **filter duplicate with same name in the radius 30 meters**. [Place in the code](https://github.com/osmandapp/OsmAnd/blob/6963f4a6c6e124e65830f4e855ec848f3181188d/OsmAnd-java/src/main/java/net/osmand/search/SearchUICore.java#L296).

Searching by types: soccer, beach volleyball, sport centre works fine.

**Comment by ivanPyrohivskyi** [comment]
PR https://github.com/osmandapp/OsmAnd/pull/20343 (Android) no need to transfer to iOS (core). We do not filter categories in ObfPoiSectionReader_P.cpp readAmenity , but save all if any category was accept.

**Comment by ivanPyrohivskyi** [comment]
iOS bug in detail info when click on subcategory search item.
Tap on subcategory "Футбол":
<img width="400" src="https://github.com/user-attachments/assets/7de16d04-8cd2-422b-a032-427755e4e936" /> <img width="400" src="https://github.com/user-attachments/assets/3597d9f7-b6f8-4ca9-a84a-3ffd5636894c" />

Expected:
<img width="400" src="https://github.com/user-attachments/assets/99f12921-0a6f-4d4f-9cb8-31223862aff2" />

**Comment by dmpr0** [comment]
# Review

<table style="width:100%">
  <tr>
    <th>Sports club</th>
    <th>Restaurants</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/4e75e4a0-f70a-4929-a214-2ca285f3f465"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/09c71821-98f9-4a2d-a255-e3deb5f54dcf"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ] There is no way to filter Sports club by sport type. We can filter Restaurants by Cuisine.
