### ISSUE TITLE
Sqlitedb doesn’t erase its cache 

### ISSUE THREAD

**Issue by nnngrach** [osmandapp/Osmand#8484]
When you click the delete cache button, it is not actually deleted, but only hidden. The file size is not reduced.

It happens with online map in sqlitedb format 

It looks like the SQL command  “**Vacuum**” was skipped.

**Comment by max-klaus** [comment]
Did you access the file or may be just look to the info above the buttons?

**Comment by nnngrach** [comment]
Here are files and screenshoots:

**Comment by nnngrach** [comment]
https://www.dropbox.com/sh/usk1r8oum0h9hel/AABlG-WTI1MGsdv9iqCrYvQ3a?dl=0

**Comment by nnngrach** [comment]
Thank you, it works!
