### ISSUE TITLE
GPS Track uploads fail, orbot proxy suspected

### ISSUE THREAD

**Issue by githubber42** [osmandapp/OsmAnd#8486]
Before entering an issue, please read the information below.

What version of OsmAnd are you using, on what device and Android/iOS version?
Latest OsmAnd from f-droid, 3.5.5. Android Version 9, lineage_shamu (without Gapps). Orbot "full device VPN" for all apps.

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

Using Offline maps

What I did: Setup OSM editing with account and password; setup OsmAnd Proxy Host 127.0.0.1, Port 8118; Record GPS Track and save; Select Dashboard, Show all tracks, Rec pulldown, Vertical 3 dots for desired track to upload, Export, change to "Identifiable", Yes to upload. Check OsmAnd Edit user and password; repeat.
Expected Response: Track uploads
Actual Response: Message displayed "0 of 1 tracks uploaded"

Successful Workaround: Use a browser to login to openstreetmap.org and upload track file.

Other observations: Offline map downloads work OK in OsmAnd. ONline maps are rarely used, but they work OK too. So not as severe as bug #6659.

**Comment by cs-nero** [comment]
You can close this. Sorry.
