### ISSUE TITLE
Turn left then in zero feet make a u-turn (to turn right)

### ISSUE THREAD

**Issue by ithink314** [osmandapp/Osmand#8487]
What version of OsmAnd are you using, on what device and Android/iOS version?

Latest OsmAnd from f-droid, 3.5.5. Android Version 9, lineage_shamu (without Gapps). Orbot "full device VPN" for all apps.

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

Using Offline maps.

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.

(Using US_north-carolina_northamerica.obf, Dec 31, 2019)

__*In case of wrong routing:*__

Used OsmAnd's in-app offline routing

What routing profile is chosen in OsmAnd app? (car, bike, pedestrian, fastest or shortest)

car, fuel efficient.

Please specify as exactly as possible the start and end point of your route by telling us city name and street name so that we can find it via in-app address search easily. Also, a permalink from openstreetmap.org can be helpful.

Start approximately 35.30006 N, 80.53096 W (or farther to west). 
Finish approximately 35.28594 N, 80.49095 W.
Problem was at T-intersection of Flowes Store Road East and US 601.

https://www.openstreetmap.org/#map=16/35.2995/-80.5152&layers=G

Tell us your expected routing, and how OsmAnd routes, or add screenshots here.

Route shown on map was OK - turn right onto US 601; however, voice and display (see screenshot) said to turn left, then in zero feet make a u-turn. It should have said simply turn right.

I note openstreetmap should have a stop sign for Flowes Store Road East at the T, but does not, yet.

![Screenshot_20200217-150638_OsmAnd~](https://user-images.githubusercontent.com/843769/74691337-62172780-51b0-11ea-9816-45591c0e200c.png)

**Comment by MadWasp79** [comment]
@ithink314 In the last version of Osmand with fresh maps everything seems okay -  https://www.youtube.com/watch?v=zvmptcYr-dU. 
Please update map and app to latest version.
