### ISSUE TITLE
[Nice to have] Add text to the map cache removal pop-up menu

### ISSUE THREAD

**Issue by nnngrach** [osmandapp/Osmand#8499]
If you delete the cache of most Sqlitedb maps, this will work correctly. However, if you try to delete the cache from the map that is currently displayed on the screen, the cache will not be deleted. 

The first thought that comes to mind at this moment is that this is an application bug. And this makes you want to click the delete button again. And again...

Here are screenshots to demonstrate how it looks:

https://www.dropbox.com/s/mhrr7mli7hcu91j/1%20before.png?dl=0
https://www.dropbox.com/s/6mudv3w0x2u1759/2%20message.png?dl=0
https://www.dropbox.com/s/25vbykmqisrj55z/3%20after.png?dl=0

Please add an additional line of text when deleting the cache from the active map. For example, something like this: "The cache of this map will be deleted after it is closed". I think this simple thing will help get rid of this problem.

https://www.dropbox.com/s/i8837iqek4iwtcq/4%20new%20message.png?dl=0

**Comment by nnngrach** [comment]
Or you can just make sure that when you click the "Delete cache" button, the cache is actually deleted. Even from an active map.

**Comment by nazar-kutz** [comment]
I have tested and everything works fine now. I think it was already fixed by this commit
https://github.com/osmandapp/Osmand/commit/55cc4c44f8fb990d69347beb900c6508e95645a5
