### ISSUE TITLE
Crash using boat routing

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#8502]
Not quite sure how to reliably reproduce, but when testing boat routing with daily builds in the last few weeks I often receive the enclosed crash. OsmAnd will afterwards not start anymore unless manually force-stopped.

The crash  usually occurs after tapping "Directions", then "Boat profile" (with default settings), then selecting a "From" point somewhere in the open sea.

EDIT: Looks like the issue is independent of boat routing , it results from an NPE while trying to detect a "driving region" for a point too far offshore.

[exception.log.txt](https://github.com/osmandapp/Osmand/files/4222011/exception.log.txt)

**Comment by sonora** [comment]
I guess the issue is that `getSmallestBinaryMapDataObjectAt(...)` can return null (e.g. for points outside defined regions)?

**Comment by sonora** [comment]
Yes, that fixes it, thanks!

What also works great now is the straight line routing, good job!

What I am not so sure about is the default boat routing. I think it works on rivers and canals, but it seems to fail miserably in the open ocean, see screenshot below. But maybe I misunderstand its purpose?

![Screenshot_20200219-231116_OsmAnd~](https://user-images.githubusercontent.com/845735/74881236-40af6a80-536d-11ea-998c-9ed3befb4362.jpg)

**Comment by vshcherb** [comment]
We have Straigntline and direct-to-point improved designed to work in open ocean / seas.
This routing is only good for rivers / channels. Probably we will introduce 2 routing types Boat (Big / small) to make visual difference for open water profile
