### ISSUE TITLE
[Feature request] add bearing line to the boat icon

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8506]
On the map, where the user's current position is displayed, it is useful to have a bearing line "direction right ahead" displayed near to the boat icon, as is typically on classic ship chartplotters.

**Comment by vshcherb** [comment]
We've just added "Direct-to-point' navigation and there are also Markers line available

**Comment by sonora** [comment]
What's the difference between direct-to-point and straight line routing?

**Comment by vshcherb** [comment]
direct-to-point doesn't recalculate route and draws line always from start to end

**Comment by sonora** [comment]
Ok, but not very speaking. Shall we maybe rename "direct-to-point" to "Straight line (static)"?

**Comment by vshcherb** [comment]
Better to pick up existing terminology (please check with author of original issue in 3.7)
