### ISSUE TITLE
brouter profile calculates wrong travelling time

### ISSUE THREAD

**Issue by mvdwege** [osmandapp/Osmand#8520]
OsmAnd 3.5.5 on Android 9, using brouter for offline routing. I have made a custom profile, and it uses brouter correctly, I get a nice correct route.

However, OsmAnd calculates travelling time for that route as if it were a walking profile; verified by actually checking the default walking profile in OsmAnd, which picks a slightly different route with comparable travel time.

It does not matter which route I pick, it consistently gets calculated as a walking route.

**Comment by vodie** [comment]
BRouter since version 1.5 can calculate the traveling time and Osmand since version 3.4 can use it. Maybe your BRouter profile calculate the wrong times.

**Comment by mvdwege** [comment]
I have no clue what it did wrong, but as of the latest update, version 3.6.2, 2020-02-24, it works correctly. It had thrown away my old profile, but creating a new brouter profile and it calculates the correct travel time again.

**Comment by mvdwege** [comment]
Found the problem. The brouter 'Shortest' profile calculates the wrong time; brouter web gives me around 3 hours too. For bicycle profiles you need one of the 'fastbike' profiles.
