### ISSUE TITLE
Wrong genus in German navigation instructions

### ISSUE THREAD

**Issue by Discostu36** [osmandapp/Osmand#8522]
Osmand 3.6.0

#8053 has been fixed by @sonora but the genus used in German navigation instructions is sometimes still wrong. Problem seems to be that the name of the street is taken as source for the genus even if the street name is not said.

Example:

When I drive from [here](https://osmand.net/go.html?lat=54.33479&lon=10.11028&z=17) to [here](https://osmand.net/go.html?lat=54.34777&lon=10.12216&z=17), Osmand first says something like 

> In x Metern rechts abbiegen auf **den** B76 in Richtung Eckernförde, Universität, Wissenschaftspark, Holsteinstadion

Reason might be that the street is called "Olof-Palme-Damm" (masculine). But the street name is not uttered, the destination is said instead. So, I'd expect to hear the correct article for the ref "B76" ("Bundesstraße 76 ⇾ feminine). So correct would be:

> In x Metern Rechts abbiegen auf **die** B76 in Richtung Eckernförde, Universität, Wissenschaftspark, Holsteinstadion

Directly before making the turn Osmand says 
> Rechts abbiegen auf **den** B76 Olof-Palme-Damm

This is ok because now the masculine street name is uttered. I think I'd prefer if it also said "die" here, using the genus of the ref that is directly following after the article, but for my ear both versions are correct.

But to make things not too complicated, this might be the easiest solution:

If a ref is said as part of the "to", use the correct article for that ref (usually feminine). If there is no ref uttered, only then take the article for the street name.

**Comment by sonora** [comment]
Sorry for not seeing this issue earlier. Fixed now.

We had the wrong order of conditions: The masculine "-damm" prevailed in this case (even though we omit pronouncing it to favor destinations if present). On the other hand, any **refs** are always announced, though, and I have changed to now **all refs containing digits causing to use feminine**, and making this the prevalent condition.

I hope this is likely (at least mostly) correct in German, as in "A 6", "B 76", "St 2205", etc.
