### ISSUE TITLE
Map flooded

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8523]
At 37.01628° N, 7.93520° W, the city of Faro, Portugal is flooded.
![image](https://user-images.githubusercontent.com/50198677/74935536-143d3200-53f1-11ea-829b-97f7cde62df5.png)

**Comment by pebogufi** [comment]
Where is the problem ? I think map is ok.
The water left of the "F" of Faro is the port, around the "+" is a salt lake. Please explain, where do you see a problem. Compare map with satelite foto.
