### ISSUE TITLE
Routing in different cases in error when using Brouter (same issue as #7452)

### ISSUE THREAD

**Issue by EssBee59** [osmandapp/Osmand#8524]
Hello,

This is an update of #7452:
By selecting the Osmand base profile "cycling", the routing function (calculation of a tour from A to B) is Ok in every of the 3 cases I tested:
Case 1: entering the from and to positions manually
Case 2: giving the from and to positions with a GPX file containing a so. called "route" (= 2 rtept)
Case 3: case where Osmand has to calculate the tour between my current position and the start of a track that was selected to be followed

But I am biking with a fastbike I use that for the 3 party router "Brouter" for routing.
For that I create an own profile in Osmand (add function) with the following:
Base profile: cycling
Name: brouter (free choice)
Navigation type: Brouter (offline)

To be sure, only this profile can be used, I deactivated all other profiles.

Now the issue:
Case 1: is ok
But, Case 2 and Case 3 are in error!
Instead using the Brouter to calculate the tour, a native Osmand profile for car is used!
The issue is dangerous, as the routing leads bikers on the motorway...

Here an extract of the "adb logcat" collected by testing the "Case 2" above (routing with a "route" of 2 rtept)
02-16 19:19:07.600 6550 6866 I net.osmand: RouteResultPreparation <test regions="" description="" best_percent="" vehicle="car"
02-16 19:19:07.600 6550 6866 I net.osmand: start_lat="50,02584" start_lon="8,67219" target_lat="49,91985" target_lon="8,48634" routing_time="0,00" loadedTiles="56" visitedSegments="3" complete_distance="0,00" complete_time="0,00" >
02-16 19:19:07.600 6550 6866 I System.out: <test regions="" description="" best_percent="" vehicle="car"
02-16 19:19:07.600 6550 6866 I System.out: start_lat="50,02584" start_lon="8,67219" target_lat="49,91985" target_lon="8,48634" routing_time="0,00" loadedTiles="56" visitedSegments="3" complete_distance="0,00" complete_time="0,00" >

I try to provide the full log as attachement.
By a  look at the code I suspect a bug in the "RouteProvider.java"....

			try {
				RouteCalculationResult res;
				boolean calcGPXRoute = params.gpxRoute != null && !params.gpxRoute.points.isEmpty();
				if (calcGPXRoute && !params.gpxRoute.calculateOsmAndRoute) {
					res = calculateGpxRoute(params);
				} else if (params.mode.getRouteService() == RouteService.OSMAND) {
					res = findVectorMapsRoute(params, calcGPXRoute);
				} else if (params.mode.getRouteService() == RouteService.BROUTER) {
					res = findBROUTERRoute(params);
 
I liked to test  a  change in the order of the "if´s" (first call findBROUTERRoute(params)..), as I think it could solve the issue… but my dev. platform is not running till yet….

Regards

[rt_osmand.txt](https://github.com/osmandapp/Osmand/files/4231445/rt_osmand.txt)
[DrKs_RTE_2WP.gpx.txt](https://github.com/osmandapp/Osmand/files/4231545/DrKs_RTE_2WP.gpx.txt)

**Comment by EssBee59** [comment]
attachement  "rt_osmand.txt" were inserted above

**Comment by EssBee59** [comment]
Attachement "DrKs_RTE_2WP.gpx.txt" were inserted. (to be renamed as .gpx for testing the route)

**Comment by EssBee59** [comment]
Hello,

After I got my local dev. platform running I could test after the following change in RoutingProvider.java:
			try {
				RouteCalculationResult res;
				boolean calcGPXRoute = params.gpxRoute != null && !params.gpxRoute.points.isEmpty();
                      if (params.mode.getRouteService() == RouteService.BROUTER) {
					res = findBROUTERRoute(params);
				} else if (calcGPXRoute && !params.gpxRoute.calculateOsmAndRoute) {
					res = calculateGpxRoute(params);
				} else if (params.mode.getRouteService() == RouteService.OSMAND) {
					res = findVectorMapsRoute(params, calcGPXRoute);

(just the order of the if´s is changed!)
And my results are ok! using a "brouter" profile, the routing is as expected

**Comment by vshcherb** [comment]
https://github.com/RussianFox/osmandbuilddocker

**Comment by vshcherb** [comment]
The fix looks strange cause the same situation applies to OsmAnd routing itself. If you use GPX you need to toggle option to allow "OsmAnd to calculate start/end segment for the route" in that case BRouter will calculate start and end

**Comment by vshcherb** [comment]
I think correct fix is different, please feel free to test with master branch

**Comment by EssBee59** [comment]
Hello,
In "Case 2" above, the option "calculate the Osmand route-part offline" is not involved…
But if you have the possibility to test this case 2, you will see using adb logcat, that Osmand is using a wrong routing....
I think, the Problem is, that the condition  "if (calcGPXRoute && !params.gpxRoute.calculateOsmAndRoute)" is true, also when only a brouter profile is activated…
So, by inverting the if´s, this Problem has no negativ effect….
In "case 3" and having the option "calculate the Osmand route-part offline" set, the same issue occured before my change…

Sorry, I am not expert with master branch (today I intalled a local dev platform using this page: https://osmand.net/help-online#dev-compile-android )

Please try to test the cases I described above. I hope I did not make mistakes and you get the same results as myself
Ess Bee

**Comment by EssBee59** [comment]
A remark: With the change above, the retest is ok with a "brouter" profile using as input a route with 2 WP´s, but not OK with 3 ore more WP´s....
Anyway, the more interesting (often used) "case 3" is ok.

**Comment by vshcherb** [comment]
Any build you did is ok to compile it again. Here is a docker that compiles everything and produces apk (https://github.com/RussianFox/osmandbuilddocker). Docker is like an executable that you run and get apk as a result.

I've fixed the issue according to your "pull-request" code that you've sent. I see that you try to override GPX-routing which is not correct cause GPX should be triggered first and I fixed how the segments are calculated between <rtept>, so now they are using B-Router and not OsmAnd. 
It was an issue before but now it should work as configured

**Comment by EssBee59** [comment]
Fine, and thank for the docker I will test asap!
Is the change already included in the daily build tomorrow?
If so, I will test it...
Regards

**Comment by vshcherb** [comment]
Yes already available

**Comment by EssBee59** [comment]
Hello,
My retest using the daily build:
Case 3: OK (now, the Brouter is used!)  THIS IS THE MOST IMPORTANT CASE.
Case 2: Seems not Ok,  (the calculated route leads on motorway)…

I hope to find more time tomorrow to test again and look at your change.
But as "Case 3" is solved, the effect of the issue decreased

**Comment by EssBee59** [comment]
Hello Vshcherb,

Your change and Approach  is much better as my first change!

I adding your "logic" in the method "RouteCalculationResultcalculateOsmAndRouteWithIntermediatePoints…" 

and ALL my tests succeeded!
(Case 1, Case 2 with 2 WP's and 5 WP´s,  and Case 3)
Fantastic!!!
I try to send you my last version of RouteProvider.java, but I think you understand the change
(replace "return findVectorMapsRoute(rp, false)" with your "try …..")
Regards
Ess Bee

**Comment by EssBee59** [comment]
To be clear: My change above was just on my local machine (I am not expert in master branch)
But I could attach the java file...
