### ISSUE TITLE
App prefers lwn over rwn hiking route

### ISSUE THREAD

**Issue by mahdi1234** [osmandapp/Osmand#8541]
Osmand 3.5.5~ with "Colouring according to OSMC" and Cycling/MTB/Horse routes disabled.

In hiking profile

https://www.openstreetmap.org/way/679127828 has two relations

local - https://www.openstreetmap.org/relation/898658#map=15/49.0559/16.3297
regional - https://www.openstreetmap.org/relation/163184#map=13/49.0814/16.3840

OsmAnd seems to be choosing randomly which one to render (in general). Imo regional should always be preferred over local one as local ones are sometimes done by enthusiasts and not even properly marked in terrain.

https://wiki.openstreetmap.org/wiki/Tag:network=lwn?uselang=en-US
https://wiki.openstreetmap.org/wiki/Tag:network=rwn?uselang=en-US

![Screenshot_2020-02-22_21-32-49](https://user-images.githubusercontent.com/1097047/75098845-fcada700-55b2-11ea-8da4-30b0a98f3625.png)

**Comment by vshcherb** [comment]
I think randomly is  always worse the predetermined

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-tools/commit/4dd03c41add134efc154603d31d60e7622856bcf Fixed - needs to be checked @xmd5a2
