### ISSUE TITLE
Road mistakenly disconnected

### ISSUE THREAD

**Issue by AbedKarmi** [osmandapp/Osmand#8544]
![Screenshot_20200224-035413_Barcode Scanner+](https://user-images.githubusercontent.com/5672417/75124685-8fd10480-56b9-11ea-94f9-a9c06d3342e5.jpg)

![Screenshot_20200224-035341_OsmAnd+](https://user-images.githubusercontent.com/5672417/75124705-a2e3d480-56b9-11ea-9891-174e56201436.jpg)

**Comment by MadWasp79** [comment]
It's a data issue from OSM, road connection is incorrect.

**Comment by AbedKarmi** [comment]
> It's a data issue from OSM, road connection is incorrect.

It is correct in OSM, I have checked it there!
![os](https://user-images.githubusercontent.com/5672417/75157810-9002eb80-571d-11ea-8439-2c294946de1e.png)

**Comment by vshcherb** [comment]
As I see on current data it is not longer an issue though it could possibly happen if there are 2 very close to each other nodes in the middle of the way.
