### ISSUE TITLE
Snap to road issue

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8549]
While creating a track with Distance Measurement and enabling Snap to road option, you still get 2 tracks, one with a line that follows the roads but also one with a line that shows a track like that would be made with the disabled snap to road option. You don't see the second in OsmAnd, but you can see it with the GPX viewer and recorder, for example. Also in the Garmin programs if the track was first edited with GPS visualizer.

**Comment by vshcherb** [comment]
This is a single track that has 2 representations: 1 with rtept and 2nd as a line
