### ISSUE TITLE
Issue with new exit info feature

### ISSUE THREAD

**Issue by bitboy85** [osmandapp/OsmAnd#8550]
First: I like the way how exit number and street types are now shown in the top middle bar.

But the info given about exits is now confusing. It gives the exit number and the exit name. From my personal experience in germany and luxembourg there is no sign which displays the name of an exit (i'm still wondering where the osm guys got this information). So giving the exit name is not helpful at all. Sadly, if an exit number/name exists, the destination of that exit is omitted, but the destination is a much more useful information for the driver.

So could you please change voice and top bar information to something like
$TurnInfo $ExitNumber $DestinationRoad(s) >> $Destination

**Comment by naoliv** [comment]
Maybe people are wrongly using the `destination` as `name`? (sometimes I see this here in Brazil, where we basically have only `ref` and `destination` in the signs)

**Comment by pebogufi** [comment]
Please add exit number also in list Details of navigation in "Turn-By-Turn" list.

**Comment by bitboy85** [comment]
Here is an example: https://www.openstreetmap.org/edit#map=19/49.60589/6.08145
The exit name is "Helfent" it han an "exit_to" (never seen that before...) to "Luxembourg-Centre Bertrange" but the destination on the exit lane is: Luxembourg-Nerl;Bertrange.
I guess in most cases the destination on the exit lane is the most tagged and "correct" one.

**Comment by polarbearing** [comment]
Example of an exit name "Dreieck Potsdam" prominently posted, from Berliner Ring A10. (Ignore the orange circle, that was for another issue)

![Screenshot 2020-10-04 at 22 13 59](https://user-images.githubusercontent.com/8266355/95026288-95032280-0690-11eb-86c8-c6a86a666a5d.png)

(image based on mapillary-upload by grobin (cc), taken 2020-08-08)

**Comment by scaidermern** [comment]
The usage of exit numbers in Germany varies a lot. Some motorways do show exit numbers, others don't. I think their importance declined over the time. Exit names and destinations became more important than exit numbers.

**Comment by vshcherb** [comment]
Merged into #9592
