### ISSUE TITLE
regressikn: GPX waypoint dialog does not show Save button

### ISSUE THREAD

**Issue by jengelh** [osmandapp/Osmand#8556]
osmand 3.6.2, in this dialog
![Screenshot_20200225-140254](https://user-images.githubusercontent.com/8861948/75250403-97d39600-57d8-11ea-918f-df3a378cbaa9.png)
the Cancel/Save button is not visible when the keyboard is shown. This was better in (I think it was) osmand 3.5.x.

**Comment by vshcherb** [comment]
#6669

**Comment by jengelh** [comment]
Still unfixed as of 3.7.2.
![sc](https://user-images.githubusercontent.com/8861948/82740595-8e5fb880-9d4a-11ea-8c01-b01eda82a64c.jpg)
