### ISSUE TITLE
OsmAnd+ crashes since 3.6

### ISSUE THREAD

**Issue by AndyGHenderson** [osmandapp/Osmand#8560]
I just installed the above together with the latest GB map. OsmAnd starts up OK and displays my position on the map correctly. Any attempt to move away by swiping causes a crash. The UI does not restart automatically (although I see a 'service restarted' message). Unlike other crashes I've seen, I am not offered the option to send in diagnostics.

I tried removing some map features to see if it would help, but the crash occurred when I unset contour lines and again when I unset hill shading.

Tried running in safe mode: UI locked up and then OsmAnd crashed as before.

Tried complete re-download of the GB England map - no improvement.

I'm running Android 6.1 on a Motorola G third generation.

Is there a way to provide better diagnostics? Reproducing the crash is easy for me,

Andy

**Comment by njohnston** [comment]
You can [install adb](https://developer.android.com/studio/releases/platform-tools) on your computer, connect your phone, and run `adb logcat` before you open OsmAnd. This produces a lot of output so you should grep it for OsmAnd.

**Comment by AndyGHenderson** [comment]
Thanks for getting back.

[adb.log](https://github.com/osmandapp/Osmand/files/4255897/adb.log)

Here you go, if I understand correctly 'grep' means filtering for OsmAnd but it seems like there's some useful diagnostics on lines that didn't have OsmAnd on and the file is less than 1Mb so I've given you the whole thing.

To get the log as clean as possible, I started from power on. Let the phone settle down. Started logcat them immediately started OsmAnd. Waited for it to draw the initial map. Then dragged the map from top right to bottom left to cause the crash.

Andy

**Comment by scaidermern** [comment]
@AndyGHenderson You should filter this log and remove everything not related to OsmAnd since it may contain potentially sensitive information about other apps and services.

**Comment by AndyGHenderson** [comment]
Possibly so, but I've no way to know what is relevant to OsmAnd, or not.

**Comment by vshcherb** [comment]
From the logs I couldn't get enough information, only that there are some issues with payment system? or connection to palyment system.

Probably it is worth to do complete app reinstall
FYI: You can also use Development plugin and click Logging options. Also after each crash there should be dialog showing to share information.

**Comment by AndyGHenderson** [comment]
Thanks for looking.

I've reinstalled OsmAnd+ - bit of a pain because I lost all my settings and had to re-download my maps - but I am up and running again. I re-enabled plugins and settings one at a time in case the crash reappeared, but it didn't.

Thanks all for your help,

Andy

**Comment by vshcherb** [comment]
With new version there are "Export profile" feature and in future it will be "Export profiles"
