### ISSUE TITLE
[Feature request] add remove Map Markers group

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8564]
Currently, in OsmAnd menu - Map Markers - Groups, there is possible to move to history the markers in the group only. Even deleting the markers in the History folder does not remove the Group, therefore many empty groups remain on the device.
Adding the Delete button may solve this issue.

**Comment by vshcherb** [comment]
The switch on top supposed to delete the group. Empty switches are probably displayed because of enabled GPX files
