### ISSUE TITLE
Map details

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8566]
on the 20m map zoom level, there are two different maps can be enabled.

![image](https://user-images.githubusercontent.com/50198677/75343876-0b8da580-58a2-11ea-85ed-177351fe0838.png)
![image](https://user-images.githubusercontent.com/50198677/75343879-10eaf000-58a2-11ea-8923-19bd543cfaff.png)

**Comment by pebogufi** [comment]
What do you want to tell us ?
Do you think there is something not working, do you see a bug ?

**Comment by xmd5a2** [comment]
Not reproducible
![Screenshot_2020-03-02-11-28-11-806_net osmand plus](https://user-images.githubusercontent.com/5829014/75658382-4c5a3580-5c79-11ea-9389-c0e84f53a77b.jpg)
