### ISSUE TITLE
Easier way to announce an obstacle on the road when travelling

### ISSUE THREAD

**Issue by 1Cedric1** [osmandapp/Osmand#8581]
Hello,

It is quite difficult to annonce in Osmand offline an obstacle on the road when travelling.

Example : you are driving on an highway, with Osmand OFFLINE running, and you hear on the radio that the road will be closed in 10 km, due to an accident. Is it possible to simply enter this information in Osmand offline, so that it calculates a new route before reaching the closed road ?

Currently, we have to click EXACTLY on the concerned road, what is not easy when traveling, specially if you have "big" fingers, then click on "actions" and "avoid road". It works, but is not easy. If you travel in a country or a city you do not know, it will be impossible to find the exact point where the obstacle will be.

I rather propose juste to select just the area or a region on the map where the obstacle should be and where the intended route visible is, instead of the exact point on the road. Then, it would be great to click on "action", "avoid road", and Osmand should "close" the all road route which is currently visible on the screen. This would avoid to zoom and click more times to reach the exact point on the map.

thank you for your interest!

![Screenshot_20200228-102123](https://user-images.githubusercontent.com/61581150/75537079-a60ef580-5a16-11ea-8197-30fb4326f664.png)

**Comment by max-klaus** [comment]
I will be fixed in the next release. The avoid road feature will exclude the road if you tap near calculated route segment.

**Comment by 1Cedric1** [comment]
great, thank you!
