### ISSUE TITLE
[Bug] Https redirecting error

### ISSUE THREAD

**Issue by nnngrach** [osmandapp/Osmand#8585]
I noticed a bug that occurs when connecting to online-map servers that return a Http Redirect instead of returning a tile image. For example, consider this sqlitedb preset file.

https://www.dropbox.com/s/oo261do3zxttr1q/russia_geology_map_https.sqlitedb?dl=0

It makes Osmand to connect to the Anygis.ru server using HTTPS. 
`https://anygis.ru/api/v1/Other_Ru_Vsegei_Geology/{1}/{2}/{0}`

This is a working URL. Here is an example of how one online map viewer site correctly downloads tiles from this link.

https://nakarte.me/#m=7/60.07493/57.53892&l=-cseyJuYW1lIjoiUnUgR2VvbG9neSIsInVybCI6Imh0dHBzOi8vYW55Z2lzLnJ1L2FwaS92MS9PdGhlcl9SdV9Wc2VnZWlfR2VvbG9neS97eH0ve3l9L3t6fSIsInRtcyI6ZmFsc2UsInNjYWxlRGVwZW5kZW50IjpmYWxzZSwibWF4Wm9vbSI6MTgsImlzT3ZlcmxheSI6dHJ1ZSwiaXNUb3AiOnRydWV9/O

But in fact, Anygis does not return a tile. It returns a redirect to another URL like this.

http://wms.vsegei.ru/VSEGEI_Bedrock_geology/wms?LAYERS=RUSSIA_VSEGEI_1M_BLS&TRANSPARENT=true&FORMAT=image%2Fpng&PROJECTION=EPSG%3A3857&REPROJECT=true&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&SRS=EPSG%3A3857&BBOX=5635549.221409474,8140237.7642581295,5792092.255337514,8296780.79818617&WIDTH=256&HEIGHT=256

As you can see, this is a URL with HTTP. Moreover you just won't be able to connect to it via HTTPS.

https://wms.vsegei.ru/VSEGEI_Bedrock_geology/wms?LAYERS=RUSSIA_VSEGEI_1M_BLS&TRANSPARENT=true&FORMAT=image%2Fpng&PROJECTION=EPSG%3A3857&REPROJECT=true&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&SRS=EPSG%3A3857&BBOX=5635549.221409474,8140237.7642581295,5792092.255337514,8296780.79818617&WIDTH=256&HEIGHT=256

So what happens if you add this sqlitedb file to Osmand and try to view the map? Nothing. 

However, if you add this file instead, the map will be displayed correctly.

https://www.dropbox.com/s/u0tnoh7q9wmi0ys/russia_geology_map_http.sqlitedb?dl=0

In this file, the connection to Anygis occurs via HTTP. (not HTTPS)
`http://anygis.ru/api/v1/Other_Ru_Vsegei_Geology/{1}/{2}/{0}`

Based on this, I have a guess. If Osmand connects to a server over HTTPS and then receives a redirect from It to another server with HTTP, Osmand will still connect to it over HTTPS. 

Perhaps the opposite is also true: from HTTP, it always redirects to HTTP. Regardless of which URL is actually received.

I think this is a bug, because it doesn't allow to load many maps. Not just this one. I think tiles should be downloaded for each of these sqlitedb files.

https://www.dropbox.com/s/oo261do3zxttr1q/russia_geology_map_https.sqlitedb?dl=0
https://www.dropbox.com/s/u0tnoh7q9wmi0ys/russia_geology_map_http.sqlitedb?dl=0

**Comment by Totorrr** [comment]
Yes, I noticed this: if I manually add a new "online tiles" source in OsmAnd, with a http:// URL and this first URL responds with a HTTP 302 redirect to another https:// URL, it won't load. 

Fortunately my first first URL also support https://, and when I use https:// for URL1 (redirecting to a https:// URL2), it works as intended (tiles appear).
