### ISSUE TITLE
drinking_water:refill

### ISSUE THREAD

**Issue by pqhf5kd** [osmandapp/OsmAnd#8587]
The tagging scheme for [drinking_water:refill](https://wiki.openstreetmap.org/wiki/Key:drinking_water:refill) was finalised. Currently there are only 4 locations tagged but hopefully this will expand rather quickly. Is there any support for adding to OsmAnd?

**Comment by pqhf5kd** [comment]
Hi @xmd5a2, I'm unable to find, or search for, the refill category. I can see 'Drinking water refill: yes' when I select a POI with the relevant tag.
I'm running 3.14 on iOS.

**Comment by pqhf5kd** [comment]
@vshcherb Can you reopen this issue please?

**Comment by vshcherb** [comment]
This is additional tag, you can't search for it, you can only select drinking water and then filter options.

**Comment by pqhf5kd** [comment]
Should I find a 'refill' option here? iOS 3.14

https://imgur.com/a/NcSHLp2

**Comment by vshcherb** [comment]
You need to select drinking water and then additional Filters for this POI type

**Comment by pqhf5kd** [comment]
How do I do that?

**Comment by vshcherb** [comment]
It should be herewhen you click button customize Drinking water (right from Show drinking water on the map), but I don't see it as well
![image](https://user-images.githubusercontent.com/1042025/89402179-c0ac6f80-d716-11ea-9b99-db3bc276d83c.png)
