### ISSUE TITLE
way 768738668 routing issue

### ISSUE THREAD

**Issue by 532910** [osmandapp/Osmand#8590]
Left turn is allowed here and I see nothing in the osm database (iD editor) that can prevent it.
This issue is reproducable for me.
https://www.openstreetmap.org/way/768738668
![image](https://user-images.githubusercontent.com/14617699/75613858-58dc7200-5b43-11ea-9d8b-900884928440.png)

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-core/commit/0202d051fac22264be3967f706c28f409ca8b37c

**Comment by 532910** [comment]
Works fine now. Thank you!
