### ISSUE TITLE
Distance measurement: Allow to disable snap to road for individual points

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#8592]
Sometimes OSM data is broken and has unconnected roads. Or there is a large area (for example highway=pedestrian) but no artificial ways for connecting the surrounding roads. Example (I already added the missing connection in OSM):
![photo_2020-03-01_09-50-02](https://user-images.githubusercontent.com/1040784/75622664-38440480-5ba3-11ea-9819-707f5c661870.jpg)

In these cases it would be very helpful to disable "snap to road" for a single connection between two points. Currently this setting always applies to all points.

**Comment by vshcherb** [comment]
This is duplicate request to change navigation profile between points

**Comment by scaidermern** [comment]
Has been implemented meanwhile (in the "Plan a route" tool).
