### ISSUE TITLE
Opening hours for recycling centre are not shown

### ISSUE THREAD

**Issue by HT43-bqxFqB** [osmandapp/Osmand#8594]
### Issue
I wanted to look up the opening hours from a recycling centre (https://www.openstreetmap.org/way/28198135) but the app does not show them when opening the details page. The data is present. If it is not a bug, it should be enabled to show this value.

### Versioning details
- OsmAnd~ 3.5.5 from F-Droid
- Android 7.1.1

### Configuration details
- offline vector data

**Comment by xmd5a2** [comment]
Looks like issue was fixed https://github.com/osmandapp/Osmand/issues/8368
Data in obf offline maps are correct

**Comment by HT43-bqxFqB** [comment]
Thanks :+1:
