### ISSUE TITLE
U-turn during navigation

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8595]
The car route from 50.77965, 6.15343 to 50.76423, 6.13455 has a restricted u-turn at 50.77765° N, 6.14138° E. 
https://www.openstreetmap.org/note/2103950#map=19/50.77715/6.14240&layers=N
![image](https://user-images.githubusercontent.com/50198677/75654346-33955400-5c68-11ea-9a5b-bb586db52153.png)

Enabling the Fuel-efficient way lets to avoid the issue.

**Comment by vshcherb** [comment]
Fixed with latest map
