### ISSUE TITLE
Search term 'Toilet' doesn't finds category

### ISSUE THREAD

**Issue by Spielmops** [osmandapp/Osmand#8598]
I visit a town and eventually need a toilet. Therefore I tap on my map near where I am and then "search nearby" and as a search string "toilet". When the search stops, I get in the first line: "Toilet 72km", in the second "toilet 136km". That is not what I understand of "nearby".

I often get results like this and that frustrating. I would like Osmand to limit the term "nearby" to 1km/5km/10km/20km/50km (a custom setting).

Spielmops

**Comment by pebogufi** [comment]
Which version do you use,
see https://github.com/osmandapp/Osmand/issues/8599

**Comment by Spielmops** [comment]
Forgot: Osmand version 3.6.2

Spielmops

**Comment by scaidermern** [comment]
This is caused by using the "wrong" search term. Searching for "toilet" finds POIs with "toilet" contained in their `name` tag. Instead try searching for "restroom" which is the name of the category in OsmAnd.

Ideally OsmAnd should support synonyms here. The user can't know which term to search for if more than one applies.

**Comment by Spielmops** [comment]
In this case, the searchterm "toilet" is the right term, because it is a part of the German word "toilette" and "toilette" is found. But because Osmand is not searching "nearby", every toilet elsewhere in the world is first shown. What I want: Osmand should search "nearby" and more than some kilometers is not nearby. In this case if Osmand had only searched nearby, it would have found every "toilette" around me.

To say it clear: Osmand should search nearby, if I tap on "search nearby" ...

Spielmops

**Comment by vshcherb** [comment]
Here it is not clear what's exactly the problem. You need to choose category to search through the category.
 1st item:
![image](https://user-images.githubusercontent.com/1042025/75806497-0a69e600-5d84-11ea-9e9b-8b6a11ba3552.png)

**Comment by Spielmops** [comment]
My mistake is, that I used an example und you all do not read the wish,

So next example:

goto Gütersloh in Germany. Tap on "Gütersloh", tap on "actions", chose "search nearby.write as search term "meierhof", tap on go and look at the results. The search did not stay "nearby" and the very next "meierhof" ist listed somewhere near the bottom. That is not a search-re: sult for "search nearby". And for the guy telling me, that I did not use the right searchword: why is Osmand listing "Zum Meierhof" and "Am Meierhof" first - I did not search for "zum" or "am" ...

The problem: I do not get a usable result with the recent search.
The solution: Osmand should search "nearby" - some kilometers.

Spielmops

@vshcherb: be so kind and reduce the size of pictures

**Comment by vshcherb** [comment]
@Spielmops it looks quite different than initial example. I think listing "Zum Meierhof" with "meierhof" is legitimate anyway we want to list a bit more results so it is safer cause we are not sure that algoirthm can find right data and OSM data is consolidated. 

There is a limit of kilometers (nearby) when you Browse (search) a selected POI category (like toilets or fuel) though we don't limit Search by name up to 1000 km cause it introduces some other issues. To summarize we should separate 2 issues: 1) there are irrelevant results but there is no corrrect resutls - low priority issue 2) there is no correct result but it is present in OSM (if it is not present obviously we can't do much)

**Comment by eMPee584** [comment]
Whatever the very valid reasoning, osmand search UX is very very #sad at the moment. And very likely there are many more users repeatedly swearing at the awkward implementation logics of this vital map/navi feature.
And this is not fully dealt with even fixing the issue fragments you propose.

**Comment by Spielmops** [comment]
I wish that the results of the search would be sorted by distance. That would help a lot.

Spielmops
