### ISSUE TITLE
Routing off highway, not smart? (also map issue)

### ISSUE THREAD

**Issue by ithink314** [osmandapp/Osmand#8609]
United States North Carolina, Jan 31, 2020
Start: 35.27473, -80.81025  End: 35.25132, -80.85629
https://www.openstreetmap.org/#map=17/35.26114/-80.84184

Expected to stay on highway. OsmAnd routes off highway, then back on highway. Map should have 4-way stop signs (eventually will be a traffic light) and lower speed limit, but it is already an intersection, versus staying on highway without intersection. 

![Screenshot_20200303-083741_OsmAnd~_new](https://user-images.githubusercontent.com/843769/75803693-c0c6ce80-5d76-11ea-8d3d-73191a6b4ccf.png)

**Comment by vshcherb** [comment]
Looking at the pictures there is a stop sign, so it is introduced in the maps and special penalty added to fix that issue https://github.com/osmandapp/OsmAnd-resources/commit/97551f4b3a07ad5c9b6cc81d16487278498b9c2e
