### ISSUE TITLE
"Strait" to be fixed on the map

### ISSUE THREAD

**Issue by RabbitDuck** [osmandapp/Osmand#8610]
Osmand App Version: 3.6.2 (installed from F-Droid)

The missing map location: 
https://osmand.net/go?lat=22.49080995732556&lon=114.36018705368042&z=14

It can be displayed on the online map (using web browser)

![_20200304_113131](https://user-images.githubusercontent.com/31124140/75842939-c1aa3f80-5e0c-11ea-8bc3-22d72a0c921f.JPG)

But, it is missing on the offline map (Android App)

![_20200304_112957](https://user-images.githubusercontent.com/31124140/75842931-ba833180-5e0c-11ea-87bc-fbdfab9e9200.JPG)

**Comment by vshcherb** [comment]
https://www.openstreetmap.org/way/675121341#map=16/22.4913/114.3602
it is on the map

**Comment by xmd5a2** [comment]
Issue is not related to strait tag. Island multipolygon has wrong boundaries. Fixed
![Screenshot from 2020-03-10 16-17-40](https://user-images.githubusercontent.com/5829014/76315975-cda17000-62ea-11ea-9e21-c7c7eeaeb22f.png)
