### ISSUE TITLE
Route building issue

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8616]
OsmAnd builds an inconvenient route
from: 47.410053 39.97202
to: 47.421967 40.09112
it cannot be changed with any navigation settings
![image](https://user-images.githubusercontent.com/50198677/75870470-ae4ea280-5e13-11ea-865d-e16aabebd2ac.png)

**Comment by xmd5a2** [comment]
Not reproducible with latest OSM data and native routing 
![Screenshot from 2020-03-13 13-28-26](https://user-images.githubusercontent.com/5829014/76613121-928f7e80-652e-11ea-9a35-41c378ecd0a1.png)
