### ISSUE TITLE
[Feature request] current position icon blink

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8619]
it may be useful for the drivers to see their current position icon blinking, so that the icon could catch their eye during the navigation.

**Comment by scaidermern** [comment]
The current position is always at the same location on the screen. Why make it blinking? The driver should focus the road and must not be distracted by random blinking objects.

**Comment by vshcherb** [comment]
Unfortunately it doesn't seem nice request cause my position have own fixed position on the map. Blink causes too much distraction, so it is better to use bigger icon probably
