### ISSUE TITLE
Routing issue (to test 03-2020)

### ISSUE THREAD

**Issue by zekooooo** [osmandapp/Osmand#8622]
A short car routing makes a double right turn too late. Bicycle routing is correct and car routing is fixed when I turn on "Fuel efficient way". Avoid private roads and avoid unpaved don't have an effect. I think my other routing settings are default.

![Routing screenshot](https://i.postimg.cc/P5K5NhG7/Bad-routing.png)

Start: 45.81011,15.99206 (Ulica kralja Zvonimira 20, Zagreb)
End: 45.80830,15.99273 (Ulica kneza Ljudevita Posavskog)

The routing goes via Ulica Natka Nodila when it should go via Ulica Crvenog križa. Even if I put an intermediate destination in Crvenog križa (as in the screenshot), it still avoids the street. OSM.org [gives the correct route](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=45.81011%2C15.99206%3B45.80832%2C15.99273) using both OSRM and GraphHopper. Couldn't find any turn restrictions on Crvenog križa that could cause this

Using OsmAnd~ 3.5.5 (F-Droid) on Android 7.0, up to date offline map, offline routing

**Comment by vshcherb** [comment]
It looks liked the route is forbidden cause it doesn't try to use it even. Probably it is better to try with fresh maps coming in March.

**Comment by zekooooo** [comment]
Seems like it's still happening with the March map.

**Comment by zekooooo** [comment]
Tried it again on 3.6.3 and routing works correctly now. However, the street was also recently changed in OSM from unclassified to residential.
