### ISSUE TITLE
Public transport routing: OsmAnd jumps from the end of the route to the start

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#8623]
Sometimes OsmAnd doesn't handle a public transport route correctly and jumps from the end to the start of a route. Example:

![photo_2020-03-04_18-25-25](https://user-images.githubusercontent.com/1040784/75905742-b45d7700-5e45-11ea-8972-11beb794993d.jpg)

Start: 44.8315163,-0.7014459
End: 44.82327, -0.6006539

Route relations: https://www.openstreetmap.org/relation/2411701, https://www.openstreetmap.org/relation/2409074

**Comment by scaidermern** [comment]
Is this caused by wrong data? The stops in the route relation aren't in the correct order. Is this required by OsmAnd?

**Comment by vshcherb** [comment]
Yes it is required, also I suspect that platforms should be aligned with stops. Stops should be definitely in the right order and it looks like algorithm prefers platform over stop sometimes and it is better to list "platform" next to "stop"

Please feel free to test with OsmAnd Live which should support PT

**Comment by scaidermern** [comment]
I wonder why the order of the stops matters. The relation usually contains the ways in the correct order because this is very easy (JOSM is able to sort them). The stops can't be sorted automatically. However OsmAnd could just use the ways to calculate a route and the stop positions because they are part of these ways. This also means that platforms can be ignored for route calculations if stops are used instead. Do I miss something?

**Comment by vshcherb** [comment]
Unfortunately I don't know the algorithm how it could be sorted in all cases correctly anyway we can open a feature-request to be able to sort stops in the right order

**Comment by scaidermern** [comment]
> Unfortunately I don't know the algorithm how it could be sorted in all cases correctly anyway we can open a feature-request to be able to sort stops in the right order

Maybe ask the developer who implemented it if this idea sounds feasible. Sorting the stops based on the already sorted ways should be not very hard I suppose.
