### ISSUE TITLE
No name of the streetcar stop, just the platform label.

### ISSUE THREAD

**Issue by MSenning** [osmandapp/Osmand#8624]
In Vienna I noticed that in many cases only the label of the platform is shown on the navigation screen. (Rf to the red circle in the picture below: "E" is the arrival platform of the streetcar stop "Währinger Straße - Volksoper".) But the name of the streetcar stop, i.e. "Währinger Straße - Volksoper", is not shown on the OSMAND screen. The yellow circle shows a correct marker of a streetcar stop.

![Screenshot_20200301_151514_net osmand plus (2)](https://user-images.githubusercontent.com/17511805/75909198-e4a81400-5e4b-11ea-9c13-028c044367fb.jpg)

Map name: Österreich
OSMAND Version: ~3.5.6#29128m, published: 2020-02-29

**Comment by vshcherb** [comment]
CC @MadWasp79

**Comment by vshcherb** [comment]
https://www.openstreetmap.org/node/4283722994#map=19/48.22500/16.34973

**Comment by vshcherb** [comment]
41 - relation https://www.openstreetmap.org/relation/2296590

**Comment by vshcherb** [comment]
This copy was intentionally introduced - https://github.com/osmandapp/OsmAnd-tools/commit/c633dea861942203cce53bbfaabf0913978406a0
I can't explain why but not I put a empty-name check to not copy it 
https://github.com/osmandapp/OsmAnd-tools/commit/850216c2549168b1ec590448ec2ac26c1b0c6c88
