### ISSUE TITLE
Marker: Make history clearable

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#8626]
Currently the marker history grows larger and larger. It is possible to delete only individual entries, one by one. It would be nice to have a button for clearing the complete history.

**Comment by pebogufi** [comment]
.. or delete all older than "this" position.

**Comment by vshcherb** [comment]
I think we need to have button delete for the whole section 2018, 2019, February. Then it will require 5-6 clicks to delete whole history

**Comment by scaidermern** [comment]
> I think we need to have button delete for the whole section 2018, 2019, February. Then it will require 5-6 clicks to delete whole history

This sounds like a good idea.

**Comment by dmpr0** [comment]
![Markers](https://user-images.githubusercontent.com/9365308/76404741-a5b81800-638f-11ea-92a1-ffdb6fddaf04.png)
