### ISSUE TITLE
PT: trying to modify routing.xml 

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/OsmAnd#8638]
Related with https://github.com/osmandapp/Osmand/issues/8224

Here is my routing.xml
I have changed "walkChangeRadius" and "maxTimeRoute".

I have tried to change time per stop depending on tags "bus=yes" "subway=yes" and "train =yes".
I have also tried to change bus speed with a tg relation.
I have also tried to establish a delay for traffic lights, crossings etc. so that they are taken into account just as they are taken into account on car routes.

[Mod.xml.zip](https://github.com/osmandapp/Osmand/files/4298274/Mod.xml.zip)

**Comment by hvdwolf** [comment]
You created a modified profile, but you kept the name the same. In that case OsmAnd might not know which one to use: the default one with the same name, or your modified profile.

I removed the unnecessary profiles above it and renamed the profile to "my public_transport". And that was all I did.
Please try attached. 
[PT-routing.zip](https://github.com/osmandapp/Osmand/files/4303569/PT-routing.zip)
Note that when creating a new profile, you now have to go back in the profile and:
- Go to navigation settings (2nd option)
- Select Navigation type (top one)
- Now scroll down and select the "my public_transport" navigation type

**Comment by OpenSourceForEver** [comment]
I know I have to select "navigation type" I dit it with my routing file.

Your file do not work for me.

**Comment by OpenSourceForEver** [comment]
I have tried to change routing.xml again and I think there has been a change in the code that has allowed me to set "maxspeed" as speed for buses. I have changed some parameters to generate more accurate route times but I would need to establish delays for traffic lights and speed bumps. Could someone change the code to achieve this?

The parameters that I have changed are:
+ Time per stop: 60 seconds
+ Subway speed: 50 km/h
+ Bus speed: "$maxspeed" (more appropriate for interurban routes and does not lose precision on urban routes if a delay is established for traffic lights, crossings and speed bumps)
+ 
[routing.zip](https://github.com/osmandapp/Osmand/files/4742524/routing.zip)
Trolleybus speed: 40 km/h

if I could set a delay for traffic lights, crosswalks and speed bumps the calculated times for the routes would be much more accurate, since now the estimated times for public transport are imprecise. 

I attach the routing.xml file so that if someone wants to, they can test the highest precision of these parameters. I have tested it on public transport in Spain thanks to the daily use of public transport and times provided by operators.

**Comment by OpenSourceForEver** [comment]
Bus speed is changed with https://github.com/osmandapp/OsmAnd-resources/commit/ac60ba87739712abd7e0b2f33012049d62424b88 

Need to change the following parameters:
1. Set the value of the "interval" tag as boarding time.
2. Ad a delay for traffic lights, crossings etc. so that they are taken into account just as they are taken into account on car routes.
3. Increase "walkChangeRadius" value up to 600 (It would be advisable for towns/villages with little variety of public transport (especially small towns/villages).

**Comment by vshcherb** [comment]
I think there is another request about adding interval to PT routes - https://github.com/osmandapp/OsmAnd/issues/10000

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/6700

**Comment by OpenSourceForEver** [comment]
What about adding a delay for traffic lights, traffic calming, crossings...?  (exposed in this issue)

> 
> Need to change the following parameters:
> 
> 1. Set the value of the "interval" tag as boarding time.
> 2. Ad a delay for traffic lights, crossings etc. so that they are taken into account just as they are taken into account on car routes.
> 3. Increase "walkChangeRadius" value up to 600 (It would be advisable for towns/villages with little variety of public transport (especially small towns/villages).

**Comment by vshcherb** [comment]
Please create a separate issue but I guess it's not possible in a feasible future, the most important would be to introduce a tag like "interval_stop" that will be aligned with schedule. I think the simple PT tags not using GTFS:
1. Interval - approximately how often 
2. Opening hours - when
3. Time to next stop in minutes

That would allow to build approximately all routes for something more precise it will be better to use GTFS.
