### ISSUE TITLE
Extend 'Auto-record track during navigation' until user acknowledgement

### ISSUE THREAD

**Issue by InsertUser** [osmandapp/OsmAnd#8645]
I use the "Auto-record track during navigation" option on OsmAnd. 

When I am close to the destination, the app asks if I am finished navigating and immediately stops track recording before I have responded. It will do this even if the navigation preview shows several more steps to reach the destination.

I am often still driving because there are service roads that require me to go past the destination marker and loop back to reach it or I have to find parking. Sometimes these roads aren't recorded in OpenStreetMap or (more rarely) OSM is out of date and there is new road geometry to deal with. 

I would like the gpx track to continue to record (and navigate) until I have actually reached my destination, indicated by my response to the options presented. I think this is related to issue #8640 where users see a map style change before they expect to. 

Software versions:
App : OsmAnd+ 3.6.3
Phone : Android 9

Note that it is more difficult to reproduce this when simulating navigation as GPS inaccuracy is not simulated, but it does show that the simulated track stops short of the destination.

**Comment by pebogufi** [comment]
Fully agree, quite often I have to restart recording after routing is "ready" until I am really at destination point, where I stop it.
