### ISSUE TITLE
New feature: search in local OSM data aka overpass-api

### ISSUE THREAD

**Issue by RussianFox** [osmandapp/Osmand#8646]
I've recently known that Osmand stores full OSM base in it's data. It would be great to have a possibility to search across the base using my search requests and to save these requests in the Search menu

**Comment by jomo** [comment]
Something like overpass-api would definitely be overkill, but being able to search for any given combination of tags (with or without values) would be helpful.

**Comment by vshcherb** [comment]
Nope, OsmAnd doesn't store full OSM-base and it is even not working like that. OsmAnd uses only POI information to search, we're going to rework UI for custom POI categories for OsmAnd though it is still very very limited options to search. 
Anyway, who wants to search specific objects is better to create own maps and specify custom poi_types.xml during creation. So it will be possible to use that data in OsmAnd later
