### ISSUE TITLE
City and street search failed

### ISSUE THREAD

**Issue by max-klaus** [osmandapp/Osmand#8647]
carrer de Vic, Sant Bartomeu del grau

**Comment by hvdwolf** [comment]
De general search doesn't work indeed
When I search under Address  and select city/town/locality and type in "Sant Bartomeu del grau". It finds the town. When I simply continue to type with "carrer de Vic", it also finds that one

As there are no housenumbers you need to select one of the crossings.

**Comment by vshcherb** [comment]
Latest result:
- 'Carrer de Vic' - finds street correctly but it is 3rd place. So it is a last step sorting issue. Cause all 3 results fit though only 1 has complete match.

- 'Carrer de Vic, Sant Bartomeu del grau' - finds street "Sant Bartomeu del grau" in Vic city though the biggest problem that it doesn't list correct result at all.

**Comment by vshcherb** [comment]
<img width="709" alt="Full search" src="https://user-images.githubusercontent.com/1042025/82756038-d0830b80-9dd7-11ea-83fa-60bdc511445e.png">
<img width="822" alt="Street search" src="https://user-images.githubusercontent.com/1042025/82756040-d24ccf00-9dd7-11ea-9b0c-303c17ef3551.png">
Fixes improved search by still, the results are on 4th and on 2nd place (full search). Right now the issue that matched words are misordered and prioritizing another result

Tests still need to be added!

**Comment by hvdwolf** [comment]
_"Tests still need to be added!"_
What do you mean? You want us to test? Or do you mean automatic tests via the compilation/build?
Or even something else?

**Comment by vshcherb** [comment]
Junit tests are already added. Issue is not closed yet
