### ISSUE TITLE
Save button for app profiles is greyed out

### ISSUE THREAD

**Issue by bege10** [osmandapp/Osmand#8648]
OsmAnd 3.5.5
Samsung Galaxy S5 Plus (SM-G901F), LineageOS for microG 16 (Android 9)
App data (e.g. offline maps) on external storage 2

I cannot change the speed parameter for navigation because the "save" button in the app profiles is greyed out. Write access seems to be OK because I can save favorites.

**Comment by hvdwolf** [comment]
Please upgrade to 3.6.2.
The 3.5.5 is rather buggy. The 3.6.x releases work much better.
Note: Creating a profile needs the save button. Once a profile is created all modifications are "auto saved"

**Comment by bege10** [comment]
Thank you. Strange, F-Droid didn't show the new version for update, it still "recommends" 3.5.5.
3.6.2 solved the problem.
