### ISSUE TITLE
Wrong routing when target is close to bigger road

### ISSUE THREAD

**Issue by ronnystandtke** [osmandapp/Osmand#8649]
I'm using OsmAnd version 3.5.5 on a Samsung Galaxy S5 with LineageOS 16.0 (Android 9), the OsmAnd offline maps and in-app offline routing with the car profile.

I tried to navigate to an underground parking in Bern, Switzerland, Belpstrasse 18, only accessible via a oneway service road from the south (no left turn from the north), see here:
https://osm.org/go/0CZwkmfO_?m=
You can reproduce the issue by setting the start point to this location:
https://osm.org/go/0CZwkTIC?m=

OsmAnd navigates the user just to the middle of Belpstrasse and seems to ignore the last part of the route (maybe because the target is too close to the larger street?), see this screenshot:
![OsmAnd Bad Routing Bern](https://user-images.githubusercontent.com/1651625/76159545-0e01c200-6122-11ea-96ef-6d48a390b384.png)

I would have expected that OsmAnd takes the full route into account, including the last part with the oneway service road, and would have calculated a route where the last part of the route is coming from the south where the service road to the underground parking is actually accessible.

Thank you for this very useful app and for fixing all these little nasty routing bugs.

**Comment by hvdwolf** [comment]
V 3.6.2
It does indeed not work with car navigation. 
It does work with pedestrian and bicycle navigation.

@ronnystandtke: Please update to 3.6.2. The 3.5.5 version is quite buggy

**Comment by ronnystandtke** [comment]
OK, I upgraded to v3.6.2 but, as you already confirmed, it still doesn't work with car navigation.
