### ISSUE TITLE
add 12t and 30t to permitted weight

### ISSUE THREAD

**Issue by hvdwolf** [osmandapp/Osmand#8650]
12 tons seems to be an important max. value in the truck industry.
30 tons was added to simply have a smaller gap between 20t and 40t

see mailing list: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/osmand/66wqaInupU4/2QVS5rY0AgAJ

I created a pull request
https://github.com/osmandapp/OsmAnd-resources/pull/613

**Comment by naoliv** [comment]
Maybe `weight`, `height`, `width` could all be free input fields (see also #8112 #8634)

**Comment by hvdwolf** [comment]
It was also commented that for truck driving the length is also important. 
Sometimes cities do not allow trucks if they are over xy meters.
