### ISSUE TITLE
Downloading slows then OOM crash

### ISSUE THREAD

**Issue by kevinmcmurtrie** [osmandapp/OsmAnd#8651]
OsmAnd+ 3.6.3, 2020-02-28, Galaxy S9+, Android 10, files on 1TB microSD card, 300Mbps WiFi capacity.  I've observed this on older "backup" phones too.

Long downloads start out reasonably fast at about 12MB/sec, suddenly drop to about 1MB/sec, decline further into KB/sec territory, then crash on OOM.  The rate at which it slows down seems to be random - maybe in the middle of one large download or it may not start until after many downloads.  The app becomes gradually unresponsive during this time too.  App recovers after restart.

The easiest way to reproduce is to queue up a large number of large downloads.  Queue the western US, Japan, or China in one shot.  Odds are low that it will ever finish.

**Comment by vshcherb** [comment]
How many maps to schedule 1 GB  or 10 GB (10 files or 100 files)?

**Comment by kevinmcmurtrie** [comment]
I don't see a fixed point where it becomes slower. It may happen at any time, even on a single map. Selecting many maps makes it reproducible. I do have tens of GB of offline maps installed.

Select all of the Western USA or all of China, or all of Japan for download (standard + contour + hillshade + Wikipedia). It will usually slow down before 10 maps are downloaded. It will repeatedly slow down until it's essentially stuck.

If you leave it running, and OsmAnd+ will be killed in the background.  Force the app to stay in the foreground with a charger and developer options, and OsmAnd+ crashes on OOM after several hours.

-----Original Message-----

**Comment by kevinmcmurtrie** [comment]
In 4.4, the UX slows down but downloading continues and there's no crash.

**Comment by dmpr0** [comment]
_Crashes panning or zooming urban areas, same as the non-beta. Singapore, Edinburgh Scotland, California US, Tokyo Japan, etc. It's mostly unusable._
5202

**Comment by kevinmcmurtrie** [comment]
I think you meant to reopen #23347
