### ISSUE TITLE
Routing: ignore restrictions via ways 

### ISSUE THREAD

**Issue by RussianFox** [osmandapp/OsmAnd#8652]
In OSM wiki states that 'via' can be a way. And it is sometimes necessary. But Osmand is ignoring ways in 'via'

**Comment by vshcherb** [comment]
OsmAnd doesn't use yet "via" at all it uses only start and end of restriction, it is probably a duplicate feature request. Anyway it is not currently possible with existing routing engine

**Comment by Hedaja** [comment]
I have an example where this is important to have.
https://www.openstreetmap.org/#map=18/42.63348/-83.74882
https://ahorn.lima-city.de/tr/?zoom=19&lat=42.633518&lon=-83.748906&layer=Grayscale&overlays=TTT
The GraphView Plugin in JOSM handles this crossing just fine. Unfortunatly OsmAnd doesn't prevent you from turning back onto the big highway.
![photo_2020-12-22_14-07-46](https://user-images.githubusercontent.com/693781/102892895-df5e9900-4460-11eb-8df4-b6385a04c19c.jpg)

**Comment by vshcherb** [comment]
Not clear if you have restriction "from" 1 way "to" 2nd way via "3rd way", osmand should support that restriction. I think currently it is not supported to have it via multiple ways but it's definitely possible via single segment

**Comment by Hedaja** [comment]
It's one vía way only(seehttps://www.openstreetmap.org/relation/12047679If). If one vía way is supported then this might be an issue with routing on OsmAnd live data. I just recently made this change so its not in the normal map update yet. 

I'll see if I can find an older example and reportbback on results there.

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd/pull/10539
https://github.com/osmandapp/OsmAnd/pull/10541
https://github.com/osmandapp/OsmAnd-core/pull/176
https://github.com/osmandapp/OsmAnd-resources/pull/662/files

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd-resources/pull/664

**Comment by Hedaja** [comment]
Just got the latest beta update and was able to test it. It works fine now. Thank you for the quick fix!
