### ISSUE TITLE
Compilation of nightly build / QT build fails 

### ISSUE THREAD

**Issue by hvdwolf** [osmandapp/Osmand#8653]
I try to compile the repo/git versions of the Nightly build and the QT nightly build.
For the last week or so, both fail on: 
```
net.osmand.util.OpeningHoursParserTest > testOpeningHours FAILED
    java.lang.AssertionError at OpeningHoursParserTest.java:97
```
Note that the code defaults to en_US, while all my systems are on nl_NL (Debian and Ubuntu/GalliumOS)

Note2: We had something like this a couple of months ago. Then it needed to default to us_US. I can't find that issue back but as soon as have found it I will link to it (when relevant)

**Comment by vshcherb** [comment]
it changes locale during the test 

https://github.com/osmandapp/Osmand/blob/master/OsmAnd-java/src/test/java/net/osmand/util/OpeningHoursParserTest.java#L118

**Comment by hvdwolf** [comment]
I did see that, but when changing it to nl-NL or completely outcommenting the line, it still doesn't work correctly.
And from that point my limited java knowledge more or less stops.

**Comment by vshcherb** [comment]
I have little understanding how it could be but it is related purely to dev environment so I don't think we're going invest much time into that issue.
You can always run without tests like "gradle -x test" or try docker env to compile it (was mentionned somewhere probably easier to google it).
