### ISSUE TITLE
Lanes widget: display left/right turn together

### ISSUE THREAD

**Issue by RussianFox** [osmandapp/Osmand#8656]
In combination "turn:lanes=left|left;slight_right|slight_right" ignoring second "left"
https://www.openstreetmap.org/way/362796525
![image](https://user-images.githubusercontent.com/11329995/76294388-d2066280-62c3-11ea-9053-a8c4ab24f596.png)

**Comment by vshcherb** [comment]
it is a known issue we simply need to display it on UI
