### ISSUE TITLE
Defibrillators are no more displayed via POI overlay

### ISSUE THREAD

**Issue by rbovard** [osmandapp/Osmand#8666]
Hi,

Since several weeks, the defibrillators are no more displayed via POI overlay setting:
- Configure map > POI overlay > Defibrillator

I found this old issue https://github.com/osmandapp/Osmand/issues/4265, don't know if something similar is happening again?

Thanks for your work.

OsmAnd+ v3.6.3
Maps of March 2020

**Comment by xmd5a2** [comment]
This is because defibrillators were moved from "Emergency infrastructure" to "Emergency" category in this commit https://github.com/osmandapp/OsmAnd-resources/commit/dfb75037c0d1c8730940b8c482ee904a2d798ba2. April maps and OsmAnd >3.6.3 should work fine.
