### ISSUE TITLE
Search: results after not sorted by distance

### ISSUE THREAD

**Issue by arbitrary-dev** [osmandapp/OsmAnd#8677]
## Reproduction

1. Search for "Spice Riga"
1. Select "Spice Building"
1. Actions – Search nearby – "Lido"
1. Observe that the closest match "Lido Spice" isn't the first in result set

**Comment by Zirochkabila** [comment]
@arbitrary-dev Please give a more detailed description of the query, as Lido Spice is not shown in the results
But, if we were talking about the fact that the search results are not placed in ascending order of distance, yes, this is confirmed
OsmAnd~ 4.4.0#14164mqta, Released: 2023-02-09

https://user-images.githubusercontent.com/104760013/218256531-147805fc-5010-42bf-bb5d-5fb2650a9fad.mp4

**Comment by vshcherb** [comment]
Looks like it's duplicate https://github.com/osmandapp/OsmAnd/issues/16397
