### ISSUE TITLE
My Places/Tracks shows wrong checkbox status of headlines

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#8684]
Go to My Places/Tracks, then tap the Show on Map button (middle one in the bottom row). Then tap the checkbox for an entire folder  like e.g. Tracks. All tracks contained will be correctly tickmarked, return to the map to see them displayed . Now from the map return to the same screen, and verify the tick box status: While all track entries under the previously selected folder will correctly have their checkmarks on, the checkmark for the folder headline is incorrectly off. When the folder is collapsed, there is zero indication it contains visible tracks at all.

The situation becomes clumsy if you have many tracks enabled and want to disable them all again: You can neither do this with one tap for the 'Visible' group (this headline is missing a checkbox entirely! We should palace on there!) , nor do you see an indication in which folders the visible ones are located.  You may end up manually unchecking dozens of line items one by one in the 'Visible' section.

**Comment by vshcherb** [comment]
I think it will be also addressed to gether with #8685 in 3.8 release
