### ISSUE TITLE
Simplify the UI by retiring the Show GPX data dialog

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#8685]
I see many user struggle with the deficiencies of our old Show GPX data dialog, which you reach by tapping Configure map/GPX files. Its tickbox status is often buggy (#7763 would still require a reasonable fix), it has no folder management  and overall is missing all essential GPX management functionalities.

I propose that instead of maintaining two GPX management interfaces, we retire this one and instead link Configure map/GPX files to our more powerful My Places / Tracks (preferably open that one directly in its 'Show on map tick mark' state).

We would save the maintenance of two separate dialogs and related bugs, simplify support, and simplify user experience.

We will only need to slightly improve the My Places/Tracks interface with #8684 (which is a bugfix), and by maybe adding an the overall color/thickness "Appearance" selector for all visible tracks like we currently have it on the Show GPX data dialog.

**Comment by vshcherb** [comment]
Yes definitely now it becomes obvious that we need to change track management screen with "Search" provided and different sorting options cause number of tracks typically  exceeds the reasonable amount for this UI. Obviously it should impact on Select GPX in Configure Map

**Comment by sonora** [comment]
Just to be clear: Screen `My Places / Tracks` already has it all, pretty much, so we could likely focus on using that. (And also linking it as target for when user taps on the caption of `Configure map / GPX files...`)

**Comment by faramir** [comment]
It could be nice to have also possibility to order tracks in `My Places / Tracks` by date, but in descending order (the most recent on top).

**Comment by smirnov-d-a** [comment]
I think it would be nice to have configurable sorting order, since basically everyone has their own preferences on that. For instance, I would like to sort tracks by date in ascending order (oldest on top, newest on bottom). At the very least I can deal with alphabetical sorting, since I can rename tracks accordingly myself.

**Comment by vshcherb** [comment]
Moved to https://github.com/osmandapp/OsmAnd/issues/10704
