### ISSUE TITLE
Add “hasFragileUserData”  + Update target sdk 29

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#8686]
Since Android 10, apps can add a flag that allows system to ask the user about app data while deleting or reinstalling the app.

If true the user is prompted to keep the app's data on uninstall
https://developer.android.com/reference/android/R.attr#hasFragileUserData

**Comment by vshcherb** [comment]
Upgarde targetSdkVersion 28 ->  29
https://developer.android.com/about/versions/10/behavior-changes-all

**Comment by Chumva** [comment]
This should be added here https://github.com/osmandapp/OsmAnd/pull/10022. But it needs testing because I wasn`t able to check hasFragileUserData.
