### ISSUE TITLE
UI: use space moreefficient on small (1024x600px) displays

### ISSUE THREAD

**Issue by Tobi7241** [osmandapp/OsmAnd#8690]
See: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/osmand/YcUimBeCq34

the newer version increase the space around text and add more "dead" area so it becomes impossible to easily navigate on smaller display sizes like 2 year old car navigation radio systems with HD 1024x600 Pixel display.

**Comment by dmpr0** [comment]
I can't see any dead area, only the big screen with the small resolution, you can try to decrease UI scale in system settings this must work from Android 6.

**Comment by Tobi7241** [comment]
I can easily think of serveral areas of "wasted space" especially if you cannot easily upgrade your Android devie every year.
Once you select "car usage" there is no option for bicycle/pedestrian of the car anymore
I really like the mute Audio button, but now it takes an own row and cannot be a floating panel.

Search:Adress/ Search:Favorites has to become more space saving, you will have more than a single POI ?

![edit2020-03-18 21_43_41-IMG_20200306_092735128](https://user-images.githubusercontent.com/62337620/77006137-3b404280-6962-11ea-85ef-7724df032b10.jpg)
![edit_2020-03-18 21_45_36-IMG_20200306_092752358](https://user-images.githubusercontent.com/62337620/77006141-3bd8d900-6962-11ea-87d1-dc59cef41458.jpg)
