### ISSUE TITLE
Navigation issue for the pedestrian route

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8696]
from: 47.88853 35.05997 
to: 47.85688 35.09721
OsmAnd suggests to make a hook while in pedestrian navigation profile, while there is a possibility to make the route shorter
![image](https://user-images.githubusercontent.com/50198677/77058473-299c8080-69de-11ea-8089-df786f0ee6b4.png)

**Comment by hakuchi** [comment]
check connections/crossings on OSM

**Comment by scaidermern** [comment]
This is a map data issue. There is a short stretch with `foot=no`: https://www.openstreetmap.org/way/163080374

**Comment by hakuchi** [comment]
@katerynakocherhina can the dam be accessed by foot or is it prohibited?
If not, this way calculated from OsmAnd looks ok for me

**Comment by scaidermern** [comment]
> @katerynakocherhina can the dam be accessed by foot or is it prohibited?
> If not, this way calculated from OsmAnd looks ok for me

@katerynakocherhina Could you please respond to this question? Do you have local knowledge of this area and can tell us if the map data needs to be fixed?
