### ISSUE TITLE
Audio Delay in all modes.

### ISSUE THREAD

**Issue by ilyaguy** [osmandapp/Osmand#8706]
I've installed OsmAnd on android car radio, and there's issue:
Car radio cut beginning of audio advice.
OsmAnd has option to change delay before start output, but it works only in "Phone Call Channel" and it seems that my car radio doesn't use this channel at all.
Is it possible to allow this delay works in every audio cahnnel?

**Comment by sonora** [comment]
Can you please describe your setup, both in terms of hardware and the configuration/settings on all systems?

I do not currently understand the request, because from all setups I have come across, for the media (i.e. music) and notification (I.e. ringtone) channels to be auditable on the car stereo at all, the stereo needs to be set to Aux/bluetooth input, meaning you would **always** (exclusively and permanently) hear only the external device, and it would be an 'always on' situation (not the interruption situation I implement via the phone call channel). Hence it is unclear why there should be a cut-off at all.

**Comment by ilyaguy** [comment]
2DIN Android car radio CT-0011 (Android 6.0, touch screen 1024x600).
Installed latest OsmAnd+ from playmarket on it. So, there's only one device.
I've configure voice guidance. It works mostly fine, except one thing: osmand or device cut about 0.5 seconds beginning of phrase. 

I've opened development plugin and go to "Test Voice" screen. When I tapped on phrase there's no first word for all of them. Or, if word is long enough, I hear end of it: "...га" instead of "Увага", etc.

In development plugin there's option to change delay before audio, but it works only if "Phone Call Channel" selected to use voice notifications. But if I selected it, there's no sound at all. (This is a problem of device, I think). 

My request is about enabling this delay for all audio output mode: "media", "notifications" and "phone call".

I can shoot and upload video if it could help.

**Comment by sonora** [comment]
Ok, I think I understand the issue now, let me think about it as time allows. I have to find a solution not complicating the world for the 99% of users not needing this. If I expanded the timeout to just the notification channel, would that work for you?

**Comment by ilyaguy** [comment]
I think it will help. Because when I tap two or more times on the same phrase I heard second and following plays completely and without any cuts.

**Comment by sonora** [comment]
@vshcherb 
I think as time allows I will convert and expand the current osmandSetting SCO_BT_DELAY into an array VOICE_PROMPT_DELAY[3], with respective default values of 1500ms, 0ms, 0ms for the phone call, notification, and media voice output channels. Please note that this will remain a global, not profile, setting, as triplet is needed per voice channel, not per app mode. The amount of corresponding code changes is moderate, I see no risk of adverse effect.

Ok? Or any better idea?

**Comment by vshcherb** [comment]
Hard to say sounds quite a niche issue / request so we need to see how it looks and is it easy to understand :-)

**Comment by sonora** [comment]
Hi Victor, true. It is straightforward to fix, though, see here: https://github.com/osmandapp/Osmand/pull/8727/files

I have tested that it works as expected. Should also fix the original issue, to be verified on the specific hardware. No adverse effect for all users not requiring this.

**Comment by vshcherb** [comment]
I think this code will require some review / refactoring, at least I don't see need to use settings when it is mostly constants, so I will leave PR open still and assign it to 3.7

**Comment by sonora** [comment]
Note that there is no change to the UI. This is a simple expansion of my 2016 implementation for establishing the BT SCO link, with the delay now selectable for all audio streams. Just like before, adjustable only via the development plugin, this has suited us for some years now.
