### ISSUE TITLE
Poland: fix road-only map not updated since 2019

### ISSUE THREAD

**Issue by gjedeer** [osmandapp/Osmand#8707]
There is a road which is displayed as 2 roads in Osmand. I checked OSM data in editor and web viewer and it looks like it's not a problem with data.

https://www.openstreetmap.org/#map=17/53.87708/15.18617

https://www.openstreetmap.org/note/2127009

![Screenshot_20200323-102331_OsmAnd~](https://user-images.githubusercontent.com/315648/77312437-4ac4e000-6d02-11ea-8cd1-e969708d9c94.png)

![Selection_310](https://user-images.githubusercontent.com/315648/77312464-56180b80-6d02-11ea-9a07-5d131c555478.png)

The same can be observed at another location, https://osmand.net/go?lat=53.8037&lon=15.127468&z=16

OsmAnd~ 3.6.3, maps up to date.

**Comment by gjedeer** [comment]
I've found a solution for this: I've had a country-level map from March 2019 and a region-level map from March 2020. Disabling one of these fixes the problem.

I'm not closing it because it still feels like a bug to me.

**Comment by scaidermern** [comment]
> I'm not closing it because it still feels like a bug to me. Shouldn't the more specific map override the less specific one?

And shouldn't OsmAnd warn the user about the outdated map?

**Comment by gjedeer** [comment]
It's not outdated, March 2019 is the latest available for Poland

**Comment by scaidermern** [comment]
Indeed, the last roads-only map of Poland is from 2019. @vshcherb This looks suspicious. Is this intended?

**Comment by vshcherb** [comment]
Poland is not supported any more cause it became bigger than 2GB, so we have technical limitations with this region.

**Comment by scaidermern** [comment]
> Poland is not supported any more cause it became bigger than 2GB, so we have technical limitations with this region.

The Poland road-only map from 2019 can still be downloaded in OsmAnd.

**Comment by gjedeer** [comment]
> The Poland road-only map from 2019 can still be downloaded in OsmAnd.

Yeah, this is confusing, how should someone know that it's not supported any more? I was using it out of convenience, 1 download instead of 16, had no idea it's unsupported.

**Comment by scaidermern** [comment]
@vshcherb Could you check the Poland road-only map again, please? Either it needs to be updated or it needs to be removed. The current state doesn't seem to be correct since the map from 2019 is still offered for download.

**Comment by vshcherb** [comment]
the map is only for roads-only is offered and not complete one

**Comment by scaidermern** [comment]
> the map is only for roads-only is offered and not complete one

Not sure what this is supposed to mean. There are road-only maps for other large countries such as France or Italy. They are from 2020. The Poland road-only map however is from 2019.

**Comment by gjedeer** [comment]
Maybe let's clear one thing, I'm not a new user and that map has been installed for a long time. No idea if it's still available for download.

But how do you expect users to know they're supposed to download new region-wide maps now? Should everyone open a github issue?

**Comment by scaidermern** [comment]
> Maybe let's clear one thing, I'm not a new user and that map has been installed for a long time. No idea if it's still available for download.

It definitely is. I don't have it installed but it gets still listed and the download works.

**Comment by scaidermern** [comment]
No reply from @vshcherb, I guess this will stay broken :(

**Comment by scaidermern** [comment]
There is also a Poland Wikipedia file from 2018 still listed for download. This seems wrong, too. Probably a leftover from the splitup into individual regions, like the roads-only map.

**Comment by vshcherb** [comment]
* I don't see Poland map listed, there are only new files listed 2020
* Yes, wikipedia was wrong too. And I deleted it.
* Poland road only map  is going to be updated.

If you delete old files and download new ones, you shouldn't see the duplicate roads

**Comment by xmd5a2** [comment]
Roads only map fixed

**Comment by scaidermern** [comment]
> Roads only map fixed

Confirmed, thanks.
