### ISSUE TITLE
XXE in Osmand

### ISSUE THREAD

**Issue by prodigysml** [osmandapp/Osmand#8711]
While reading the code in the Osmand project we (@n33dle and I) identified a vulnerability we wanted to raise. The vulnerability is an XXE vulnerability (https://owasp.org/www-community/vulnerabilities/XML_External_Entity_(XXE)_Processing) and can be identified in the lines of code below:

https://github.com/osmandapp/Osmand/blob/963acad11fd80c24549cfcfa3b9596769864696a/OsmAnd-java/src/main/java/net/osmand/binary/BinaryMapIndexReader.java#L2205-L2219

**Comment by vshcherb** [comment]
It's quite interesting finding, though it is a place of a test method and it is not used at all.
