### ISSUE TITLE
Not possible to delete the GPX traces using IOS

### ISSUE THREAD

**Issue by Pecita** [osmandapp/Osmand#8730]
I use OSMAND 3.13 on IOS 13.4 mainly to record GPX traces (It is very very complicated!).
It seems to me that it is not possible to delete the GPX traces that I no longer need. What about?

**Comment by dmpr0** [comment]
Hello, @Pecita ! Thank you for the feedback.
You can delete GPX tracks in Menu — My places — Trips — Open needed track, tap 3 dost button in the right top corner — choose Remove.

Yes, it looks hard to find, I think we need to add Remove button on the Trips screen.

**Comment by Pecita** [comment]
Argh! Thanks, it works.
In functionality OSMAND is the most relevant trek maps software but in ergonomics it is really bad.
You should group everything related to GPX traces clearly under a primary submenu and not disseminate these functions everywhere. Conversely, I do not understand the sense of the My Places submenu if not as a labyrinth.
For a hiker, GPS tracks are the most important feature.

Congratulations to you.
