### ISSUE TITLE
Lane guidance not working in recent night builds

### ISSUE THREAD

**Issue by jfburke3** [osmandapp/Osmand#8732]
What version of OsmAnd are you using, on what device and Android/iOS version?

Night builds 3.5.6#29283m, released 2020-03-28 and 3.5.6#29292m, released 2020-03-30.  Samsung Galaxy S7 Edge, Android 7.0

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

OsmAnd offline maps

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.

US Georgia, US Florida, both dated Feb 29, 2020.  Also have OsmLive enabled on this phone (my "test everything" phone).

Tell us whether you have used OsmAnd's in-app offline routing, or any online routing provider like YOURS, OpenRouteService or OSRM.

OsmAnd's in-app routing

What routing profile is chosen in OsmAnd app? (car, bike, pedestrian, fastest or shortest)

Car profile, all route modifiers at defaults (e.g., no "avoid" modifiers enabled).

Please specify as exactly as possible the start and end point of your route by telling us city name and street name so that we can find it via in-app address search easily. Also, a permalink from openstreetmap.org can be helpful.

The last few night builds of OsmAnd do not highlight the lane guidance arrows at the top of the screen.  The appropriate number of arrows are displayed (they appear to match the lanes=* value correctly), but arrows are no longer highlighted in yellow/green as appropriate for lane guidance.

I don't think it matters what start/end points you select, but an easy example is to start at this church https://osm.org/go/ZHDT1_5wf?layers=N&way=785891643 with this gas station as the end point https://osm.org/go/ZHDHxmRea?layers=N&way=316471352.  Route along I-75, and observe the lane guidance arrows along the way.

It worked in night builds a few days before the 03-28 one (not sure exactly which one, haven't had time to determine that yet).

**Comment by jfburke3** [comment]
This might be fixed. Seems to be working in build 3.7.0#29302m released 2020-03-31.

**Comment by max-klaus** [comment]
Yes, it was fixed yesterday.
