### ISSUE TITLE
opening_hours:covid19=

### ISSUE THREAD

**Issue by pqhf5kd** [osmandapp/Osmand#8742]
A team in France have put together a [tagging scheme](https://wiki.openstreetmap.org/wiki/Key%3Aopening_hours%3Acovid19) for restricted opening hours due to the pandemic. They have also [launched a map](https://www.caresteouvert.fr/) to display these details. It currently only covers France, but according to their GitHub, it will be expanding worldwide.

The tag has already been [used 12000](https://taginfo.openstreetmap.org/search?q=opening_hours%3Acovid19) times, mostly in France.

Is this something OsmAnd wants to support?

**Comment by scaidermern** [comment]
Note that there are already various [other subkeys for `opening_hours`](https://wiki.openstreetmap.org/wiki/Key:opening_hours#Similar_tags):
- `opening_hours:office`
- `opening_hours:kitchen`
- `opening_hours:reception`
- `opening_hours:workshop`
- `opening_hours:atm`
- `opening_hours:drive_through`

**Comment by yopaseopor** [comment]
Now is available also for Spain, Andorra, Germany... Please take in consideration these tags

opening_hours:covid19=same
opening_hours:covid19=open
opening_hours:covid19=off
opening_hours:covid19=restricted	
opening_hours:covid19=*

description:covid19=*
delivery:covid19=yes/no
takeaway:covid19=only
note:covid19=*

**Comment by vshcherb** [comment]
We think to take into consideration opening_hours:covid19 similar to opening_hours:atm by applying extra rule of appending "|| covid19 <value>" cause this approach is supported by UI in  OsmAnd.

We have no plans to support other tags (i.e. replace the values in the application) cause it is not clear whether these tags will stay longer than 6 months (even 3 months is not clear). Usually we consider to support tags for 12 months+

**Comment by overflorian** [comment]
Hi, I think you're right: in most countries the tag might not last more than 6 months. Nevertheless I think you also should consider the emergency and the uniqueness of the situation.

The tags now have 24000 uses all around European countries. Would be glad to have an approach similar to Qwant Maps (see https://www.qwant.com/maps/place/osm:node:6597224025@Carrefour_Market_G%C3%A9vez%C3%A9 ) where lockdown opening hours are shown before usual opening hours.

Our team is a your disposal to discuss the details.

**Comment by vshcherb** [comment]
Yes, we're considering to have it displayed and probably add it to other tags. For us it doesn't mean that can immediately propagate this tag to all users but we can try to add a generic solution in 3-5 weeks which will work for other "mid-term" and "long-term" restrictions or special occasions.

**Comment by overflorian** [comment]
ok that's duly noted. Thanks for your consideration and don't hesitate to contact us if needed. Regards

**Comment by vshcherb** [comment]
Should be present in new maps - middle of May
