### ISSUE TITLE
Navigation issue: roundabout is displayed instead of straight line

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8744]
When navigating from :47.99543° N, 18.17085° E
to: 47.99471° N, 18.17321° E , 
in 47.99500° N, 18.17161° E, the widget on the left panel displays the roundabout when both in OsmAnd and in OSM there is a turn.
![image](https://user-images.githubusercontent.com/50198677/78134767-52ceff00-7429-11ea-83fb-9ccd75a97516.png)

**Comment by vshcherb** [comment]
Fixed on the map
