### ISSUE TITLE
Route calculation in pedestrian profile

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8758]
While in car navigation profile the route is calculated, in the pedestrian profile the error notification appears: "Attempt to get length of null array".
from: 48.69419° N, 9.41374° E
to: 48.72947° N, 9.33711° E

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/commit/9a7fcbd7b8be3a677c36f8b278150eb157b504dd
