### ISSUE TITLE
Zip codes missing in search result >> impossible to pick the right search result

### ISSUE THREAD

**Issue by bugzillus** [osmandapp/Osmand#8761]
In large cities, the same street name can apply to several different streets. It can be distinguished only by zip code. Example: In Berlin, there's several streets called "Hauptstraße" or "Berliner Straße". Plus, a street can be related to more than one zip code.

1. Osmand still does not accept zip codes as town reference or zip + town name (in case, a zip code refers to several towns). In Europe, most countries list the zip code first, then the town. So, if available, entering the zip code plus blank could extremely shorten the still very slow (offline) search.

2. Osmand still does not show the zip codes in the search results. In the sample case of Berlin, the neighbourhood names are shown (which are a subset of city districts), but a street address is usually referred to by zip + town like 10115 Berlin. The neighbourhood names and boundaries are sometimes not even known to habitants of other parts of the city, and usually not to guests and tourists. So, the zip code would be mandatory to pick the right street and not go to an opposite part of the city.

3. Zip codes are not even shown in the location info of any clicked point in the map. So, it cannot be verified, if the address is the correct one.

Thanks for adding the zip code to search and location info.

**Comment by littlehelper** [comment]
For me, this would be very helpful too.
Similar to #5795 ?
Related to #4176, #4174 ?

**Comment by vshcherb** [comment]
Right now it should not be a problem cause there is District name in braces so it is easy to get where the street belongs to.
![image](https://user-images.githubusercontent.com/1042025/84417870-8c389d80-ac16-11ea-8273-f9a5d66f0ca5.png)
