### ISSUE TITLE
[Request]: Split the region France_provence-alpes-cote-d-azur_europe_2.obf.zip

### ISSUE THREAD

**Issue by tuxayo** [osmandapp/OsmAnd#8762]
Hi, it's currently
- 226MiB to download
- 332MiB to store
- 90MiB of OsmAnd Live for 4 months of updates

Having it split into it's [six departments](https://en.wikipedia.org/wiki/Provence-Alpes-C%C3%B4te_d%27Azur) (while keeping the whole region if it's worth it (?), like done for Bayern in Germany) would lead to:
- smaller first time downloads
- smaller monthly updates
- smaller OsmAnd Live updates
- smaller storage need

As phones with non-expandable storage are getting more and more common since years. If one wants to avoid the huge environmental and social cost of buying a new phone, then being able to trim storage usage is very very useful.

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/7e4963facf90f831392ce63f48e40c770a3ba8ff

**Comment by tuxayo** [comment]
@xmd5a2 Is that expected that can find the subregions in "other maps" and not in France_provence-alpes-cote-d-azur? Other regions have their subregions in them.

**Comment by tuxayo** [comment]
"other maps" seems to also contain other maps that seems to belong elsewhere
- Greenland (has northamerica suffix)
- Krasnoyarsk
- a few norway regions
- south sudan

**Comment by vshcherb** [comment]
New structure will be in the new application, old application will have new maps in section Other Maps

**Comment by tuxayo** [comment]
Thanks a lot, have a nice day :)
