### ISSUE TITLE
[Bug] On transfering favourites to a different device tag backround is lost

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#8764]
On transfering favourites to a different device (copying favourites.gpx or only a group by sharing it)
the shape of the icon (tag backround) is lost (not imported).
see #8032 
version 3.7.0#29361 2020-04-07

**Comment by vshcherb** [comment]
This feature is not released yet to 3.7 so all devices should be 3.7

**Comment by pebogufi** [comment]
version 3.7.0#29385 2020-04-10
export with this device and then immediately reimport with same device. Same problem as described.

**Comment by vshcherb** [comment]
Yes, 3.7 is broken.

**Comment by pebogufi** [comment]
Confirm fixed.
thanks !!
Peter
