### ISSUE TITLE
Osmand for cycling - whishlist 2 - pair with BLE HR and Cadence sensors 

### ISSUE THREAD

**Issue by jutuiz** [osmandapp/OsmAnd#8769]
The way Osmand shows speed, arrival time, battery %, etc... in an overlay on the right hand corner is just perfect.   There should be a way to pair external HR sensors (read: Scosche Rhytm+ or Polar OH1) and bike cadence sensors to the smartphone and have the readings displayed on screen.  

This would make sense in order to have the smartphone as the only device with you and fixed on your handlebar during a ride.

**Comment by littlehelper** [comment]
I agree. I know many people using their bicycle computer and Osmand on their smartphone at the same time although they are looking for a single device solution. Many of them claim that bicycle computers provide better support for (wireless) sensors but they do not want to go without Osmand because of its routing capability.

**Comment by vshcherb** [comment]
Merged into #7934

**Comment by vshcherb** [comment]
https://developer.android.com/guide/topics/connectivity/bluetooth/transfer-ble-data

**Comment by vshcherb** [comment]
Test apk https://github.com/osmandapp/OsmAnd/files/10568619/app-debug.zip is done and UI task to merge to OsmAnd https://github.com/osmandapp/OsmAnd/issues/15459.

**Comment by Zidar** [comment]
Please consider adding these two features to external sensors:

1. Power meter via BLE. Currently external sensors plugin seem to support only ANT+ for cycling power. My bicycle exposes power measurements over BLE using standard characteristic (00002a63-0000-1000-8000-00805f9b34fb, "Cycling Power Measurement"), but OsmAnd can't read it. The BLE device itself is successfully connected though, speed and distance are read correctly.

2. Battery level of BLE device. (00002a1b-0000-1000-8000-00805f9b34fb, "Battery Level State"). It can show battery level of heart rate monitor or e-bike.
