### ISSUE TITLE
Regression: Cannot set Driving region to Automatic

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#8783]
Not sure what exactly the background is to make this reproducible: Whenever I tap 'Automatic' on the Driving region dialog for any profile, the dialog just closes without accepting the selection. All other region options work and pop up the subsequent 'Apply to...' dialog.

**Comment by vshcherb** [comment]
We have a major issue cause we used to store a "Number" and not a "String identifier" in the settings file and cause number is quite dynamic and depends on order of items it was broken couple of times. This is going to be fixed this release and obviously this issue will be tested
