### ISSUE TITLE
App crashes while choosing POI type in RTL layout

### ISSUE THREAD

**Issue by ahangarha** [osmandapp/Osmand#8786]
I am running OsmAnd~ 3.6.3 from F-Droid on Android 8.1.0 in Persian language which make the phone layout **RTL**.

Since the last update, If I want to make a POI or edit one, if I click on type POI type, the app crashes.

This wont happen on LTR layout like in English. This indicates that the issue is something related to RTL layout or language (like translating something in wrong format as once had this experience on Tusky app)

I think this much detail should be enough to find the problem. Let me know if I can provide any further detail.

**Comment by iriman** [comment]
I also tried the same action with device language set to English and app language set to Persian, and it was OK. So I think it's likely not an issue with translation.

**Comment by nazar-kutz** [comment]
Fixed with https://github.com/osmandapp/Osmand/pull/8848/commits/f675b8d640e96114bc7efdd2de9e05af7c2d7c4a#diff-613ccbeb41b6361b479820d530cd5cbdR311
