### ISSUE TITLE
"filter created"-toast: string not replaced

### ISSUE THREAD

**Issue by ce-4** [osmandapp/Osmand#8795]
When I create a custom POI filter named eg. MyFoobar, a short toast is displayed at the bottom, which reads
"%1$s filter created". Expected output is "MyFoobar filter created". deleteFilter does show the correct "MyFoobar filter deleted" toast though.

Osmand is latest 3.6.3 version. Happens both in english and german language.
looks like it's here: OsmAnd/src/net/osmand/plus/search/QuickSearchPoiFilterFragment.java

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/commit/3e7ca15a26ef00968f18186ef4fa6411623bace7 Fixed
