### ISSUE TITLE
Cycle and pedestrian navigation profiles

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8803]
During the navigation with the cycle navigation profile, the route is built through the stairs. While using the pedestrian profile they are avoided. 
Start: 49.06194° N, 13.78007° E
Destination: 49.05870° N, 13.78192° E

**Comment by xmd5a2** [comment]
Not reproducible. Besides there is "Avoid stairs" option in pedestrian/bicycle routing profile's settings.
