### ISSUE TITLE
Cycle route renderer should not render proposed cycle routes

### ISSUE THREAD

**Issue by andrewshadura** [osmandapp/Osmand#8806]
In Bratislava, where I live, there’s quite a lot of ‘proposed’ cycle routes which have been buried somewhere in the official papers for ages without having been marked on the ground, but [our local cycle activists](https://cyklokoalicia.sk/) (@cyklokoalicia) have added them to OSM as `route=bicycle` + `state=proposed` e.g. [this relation](https://www.openstreetmap.org/relation/2793918). OpenCycleMap displays them in wide dashed overlay bands, so that they differ from the actual routes:
![OCM rendering of proposed cycle routes](https://user-images.githubusercontent.com/309253/79593510-dc462880-80db-11ea-9dca-4db633e917c3.png)
That said, given that there’s quite a lot of those in Bratislava, it’s easy to mistake them for the marked ones, but nevertheless it’s something.

OsmAnd, on the other hand, seems to completely ignore `state=proposed` and generously draws them in solid purple:
![OsmAnd’s rendering of proposed cycle routes](https://user-images.githubusercontent.com/309253/79593675-1c0d1000-80dc-11ea-86b9-a88307bbe174.png)

Have I planned the route in advance properly, I would have known that [Ľadová](https://www.openstreetmap.org/way/234443886) is a proper one-way road despite what @MichalPP thinks, and that it ends (or starts, if you may) in a proper 5-lane road with not a slightest hint of a civilised bicycle (or pedestrian, for that matter) crossing, and speeding cars racing with trolleybuses:
![The view of an imaginary cycle crossing](https://user-images.githubusercontent.com/309253/79594067-b0777280-80dc-11ea-8d66-d41575101e2d.png)

However, I did not, and discovered it when found myself going the wrong way on a one-way street leading to the said road.

It would be great if OsmAnd could offer some distinction to routes with non-empty `state`, especially those with `state=proposed`, and possibly have an option to hide them.

Thanks!

**Comment by aceman444** [comment]
In the past the 'state=proposed' tag wasn't documented (maybe it was invented privately by OpenCycleMap) so of course OsmAnd coudn't handle it. But now it seems documented on the wiki: https://wiki.openstreetmap.org/wiki/Relation:route#Tags .
So I support this proposal, thanks.

**Comment by andrewshadura** [comment]
Thanks for getting this fixed. When is the release this lands in is planned?

cc @nekromoff

**Comment by xmd5a2** [comment]
In next maps generation (may)
