### ISSUE TITLE
wrong direction arrow highlighted

### ISSUE THREAD

**Issue by 532910** [osmandapp/Osmand#8807]
https://www.openstreetmap.org/directions?engine=graphhopper_car&route=59.99541%2C30.38016%3B59.99654%2C30.38122

![image](https://user-images.githubusercontent.com/14617699/79601030-d3ac1d00-80f0-11ea-8749-ee326f5788ff.png)

**Comment by 532910** [comment]
I've checked, it's reproducable.

**Comment by 532910** [comment]
This is the same issue, isn't it?
https://www.openstreetmap.org/directions?engine=graphhopper_car&route=59.91471%2C30.35644%3B59.91592%2C30.34884

![image](https://user-images.githubusercontent.com/14617699/82267502-3ce3b200-9975-11ea-9c6b-83a2b3ac87fe.png)

**Comment by vshcherb** [comment]
1st one is map issue - https://www.openstreetmap.org/way/172306703 - fixed on map.

2nd is the same -
https://www.openstreetmap.org/way/313814091#map=19/59.91496/30.35483 - please fix on the map
it should have "turn:lanes : left|left|through|through"

Generally if there are 2 more options after split,  roads should have turn:lanes so it's clear how it's split

**Comment by 532910** [comment]
turn:lanes added:
https://www.openstreetmap.org/way/313814091

**Comment by vshcherb** [comment]
Should be fine as I see
