### ISSUE TITLE
slight_right arrows not highlighted

### ISSUE THREAD

**Issue by 532910** [osmandapp/Osmand#8808]
https://www.openstreetmap.org/directions?engine=graphhopper_car&route=59.97913%2C30.34456%3B59.97629%2C30.34461

![image](https://user-images.githubusercontent.com/14617699/79601468-83818a80-80f1-11ea-8c6c-1e5189fa9865.png)

I've checked, it's reproducable.

**Comment by vshcherb** [comment]
Duplicate
