### ISSUE TITLE
Map of Reunion_africa_2.obf.zip of size 0.0

### ISSUE THREAD

**Issue by berturion** [osmandapp/Osmand#8809]
OsmAnd is not able to download the map of La Reunion. Worst, an update will erase it.
The reason is that the file located at http://download.osmand.net/download?standard=yes&file=Reunion_africa_2.obf.zip is empty.
Its size is at zero (0.0).
OsmAnd is simply not working for now at La Reunion (France).

**Comment by vshcherb** [comment]
The file looks empty

**Comment by xmd5a2** [comment]
Fixed
