### ISSUE TITLE
*.OSF plugin does not generate map files well

### ISSUE THREAD

**Issue by nnngrach** [osmandapp/Osmand#8817]
I was sent a *.OSF plugin template for testing. I added JSON with several online maps to it. When I enabled this plugin, Osmand generated files for these maps in the Tiles folder.  When I enabled this plugin, Osmand generated files for these maps in the Tiles folder.

### When creating a Sqlitedb file:
the "**expire**" value from JSON is not copied to the "**expiresminutes**" field"

### When creating a Metainfo file:
the "**randoms**" value from JSON is not copied to the "**randoms**"
the "**referer**" value from JSON is not copied to the "**referer**"
the "**ellipsoid**" value from JSON is not copied to the "**ellipsoid**"
the "**inverted_y**" value from JSON is not copied to the "**inverted_y**"
the "**expire**" value from JSON is not copied to the "**expiration_time_minutes**"

Here are the sample files to make it easier to compare:
https://www.dropbox.com/s/lpmbmyh8omqq2vh/exaples%20of%20generating%20map%20files%20from%20json.zip?dl=0

---
OsmAnd Nightly 3.7.0#26430d 2020-04-17
Android 7.1

**Comment by vshcherb** [comment]
The issue is fixed though I'm not sure it is used any more by plugin itself

**Comment by Chumva** [comment]
Also "ellipsoid" and "inverted_y" are added to the file only if they are true.
