### ISSUE TITLE
Vector icons are not supported on Android 4.x Devices (remove hdpi from apk)

### ISSUE THREAD

**Issue by MAlfare** [osmandapp/Osmand#8829]
New builds (3.7.0#29477 and before) are crashing immediately on two devices, Android version 4.2 and 4.4, but are working on a smartphone with version 8.1.
Latest version I found to work on those two devices is:
OsmAnd-master-nb-2020-04-20.apk from  20-Apr-2020 14:56
Maybe the last working build was 3.7.0#29446, or 3.7.0#29443

**Comment by CJTmmr** [comment]
The same here; 
Latest Nightly is fine on Samsung A8/ Android 9.0

But crash before Splash-screen is over on Samsung Galaxy Camera 2 (EK-GC2000)/ Android 4.2
This is the 
[exception.log](https://github.com/osmandapp/Osmand/files/4517407/exception.log)

**Comment by vshcherb** [comment]
Please use previous builds, we are going include raster icons for Android 4.0

**Comment by vshcherb** [comment]
Should be fixed now

**Comment by vshcherb** [comment]
In future release we will address issue to remove hdpi icons, so apk will be smaller

**Comment by vshcherb** [comment]
+ Wrong scale of map icons (shields / poi icons)
