### ISSUE TITLE
Rendering issue (e.g. in measurement tool) caused by bug in calculatePath()

### ISSUE THREAD

**Issue by febeslmeisl** [osmandapp/Osmand#8835]
While developing a new feature in my local branch I think I have spotted an error in existing master branch code, that is also causing a (minor) rendering issue in current measurement tool functionality, so reporting here:

Steps to reproduce (checked on official OsmAnd~ 3.6.3):
- Put your device in  Landscape orientation.
- Set map to north is on top orientation
- Start measurement tool and add a start way point on your current location
- Add a new way point far in north
- Go back to start position and zoom in that the northern way point is **far** out of screen
- Rotate landscape that east is around top
- You see the dashed line of the measurement tool starting in "the middle of nowhere" going to center. Please also refer to [this Screenshot below](https://user-images.githubusercontent.com/34205180/80488186-3e195480-895e-11ea-8ccd-cd19f7cf63d6.png).

![Screenshot_20200424-153037](https://user-images.githubusercontent.com/34205180/80488186-3e195480-895e-11ea-8ccd-cd19f7cf63d6.png)

My root cause analysis so far:
- Method `calculatePath(RotatedTileBox tb, List<Float> xs, List<Float> ys, List<GeometryWayStyle> styles, List<Pair<Path, GeometryWayStyle>> paths)` of net.osmand.plus.views.OsmandMapLayer causing rendering issues if map in not in "north is on top" orientation. Because the view rect that is checked for paths going in or out is not rotated along with map. 
- Also `calculateIntersection` of net.osmand.util.MapAlgorithms in my opinion has a special case not handled correctly also contributing to this issue: The cases where `(outx == rightX || outx == leftX || outy == topY || outy == bottomY)` here currently the return value is comment out (maybe for good reason?).

What to do:
I'm very new to OsmAnd and not so familiar with its architecture, therefore I'm not sure about best/most performant way to fix it. But here is what is working for me (with minimal changes in existing code) as a orientation:

- For calculatePath in `net.osmand.plus.views.OsmandMapLayer`: rotating all tx,ty points before calculating view rect intersection by RotatedTileBox's angle and rotating back before drawing (with `mtx` and `inv_mtx` Matrix):
```java
		boolean segmentStarted = false;

		mtx.setSinCos((float)tb.getRotateSin(), (float)tb.getRotateCos(), tb.getCenterPixelX(), tb.getCenterPixelY());
		inv_mtx.setRotate(-tb.getRotate(), tb.getCenterPixelX(), tb.getCenterPixelY());
		pointCache = new float[xs.size()+ys.size()];
		for (int i = 0; i < xs.size(); i++) {
			pointCache[i * 2] =xs.get(i);
			pointCache[i * 2 + 1] =ys.get(i);
		}
		mtx.mapPoints(pointCache);
		float prevX = pointCache[0];
		float prevY = pointCache[1];
		int height = tb.getPixHeight();
		int width = tb.getPixWidth();

		int cnt = 0;
		boolean hasStyles = styles != null && styles.size() == xs.size();
		GeometryWayStyle style = hasStyles ? styles.get(0) : null;
		Path path = new Path();

		boolean prevIn = isIn(prevX, prevY, 0, 0, width, height);
		for (int i = 1; i < xs.size(); i++) {
			float currX = pointCache[2*i];
			float currY = pointCache[2*i+1];
			boolean currIn = isIn(currX, currY, 0, 0, width, height);
```
... rotating back:
```java
			if (draw||hasStyles) {
				outPutPoints[0]=prevX;
				outPutPoints[1]=prevY;
				outPutPoints[2]=currX;
				outPutPoints[3]=currY;
				inv_mtx.mapPoints(outPutPoints);
			}
			if (draw) {
				if (!segmentStarted) {
					cnt++;
					path.moveTo(outPutPoints[0], outPutPoints[1]);
					segmentStarted = true;
				}
				path.lineTo(outPutPoints[2], outPutPoints[3]);
			} else {
				segmentStarted = false;
			}
```
... and also here
```java
			if (segmentStarted) {
				path.moveTo(outPutPoints[2], outPutPoints[3]);
			}
```
(Better way would be of cause to check the view rect before/after map is rotated anyway in rendering process to avoid transforming points two times in this method, but not sure this)

- For calculateIntersection in `net.osmand.util.MapAlgorithms`: replacing mentioned case `(outx == rightX || outx == leftX || outy == topY || outy == bottomY)`  with two cases for X and Y coordinates:
```java
	if (outx == rightX || outx == leftX ) {
			if (outy >= topY && outy <= bottomY) {
				bx = outx;
				by = outy;
				return combine2Points(bx, by);
			}
		}

		if (outy == topY || outy == bottomY) {
			if (leftX <= outx && outx <= rightX) {
				bx = outx;
				by = outy;
				return combine2Points(bx, by);
			}
		}
```
With that in place measurement lines look good in all rotation tested so far.

Hope this helps to improve this already great tool.

**Comment by vshcherb** [comment]
MapAlgorithms has commented out cause outx / outy supposed to be outside of the box and border is considered to be inside, so it is a wrong parameter passed issue.

**Comment by vshcherb** [comment]
Though I think it is possible to fix it that way

**Comment by febeslmeisl** [comment]
Thanks for fixing, but commit 3e6733d seems only contain the second part, not the rotation part of net.osmand.plus.views.OsmandMapLayer. Was this file missed in the commit?

**Comment by vshcherb** [comment]
Can you please create pull -request cause it is hard to review (you could probably do it via github

**Comment by febeslmeisl** [comment]
Sure I could make a PR, but I think my account has no permission to create a new branch for the fix. Just tested it.
(Or maybe I didn't understand the process for PRs in OSMAnd project, I'm new to this, sorry)

**Comment by scaidermern** [comment]
> Sure I could make a PR, but I think my account has no permission to create a new branch for the fix. Just tested it.
> (Or maybe I didn't understand the process for PRs in OSMAnd project, I'm new to this, sorry)

You need to fork the project and modify this fork. Then you can create a pull request.

**Comment by febeslmeisl** [comment]
Great! This does also the job for my use case:) Just one last remark: during merge with my fork I spotted a little possibility for optimization: canvas in some cases is rotated twice: once in drawCenterIcon and later again in onDraw. This can be combined by rotating only once right in the beginning of onDraw I guess.  Could be done also in master branch of measurement tool if you like...

**Comment by vshcherb** [comment]
I'm not sure if it is important optimization, don't forget that main weak point is calculating place for each point [Multiplying Matrix to Vector] happens in the loop. 1 Rotation is just Matrix to Matrix. 
So we just shouldn't rotate in the loop, other rotations are less important
