### ISSUE TITLE
OsmAnd maps usage: statistics

### ISSUE THREAD

**Issue by blackboxlogic** [osmandapp/Osmand#8837]
I'm trying to get a sense of relative OSM popularity between regions, and I suspect this could be informative for other people also. Usage of OsmAnd could be informative.
I know (or hope) that you don't track your users, but I thought you might track how many times each map region is downloaded.
I'm specifically interested in how many times per month the USA-Maine map is downloaded compared to other states and how that is changing over time.

Please consider making a blog post at https://osmand.net/blog showing how many times per month each map region is downloaded, and how those are changing over time with some basic statistical analysis.

**Comment by vshcherb** [comment]
Yes we do have that information in the logs though we don't analyze it :) It is quite interesting cause I don't know that information myself.

**Comment by vshcherb** [comment]
https://docs.google.com/spreadsheets/d/1M4-cISwXkV5GMNozr-oUtWNeS-mf6Dd8A9hBQGeFux0/edit?usp=sharing - example

**Comment by blackboxlogic** [comment]
Thank you!
In Maine, 1 out of ever 2000 people downloads the state map each month (many assumptions were made). There was no strong trend over a year. Maine is the 10th most downloaded map per capita, which disproved my assumption that it was relatively poorly mapped, and therefore would not be heavily used compared to other areas in the US. The most popular US states per capita are DC, Wyoming and Vermont.
![image](https://user-images.githubusercontent.com/31355456/80753518-638f9500-8afb-11ea-879a-ac18cbb4c124.png)

**Comment by vshcherb** [comment]
It could be related to number of tourists more than to number of population. We assume that 60-70% of maps are downloaded by people who travel outside domestic region though it is hard to say what is domestic :)
