### ISSUE TITLE
"Could not find node or way" when clicking on a gate

### ISSUE THREAD

**Issue by opk12** [osmandapp/Osmand#8839]
In OsmAnd free, click Download for the Italian region Campania. Enable the OSM editing plugin.

Select the gate at https://www.openstreetmap.org/node/1791415188 ("Porta piccola" entrance to the Parco di Capodimonte). Click Actions, Modify POI. This error message pops up and nothing else happens: `I/O error. Could not find node or way.`

What version of OsmAnd are you using, on what device and Android/iOS version?
OsmAnd 3.6.3, Android 7

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.
`Italy_campania_europe.obf`, Apr 1, 2020. I also have "OsmAnd (online tiles)" in the Local maps list, but I don't remember setting it up and I assume it was set by default.

**Comment by dbogdanov** [comment]
Similar problem happens to me in the 3.7.4 version (2020-06-09). Has this pull request been included in the most recent release?
