### ISSUE TITLE
Stop Sign warnings when only traffic lights on road being traveled

### ISSUE THREAD

**Issue by ithink314** [osmandapp/Osmand#8840]
What version of OsmAnd are you using, on what device and Android/iOS version?
OsmAnd 3.6.3 from f-droid. Moto/Google Nexus 6. 

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?
Offline map.

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.
United States North Carolina March 31, 2020

__*In case of wrong routing:*__

Tell us whether you have used OsmAnd's in-app offline routing, or any online routing provider like YOURS, OpenRouteService or OSRM.
OsmAnd in-app

What routing profile is chosen in OsmAnd app? (car, bike, pedestrian, fastest or shortest)
Car (default/fastest, IIRC)

Please specify as exactly as possible the start and end point of your route by telling us city name and street name so that we can find it via in-app address search easily. Also, a permalink from openstreetmap.org can be helpful.

Traveling to southwest on Cabarrus Ave. West, from Concord downtown.

https://www.openstreetmap.org/#map=15/35.4036/-80.5966

Tell us your expected routing, and how OsmAnd routes, or add screenshots here.

Routing is fine, but app gives several Stop Sign warnings, when no stop signs are passed on Cabarrus Ave West (there are stop signs for side streets). Traffic lights are passed, but not stop signs. See screenshot.
![Screenshot_20200416-102320_OsmAnd~a](https://user-images.githubusercontent.com/843769/80298647-03f15c80-877e-11ea-930a-2e27a104c487.png)

**Comment by dead10ck** [comment]
I've noticed that it gives warnings about pedestrian cross as well when they are not actually on the road you are traveling on. It feels like it warns of every stop sign or pedestrian crossing in your proximity without checking if it's actually on the road you're traveling on.

**Comment by vshcherb** [comment]
I've found 6 stop signs https://overpass-turbo.eu/s/TwO

**Comment by dead10ck** [comment]
Oh yes, looking at the map data for that street, it does look like the stop signs are wrong. They are on the Cabarrus Ave way, instead of on the side street ways, and they don't have a direction tagged either.

**Comment by dead10ck** [comment]
And actually, looking at the area where something similar happened to me, it looks like it may just be someone gone crazy with the tagging of pedestrian crossings, even where there really aren't any. So I think this may just be an issue of incorrect map data.

**Comment by dead10ck** [comment]
@ithink314 I attempted to fix up the map data along that stretch of road in https://www.openstreetmap.org/changeset/84507964#map=15/35.4048/-80.5883. Let me know if that fixes the issue for you.

**Comment by ithink314** [comment]
Those changes will probably fix it, but it will be some time before it gets in offline maps and I go that way again. Thanks @dead10ck ! Another map issue, not osmAnd.

**Comment by vshcherb** [comment]
it's always a combination of map + OsmAnd issue because app & data couldn't exist without each other
