### ISSUE TITLE
Navigation ignores private road and starts with a straight line 

### ISSUE THREAD

**Issue by ithink314** [osmandapp/Osmand#8841]
What version of OsmAnd are you using, on what device and Android/iOS version?
 OsmAnd 3.6.3 from f-droid. Moto/Google Nexus 6.

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?
Offline

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.
 United States North Carolina March 31, 2020

__*In case of wrong routing:*__

Tell us whether you have used OsmAnd's in-app offline routing, or any online routing provider like YOURS, OpenRouteService or OSRM.
 OsmAnd in-app

What routing profile is chosen in OsmAnd app? (car, bike, pedestrian, fastest or shortest)
 Car (default/fastest, IIRC)

Please specify as exactly as possible the start and end point of your route by telling us city name and street name so that we can find it via in-app address search easily. Also, a permalink from openstreetmap.org can be helpful.

Traveling to north on Mount Pleasant Road South, to parking area at end of Pharr Family Preserve Access Road (gravel)

https://www.openstreetmap.org/#map=16/35.2904/-80.4888

Tell us your expected routing, and how OsmAnd routes, or add screenshots here.

Expected to turn right on access road, but OsmAnd said turn right where no turn was possible (see screenshot), then re-navigated to travel somewhere off map to north beyond the destination. After making the turn onto access road, OsmAnd navigated down that road OK as expected (see next screenshot). When departing, OsmAnd again wanted to navigate cross-country, off road (see last screenshot); expected to travel on roads.
![Screenshot_20200419-175120_OsmAnd~a](https://user-images.githubusercontent.com/843769/80298971-8b3fcf80-8780-11ea-8e1e-ce3cd94ecf75.png)
![Screenshot_20200419-175151_OsmAnd~a](https://user-images.githubusercontent.com/843769/80298983-98f55500-8780-11ea-99c7-c81062affff1.png)
![Screenshot_20200419-184753_OsmAnd~a](https://user-images.githubusercontent.com/843769/80299002-b0344280-8780-11ea-981e-18631dd13955.png)

**Comment by dead10ck** [comment]
Not a dev, but I had [a similar issue that I posted about in the osmAnd email list](https://groups.google.com/forum/m/#!topic/osmand/NAb2LvebHCE). The issue there turned out to be that the router refuses to go through private roads, even when there is no other option, and even when you tell it that private roads are okay in the navigation settings. It looks like in this case, there's [a road it must cross that is `access=private`](https://www.openstreetmap.org/way/16436483#map=15/35.2951/-80.4843), so it's exhibiting similar behavior.

This behavior with private access roads is a serious problem.

**Comment by scaidermern** [comment]
Looks like the first part of https://www.openstreetmap.org/way/16436483 shouldn't have `access=private` set, i.e. it must be split and the tag removed.

**Comment by dead10ck** [comment]
@scaidermern you probably shouldn't recommend removing a private tag just to get the router to work. If it's actually a private road, then it should be private.

And even if it's not, this is a larger problem in the router. There are cases where it simply refuses to route through private roads, even when the config option is set to allow it. See the email thread I linked to.

**Comment by scaidermern** [comment]
> @scaidermern you probably shouldn't recommend removing a private tag just to get the router to work. If it's actually a private road, then it should be private.

You are correct, this wasn't my intention though. Since @ithink314 didn't mention any private road I assumed that the route he is following doesn't require access to private territory.

**Comment by vshcherb** [comment]
Yes we have an issue introduce recently. You need to enable flag to allow private road calculation to get it working correctly. Sometimes we introduce that flag automatically but when there is no roads nearby at all, here the distance between point and road is small and it was considered to ok to start navigation.

**Comment by dead10ck** [comment]
@vshcherb this happens even when private roads are enabled in the navigation settings. See the mailing list discussion I linked to.

**Comment by vshcherb** [comment]
That's strange it must be something blocking than the road probably a special obstacle that we need to handle

**Comment by jfburke3** [comment]
I haven't seen this problem when my destination requires private road access in the final phase of routing. OsmAnd prompts me to allow private roads because my destination is on one, I answer yes, and it navigates me there properly. 

When my navigation *begins* at a location on private roads is another story, but that's an issue for a different Github entry.

**Comment by ithink314** [comment]
The first segment of road has been changed from private to public, because it is. Thank you for noticing that detail. There are seasonal hours restrictions, and a gate sometimes closed, but those details will be for later. I'm not sure if I had "allow private roads" set in osmAnd. Either way, 300-400 meters through woods, and across a creek, is not good for a street car. :-)  The map change probably fixes this for me (in another month or so).

**Comment by dead10ck** [comment]
@vshcherb there is still the issue of navigation on private roads. The original issue was but one example, which happened to be fixable with a change in the map data, but there is still the general problem of routing through private roads not working.

**Comment by vshcherb** [comment]
It should work with option enabled, so if it doesn't please open another bug with example to proceed with
