### ISSUE TITLE
Poi information=guidepost not editable

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#8853]
Poi information=guidepost not editable.
information 	guidepost
tourism 	information
When opening action I can "create poi" but expected would be "Edit poi", because poi already exist.

osmand version 3.7.0#29527 2020-04-27
Examples (map= Germany_baden-wuerttemberg_europe from April 2020)

48.19439° N, 7.94350° E
https://www.openstreetmap.org/node/6032724053

48.19925° N, 7.94402° E
https://www.openstreetmap.org/node/6032724054

48.19926° N, 7.94520° E
https://www.openstreetmap.org/node/3739579640

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-resources/pull/615/files
