### ISSUE TITLE
Colour of bicycle route displayed when only hiking routes are set to be shown

### ISSUE THREAD

**Issue by aceman444** [osmandapp/Osmand#8854]
When in the tourist/hiking profile is selected and hiking routes are enabled, to be colored by the OSMC symbol AND no bicycle routes are enabled to be displayed, then on paths that are part of a hiking and ALSO a bicycle route, there the color of the bicycle route is used, but the correct symbol of the hiking route is shown. Also the wrong ref of the cycle route is shown and not of the hiking route. You can check e.g. at https://www.openstreetmap.org/way/59135623 .

This is in latest OsmAnd 3.6.3 and is the same whether the Topo or OsmAnd rendering styles are set.

The problem is NOT the same as issue #1721, where just OsmAnd picks the wrong color. In my report, the bicycle route should be completely ignored, thus its ref and colour should not be considered in any rendering decisions/prioritisation. On the sample way, there is only a single hiking path, whose colour 'red' should be picked up.

Thanks.

**Comment by vshcherb** [comment]
Merged into https://github.com/osmandapp/Osmand/issues/8540
