### ISSUE TITLE
Night build 3.7.0#29568m released 2020-04-30 is very crashy

### ISSUE THREAD

**Issue by jfburke3** [osmandapp/Osmand#8872]
This build has a problem in which it can get into a crash loop. I *think* that the problem starts when it has to recalculate the route during navigation. 

The crash appears to  occur just as it announces the recalculation results.   It then restarts automatically, asks the usual question about continuing the previous navigation, then crashes again when announcing the results. Crash loop appears to continue indefinitely until something helps break it out. 

Things that i think help break the loop: 
* If you stop long enough for it to complete a full route calculation while not in motion (maybe, not sure yet) 
* After it restarts, if you can get into the Help menu quickly enough (for example, to get the build number so you can report the problem on Github) 

Using OsmAnd offline routing, OsmAnd offline maps US Georgia and Florida dated March 31, 2020.  Live enabled, but I don't think any of the roads used have changed recently. 

Samsung Galaxy S7 Edge, Android 7

My original route included several waypoints to force a specific route, which I deviated from a couple of times. But, the problem continued after I got back on the freeway for the last part of my trip, which only had my destination.

**Comment by vshcherb** [comment]
Can you please attach a crash log?

**Comment by jfburke3** [comment]
[exception.log](https://github.com/osmandapp/Osmand/files/4565295/exception.log)

Let me know if this looks good or if you need another one.

**Comment by jfburke3** [comment]
Backgrounding OsmAnd also appears to break the loop.  I have *no* idea why that works. 

The crash problem doesn't appear to simply involve a recalculation. It appears to also include passing an intermediate destination, but I'm still working out details.

**Comment by jfburke3** [comment]
Another log

[exception.log](https://github.com/osmandapp/Osmand/files/4567144/exception.log)

**Comment by jfburke3** [comment]
A note that I'm still not completely sure what circumstances start the crash loop cycle. All I can say for sure is that since installing that night build, all of my routing has included intermediate destinations, and the crash has eventually happened during all of them, and that going into the Help menu (probably any menu will work) or backgrounding the app will break the cycle.  (It has to be able to do a complete recalculation in that state to break the cycle. E.g., if you background it a second after recalculation starts, it will still crash, but just leave it in the background and it will get out of the loop after the next recalculation.)

**Comment by vshcherb** [comment]
Wrong decoding for vector icons - https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/views/mapwidgets/MapInfoWidgetsFactory.java#L1203

**Comment by max-klaus** [comment]
Fixed by https://github.com/osmandapp/Osmand/commit/7fee1d08caf89e969f6f341e2415a09f48c64713
