### ISSUE TITLE
Indicate noexit=yes on map

### ISSUE THREAD

**Issue by mahdi1234** [osmandapp/Osmand#8877]
There's some 726K noexit=yes tags in the world - https://taginfo.openstreetmap.org/tags/noexit=yes which is used to indicate track/path doesn't continue. This would be really helpful to see when mapping, so one could ignore such track/path (not checking whether it continues).

I can imagine this being visible only when "OSM mapper assistant" is enabled.

**Comment by jfburke3** [comment]
I'm not sure I see how this would be very useful myself. Can you describe a particular use case?

**Comment by mahdi1234** [comment]
Well I guess it really depends on everyone's mapping style, my use-case is very simple

- somewhere on the hike/in the forest with plenty of time to go somewhere random
- look at the map if there's some path/track which ends somewhere near/on the way and has potential to continue
- verify whether it has fixme=continue --> go ahead and map it
- verify whether it has noexit=yes--> ignore as it's validated not to continue
- if it has neither of those --> go check and either extend/map or tag it with noexit

Hope it's clear it definitely helps when it's properly tagged.

**Comment by vshcherb** [comment]
I think we have red pillars for noexit for close zoom information @xmd5a2

**Comment by xmd5a2** [comment]
We already render noexit=yes for several years

**Comment by mahdi1234** [comment]
@xmd5a2 can you please tell me which zoom/style? I'm at 2m level and trying OSMand/Mapnik/Offroad and none of them shows that for path/track with 3.6.3

**Comment by xmd5a2** [comment]
@mahdi1234 default style and derivatives. Zoom 18+
![Screenshot from 2020-05-04 20-35-28](https://user-images.githubusercontent.com/5829014/80995434-edff2e00-8e46-11ea-8b52-4477e68672e6.png)

**Comment by mahdi1234** [comment]
@xmd5a2 Thanks it's under "More details" which is not available in all styles though. I'll ask on telegram more on those missing things.
