### ISSUE TITLE
Changing new map name

### ISSUE THREAD

**Issue by theultimatekehop** [osmandapp/Osmand#8889]
What version of OsmAnd are you using, on what device and Android/iOS version?
Osmand 3.6.3 2020-02-28
Android 8.1.0 and Android 9.0

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?
Yes OSMAND vectorial is downloaded but the issue is when adding a new online map

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.
Nothing with offline maps

Issue  : 
When I'm addind online map (in french setting but also tried in english and have same issue) I try to add a map. Previously I was able to rename the custom map. Now the field saying 'newMapnik' is not available to edit. When I click on it, it just doesnt let me edit the name of the map Im trying to create
![image](https://user-images.githubusercontent.com/32905468/80984172-8374d080-8dfb-11ea-81ac-e9c5e6dbcf26.png)

![image](https://user-images.githubusercontent.com/32905468/80984320-b1f2ab80-8dfb-11ea-8407-6d4f5b95339a.png)

**Comment by vshcherb** [comment]
Merged into #7658 .
