### ISSUE TITLE
[Feature request] track user's speed beyond the navigation mode

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8896]
Sometimes, users do not have a proper destination point, but they would like to use the features of the navigation mode, like speed tracking and displaying the allowed speed on the road.

**Comment by njohnston** [comment]
This is already supported. Open the main menu and select "Configure screen", and then enable the "Speed" and "Speed limit" widgets. The speed widget appears when you start moving.

**Comment by JonnyTech** [comment]
@vshcherb, the 'speed limit' widget is only available in the 'driving' profile. Can it be enabled in the 'browse map' profile?

**Comment by vshcherb** [comment]
Nope, I think we intentionally keep Browse Map simpler

**Comment by JonnyTech** [comment]
Is there another way to get speed limit warnings when driving without a calculated route?

**Comment by vshcherb** [comment]
You can simply change current profile, it is not bound to navigation or route.
