### ISSUE TITLE
[Feature request] display passed route without saving the recording

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8897]
After reaching the destination point, the recording plugin asks to save or to stop the recording. It would be more convenient to stop recording as soon as the navigation mode is off. 
Enabling the Auto-record track during navigation would save the recordings, which can clog the storage folder. 
An additional setting that could allow stopping a recording automatically may be a solution.

**Comment by vshcherb** [comment]
Duplicate with https://github.com/osmandapp/Osmand/issues/8911
