### ISSUE TITLE
[Feature request] Intent to open polyline

### ISSUE THREAD

**Issue by systemed** [osmandapp/Osmand#8901]
Lots of [cycle.travel](https://cycle.travel/map) users like to view their planned routes in OsmAnd, but [sometimes find it complex](https://forum.cyclinguk.org/viewtopic.php?f=1&t=137308&sid=e61e1d864bf305304eeca3b0dffe2812). I'd like to make this easier.

Could you consider adding an intent to open a polyline route in OsmAnd, so that websites like cycle.travel could offer an "Open in OsmAnd" button?

This could potentially be implemented by:

- an intent which takes a Google-encoded polyline and parses that similarly to a GPX track;
- or an intent which takes a URL of a GPX track; on receiving the intent, OsmAnd fetches the file from the given URL, and then opens it.

**Comment by vshcherb** [comment]
Yes I would say it could be easy but it requires to handle custom domains, so the only option i would see
https://osmand.net/open-gpx?url=<encoded url to gpx.gz file....>. If you could share one of such url I think it we could implement it relatively easy.

**Comment by systemed** [comment]
Excellent! Here's an example: https://cycle.travel/gpx/148463.gpx

**Comment by vshcherb** [comment]
https://osmand.net/open-gpx?url=https%3A%2F%2Fcycle.travel%2Fgpx%2F148463.gpx

**Comment by systemed** [comment]
That would be superb. Once that's live (3.7?) I'll integrate this with cycle.travel.

**Comment by vshcherb** [comment]
We can probably support "name" parameter in url itself or detect name by taking characters from last '/' to '.' or to the end

**Comment by systemed** [comment]
Sounds good. Reading the name element in the GPX would probably be best, I'd guess?

**Comment by vshcherb** [comment]
We need to add simple page to open-gpx

**Comment by systemed** [comment]
Superb - thank you! Looking forward to the next release.

**Comment by systemed** [comment]
Hi folks - thanks again for this feature! Is this live? I can't yet get it to work (latest OsmAnd on iOS) but might be missing something.

**Comment by Chumva** [comment]
@systemed did you try in on android version of OsmAnd?
