### ISSUE TITLE
Live Update makes highways duplicate

### ISSUE THREAD

**Issue by sndrz** [osmandapp/Osmand#8906]
Version 3.7.0 released 2020-05-06 with live update maps of Russia Moscow and Russia Moscow oblast 2020-05-07 produce a visualization glitch with duplicated and shifted highways.

For example see
55.90989° N, 37.82722° E
55.91394° N, 37.81240° E

Routing is fine by of the lines.
![Screenshot_20200507-122347_OsmAnd](https://user-images.githubusercontent.com/4329032/81277946-bc13e480-905d-11ea-89d7-27cb1bc621bc.jpg)
![Screenshot_20200507-122328_OsmAnd](https://user-images.githubusercontent.com/4329032/81277974-c33af280-905d-11ea-9e0f-27a1975b0cd5.jpg)

**Comment by vshcherb** [comment]
Fixed https://github.com/osmandapp/OsmAnd-core/commits/legacy_core
