### ISSUE TITLE
Remember last choice for showing GPX on a map

### ISSUE THREAD

**Issue by Ungoose** [osmandapp/Osmand#8913]
Currently, “Show on Map” is always enabled by default for each recorded track and it does not remember the last choice, so I need to turn it off every time (or sift through the menus later if I accidentally close the menu without touching the switch). Is it possible to set a preferred behavior (e.g., by remembering the last choice)? It would save a lot of taps for some users.

**Comment by vshcherb** [comment]
Not reproducible
