### ISSUE TITLE
NPE on Android 4.3 when Manual Changing Storage Folder/ Latest Nightly

### ISSUE THREAD

**Issue by CJTmmr** [osmandapp/Osmand#8924]
On Samsung Galaxy Camera 2 (EK-GC200)/ Android 4.3
After fresh install of latest nightly, 3.7.0 build 26630d.
I try to change Data Storage folder.
On 4.3 it had to be done Manually;
Initial is is set to: /data/data/net.osmand.dev/files/osmand/osmand

When you try to change to: /storage/extSdCard/osmand -> immediate crash when you tap Apply.
This is the [exception.log](https://github.com/osmandapp/Osmand/files/4600504/exception.log)

Same behavoir on Samsung Galaxy A8/Android 9.0

The default builds from download.osmand.net/night-builds where okay until 2020-04-06 (build 26335d)
Build 26388d from 2020-04-10 is first with NPE.
Something with commits for: "Show SnackBar when preference change"??

**Comment by Chumva** [comment]
Fixed with https://github.com/osmandapp/Osmand/commit/74a732edf95322f1b0f80ac71b22510c53a928bc.
