### ISSUE TITLE
Take the tag "direction=forward/backward" of STOP signs, traffic lights, etc. into account when building routes

### ISSUE THREAD

**Issue by yyatsyn** [osmandapp/Osmand#8928]
STOP signs are frequently asymmetric (are binding not for ALL, but only for certain directions of traffic).
As a result, if the routing algorithm ignores the "direction=forward/backward" of STOP signs, traffic lights and other constraints then it can build sub-optimal routes by penalizing for constraints that are not applicable to a considered direction of traffic.
More details are provided in a post [here](https://t.me/ruosmand/43519).

**Comment by pfg21rus** [comment]
the direction is necessary not only for the stop sign.
for example "give way".

**Comment by scaidermern** [comment]
Duplicate of  #6774.
