### ISSUE TITLE
Roads are drawn twice without perfect overlap

### ISSUE THREAD

**Issue by H--W** [osmandapp/Osmand#8932]
For the past couple versions of OSMAND+ (including current version 3.6.3, released 2020-02-28) many roads appear to be drawn twice. Once, using all nodes of the road and again using only some nodes. The result is that at some locations the duplicate drawing is very apparent where they do not overlap. See attached "Duplicate-Road-Osmand+.jpg". I've also attached a Vespucci screenshot which shows the location of the nodes along the way. This appears to highlight how one of the duplicates is drawn only using some of the nodes. I've also attached the logcat which appears to show various errors, trivial or perhaps otherwise. Best Rgds, -H-

Technical information:
Map "Canada Nova Scotia, April 30, 2020"
43.82823N 66.08893W
Duplicated Road Way: 98560071
URL: https://www.openstreetmap.org/way/98560071
Last Edited 7 Years Ago
Tagged:
highway=service
lanes=2
surface=paved
source=NRCan-CanVec-7.0

Device : j3popeltecan
Brand : samsung
Model : SM-J327W
Product : j3popeltevl
Build : M1AJQ.J327WVLS4BSK1
Version : 8.1.0
App Version : OsmAnd+
Apk Version : 3.6.3 363

![Duplicate-Road-OsmAnd+](https://user-images.githubusercontent.com/5553887/81637494-e6162f80-93ec-11ea-8a09-b08909b7d213.jpg)

![Duplicate-Road-Vespucci](https://user-images.githubusercontent.com/5553887/81637574-12ca4700-93ed-11ea-828d-b9759ff0e516.jpg)

[duplicate-roads-logcat.log](https://github.com/osmandapp/Osmand/files/4613337/duplicate-roads-logcat.log)

**Comment by scaidermern** [comment]
Do you have conflicting maps installed? A roads only map and a country/region map, for example?

**Comment by vshcherb** [comment]
THis is OsmAnd Live issue and it is going to be fixed with new beta.
Nightlies should be fixed already
