### ISSUE TITLE
Navigation refuses to route through private roads with private access enabled

### ISSUE THREAD

**Issue by dead10ck** [osmandapp/Osmand#8933]
This is osmAnd 3.6.3 on Oxygen OS 10.0.9.HD65AA. The problems described are in the San Francisco map, with OSM Live enabled.

It seems osmAnd is having trouble routing any route inside of a big mobile home park where there is a big network of private roads. There are two entrances to the park, the main one being at 849WC232+95, and a smaller one at 849VCX3V+8V. The rest of the park is surrounded by a wall, so there is no other way to get inside the park but these two entrances. And if you pick a house that is close to the edge of the park, instead of routing through one of the entrances, it will simply give up on the street outside the wall.

As an example, if you route from 849V9XWG+RQ to 849WC252+25, you can see it stop routing on Persian Drive and say to drive straight through the wall. **Note that this is with private roads enabled.**

![Screenshot_20200511-175132](https://user-images.githubusercontent.com/846275/81639292-58c4e200-93d0-11ea-8944-27349d3f42e1.jpg)

If you don't go too deep inside the park, the router does something reasonable, like if you pick 849WC242+68 as the destination. So from this I conclude that the router isn't completely avoiding all private roads.

I posted about this in the [osmAnd user mailing list](https://groups.google.com/forum/m/#!topic/osmand/NAb2LvebHCE), which has a discussion with more weird examples and screenshots.

I thought maybe something was wrong with the map data, like a disconnected way or something like that, but I cannot find anything wrong that I could understand causing this.

I wasn't sure if maybe the router has trouble knowing how to handle the barrier entrance, but even if you drive inside during navigation, it will refuse to reroute to something reasonable even after you're already inside the park. I took the following video while I was navigating here in my car. The route I am driving is the route it should calculate, but even as I am driving through the park, it simply refuses to route anywhere through the park.

https://vimeo.com/417472429

As a complete ignorant guess, my understanding is that the router gives certain weights to some roads over others. I'm not sure if maybe the router isn't outright disallowing a route through private roads, but perhaps the complex network of private roads is making any route whatsoever have so much weight that it will not do it, even though there is no other option to actually get to the destination.

**Comment by jfburke3** [comment]
@dead10ck You're right that it gives different weights to different roads, but even so, as far as I know, it is supposed to pick the closest road to your destination for the final stage of navigation.

I did some poking around in the app, and I found a few situations where I can reproduce what you describe with private access enabled in the current beta release.

**Comment by vshcherb** [comment]
Tested with this location should be fine now
