### ISSUE TITLE
Add the ability to search for a car wash without self-service

### ISSUE THREAD

**Issue by Prusaker** [osmandapp/Osmand#8935]
At now if I need to find a car wash where there is no self-service, the current search settings do not allow me to do this (aearch results will include both: self-service and non-self-service sinks or only car washes with self service).

Its possible to add the ability to search for a car wash without self-service? In this filter, the search should show results with the tag self_service=no or if this tag is not specified at all.

Thanks in advance.

**Comment by xmd5a2** [comment]
"If this tag is not specified at all" in most cases mean that data is incomplete. Added car_wash=no to filter
