### ISSUE TITLE
Confusing names of action buttons for GPX logging

### ISSUE THREAD

**Issue by eumiro** [osmandapp/Osmand#8942]
When the GPX logging is active, a “PAUSE” button appears in the Android's notification bar, then replaced by a “CONTINUE” button, which is what I'd expect. During my trip I want to PAUSE and CONTINUE/RESUME the GPX logging.

However when I click on the “GPX” widget, there are four items:

- “Stop GPX logging” (replaced then by “Start GPX logging”)
- “Start new segment”
- “Save current track”
- “Clear recorded data”

The first item “Stop/Start GPX logging” does exactly what PAUSE/CONTINUE does, but is named differently. And “Start” sounds more like “forget about what you did until now and start a new track” than “continue after the pause”. They also appear only after the tracking has started for the first time, so there is no real new “start”.

I'd like to change these two strings `gpx_monitoring_stop` and `gpx_monitoring_start` to “Pause” and “Resume” (or “Continue”), but I cannot find the “Pause” and “Continue” strings from the notification bar in the source code.

If you like the idea, I can do a PR and fix also a few translations of these two strings.

**Comment by Ungoose** [comment]
This is a great idea. I have suggested a very similar scheme here: #8415 
A much needed step in the direction of a better UI for OsmAnd

**Comment by sonora** [comment]
Yeah, I've struggled with this for a while, too, but never took the time to investigate.

Each of the `gpx_monitoring_start/stop..`. string is used in 4 different places in the app, I need to see what makes sense, in particular if pause/resume really makes sense and if there are no use cases where users would be looking for a start or stop also.

**Comment by eumiro** [comment]
I believe these two strings appear only after a tracking has started. This would be the first step to prevent confusion. The second step would be something like @Ungoose proposed in #8415, which would improve the usability even further.

Just out of interest, I have grepped case-insensitively the whole repository for the single word `pause` and `continue` (the latter appears often in Java/Kotlin code), but can't find those strings from the notification bar. Where are they?

**Comment by sonora** [comment]
I guess we can go with Pause/Resume, let's test it.
