### ISSUE TITLE
Logging Notification not updated after 'Clear recorded data'

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#8957]
I just notice that if you select 'Clear recorded data' for a GPX recording, the content of the Android recording notification is not updated, i.e. will still reflect the data as if not cleared.

(The notification will only be correctly updated with the recording of the next point, or if the recording had previously been stopped, when putting the app on the background and back in the foreground.)

**Comment by vshcherb** [comment]
Due to limited time will be fixed with redesigning save dialog in 3.8

**Comment by sonora** [comment]
I had already fixed it this morning: https://github.com/osmandapp/Osmand/commit/582fa5d32ebc18ef78d7bb3b6d9ef1cf9f24d718. Must have somehow only tested the wrong build after that - Works now.
