### ISSUE TITLE
POI layer reappears after restarting the app

### ISSUE THREAD

**Issue by Athoss9** [osmandapp/Osmand#8958]
Android version: 9
OsmAnd version: OsmAnd Nightly 3.7.0#26696d

How to reproduce:

- Show POI layer by search or selecting one from the menu
- Restart the app
- Hide POI layer by the toggle in the menu or by a quick action
- Restart the app
- The POI layer reappears sometimes immediately, sometimes after zoom in/zoom out

If I hide the specific POI type with the respective checkbox, it doesn't reappear after restart.

**Comment by scaidermern** [comment]
I can confirm this bug, I'm experiencing the same.
