### ISSUE TITLE
Problem with the rate dialogue

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/Osmand#8966]
There are feedback from users that the rate dialogue shows very often. 

We have the next algorithm for showing it in OsmAnd:
The rate dialogue must appear maximum two times.
The first time: 
>15 days from the first start
or
>100 starting
If the button "no (cancel)" was chosen the rate dialogue appear the second time:
from next 50 starting,
but no more 60 days from appearance first the rate dialogue.

**Note:** If the app was installed more than 350 days ago the dialogue doesn't show.

**Comment by sonora** [comment]
Yes, that's been a real issue lately ...
