### ISSUE TITLE
mixing the display of monthly and hourly map updates

### ISSUE THREAD

**Issue by PPilotPirx** [osmandapp/Osmand#8973]
OSMand V.3.7.0
Device Huawei BTV-DL09
Android 7.0
and
Sony Xperia XZ1 Compact G8441
Android 9

After the monthly update in May and the hourly updates that followed, the result is a mix of both images. The intersection was transformed into a roundabout on 9 May. Deleting and reloading the monthly update did not result in any changes. This problem occurred on two devices with the same OSMand version. The routing is based on the hourly updates.

![image](https://user-images.githubusercontent.com/48177086/82035606-06214980-96a0-11ea-9806-c194ae8b1bd6.png)

**Comment by scaidermern** [comment]
The same bug as #8932?
