### ISSUE TITLE
osmand v3.7.0 crashes if brouter route is exported or shared

### ISSUE THREAD

**Issue by cyberman54** [osmandapp/Osmand#8984]
Brouter routes cannot be exported as .gpx, neither be shared with other app (e.g. GPXimport for Garmin). The app crashes if the button download or share is pressed, when navigation type Brouter is selected. This feature does work seamless in previous version 3.6.3 on the same device.

Device: crosshatch
Brand: google
Model: Pixel 3 XL
Product: crosshatch
Build: QQ2A.200501.001.B2
Version: 10
App Version: OsmAnd+
Apk Version: 3.7.0 370

Brouter version: 1.6.1

**Comment by vshcherb** [comment]
Do you have exception.log to share?

**Comment by cyberman54** [comment]
@vshcherb i found the above information in the exception.log, nothing more. Is there / should there be some more? Where can i find it on the phone?
