### ISSUE TITLE
Please remove 'OpenWandelKaart' as overlay underlay option, as it's very outdated and no longer maintained

### ISSUE THREAD

**Issue by hgcvm** [osmandapp/Osmand#9001]
Please remove 'OpenWandelKaart' as overlay underlay option, as it's very outdated and no longer maintained. It at least didn't receive an update since 2018, probably earlier. I don't know the full story, but apparantly the hosting server is still up, but the developper is MIA. See forum thread (in dutch) https://forum.openstreetmap.org/viewtopic.php?id=61438

The same goes for OpenFietsKaart http://openfietskaart.nl/

**Comment by hgcvm** [comment]
That was quick. Thanks a lot!

**Comment by selfishReplicator** [comment]
PLEASE PLACE the the OpenWandelKaart BACK
It might be outdated, but I use it a lot!
Please only remove something if there is an alternative. Is there?

I bought a new phone today and I used this map literally every week on my previous phone that has defects now and really like to install it again!

**Comment by hgcvm** [comment]
As an alternative, you could use 'Waymarkedtrails Hiking' or Cycling/MTB/Riding.  It's a lot more detailed and very up to date.

**Comment by selfishReplicator** [comment]
Aaah, thanks for this quick and valuable feedback!
