### ISSUE TITLE
Switching profiles using the quick action makes the map jump

### ISSUE THREAD

**Issue by Athoss9** [osmandapp/Osmand#9010]
Android version: 9
OsmAnd version: OsmAnd Nightly 3.7.0#26771d

If I use the new quick action 'change application profile' the map jumps about half screen to north each time I press the button.
If I don't move the map at all from the application start, the bug doesn't occur.

**Comment by vshcherb** [comment]
The map center is different in different profiles. So you can configure it to avoid jump

**Comment by vshcherb** [comment]
This issue is related to all switches between profiles not only quick action.

**Comment by Athoss9** [comment]
If I switch profiles using the map view settings or the top item in the drawer menu, the map jumps back and forth due to the different map centre but if I use the quick action it always jumps north.

I made a quick video: https://mega.nz/#!9FsHGJ6B!mo6K-tq0H7GNDvCmSbMkiTm2c-EHQNdIDrNQBLK0JyA

**Comment by vshcherb** [comment]
I think we need to fix it for all cases:
1. We should realign map center so center of the map is the same if my location is not centralized
2. If my location is centred, then map should jump according to map center connected to my location.

**Comment by Athoss9** [comment]
The exact same issue occurt again after the latest update.
If I use the quick action, the map keeps jumping to north but if I switch profiles using any other methods, it works fine.
