### ISSUE TITLE
'Bike routes' also shows hiking symbols on shared sections

### ISSUE THREAD

**Issue by Athoss9** [osmandapp/Osmand#9011]
Android version: 9
OsmAnd version: OsmAnd Nightly 3.7.0#26771d

If I activate the cycle routes in the map view settings, roads sharing both cycle and hiking routes show the hiking symbols as well.

I attached an example:
https://www.openstreetmap.org/way/46972871
![Screenshot_20200519-174942](https://user-images.githubusercontent.com/28255870/82349056-ee2c2b80-99f9-11ea-867d-b5af8f489a8f.png)

**Comment by vshcherb** [comment]
Actually we fixed it already in 3.7 but we need to generate new maps though it will be backward incompatible with 3.6. So June maps should be ok and 3.7 should be 100% rolled out.

**Comment by aceman444** [comment]
@vscherb, I noticed June maps with OsmAnd 3.6 are almost all blue with no symbol displayed (regardless of osmc:symbol and colour in the relation). Do you say the maps need to be viewed with 3.7 to display properly?

**Comment by vshcherb** [comment]
new June maps won't be compatible with 3.6 only with 3.7.

**Comment by Aiurek** [comment]
@vshcherb for me it still looks like this, despite Osmand+ 3.7.3, released 2020-06-04 and Jun 1, 2020 maps. Guess this is not deliberate?

![Bild1](https://user-images.githubusercontent.com/27865200/84033052-92214b00-a998-11ea-9f5b-cdee8a9b6849.jpg)

**Comment by vshcherb** [comment]
@Aiurek you are referring to red squares or something else?

**Comment by Aiurek** [comment]
@vshcherb also to the blue, yellow scallop symbol on the pink track at the top of my screenshot. Thought this might be related to the Camino de Santiago hiking path, but haven't checked: https://en.wikipedia.org/wiki/Camino_de_Santiago

**Comment by xmd5a2** [comment]
> @vshcherb for me it still looks like this, despite Osmand+ 3.7.3, released 2020-06-04 and Jun 1, 2020 maps. Guess this is not deliberate?
> 
> ![Bild1](https://user-images.githubusercontent.com/27865200/84033052-92214b00-a998-11ea-9f5b-cdee8a9b6849.jpg)

Cycle routes and mtb routes share osmc:symbol values at that moment. Also mtb route osmc:symbols are not supported. There are 2 groups of routes that use different symbols in current release: 1) route=hiking,walking,foot 2) other routes (cycle, horse)

**Comment by xmd5a2** [comment]
I've found a bug with these red squares. When route=foot then no prefix is added to osmc internal tags (osmc_waycolor, osmc_background etc.)

**Comment by vshcherb** [comment]
The bug is fixed of red squares, please let us know and we will regenerate these specific maps to test.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-tools/pull/355

**Comment by aceman444** [comment]
I also noticed that in 3.7.3 there is a difference between the "Topo" style (where the new routes render OK), and the base "OsmAnd" style, where they look incorrect (almost all hiking routes blue, actually similar to what 3.6 would render).

**Comment by Aiurek** [comment]
It's not only the red squares unfortunately. More like all the different hiking symbols are illustrated with cycle routes switched, despite hiking symbols being switched off
