### ISSUE TITLE
OsmAnd Live shows both old and new data

### ISSUE THREAD

**Issue by Athoss9** [osmandapp/Osmand#9033]
Android version: 9
OsmAnd version: OsmAnd+ 3.7.0 Beta (2020-05-06)
Map: Hungary (2020-05-01)
OsmAnd Live: Hungary (2020-05-20 17:45)

I recently redraw all buildings in an area after the release of a higher resolution imagery but now OsmAnd shows both the old and the current versions of the houses.

![Screenshot_20200520-180703](https://user-images.githubusercontent.com/28255870/82469790-cb1a7e00-9ac4-11ea-832c-ea6d62ada913.png)

**Comment by vshcherb** [comment]
Issue of old beta, should be fixed in new beta (released 19-05-20).
