### ISSUE TITLE
Ford inside tunnel

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#9036]
Not all map details from the OSM are available in OsmAnd maps.
56.05115° N, 92.51955° E
The ford inside tunnel is not displayed in OsmAnd
![image](https://user-images.githubusercontent.com/50198677/82533604-4c692380-9b4c-11ea-9de4-0926b3c53fa3.png)
![image](https://user-images.githubusercontent.com/50198677/82533680-73275a00-9b4c-11ea-898a-301df6b10e84.png)

**Comment by xmd5a2** [comment]
It is rendered, but without an icon
![Screenshot from 2020-06-22 10-33-41](https://user-images.githubusercontent.com/5829014/85260777-e259dc00-b473-11ea-8e9d-6431ca5d2624.png)

**Comment by vshcherb** [comment]
We don't support icons on the line please add ford on the middle node of the way
