### ISSUE TITLE
[Feature request] make fever voice guidance notifications

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#9050]
Even while navigation along a single street, if it is curved, OsmAnd suggests to take a turn. 
It would be more useful to receive voice notifications in cases when it is not obvious which way to choose.

**Comment by vshcherb** [comment]
This issue is related to GPX navigation, it is suggested to create GPX inside 3.7 (Measure distance) where it keeps all turns correct. 
Also we have another request open to create a correct GPX attached to OSM roads, so turns will be calculated correctly.

**Comment by scaidermern** [comment]
> Also we have another request open to create a correct GPX attached to OSM roads, so turns will be calculated correctly.

Which is #3908, just for reference.
