### ISSUE TITLE
MapCreator looses subtype "description"

### ISSUE THREAD

**Issue by MAlfare** [osmandapp/Osmand#9051]
Since very long time, every 10 days I download 8 gpx-files containingcharging stations.
Convert them to osm, do some editing an filtering.
Download the latest OsmAndMapCreator, convert the osm-files to obf and
merge 7 of them to one.
Yesterday I found a large difference in size of the obf-files.
Version from 9.5.2020 O.K
Version from 21.5.2020 NOT O.K

Details are listed in the  attached text file
[OMC_Problem.txt](https://github.com/osmandapp/Osmand/files/4667972/OMC_Problem.txt)

**Comment by vshcherb** [comment]
Fixed with https://github.com/osmandapp/Osmand/commit/88a6d620803e19538e39cf24023c3c941a8dc307
