### ISSUE TITLE
PlayStore release still shows version 3.6.3 for May 22 update

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#9057]

**Comment by BikeRoad** [comment]
I think that the publication of updates on Google Play is not always immediate.
But you can download the latest version of Osmand at:
https://download.osmand.net/releases/
Regards.

**Comment by sonora** [comment]
I know, thanks!

**Comment by vshcherb** [comment]
10% still, probably tomorrow 100% if no critical crash - 3.7.2
