### ISSUE TITLE
Enhancement: Show current progress in the elevation-view while riding a track

### ISSUE THREAD

**Issue by mschwehl** [osmandapp/OsmAnd#9058]
When having a ride in the mountains it is always good to know what is ahead of you for saving your energy to the right places. Osmand have this nice feature of calculating the elevation-profile from one gpx-track. At current state this view is static, it hides e.g. the zoom-buttons. You cannot go to back to other functions.

This would be very cool: Place a widget with this view below the map like this mock-up screenshot

![Screenshot_2020-05-22-11-10-23](https://user-images.githubusercontent.com/7300829/82724057-80bb1c00-9cd3-11ea-8015-917d3d3d5e79.png)

You can also make a small circle where the rider is on the graph. 

Regards 
Martin

**Comment by littlehelper** [comment]
I would love to see such widget.
Similar proposal in #5684

**Comment by sonora** [comment]
I think our 'Analyze on map' function produces the view you are talking about (for a GPX file: Menu button / MyPlaces / Tracks / (tap any track) / Analyze on map, or for a route under Details / Analyze on map). But I am not sure it displays your position on the graph, only the other way round: if you tap the graph that indicates the respective location on the map).

**Comment by mschwehl** [comment]
the screenshot is taken from the current version osmand+ so all features are already build in. The only problem is you can not have it while riding. "Analyze on map" is very close but in this mode you are missing turn by turn view and 'center' button

**Comment by littlehelper** [comment]
For me this enhancement would improve using Osmand as kind of cycle computer on the handle bar tremendously. Together with a trip computer view #1734 this proposed elevation view would help me to always see where I am on my ride and what will come the next kilometers at one glance.
Up to now it is easy to follow my position/progress on the map, to be able to follow it live on the elevation profile in parallel would be awesome on the one hand.
On the other hand this feature would help me in answering my family's or riding partner's questions like "How far are we? How many uphill meters to go?" easily. :)

**Comment by mschwehl** [comment]
from a technical perspective, it is also very handy to have a placeholder-widget below the map. You can show wikipedia, elevation-view (zoomable), have a poi-area to display text, and so forth. Just make the area swipeable and you put context-information whether for the track or the point you click on the map

**Comment by vshcherb** [comment]
It is partially implemented with Analyze on graph, there you can synchornize the graph with current position and graph will be updated automatically once you start moving. We need to implement it as a widget for current navigation route or selected route.
So this request is merged to https://github.com/osmandapp/OsmAnd/issues/5684
