### ISSUE TITLE
When changing group of favourite, color should also change

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#9060]
Especially when creating a new fav, and change the group, the color should "follow" that change.
Version nightly 3.7.9#29794 2020-05-22

**Comment by cebderby** [comment]
This also needs to happen when editing an existing favourite, changing the group must change the colour to the colour of the group - unless perhaps if the point was not the colour of the old group ie had been manually changed as now possible.

**Comment by vshcherb** [comment]
2. when we change category color, we should update all points color that matched category color before
