### ISSUE TITLE
Heavy performance issues when using external input device

### ISSUE THREAD

**Issue by cngripper** [osmandapp/Osmand#9067]
Hello,
I experince heavy performance issues when using an external input device (keyboard) e.g. for moving the map and zooming. After the keyboard has been used the first time for example for moving or zooming in the map, the performance issues starts and the map renders extremly slow and also with a lot of artifacts (e.g. white areas). Scrolling and zooming using the touchscreen behaves similar.
After the external input device is disconnected, zooming and moving the map works again.
Im using a Moto G6.

**Comment by cngripper** [comment]
I did some more test and notced further strange behaviour: it runs much better if I enable some further display information, like the FPS-Debug-Info or the circkes around the display center.

**Comment by Chumva** [comment]
What android version are you using? Can you add video with this issue?
