### ISSUE TITLE
French translation issue 

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#9071]
In English, both in OSM and OsmAnd, the POI belongs to the healthcare: physiotherapist tag.
In French, the very same POI belongs to the psychotherapist tag.
The issue occurs at: 43.49213 -1.46439
https://www.openstreetmap.org/node/7510210795#map=19/43.49211/-1.46378
![image](https://user-images.githubusercontent.com/50198677/82788224-b0ebf180-9e70-11ea-9bef-d7f5cdcf2b7e.png)
![image](https://user-images.githubusercontent.com/50198677/82788226-b47f7880-9e70-11ea-9c7c-1dfb3c229629.png)
![image](https://user-images.githubusercontent.com/50198677/82788232-b77a6900-9e70-11ea-8efe-cd53e78c7f3a.png)

**Comment by vshcherb** [comment]
Sorry didn't undestand what's the issue about
