### ISSUE TITLE
Add "Replace" button to the context menu of navigation points

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#9074]
I think we can add the "Replace" button next to "Remove" to the context menu of start, waypoint, and destination point, which will open a menu similar to "Set starting point". 
![Screenshot_20200525-132910](https://user-images.githubusercontent.com/9365308/82805411-a6d7ec00-9e8c-11ea-9bc2-8ef596a88888.png)
![Screenshot_20200525-133524](https://user-images.githubusercontent.com/9365308/82805423-accdcd00-9e8c-11ea-89ac-c77359285259.png)

**Comment by vshcherb** [comment]
Too complicated looks like and it will make UI more cluttered
