### ISSUE TITLE
FPS icon

### ISSUE THREAD

**Issue by 532910** [osmandapp/OsmAnd#9078]
The same FPS icon should be used on the widget as in settings:

![image](https://user-images.githubusercontent.com/14617699/82830361-3053e200-9ebe-11ea-9a39-2a5288a954b8.png)
+
![image](https://user-images.githubusercontent.com/14617699/82830370-347fff80-9ebe-11ea-87fc-d7453e2b0d6e.png)
↓
![image](https://user-images.githubusercontent.com/14617699/82830380-3cd83a80-9ebe-11ea-9ca7-33dc223b2545.png)

**Comment by 532910** [comment]
And the font size should be the same as for other widgets.

**Comment by dmpr0** [comment]
I added icons 1985364a2134ccb41bca40f14e80de7baff9f1ff

**Comment by 532910** [comment]
Nice, what about font size?

**Comment by vshcherb** [comment]
It is small cause it could be 6-7 chars

**Comment by 532910** [comment]
`Start`(for the AV note) takes 5 chars and there is a free space for 3-4 chars more.
