### ISSUE TITLE
per profile recorded track color

### ISSUE THREAD

**Issue by 532910** [osmandapp/OsmAnd#9080]
It will be nice to have different track colors for different profiles and different map modes (day/night).
While some color looks well on one view it's invisible on another one.

**Comment by sonora** [comment]
You can adjust the GPX color for any background, map section, mode,  or current light condition under MyPlaces/Tracks.

There are also colors which are compromise-visible in both day and night conditions (check out e.g. the route color in the Touring view map style), but it always depends on map type and map section.

Hence I think it may be overkill to and not too universally useful  have automatic color switching just for that ttansition.

**Comment by 532910** [comment]
1. I need to adjust colors every time I switch to another profile
2. There are no compromise-visible colors for all Map Styles.

**Comment by sonora** [comment]
So is your request to remember each individual custom GPX color per app profile, per map style, and per map mode?

Have you tried the default GPX colors, they are contained in the map styles, maybe your issue only exists up when you use a customized fixed color?

**Comment by vshcherb** [comment]
We plan to have individual track colors instead of default track colors for profile. And we plan to make it easier to configure.

**Comment by 532910** [comment]
BTW, it will be nice to be able to choose own color instead of a predefined set.

**Comment by 532910** [comment]
> So is your request to remember each individual custom GPX color per app profile, per map style, and per map mode?

per app profile + map mode should cover all needs

**Comment by dmpr0** [comment]
Current nightly builds have a new "Appearance" screen for each track file, where is possible to set the custom color with custom transparency. 
Right now we don't have plans to add options to set color depending on profile, mostly because it we save and read colors from GPX file and it will add more complex UI.
