### ISSUE TITLE
Display Osmand with power button (while screen is locked)

### ISSUE THREAD

**Issue by rafafaf29** [osmandapp/Osmand#9082]
Hello !

It would be nice to be able to turn on phone screen using power button, with Osmand displayed, while phone is locked.

We can do this by waving the hand in front of the phone, but that feature always turn on screen while phone is on my pocket (i often use it for directions while walking, keeping phone in my pocket, and looking at it every 5 minutes or so, just to be sure i'm in the right direction). So it's heating, and draining battery very fast.
So i disable it, but the i have to unlock the phone every time, making a 1 second action a 10 seconds action (and sometimes i walk into something, or someone...)

It was possible before, i think when Osmand had Admin right on the phone.
If there is any way i can help, please tell me :)

**Comment by rafafaf29** [comment]
Hello !
I see this bug/request have been assigned, so thank you for taking it into account :)

On the same topic, i think the 2 "manual turn on screen" options (with hand waving and with power button) should be separated from the "auto turn on screen" option (some time before a direction change), because it can answer different needs.

So, instead of having :

1. Turn on screen  (on-off)
  1.1. Time  (x seconds)
  1.2. Use proximity sensor (on-off)

we could have :

1. Turn on screen (menu)
   1.1. Auto turn on screen (on-off)
      1.1.1. Time before direction change (x seconds)
      1.1.2. Time to stay on after direction change (x seconds)    (suggestion)
   1.2. Use proximity sensor (on-off)
   1.3. Use power button (on-off)

**Comment by Chumva** [comment]
Fixed with https://github.com/osmandapp/Osmand/pull/9099. 
Power button should work with `System screen timeout` or `custom screen timeout` set to `Keep screen on`. There is a new menu `Screen control` in profile general settings.
