### ISSUE TITLE
barrier=swing_gate icons display issue 3.7

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#9088]
The icons which stand for the road gates are displayed as black circles
E.g. at 49.90515, 8.703672
![image](https://user-images.githubusercontent.com/50198677/83005064-0cf17a00-a019-11ea-90aa-8e5719e78b5c.png)

**Comment by vshcherb** [comment]
Should be fixed now

**Comment by dmpr0** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/090403c4abebb3b2d83d0b9e50273daa21500dc8
