### ISSUE TITLE
Accuracy vs Precision

### ISSUE THREAD

**Issue by iriman** [osmandapp/Osmand#9091]
from https://hosted.weblate.org/translate/osmand/main/fa/?checksum=5e26c4fd1f28e3d

> This will record only points measured with a minimum accuracy indication (in meters/feet, as reported by Android for your chipset). Accuracy refers to the scatter of repeated measurements, and is not directly related to precision, which defines how close your measurements are to your true position.

I guess the second sentence should be:

> Precision refers to the scatter of repeated measurements, and is not directly related to accuracy, which defines how close your measurements are to your true position.

or better:

> Accuracy refers to how close your measurements are to your true position, and is not directly related to precision, which is the scatter of repeated measurements.

**Comment by sonora** [comment]
Thank you, let me please congratulate you on spotting this!  ;)
- Fixed.
