### ISSUE TITLE
OSM editing: OsmAnd loses modifications on upload

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#9093]
OsmAnd sometimes doesn't upload all POI changes. This seems to happen when modifying a POI, keeping the modifications _without_ uploading them and then later re-modifying it before uploading it.

An example is this changeset: https://www.openstreetmap.org/changeset/85846214 (https://overpass-api.de/achavi/?changeset=85846214). I modified the cuisine tag but the modifications haven't been uploaded. The changeset is essentially empty.

So far I encountered this bug already multiple times. It exists since many versions, probably always has been. Unfortunately so far I wasn't able to reproduce it deliberately.

**Comment by vshcherb** [comment]
We were again not able to reproduce and we still have no idea when & how this happens. We will postpone it to collect more information

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/10646 needs to be check for extra information

**Comment by phaerrax** [comment]
This happened to me twice over the last few days. I edited more or less fifty points on the map, then uploaded them later in two bunches, in two different days. Today I find that for each POI only one or two tags, among the ones I added or edited (they were about six or seven, for each POI), were uploaded, the others are nowhere to be found, so I practically lost all the work I did.

**Comment by scaidermern** [comment]
@vshcherb If you can't reproduce it then maybe try to add some debugging information instead. For example log messages that help to understand the problem. Edited text fields, changed tags, a list of tags to upload etc.

**Comment by phaerrax** [comment]
Could a notification also be shown to the user to warn them about this before they upload? At least until it's resolved, so that they can back up the edits, or just automatically do the backup; this way in the unfortunate case the upload fails at least they can try again, without losing their work.

**Comment by pebogufi** [comment]
Bofore uploading your edits, you can also export (=share) your changes resp. the current data to a .osc file. So you can verify what happens.
Use
My Places / OSM Edits, then on bottom the share/export symbol.

**Comment by pebogufi** [comment]
@phaerrax The described export can also be used as backup.

**Comment by phaerrax** [comment]
Yes, of course. If only I had known that before yesterday...

**Comment by phaerrax** [comment]
It happened once again yesterday. I tried today, and it didn't. I can't find what triggers this behaviour. I thought that the tags added through the "basic" panel were discarded, and somehow OsmAnd uploaded just the ones I manually added in the "advanced" panel (that's what I thought it happened the previous times), but today tags from both groups were succesfully added.

**Comment by letypequividelespoubelles** [comment]
It happens once again today. It didn't upload the name of the restaurant I modified. With Osmand 3.9.10 from f droid

**Comment by lgommans** [comment]
Hi, I ran into this bug as well (thanks to Alex for [linking](https://t.me/OpenStreetMapOrg/80381) me here). See the change history of this way: https://www.openstreetmap.org/way/276647641/history

I don't know if there are clear steps to reproduce, but it consistently happened on that object. I don't remember seeing this in past edits with OsmAnd, but I also rarely edit with OsmAnd¹. Perhaps try to do an innocuous change, like add (and later remove) two dummy tags since doing single tag edits seems to work? To reproduce more closely, the way I do tag edits is this:

1. Zoom on the downloaded map in OsmAnd (Limburg) to the object and short tap it
2. Click on the Actions option
3. Click on Modify POI
4. Go to the Advanced tab
5. Scroll to bottom, hit add tag, do the edits... and I always decapitalize the tag name (my keyboard tries to capitalize the first letter) in case that might make a difference.
6. Click on Save
7. Click on Upload in the still-open object details view (what we interacted with in steps 2 and 3)

This is with OsmAnd~ version from F-Droid, 3.9.10.

¹ In case someone is looking for user experience reports to improve mobile editing in OsmAnd: the scrolling doesn't work well in the advanced edit view, tag and value suggestions are not context-aware (rarely helpful, often in the way), always need to uncapitalize the tag name, no presets, no error checking, can only edit certain types of points. And also simply it's a mobile view with an annoying touchscreen, so I'd usually want to create things in a few taps using presets, similar to the style of StreetComplete but for new nodes or ways.

**Comment by xeruf** [comment]
I was about to open a new issue, but this seems related:
Just today I edited a POI and pressed upload.  The upload failed, but the modifications were also gone nowhere to be found, essentially losing my work.
I remember experiencing this months ago as well. This has already corroded lots of trust in OSMAnd as a mapping aid - now I often take notes and try to make the edits on the computer, but I tend to forget about them by then and then never do them.

**Comment by scaidermern** [comment]
> The upload failed, but the modifications were also gone nowhere to be found, essentially losing my work.

This is strange. If the upload fails the modifications should still be available, allowing you to upload them again.

**Comment by xeruf** [comment]
Well, for me, modifications also seem to be lost as soon as I deselect a POI, so I can't batch edits. Using the latest version from F-Droid.
Or are they stored somewhere outside the POI?

**Comment by scaidermern** [comment]
> Well, for me, modifications also seem to be lost as soon as I deselect a POI, so I can't batch edits. Using the latest version from F-Droid.
> Or are they stored somewhere outside the POI?

They are stored as separate OSM edits. You can enable to show OSM edits under "Configure map" although this should be the default. You can also see pending edits at My Places > OSM edits.

**Comment by xeruf** [comment]
> > Well, for me, modifications also seem to be lost as soon as I deselect a POI, so I can't batch edits. Using the latest version from F-Droid.
> > Or are they stored somewhere outside the POI?
> 
> They are stored as separate OSM edits. You can enable to show OSM edits under "Configure map" although this should be the default. You can also see pending edits at My Places > OSM edits.

Oh, thank you very much! I initially disabled as much options as possible to avoid clutter and didn't know what this option meant.
Maybe its icon should be a pencil rather than a lens to indicate these are _my_ edits and not some kind of explorative feature ^^

**Comment by mnalis** [comment]
@lgommans, when you do that edit, is you mobile data connection enabled or disabled? (I am not sure if OsmAnd tries to download latest revision of the element when one does edit if you are online)

**Comment by lgommans** [comment]
That is a good question, I do not remember whether that was enabled. Odds are good that it was. Then again, I'm also fairly certain that I edited multiple tags in one go, not that I opened up the edit screen twice.

**Comment by scaidermern** [comment]
Bug still exists in version 4.1.6.

This time I added two tags and closed the edit mode. Then I opened the edited object again because I forgot a tag. I added this third tag and closed the edit mode. Then I uploaded the POI. Only the last tag has been added, the first two tags from the first edit got lost.

**Comment by scaidermern** [comment]
> Bug still exists in version 4.1.6.
> 
> This time I added two tags and closed the edit mode. Then I opened the edited object again because I forgot a tag. I added this third tag and closed the edit mode. Then I uploaded the POI. Only the last tag has been added, the first two tags from the first edit got lost.

Oh, I just realized that this could be a separate issue. How to reproduce:

- edit a POI, add a tag, save without upload
- edit the POI again (the original POI, not the existing edit)
- previous tag changes are not present and will get lost on save/upload

**Comment by letypequividelespoubelles** [comment]
I had the same, not sure it's linked : I modify a POI, and then move the modify POI, and then upload the modify POI. It ended with no modifiction at all, for exemple [this changeset](https://www.openstreetmap.org/changeset/115101816).
