### ISSUE TITLE
Huge icons on tablet

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#9100]
Device tablet Samsung S5e SM-T725, 10,1"

on version 3.7.0#29844 2020-05-28
I have huge icons of favs, pois and other.
![Screenshot_Huge-Icons](https://user-images.githubusercontent.com/18628183/83176056-27148080-a11d-11ea-8e83-ad42780c5a2f.jpg)

It was ok with version 3.7.0#29725 2020-05-17
![Screenshot_Normal IconSize](https://user-images.githubusercontent.com/18628183/83176077-2d0a6180-a11d-11ea-8cde-5a46b6a1899b.jpg)

**Comment by dmpr0** [comment]
Hello, @pebogufi! Thank you for the feedback.
Do you increase the "Text size" option value in "Configure Map"? I think in the latest nightly updates this option affects all icons on the map, before that only colored POI's increased with this option.

**Comment by pebogufi** [comment]
No, the two screenshots are made only with exchanging osmand, no changes made in any other settings. The huge buttons occured short after the "good" version of may 17.
