### ISSUE TITLE
Missing house numbers not interpolated by forward address search

### ISSUE THREAD

**Issue by joernheissler** [osmandapp/Osmand#9101]
Hello,

System Info:

* Android 10 (Samsung Note 10 Lite)
* OsmAnd 3.7.2
* Germany Schleswig-Holstein, 1 May 2020

What I did:

I tried navigating to the address `Hamburger Straße 30, Bad Bramstedt` ( `<streetname> <housenumber>, <city>`). OpenStreetmap data is missing that particular (and lots of other) house numbers in that street.

What I saw:

OsmAnd presented me with the street+housenumber combo in lots of other cities, but not in `Bad Bramstedt`.

What I was expecting instead:

Could OsmAnd still show the street and try to approximate the house number even if the result will be off by a few hundred meters? There are house numbers 2 and 46, so it should be somewhere inbetween. Might have pointed to https://osm.org/go/0HpEeP1uh--?m= or nearby.

Cheers!

![Screenshot_20200528-215553_OsmAnd](https://user-images.githubusercontent.com/865592/83190703-1cfd7c80-a133-11ea-8d60-977d022ee060.jpg)
![Screenshot_20200528-215453_OsmAnd](https://user-images.githubusercontent.com/865592/83190706-1d961300-a133-11ea-95fd-566c8246e8dd.jpg)

**Comment by vshcherb** [comment]
with 3.7.3 you can find
Hamburger Straße 53, 24576 Bad Bramsted - as first result

**Comment by joernheissler** [comment]
Thanks, that solves my problem.

> Though i didn't find house number 30 on that street in OSM

It's missing from OSM.
