### ISSUE TITLE
[Feature request] Ability to change My Favourite icons for a whole group

### ISSUE THREAD

**Issue by Boothy99** [osmandapp/OsmAnd#9104]
Updated to android OsmAnd+ 3.7.2
Following the update and ability to choose a variety of icons / colours for My Favourites, I found I can change an icon for an individual favourite, but am not able to change a group of favourites (and I have a lot 😕) in one go. 
Only "Edit name" or "Change colour" is available from the menu alongside a Favourite group (in My Places / My Favourites). Could there be a "Change Icon" available in this menu, so that all items can be changed at once, rather than having to change them individually?

I also noted that when I imported favourites.gpx from one device to another - the icons that were set as original "star-inside-circle" became changed to "globe+POI marker" icons (colours transferred correctly). I would preferred to have kept the original standard star icon on importing Favourites.

**Comment by Boothy99** [comment]
Thanks for updating the issue for a future milestone, vshcherb.

**Comment by Friptick** [comment]
Can confirm this problem in 3.7.3. A group color is no longer attributed to a new POI of the group. Seems like an oversight.

**Comment by Friptick** [comment]
Any news on this?

Please note that it is a straightforward bug, not a feature request as OP put it. To reproduce:

1. In  **My Places > Favorites**, attribute the color **red** to the **Hotel** group
2. On the map, **Add** a new favorite, selecting **Hotel** as the group, which is correctly colored **red** in the dialog
3. The new favorite will take the color of the favorite added previously, not red

**Comment by Boothy99** [comment]
@Friptick - the issue of a new Favourite added to a group and not retaining the correct original colour appears to have been corrected in the new update OsmAnd+ 3.8.2 (22-9-20).
Hopefully the addition of ability to change the group's icon might follow soon 🤞

**Comment by tradavyvy** [comment]
this issue seems linked to issue 9861

**Comment by Friptick** [comment]
> appears to have been corrected in the new update OsmAnd+ 3.8.2 (22-9-20)

Confirmed! It finally turned up in F-Droid. Thanks @vshcherb for your patience and commitment.

**Comment by tradavyvy** [comment]
This is simmilar to issue #10850 wich is scheduled for version 4.1

**Comment by Friptick** [comment]
@vshcherb Please merge this into #10850 which is already milestoned. They are the same thing (which I want too).

**Comment by Boothy99** [comment]
They do appears to be the same thing as tradavyvy's "Default shape and icon for favorite groups #10850" earmarked for milestone 4.1-android.

**Comment by vshcherb** [comment]
It's not clear how "default shape / icon " will be implemented and will it be satisfactory, so it's better to have references for the issues. Though "default shape / icon for a group" doesn't have UI-design yet, so it's quite far from implementation still

**Comment by vshcherb** [comment]
I see 2 issues have 2 different goals and 2 different tasks, if they are implemented at the same time or not will be decided later once development is started. I don't disagree now that 1 solution could fit them both but I see 2 use cases for end user.

**Comment by MiMoHo** [comment]
I find the requested feature very useful as after importing my library on a new device, all favorites got the same globe icon.
However, in some cases, there are different icons within the same category like cutlery for food but a burger and glass for fast food. When now changing the icon of my restaurant folder, the OSM category would be ignored. So I would need to write either the food or fast food icon over my restaurant folder. Thus, there should also be an option to revert to "default". That way, I could first convert my restaurants labeled with a globe icon to cutlery and then revert back to the default icon on OSM so that I get an appropriate icon for all places regardless if it's a personal or registered OSM POI.

**Comment by dmpr0** [comment]
Done, available in the latest nightly builds, but developers have to make a few fixes.

**Comment by Boothy99** [comment]
Thanks @dmpr0 👍👌
I (we) look forward to seeing the final release.
Cheers,
Dave.

**Comment by Boothy99** [comment]
Many thanks for adding the new ability to completely edit POI appearances !! Excellent work and much appreciated.

**Comment by tradavyvy** [comment]
Verry happy too
