### ISSUE TITLE
Screen control issues

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#9110]
**(1)** This control could be set up in a little more logical fasion, I think the screen should be divided in an upper section called 'Screen timeout' with options 'No timeout',  'Use system timeout', and 'Custom timeout' (slider).

The lower half of the scren should be called 'Turn on options', where description turn_screen_on_descr alone would suffice, and then the 3 options we alteady have there.

**(2)** There is currently a bug that if you once set the Power button option to On, it seems that disabling this again does not disable the associated functionality ever again. (the only way I find  to suspend the functionality again is while a custom timeout is selected).

**Comment by sonora** [comment]
Ok, this https://github.com/osmandapp/Osmand/commit/14c40b24589d5680e1f5b5f1d13e2b464cd3e98c mitigates **(1)** by now producing this setup: 

![Screenshot_20200603-095718_OsmAnd~](https://user-images.githubusercontent.com/845735/83611347-2480b380-a581-11ea-9310-b18ad1ee38ad.jpg)

I guess it would still be more simplified if for the '_Screen timeout_' section we simply produced a single list selector like:
```
 [ ]  Use system timeout
 [ ]  No timeout (keep screen on)
 [ ]  5 seconds
 [ ]  10 seconds
 ...
```

**Bug (2)** still seems present in latest nightlies (reproduced under Android 10).

**Comment by vshcherb** [comment]
(1) will be reverted cause it should be related to Turn Screen on and wake up time was a correct name. Right now there is a confusion that Custom screen timeout = 5 seconds will have map for 5 seconds enabled and this is not true. This Wake up interval is related only for non-user interaction screen. More important if wake up interval is not 'keep screen always' then 'power button' won't be able to work - technical limitation
(2) is fixed already

**Comment by vshcherb** [comment]
It is quite complicated though it provides the best options we can implement. All combinations were tested and it works on my device but indeed it is not the easy function
+ 0. No Settings enabled + Wake  time
+ 1. Screen timeout on, Power Button 
+ 2. Screen timeout on, Power Button + Proximity 
+ 3. Screen timeout on, Proximity  
+ 4. Screen timeout on 
——————- Screen timeout off ——————
+ 5. Wake time = Keep screen on, Power Button 
+ 6. Wake time = Keep screen on, Proximity 
+ 7. Wake time = Keep screen on, Power Button + Proximity
XXX 8. Wake time = 5 sec, Power Button 
+ 9. Wake time = 5 sec, Proximity
XXX 10. Wake time = 5 sec, Power Button + Proximity

**Comment by sonora** [comment]
Instead of having a complex settings structure, maybe just put all working combinations into a flat list so the user can pick one?

**Comment by vshcherb** [comment]
we have about 8 different working configurations and only 2 are not working

**Comment by sonora** [comment]
From what I ser, my siggestion above would exactly cover it?

- Instead of saying `Disabled` under `Power button`, we could display a new string `Requires 'Keep screen on' under 'Timeout after wake-up'.`

**Comment by vshcherb** [comment]
- Instead of saying Disabled under Power button, we could display a new string Requires 'Keep screen on' under 'Timeout after wake-up'.

This makes sense

**Comment by sonora** [comment]
https://github.com/osmandapp/Osmand/commit/75d2affdcb3573d56a4b14ffcbfaf64c794f5af6

**Comment by sonora** [comment]
By my testing, all combinations we now allow in the UI work ok.

It is worth noting that the 'Power button' option can either be combined with 'Use system screen timeout' or with 'Keep screen on' (which is our default for the map screen). _The latter carries the significant risk that if you carry the device in your pocket and the power button gets pressed accidentally, the map screen will remain active indefinitely and may drain your battery without you noticing._
