### ISSUE TITLE
Update to harfbuzz C++/Java

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd#9116]
- [x] Update Skia (and check new method to drawTextOnPath)
- [x] Update Skia / Harfbuzz to use new arabic methods
The local name in Arabic is displayed wrong on the map while in the OSMand in the context menu it is correct. The issue occurs at:
35.5469/44.5786
https://www.openstreetmap.org/#map=15/35.5469/44.5786
Correct: 
hb-view ../resources/rendering_styles/fonts/05_NotoSans-Regular.ttf هەیبە

- [ ] Fix namespace conflict with openjdk@11 harfbuzz.dylib - as for now workaround: disable (delete) libharfbuzz.dylib from openjdk. Draft solution is draft and it's better to patch whole namespace for harfbuzz i.e. ``` namespace OT -> namespace OT_OsmAnd``` if we encounter issue later on.

**Comment by vshcherb** [comment]
We have already font that supports it but ICU doesn't render it correctly, so we need to update to harfbuzz
![image](https://user-images.githubusercontent.com/1042025/84377224-92ad2200-abe2-11ea-8b9b-51760d270bda.png)

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-core-legacy/pull/25
https://github.com/osmandapp/OsmAnd/pull/12150

**Comment by ivanPyrohivskyi** [comment]
Need add namespace for local harfbuzz for avoid conflict with system library (openjdk@11 libharfbuzz.dylib)

**Comment by ivanPyrohivskyi** [comment]
Draft branch [issueStaticLibs](https://github.com/osmandapp/OsmAnd-core-legacy/tree/issueStaticLibs)
