### ISSUE TITLE
Church POIs stand out from the rest of POI.

### ISSUE THREAD

**Issue by BikeRoad** [osmandapp/OsmAnd#9137]
When I enable the "more details" option, church POIs stand out from the rest of POI. It is normal?
I remember that in previous versions (2.x.x) that did not happen.

"more details" enabled
![Screenshot_20200603-225652700](https://user-images.githubusercontent.com/19896035/83713722-80355600-a5ee-11ea-9bb4-ad0da85419cc.jpg)

"more details" disabled
![Screenshot_20200603-225713261](https://user-images.githubusercontent.com/19896035/83713731-84617380-a5ee-11ea-86c2-ec928ae14347.jpg)

**Comment by sonora** [comment]
Churches are often bigger buildings and as such have a certain value for orientation, hence this may be justified when you select 'More details'.

Having said that, I am not really aware there was a change in related code at all. I do remember,  though, that there were interim issues with POI icon size on tablet devices. I think this has been fixed and should be in the next minor release.

**Comment by cpmsmith** [comment]
I'm still observing this in v4.1.0 on iOS; here's Manhattan island for example: ![image](https://user-images.githubusercontent.com/9437625/147390000-9e52688f-5a11-445a-98e3-ef3cc02c6009.png)

**Comment by xmd5a2** [comment]
Agree with @sonora that churches should be visible at lower zooms than most other POI. Of cource there are places with different density of churches but in my tests most places looks good and these icons are helping to navigate.

**Comment by sonora** [comment]
Precisely. "More details" means "More details", and church buildings are above-average valuable for orientation.

Comparing the 2 "with and without More Details" Lima screenshots provided above, the inclusion of the churches seems to be the bulk of the difference anyway. If excluding these, the setting "More details" would make very little difference at all.

I would definitely leave it as is!

**Comment by sonora** [comment]
@xmd5a2 I suggest we close this without action?
