### ISSUE TITLE
favourites displayed as white circles

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#9139]
in latest version 3.7.0#29888 2020-06-03 favourites which are diplayed in small version when zoomed out are now displayed as white circles.
In older versions, they hve been resized.
Examples in screenshot: 
camping car in pink square is in other favs resized wrong.
Edit: some of white circles are in normal size also the standard circles with star.

![Screenshot_20200604-103311_OsmAnd~~01](https://user-images.githubusercontent.com/18628183/83734678-9d4e4100-a64f-11ea-9082-ba111e399f69.jpg)

**Comment by dmpr0** [comment]
Hello! Thank you for the feedback.
We are currently working on fixing this issue, and planning to fix it today at nightly's.
