### ISSUE TITLE
Color route=foot according to OSMC

### ISSUE THREAD

**Issue by shadow-identity** [osmandapp/Osmand#9145]
Hi and congrats for anniversary,

Please use `osmc:symbol=*` also for `route=foot` relations, not only for `route=hiking` and  `route=horse`. _Foot_ relations widely used in cities, parks etc, and they often has color marks: http://overpass-turbo.eu/s/UHq

According to wiki, `osmc:symbol` is approved for _foot_ as well as for _horse_ and _hiking_.
https://wiki.openstreetmap.org/wiki/Key:osmc:symbol

**Comment by vshcherb** [comment]
Should be accessible with new June maps
