### ISSUE TITLE
Sharing tracks, favorites or edits uses previously chosen target

### ISSUE THREAD

**Issue by opk12** [osmandapp/Osmand#9146]
1. I chose WhatsApp the first time I clicked Share under tab Favorites. Now tabs Favorites and OSM Edits always send to WhatApp (do not ask me for a target).

2. Track sharing behaves the same with another target. I shared the first track with Signal. Now tabs Favorites and OSM edits are bound to WhatsApp and any track's detail page is bound to Signal.

3. I installed VLC, which created a share target visible in other applications. Then, I clicked OsmAnd's Share buttons. They asked for the target once (as if they were "reset") and got stuck with that target, again. Instead, upgrading VLC does not "reset" them.

4. Selecting a favorite, marker or OSM edit on the map and clicking Share/Send does as expected (always pops up the target list). Please note that this shares a string of coordinates, but the stuck Share buttons of paragraphs 1 and 2 share files *.gpx.

5. Other apps on the phone share files and text as expected flawlessly (always pop up the target list).

Android 7
Happens with OsmAnd 3.6 and 3.7

**Comment by vshcherb** [comment]
It is possible to reset this connection in System  -> Apps -> OsmAnd

**Comment by dmpr0** [comment]
Hello! Thank you for the feedback.
Are you using a Samsung device? I have the same behavior on the Samsung devices, it can be fixed by going to device Settings – find Default Apps – Default App selection, set to Ask before setting.

**Comment by opk12** [comment]
Many thanks. These are Samsung smartphones. Got the connection cleared with Settings >> Apps >> Signal >> Set as default >> Clear defaults.
