### ISSUE TITLE
Navigation Voice Repeation

### ISSUE THREAD

**Issue by IamStefin** [osmandapp/Osmand#9151]
The Voice will keep on repeating until the number of times I pressed that top left button during navigation.

**How to recreate this Issue?**

1. Navigate to the destination
2. Click on the highlighted part of the image that follow

![photo](https://user-images.githubusercontent.com/28928206/83866521-89f1b300-a6ed-11ea-9e7c-074861e93ea9.jpeg)

**Comment by vshcherb** [comment]
This is exactly how it supposed to work. You've found a feature, Congrats!

**Comment by IamStefin** [comment]
Okay :)
