### ISSUE TITLE
Menu -> navigation -> navigation settings ignore theme

### ISSUE THREAD

**Issue by Bushmills** [osmandapp/Osmand#9153]
Selected theme is "always dark / night mode". Navigating to those configuration pages shows them, contrary to other menu pages, with white background.
![Screenshot_20200605-150754_OsmAnd+](https://user-images.githubusercontent.com/1392204/83879854-9b16e000-a73e-11ea-9f91-69ef42b1bce7.png)
![Screenshot_20200605-150806_OsmAnd+](https://user-images.githubusercontent.com/1392204/83879865-9f42fd80-a73e-11ea-94bf-312261658603.png)

**Comment by vshcherb** [comment]
You need to select "dark theme" in general settings as well. Dark/light is map related setting.

**Comment by Bushmills** [comment]
Of course. But it is (and has been) set to as dark as it can be for quite some time already.
![Screenshot_20200605-182048_LineageOS-Einstellungen](https://user-images.githubusercontent.com/1392204/83900046-bd6a2700-a759-11ea-8cc3-793cf064c023.png)

**Comment by vshcherb** [comment]
You need to apply Dark Theme - Globally cause Navigation Settings use Theme from its own driving profile
