### ISSUE TITLE
Unnecessary Turn by Turn Directions When Navigating Using a .gpx File

### ISSUE THREAD

**Issue by ospangler** [osmandapp/Osmand#9160]
I've been trying to create biking routes using the OpenRoutingSerivce and importing the .gpx track into OsmAnd for navigation. However, whenever there is even a slight curve in the road, OsmAnd adds unnecessary and repetitive turn by turn directions, as [depicted in this example](https://imgur.com/a/IRTqveE).

This kind of turn by turn navigation seems to happen for even recorded .gpx files in the app, so I don't think the issue is exclusive to the OpenRouting service I'm using. Is there any way to clean up these directions by doing something like snapping the route to roads within OsmAnd?

[Here is the route in the OpenRouting planner](https://maps.openrouteservice.org/directions?n1=41.182724&n2=-73.449075&n3=15&a=41.194399,-73.438239,41.182667,-73.454483,41.173227,-73.45238&b=0&c=0&k1=en-US&k2=km) and I've attached the .gpx file used for navigation below.

[ExampleTrack.zip](https://github.com/osmandapp/Osmand/files/4742475/ExampleTrack.zip)

Version 3.7.3 on Android, Using the Cycling Routing Profile

**Comment by bhugh** [comment]
The primary issue where this is being actively discussed seems to be [#3908](https://github.com/osmandapp/Osmand/issues/3908).

**Comment by ospangler** [comment]
> The primary issue where this is being actively discussed seems to be [#3908](https://github.com/osmandapp/Osmand/issues/3908).

Apologies, I missed that issue when searching for similar ones. Thank you!
