### ISSUE TITLE
Remove outdated Plugin Settings screens and code

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#9162]
Spillover of #8911: We now have new and correctly themed plugin settings screens, reachable via `Configure profile`. We have disabled most old setting screens which where reachable via `Menu / Plugins / <Plugin> / Settings`, but there we still have the the following now redundant Settings screens for
 - Trip recording
 - Audio/video notes
 - OpenStreetMap editing
 - Accessibility
 - OsmAnd development

As discovered in https://github.com/osmandapp/Osmand/issues/8911#issuecomment-639745714, these do not only use their own, outdated layout, but also partly their own methods and their own string resources. Removing all this cleanly provides a significant clean-up potential.

**Comment by vshcherb** [comment]
Obviously these settings needs to be combined though it is planned for 2020 to redesign Plugins screen completely and it will be part of it.

**Comment by sonora** [comment]
From what I see, all screens I listed here as obsolete are present now in their maintained state and updated layout also under "Configure profile".

**Comment by Chumva** [comment]
This should be fixed here - https://github.com/osmandapp/OsmAnd/pull/10015.

**Comment by dmpr0** [comment]
In Menu – Plugins – Tapping on description text doesn't do anything, in some cases text scrolling could be started.

**Comment by vshcherb** [comment]
@dmpr0 please open separate issue, this screen needs a redesign.
