### ISSUE TITLE
opening_hours:lastcheck is parsed as opening hours value

### ISSUE THREAD

**Issue by Discostu36** [osmandapp/Osmand#9163]
The support of opening hours tags with a colon needs an exception for `opening_hours:lastcheck`. This is used for providing information about the last time the correctness of the openig hours value was validated. At the moment Osmand interprets this key as 24/7 open.

**Comment by Discostu36** [comment]
![Screenshot_20200608-111316_OsmAnd](https://user-images.githubusercontent.com/30999326/84013439-35626800-a979-11ea-82c7-a71ab805d176.jpg)

**Comment by sonora** [comment]
Duplicate: #9159
