### ISSUE TITLE
Issue to download slopes for Quebec

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/Osmand#9165]
Slopes for Quebec, the size look quite big. 
Download it goes directly to 99% and after that the app is freezed.
![image](https://user-images.githubusercontent.com/44466116/84031474-6a34e600-a99e-11ea-9ef3-f406d8e3b7d6.png)
![image](https://user-images.githubusercontent.com/44466116/84031499-74ef7b00-a99e-11ea-8968-935cfbc3081d.png)

**Comment by ssejourne** [comment]
+1

**Comment by vshcherb** [comment]
There is a request to split Canada maps into reasonable chunks by size

**Comment by xmd5a2** [comment]
Fixed by adding subregion slope maps
