### ISSUE TITLE
No search result depending on order of entered words

### ISSUE THREAD

**Issue by Isolator70** [osmandapp/Osmand#9166]
**Topic:** Depending in which order one enter a result into the search you will get the correct or no result at all.

**Issue**: Searching for a railway station (German: Bahnhof) at a specific location. The name of the railway station is known and existing exactely like given on the map on the device.

**Usecase**: 
A: If one enter "Bahnhof Friedrichssegen" (English: "Trainstation Friedrichssegen") one get NO result.
B: If one enter "Friedrichsegen Bahnhof" (English: "Friedrichsegen Trainstation") the result is topmost on the list.
C: Sometimes(!) a generic list entry "Bahnhof" (English: Railwaystation) is the only entry in the list, but it refers to the GPS instead of the searched location. In that case there is no change , if the search area is expanded up to 100km, even if the station is ~62km away (Screenshot B)

**Expected**: Even if the strings are entered like A, the search should deliver the result. No one will understand why he has to follow a specific order, because it's Nineties style and not inuitive. Moreover its in the nature of German language to say _type_ followed by the _location_ of it.  (Bahnhof München).

**Impact**: Frustrated users

**Steps to reproduce:**
1. Map Location is set to Lahnstein, Germany
2. Open search and execute usecase.

Depending if one selects "Bahnhof auf Karte zeigen" (E: "Show railwaystations on map") prior to enter the name one will get the offer to increase the search radius (tried with 100km and no result)

Screenshot usecase A:
![Screenshot_20200608_143203_net osmand plus](https://user-images.githubusercontent.com/35434137/84034147-3b1c7580-a99a-11ea-94fc-aee5f933ae15.jpg)

Screenshot usecase B
![Screenshot_20200608_143412_net osmand plus](https://user-images.githubusercontent.com/35434137/84034361-83d42e80-a99a-11ea-9c6d-4817001b7e06.jpg)

Screenshot usecase C:
![Screenshot_20200608_152410_net osmand plus](https://user-images.githubusercontent.com/35434137/84035736-7e77e380-a99c-11ea-98fb-1376de69bb98.jpg)

**Comment by vshcherb** [comment]
![image](https://user-images.githubusercontent.com/1042025/84046030-db2dcb00-a9a9-11ea-81d7-3cbde04a94a5.png)
Should be fixed with 3.7.3

**Comment by Isolator70** [comment]
Really, the latest version does the trick (I updated some days before writing this ticket but this was prior to release 3.7.3.
So thanks a lot guys for improvement of this nice tool :+
