### ISSUE TITLE
wrong download suggestion: Saint Petersburg slopes 

### ISSUE THREAD

**Issue by 532910** [osmandapp/Osmand#9172]
I have `Slope Russia leningradskaya asia` map installed, but it says I need to download additional map for Saint-Petersburg.

![image](https://user-images.githubusercontent.com/14617699/84081022-e1419d00-a9e5-11ea-803a-e5fd2428eb6f.png)

**Comment by vshcherb** [comment]
![image](https://user-images.githubusercontent.com/1042025/87172122-06227c00-c2d4-11ea-8f85-6433f488dd74.png)
WIkipedia is still suggested

**Comment by Chumva** [comment]
Should be fixed here - https://github.com/osmandapp/Osmand/pull/9472.

**Comment by dmpr0** [comment]
Wikipedia: shadow is lost, below card with language selecting if no map is proposing.
![Group 104](https://user-images.githubusercontent.com/9365308/88041561-434c0100-cb53-11ea-9e49-c64f55baf360.png)

**Comment by vshcherb** [comment]
non-functional requirement will be fixed separately
