### ISSUE TITLE
Wrong title for some wikipedia articles

### ISSUE THREAD

**Issue by YevgeniyMovsesov** [osmandapp/Osmand#9175]
1. OsmAnd 3.7.3, Android 9, Samsung SM-J730F, offline maps
2. Enable Wikipedia map
3. Navigate to the 50.38250° N, 30.47080° E and click Wikipedia icon on "University of Kiev Faculty of Radio..."
4. Click "Read article" and switch to Ukrainian language

Actual result: some gibberish symbols appeared

This is strange, because neither in Ukrainian Wikipedia article, neither in Wikidata I do not see any bad symbols in the headers.

5.1 I've suggested that OsmAnd works bad with apostrophe (%27) found in the Ukrainian title of the article. 
https://uk.wikipedia.org/wiki/Факультет_радіофізики,_електроніки_та_комп%27ютерних_систем_Київського_національного_університету_імені_Тараса_Шевченка

5.2 It seems I was wrong, because OsmAnd works fine with another title with apostrophe:
https://uk.wikipedia.org/wiki/Об'єднаний_інститут_економіки_НАН_України

![Gibberish_UK_wikipedia_OsmAnd](https://user-images.githubusercontent.com/13016833/84124659-31e7e300-aa44-11ea-89e7-1731f31edec6.jpg)

**Comment by vshcherb** [comment]
Title is too long, so it was gzipped and that didn't work properly for UI
