### ISSUE TITLE
"Turn screen on" option went away on OsmAnd 3.7.3 for Android

### ISSUE THREAD

**Issue by florian29** [osmandapp/Osmand#9179]
tested with Android 4.4.4

on OsmAnd 3.7.2 for Android there was an option "Turn screen on" in the navigation settings of each profile:
![372](https://user-images.githubusercontent.com/43439672/84155480-a896d780-aa68-11ea-92bd-c9898dd87145.png)

with the update to OsmAnd 3.7.3 this option has gone, like you can see here:
![373](https://user-images.githubusercontent.com/43439672/84155572-c49a7900-aa68-11ea-82af-3e359ed95669.png)

Is this a mistake or a bug? If it is so, will you bring it back? Or was it removed intentionally? I'm sure not only me but a lot of users want to have this option back. Thank you in advance for replying.

**Comment by vshcherb** [comment]
It has multiple options now and it is under General Settings -> Screen Control
