### ISSUE TITLE
Support more values for club=* POIs

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#9190]
Currently the POI [`club=*`](https://wiki.openstreetmap.org/wiki/Key%3Aclub) gets rendered but is missing all of its details:

![photo_2020-06-10_08-40-28](https://user-images.githubusercontent.com/1040784/84235455-28b74e80-aaf6-11ea-878d-428f97245e83.jpg)
Location: geo:51.06516,13.758837?z=20
https://www.openstreetmap.org/node/3891604053

`club=*` is currently [used](https://taginfo.openstreetmap.org/keys/club) over 24k times world-wide.

**Comment by Aiurek** [comment]
Seems like only a few club-tags are supported: e.g. `club=sport` is illustrated in OsmAnd, whereas `club=music` isn't

https://wiki.openstreetmap.org/wiki/Key%3Aclub

**Comment by scaidermern** [comment]
In this case the list of supported values should be extended, see https://taginfo.openstreetmap.org/keys/club#values for popular values.
