### ISSUE TITLE
[Feature request] add new icons for the Canadian road signs

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#9192]
While in the USA there "Speed limit" road signs are displayed, in Canda they are called "Maximum"
It would be more convenient for Canadian users to see their own signs instead of the United States' ones.

**Comment by dmpr0** [comment]
I have added images 25218bc9a0

**Comment by vshcherb** [comment]
- Widget size on the screen is not 100% (in the release version too)
– больше шрифт у едини измерения
- двузначное ограничение сьезжает на единицы измерения
