### ISSUE TITLE
Default walking speed in profile not editable

### ISSUE THREAD

**Issue by Thunichgud** [osmandapp/Osmand#9194]
I created a custom profile with the base profile Walking. As navigation type I tried "Direct-to-point" and "Straight line" (I don't understand the differences). In both navigation types it is not possible to define the max. and the min. speed and the minimum editable default speed is 4 km/h. 
When I walk straight line in a forrest or anywhere else in the nature, I never reach a speed of 4 km/h. The possible minimum default speed should be 0,1 km/h (one tenth of a kilometer in an hour) or 0,5 km/h (five tenth of a kilometer in an hour). And it should be possible to define a maximum and a minimum speed as in the other navigation types (e.g. OnFoot, Car, Bicycle, BRouter ...).

**Comment by vshcherb** [comment]
There was a misunderstanding, minimum and maximum speed are relavant only for OsmAnd router, we're going to clarify it with UI
