### ISSUE TITLE
Speed/moving time difference while importing external gpx file

### ISSUE THREAD

**Issue by fdawans** [osmandapp/OsmAnd#9198]
I am using Osmand 3.6.3 on Android 10.
It seems that there is an discrepancy when I import a Gpx track from OpenTracks to Osmand.
The moving time (also speed) is calculated differently in Osmand. 
Is there a threshold that I can select somewhere when I am moving at low speed / or when the GPS fix is not precise enough? 
See gpx and screenshots in attachment. 
![Screenshot_20200610-210204](https://user-images.githubusercontent.com/53601011/84307846-d873d700-ab5d-11ea-8c41-246cd873c48e.jpg)
![Screenshot_20200610-210140](https://user-images.githubusercontent.com/53601011/84307850-d9a50400-ab5d-11ea-917f-0590ff5ed060.jpg)

**Comment by patrickziegler** [comment]
This might be a duplicate of https://github.com/osmandapp/OsmAnd/issues/24215 but without the gpx file we can't tell
