### ISSUE TITLE
Favorite does not get the right group-color at first use

### ISSUE THREAD

**Issue by dadavyvy** [osmandapp/Osmand#9213]
When entering a new favorite it gets the color of the last used "group", NOT the color of the current group. The next favorite (if it is in the same group) gets the right color.

Example:
Say I have four groups: Towns (red); Lakes (blue); Parks (green) and Deserts (Yellow).
And the last Favorite I entered was a town.
When I now mark 6 new favorites, the following happens without me selecting a color:
Mark FishLake as a Lake (it turns red)
Mark Swimlake as a Lake (it turns blue)
Mark OakPark as a Park (it turns blue)
Mark SprucePark as a Park (it turns green)
Mark DustyDessert as a Desert (it turns green)
Mark RockyDessert as a Desert (it turns yellow)

This feels like a bug, it looks like the default group-color is activated after the entry of the favorite in stead of after the choice for witch group this favorite is in.

This happens on my phone, my wifes phone and my tablet, all three different (but all Samsung).
I just tested it and the problem is still there in version Osmand+ 3.7.4.

**Comment by pebogufi** [comment]
See also #9060
