### ISSUE TITLE
[request:] default icon for favorite-groups

### ISSUE THREAD

**Issue by dadavyvy** [osmandapp/Osmand#9215]
I love what you are doing with favorites in the latest versions.

I think it would be great to be able to choose a default icon for the favorite groups.
We use osmand for our extensive (motorhome) trips and we have lots of different groups.
A default tent icon for camping spots would make it easier to differentiate them from sanitairy dumpsites (wich are both brown in our color scheme). And our beaches, lakes and hotsprings (all blue) could also use differentiating. It is now possible to mark them all individualy, but a default icon is much easier.
While you are at it, why not also make a default shape per group possible.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/issues/9104
