### ISSUE TITLE
make check_date visible for POIs

### ISSUE THREAD

**Issue by Lukas458** [osmandapp/Osmand#9224]
Hi,
for assessing how actual some osm data are, there's not jst only important how actual own OsmAmd-data are, but also, when a feature was checked out there last time. For this, we have the key check_date=*.

I think it would be worth the effort to add this, here are some examples were it would be useful to see on POIs when they were checked last time:
- shops which are changing quickly (shop=variety_store)
- vending machines which may get removed more and more (vending=cigarettes, vending=chewing_gums)
- amenity=telephone features get removed in industrial countries
the same for:
- information=map
- amenity=clock

**Comment by vshcherb** [comment]
Connected to https://github.com/osmandapp/Osmand/issues/7643

**Comment by Lukas458** [comment]
Yes, true. But even though, I would still attach agreater importance to the tag check_date=*. I already saw so many OSM edits, in which nothing was checked at the location itself. 

These are often quality-issued edits, changing just a tag generally like recycling:glass to recycling:glass_bottles, adding a fixme, reverting a changeset from another user, change one tag to another etc.

I saw hundreds of amenity=telephone for example which were moved some centimetres in the last edit because they might were positioned wrong earlier, but without _any_ survey/local knowledge. There was not even looked whether it still exists at all. Sorry but from showing when a feature was edited last you cannot at all conclude that the feature was checked at this point of time.

**Comment by sonora** [comment]
Similar to #9159 ?

**Comment by Lukas458** [comment]
Hmm, there might be a relation, but the propose would be to add recognizing of check_date, where all tags of a feature were checked (according to the tag's definition). #9159 is about misinterpreting an already recognized (or by mistake recognzied?) key.

**Comment by sonora** [comment]
I only mention this beause I would argue we should display both check_date and lastcheck, not just ignore or filter them.

**Comment by vshcherb** [comment]
Last modified is the most important and it's not a tag though editor could store extra flag that he changed the geometry and didn't check the content of the object. For most POI it's enough information that somebody added some details i.e. he verified object exists and other tags make sense.

So it is merged #7643
