### ISSUE TITLE
shut of osmand down not possible

### ISSUE THREAD

**Issue by schdrag** [osmandapp/Osmand#9228]
compared to Locus maps pro, Osmand can not be shut down by double tap. Allthoug I've closed the Osmand window, Osmand is still active in the background (nice messages: "lost GPS" "route recalculated". Off course during the routing Osmand has to stay active, but not, if I do not want to use Osmand at all.

**Comment by vshcherb** [comment]
You need to disable GPX recording, after that OsmAnd could be easily killed by standard procedure. You can also disable GPX recording on top
