### ISSUE TITLE
asking for rating is an ergonomic solecism

### ISSUE THREAD

**Issue by Bushmills** [osmandapp/Osmand#9231]
especially when OsmAnd is launched by event, when device is attached to motorbike steering bar.
Bikers tend to wear protective gloves. So in order to click the nagging dialog away, I need to stop, remove a glove, then click on a choice before I can don glove again and continue driving. This while there IS a public review which I've left a while ago already.
This applies to the Google Play version of OsmAnd+.
Please remove this completely insensible Rating begging dialog. At least, prevent it from showing again after any choice was made.

**Comment by vshcherb** [comment]
It was redesigned to show only 2 times. There was a bug in previous version up to 3.6.
You also should be able to disable all dialogs in OsmAnd Settings.
