### ISSUE TITLE
"Save" button issue while adding/editing Favorites 

### ISSUE THREAD

**Issue by aslanosm** [osmandapp/Osmand#9234]
Starting from version 3.7.3 there is no way to save "Favorites" usual way.  
The "Save" button stays behind keyboard while adding/editing name for Favorites points and no way to tap on "Save" button. On my phone I use gesture instead of navigation button and accordingly it is very difficult to save point in "Favorites" while driving the car. Please take out the "Save" button.
![Save_button__net osmand plus](https://user-images.githubusercontent.com/38922911/84577569-7cfc5000-adce-11ea-9d04-d3fe0dedd5e5.jpg)

**Comment by sonora** [comment]
True. The issue is that the name field receives focus immediately when the screen is created, which pulls up the keyboard. I guess we could wait if someone really taps the name field at all to change it.

**Comment by vshcherb** [comment]
If it's not possible to bring Save buttons to top, we should support scenario of tapping on Enter (here it should be default action of Save)
