### ISSUE TITLE
Quick action button overlays zoom out button in General Profile

### ISSUE THREAD

**Issue by Trojgarb** [osmandapp/Osmand#9237]
Hello,

did not find similar issue here, so I submit the following:

In Osmand 3.7.3 quick action button overlays zoom out button in General Profile. I tried to switch it off and on, also reset the profile to default settings. The issue concerns only General Profile. The rest of profiles have Quick Action button positioned properly (above zoom in button). I haven't reinstalled/reset the whole app yet, because Osmand has no option to export all settings and I don't have it set again manually.

Greetings.

**Comment by pebogufi** [comment]
If I understand you right...
Make a loong tap on the quick action button, then you can move it

**Comment by aslanosm** [comment]
Confirmed.
It's not only in General Profile.
It's the same on all other profile when you add it.

**Comment by Trojgarb** [comment]
> 
> 
> If I understand you right...
> Make a loong tap on the quick action button, then you can move it

Exactly! Thank you very much. It looks that Osmand has a few quite useful but a little hidden options. :-)
