### ISSUE TITLE
Slow calculation of Snap for large GPX file leads to GPX file being lost

### ISSUE THREAD

**Issue by scorpion-girl** [osmandapp/OsmAnd#9238]
Hello!

I've recorded a route and tried to optimize it.

At first I've opened it, clicked on edit and activated for the route to be attached to available streets/paths. The program Osmand.plus processed this request and attached the single points to the available streets/paths. After the processing had ended, I chose to save this as a new GPX track, selected a title and the program confirmed to have saved the new route under tracks. But neither in Osmand.plus, nor anywhere on my smartphone the new track was available. We did the same with the smartphone of my husband but with similar result.

I've manually recreated the route via "distance measure" and saved it and the program confirmed to have saved the new route under tracks. But neither in Osmand.plus, nor anywhere on my smartphone the new track was available.

It's really unusual, that the program confirms to have saved the gpx-file but it's neither in the program nor on any place on the smartphone available.

The initial recording worked just fine and is listed in the program and the respective folder on the SD card (and Osmand.plus has the rights to use the SD card). I've also tried a re-start of the smartphone and to clear the cache but to no avail.

Is there potentially a limitation in listable entries for "my places"?

I've attached the respective gpx track in zipped format, as the portal wouldn't accept the gpx-file alone.

It would be great, if you could help me, as I find it very disturbing, that I'm not able to automatically optimize the route and save it (or better, that the program confirms the saving but no gpx-file is found neither in Osmand.plus nor anywhere on the smartphone).

Thank you in advance for your help!

Kind regards,
Anett

[2020-06-13_10-34_Solingen Obstweg_original.zip](https://github.com/osmandapp/Osmand/files/4776744/2020-06-13_10-34_Solingen.Obstweg_original.zip)

**Comment by vshcherb** [comment]
The issue is related that it needs sometime to calculate the route and only after that you should be able to save the track. Workaround: wait until calculation is finished

**Comment by scorpion-girl** [comment]
Thank you for the feedback. In fact I waited till the route was calculated to be attached to streets and paths. Only afterwards (and this was a lenghty process) I selected to save it as a new gpx file, the program confirmed it but no file was to be found.Similarly with the phone of my husband. I applied this method before and it worked. This time it failed in several attempts. And the manual recreation additionally failed to boot. To me it seems not like a problem of too early saving. Did you try my procedure based on my gpx file, which was included in the issue? Thank you in advance for your help! Kind Regards, Anett Please help me -- Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 19.06.20, 15:40 schrieb vshcherb <notifications@github.com>:

   
  The issue is related that it needs sometime to calculate the route and only after that you should be able to save the track. Workaround: wait until calculation is finished

**Comment by vshcherb** [comment]
> Your track has 1237 points, so if you snap it to the road, it takes 6 min to caclculate the distance. Probably it crashed during that calculation. The reasonble amount to use Snap functionality about 50-100. 

Anyway it should work if you don't use Snap and it should save poitns

**Comment by BG2311** [comment]
> The issue is related that it needs sometime to calculate the route and only after that you should be able to save the track. Workaround: wait until calculation is finished

Hi, this is interesting, I've tried to replicate my route (25 points, 20km) and then save: "saves as new GPX file" with "save as route points" -> the usual message says that it's saved in the storage, but this time I've waited more (I usually go back to the main menù almost immediately after the message), and then there was another message with saved in the storage: now I see it listed in "Tracks" under "My Places" as usual.
I don't know why there is this "double saving", it was different months ago.

Thanks for the hint, regards
Claudio
