### ISSUE TITLE
Hiking symbols are rendered when cycle routes are enabled AND hiking symbol layer is disabled

### ISSUE THREAD

**Issue by ligfietser** [osmandapp/Osmand#9240]
If I enable **cycle routes** and I **disable hiking symbol layer**, I still see the hiking route symbols rendered on the maps. This applies for all map layers, offline and online.  Also mentioned in this issue: https://github.com/osmandapp/Osmand/issues/9065#issuecomment-643804125 it matters on which location you are browsing the map. In Hungary this issue is not observed, in the Netherlands this is rendered. Screenshot:
![84600517-fbfa9280-ae79-11ea-9d44-e8f260e8ed46](https://user-images.githubusercontent.com/9638726/84602227-1fc3d580-ae86-11ea-90ac-c737b67fde18.jpg)

I'm using Osmand v 3.7.4, with Android 10. I also observed it in v3.7.3, not in 3.6.x

**Comment by vshcherb** [comment]
Is it new maps? I think there was an issue in May maps, actually 3.6 won't work correctly with these maps as well

**Comment by ligfietser** [comment]
@vshcherb I'm using The Netherlands June 2020, but I also see it on the mapnik online layer.

**Comment by Aiurek** [comment]
duplicate #9011

**Comment by xmd5a2** [comment]
![Screenshot from 2020-06-15 12-41-30](https://user-images.githubusercontent.com/5829014/84642771-99e76f00-af05-11ea-9694-867c0ec02a17.png)
Issue was fixed but maps must be regenerated
