### ISSUE TITLE
avoid unpaved road setting issue

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#9254]
When calculating a route with car profile and Avoid unpaved roads setting enabled, OsmAnd builds a straight line:
Starting point: 51.81229N 18.28363E
Ending point: 51.81371N 18.27545E

![image](https://user-images.githubusercontent.com/50198677/84777472-50bd1b00-afea-11ea-8037-c5c46ea59b55.png)

**Comment by vshcherb** [comment]
There is no other option as I see
