### ISSUE TITLE
Support PT routing without ways in the route relation

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#9264]
Many (e.g. bus ) PT route relations are mapped without 'Ways' members (still recommended in PTv2), mostly because mapping them is tedious, and because while stops can be extracted by mappers from time tables, knowing the actual ways taken by a route requires local knowledge.

In light of 'Proposed features/Refined Public Transport', see https://wiki.openstreetmap.org/wiki/Proposed_features/Refined_Public_Transport, we can expect that occurrences of PT routes without Ways may even increase. Ways members are there proposed only as optional, and it is (correctly) stated that the presence of the sorted stop nodes alone (roles stop/platform, or even empty) suffices to perform a correct PT routing.

I wonder if in the absence of ways members we can have OsmAnd calculate the PT route using the node members of the PT route relation only (probably by simply assuming straight lines between subsequent nodes of the route if our algorithm relies on having connected ways).

I have tried PT routing with OsmAnd today along bus routes containing nodea only, and that seems to fail: OsmAnd pretty much makes we **walk** along such routes.

**Comment by vshcherb** [comment]
This is called PTv3 scheme and OsmAnd supports them. So it doesn't draw correct line but it draws direct line between stops anyway and uses them correctly in routing .

To support line refinement probably another issue could be used though we don't plan to support it yet until it becomes popular enough :-)

**Comment by sonora** [comment]
@vshcherb  Ah,  you're right: It works just fine for the test route 165 mentioned in #9226. I guess the other maps I had tested this with were just too old.
