### ISSUE TITLE
Slope classes

### ISSUE THREAD

**Issue by vascotenner** [osmandapp/OsmAnd#9283]
Recently, a slope layer has been added to osmand. This layer shows the slope angle in degrees via a nonlinear color scale.

I think it is a nice feature of osmand. The past years I have been compiling my own overlay datasets with slopes from freely available elevation data sources via qgis ans mobac. Osmand has the potential to make this extra work not needed anymore. However, for my usecase I need a slighty different visual representation.

My usecase is as follows. I use these slope maps to estimate the avalanche danger when doing off-track skiing. In the most common used risk estimation framework (based on prm designed by Werner Muenter) three slope classes are distinct:
1. [30, 35)
2. [35, 40)
4. [40, 90)

For this reason many web based maps have a winter map showing these slopes, like the [swiss maps](https://map.geo.admin.ch/mobile.html?lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,ch.swisstopo.hangneigung-ueber_30&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&E=2786066.10&N=1176561.77&zoom=5.775955729690452&catalogNodes=457,532,508&layers_opacity=1,1,1,1,0.4) , the french IGN maps, the outdooractive and bergfex maps. They all use the same colorscale for these maps.

Could osmand+ include this overlay?

**Comment by vshcherb** [comment]
Unfortunately these are raster layers which means it should be a different data set, also we've used a gradient-like style, so it might be not what expected.

**Comment by dustinlagoy** [comment]
I agree with vascotenner, this could be very useful for backcountry skiing with a more appropriate color scale. Is there some other use for the slope layer that benefits from the current color scaling? Could this be changed to a grayscale raster and have coloring applied in-app for different rendering styles (this could allow for smaller map files too)?

Also, @vascotenner are you making overlay layers that you can use in osmand? I'm familiar with qgis but not how I could use such a layer in osmand.

**Comment by cycore** [comment]
+1 for the avalanche danger use case.

right now, it is very difficult to see where the slope is steeper than 30 degrees. the map is cluttered or overly colorful in areas where the slope is below 30°. it is hard to estimate avalange danger from that.

i would like to propose a different and maybe simpler aproach instead of using distinct slope classes: only show the color gradient for slopes greater than 30° (or configurable value).
@vshcherb: Do you mean the slope layer is not configurable at all, because it is a raster layer and therefore "pre-baked"?

@dustinlagoy check out https://www.openslopemap.org/karte/ . there you can download rasterized slope maps for most of the alps and use them as a overlay in osmand.

**Comment by vascotenner** [comment]
> I agree with vascotenner, this could be very useful for backcountry skiing with a more appropriate color scale. Is there some other use for the slope layer that benefits from the current color scaling? Could this be changed to a grayscale raster and have coloring applied in-app for different rendering styles (this could allow for smaller map files too)?
> 
> Also, @vascotenner are you making overlay layers that you can use in osmand? I'm familiar with qgis but not how I could use such a layer in osmand.

I have downloaded altitude data for europe, and parse that using DEM models to retrieve slopes. This slope layer can be exported to tiles (I used qtiles before) and then I use mobac to create a selection of these tiles to a osmand sqlite database.

The link of @cycore looks much easier.

**Comment by vascotenner** [comment]
Use case is described in: https://github.com/osmandapp/OsmAnd/issues/6636 . Lets close this issue

**Comment by vshcherb** [comment]
Progress made https://github.com/osmandapp/OsmAnd/issues/6636
