### ISSUE TITLE
screen control, how to setup "display remain darc" 3.7.4

### ISSUE THREAD

**Issue by quax2712** [osmandapp/Osmand#9292]
New "screen control" I can not find a possibbility to leave screen off.
When cicyling I only use voice navigation to save battery.
This option was possible in early version.
greetings
Rainer

**Comment by sonora** [comment]
How about by simply not enabling any of the options to  Turn screen on'. Then turn off the screen manually?

**Comment by quax2712** [comment]
If I disable all, the screen will be activated with first command and stay on.
There is no possibility to avoid activating screen.
You can test it in "simulation mode".

**Comment by quax2712** [comment]
I found the switch!
I interpreted "Navigation instructions" not to hear voice instructions.
thank you
