### ISSUE TITLE
[Feature request] add length to the Vehicle parameters

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#9294]
the Length is unfortunately not included into the Vehicle parameters, so you can go with Car with Caravan, Camper with trailer, or Truck with a trailer can still drive through eg Liège and get a ticket. 
A Weight and Length prohibition stands for driving may be set for some roads.

**Comment by dmpr0** [comment]
Icon: ic_action_length_limit
Image for dialog: img_help_length_limit_day/night
Predefined parameters: 5 m, 6 m, 6.5 m, 7 m, 8 m, 9 m, 9.5 m, 10 m, 11 m, 12 m
