### ISSUE TITLE
Public transport navigation not functioning due to error message

### ISSUE THREAD

**Issue by JCGoran** [osmandapp/Osmand#9298]
Osmand version: `3.7.4`, downloaded from f-droid
Local maps name and version: Switzerland, 1 Jun 2020
Android version: LineageOS 13.0
Routing used: public transport, no transport types avoided, temporary limitations not considered

The navigation for public transport is for some reason broken on my device, the following message keeps appearing on screen:

```plaintext
Could not calculate route.:

While parsing a protocol message, the
input ended unexpectedly in the middle
of a field. This could mean either than
the input has been truncated or that an
embedded message misreported its own
length.
```

The bug is not specific to any pair of locations. The other navigation options (car, bike, walking) work fine.

See also the screenshot below:

![Screenshot_20200623-120653-mod](https://user-images.githubusercontent.com/25671271/85392714-3c2dd500-b54c-11ea-87ff-b86cbf359ee0.png)

**Comment by MadWasp79** [comment]
Is it happens on any map or just in Geneva?

**Comment by MadWasp79** [comment]
@JCGoran issue is fixed in OsmAnd nightly version
