### ISSUE TITLE
Show localized names in POI info panel

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#9300]
It is already possible to configure the language of labels. However it would be really nice to display additional names of POIs in their info panel.

Example:
![photo_2020-06-23_13-57-41](https://user-images.githubusercontent.com/1040784/85401707-c11feb00-b55a-11ea-9c2d-227f82ba68ba.jpg)

The above picture has an additional row for showing the POI name in the currently configured language (in this case English). Optionally there could be a drop down button on the right to view the POI name in _all_ available languages (useful for multilingual users).

**Comment by Erlendur22** [comment]
I just came across this post and I have the same feature request. 
But first I would like to understand, how this actually works in Osmand. 
I checked aforementioned example and I have a different result. My map language is set to "local names", therefore this POI is named like in the Screenshot above. But in the details panel it does not show the English name, it shows the Alternative name "Lázně I.". Strange.
Checking out the name of the city where this POI is located ("Karlovy Vary"), the details panel shows the Alternative name "Carlsbad" and the International name "Karlovy Vary".

Those two examples make me wonder, what the criteria, the algorithm in Osmand is, when what names are shown. 

Another example. I cycled through Hungary recently and found a camp site on the map. But it was all in Hungarian and I was offline, so I couldn't check the name or translate it.
When I arrived there, I didn't check it out, it was in the forest. But once with Internet again I found out, the name translated meant "Youth camp".
Would the English name have been visible at least in the details panel, I would have known what it was. 
I changed it in OSM and it actually shows now as "Youth camp" in OSM. At least on my PC. On my phone it's still in Hungarian but in the details panel it shows the English name. That's all I need.
BUT in Osmand not. It still stays written in Hungarian, no English name in the details panel as well as it does not change to the English name when I change the map language.

So what is going on here? The suggested feature of having a name of a POI shown in different languages, best in a drop-down menu, would be the best.
Is this possible? 

![Youth camp in OSM](https://user-images.githubusercontent.com/104724692/194758687-869f83ac-dcc4-40ac-9a83-2d8adf4764e3.jpg)
![Youth Camp in Osmand](https://user-images.githubusercontent.com/104724692/194758718-e7103a83-bf96-4d91-a113-a6c9cf22f584.jpg)

**Comment by dmpr0** [comment]
## ToDo
- [ ]  Use **Display language** as default > if it **unavailable** > try to use languages from system list of [preferred languages](https://developer.android.com/reference/android/content/res/Configuration#getLocales()) (in order of presence) (we show similar for Wikipedia languages).
- - [ ] If **Display language** = English and POI has it variant, show it
- - [ ] If **Display language** = English and POI don't have it, show Name on first language from Preferred languages
- - [ ] If **Display language** = English and POI don't have it, and languages from Preferred languages is not available too, show list of languages in order of presence.
- [ ]  Copy name to clipboard on long tap

<table style="width:100%">
  <tr>
    <th>Closed state</th>
    <th>Open state</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/211028381-0a736215-c736-4b49-83b6-b572cc752c7c.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/211028376-4abf72f5-fd0b-47af-86ee-8b5f641c370c.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14108mqta, released: 2023-01-17
Done


https://user-images.githubusercontent.com/104760013/212950738-c6ccc3dc-80dd-4095-b185-5df062ef47b2.mp4

**Comment by EugeneZmeuk** [comment]
https://osmand.net/docs/user/map/map-context-menu#details
