### ISSUE TITLE
Crash on change of profile from globe to pedestrisn direct after start

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#9306]
Device : herolte
Brand : samsung
Model : SM-G930F
Product : heroltexx
Build : R16NW.G930FXXS3ERLF
Version : 8.0.0
App Version : OsmAnd~
Apk Version : 3.7.0#30051m 370

[exception_log.zip](https://github.com/osmandapp/Osmand/files/4823937/exception_log.zip)

**Comment by nazar-kutz** [comment]
Probably fixed with https://github.com/osmandapp/Osmand/commit/9c100a0552e1399ec19f7cf49a77e58b5ff82f5a
