### ISSUE TITLE
Wrong arrow width on route action drawing

### ISSUE THREAD

**Issue by ehermann** [osmandapp/Osmand#9307]
Hello,
When choosing a large width route style (for better outdoor visibility for instance) the arrow tip is of the wrong size.
Example using strokeWidth="20"

![image](https://user-images.githubusercontent.com/467129/85527566-4662d880-b60b-11ea-9ea9-10956551c9fd.png)
Expected result:
![image](https://user-images.githubusercontent.com/467129/85528273-f9333680-b60b-11ea-8de7-7118aaf31d74.png)
P.S. I already have the correction for this, I'll make a pull request asap.

**Comment by vshcherb** [comment]
Looking forward with PR
