### ISSUE TITLE
Logging GPX in background (Android 8.0.0)

### ISSUE THREAD

**Issue by JPDeLaToya** [osmandapp/Osmand#9314]

**Comment by JPDeLaToya** [comment]
Wondering if there could be an easy fix to gpx logging such that it can work in the background. Currently, logging stops when I exit app and resumes when I re-enter (e.g. check messages or browse web). Could gpx logging be enabled passively?

**Comment by vshcherb** [comment]
This should work by default. Please check how to setup Samsung device to keep app running - https://osmand.net/help-online/faq.
