### ISSUE TITLE
Travel fix colors

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#9323]
We have a few issues with text and icon colors.
**Article screen:** overflow menu icon color: icon_color_default_
**Show images dialog:** text color: text_color_secondary_
**Search:** icon colors: icon_color_default_

![Group 1](https://user-images.githubusercontent.com/9365308/85754462-be1d2a00-b715-11ea-850a-6ccf5514b654.png)

**Comment by vshcherb** [comment]
@angry010101
