### ISSUE TITLE
Quick action button has negative Y size

### ISSUE THREAD

**Issue by Bushmills** [osmandapp/Osmand#9325]
After considerable changes to the Car profile, then using car profile as template for a new motorbike profile, I noticed that the quick action button wouldn't show when enabling in motorbike profile. Neither does it show in car profile.  But it does show in pedestrian profile.
As I thought that a change to an option was responsable for disabling quick actions, I went through many options, changing them to previous values, in the hope that I might catch the one which prevents the quick action button from showing, but to no avail.
I then used a script which looped until the element with the id of the quick actions button showed, then printed position and size of that element (net.osmand.plus:id/map_quick_actions_button).
With both pedestrian and motorbike profiles was that element found. But while with pedestrian profile did screen coordinates and size have plausible values, in motorbike profile is the size in y dimension negative. Presumably, this negative size prevents the button from showing.
I don't know how to change y size of that button to a plausible value, so the button shows.

Shown numbers in screenshots are  x, y coordinates, then x, y size of quick action button.

![Screenshot_20200625-234047_Automagic_Premium](https://user-images.githubusercontent.com/1392204/85799942-62b46180-b740-11ea-8c6f-e6773eaed27d.png)
![Screenshot_20200625-234015_Automagic_Premium](https://user-images.githubusercontent.com/1392204/85799953-66e07f00-b740-11ea-9845-a19f2791b6cc.png)

**Comment by Bushmills** [comment]
I've now rebuilt the motorbike profile with the pedestrian profile as template, where the quick action button still shows correctly. After changing the settings, the result is exactly as before: negative Y size.

**Comment by vshcherb** [comment]
Looks like we need to validate Quick action position to be always inside BBOX

**Comment by bege10** [comment]
> 
> 
> Looks like we need to validate Quick action position to be always inside BBOX

That would solve my problem, too: I sync the OsmAnd data with another phone that has a smaller display which leads to the same issue that the quick action button disappears. Until recently the position was in only one xml-file which I edited manually. Now it is in every profile setting what makes it very cumbersome to edit.

**Comment by Bushmills** [comment]
Thanks - problem seems solved: The quick actions button shows in all profiles now.
