### ISSUE TITLE
Splitting maps for Canada

### ISSUE THREAD

**Issue by DFyson** [osmandapp/Osmand#9326]
Many of the files (maps, contour lines, hillshades, slopes) are in the order of roughly 1GB to 10GB for the larger provinces. Some of the provinces have some of the maps split up. For example British Columbia has the contour lines split up by region, but not the slopes or hillshades.

![image](https://user-images.githubusercontent.com/12941728/85819299-3f3de680-b741-11ea-985b-20e338057c43.png)

As one can see from the population density map above, Canada is a bit of a unique case with (apparently) "90% of the population within 100 miles of the border". The vast majority of users would be fine with maps which cover only the more populated regions. For example Newfoundland and Labrador could be split into the island and mainland and maybe split the other tall vast provinces (specially Quebec, Ontario, Manitoba) into North and South regions based on population density. This would result in a fraction of the file sizes for many users.

For the Territories, they are sparsely populated except for small communities. A solution might be to generate hillshade/slope/contour maps based on a radius around human civilization (eg roads or buildings)?

This issue was discussed in #5671 but I feel like Canada could use some more work. This was also alluded to in #9165.

Where is the file defining the regions kept? I wasn't able to find it in the other repos such as OsmAnd-tools.

**Comment by vshcherb** [comment]
Yes it is part of https://github.com/osmandapp/Osmand/issues/9165 discussion. So we need to make something easily accessible and rather small for downloads. 
It is a generic issue with high latitude countries where the information gets much bigger due to projection issues.
