### ISSUE TITLE
Search order priority too low for towns

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#9329]
Searching for towns (smaller cities) can be hard sometimes since they don't always appear in the top search results.

Example for [Gera](https://www.openstreetmap.org/node/240090170), Thuringia, Germany:
![photo_2020-06-26_07-51-15](https://user-images.githubusercontent.com/1040784/85825454-91532c00-b782-11ea-9115-0ae55d95f624.jpg)

The town Gera appears only in the middle of the second page. The search results that appear before the town belong to a [razed railway](https://www.openstreetmap.org/way/470958635). Razed railways seem to have a higher search order than towns. Also [this cycleway](https://www.openstreetmap.org/way/155183669) and [this footway](https://www.openstreetmap.org/way/152455067) have a higher search order than the town.

**Comment by ehermann** [comment]
Just to put a +1 on this issue.  The town weight is a major problem of the OsmAnd search, to a point that when, in a midle of a planned trip I have to go in the direction of a city I simply switch to another app.
And it's not a "small city" problem, for instance searching for Paris:
![image](https://user-images.githubusercontent.com/467129/85944017-1fbadf80-b934-11ea-949c-666d28515efc.png)
A solution would be to give a higher weight to results that exactly matches the request.  In the case of Paris, it will prioritize all the streets from cities around Paris that are Called "Avenue of Paris"

**Comment by scaidermern** [comment]
@ehermann You have to type a space after your search term to disable partial matches. This leads to better search results.

However this "feature" is suboptimal and not obvious. I wonder if a switch for enabling partial matches would be better.

**Comment by ehermann** [comment]
Hello, thanks for the hint but adding a space  mainly removes the first
result "Parish" in the case of Paris, the remaining "avenue de Paris" are
still there as before. In my point of view what is missing is a penalty to
the results that have a match but more unmatched words than the other
results.

**Comment by MiMoHo** [comment]
I'm still having this issue as the town appears in the middle of all search results on Android v4.2.7:
![Screenshot_20221130-123224-01](https://user-images.githubusercontent.com/37556964/204840597-b3c86ace-b95e-456d-a984-bcfa73baea31.jpeg)
It's weird, though, that the town appears for a millisecond on top while the search is being initiated. Please fix (again). And also please find a way to improve the results for searches as all these road (crossings) are usually less relevant than POIs.
