### ISSUE TITLE
[Feature request] Integration of MapAnt maps from Norway and Finland

### ISSUE THREAD

**Issue by danielmmmm** [osmandapp/Osmand#9335]
The maps are available on mapant.no and mapant.fi and are meant for orienteering and hiking. They provide incredibly detailed height profiles and terrain details.

**Comment by pangoSE** [comment]
HI Daniel. Could you investigate whether the maps have a public accessible WMS server or are downloadable? 
Without that support will be impossible because they are proprietary, unfortunately.

**Comment by vshcherb** [comment]
Obviously you can try to add with custom raster maps by entering a url in the app though it doesn't look like Mercator projection.
https://mapant.no/tiles/7/418/21.png

**Comment by danielmmmm** [comment]
Why was this request closed? One "selling point" of OsmAnd is the availability of offline maps and navigation.

I contacted mapant.no and will report back as soon as I get their reply.
