### ISSUE TITLE
Transferring gpx-points to favorites as a package does not transfer point display settings.

### ISSUE THREAD

**Issue by Lans-K** [osmandapp/Osmand#9340]
When you transfer points from a gpx-track to favorites, you get, as in earlier versions of the program, base one-color stars.
The customized point style is not transferred.
Program version 3.7.4., Android 6.0.1.
![Screenshot_20200627-134540](https://user-images.githubusercontent.com/65672441/85920498-f7bc7500-b87c-11ea-8046-c6c38dc979f1.png)
![20200627_135805](https://user-images.githubusercontent.com/65672441/85920698-94334700-b87e-11ea-8c25-8a29b2e7c737.png)
![Screenshot_20200627-134614](https://user-images.githubusercontent.com/65672441/85920515-0f93f900-b87d-11ea-9ac8-cd59dd1ed4db.png)
![Screenshot_20200627-134634](https://user-images.githubusercontent.com/65672441/85920523-1b7fbb00-b87d-11ea-8bb1-3845a16857e6.png)

**Comment by dmpr0** [comment]
Review:
After selecting points for copying into Favorites, a dialog appears that asks for the group name (dialog propose track name), any edits of the name don't affect for a future group. Copied points will be placed into groups that they have on the track.
