### ISSUE TITLE
Adding gpx-points to markers does not allow them to turn off later.

### ISSUE THREAD

**Issue by Lans-K** [osmandapp/OsmAnd#9341]
When adding gpx-points to markers, they are displayed as markers in earlier versions program and “stick” as turned on.
They cannot be turned off.
![Screenshot_20200627-140524](https://user-images.githubusercontent.com/65672441/85921139-97c8cd00-b882-11ea-912c-9f56d401aed5.png)
![Screenshot_20200627-140610](https://user-images.githubusercontent.com/65672441/85921147-a1523500-b882-11ea-872f-bf8d2964345d.png)
![Screenshot_20200627-140704](https://user-images.githubusercontent.com/65672441/85921151-ab743380-b882-11ea-99d6-d1d27136d0ae.png)
![Screenshot_20200627-145647](https://user-images.githubusercontent.com/65672441/85921705-c3e64d00-b886-11ea-8363-ab95fa245b75.png)
All methods of turning them off as markers lead to their repeated spontaneous inclusion when accessing the track from which they are taken.
Program version 3.7.4., Android 6.0.1.

**Comment by vshcherb** [comment]
+ The icon looks completely wrong

**Comment by vshcherb** [comment]
Markers could be deleted from Markers screen, we can't reproduce it so far

**Comment by dmpr0** [comment]
Passed makers have a different color on low zoom levels and if zoom in closer, #727272 should be used for passed markers on all zoom levels.
