### ISSUE TITLE
Wrong destination time in "Fuel-efficient way" mode

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/Osmand#9345]
The arrival time is almost two times different for "Fuel-efficient way". It is not real. The road almost the same, arrival time should really differ by 10-15 minutes.
![image](https://user-images.githubusercontent.com/44466116/86013667-114df000-ba28-11ea-85af-55c4f90c41ed.png)
![image](https://user-images.githubusercontent.com/44466116/86013689-1612a400-ba28-11ea-93cf-516ff7838d0e.png)

**Comment by Jorgeno** [comment]
Great that this strange behaviour is taken care of. In some cases the optimized route is identical, both with and without fuel efficiency enabled. One would assume identical traveling times/ETAs in those cases, but the difference is often huge...
