### ISSUE TITLE
Add support for boundary=aboriginal_lands

### ISSUE THREAD

**Issue by BikeRoad** [osmandapp/OsmAnd#9348]
This tag has the status of approved. This tag is equivalent to tag "boundary=protected_area ; protect_class=24"

Info:
https://wiki.openstreetmap.org/wiki/Proposed_features/Tag:boundary%3Daboriginal_lands

Here some examples:

https://www.openstreetmap.org/relation/11032100 (Peru)
https://www.openstreetmap.org/relation/3817157 (Brazil)

Thank you.

**Comment by BikeRoad** [comment]
Hello. I add more Aboriginal Land type relationships to highlight that it is widely used in OSM and it would be nice if it was already implemented in OSMAND. Thanks.

Reserva Indígena Yavarí Tapiche
https://www.openstreetmap.org/relation/12754608
Reserva indígena Kakataibo Norte y Sur
https://www.openstreetmap.org/relation/13080688

EE.UU
Agua Caliente Indian Reservation
https://www.openstreetmap.org/relation/7414790#map=12/33.8160/-116.4846
Allegany Reservation
https://www.openstreetmap.org/relation/9874846#map=12/42.1026/-78.7785
Annette Island Reserve
https://www.openstreetmap.org/relation/11269210
Bad River Reservation
https://www.openstreetmap.org/relation/8370913
Bois Forte Reservation
https://www.openstreetmap.org/relation/11589305
Coeur d'Alene Reservation
https://www.openstreetmap.org/relation/10078026
Fort Peck Indian Reservation
https://www.openstreetmap.org/relation/11593701

BRAZIL

Terra Indígena Kanamari do Rio Juruá
https://www.openstreetmap.org/relation/4286689
Terra Indígena Vale do Javari
https://www.openstreetmap.org/relation/3816970
Terra Indígena Tenharim Marmelos (Gleba B)
https://www.openstreetmap.org/relation/4287012

BOLIVIA

Territorio Indígena Originario Campesino Takana-Cavineño
https://www.openstreetmap.org/relation/13252271
Tierras comunitarias de origen Chácobo-Pacahuara
https://www.openstreetmap.org/relation/13251694
Tierras comunitarias de origen Cavineño
https://www.openstreetmap.org/relation/13253080

**Comment by BikeRoad** [comment]
I have been testing version 4.3.0 of osmand and the areas labeled as aboriginal_lands are not displayed correctly.

I have created test relationships.
The A/C figures were created with the tag type=multipolygon and the name is displayed
Figure B was created with the type=boundary tag and the name is not displayed.
![Screenshot_2022-11-12-08-24-11-415](https://user-images.githubusercontent.com/19896035/201477010-b3495695-9d4e-4d52-b590-ac8ae89a8548.jpg)

In both cases, none of these aboriginal_lands relationships can be displayed in the search menu as the labels with protected_area relationships do.
![Screenshot_2022-11-12-08-43-01-336_net osmand](https://user-images.githubusercontent.com/19896035/201477065-4ef3307d-81b4-448b-b9b9-cb999328dd6a.jpg)

Regarding the design of the lines of the area:
In figure A the inner line of the area is darker than the outer line of the area, is that correct?
The same thing happened with the areas labeled with protected_area.

Please give support for aboriginal_lands in Topo and Off road map styles, both don't show at all
![Screenshot_2022-11-12-08-53-57-801_net osmand](https://user-images.githubusercontent.com/19896035/201477398-440421ff-250b-4e3d-9a85-ecc49662b4a8.jpg)

**Comment by vshcherb** [comment]
Issue in previous release, so it's better to open new issues with reference to it.
