### ISSUE TITLE
Country maps not available for some countries ?

### ISSUE THREAD

**Issue by Lestat-GitHub** [osmandapp/Osmand#9363]
Hi,

I'm using OSMAnd 3.7.4 and seems like I'm not able to download "full country" maps for some countries.
As an example I cannot download "roads only" for France (Germany has the same behaviour), I have to select
each region and download the region specific map.

Is that a bug or something new on the way to manage maps ?
Thanks.

**Comment by vshcherb** [comment]
This is duplicate issue to offer button to download maps for whole region. Some maps are too big to be in 1 file
