### ISSUE TITLE
6 lanes are shown while there are only 3

### ISSUE THREAD

**Issue by 532910** [osmandapp/Osmand#9365]
https://www.openstreetmap.org/directions?engine=graphhopper_car&route=60.01395%2C30.43361%3B60.01803%2C30.43275
![image](https://user-images.githubusercontent.com/14617699/86295897-42811880-bc00-11ea-98fd-9cfd094903da.png)

**Comment by vshcherb** [comment]
In order to draw correctly, you need to use "turn:lanes" something like "C,TL;C,TL;C,TL". https://www.openstreetmap.org/way/31371500 on this road 3 lanes are split into 3 + 3 lanes, the algorithm counts target lanes as there are 6 lanes.

**Comment by 532910** [comment]
There no directions signs mapped on the road. So I believe algorithm should use default `L,T|T|T` as left turn is allowed only from the leftmost lane by default.

**Comment by 532910** [comment]
> "C,TL;C,TL;C,TL"

What `C` and `TL` stand for?

**Comment by vshcherb** [comment]
turn:lanes=none|none|through;slight_right
https://wiki.openstreetmap.org/wiki/Key:turn#Turning_indications_per_lane

**Comment by vshcherb** [comment]
No signs doesn't mean the tag couldn't be assigned if these are allowed movements

**Comment by 532910** [comment]
Yep, I know about `turn:lanes`, but it's still not clear how `C,TL;C,TL;C,TL` is `none|none|through;slight_right`.

Yep, the tag could be assigned, but I still believe this shouldn't affect the algorithm.
