### ISSUE TITLE
Improvement to hiking routes

### ISSUE THREAD

**Issue by Mashin6** [osmandapp/OsmAnd#9366]
I just got the Live subscription. Very nice maps, but there are few things that are not working in my area.

1. **Route symbols are not rendered if no background is specified**
Routes in my are are marked with simple shapes or stripes, which are represented in osmc:symbol as e.g. `blue::blue_stripe or red::red_triangle`
https://www.openstreetmap.org/relation/2959608
https://www.openstreetmap.org/relation/239810

2. **Support more colors**
Particularly: pink (currently rendered same as red); teal (currently blue)
https://www.openstreetmap.org/relation/11158470
https://www.openstreetmap.org/relation/11155404

3. **Support for second foreground in symbol**
Many side trails are marked as vertical stripe with small rectangle of different color on the bottom. Currently they are marked as e.g. `blue_yellow::blue_stripe:yellow_rectangle_lower`.  
https://www.openstreetmap.org/relation/11222888
This requires support for `*_rectangle_lower` and two foregrounds in osmc:symbol
Some examples are here: https://wiki.openstreetmap.org/wiki/United_States/Long_distance_trails#Symbol_tags

4. **Display two color ways as line with alternating color pattern**
For the above point (3.) cases it would also help if the route lines carried both colors as alternating dashes.

![image](https://user-images.githubusercontent.com/5265707/86317249-f1bbf080-bbfc-11ea-8033-263e76bc0827.png)
![image](https://user-images.githubusercontent.com/5265707/86317321-25971600-bbfd-11ea-98ff-208969c1bce3.png)

**Comment by matthijskooijman** [comment]
Another example of problem 1 is the `osmc:symbol=yellow::yellow_diamond` used in the [Swiss hiking network](https://wiki.openstreetmap.org/wiki/DE:Switzerland/HikingNetwork), which is typically also painted without background on trees etc: https://www.thurgauer-wanderwege.ch/de/wanderwege/signalisation

**Comment by zipav** [comment]
OsmAnd Nightly 4.6.0#1115m, released: 2023-11-30

|https://www.openstreetmap.org/relation/2959608|https://www.openstreetmap.org/relation/239810|
|-----|------|
|![image](https://github.com/osmandapp/OsmAnd/assets/123936521/bb25c86e-ce36-4c1f-a62b-e6aa1223ba01)|![image](https://github.com/osmandapp/OsmAnd/assets/123936521/1866dcf7-851c-41e3-b652-f3d7600658d9)|


|https://www.openstreetmap.org/relation/11158470|https://www.openstreetmap.org/relation/11155404|https://www.openstreetmap.org/relation/11222888|
|-----|------|-----|
|![image](https://github.com/osmandapp/OsmAnd/assets/123936521/19fe2ac1-d1a6-49b1-9b95-abfcedff9669)|![image](https://github.com/osmandapp/OsmAnd/assets/123936521/c80b2a47-9947-4abc-8609-9b16f04d0813)|![image](https://github.com/osmandapp/OsmAnd/assets/123936521/4006de2f-33af-46bf-9a8c-ea8316e3b8e6)|

**Comment by dmpr0** [comment]
# Review 
1. Route symbols are not rendered if no background is specified. `blue::blue_stripe or red::red_triangle`
https://www.openstreetmap.org/relation/2959608
https://www.openstreetmap.org/relation/239810
`41.4280/-72.8896`

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>iOS</th>
        <th>Android</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/158d91c6-d099-48fd-a220-e3d9c4dec8df"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/2e1c8f67-38ad-4545-8ecf-db7e6f8c151d"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>

**Comment by vshcherb** [comment]
The most popular symbol from request is *_rectangle_lower (https://taginfo.openstreetmap.org/tags/osmc%3Asymbol=blue_white%3A%3Ablue_stripe%3Awhite_rectangle_lower#overview) but it's still not very popular. We need to check whether it's realted to "yellow_lower" (https://taginfo.openstreetmap.org/tags/osmc%3Asymbol=yellow%3Awhite%3Ayellow_lower%3A%3A#overview) than numbers are quite high.

**Comment by xmd5a2** [comment]
@vshcherb all this is already supported

**Comment by xmd5a2** [comment]
Maps are not updated yet because of server loading but in synthetic test colors **pink** and **teal** is working for osmc icons and waycolor.
![Screenshot_2024-01-04_12-50-11](https://github.com/osmandapp/OsmAnd/assets/5829014/facfda49-de00-41a5-be2f-7d6b5cad4071)
```
osmc:symbol=pink::pink_stripe
```
```
osmc:symbol=teal::teal_stripe
```

**Comment by xmd5a2** [comment]
- [ ] Route symbols are not rendered if no background is specified
- [ ] Support more colors
- [ ] Support for second foreground in symbol
- [ ] Display two color ways as line with alternating color pattern

"Support for second foreground in symbol" : looks like **icon_2** is unsupported [here](https://github.com/osmandapp/OsmAnd-resources/blob/master/rendering_styles/routes.addon.render.xml#L596). **rectangle_lower** icons were added recently.
"Display two color ways as line with alternating color pattern" : not possible in rendering engine/style. Development needed.

**Comment by Wonderer0** [comment]
> "Display two color ways as line with alternating color pattern" : not possible in rendering engine/style. Development needed.

Isn't it possible using a broken line in one color over a solid line in a different color, both the same width, or am I misunderstanding what is being asked for?

**Comment by xmd5a2** [comment]
There can be up to 10 routes on the same way, each with different waycolor. Besides it will be nearly impossible for renderer to align lines with different dash pattern.

**Comment by michaelblyons** [comment]
> Isn't it possible using a broken line in one color over a solid line in a different color, both the same width, or am I misunderstanding what is being asked for?

The routes are transparent, no? It might lead to some weird color mixing.

**Comment by Wonderer0** [comment]
> There can be up to 10 routes on the same way, each with different waycolor.

10 semi-transparent routes on top of each other in different way-colors is going to give a confusing color even with a single color for each route.  It will depend upon how the compositing works, but will probably blend them all into a shade of grey.

> Besides it will be nearly impossible for renderer to align lines with different dash pattern.

Sorry, I should have been clearer - using something like `color_1`, `strokeWidth_1`, `color_2`, `strokeWidth_2` for each route, which I think are always aligned.

> The routes are transparent, no? It might lead to some weird color mixing.

Good point.  My solution would make the color mixing problem even worse, giving up to 20 layers over the path being followed!

For a single route rendering it in opaque colors under the path might work, but then routes rendered over others would hide the ones underneath. Rather than trying to render multiple routes over each other perhaps, if there is more than one, the user could be allowed to choose which one is displayed by clicking on the path and choosing from a menu.

**Comment by michaelblyons** [comment]
> if there is more than one, the user could be allowed to choose which one is displayed by clicking on the path and choosing from a menu.

That'd work for me if the OSMC badges were all visible (since badges can line up next to each other). Curious what others think.
