### ISSUE TITLE
GPX navigation settings missing

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#9367]
In the latest 3.7.4 OsmAnd version, after selecting the GPX file for the navigation, there are no related settings available. In the previous versions, in Directions  - Options, there were available such settings:
Reverse GPX direction, 
Pass along entire track, 
Calculate OsmAnd route for first and last route segment.
The issue is not reoccured in the Nightly
![image](https://user-images.githubusercontent.com/50198677/86321933-a2001800-bc42-11ea-8b9e-bc1b1a7c55be.png)
![image](https://user-images.githubusercontent.com/50198677/86321945-a5939f00-bc42-11ea-9e97-3b421fdbb462.png)

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/Osmand/issues/9388
