### ISSUE TITLE
[Feature request] improve Korean font on the online tiles

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#9371]
While on the offline vector maps, there is easy-to-read Korean font, the online tiles display a different font that is difficult to distinguish. It would be useful to have an option to see the same text data in another font.
![image](https://user-images.githubusercontent.com/50198677/86356228-8ca3e180-bc74-11ea-826f-050351d27f76.png)
![image](https://user-images.githubusercontent.com/50198677/86356243-90cfff00-bc74-11ea-81a4-1a614e911e8b.png)

**Comment by vshcherb** [comment]
We need to add missing fonts on the server

**Comment by xmd5a2** [comment]
All required fonts are installed
NotoSansCJK-Bold.ttc
NotoSansCJK-Regular.ttc
NotoSerifCJK-Bold.ttc
NotoSerifCJK-Regular.ttc

Issue is described here: https://github.com/gravitystorm/openstreetmap-carto/issues/2208
