### ISSUE TITLE
Bug: Update of color of category does not update the color of the place

### ISSUE THREAD

**Issue by Barkole** [osmandapp/Osmand#9375]
What version of OsmAnd are you using, on what device and Android/iOS version?
Android OsmAnd+ 3.7.4

The new version introduces the bug, that the color of the place is not updated, if the color of the category is changing.

Also if I move the place to another category, the color of place is no longer updated to the color of the category

In a previous version of OsmAnd+ that was working fine.

**Comment by vshcherb** [comment]
This is part of transitioning from Category color to individual colors, we hope to be fixed soon to make it clear.
1) So first part will be fixed. Changing color of category will suggest to change all colors of the waypoints
2) Moving favorite won't change color any more.

**Comment by Spielmops** [comment]
A new item should get the color of the category automatically, like it has been with the previous versions.

Spielmops

**Comment by vshcherb** [comment]
Yes, there is a separate issue for that https://github.com/osmandapp/Osmand/issues/9060
