### ISSUE TITLE
Bug: Categories not enabled to be displayed are not selectable

### ISSUE THREAD

**Issue by Barkole** [osmandapp/Osmand#9376]
What version of OsmAnd are you using, on what device and Android/iOS version?
Android OsmAnd+ 3.7.4

With the new version a bug was introduced, so I can't move a place to a category, which is not enabled to be displayed on the map.

In a previous version of OsmAnd+ that was working fine.

**Comment by pebogufi** [comment]
See also #9319

**Comment by vshcherb** [comment]
Duplciate #9319
