### ISSUE TITLE
POI along the route are not shown

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/Osmand#9377]
Not work the feature (**show POI along the route**)
https://osmand.net/features/navigation#How_to_view_POI_along_the_road
Not appear top screen notifications.

**Comment by vshcherb** [comment]
A) Doesn't function top bar doesn't display POI information (instead of street name) on top
B) As I remember, Show along the route should show only POI on the map which are close to the route and not all possible

**Comment by vshcherb** [comment]
B) * Probably it should show them differently i.e. small circle instead of big ones

**Comment by dmpr0** [comment]
Blue arrow shows up below POI name
![photo_2020-07-21 13 04 19](https://user-images.githubusercontent.com/9365308/88041194-b7d27000-cb52-11ea-9462-999a0f042a40.jpeg)

**Comment by Chumva** [comment]
Blue arrow should be fixed here https://github.com/osmandapp/Osmand/pull/9556
