### ISSUE TITLE
Wikipedia articles missing numbers and other stuff

### ISSUE THREAD

**Issue by mahdi1234** [osmandapp/OsmAnd#9384]
OsmAnd~ 3.7.4 with wikipedia updated as of Jun 28, 2020

https://en.wikipedia.org/wiki/Bystr%C3%A9_%28Svitavy_District%29

Most of the part in brackets missing

> Bystré (Czech pronunciation: [ˈbɪstrɛː]; German: Bistrau) is a town in the Czech Republic

![osmand_en](https://user-images.githubusercontent.com/1097047/86496173-a7a54d00-bd6b-11ea-8965-439ccdd43bbc.png)

https://cs.wikipedia.org/wiki/Bystr%C3%A9_(okres_Svitavy)

"1500" missing

> Žije zde přibližně 1 500[1] obyvatel.

![osmand_cz](https://user-images.githubusercontent.com/1097047/86496209-ce638380-bd6b-11ea-99d8-ea2cc9971028.png)

https://fr.wikipedia.org/wiki/Bystr%C3%A9_(district_de_Svitavy)

"1 569" missing

> Sa population s'élevait à 1 569 habitants en 2017

![osmand_fr](https://user-images.githubusercontent.com/1097047/86496233-e6d39e00-bd6b-11ea-81f7-958a6a151f22.png)

**Comment by njohnston** [comment]
Related to #8621 and #6407.

**Comment by vshcherb** [comment]
Some macrosses are not supported:
by looking at raw wikipedia https://fr.wikipedia.org/wiki/Bystr%C3%A9_(district_de_Svitavy)?action=raw. I found following macros
```
{{Počet obyvatel}}
{{Formatnum:1515}}
{{IPA-cs|ˈbɪstrɛː}}
```
I think we have no other choice then handle them one by one and probably in different issues. We are not going to be 100% complete though we would like to display all important numbers so text looks naturally

**Comment by vshcherb** [comment]
Issue: https://en.wikivoyage.org/wiki/Frankfurt?action=raw we have issues likely starting from 
```
<!--U-Bahn-->{{Mapshapes|Q3040919}}
```

**Comment by njohnston** [comment]
> I think we have no other choice then handle them one by one and probably in different issues. We are not going to be 100% complete though we would like to display all important numbers so text looks naturally

@vshcherb: there [so many of these](https://en.wikipedia.org/wiki/Special:AllPages?from=&to=&namespace=10) (they're actually called templates, I discovered) that it will be almost impossible to add support for all them. Some are even implemented in Lua. Would it better to use [Parsoid](https://www.mediawiki.org/wiki/Parsoid) (the parser and converter which Mediawiki uses) instead?

Alternatively, Kiwix uses [MWoffliner](https://github.com/openzim/mwoffliner) to scrape Wikipedia etc. This uses Parsoid internally too.

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd-tools/pull/375

**Comment by vshcherb** [comment]
We probably need to follow @njohnston suggestion and use something like a scrapper, though it's better to have as a separate task.

Right now we process all information offline by using a wikipedia dump. So online tools actually not bad but they will be significantly slower.
