### ISSUE TITLE
Screen control doesn't seem to work

### ISSUE THREAD

**Issue by IsecacIt** [osmandapp/Osmand#9386]
Or maybe I'm not using it correctly, settings are too complicated.
For instance, is there a difference between "screen timeout" and "wake time" ? There already is an issue about it #9110 and I'm not sure I understand the answer (I guessed "wake time" is only considered when the screen turns off after it automatically woke up ? But then, what about the start of the ride ?)

Anyway, this morning I went for a ride. What I wanted :
- screen turns off after x seconds
- screen wakes up (bypassing lock screen) when there is an intersection, or when I press the power button

I set a "wake time", but could not turn on "power button". I found out on an issue that it's not possible when you have set "wake time".
So instead I turned on "screen timeout", thinking that the screen would turn off after 30s (system setting).
But it didn't, the screen would stay on. I turned it off manually by pressing the power button, but then it would never wake up, nor give me instructions... So I pressed the power button again and the lock screen showed.

As you can see I don't get how it works, but I'm confident there is something wrong. I'm planning a day-long trip and I can't keep the screen on (battery dies after ~3h on my Pixel 3).

Thanks

**Comment by vshcherb** [comment]
Not all options are supported on Android devices, some options might not be accessible at all. 

1. So if you want to have screen on indefinite time, you shouldn't enable Screen Timeout at all.
2. If you want to have screen automatically off after 5 seconds for example, you can't use power button.

As I see the combination that you specified is not possible and it mentions in the settings when you enable wakeup time it disables power button with comment.

**Comment by IsecacIt** [comment]
I don't think you read my message. In the end I did not enable "wake time" but "screen timeout".

It's supposed to work, you said it yourself here : https://github.com/osmandapp/Osmand/issues/9110#issuecomment-638972698
"i. Screen timeout on, Power Button"

There is no Android technical limitation, Komoot does it well.

I'm a software engineer, if I can't get it to work the way I want even after searching if github issues, the average user won't either.

**Comment by vshcherb** [comment]
Yes, 
- Screen timeout on + Power Button - works on my device.

Which profile did you apply / test it ? Did you try on another profile - Browse map

**Comment by IsecacIt** [comment]
@vshcherb Ok so I did some tests from home, and here is what happens on multiple profiles (I tried cycling and driving):
- with "screen timeout on + navigation instructions", screen turns off after 30s, OK
- with "screen timeout on + power button", screen also turns off after 30s, and I can get osmand back by pressing the power button, OK
- with "screen timeout on + navigation instructions + power button", screen doesn't turn off until I manually turn it off by pressing the power button (but next time it will turn off after 30s)

3rd one is a clearly a bug, even if not that bad compared to what I experienced previsouly (obviously since I'm at home, I can't say if instructions work):

> But it didn't, the screen would stay on. I turned it off manually by pressing the power button, but then it would never wake up, nor give me instructions... So I pressed the power button again and the lock screen showed.

**Comment by vshcherb** [comment]
Clear need to be fixed

**Comment by IsecacIt** [comment]
`(obviously since I'm at home, I can't say if instructions work when the screen is off):`

Went for a ride today, navigation carried on when screen was off and vocal instructions woke up the phone as wanted (just had to allow location access in background, see #9425)

So all there is to fix is the small bug with "screen timeout on + navigation instructions + power button".

**Comment by vshcherb** [comment]
We've tested it with many settings and it's possible that screen doesn't turn off if you touch the map or move the map in between sessions on some devices.

With our latest tests the perfect setup:
System screen timeout (possible to change that profile) + navigation instructions + power button + proximity sensor

Works perfectly in all situations and it is also possible to configure screen timeout on  device itself.

We will probably disable setup of separate screen timeout and use only system default
