### ISSUE TITLE
POIs with tourism:alpine_hut displayed only on high zoom levels

### ISSUE THREAD

**Issue by dritter** [osmandapp/Osmand#9387]
Hi there,

POIs with `tourism:alpine_hut` are displayed only on high zoom levels.

For Example the ["Landsberger Hütte"](https://www.openstreetmap.org/way/101987039) shows only if I zoom down to 10 Meters, but not if zoomed to 20 Meters.
![Screenshot_20200704_162633_net osmand plus](https://user-images.githubusercontent.com/1544760/86514714-db3bb200-be13-11ea-9396-caf99f831696.jpg)

![Screenshot_20200704_162624_net osmand plus](https://user-images.githubusercontent.com/1544760/86514721-e1ca2980-be13-11ea-841d-9dbbff50b401.jpg)

It would be nice if these POIs would be displayed on lower zoom levels as well.

**Comment by vshcherb** [comment]
I agree it's probably should be enabled since 17th zoom.

**Comment by dritter** [comment]
@vshcherb Thanks for your reply. The more I think about that, the less I am confident I understand you correcly. That may be because of my lack of using the correct terms. For what I understood is that the 17th zoom level is 20 meters, and assume that the 18th zoom level is a more "zoomed in" (down to 10 meters) view. 
In my opinion the alpine huts should be displayed even in a 500 meters zoom (not sure which zoom level that is).

**Comment by vshcherb** [comment]
Well we have certain limitations and we need to use some levels for some modes. For default map style zoom level could be the minimum 16, where for more specific modes like more details or hiking it could start from zoom 15 or 14.

**Comment by dritter** [comment]
@vshcherb good point! I use biking as my default profile, and once I switch to hiking, the hut is displayed at a zoom level of 100 meters.
Interestingly the well right next to the Landsberger Hütte is displayed from 200 meters zoom (hiking) and 100 meters (biking). I would suggest that alpine huts are preferred over wells (that would even play well with the limitations). But that is just my opinon and may depend on the surrounding (e.g. in the desert where no hut is around, I prefer to see wells probably :smirk: ).

**Comment by vshcherb** [comment]
Fixed
