### ISSUE TITLE
Dangerous U-turn

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#9389]
Driving 
from 49.46879° N, 7.14605° E
to 49.48433° N, 7.13405° E
the navigation want to make a U-turn which is quite dangerous and not necessary. Of course a turn restriction could help, but no driver would make such a turn. There might be much of theese situations.
version 3.7.0#30110 from 2020-07-04
profile: default car

![Screenshot_20200704-214244_OsmAnd~~01](https://user-images.githubusercontent.com/18628183/86519903-bfe69c00-be3f-11ea-8d28-c8e0bed5fa09.jpg)

**Comment by vshcherb** [comment]
Navigation can't detect if U-turn or sharp-turn is dangerous. Anyway we don't want warning we would like to avoid such route at all. Unfortunately it is only possible if there is a turn restriction. 
We have extra penalty for sharp turns which could be increased to a certain limit.

**Comment by pebogufi** [comment]
I think crossing the oncoming lane of a highway=trunk with a maxspeed=100 to the left for a sharp u-turn can be treated as a suicide attempt - so for me dangerous. 
I think this crossing of a fast lane for a sharp u-turn should have a very high penalty.

**Comment by scaidermern** [comment]
I agree. The penalty for u-turns should depend on the highway class.

**Comment by Aiurek** [comment]
duplicate #7388

**Comment by hakuchi** [comment]
there is a 5 years old turn restricton:     
https://www.openstreetmap.org/relation/1898792

Maybe OsmAnd have a problem with the `only_straight_on` in this restriction.

@pebogufi: is the route calculation correct if you come from north and drive to the east?

**Comment by pebogufi** [comment]
> @pebogufi: is the route calculation correct if you come from north and drive to the east?

Yes it is correct.

**Comment by MadWasp79** [comment]
Cannot reproduce on current maps. Maybe it was some glitch. 
![image](https://user-images.githubusercontent.com/13146346/91834590-ef076700-ec50-11ea-9581-d9955d092c3c.png)
