### ISSUE TITLE
Crash when trying to create poi

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#9391]
Device : gts4lv
Brand : samsung
Model : SM-T725
Product : gts4lveea
Build : PPR1.180610.011.T725XXU1ATE3
Version : 9
App Version : OsmAnd~
Apk Version : 3.7.0#30113m 370

[exception_log.zip](https://github.com/osmandapp/Osmand/files/4874706/exception_log.zip)

**Comment by vshcherb** [comment]
Fixed
