### ISSUE TITLE
Display user relevant PT route related information

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#9395]
I just notice we seem to not display vital information data (e.g. for bus routes) which per OSM wiki is to be tagged with either the route relation or the route_master relation, most prominently e.g. tags
- website
- opening_hours
- network
- operator
- description

**Comment by vshcherb** [comment]
Yes known issue, we planned to implement it with other bug for Night buses, though I will keep this issue separately open

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/7029
