### ISSUE TITLE
Japanese placenames are transliterated as Chinese

### ISSUE THREAD

**Issue by zekooooo** [osmandapp/Osmand#9400]
When using a non-Japanese language with transliteration turned on, if there's no corresponding name:language tag on a placename in Japan, the kanji parts are transliterated using Mandarin Chinese pinyin, which has no relation to the Japanese pronunciation.

Hiragana parts seem to be transliterated properly, maybe because hiragana characters are specific to Japanese, while kanji characters are mostly shared with Chinese.

The problem is compounded by the fact that most kanji have multiple pronunciations. A workaround could be to substitute name:en where it's available, since that's probably the most common foreign name tag.

Using OsmAnd~ 3.7.4 on Android 7.

**Comment by vshcherb** [comment]
that issue supposed to be fixed for maps of Japan please share location to test.

**Comment by vshcherb** [comment]
Here is what should happen - https://github.com/osmandapp/OsmAnd-tools/blob/master/java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/util/JapaneseTranslitHelper.java#L20

**Comment by zekooooo** [comment]
I don't have any Japan maps installed. When browsing the world map, faux Chinese names appear when zooming in when language is set to e.g. Croatian and transliteration is enabled.

It seems that when I install e.g. the Kyushu map the issue goes away (Japanese characters are displayed even with transliteration enabled). I've uninstalled that map and the characters stayed untransliterated even after several switches to English or local and back, but the next day "itikiChuan Mu Ye Shi" etc. came back.

**Comment by MadWasp79** [comment]
@zekooooo During map creation, we are forcing correct transliterations only for name_en tags (in case there is no translation in data already). Adding transliterated tags for every language is overkill. And as I see it, we turned off transliteration for other languages, so even turning it on leaves original Japanese hieroglyphs in place. I will look into this issue but for now, if you want to see correct transliteration, choose the English language for map browsing and it will transliterate most of the signs in Japan correctly.

**Comment by zekooooo** [comment]
Ok, thanks. It's really more of a cosmetic problem here since it only happens to people browsing the world map, not to those who have (and use) a Japan map. Just posted here in case it had a quick fix :)
