### ISSUE TITLE
Flooding: Skadovsk

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#9404]
http://www.openstreetmap.org/#map=12/46.02125/33.46258
Maps: Russia_crimea and Ukraine_kherson. Looks like algorithm issue. Basemap is not the cause. 
![Screenshot from 2020-07-03 10-21-43](https://user-images.githubusercontent.com/5829014/86775277-ec78fe80-c05f-11ea-9a43-75d4f2b5912e.png)

**Comment by xmd5a2** [comment]
Looks like the same issue
http://www.openstreetmap.org/#map=10/45.940666/32.96924
Maps: Russia_crimea and Ukraine_kherson
![Screenshot from 2020-07-07 14-45-14](https://user-images.githubusercontent.com/5829014/86775947-79bc5300-c060-11ea-8a51-f936ab298d16.png)

**Comment by vshcherb** [comment]
Not reproducible :-(

**Comment by xmd5a2** [comment]
Issue with Alekseevka is not reproducible on my system but second case (Skadovsk) is easily reproducible
