### ISSUE TITLE
Not all hiking routes shown

### ISSUE THREAD

**Issue by matthijskooijman** [osmandapp/Osmand#9405]
I'm using OsmAnd+ from F-droid on Android 7 (FP2) version 3.7.4 with offline maps and a live subscription.

I have hiking routes enabled with Routes -> Hiking symbol overlay -> Color by OSMC hiking symbol. This causes some routes to show up, but not others. For example:
 - https://www.openstreetmap.org/relation/9505347 is not rendered ([screenshot](https://user-images.githubusercontent.com/194491/86827240-08959380-c092-11ea-8576-4ad25bf60424.png)).
 - https://www.openstreetmap.org/relation/7810572 is properly rendered ([screenshot](https://user-images.githubusercontent.com/194491/86827233-07fcfd00-c092-11ea-9773-c6fde85cdeed.png)).

The route is not rendered regardless of zoom level. I also tried enabling "Alpine hiking scale (SAC)", but that did not help. Also the "Color by network affiliation" or "Node Networks" options do not render the route.

I'm not entirely sure if this is a rendering bug or a tagging bug, but looking at the relations in the OSM database, they look highly similar, ~~except that the broken route has a `fixme` and the non-broken route has a `note` tag (and I wouldn't expect those to be relevant)~~.

**Comment by matthijskooijman** [comment]
I added a note to the broken route (since that's documented as a [recommended but optional tag](https://wiki.openstreetmap.org/wiki/DE:Switzerland/HikingNetwork) anyway), but if the live hourly updates worked as expected (I uploaded the change about 3 hours ago), that didn't help. I just removed the fixme, making both routes pretty identical in their tagging (I'll have to check if that helped tomorrow).

**Comment by matthijskooijman** [comment]
I also added some other routes, including [this one with a fixme](https://www.openstreetmap.org/relation/11281548#map=16/47.2299/9.0574), which are rendered as expected, so it does not seem to be the fixme.

The only other thing I can find is that the broken round uses spaces around the - in the name and note (i.e. "Unter Berg Sion - Schwarzholz", while others do not (i.e. "Bergli-Wilderau"), but I would not expect that to be relevant (OTOH, I've read somewhere that routes must have a name to be rendered, so maybe this is somehow relevant)? Also, this broken route is not actually connected to it (it's just a single stretch disconnected from the rest of the network), but that should also be possible I guess (not all routes are part of a network anyway).

**Comment by xmd5a2** [comment]
Not sure how did you tested but this route is rendered correctly. There are no osmc:symbols because no background is specified in corresponding tag.
![Screenshot from 2020-07-08 10-17-53](https://user-images.githubusercontent.com/5829014/86889376-4c28e580-c104-11ea-8b81-79a3db4a392a.png)

**Comment by vshcherb** [comment]
With live updates there is another issue that sometimes we're missing tags on the road, it is open already for 3.8
https://github.com/osmandapp/Osmand/issues/6743

**Comment by matthijskooijman** [comment]
Hm, I can also no longer reproduce it, maybe it was indeed caused by #6743 and another live update has fixed it again.

Thanks for your responses!
