### ISSUE TITLE
[Feature request] Show context menu for the current location after a long tap on location button.

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#9408]
We can try to show the context menu for the current location after a long tap to "My location" button.

**Comment by dmpr0** [comment]
Review:
If there are other points or track around the location after a long tap appears "What's here" menu, I think long tap on location button should always open a context menu for location.

**Comment by dmpr0** [comment]
![Screenshot_20200811-170328](https://user-images.githubusercontent.com/9365308/89907027-cb727300-dbf4-11ea-8d77-24517dd7cb69.png)

**Comment by pebogufi** [comment]
When making a long tap to set a destination oder intermediate destination for routing i also have a problem. Tracks are shown like last posting (screenshot from dmpr0), but not the menu for routing.
See also https://github.com/osmandapp/OsmAnd/issues/9613
