### ISSUE TITLE
[Feature request] add automatic track recording

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd#9414]
In the Track recording plugin settings, there is an option to enable Automatic recording during the navigation mode. 
It would be useful to add automatic recording after starting the app.

**Comment by kocjs** [comment]
#10105

**Comment by kocjs** [comment]
#10105

**Comment by kocjs** [comment]
Any particular reason for closing this without a comment?

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/10105
