### ISSUE TITLE
Make man_made=pier routable

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#9416]
Several ferries are connected via `man_made=pier` to the routing network. Some have an additional `highway` way, but not all of them. The ones just using `man_made=pier` are currently ignored for routing. Please include `man_made=pier` in the routing network.

Example for ferries connected only via `man_made=pier` and being ignored for routing:
* https://www.openstreetmap.org/way/24349314
* https://www.openstreetmap.org/way/23020310

Examples for ferries with an additional `highway` connection and being used for routing:
* https://www.openstreetmap.org/way/27370672
* https://www.openstreetmap.org/way/4773668

**Comment by xmd5a2** [comment]
That's debatable change. According to wiki man_made=pier is not routable by default.
https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dpier

> If passengers wait for ferry lines at this pier and if the ferry routes are mapped as public transport relations:
>     add public_transport=platform on it

Most of piers are pedestrian only. I think that issue should be solved on OSM side
