### ISSUE TITLE
Change (or remove) translation for UK-Region "Greater London"

### ISSUE THREAD

**Issue by kmpoppe** [osmandapp/Osmand#9421]
"Greater London" is defined in the resources:
https://github.com/osmandapp/OsmAnd-resources/blob/b433f5326814cee17477d991a96fa4e8610bf342/countries-info/regions.xml#L413

"North East England", "North West England", "South East England" and "South West England" where "England" is the proper name and North/South/East/West are merely the geographical description, for me, make sense to be translated (for German these are Nordostengland, Nordwestengland, ...). All other Regions (East Midlands, East of England, West Midlands, Yorkshire and the Humber) are not translated which is totally fine as those are a proper name in their conqunction.

YET, "Greater London" has a translation to "Groß-London" which makes no sense as "Greater" isn't a description of London but GL/the GLA respectively are a proper name in their conqunction only.

I wasn't able to find the translations of the map names on weblate. So, if anyone would be able to point me to the right area where to look for them, I'd be happy to change this myself.

Obviously, I'm also open for discussion on this matter.

Kai

**Comment by vshcherb** [comment]
It is managed on openstreetmap.org please change it there first.

**Comment by kmpoppe** [comment]
@vshcherb I kid you not, I had never thought that the translation comes from the `name:de` of https://www.openstreetmap.org/relation/175342. I will need to investigate/discuss that further.
Closing the Issue in the meantime as this is not a OsmAnd-thing per se.
Thanks!

**Comment by vshcherb** [comment]
We regenerate / retrieve new names on average 1-3 times a year, though we can do it on request as well. 
Scripts and data are located here - https://github.com/osmandapp/OsmAnd-misc/tree/master/osm-planet/osm-data
