### ISSUE TITLE
Route calculation issue - U turn

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#9428]
When calculating a route in the car profile from:
55.93053° N, 23.30479° E
to:
55.92445° N, 23.31262° E
the route is build with the U-turn that is impossible to follow
![image](https://user-images.githubusercontent.com/50198677/87149972-e1b9a600-c2b9-11ea-9753-4fe34e39b240.png)

**Comment by naoliv** [comment]
A `turn_restriction` would probably be the solution there.
See also #7388 and #9389
