### ISSUE TITLE
[Feature Request] More selectable Colors for GPX tracks

### ISSUE THREAD

**Issue by jensMF** [osmandapp/OsmAnd#9431]
OsmAnd+ 3.7.4

There are 12 colors that can be selected for favorites but only 6 (the same six in non-transparent and in transparent so there are 12 options as well) for GPX tracks. I would find it great to have more colors selectable and maybe also have the option to select custom colors (for both, favorites and tracks).

**Comment by dmpr0** [comment]
Current nightly builds have a new "Appearance" screen for each track file, where is possible to add custom color using the color picker.

**Comment by jensMF** [comment]
I really like this feature, but one can only add six colors. In one of the recent releases, one could change these colors for a new track, and the old one kept the color chosen before. In the last release, when I change the color, the color of the old track changes too.
I liked it more, when the old track kept the old color, because that gives me more flexibility. May be, it would be possible to change that back or to have at least one completely free choosable color field (where tracks that got this color before do not change color when one changes the color, but keep the color they have.)
