### ISSUE TITLE
Offline navigation does not regard turn restriction

### ISSUE THREAD

**Issue by bege10** [osmandapp/Osmand#9433]
OsmAnd 3.7.4
Samsung Galaxy S5 Plus (SM-G901F), LineageOS for microG 16 (Android 9)

Germany_bayern_europe.obf 2020-07-01
 OsmAnd's in-app offline routing (car, bike)

**Würzburg, Grombühlstr. to Senefelderstr.** 

![Screenshot_20200615-002810_OsmAnd~](https://user-images.githubusercontent.com/1184237/87250081-0bfa9780-c463-11ea-9b6d-768078adf751.png)

![Screenshot_20200622-185728_OsmAnd~](https://user-images.githubusercontent.com/1184237/87250112-3d736300-c463-11ea-9a9a-44d55728a3f4.png)

https://www.openstreetmap.org/relation/63708

**Würzburg, Grombühlstr. to Schweinfurter Str.**

![Screenshot_20200615-002414_OsmAnd~](https://user-images.githubusercontent.com/1184237/87250245-d6a27980-c463-11ea-9855-48541f66c576.png)

https://www.openstreetmap.org/relation/69117

in both cases the no_left_turn restriction is not regarded for both car and bike

The app Mapfaktor free does it correct (bike through tunnel)
https://forum.openstreetmap.org/viewtopic.php?pid=790953#p790953

Compare with PC **browser openstreetmap navigation**: **car** navigation OSRM is correct
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=49.80071%2C9.94969%3B49.80113%2C9.95139#map=17/49.79985/9.95225
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=49.80039%2C9.95211%3B49.80028%2C9.95102#map=17/49.80063/9.94938
Graphhopper is wrong as OsmAnd oflline
**bike** navigation both are wrong as OsmAnd offline.

**Comment by xmd5a2** [comment]
All cases are not reproducible
![Screenshot_2020-07-23-11-31-47-761_net osmand plus](https://user-images.githubusercontent.com/5829014/88267351-66a0b880-ccd9-11ea-84eb-45e4937e58b4.jpg)

**Comment by vshcherb** [comment]
Can't reproduce any more

**Comment by bege10** [comment]
I still have 3.7.4 and just updated the map via OsmAnd Live.
The route in the last screenshot is correct now for both car and bike (bike through tunnel).
The route in the first two screenshots is still the same as posted.

**Comment by vshcherb** [comment]
First screenshot not reproducible with new map data. So only pedestrian can do this left turn, bicycle and car will make a detour. 

Please wait for new maps and clean up live data if you have it .Bicycle:
![image](https://user-images.githubusercontent.com/1042025/89291303-9c8b5880-d65a-11ea-90c9-a4e18f7ef5dd.png)

**Comment by bege10** [comment]
I updated the offline map for Bavaria, cleared Live data and afterwards updated Live data. Still the same. What else can I do?

**Comment by vshcherb** [comment]
You can try to delete Bavaria and download only Lower Saxonia.
![image](https://user-images.githubusercontent.com/1042025/89401215-40d1d580-d715-11ea-88f9-adefce60a454.png)
![image](https://user-images.githubusercontent.com/1042025/89401222-429b9900-d715-11ea-9deb-9040932596b2.png)

The best will be to wait for August maps and August release 3.8 and then let us know, we're still confused how does it not work.
