### ISSUE TITLE
Osmand ignores "world overview map" installation, constantly believes it's out of date

### ISSUE THREAD

**Issue by frankspace** [osmandapp/Osmand#9435]
Osmand seemingly downloads and installs the "world overview map."  However, it never seems to _actually_ update it.  It isn't listed in the "Updates" tab, and the current version is listed as installed in the "Local" tab, but it remains listed as not updated under "All Downloads" and I'm always prompted to install it -- despite it apparently already being installed.  This does not seem like correct behavior.

**Comment by scaidermern** [comment]
Same for me. Has already been mentioned in

**Comment by tps800** [comment]
Same here. Downloads the same map over and over again, believing it is out of date. Sems the same bug as with some other maps it believes they are out of date too.

**Comment by martincampbell** [comment]
Same for me too. Started after I downloaded "World overview map (detailed)". Repeatedly prompts to download "World overview map" even though it is already downloaded and up to date.

**Comment by vshcherb** [comment]
You probably need to redownload World wide overview, it's from 12th of June 2020. First of all detailed map now is removed and you can delete it as well and only 1 map left. Secondly, it was reuploaded recently. 
This is considered to be a stable version at least for 2020.

**Comment by scaidermern** [comment]
OsmAnd 3.7.4 still asks for updating the world overview map when updating a regular map. The world overview map is shown as grey in "all downloads" but green in "local". Removing and reinstalling it doesn't help.
