### ISSUE TITLE
Some cycling network nodes and routes not rendered

### ISSUE THREAD

**Issue by matthijskooijman** [osmandapp/OsmAnd#9437]
This is a followup from #5686, which has been closed after cycle route rendering was much improved.

I doublechecked all the problematic cases from my https://github.com/osmandapp/Osmand/issues/5686#issuecomment-412665824 and indeed most of them are fixed, but unfortunately not all of them. Also, some of them seem to be more pronounced in the Topo map style (which I rather like for cycling, because of its higher contrast), but also happen in some cases in the default OsmAnd style.

In particular, the following problems still exist:
 - https://www.openstreetmap.org/node/43356003 is shown at medium zoomlevels ([screenshot](https://user-images.githubusercontent.com/194491/86819407-e4cd5000-c087-11ea-9f17-271d4b680036.png)) but not when zoomed further in ([screenshot](https://user-images.githubusercontent.com/194491/86819410-e565e680-c087-11ea-80c8-7591b2581434.png)) or out ([screenshot](https://user-images.githubusercontent.com/194491/86819405-e434b980-c087-11ea-8220-7bf449dc8cd9.png)). In Topo map style, it is not shown at all regardless of zoomlevel ([screenshot](https://user-images.githubusercontent.com/194491/86819403-e39c2300-c087-11ea-9cb7-98bb33ead15b.png)).
 - https://www.openstreetmap.org/node/44244889 is not shown when zoomed out ([screenshot](https://user-images.githubusercontent.com/194491/86819399-e26af600-c087-11ea-8003-7a32b51c00ec.png)), even when other nearby nodes are shown at that zoom level. In Topo map style, it is not shown at all regardless of zoomlevel ([screenshot](https://user-images.githubusercontent.com/194491/86819400-e3038c80-c087-11ea-864b-b876a03e0075.png)). There is a picnic table very nearby, which I originally suspected to be the cause (though it happens even when the picnic table is not rendered at a particular zoom level).
 - https://www.openstreetmap.org/node/43319582 is not rendered when zoomed out ([screenshot](https://user-images.githubusercontent.com/194491/86824112-00d3f000-c08e-11ea-97d8-dd6bd00fcfca.png)) even when other nearby nodes are shown at that zoomlevel. With Topo map style, it is not shown at all regardless of zoomlevel ([screenshot](https://user-images.githubusercontent.com/194491/86819396-e1d25f80-c087-11ea-9d97-65217c179c1a.png)). I originally suspected this happened because the node is also `traffic_calming=table`, but the problem happens when the table is not rendered (Topo-style never seems to render those), so I'm not sure if that's actually the cause.
 - https://www.openstreetmap.org/way/97677179 is not shown ([screenshot](https://user-images.githubusercontent.com/194491/86819399-e26af600-c087-11ea-8003-7a32b51c00ec.png)) when zoomed out somewhat (it is shown when zooming in more closely). The same happens with the Topo style ([screenshot](https://user-images.githubusercontent.com/194491/86825204-61176180-c08f-11ea-8e0d-f1a3a77f3051.png)). This is a new problem, not from the original comment, that I noticed because it was nearby the previous point. Also note that the original way is not drawn at that zoom level either, but in other cases that does not stop the route from being drawn either (e.g. the route going ENE from node 65). I also considered this might be caused by live updates (i.e. #6743), but reinstalling the map with live updates disabled still shows the problem, so I think it is not the same problem.

So there might actually be two separate issues:
 - For the OsmAnd style, some things are not shown depending on zoom level, but they can always be shown by (usually) zooming in or (sometimes) zooming out, so these are minor issue (though they still hurt usability when using OsmAnd for bike navigation). I suspect that the fixes made for this issue have helped to give routes more priority, but maybe there might still be priority conflicts in some cases.
 - For the Topo style, these issues occur regardless of zoom level, more like the OsmAnd style originally, so maybe the fixes made for this issue were made only to the OsmAnd style and not for Topo yet? These issues are also more significantly hurting usability.

This is OsmAnd version 3.7.4, on Android 7, with offline maps and live updates. Screenshots above were made with the "Netherlands" standard map from May 1, 2020, with live updates applied (not sure which version, probably something like july 6th or 7th).

**Comment by vshcherb** [comment]
I think this issue should be closed with new maps. 
- Topo style is fixed. (nightly already)
- Some nodes are not rendered due to text priority from City/Towns which we think could be more important.

**Comment by matthijskooijman** [comment]
> I think this issue should be closed with new maps.

Thanks! I see in the rendering styles that significant changes have been made in the last weeks, I suppose that's what should fix this. I wanted to doublecheck the above items with the nightly build, but I noticed some of the changes also affect the obf export files, so I suspect this means that the nightly build needs newly exported map files as well (seems most recent maps available are july 1st, so I guess that's too old)?

More generally, I wonder whether this means that updating the app without updating the maps might actually break things due to refactorings like these? Or are there mechanism in place for compatibility?

In partcular, I noticed (in yesterday's nightly with july 1st maps) the Topo style seems to show no cycle nodes at all, but I suspect this is because some tags are missing in the older maps?

**Comment by vshcherb** [comment]
Once @xmd5a2 is back from vacation he will double check Topo style and this issue will be finally over. I started using cycle nodes myself more often in NL, so I think I will double check visibility in all modes in field. 

Most important of course to draw nodes and display a combination of international routes as well. As I see we need to show route names on the line (not like flat label point) and there is a mismatch sometimes (60-61 is separated from other routes)

![image](https://user-images.githubusercontent.com/1042025/90420950-f8bd9600-e0b8-11ea-9e7a-0e5ae6c2a362.png)

**Comment by vshcherb** [comment]
List of TODO from me:
1. Draw routes (60-61, LF2, LF7,...) along the line
2. Remove Halo effect around numbers (62), so it looks better
3. Check if we need combine lines if they are the same i.e. combine 50-61 with 60-61 (probably we don't need to do it cause they are parallel lines)
4. Check Topo style has these features inherited

**Comment by matthijskooijman** [comment]
> As I see we need to show route names on the line (not like flat label point)
Ah, that would indeed be helpful. As for drawing the route names at all, I originally thought those would be rather pointless (at least for node networks), but now that they are drawn, I noticed on my recent trip that it is indeed terribly convenient if you can see what the destination node of a route is going when you're zoomed in on the departure node. Drawing them along the route, would make them even easier to distinguish.

> (60-61 is separated from other routes)

Looking at your screenshot, isn't 60-61 left of the river and the other routes right of the river? If so, they're rightfully separated? OSM.org confirms this when you zoom in: https://www.openstreetmap.org/#map=17/52.31524/4.90515&layers=CN Maybe you realized this already, but considered to merge them anyway when zoomed out because they're close enough? That sounds hard to implement, and might even be confusing to users.

**Comment by vshcherb** [comment]
Modified the list then :-) 60-61 is correct separation

**Comment by matthijskooijman** [comment]
In case you didn't see them yet, maybe #9598 and #9597 are also things that are related to the things on your list.

**Comment by matthijskooijman** [comment]
Hm, that might sound a bit unfriendly ("Here, there's more things I think you should do"), but that's certainly not what I meant. Even more so, I'm actually very happy with all the work that's gone into the cycling (route) features recently. OsmAnd was already a great tool for bicycle route planning and live navigating (I built a mount to put my tablet on my bike for running OsmAnd on the way two years ago as a first attempt, and we stopped carrying paper maps the next holiday because it worked so well), recent additions and fixes have made it better and it seems that perfection is getting near :-) So thanks for all this!

**Comment by xmd5a2** [comment]
https://github.com/osmandapp/OsmAnd-resources/commit/8d58e9bad376a4be95df5cfdd73d4078534f29f8

**Comment by matthijskooijman** [comment]
I just tried the default dev build, which has that change included, looks good!

**Comment by vshcherb** [comment]
Most of the issues closed and fixed, others are moved to another issues
