### ISSUE TITLE
Compile for GNU/Linux: How to do it, how tu use  'i686-linux-clang.sh'?

### ISSUE THREAD

**Issue by felixbecker2** [osmandapp/OsmAnd#9442]
Dear OsmAnd-people,

I was asked by the support team to post my request here as an issue, although I do not see it as an issue with OsmAnd itself.

So I post here what I emailed before:

I really like your app, and although I am using the variant from f-droid, I am thinking of making your a donation.

It is the best offline OSM-based mapping and routing software I have encountered so far.

Now, I have a question:  
I am usually not using android, but a normal desktop computer.

I wish to run it under GNU/Linux (natively).

I discovered that there are the files `i686-linux-gcc.sh` and `i686-linux-clang.sh` in [github.com/osmandapp/OsmAnd-build](/osmandapp/OsmAnd-build) -- but I cannot find any documentation on how to build it for Linux (just invoking the scripts fails, and invoking `cmake` locally in OsmAnd-build also fails).

Can you give advice/ write documentation on how to compile OsmAnd(~/+) for GNU/Linux?

**Comment by vshcherb** [comment]
This is not possible all features require Android API, the only program runs under Linux is OsmAndMapCreator but it a map preparation program

**Comment by brabo** [comment]
i had a cursory glance at this in order to maybe get osmand to run on leste. seems an emulation layer like anbox might work, i myself did not look further into the matter though ;)

**Comment by hstejas** [comment]
@vshcherb 
Probably its not exactly what OP wanted, but I was able to build it on Ubuntu 18.04, with very minimal changes. (gcc 7.5)

I saw there were some examples for Linux and not Android
The build target is bird_standalone / [map_viewer](https://github.com/osmandapp/OsmAnd-tools/tree/master/cpp-tools/map-viewer)

The binary is generated and I am able to launch it, but all i see are white/empty tiles. I am guessing this was meant for debugging/testing

It seems to require some parameters `-obfsDir` or `-dataDir` AND `-stylesPath` or `-style`

I tried to give a directory containing this https://builder.osmand.net/basemap/World_basemap_mini_2.obf and another obf for Berlin I built using the data from geofabrik, (for `obfsDir` and `dataDir`)

Am I giving the params correctly? is there some log or something else I can check?

**Comment by noci2012** [comment]
Getting this working might make it useful for Librem-5, PinePhone etc as well.
The alternative is using flatpack "Pure maps" + flatpak "OSM Scout server"   (probably installing 2 different versions of KDE envronments). 

Anbox might run or not. Librem will not put any effort in anbox though, their priorities are with a native environment. They won't block efforts for anbox though.

**Comment by joshbowyer** [comment]
Yes, this would be amazing on the Pinephone/Librem5 (Debian). And also for regular Linux desktop.

Although honestly I wonder if it might just be easiest to fork GNOME Maps and add the functionality in that...

**Comment by vinniec** [comment]
It's very sad that the best nav software is opensource and at the same time only for android :(

**Comment by vshcherb** [comment]
It is not planned to be fixed in our roadmap for next year, so the issue will be closed

**Comment by anaxonda** [comment]
Am responding here rather than starting a new issue: How hard would it be to port a native linux version of Osmand? Having native Osmand would be a huge boon in being able to switch away from android to a pinephone or librem.

**Comment by vshcherb** [comment]
All UI is tight to Android or Apple SDK, so it all needs to be ported and it seems not possible now.
