### ISSUE TITLE
Issues with some maps (won't download / update)

### ISSUE THREAD

**Issue by chris-ca** [osmandapp/Osmand#9445]
Using Osmand+3.7.4 (Android 10).

During the monthly map update I did an "update all" on my installed maps. Most maps were properly downloaded and updated, but 4 maps were not. Example: Germany_baden-wuerttemberg_europe_2.

I observed the automatic download reaching 100% but after completion the map was still listed in the "Updates" section. 

## Partial workaround
I  renamed the outdated map to ".old" and manually downloaded the new map and saved it in the files folder. As a result, the map disappeared from the "Updates" tab. I observed the new and the old map having different file sizes and different names (*europe.obf vs *europe_2.obf)
<img src="https://user-images.githubusercontent.com/13023534/87406105-91e02500-c5c0-11ea-9952-28d30748fae7.png" width="100">
<img src="https://user-images.githubusercontent.com/13023534/87406107-9278bb80-c5c0-11ea-9269-ffef99aa4808.png" width="100">

The downloaded maps seems to work fine, however Osmand still does not fully recognize it. The map area is **not** marked green in the overview and Osmand still asks to download a regional map when zooming in:
<img src="https://user-images.githubusercontent.com/13023534/87407797-ef757100-c5c2-11ea-9abd-8815cd180d7f.png" width="100">

I also deleted "regions.ocbf" and "ind.cache", which had no effect.

**Comment by tps800** [comment]
Same here. Certain maps download, but are never recognized as downloaded. In some cases it helped to delete the old map from osmand, then download the new map again. But not in all cases.

**Comment by sonora** [comment]
@vshcherb I guess there is something wrong with our map creation this time round: As an example, the July 1 map Germany_bavaria did not show up until July 12 or so. It is now finally offerrd for download, I have installed it, and see the same issue reported above. It is dated July 1, 2020, but labeled as outdated. By inspecting it it clearly seems to miss features which were edited into it before July 1, so its content seems indeed not up to date. The region map Bavaria_upper-palatinate, however, did appear rather promptly on July 1, and it does in deed contain recent edits. Have we maybe hit a size limit with Bavaria, or is zhere some other issue going on?

**Comment by martincampbell** [comment]
Same for me. Prompts me to update "Germany Hesse". No sooner is it downloaded than in prompts me to update it again.

**Comment by martincampbell** [comment]
This is a recurring SERVER SIDE problem at osmand.net.
The index server at osmand.net advertises a list of the latest maps with dates.
When you download a map, you are randomly redirected to a load-balanced download server.
The map versions on the download servers frequently lag behind the versions advertised on the index server.
The client app sees an update on the index server, tries to download it, gets an old map instead, and tries again and again.
The problem eventually goes away when the versions on the download servers finally catch up with the version advertised on the index server.

**Comment by chris-ca** [comment]
Meanwhile the maps have updated for me as well. Thanks for the explanation, @martincampbell.

I'll leave the issue open so a project member can decide right course of action

**Comment by vshcherb** [comment]
Between 12-17 July there was a huge load on our download servers and they were running out of network. Except normal activity of updating all maps which creates high load on 12th dates beginning from month, we've also detected some spam activities. 

The map dates are always checked on device and could be marked outdated immediately after download because load balancing will offer a wrong outdated map. Combined maps such as Bavaria were generated on 12th July and that's probably caused additional instability

**Comment by vshcherb** [comment]
Different names will lead to problems of Highlighting areas, so you can rename it after unpacking
