### ISSUE TITLE
Show canal locks in waterway routing

### ISSUE THREAD

**Issue by tbertels** [osmandapp/Osmand#9446]
When we enable the boat navigation profile to use the beta waterway routing feature (#3990), the canal [locks](https://wiki.openstreetmap.org/wiki/Key:lock) and their name should be shown in the turn-by-turn list.
Going through a lock takes at least 15 minutes (if there's no queue), so it's important to mention them.
Osmand could also add 20 minutes or so per lock to take that time into account.

**Comment by vshcherb** [comment]
Waterway=lock_gate penalty is introduced. Unfortunately there are many map objects which are shown on the map as "ways", our routing engine can't support penalty for way obstruction. It is quite special penalty cause it is not a penalty on the road which belongs to the route, but it is a penalty on the way which intersects the route itself. 

We suggest to change mapping scheme or simply put points which could be marked as barriers for waterway route.
