### ISSUE TITLE
Screen Control, proximity sensor although has light effection

### ISSUE THREAD

**Issue by quax2712** [osmandapp/Osmand#9447]
When the proximity sensor is activated, the screen also turns on due to strong changes in light. This happens when you cycle along a path with trees, where the sun and shade alternate regularly. Then the screen may not turn off for a long time.
Problem accu will not keep for the rest of the day.

Greetings
Rainer

**Comment by scaidermern** [comment]
Sounds like a problem with your particular smartphone hardware. The proximity sensor works via a pulsing infrared LED. I guess the intermittent sun light is interpreted as a infrared reflection by your smartphone.

**Comment by quax2712** [comment]
You are right, I checked the proximity sensor by app. When sun and shadow alternate, it sometimes create a sensor peak.
Power button would be a solution, but could not be used in this mode.
Using system screen control, it is not possible to activate other apps like foto, but power button would work.
thanks
Rainer
