### ISSUE TITLE
show menu with swipe from left on all screens

### ISSUE THREAD

**Issue by 532910** [osmandapp/Osmand#9449]
Right now swiping from the left edge show menu only on map screen, I believe this should work on all screens:
![image](https://user-images.githubusercontent.com/14617699/87489804-9f42f100-c64c-11ea-920c-d64d26ae3e09.png)

**Comment by vshcherb** [comment]
It is disabled by purpose on all screens, this is not intended behavior

**Comment by 532910** [comment]
What is the purpose?

Does `#Observed` mean "not in this life"?

**Comment by dmpr0** [comment]
Modern devices have swipe navigation, and swipe from left usually works as the back button, so I think this only makes mess in navigation.

**Comment by 532910** [comment]
This contradicts the current behavior to show the menu swiping from the left.

**Comment by dmpr0** [comment]
OsmAnd has a separate "Menu" button on the map screen. Maybe we must disable swipe from the left for the drawer at all.

**Comment by 532910** [comment]
In my configuration menu button is replaced with dashboard button, so disabling swipe from the left for the drawer at all will requie one more action to open the menu for  such setups. 

Moreover, on modern devices that have swipe navigation, the menu already doesn't work nowhere, so it can't make a mess in navigation. Please reopen.
