### ISSUE TITLE
POIs along the Route

### ISSUE THREAD

**Issue by orbisvicis** [osmandapp/Osmand#9450]
OsmAnd can show POIs along the route. This shows a list of POIs of a given category within a given distance of the entire route, sorted by distance from the current position. Given the name "Show along the route", I'd like clarification regarding this feature. Are the POIs along the route supposed to be differentiated from other POIs? I am expecting only POIs along the route to be shown, or perhaps distant POIs to be given smaller icons. Instead all POIs are show identically, irrespective of distance.

1. Is this a bug? Does the functionality exist in a currently broken state?
2. Or is this a missing feature? Given the misleading name "Show along the route" perhaps even a planned feature.

Finally, does "Show along the route" have any bearing on the "Nearest POIs" category? Currently "Nearest POIs" shows every possible POI everywhere on the map. Not really "nearest". Just as the POI category "Search by name" applies to POI search results shown on the map, was the "Nearest POIs" category intended to apply to POIs selected along the route?

I ask because - assuming someone were to implement filtering route POIs on the map - if the "Nearest POIs" category can be repurposed, or if serves some other functionality.

OsmAnd/Android 3.7.4

**Comment by vshcherb** [comment]
They are filtered by distance and displayed in the list and 2nd is an issue
https://github.com/osmandapp/Osmand/issues/9377
