### ISSUE TITLE
Train Station POIs

### ISSUE THREAD

**Issue by orbisvicis** [osmandapp/OsmAnd#9451]
There should be a way to filter for train station POIs in the search. This would be more useful than the transport overlay for distance, completion, names, etc.

**Comment by dmpr0** [comment]
Hi! 
You can create a custom search category to "Railroad station".

<img src="https://user-images.githubusercontent.com/9365308/164894421-7fa823f1-9f57-4032-a61e-29a74cc01722.png"  width="360" height="auto"/>
