### ISSUE TITLE
[Feature request] sort groups of favorites for selecting a navigation point

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#9461]
When selecting a starting or a destination point of the route, there is an option to select a Favorites. Tapping on it the whole list of favorites appears. It may be more convenient to display groups of favorites that can be opened to see the related points and select a required point faster.

**Comment by scaidermern** [comment]
Quite similar to #5468.

**Comment by vshcherb** [comment]
Yes merged to  #5468
