### ISSUE TITLE
GPX-related crash in latest nightly

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#9464]
Not sure if this has been reported before, I am a little behind keeping track of recent issues:

With yesterday's nightly, I displayed 2 of my GPX tracks (not customized in any fashion, i.e. meaning to just display with standard color and standard 'star' icon for the waypoints contained).

Two observations:

Some waypoints shown did not have the star icon, but instead another symbol, like a little circle or a little checkerboard.

Zooming in to these points to investigate always resulted in the ArrayIndexOutOfBoundsException crash attached: here [exception.txt](https://github.com/osmandapp/Osmand/files/4931781/exception.txt)

PS: We should probably upgrade our apk version number some time soon, because when I reverted back to my current productive build, this produced more crashes because of 
`Caused by: android.database.sqlite.SQLiteException: table gpxTable has 33 columns but 26 values were supplied (code 1 SQLITE_ERROR[1]): , while compiling: INSERT INTO gpxTable VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

**Comment by vshcherb** [comment]
Well you can not revert some type of builds unfortunately, we always update version number for release though we're not doing it for nighlty versions. I hope this type of problems doesn't happen often cause it is not easy to deal with it.

**Comment by vshcherb** [comment]
> Some waypoints shown did not have the star icon, but instead another symbol, like a little circle or a little checkerboard.
This is start and finish, waypoints probably are missing

```java.lang.ArrayIndexOutOfBoundsException: length=1185; index=-1
	at java.util.ArrayList.get(ArrayList.java:439)
	at net.osmand.plus.views.GPXLayer.getTracksFromPoint(GPXLayer.java:667)
	at net.osmand.plus.views.GPXLayer.collectObjectsFromPoint(GPXLayer.java:818)
	at 
```
It is related to click on GPX functinality
