### ISSUE TITLE
No search results for some natural objects (Island, Islet, Fjord)

### ISSUE THREAD

**Issue by 532910** [osmandapp/OsmAnd#9467]
Search -> Categories -> Custom Search -> Natural -> Island + Islet + Fjord
Could not find anything: 500km

**Comment by vshcherb** [comment]
Natural objects are only searched if they have names

**Comment by 532910** [comment]
This is not true: it finds springs without names!

**Comment by vshcherb** [comment]
I tried this combination and it works for me. But certain type of pois are searchable only with name here you can see which are name-only
https://github.com/osmandapp/OsmAnd-resources/blob/master/poi/poi_types.xml#L3984

**Comment by 532910** [comment]
BTW, there no results for Saint-Petersburg's islands with names.

**Comment by vshcherb** [comment]
![image](https://user-images.githubusercontent.com/1042025/88200462-7622f180-cc46-11ea-93bd-88344fdb5fa9.png)
Can't reproduce it so far.

**Comment by 532910** [comment]
The original issue is about unnamed natural objects, isn't it?

**Comment by vshcherb** [comment]
Original issue:
```
Search -> Categories -> Custom Search -> Natural -> Island + Islet + Fjord
Could not find anything: 500km
```
Not reproducible island and islet (without names) are searchable

**Comment by 532910** [comment]
This issue is reproducable every time on 3 android phones with OsmAnd~ 3.7.4 from F-Droid.
Moreover OsmAnd on iPad also finds nothing.

**Comment by scaidermern** [comment]
> Original issue:
> 
> ```
> Search -> Categories -> Custom Search -> Natural -> Island + Islet + Fjord
> Could not find anything: 500km
> ```
> 
> Not reproducible island and islet (without names) are searchable

I can reproduce it. Searching for individual islands or islets works. Searching for the above combination via custom search doesn't work, the search result is empty.

The difference is the category. In custom search "Island" exists two times: Natural -> Island and Administrative -> Island. The first one has no search results, the second one works. Searching just for "Island" uses the second type (Administrative -> Island) and therefore works.

So it looks like Natural -> Island, Natural -> Islet and possibly Natural -> Fjord are broken.

**Comment by vshcherb** [comment]
thanks @scaidermern , this needs to be consolidated to one of the tags. _

**Comment by 532910** [comment]
Should it be reopened?

**Comment by xmd5a2** [comment]
There is no 2 different POI in different categories but only 1 with poi_reference instruction. Look like this is search issue.

**Comment by xmd5a2** [comment]
`natural=fjord` is deprecated. OSM now uses `natural=bay`+`bay=fjord`. This was the cause of no `fjord` results. Fjord support is fixed.

**Comment by xmd5a2** [comment]
Original issue
> Search -> Categories -> Custom Search -> Natural -> Island + Islet + Fjord
Could not find anything: 500km

is not reproducible now. Fjord will be searchable after next maps and application release.
