### ISSUE TITLE
Trip recording wakes screen

### ISSUE THREAD

**Issue by Vaaltuin** [osmandapp/Osmand#9482]
This is a real problem on Android for OsmAnd 3.7.4 and I have thoroughly investigated the circumstances. There are actually two problems:

    The recording plugin switches the screen on upon each saving of location data to the gpx file.
    Navigation instructions locks the screen on.

The following are the steps to verify the symptoms:
For both set the phone screen to time out after 15 seconds.

**Issue 1 Trip recording switches the screen on:**
For the profile of your choice set:

- Plugins/Trip recording/Settings/General logging interval: 15 sec
- Plugins/Trip recording/Settings/Logging minimum displacement : Not selected (To ensure that each position gets saved, so that you don't have to move around)

On the main screen press the manual recording gpx button and observe how the screen continuously times out, and then comes on upon each saving of a location point.

**Issue 2 Navigation instructions locks the screen on:**
For the profile of your choice set:

- Plugins/Trip recording/Disable
- Settings/General settings/Screen control/Screen timeout: enabled
- Settings/General settings/Screen control/Navigation instructions: Enable

If there is no navigation then the screen times out.
Start a navigation and the screen stays on.
Dismiss the navigation and the screen will time out again.

From my bit of investigation into coding the Android (In Xamarin on Visual Studio) I am sure that both the recording plugin and the Navigation instructions have the wrong set of WAKE_LOCK flags for the PowerManager.

**Comment by scaidermern** [comment]
Related to #9401?

**Comment by vshcherb** [comment]
Moved #9401
