### ISSUE TITLE
Wrong city or town shown on POIs addresses and search

### ISSUE THREAD

**Issue by lucumon** [osmandapp/OsmAnd#9491]
Hi!

In some POIs and streets of Santiago de Compostela, the capital city of Galicia, Spain, I have seen a bug that shows on the address the name of a town called Bertamiráns that is 10km away from Santiago. There are some screenshots:

![Screenshot_Cancelas](https://user-images.githubusercontent.com/24960275/87979520-7b5f2f80-cad2-11ea-91ce-fa26f396f17b.png)
On this screenshot, we can see that when searching a street in Santiago, we get one result with "Santiago de Compostela, Bertamiráns" (wrong) and a duplicated one with "Santiago de Compostela" (correct).

![Screenshot_Repsol](https://user-images.githubusercontent.com/24960275/87980591-28867780-cad4-11ea-8759-d22f403d7851.jpeg)
On this screenshot, we can see a fuel station in Santiago that gets Bertamiráns in its address.

![Screenshot_McDonalds](https://user-images.githubusercontent.com/24960275/87980852-84510080-cad4-11ea-97f6-4b82c1ff2703.jpeg)
On this screenshot, we can see a McDonalds next to the fuel station that doesn't suffer this issue.

![Screenshot_Milladoiro](https://user-images.githubusercontent.com/24960275/87980956-b95d5300-cad4-11ea-92d4-9ca11670f8fb.jpeg)
Here we can see that the same issue reproduces in a town near Santiago called Milladoiro, that is on the same municipality as Bertamiráns. Here I think that the problem exists on every POI in the town.

Since Santiago de Compostela has his own city boundary, I don't know why osmand keeps saying some POIs are in Bertamiráns.

Thank you in advance.

**Comment by lucumon** [comment]
### LOCATIONS

**Fuel station:** https://osm.org/way/555716061
**McDonald's:** https://osm.org/way/555716060
**Parking in Milladoiro:* https://osm.org/way/324682712


Also add that I'm using OSMAnd 3.7.4 with live maps

**Comment by vshcherb** [comment]
It looks like OSM data is not complete cause Bertamirans doesn't have city boundary probably this one is good city boundary - https://www.openstreetmap.org/way/79748599#map=15/42.8608/-8.6510

**Comment by lucumon** [comment]
That could be a suitable solution to this case, so I'm going to set a boundary as said but anyway, I don't think that osmand behavior when no boundary exists is correct. It's a nosense that inside a city with his own boundary, addresses are altered because a town without boundary that is not that close. Maybe I'm requesting something hard to solve because the way osmand is build (I really don't know if it is).

**Comment by vshcherb** [comment]
The way data is structured in OSM this is a correct behavior we've found in many countries, towns are located inside other city boundaries and have a meaning of "suburb" / "district" of another city. 
Anyway the best practice of OSM is always to have city/village boundaries in order to calculate whole administrative address structure.

**Comment by lucumon** [comment]
When I opened this issue, we had the following boundaries:

- Santiago's city boundary: https://www.openstreetmap.org/relation/3203720

- Santiago's municipality boundary: https://www.openstreetmap.org/relation/3203720

- Ames's municipality boundary (Bertamiráns as admin_centre): https://www.openstreetmap.org/relation/342629

Since affected POIs were inside a city boundary and a municipality boundary different to Bertamiráns one, I don't think that the issue was caused because of Bertamiráns not having a boundary. Anyway, I created an administrative boundary for Bertamiráns https://www.openstreetmap.org/relation/11489614 and, surprise, the issue persists.
After some research, I have noticed that affected POIs aren't only in Santiago's municipality, but they are all around Santiago's "comarca", that is surrounded by this boundary https://www.openstreetmap.org/relation/9098132#map=11/42.9194/-8.5811. Here, Ames shares a boundary with Santiago. I don't know what is happening but I think that [Map data issue] is an incorrect label for this issue, so I'm removing it.

Thank you in advance, and sorry for taking so long to answer.


P.S.: In Spain, a "comarca" is a territorial division formed by a group of municipalities.

**Comment by lucumon** [comment]
After a time, I reviewed the issue again, and it seems solved without further work. 
Could it be that it is an error when compiling the live maps?

This particular case is solved, but I'm not closing the issue because that behaviour was very strange and may need some more research.

**Comment by vshcherb** [comment]
Nope the issue will be closed cause all routing / address  issues should be fixed and investigated separately
