### ISSUE TITLE
Navigation issue: U-turn on a crossroad

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd#9499]
The issue occurs at 42.43515/-96.36954 when building a route from South Lewis Boulevard to Singing Hills Boulevard. 
from: 42.44748° N, 96.37211° W
to: 42.43531° N, 96.36908° W
![image](https://user-images.githubusercontent.com/50198677/88048729-88286580-cb5c-11ea-9938-7dad8090d713.png)

**Comment by lucumon** [comment]
That seems a mapping issue, try to put a turn restriction there.

**Comment by scaidermern** [comment]
Though unclear why OsmAnd just doesn't take a turn at the previous intersection shown at the top of the screenshot, similar to [here](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=42.43635%2C-96.37036%3B42.43543%2C-96.36843).

**Comment by lucumon** [comment]
> Though unclear why OsmAnd just doesn't take a turn at the previous intersection shown at the top of the screenshot, similar to [here](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=42.43635%2C-96.37036%3B42.43543%2C-96.36843).

I thought that this turn was not possible

**Comment by kylegates** [comment]
It may have something to do with the rail crossing adding a penalty to that segment.

**Comment by alisa911** [comment]
Reason for incorrect routing in "penalty_transition". On this road section, "trunk" is changed to "secondary" twice. A small reduction this penalty for  "secondary" roads solves this issue.

https://github.com/osmandapp/OsmAnd-resources/pull/677
