### ISSUE TITLE
Public transport issue: route cannot be calculated

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#9504]
The issue occurs in Germany, Bonn

From: Public transport stop Konrad Adenauer Patz (50.7396508,7.1182472)
To: Public transport stop Hangelar Ost (50.7637883,7.1716887)
![image](https://user-images.githubusercontent.com/50198677/88163219-00556080-cc1b-11ea-8e2b-ac5444737c2f.png)

Building the route with other navigation profiles works, except for the public transport profile.

**Comment by MadWasp79** [comment]
![image](https://user-images.githubusercontent.com/13146346/88206019-4bd93000-cc56-11ea-9d7b-b525b4a147a3.png)
Works ok in nightly. Already fixed
