### ISSUE TITLE
Incorrect suggested name for profile

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#9512]
Steps to reproduce:
- Create an app profile and name it with only numbers without any spaces e. g. "123"
- Create a new profile based on the created above
Auto suggested name will be "124" instead of "123 1".

**Comment by vshcherb** [comment]
Why incorrect sounds logical.
"Route 1" -> "Route 2" (correct)
"Route 123" -> "Route 124" (correct)

Otherwise it will be always "Route 1" -> "Route 11" -> "Route 111" (incorrect).
