### ISSUE TITLE
Have a separate icon for excrement bag dispenser

### ISSUE THREAD

**Issue by NotSoImportant** [osmandapp/OsmAnd#9522]
Hi,
currrently genric vending_machine icon is used - which is not very accurate as well as not intuitive for excrement bag dispenser.
(At least all occurances I know) have fee=no and are no machine, but a simple dispenser.
Please introduce an own icon.
https://wiki.openstreetmap.org/wiki/Tag:vending%3Dexcrement_bags

**Comment by xmd5a2** [comment]
Separate icon is already used. Do you mean icon on the map?
![Screenshot_2020-09-10-16-11-53-952_net osmand plus](https://user-images.githubusercontent.com/5829014/92734107-eaddf680-f380-11ea-9911-fadf9d9e8965.jpg)

**Comment by NotSoImportant** [comment]
Yes I mean the redered items on the map
