### ISSUE TITLE
Render beehives (and other nodes of unrecognized type)

### ISSUE THREAD

**Issue by NotSoImportant** [osmandapp/OsmAnd#9523]
https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dbeehive (state: proposal)

Currently there are >37k nodes in the database with this tag. IMHO makes sense to render them.
**Currently they don't show up in the map at all.**

Is there a general concept on how to deal with nodes/ways of unknown type? Can/Could they be rendered in a generic way? Maybe after applying a setting?

**Comment by NotSoImportant** [comment]
Please also add a preset to be able to create such pois.

**Comment by NotSoImportant** [comment]
Hi, with nightly OsmAnd 3.7.0#27633d, released 2020-09-15:
- I can see beehive exists as a preset
- I can see behive exists as a poi category
- however beehives are not rendered as part of the map
Is it because the maps need to be published separately?

**Comment by xmd5a2** [comment]
Yes, you need new october maps
