### ISSUE TITLE
Unify all apostrophe symbols

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/Osmand#9529]
The different keyboard can show different apostrophe symbols, that occurs empty search results.
For example, try to search "chemin de l'her" or "chemin de l’her" around Malmedy in Belgium https://osmand.net/go?lat=50.426537&lon=6.027605&z=17.

![Group 3](https://user-images.githubusercontent.com/9365308/88656941-c3391480-d0d9-11ea-90b5-d7eee99e03f6.png)

**Comment by sonora** [comment]
Yet another use case for search string normalization ;)

**Comment by vshcherb** [comment]
We already do it for some symbols and characters for example we delete conjunctions from string: a, the, der, den, ...

The trick we need to normalize on both sides, on server side and on client side
