### ISSUE TITLE
Navigation issue: route ends on the road nearby

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#9534]
Start: 48.99030/9.40930
End: 48.81622/9.29908
With the updated map, OsmAnd builds the wrong route
![image](https://user-images.githubusercontent.com/50198677/88775476-6c8d1280-d18d-11ea-8fa8-267e72a7377c.png)

Changing navigation settings does not help

**Comment by scaidermern** [comment]
Similar to #7520 and #5395.
