### ISSUE TITLE
Navigation issue: straight line instead of the detour

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#9535]
The issue occurs from: 50.749969, 40.049085
to: 50.157927, 40.428726
![image](https://user-images.githubusercontent.com/50198677/88784142-5df82880-d198-11ea-85c0-0789f4bcd4c2.png)

**Comment by scaidermern** [comment]
You are on a non-routable construction road. OsmAnd chooses the shortest distance to the next routable road. The behavior is as expected.
