### ISSUE TITLE
Duplicate categories in search results

### ISSUE THREAD

**Issue by rrooggiieerr** [osmandapp/OsmAnd#9541]
When searching for categories, they are shown multiple times, while only the last one works.

See Issue #6821 which I still face when using 3.7.4

Interestingly it does not seem to happen when my phone has restarted, but is introduced gradually when I'm using Osmand over a longer time. First showing a second duplicate, some time later a third duplicate. I have seen up to 4 duplicates of the category

**Comment by vshcherb** [comment]
Could you please share a screenshot to see what are the details of the search

**Comment by rrooggiieerr** [comment]
You can find a screenshot in the mentioned issue #6821

**Comment by vshcherb** [comment]
Issue was not reproduced so far
