### ISSUE TITLE
Profile settings UI issue

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/OsmAnd#9550]
Steps to reproduce:

- Open the settings screen for a disabled profile (the screen with general settings, nav settings, configure map etc.)
- Select Configure map (or screen) settings
- Go back to the settings screen

Result: the top switch will show that the profile is still disabled while the profile is, in fact, enabled.

**Comment by Hedaja** [comment]
I can confirm this in 3.7.4.
Going back from the "configure map" menu to "configure profile" will have the text say on but the slider show off.
GOing further back to "settings" the slider is correct again, as is when you reenter the "configure profile"

![photo_2020-08-15_18-10-10](https://user-images.githubusercontent.com/693781/90316453-9e8acc80-df22-11ea-9f7e-b546398c6966.jpg)
