### ISSUE TITLE
uploaded POIs are duplicated (intermittently)

### ISSUE THREAD

**Issue by H2172** [osmandapp/OsmAnd#9566]
Version: OsmAnd~ 3.7.4

Recently, I noticed some of my uploaded POIs were duplicated.
It seems the duplication happened withing the same changeset (the same node is added twice within the same changeset created by Osmand).

Examples:
https://www.openstreetmap.org/changeset/88726363 (wrong) -- see screenshot below
https://www.openstreetmap.org/changeset/88810750 (wrong)

The issue appears to be **intermittent**, as some other similar uploads around the same time didn't have the same issue, examples:
https://www.openstreetmap.org/changeset/88744698 (correct)
https://www.openstreetmap.org/changeset/88726582 (correct)

![Screen Shot 2020-08-03 at 17 57 01](https://user-images.githubusercontent.com/24855951/89202132-c8eb9a00-d5b2-11ea-96f7-34eaaed7f17a.png)

**Comment by vshcherb** [comment]
No complains since then, so I will think that issue is solved with 3.8
