### ISSUE TITLE
Local cycle network indicated by tag does not appear

### ISSUE THREAD

**Issue by Athoss9** [osmandapp/Osmand#9571]
Android version: 9
OsmAnd version: OsmAnd+ 3.7.4 Beta
Map: Hungary 2020-08-01
OsmAnd Live: 2020-08-05 09:06

When I enable cycle routes, OsmAnd used to render cycle networks indicated by the tag lcn=yes. After the map update only cycling routes mapped as relations are rendered.

June map:
![Screenshot_20200805-100244](https://user-images.githubusercontent.com/28255870/89387756-3b6b8f80-d703-11ea-9361-cab8e162a90b.png)

August map:
![Screenshot_20200805-100248](https://user-images.githubusercontent.com/28255870/89387777-46bebb00-d703-11ea-928b-d736db974877.png)

**Comment by vshcherb** [comment]
Map was regenerated tonight, you can delete and download it again. Please follow this discussion in https://t.me/OsmAndMaps
