### ISSUE TITLE
[Feature request]  license key

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#9572]
Many users ask to implement a license key for those who switched from Google Play to the Apple Store and vice versa. This would let them use OsmAnd on both platforms.

**Comment by vshcherb** [comment]
This is not supported by Google Play and App Store, it is a limitation of Google vs Apple

**Comment by bascisco** [comment]
Hello OSMAND developers. Why is it not feasible to have a license key for those who switch or i.e. even work cross platform? Also we as cycling family doing tours (even more in COVID-19 times).  Other apps like Spotify, Citymaps2Go and others have a license key or mechanism to work cross platforms and even a family account/subscription. I.e. then you can share easily routes between each others.

Brgds, Bas.

**Comment by vshcherb** [comment]
This is not compliant with App Store / Google Play licenses for Digital product distribution. For products like Spotify, Youtube they are just big to be banned though you've probably heard about Netflix subscription on App Store. 

Anyway products you've mentioned introduced it years ago and things has changed on App Stores.
