### ISSUE TITLE
Wrong route logic (France map)

### ISSUE THREAD

**Issue by ana-dav** [osmandapp/OsmAnd#9578]
By the following coordinates, the road leads to the wrong way. 
Please see the screenshots attached. 
From:
Avenue des Platanes, 34970 Lattes, France
Latitude: 43.584384 | Longitude: 3.926063

To:
Clarensac, Nîmes, France
Latitude: 43.82669 | Longitude: 4.217654
![Capture d’écran 2020-08-05 à 14 54 28](https://user-images.githubusercontent.com/62652223/89521792-d38f7480-d7e8-11ea-93a7-c70fdc211ad5.jpg)
![Capture d’écran 2020-08-05 à 14 54 43](https://user-images.githubusercontent.com/62652223/89521795-d4c0a180-d7e8-11ea-8506-deaffe3f8fd9.jpg)

**Comment by pebogufi** [comment]
See also https://github.com/osmandapp/Osmand/issues/9389

**Comment by tuttiquantic** [comment]
Hi,

I would share that with the august map update that routing problem doesn't occur.

HTH

**Comment by vshcherb** [comment]
Great
