### ISSUE TITLE
House address missing

### ISSUE THREAD

**Issue by ana-dav** [osmandapp/OsmAnd#9581]
House address missing
On the openstreetmap they are presented
Coordinates:
https://www.openstreetmap.org/#map=18/37.84458/23.77336

Screenshots:
![Openstreetmap-Greece](https://user-images.githubusercontent.com/62652223/89533526-3a6a5900-d7fc-11ea-9733-91451293ef2f.jpg)
![Osmand-Greece](https://user-images.githubusercontent.com/62652223/89533530-3b9b8600-d7fc-11ea-8659-03b99f9eae49.jpg)

**Comment by scaidermern** [comment]
Any chance to regenerate August maps with house numbers displayed? This is a quite useful feature.

**Comment by vshcherb** [comment]
Fixed maps are regenerating, probably will take 5-6 days. Please remove & redownload map after that (it will be still marked as 1 Aug).

**Comment by scaidermern** [comment]
> Fixed maps are regenerating, probably will take 5-6 days. Please remove & redownload map after that (it will be still marked as 1 Aug).

Could you give us a feedback when map generation has finished? Since there won't be any notice from within the app if i understand correctly.

**Comment by vshcherb** [comment]
Europe is done, Asia almost, other countries probably mid next week
