### ISSUE TITLE
Show photos from Wikimedia Commons

### ISSUE THREAD

**Issue by pyrog** [osmandapp/OsmAnd#9585]
See https://github.com/osmandapp/Osmand/issues/7131#issuecomment-507119815

I don't see `wikimedia_commons` picture for theses POI:
* https://www.openstreetmap.org/node/1572748364
* https://www.openstreetmap.org/node/7296733702 (display only `mapillary` pictures)
* https://www.openstreetmap.org/node/494251394 (display only `image` and `mapillary` pictures)

**Comment by Adamant36** [comment]
I'm not sure how it's done on OsmAnd's side, but I know that in Wikimedia Commons a lot of photos don't have coordinates attached to them yet. Perhaps that would help. Although, I don't really know what I'm talking about. So, probably not 😆

**Comment by pyrog** [comment]
> I know that in Wikimedia Commons a lot of photos don't have coordinates attached to them yet

It doesn't matter:
The OSM object have is own coordinates and an OSM contributor have associated one (or more) photos with it 😉

What you describe is "discovering" Wikimedia Commons pictures near/around an OSM object.
See [wikishootme](https://wikishootme.toolforge.org/#lat=53.17519949167912&lng=6.97307825088501&zoom=17&layers=commons,flickr,mixnmatch,mnm_lc,wikidata_image,wikipedia) that query Commons, Wikidata…

**Comment by Adamant36** [comment]
With Wikimedia Commons how to does it know which is the correct or best image of a certain location to use though?

**Comment by pyrog** [comment]
Wikimedia Commons don't know. The human (OSM contributor) know 😉 

Ok, it's possible to query Commons by coordinates, categories i.e [Defibrillators in England](https://commons.wikimedia.org/wiki/Category:Defibrillators_in_England), [Quality images](https://commons.wikimedia.org/wiki/Category:Quality_images)…

**Comment by pyrog** [comment]
thank you 😃
