### ISSUE TITLE
Wish: new switch for exit-numbers

### ISSUE THREAD

**Issue by Spielmops** [osmandapp/OsmAnd#9592]
In Gemany we do not use exit-numbers on motorways. It irritates when such numbers are announced. Why not introduce a switch for it. Exactly as well as for street names,

Spielmops

**Comment by pebogufi** [comment]
if they are announced, it is obvious, that they exist. So they ARE used.

**Comment by Spielmops** [comment]
Not obvious: exit numbers exist, but they are not shown on signs. So what should I do with an announced number, if I can not compare?

Spielmops

**Comment by vshcherb** [comment]
In Germany they are shown and extremely important. They are very similar to NL and helps a lot for complex junctions
![image](https://user-images.githubusercontent.com/1042025/90316381-21f7ee00-df22-11ea-9027-cc9b36c38e23.png)
![image](https://user-images.githubusercontent.com/1042025/90316392-3dfb8f80-df22-11ea-8aa6-4595603ac453.png)

**Comment by pebogufi** [comment]
@vshcherb The numbers you see in the screenshot are NOT exit numbers.
31 and 311 refers to "B 31" and "B 311" which are primary roads = national roads, (DE:Bundesstrasse). The signalation tells you that you have a connection to B 31 or B 311 when leaving here the motorway. 
"U 25" is the name of a diviation (DE:Umleitung) which you are recommended to use if the motorway has a taffic jam.

**Comment by vshcherb** [comment]
May be I'm wrong, in NL is quite important info (afrit 10)
![image](https://user-images.githubusercontent.com/1042025/90317112-6df96180-df27-11ea-8ed1-74686723c623.png)

**Comment by Spielmops** [comment]
Street names are very important and they are used in every country. Nevertheless there is a switch in Osmand to switch off the announcement of street names. So why not also for exit numbers?

Spielmops

**Comment by vshcherb** [comment]
Yes we need to introduce it then

**Comment by polarbearing** [comment]
> In Gemany we do not use exit-numbers on motorways.

Sorry but this is utter nonsense. Exit numbers are an important element of long-range planning and driving. They existed already in the ancient times of printed road atlases.  I was very happy to see that implemented eventually as in #1347 . 

It remains unclear to me if @Spielmops wants a switch for visual or voice announcements. If others feel a need for such a switch as well it might be combined with switching the street name, thus no extra switch in the UI. 

Exit number example below, from Berliner Ring A10. 

![Screenshot 2020-10-04 at 22 13 59](https://user-images.githubusercontent.com/8266355/95026288-95032280-0690-11eb-86c8-c6a86a666a5d.png)
![Screenshot 2020-10-04 at 22 13 50](https://user-images.githubusercontent.com/8266355/95026293-99c7d680-0690-11eb-83f1-1b951999bf4d.png)
(images based on mapillary-upload by grobin (cc), taken 2020-08-08)

**Comment by scaidermern** [comment]
The usage of exit numbers in Germany varies a lot. Some motorways do show exit numbers, others don't. I think their importance declined over the time. Exit names and destinations became more important than exit numbers.

**Comment by scaidermern** [comment]
Can we merge this with #8550?

**Comment by vshcherb** [comment]
But the info given about exits is now confusing. It gives the exit number and the exit name. From my personal experience in germany and luxembourg there is no sign which displays the name of an exit (i'm still wondering where the osm guys got this information). So giving the exit name is not helpful at all. Sadly, if an exit number/name exists, the destination of that exit is omitted, but the destination is a much more useful information for the driver.

So could you please change voice and top bar information to something like
$TurnInfo $ExitNumber $DestinationRoad(s) >> $Destination

**Comment by scaidermern** [comment]
Right, could be that there are no exit names in Germany at all. The destination(s) is the really important information.

**Comment by vshcherb** [comment]
I don't what's exit name, the change didn't remove destination, so it should announce now 2 things exit number & destination

**Comment by scaidermern** [comment]
Sometimes OsmAnd announces the exit number and the name of the freeway interchange (German: Autobahnkreuz) which isn't helpful at all since the name of the interchange has nothing to do with the exit. I'm not sure if this is a tagging error. However this happens quite often, so I doubt that the tagging is wrong. Also I'm quite sure this didn't happen in the past (OsmAnd <= 3.7).

**Comment by Spielmops** [comment]
It's me, the thread-opener again:

The discussion gets away of the problem. It is not important to use exit numbers or destinations, because all announcements beside "use this exit" are distracting. I am on the highway and have to watch out for the traffic. What should I then do with an exit number? Does it exist, does it not exist? Where is the number? Is that the right number? And when destinations are announced: is that my destination? Isn't it what then? Is this going in the right direction, should I leave  the motorway now or not?

In the vast majority of cases there is a crossroads behind the actual exit where destinations are signposted and then the destination announcements are important. Not on the motorway.

In Osmand there is a switch for the announcement of street-names, why not add a switch for exit-nummbers/-destinations?

**Comment by scaidermern** [comment]
> In the vast majority of cases there is a crossroads behind the actual exit where destinations are signposted and then the destination announcements are important. Not on the motorway.

I disagree. On larger motorway junctions there are two or more exits right behind each other. In this case it is important to know which exit to take. Therefore the announcements have to match the road signs, otherwise they are worthless. If the road signs show destination names then OsmAnd should announce them (both visually and audibly). Of course this can be made configurable, I don't disagree on that.

**Comment by Spielmops** [comment]
During the last 4 years I made journeys of about total 50.000km. How did I arrive, where I wanted to without the navigation-announcement of exit-numbers and destinations? ;-)

Spielmops

**Comment by pebogufi** [comment]
You are absolut superior intelligent, that is unquestionable !
:-)

**Comment by Spielmops** [comment]
Sorry, no! I just followed the navigation announces: take this exit, turn right, follow for x km, and so on. Without any destinations. And it was less distracting than now.

**Comment by pebogufi** [comment]
To return to the reported problem. 
Looking at the images, it is obvious, that there are regions ("Bundesländer") in Germany which use exit numbers, and other which do not use it.
I support the idea, that it would be nice to have them displayed/announced optional with a switch.

**Comment by sonora** [comment]
Just trying to help the off-topic phantom discussion here with some information. All motorway junctions im Germany carry one unique name, which is listed in the highway authority official documention and the rescue atlas. That's what by OSM guidance is reflected in tag  'name'. In the real world it is prominently displayed as the only string announcing the exit at 1000m out, while the list of exit destinations, on the other hand, is posted on the 500m sign.

Please note that it is quite easy to mis-interpret the exit name for a destination, as of course that's how names are usually selected, a prominent destination in the vicinity. That's also why names usually carry more significance and brevity than the list of destinations, and hence why I had given them priority over possibly lengthy destination lists. (Not sure if we reverted this 10 year old behavior recently?)

For more detail and a picture of the typical signing see https://de.m.wikipedia.org/wiki/Anschlussstelle_(Autobahn).

In any case the system is rather similar in many European countries, and e.g. in the US. There the signing conventions are further out (1 mile, half mile, quarter mile). In my original design years ago I had tried to make sure announcements always sound **before** passing the signage, but it seems over time users felt they should have more coherence with the actual turns by being closer (in particular in non-motorway situations), so some prompts now in deed end up **behind** motorway signs in several countries.

I am not convinced moving them back out  again would meet the majority of users' taste. After all we always have the pre-announcements to alert drivers about 1500m before upcoming maneuvers.

Regarding exit refs: **Every** motorway junction in Germany, as well as Interstate exit in the US, carries a ref number (and I know of not a single one where that is not prominently displayed in the signage, in Germany at 1000m and at 300m). But it is true that they are heavily used by convention in many countries, less so in other countries. So yes, if we accept complicating the app for more customizeability, we could have a switch. On the other hand the numbers, if tagged in OSM are usually used, and even if less conventional, we only annouce them max twice and numbers are often short. Announcing them means erring on the safe side for the vast majority of users who do not want to work through the 6 dozen settings and options OsmAnd has before getting the app into a state which makes it useful.

**Comment by scaidermern** [comment]
> [...] That's what by OSM guidance is reflected in tag 'name'. In the real world it is prominently displayed as the only string announcing the exit at 1000m out, while the list of exit destinations, on the other hand, is posted on the 500m sign.

And exactly this is the problem in my opinion. The name is just posted once 1000m before the exit (sometimes also 2000m before). It is easy to miss, especially on crowded motorways and if you have never been there before. The list of destinations, however, is posted repeatedly (two or three times) and is thus clearly more helpful. I'm not against announcing or showing the exit _name_. But the priority should be at announcing and showing the list of destinations. If the driver missed the sign with the exit _name_ and OsmAnd keeps repeating the _name_ while the driver only sees signs with _destinations_, this is not helpful at all. In such a situation the driver then has to look several seconds at the map in order to choose which lane to take, which can become quite dangerous.

**Comment by sonora** [comment]
Hey @scaidermern , I have drafted a way forward here https://github.com/osmandapp/OsmAnd/issues/10718#issuecomment-770719234, I think that issue task about it mostly.

Yes, the 2000 m practice in German is for Highway Intersections (as opposed to highway exits) in Germany. Different signing practice in different countries is what makes this so difficult. Practice on trunk roads may once again be largely different.

PS: When testing, please make sure to use the standard German TTS voice, as the "Casual" version e.g. leaves out the 1500 m (PREPARE_TURN) prompts: there is some tendency in our user base to go for even more brevity, cut lengthy announcements or kill some entirely, in particular the far out ones where there would typically still be more time to announce longer stuff..

**Comment by Spielmops** [comment]
> Announcing them means erring on the safe side for the vast majority of users who do not want to work through the 6 dozen settings and options OsmAnd has before getting the app into a state which makes it useful.

Why is this complicated and difficult to handle by the user, if there is a similar switch for street-names? If you think this way, you should propose a light-version of Osmand ...
Spielmops

**Comment by sonora** [comment]
I am not entirely against it.

But since you asked: Any swtch or setting we have to be useful requires a user to understand there may be a switch somewhere in the first place to tweak a particular situation, locate it, understand it, and know what a good value or adjustment would be for all use case likely encounteted. As a side effect, all switches/settings require coding and software maintenance, create bugs, cause support cases, and every single one is confession that the software cannot intelligently resolve a situation without user input. 95% of our settings and switches will never be touched by 95% of our users. But their presernce contributes to ratings of OsmAnd being clumsy and complex.

The art of making a great app is keeping it as simple as possible and providing just the right level of customizability which will be appreciated by the majority of users.

 Where things can be automated intelligently instead of relying on user input or settings, this is often preferable.

**Comment by vshcherb** [comment]
Well, we should display it. As a nederland person driving in Germany, I used this exit-numbers in Germany a lot. I checked, they are present and used them. Unfortunately they are showed up only 1000 meter before and now just before the turn (100-200m)... It's strange.

I think german people don't use it cause it's newly introduced but it's a must have with more & more complicated junctions. I think switch to disable is fine and we will need to have it this release but we need to get it working by default.

**Comment by vshcherb** [comment]
About switches, it looks like a region-based specific when local people don't use local features ;-) but other people would use it. So we should have not a switch but a explanatory multi-selection dialog:
- Don't pronounce streets (for example non-tts is used)
- Pronounce street names 
- Pronounce refs
- Pronounce destinations
- Pronounce exit-numbers

**Comment by vshcherb** [comment]
![image](https://user-images.githubusercontent.com/1042025/113012409-07097f80-917b-11eb-8b5e-0105a830e7a5.png)

**Comment by dmpr0** [comment]
**We need to:**
1. Rearrange items in the "Voice prompts" menu.
2. Divide it into groups: "Announce", "User points", "Speed limit", 'Options", "Output".
3. Rename current "Sped limit" switch to "Announce when exceeded"
4. Add separate switch to control "Exit number"

**Comment by Spielmops** [comment]
Installed version 4 and found the switch I wished for: Thanks a lot! 
:-)
Spielmops
