### ISSUE TITLE
Route name should not be rendered on endpoint / cycle node

### ISSUE THREAD

**Issue by matthijskooijman** [osmandapp/OsmAnd#9598]
When cycle routes and/or cycle node routes are enabled, nodes are rendered with their number, and the routes are rendered with their name (or ref, probably, with the from and to nodes, e.g. 57-99). However, sometimes, the route ref is rendered not on the route, but on the start or endpoint. For example, the `57-99` label below is rendered on top of node 57:

![image](https://user-images.githubusercontent.com/194491/89739594-1cae2580-da82-11ea-933f-8cc99431d58c.png)

This is here: https://www.openstreetmap.org/node/47704110#map=17/52.97803/6.02682&layers=N

For especially node network routes, this is (AFAICS) always suboptimal, because:
 - The starting point for a route is always the starting point for multiple routes, so it is unclear which of the routes the label refers to (you can figure it out through elimination in the screenshot above, but that's not so useful and does not always work, e.g. when zooming in further).
 - The route label now prevents display of the node ref, which I think would be more important to render. You can still deduce the node number from the common number in all three routes, but that is cumbersome and again does not always work.

It seems that zooming in further does not resolve this particular situation, zooming out does (though the node number is still not shown then).

A simple fix here could be to give node refs a higher priority than (node network) route labels. I'm not sure if that would cause the route label to be simply hidden or relocated. If hidden, then maybe the route label placement handling could be changed to always keep clear of the end of a route (e.g. keep some zoom-level dependent distance from the route starting point).

I'm running OsmAnd nightly version 3.7.4#27376d, 2020-08-06, on Android 9 on Galaxy Tab A (8.0", 2019), with offline maps (Netherlands, July 1st 2020).

**Comment by xmd5a2** [comment]
Fixed 
![Screenshot from 2020-08-26 15-08-58](https://user-images.githubusercontent.com/5829014/91301761-1b813600-e7ae-11ea-9ed7-835f636a0c60.png)

**Comment by matthijskooijman** [comment]
Cool! I think this is a side effect of https://github.com/osmandapp/OsmAnd-resources/commit/8d58e9bad376a4be95df5cfdd73d4078534f29f8? Or was this fixed somewhere else?

**Comment by xmd5a2** [comment]
Yes, it was fixed in this commit
