### ISSUE TITLE
In map updates of 1st Aug 2020 house numbers (addresses) are no longer displayed

### ISSUE THREAD

**Issue by aceman444** [osmandapp/OsmAnd#9599]
After map updates of 1st Aug 2020 house numbers (addresses) are no longer displayed, in OsmAnd style nor Topo style.
This is with OsmAnd 3.7.4, no update of app was made by me in that time frame (around 1st Aug) and the setting "hide house numbers" in the map settings is DISABLED.

So something went wrong when generating the new obf files.
Also, when searching for addresses they exist fine, but AFAIK there is a separate database in the obf file for address search.

**Comment by scaidermern** [comment]
Probably the same issue as #9581.

**Comment by aceman444** [comment]
Yes, seems to be the same, I just have more details and pinpointing of when it regressed.

**Comment by vshcherb** [comment]
Fixed maps are regenerating, probably will take 5-6 days. Please remove & redownload map after that (it will be still marked as 1 Aug).

**Comment by aceman444** [comment]
Thanks. So what is the fix? Where is the link to the commit?

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/commit/43db22fa798f1418cdd0ad318e1c9a0b8a1bea49

**Comment by aceman444** [comment]
Thanks, even though the patch code does not mention addresses in any way.
