### ISSUE TITLE
Reset to default application mode after stop navigation

### ISSUE THREAD

**Issue by ehermann** [osmandapp/OsmAnd#9600]
Hello,
Is there a reason to call `	osmandSettings.APPLICATION_MODE.set(osmandSettings.DEFAULT_APPLICATION_MODE.get());` on
OsmandApplication.stopNavigation, or it's a bug?
It's quite annoying to have the application mode reset to the default after every navigation stop instead of staying at the current mode.

**Comment by scaidermern** [comment]
Duplicate of #9372.

**Comment by vshcherb** [comment]
You can change default of course and we are collecting feedback for #9372 to make this optional

**Comment by andrzej-gmt** [comment]
I find changing profile after stop of navigation confusing and annoying. IMHO reasonable would be to reset navigation mode according to current profile.
