### ISSUE TITLE
Flooding Taganrog

### ISSUE THREAD

**Issue by ana-dav** [osmandapp/OsmAnd#9602]
Maps: Taganrog. Flooding issue. Coordinates - 47.2066885, 38.9520652
OpenStreetMap screenshot:
![Screenshot from 2020-08-10 11-44-06](https://user-images.githubusercontent.com/62652223/89765539-32adfb80-daff-11ea-9301-d1f0c4eaef51.png)
OsmAnd screenshot:
![Screenshot_2020-08-07-19-10-10-200_net osmand](https://user-images.githubusercontent.com/62652223/89765601-4f4a3380-daff-11ea-9137-37a0e6aaa487.jpg)

**Comment by vshcherb** [comment]
![image](https://user-images.githubusercontent.com/1042025/90521389-c0769000-e16a-11ea-92ee-dad2de4f8d23.png)

**Comment by xmd5a2** [comment]
Not reproducible with latest maps. Please ensure that all surrounding maps are updated. Issue is reproducible with august Russia_rostovskaya_asia_2.obf and june Ukraine_zaporizhzhya_europe_2.obf
