### ISSUE TITLE
on display many tracks display is cluttered with icons

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#9614]
on new display of tracks, each has a icon for start end end.
When i show many tracks this clutters the map, so that i don't see the track itself any more. On display of a single track, it is very nice.
Solution:
on setting we find  a new "appearance" where i can switch on/off direction arrows. 
Please add a setting for show/hide theese start/end icons.
app version: current

![Screenshot_20200811-160604_OsmAnd~~01](https://user-images.githubusercontent.com/18628183/89908652-a6263a80-dbdd-11ea-9d2e-21ffe98ebd5c.jpg)

**Comment by vshcherb** [comment]
We need to hide start/finish if icon is bigger than track itself (so we need somehow to calculate visible bbox of the track)

**Comment by pebogufi** [comment]
Why not let the user decide with a option in appearance. Easier to code for you and easier to understand for the user when visible or not if it was his decission.

**Comment by pebogufi** [comment]
Now it is great ! Thanks a lot.
Peter
