### ISSUE TITLE
[Future request] set up target SDK to 30

### ISSUE THREAD

**Issue by ana-dav** [osmandapp/OsmAnd#9626]
To have better compatibility with Android 11 devices.
Example: better visibility of OsmAnd-Package to other apps

**Comment by vshcherb** [comment]
Reference https://github.com/osmandapp/OsmAnd/issues/8686

**Comment by vshcherb** [comment]
SAF migration needs to be done first

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/7045

**Comment by Chumva** [comment]
This should be added here - https://github.com/osmandapp/OsmAnd/pull/12866.
