### ISSUE TITLE
Travel guides - switch of points and illustration of active city/area and illustraition of active cities and history

### ISSUE THREAD

**Issue by Aiurek** [osmandapp/OsmAnd#9631]
It's unclear how to switch off the travel guide points after you've switched them on - mby add a button while active?
If you go back to the guides, enter the city name, select points and turn off the "show on map" options, these points will be removed from the map, but I would say that this should be much easier.
You also have to re-search for the respective city, since it's not displayed after opening travel guides (although the city points are active). There isn't a search history either and therefore you've to type the city name again.
Maybe cities with active (show on map) points should be illustrated at the top, when opening travel guides? + an easy way to access the travel guides search history alongside the suggestions based on the current geo location?

![doc-2020-08-13-15-23-40gif](https://user-images.githubusercontent.com/27865200/90145979-cf330080-dd80-11ea-8db7-f4d92a86f60d.gif)

**Comment by vshcherb** [comment]
Yes we have plans to change that interaction

**Comment by vshcherb** [comment]
Fixed now
