### ISSUE TITLE
Add favorite: show hidden folders in the category list dialog

### ISSUE THREAD

**Issue by ana-dav** [osmandapp/OsmAnd#9636]
While adding a favorite point, if the category folder was hidden, you can see it in the add favorite horizontal scrolling menu, but not in the 'choose category' pop-up. Please see the screenshots attached.

![1](https://user-images.githubusercontent.com/62652223/90242113-14b10580-de35-11ea-9680-2bf8d1906251.png)
![2](https://user-images.githubusercontent.com/62652223/90242118-15499c00-de35-11ea-851f-e15640a7c399.png)
![3](https://user-images.githubusercontent.com/62652223/90242121-15e23280-de35-11ea-8a74-ce9efb557667.png)

**Comment by dmpr0** [comment]
Review:
- [ ] Select hidden group form the list, additional text that informs user about hidden group doesn't show up (it shows up when selecting hidden group from the horizontal slider.
