### ISSUE TITLE
importing gpx's without meta data results in error

### ISSUE THREAD

**Issue by eddriesen** [osmandapp/OsmAnd#9642]
![Screenshot_20200811-120850](https://user-images.githubusercontent.com/29610617/90271889-d0396000-de5c-11ea-9429-1bfc58e9dd02.png)
 See gpx avontour.gpx, whereas avontour-2.gpx will work , downloadable at https://omts.mooo.com:8091/nextcloud/index.php/s/B4YCL7Wo7kk9EMR
  
Lovin the app since forever! (And subbed)

**Comment by androiddevkotlin** [comment]
I can't replicate this bug. A similarly issue was discussed [here](https://github.com/osmandapp/Osmand/issues/1559) a few years ago.
