### ISSUE TITLE
Support 'oneway:foot=yes' for footways

### ISSUE THREAD

**Issue by ArjanOnwezen** [osmandapp/OsmAnd#9645]
Plan a route doesn't respect one way foot paths, in case of walking type.
It does work fine for cycling.

**Comment by vshcherb** [comment]
It is not clear if it should respect in many areas the roads are oneway but it is possible to the other way as well. We need to filter that somehow. As of today we can't block all oneway roads but we need to find additional tag combination to block

**Comment by TO-92** [comment]
By convention "oneway" with no further detail applies to vehicles only, even on footways. Like here, for example: https://www.openstreetmap.org/way/697413230 - it would be wrong to restrict pedestrian routing to one direction.

But it would be nice if OsmAnd respected an explicit "oneway:foot=yes".

**Comment by TO-92** [comment]
By convention "oneway" with no further detail applies to vehicles only, even on footways. Like here, for example: https://www.openstreetmap.org/way/697413230 - it would be wrong to restrict pedestrian routing to one direction.

But it would be nice if OsmAnd respected an explicit "oneway:foot=yes".
