### ISSUE TITLE
GooglePlay subscription does not register in App

### ISSUE THREAD

**Issue by sense-amid-madness** [osmandapp/OsmAnd#9649]
I just bought a subscription on the Google Play store. It seemed to work, since my Google play page now says 

"Open this app to confirm your subscription before Aug 20, 2020"

However, when I open the app, nothing happens. I still have a "Free version" of the app, and when I try to buy the subscription again, I get a "you already own this" (or similar) message.

Does anyone know what the problem is here?

**Comment by vshcherb** [comment]
Not aware of it, did you try to click button restore purchases on Downloads screen?
Do you see any limitation inside the app itself?

**Comment by sense-amid-madness** [comment]
Thanks for the reply, it seems the problem solved itself, it just took half a day until the app noticed that I had bought the subscription.


For the record:

- previously, I tried "restore purchases" several times, but it just went back to the same screen as before where I could purchase several subscriptions.

- inside the app, I was still limited to 7 downloads.
