### ISSUE TITLE
Public transport routing fails with error message

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/OsmAnd#9654]
- Make sure you have Germany/Europe/Berlin and Germany/Europe/Brandenburg maps installed
- Set a marker at coordinate 1
- Set a marker at coordinate 2
- Try public transport routing between these coordinates. It doesn't matter which coordinate you use as FROM and TO. The same issue appears in both directions.

Coordinate 1
52.51860° N, 13.37570° E

Coordinate 2
52.50784° N, 13.23444° E

Result: On first try I got an error message about "invalid wire type".

![grafik](https://user-images.githubusercontent.com/6921696/90410386-95c50280-e0aa-11ea-9270-773c66d4834c.png)

On each following attempt I get error messages about "protocol message".

![grafik](https://user-images.githubusercontent.com/6921696/90410522-bdb46600-e0aa-11ea-82aa-a4dbd117634e.png)

I already tried the following:

- Re-downloaded Berlin and Brandenburg maps

Result: Same problem.

- Re-started phone

Result: Still the same problem.

Found with OsmAnd~ 3.7.4 from F-Droid.

**Comment by Norbert80** [comment]
Now I get this parsing error everywhere in Germany I try public transport routing. But not in Bangkok/Thailand for example.

**Comment by vshcherb** [comment]
Looks very strange we will investigate

**Comment by max-klaus** [comment]
https://github.com/osmandapp/OsmAnd-core/pull/158
