### ISSUE TITLE
make highway=elevator to a clickable feature

### ISSUE THREAD

**Issue by Lukas458** [osmandapp/OsmAnd#9662]
Hi,

maybe it would be worth to make **highway=elevator** as a poi/clickable feature so you can see its properties?

For example, it would be useful to see:

- between which levels it goes

- the elevator's wheelchair accessibillity, also width/length of the door/cabin...

- its maxweight

- whether it's lit

- maybe its opening_hours when not open all time

- who operates the elevator

- whether it is accessible for bicycles

and maybe in the future some more things, like:

- whether it is accessible for stollers

- whether it has a handrail

- who's the manufacturer

- does it have speech output?

-...

**Comment by Lukas458** [comment]
Well, I think this can be closed, it was added here: https://github.com/osmandapp/OsmAnd-resources/commit/51de0480b0bc9ef5c905a53b120457231d459b5c (thanks to user xmd5a2 )

**Comment by NotSoImportant** [comment]
I cannot see this in 3.7.4 with latest maps or nightly (2020-09-15) with 1 year old map.
Where / how can I see it? Thanks

**Comment by Lukas458** [comment]
Yeah, your're right, that's also my problem.

**Comment by Lukas458** [comment]
Maybe it has to do something with this section:

		<type tag="highway" value="elevator" minzoom="15"/>
		<entity_convert pattern="tag_transform" from_tag="highway" from_value="elevator" to_tag1="elevator" to_value1="yes" map="no" routing="no"/>

in the file **rendering_types.xml**?

**Comment by NotSoImportant** [comment]
In nightly osmand with maps of November it os clickable, but shows no properties:

![Screenshot_20201017-235851](https://user-images.githubusercontent.com/35758921/96354294-5aa87500-10d5-11eb-9acd-6f9b38bbec0e.png)

![Screenshot_20201018-000305](https://user-images.githubusercontent.com/35758921/96354291-59774800-10d5-11eb-920c-50cc9a130db3.png)

**Comment by Lukas458** [comment]
Yes, true, that's also what I see in my maps. The elevator gets rendered, but not recognized as a clickable POI. I would go on and delete the section I mentioned in the _rendering_types.xml_, but as I'm not so deep with this code, I would like that someone maybe can look at this or confirm my idea before I'm going to make a PR to change something concerning this.
