### ISSUE TITLE
Different distance in car and Public Transport navigation

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/OsmAnd#9664]
On the same route, OsmAnd calculates different distances in Public Transport navigation than Car navigation.

Example (it is only an example, it occurs in other routes):
From: https://www.openstreetmap.org/#map=19/40.47873/-3.72644
To: https://www.openstreetmap.org/#map=19/40.46882/-3.75041

OSRM: 3.1 km https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=40.47875%2C-3.72648%3B40.46880%2C-3.75040#map=19/40.47854/-3.72570
OsmAnd Car navigation: 3.1 km
OsmAnd Public Transport navigation: 2.64 km

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/10805 with longer conversation
