### ISSUE TITLE
wikidata info shown too prominently

### ISSUE THREAD

**Issue by aceman444** [osmandapp/OsmAnd#9671]
When touching a POI that has a wikidata tag, the value is shown in a separate row on TOP of all the other information (like wikipedia link and other properties of the POI). I don't think this happened in the past, but why does this happen? Why is wikidata so prominently on the top. What is it useful for? It can't be clicked to open the article, it actually suggest to call that number as a phone number, which is unhelpful. If the wikidata number is useful to anyone, it could at least be merged with the wikipedia datarow, or something similar. I also think if wikipedia tag is missing on a POI, the wikidata ID could still be used to lookup the corresponding article. I don't think OsmAnd is doing this yet. Some people only add the wikidata tag as it is more stable than the wikipedia link (the article name may change).

**Comment by NotSoImportant** [comment]
In 3.9.10 I cannot see a wikidata entry at all for items that definitively have a wikidata entry.

Interestingly: for one I can see the image beeing shown from the wikidata "image" field, for another one this is not happening.

**Comment by NotSoImportant** [comment]
@aceman444 can you please check if your reported behavior still exists? Otherwise this issue could be closed.

**Comment by aceman444** [comment]
Really, wikidata info is no longer shown in POI details. Thanks.
