### ISSUE TITLE
Edit POI screen UI layout issue

### ISSUE THREAD

**Issue by ArjanOnwezen** [osmandapp/OsmAnd#9686]
The OSM edit POI UI has layout issues.
Overlapping text and misalignment.
See screenshot. I'm using Osmand 3.7.0~ build 30399.
![Screenshot_2020-08-22-23-09-35-397_net osmand plus](https://user-images.githubusercontent.com/44684169/90965928-06b25300-e4cd-11ea-81c6-a76d188b88d1.jpg)

**Comment by dmpr0** [comment]
The issue is already fixed, the current beta build contains the fix.
