### ISSUE TITLE
Cycle network node shield and font size

### ISSUE THREAD

**Issue by matthijskooijman** [osmandapp/OsmAnd#9692]
Looking at the git log, I noticed that @dmpr0 added "shields" for cycle network nodes (i.e. small circles rendered behind the node numbers), which I really like. It makes the node numbers a lot easier to read and makes rendering more consistent with other online and offline cycle maps.

However, I did find that the shields and node number font size is a bit big, especially at the lower zoom levels (11/12).

E.g. this is at zoom 11, on a 8" tablet (800x1280, 189dpi):

![Screenshot_20200824-225142_OsmAnd Nightly](https://user-images.githubusercontent.com/194491/91095348-7f93e500-e65c-11ea-9928-6233cc7667b9.jpg)

I suspect that the font size is the same as it was before the shields were added, but:
 - The shields obscure more of the map than just the numbers, so at the lower zoom levels the shields become a bit overcrowded.
 - The shields significantly increase the readability of the node numbers, so the font can be smaller while still keeping things legible.

So I experimented a bit with font sizes, and ended up with below settings that look good and still legible to me:

```
                                        <apply_if minzoom="11" maxzoom="12" textSize="6">
                                                <apply_if textLength="3" textSize="6"/>
                                        </apply_if>
                                        <apply_if minzoom="13" maxzoom="13" textSize="8">
                                                <apply_if textLength="3" textSize="8"/>
                                        </apply_if>
                                        <apply_if minzoom="14" maxzoom="15" textSize="10">
                                                <apply_if textLength="3" textSize="8"/>
                                        </apply_if>
                                        <apply_if minzoom="16" maxzoom="17" textSize="14">
                                                <apply_if textLength="3" textSize="11"/>
                                        </apply_if>
                                        <apply_if minzoom="18" textSize="17">
                                                <apply_if textLength="3" textSize="15"/>
                                        </apply_if>

                                        <apply>
                                                <switch>
                                                        <case textLength="1"/>
                                                        <case textLength="2"/>
                                                        <case textLength="3"/>
                                                        <apply_if minzoom="11" maxzoom="12" textShield="purple_circle_small_cycle_node_shield"/>
                                                        <apply_if minzoom="13" maxzoom="13" textShield="purple_circle_small_cycle_node_shield"/>
                                                        <apply_if minzoom="14" maxzoom="15" textShield="purple_circle_small_cycle_node_shield"/>
                                                        <apply_if minzoom="16" maxzoom="17" textShield="purple_circle_large_cycle_node_shield"/>
                                                        <apply_if minzoom="18" textShield="purple_circle_xlarge_cycle_node_shield"/>
                                                </switch>
                                        </apply>
```
Note that I used the small shield for all smaller zoom levels, since I had no easy way to add even smaller shields.

At zoomlevel 11, this gives:

![Screenshot_20200824-225032_OsmAnd Nightly](https://user-images.githubusercontent.com/194491/91095391-95090f00-e65c-11ea-8d92-afc4c1bde2f2.jpg)

(Look at the font sizes, the shields still need to be scaled down).

So, maybe it would be good to scale down the font and shields slightly?

Also, it seems that numbers are sometimes, but not always, printed slightly off-center inside the circles. I initially thought that maybe things were properly centered, but looked off-center because of the difference between numbers, but looking more closely it seems that sometimes the text really is off-center by one pixels (if you look at the first screenshot above, you can see that it can be off in all four directions, though maybe left-right is just imbalance or half a pixel rounding error). Here's a close up of two of them, with some guides added symmetrically around the center:

![image](https://user-images.githubusercontent.com/194491/91096310-22992e80-e65e-11ea-9629-4e55590916de.png)

Maybe this is really a different issue (since I suspect this is a rendering engine issue, rather than a rendering xml issue, but maybe it's an issue with the shield SVGs), let me know if I should create a separate issue for this.

**Comment by matthijskooijman** [comment]
One more thing about the shields that I noticed: When switching to night mode, the text color becomes light, but the shields do not become dark: 
![image](https://user-images.githubusercontent.com/194491/91150889-42137400-e6bd-11ea-8726-9b7634c6d9e4.png)

For other shields (e.g. road shields), it seems that the text color and shield color remain unchanged in night mode, but for cycle routes, the color changes: https://github.com/osmandapp/OsmAnd-resources/blob/6c396b58755393a7e8321675054808c110615e90/rendering_styles/default.render.xml#L1276

I guess the fix for this would be to have a separate color for cycle nodes (on a shield) that does not change in night mode (leaving the current `cycleRouteTextColor` to change in night mode for route names that are rendered without a shield), or to switch to a differently colored shield in night mode (but if you ever want to support configuring shield colors and shape in the map data to localize the node rendering, changing color in night mode might be problematic).

**Comment by vshcherb** [comment]
Well we need to add smaller cycle so you can use it for small zoom levels.
I would summarize it as 3 step points:
- [ ] Fix night color 
- [ ] Add smaller cycle so it's possible to use it as well
- [ ] Investigate if it's possible to align text horizontally (does it happen to other icons / text overlay) ? Text alignment probably is not a big issue for higher density phones cause the error is measured in 1-2 px

**Comment by matthijskooijman** [comment]
> Add smaller cycle so it's possible to use it as well

I was wondering: Given that these are just SVG images, couldn't a single image be used and scaled on rendering, rather than having a bunch of different images? Probably needs changes in the engine, but this might be useful in other places too?

> does it happen to other icons / text overlay

I haven't checked, but I can imagine that the symmetry of a circle makes this more pronounced than other (rectangular) shapes.

> Text alignment probably is not a big issue for higher density phones cause the error is measured in 1-2 px

Yeah, I think I only saw it on my (much) lower density tablet, on my phone I had not really noticed it before.
