### ISSUE TITLE
local cycle routes lcn=yes not displayed

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#9693]
...they are only displayed (blue line) if tagged as network=lcn
Example: 
network=lcn
ref=EM
route=bicycle
type=route
But very much lcn are within towns or connecting small villages, so they don't have a ref tag. Much of them only tagged as lcn=yes and in reality with signs indicating the destination and distance.
I think we had this problem also a long time ago.

**Comment by matthijskooijman** [comment]
Looking at this tag on the wiki, it is documented, but not currently recommended (route relations are recommended instead: https://wiki.openstreetmap.org/wiki/Cycle_routes#Tagging_cycle_route_networks). However, it does seem there are still 150k ways tagged like this: https://taginfo.openstreetmap.org/tags/lcn=yes

So might be good to support this, though AFAICS this only allows coloring a way as a route, it does not allow rendering e.g. a route name along with it?

**Comment by pebogufi** [comment]
As i can see in our region, most of the small lcn (within town or local character) don't have a name. The rcn (and of course) ncn and icn have names. So for these lcn coloring would be enough for orientation.

**Comment by xmd5a2** [comment]
Yes, roads with *cn=yes aren't rendered properly after complete refactoring. Some java code modifications are needed.
