### ISSUE TITLE
Increase the cache time for online tracking in the trip record plugin

### ISSUE THREAD

**Issue by suregoodru** [osmandapp/OsmAnd#9698]
Hello. We use osmands for the work of rescuers who are looking for missing people.
Online tracking is doing our job much better than before.
But in the forest there are often lifeguards without the Internet for more than 1 hour. And we are losing some very valuable data. Is it possible to increase the cache time for online tracking to 12, or even better 24 hours?
![photo_2020-08-26_10-40-29](https://user-images.githubusercontent.com/4560198/91275258-93d50080-e788-11ea-86b4-3d668bb3cf93.jpg)

**Comment by Chumva** [comment]
![image](https://user-images.githubusercontent.com/19220417/91280216-224c8080-e78f-11ea-9610-4f76023d0381.png)

**Comment by Lee-Carre** [comment]
Instead of a long list of discrete preset values, how about allowing the user to input an arbitrary duration?
