### ISSUE TITLE
World overview map issue

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd#9701]
The area to the West from the Baden-Württemberg map (partially consists of Regierungsbezirk Karlsruhe and Regierungsbezirk Freiburg maps)  is displayed bolder than other similar regions on the further zoom levels. This issue does not occur in the Nightly OsmAnd version though
![image](https://user-images.githubusercontent.com/50198677/91304159-b62f4400-e7b1-11ea-94fc-74c103512f1a.png)

**Comment by vshcherb** [comment]
Let's wait for nightly release 3.9 and collect feedback again
