### ISSUE TITLE
Address search: Passau neuburger strasse

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#9704]
I have an interesting search issue here, found with our June 12 nightly (very close to the 3.7.4 release) and the latest Aug 1 Germany/Bavaria map.

Goal is to find street Neuburger Straße in the town of Passau.

The screenshots show that as you start typing "passau neubu", the correct search result actually shows on screen, but if you continue typing to e.g.  "passau neuburger", it has disappeared again. (If you try repeatedly, first make sure you delete this entry if once selected in a prior search from the search history again.)

The issue happens also when typing "passau, neubu" (with a comma), or using the Address search (no hit found at all), or using the Address tab's "First specify the city/town/village" feature.

![1](https://user-images.githubusercontent.com/845735/91319088-44102c80-e7bc-11ea-8ee6-8f5d9cbb5956.png)

![2](https://user-images.githubusercontent.com/845735/91319843-22fc0b80-e7bd-11ea-980d-432224b9b4e5.png)

**Comment by letypequividelespoubelles** [comment]
I don't have other example in mind but this appears very often.
And also, it would be nice that the "internet search" button is on the top the online search works so better.

Thanks

**Comment by vshcherb** [comment]
Can't reproduce it , there is no street neuberguer strasse in passau in latest maps, so I'm afraid  first screenshot is incorrect.
And I cna't reproduce it so far.
Passau neustifter strasse - works fine

**Comment by scaidermern** [comment]
> Can't reproduce it , there is no street neuberguer strasse in passau in latest maps

There is, see https://www.openstreetmap.org/search?query=Neuburger%20Stra%C3%9Fe%2C%20Passau#map=19/48.56004/13.42285&layers=N and for example https://www.openstreetmap.org/way/73317823.

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd/pull/10496

**Comment by scaidermern** [comment]
Can you explain why d2b0b38 is necessary? Looks rather weird and error-prone, i.e. which other names need to be added to this list?

**Comment by alisa911** [comment]
This is a list of very common names. For example, in this issue "neuberger" is a very popular name for the streets and cities of that area. By adding it to the list, we have lowered its search priority. That is, now it is first searched for by passau, and only then by neuberger.
