### ISSUE TITLE
Problem showing right wikipedia article due to letter case differences

### ISSUE THREAD

**Issue by aceman444** [osmandapp/OsmAnd#9708]
Notice node https://www.openstreetmap.org/node/1831956394 that has both wikidata and wikipedia tags. The wikipedia tag that OsmAnd uses to display wiki article (offline) links to https://sk.wikipedia.org/wiki/Dem%C3%A4novsk%C3%A1_Dolina . This also displayed in the OsmAnd UI, when the POI details are tapped. However, when tapping the wikipedia link, the article displayed offline inside OsmAnd is actually https://sk.wikipedia.org/wiki/Dem%C3%A4novsk%C3%A1_dolina . Notice there is only difference on capitalization of the name "Dolina". Both of these names and articles on wikipedia are valid and correct and describe different objects. On the place=village node, only the https://sk.wikipedia.org/wiki/Dem%C3%A4novsk%C3%A1_Dolina must be displayed by OsmAnd.

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd/pull/11425
