### ISSUE TITLE
Core Building Installation 

### ISSUE THREAD

**Issue by Aashish0101** [osmandapp/OsmAnd#9709]
Hi There
Thank you for making this wonderful package open source.
Actually am trying to build its core. And I followed the steps been provided but

while doing that am getting following error,can u please suggest what am doing wrong.

Please set them or make sure they are set and tested correctly in the CMake files:
FONTCONFIG_LIBRARY
    linked by target "skia_static" in directory /root/bin/cmake-3.6.2/project/core/externals/skia
X11_Xi
    linked by target "freeglut_static" in directory /root/bin/cmake-3.6.2/project/tools/cpp-tools/map-viewer/externals/freeglut
X11_Xrandr
    linked by target "freeglut_static" in directory /root/bin/cmake-3.6.2/project/tools/cpp-tools/map-viewer/externals/freeglut
X11_Xrender
    linked by target "glew_static" in directory /root/bin/cmake-3.6.2/project/core/externals/glew

Seeking your kind help.

**Comment by vshcherb** [comment]
I'm afraid we didn't use for long time, I remember last time running was 5 years ago and I'm afraid won't be able to help. So far we're running only ios/android version
