### ISSUE TITLE
Feature request: Delete maps without the need to update them first.

### ISSUE THREAD

**Issue by felixbecker2** [osmandapp/OsmAnd#9717]
Currently, when I want to delete a downloaded map in OsmAnd where an update is available, I first need to download the update before I can delete it.

Depending on the speed of the internet connection this can take long, just to delete a map.

So I phrase the following feature request: Make it possible to delete downloaded maps from within OsmAnd even when there is an update available.

**Comment by scaidermern** [comment]
This is already possible:

![photo_2020-08-30_13-46-27](https://user-images.githubusercontent.com/1040784/91658182-3bbf3680-eac7-11ea-8144-f5a8459a4069.jpg)

**Comment by sonora** [comment]
Why would you think you need to update first? Just go to Menu/Download maps, to tab 'Local' (where all files are listed you actually have locally on your device). Locate the map in question and select 'Delete' in its respective 3-dots context menu.

**Comment by sonora** [comment]
Looks like @scaidermern was 2 minutes faster than me. ;)

I guess the original misunderstanding may be that you are trying to delete from the 'Update' tab, but that shows updates you have not yet downloaded to your device. Maybe there is a better wording to translate 'Local' in your language to make it clear that this tab the list of files you had already downloaded to your device (and where naturally they also can be deleted).

**Comment by felixbecker2** [comment]
> [Why would you think you need to update first? Just go to Menu/Download maps, to tab 'Local'](/osmandapp/OsmAnd/issues/9717#issuecomment-683410903)

I was browsing in "All Downloads" (as I do usually), and downloaded & up tp date maps can be deleted from there. Not up to date maps need to be updated first before they can be deleted from there.

There was nothing pointing me that the context menues in the "Local" tab are different -- I just assumed that the tab contains a filtered list of maps: The ones which have been downloaded, but with same functionality in the context menues as in "All Downloads".

So there was a confusion for me; maybe downloaded maps at "All Downloads" can get the same context menu entries than maps at "Local"?

I hereby close the issue since the functionality is there, but I leave the comment about the confusion I got and the suggestion to make the context menus similar.

**Comment by sonora** [comment]
Ok, thanks. 'All Downloads' are all which are offered on the server (it is an online view). 'Local' are the ones present on your device locally (i.e. you must have downloaded at some point). And 'Updates' are newer versions offered for download on the online server of those you already have locally as older versions.

I am very open for any better wording which could make this clearer.

**Comment by felixbecker2** [comment]
> 'All Downloads' are all which are offered on the server (it is an online view). 'Local' are the ones present on your device locally (i.e. you must have downloaded at some point). And 'Updates' are newer versions offered for download on the online server of those you already have locally as older versions.
> 
> I am very open for any better wording which could make this clearer.

'Local' is fine, you could also name it more clear 'downloaded'.

I now used that menu, and I find that there is another sorting (and also cached web maps appear there). To find a specific map by region in order to delete it I still like 'All Downloads' more, since there is a geographical hirarchical order, which is not in 'Local'; and in 'Local' there is a lot to scroll to find the different types of maps for one region (roads, hillshading, countour, wikipedia).

So I would still like to offer also the delete functionality in the 'All Downloads' menu for downloaded maps which have updates on the server.
