### ISSUE TITLE
[offline maps] If an area is divided into sub-areas, make sure the union of all sub-areas resembles the whole area.

### ISSUE THREAD

**Issue by felixbecker2** [osmandapp/OsmAnd#9718]
I want to request that, if you divide a region into sub-regions, that the sum of all sub-regions makes up the main region.

Currently, there are regions which are only partly covered by it's sub-regions.

Examples:

* Norway:
  - If I download all sub-regions of Norway, I still do not get [the Island "Bouvetøya"](https://www.openstreetmap.org/way/174996681#map=7/-54.236/3.669), for example.
  - "[Bouvetøya](https://www.openstreetmap.org/way/174996681#map=7/-54.236/3.669)" is only covered in the map covering whole Norway (more than 1GiB in size), breaking the advantage of smaller maps for faster local updates (if I want to have "[Bouvetøya](https://www.openstreetmap.org/way/174996681#map=7/-54.236/3.669)" I need the whole Norway map as a whole, anyway).
* Russia:
  - There were similar issues with arctic islands and sub-regions divided into oblasts, where not all islands are covered by the division on oblast level.

This is quite annoying.

Another thing is that some areas are doubled, e.g. Transnistria is listed as own country, but is also covered by Moldova; Crimea is in Ukraine and Russia. (OK, this way you might please all sides when it comes to disputed territory.)

I propose an automated mechanism for the map file makers that checks for this completeness, since manual division can always produce that kind of errors again.

**Comment by vshcherb** [comment]
Norway has recently changed regions so it's probably confusing still though it is impossible that Region is not part of smaller maps.
Cause norway is collected from smaller maps (join_map_files), similar to Russia, so the region must be in one of the smaller region otherwise it will be empty in a bigger map as well.
```
<region name="norway" wiki="no" inner_download_prefix="$name" lang="nb,nn" poly_extract="north-europe" join_map_files="yes">
```

**Comment by felixbecker2** [comment]
> Cause norway is collected from smaller maps (join_map_files), similar to Russia, so the region must be in one of the smaller region otherwise it will be empty in a bigger map as well.

* I downloaded all sub-region-maps in "Europe" -> "Norway",
* [Bouvetøya](https://www.openstreetmap.org/way/174996681#map=7/-54.236/3.669) was not present,
* when I tap on a region that is not downloaded OsmAnd can give all maps which cover that region; only the "whole Norway" was offered.

Please tell me which sub-region has [Bouvetøya](https://www.openstreetmap.org/way/174996681#map=7/-54.236/3.669).

Regarding russia, it are the islands of [Novaja Semlja](https://www.openstreetmap.org/relation/4263184#map=4/73.82/65.21) in the Arctis, which are part of "Northwest Federal District" in OsmAnd, but of none sub-region of "Northwest Federal District".

Both are regions not really inhabited, by the way.

**Comment by vshcherb** [comment]
I will let @xmd5a2 answer that question though this looks technically impossible but it's probably that something was overlooked

**Comment by xmd5a2** [comment]
@felixbecker2 Novaya Zemlya is in Arkhangelsk region and I see nothing wrong with maps division in OsmAnd
![Screenshot from 2020-09-11 15-03-02](https://user-images.githubusercontent.com/5829014/92923380-0c51e780-f440-11ea-8115-f89838089840.png)

**Comment by vshcherb** [comment]
Map will be provided next month

**Comment by felixbecker2** [comment]
> but some northern islands in Krasnoyarsk region surely has an issue which I just fixed

Thanks.

I am wondering how the above cited sentence can be if

> this looks technically impossible

is valid.

Are the underlying things now also fixed, that the situation of beeing "technically impossible" is now forced world-wide? (What is with [Bouvetøya](https://www.openstreetmap.org/way/174996681#map=7/-54.236/3.669)?)

> Map will be provided next month

Thanks for the work!

**Comment by vshcherb** [comment]
"technically impossible" - technically this island wasn't part of Norway map before, so now it is fixed for Norway. I don't know any examples that we build same map twice i.e. if we build Netherlands_drenthe, ... we don't rebuild Netherlands and only use combined maps. We do it on purpose to save generate time.
