### ISSUE TITLE
[Feature request] Adjust OsmAnd/TTS audio output volume

### ISSUE THREAD

**Issue by Lestat-GitHub** [osmandapp/OsmAnd#9719]
Hi, is that possible to add a setting to adjust the audio level of TTS output ?

I'm using OsmAnd on my car with a music player on the background (Poweramp). Everything
is fine but when I push global audio volume (for quiet musics) I get very loudy OsmAnd notifications
as the TTS uses the global audio volume.

Having a setting to adjust OsmAnd audio output would be just perfect to avoid that !

Thanks.

**Comment by sonora** [comment]
We use the standard Android AudioManager implementation, this means the system volume settings apply. Android systems typically have the different output channels stream (media), notification (ringtone), and phone call audio.

OsmAnd supports streaming its sound output over any of these channels, and Android has separate volume sliders for each.

Have you tried using another channel for OsmAnd and separately adjusting its volume? (`Menu / Configure  / profile / Navigation settings / Voice prompts / Voice guidance / Voice guidance output`)

**Comment by Lestat-GitHub** [comment]
Hi,

thanks a lot for this solution... I'm sorry for not having checked it before opening the issue !
It works perfectly and do exactly what I need.

The only side effect is that as I'm using an Android Car Radio that has a volume fade option when
the GPS application speaks (lower music volume by x%), this option does not work when sound comes
from another channel than "media". But that's not a big deal...

Thanks again for this solution.
