### ISSUE TITLE
render "boundary"="national_park" objects the same way as "boundary=protected_area" objects

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd#9735]
Ways and relations tagged as "boundary"="protected_area" in OpenStreetMap are rendered with a dotted green line in OsmAnd when polygons are set as hidden, but ways and relations tagged as "boundary"="national_park" are not rendered at all on the same setting.
Rendering "boundary"="national_park" objects the same way as "boundary=protected_area" objects would make them visible or invisible independently of other polygons.

**Comment by xmd5a2** [comment]
I've found a bug related to objects order but not clear does this fix work for original issue or not. Please test with latest nightly.
