### ISSUE TITLE
Cannot build Android version with NDK: 'expat.h' file not found

### ISSUE THREAD

**Issue by bagage** [osmandapp/OsmAnd#9736]
# 🐞 bug report

### Description

In #9705 I'm trying to build OsmAnd for Android. I managed to build it *without NDK* thanks to @vshcherb using:

```sh
repo init -u https://github.com/osmandapp/OsmAnd-manifest -m readonly.xml
repo sync
unset ANDROID_NDK
./gradlew -xtest -Dorg.gradle.jvmargs="-Xmx8048m" assembleFullLegacyFatDebug
```

However if it fails if I enable NDK 14b (using the same version as [osmand builder](https://builder.osmand.net:8080/view/OsmAnd%20Builds/job/OsmAnd-main):

```sh
export ANDROID_NDK=/tmp/android-ndk-r14b
./gradlew -xtest -Dorg.gradle.jvmargs="-Xmx8048m" assembleFullLegacyFatDebug
```

## 🔥 Exception or Error
<pre><code>jni/../../../core-legacy/targets/android/OsmAndCore/../../../native/src/renderRules.cpp:5:10: fatal error: 'expat.h' file not found
#include &lt;expat.h&gt;
         ^
1 error generated.
make: *** [obj/local/x86/objs/osmand/__/__/__/native/src/renderRules.o] Error 1
make: *** Waiting for unfinished jobs....
</code></pre>

**Comment by njohnston** [comment]
Presumably the code requires libexpat (an XML parser). Try installing that plus the devel package (to get the mentioned header file).

**Comment by bagage** [comment]
Yes but we are talking Android NDK here. Installing a library is not straightforward, is it?

It should be within OsmAnd code, not something user as to add manually? Otherwise, how should it be done?

**Comment by vshcherb** [comment]
External native library where not initialized correctly looks like

**Comment by naoliv** [comment]
> Yes but we are talking Android NDK here. Installing a library is not straightforward, is it?

It should be a simple `apt install libexpat1-dev` on Debian/Ubuntu systems (and probably something similar on other distros).

**Comment by bagage** [comment]
It is already installed on my system - even doing a fresh `repo init && repo sync && ./gradlew assemble` doesn't work so I believe something is missing in my setup. But I don't see any documentation about that unfortunately.

**Comment by bagage** [comment]
There is no `/core-legacy/externals/skia/upstream.patched/third_party/externals` folder, only a single file located in `/core-legacy/externals/skia/upstream.patched/third_party/expat/BUILD.gn`.

Not sure how/when this `externals` folder should be created?

**Comment by bagage** [comment]
Update:

I managed to fix this error by deleting `/core-legacy/externals/skia/upstream.patched` folder, and run `/core-legacy/externals/skia/configure.sh` script, then externals folder appeared (thanks again @vshcherb for the valuable pointer!). 

I'm investigating why now.

**Comment by bagage** [comment]
OK found the culprit: 

> ./git-sync-deps
/usr/bin/env: « python »: Aucun fichier ou dossier de ce type

In newer Debian versions, `python` binary does not exist anymore. You have to explicity use `/usr/bin/env pyhton2` instead.

**Comment by vshcherb** [comment]
oops valuable pointer please create pull-request to update this part of documentation https://github.com/osmandapp/osmandapp.github.io/blob/master/website/help/faq.html#L582

**Comment by bagage** [comment]
@vshcherb please do not close the issue if a merge request is needed to fix it - the MR will close it once it get merged?
