### ISSUE TITLE
Import/Export issues

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#9739]
- [x] Empty value import is not correct for Android. Instead of empty, it shows 0.01 m (length, width,...). To reproduce: get export from ios (or remove property value in .osf), import profile to Android and check length, width, etc... Instead of empty value (no limit), 0.01m is there
**Import/Export**
- [x]  Navigation settings – Voice prompts – Speed limit tolerance: iOS 3mph export to Android > 5 mph.
- [x] https://github.com/osmandapp/OsmAnd/issues/9588
- [x]  Navigation settings – Route parameters: export from iOS to Android: ios(fuel efficient on)
![routeparans](https://user-images.githubusercontent.com/9365308/90873500-f0aa7280-e3a6-11ea-97d1-6f5fcfd17326.png)
[Car.osf.zip](https://github.com/osmandapp/OsmAnd-Issues/files/5107896/Car.osf.zip)

**Comment by max-klaus** [comment]
Fixed by https://github.com/osmandapp/OsmAnd/commit/20944112aca0443de3df7a43043ed2f2654cc930

**Comment by dmpr0** [comment]
Review:
- [ ]  Vehicle parameters > Length limit on the "Vehicle parameters" screen shows 0.01 m, but on the "Length limit" screen it shows those numbers, iOS version shows "None". I have used the same "Car" profile to test.
![Group 1](https://user-images.githubusercontent.com/9365308/92394755-c7ba0980-f12a-11ea-8105-c059340cddf2.png)
