### ISSUE TITLE
Touring-Style: Different road width with custom profile

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#9744]
I've configured the touring map style for the car profile (left). When creating a new custom profile (right) based on this car profile the road is rendered with a different width, although having exactly the same configuration (touring style, 150% zoom etc.):

![touring_road_width](https://user-images.githubusercontent.com/1040784/92212195-e5207680-ee91-11ea-87e7-cea916d623b4.jpg)

Looks like this happens only with the touring map style. Other styles (OsmAnd, Mapnik, Topo, ...) don't have this issue.

**Comment by vshcherb** [comment]
This is not an issue, it is designed in such a way that roads have always pixel size. So it's a question to the author style @sonora in case he wants to change it or not

**Comment by scaidermern** [comment]
Unfortunately that doesn't explain why the same style with the same settings is rendered differently in a custom profile conpared to the default profiles.

**Comment by vshcherb** [comment]
that actually doesn't explain though because this is related only to 1 style, app mode could be simply hardcoded in the style itself

**Comment by scaidermern** [comment]
Oh, I see. And there is no reason to fix this?

**Comment by sonora** [comment]
Yes, for touring purposes the car base profile accentuates major highways, just like the ped style accentuates trails (paths), bike accentuates highway=bicycle. Actually meant to be a feature, not a bug. ;)

Test it e g when hiking in the mountains: ped profile increases the trail visibility and easier distinguishes them from e.g. elevation lines or boundaries.

**Comment by scaidermern** [comment]
> Yes, for touring purposes the car base profile accentuates major highways, just like the ped style accentuates trails (paths), bike accentuates highway=bicycle. Actually meant to be a feature, not a bug. ;)

That makes sense. However both screenshots show a car based profile. Shouldn't the accentuation apply to both?

**Comment by sonora** [comment]
Ah, that's true, thanks, well observed!

I  had implemented the concept many years ago, well before the arrival of custom and derived profiles. There's probably an easy fix, will research. Thanks!

**Comment by sonora** [comment]
Fixed, Alexander, thanks for making me aware! (https://github.com/osmandapp/OsmAnd-resources/commit/7108056c7173b9efea50ece2d9d2568609e00009).

Havn't tested yet, but am confident it should work in the nightly build nightly now. (Alternatively could be tested by simply overwriting the updated rendering file in the file system.)

**Comment by scaidermern** [comment]
Works as expected, thanks!
