### ISSUE TITLE
Skip Waypoint

### ISSUE THREAD

**Issue by Sigi1995** [osmandapp/OsmAnd#9753]
hello,
i am a motorcycle driver and i tried to use OsmAnd+ to navigate. But i have a big Problem. i usually import gpx files for navigation. Sometimes i have to change my tour during travelling - for example a closed road. From that moment i cannot use your app any longer, because it tries to bring me up to the unreachabele waypoint. With other navigation tools i can delete the unreachable waypoint, and follow my tour whithout this waypoint. Is there a chance to modify your app and add such a point so that i can use this app for routing.
Thanks
sigi

**Comment by vshcherb** [comment]
This is quite unclear. Is it about normal navigation where you can modify all waypoints (intermediate points as you want), click on directions button - modify icon (pencil) and delete skip waypoint.

Also there is a quick action - delete next waypoint ! This is 1 click button which allows you to skip waypoint

Or probably this request about GPX navigation which doesn't support waypoints at all.

**Comment by Sigi1995** [comment]
Thank you for your quick answer. As far as i understand your questions, it
is the third point. i produce a gpx file in another program or download a
Tour.
greetings
sigi

vshcherb <notifications@github.com> schrieb am Mo., 7. Sep. 2020, 17:14:
