### ISSUE TITLE
"Display Nearest POIs" displays wikipedia entries in all languages (mainly Cebuano) instead of selected wikipedia languages

### ISSUE THREAD

**Issue by ColinLeath** [osmandapp/OsmAnd#9755]
Related issues:

https://github.com/osmandapp/OsmAnd/issues?q=Wikipedia+language

Most recent discussion:

https://github.com/osmandapp/OsmAnd/issues/7169

Proposed solution:

Remove non-[selected languages] POIs from appearing when "display nearest POIs" is selected.

**Comment by vshcherb** [comment]
We need to fix "Near wikipedia articles" so the settings are applied

**Comment by vshcherb** [comment]
The issue about nearby wikipedia articles is fixed and now it's controlled by central settings. 
It might that original request was about "Nearby All pois" there we couldn't filter poi's by language cause it would be technically difficult and probably incorrect
