### ISSUE TITLE
Add favorite: set proper color

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#9767]
Icon on the text filed with preview of favorite point show color with transparency, but original colors now is without transparency.
![Снимок экрана 2020-09-08 в 12 51 36](https://user-images.githubusercontent.com/9365308/92461720-4322c600-f1d2-11ea-8d5d-aaa00443ff9e.png)

**Comment by vshcherb** [comment]
Icons still have transparency on the map! Though here in this UI textbox they obviously should be opaque

**Comment by androiddevkotlin** [comment]
This bug is not reproducible. Perhaps it has already been fixed.
