### ISSUE TITLE
Track stays visible after deleting it

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#9778]
Deleting a currently visible track makes the track stay visible on the map. The visibility can't be changed afterwards since the track isn't listed any more. Only restarting OsmAnd helps.

OsmAnd nightly.

**Comment by pebogufi** [comment]
Open Configure Map / Tracks.
The deleted track is still visible here, you can uncheck to hide.
So the problem is, i suppose there are different internal lists of visible tracks, which should be merged.

**Comment by scaidermern** [comment]
> Open Configure Map / Tracks.
> The deleted track is still visible here, you can uncheck to hide.

Yes, this works. However the track is no longer shown at My Places / Tracks / Visible.

Yes, synchronizing these views seems to be necessary. Alternatively deleted tracks should really be removed, i.e. not be rendered anymore.

**Comment by scaidermern** [comment]
Problem still exists with OsmAnd 3.9.1. However now the workaround doesn't work any more, the track doesn't get listed under Configure Map / Tracks but still stays visible on the map. The only solution is to restart OsmAnd.

**Comment by androiddevkotlin** [comment]
It seems already fixed on newer version.

**Comment by scaidermern** [comment]
> It seems already fixed on newer version.

Which version? I can still reproduce it with OsmAnd 3.9.10.
