### ISSUE TITLE
cycleway:<dir>:oneway=no ignored on cycle lanes

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#9782]
For bicycle routing OsmAnd uses ways tagged with `cycleway:<dir>=lane` and `cycleway:<dir>:oneway=no` only in one direction, i.e. it ignores the `oneway=no` part.

Example: https://www.openstreetmap.org/way/762904353
![photo_2020-09-10_17-01-13](https://user-images.githubusercontent.com/1040784/92750336-4317f700-f387-11ea-9e9c-84c0f898c30f.jpg)

The epected route is (here with foot profile):
![photo_2020-09-10_17-01-11](https://user-images.githubusercontent.com/1040784/92750356-4612e780-f387-11ea-9a05-ab5acf3d034e.jpg)

**Comment by aceman444** [comment]
What should cycleway:dir:oneway=no mean? Can you link to the wiki.openstreetmap.org page defining it?
The proper tag would be oneway:bicycle=no, which OsmAnd does support.

**Comment by aceman444** [comment]
OK, I see there is a description of the tag here: https://wiki.openstreetmap.org/wiki/Key:cycleway:right:oneway .
While I do not see why the oneway-ness has to have the left/right qualifier (it may be enough to know that the way as a whole is not oneway for the bike), it seems people do use it. So OsmAnd could get support for it.
But that same wiki page also proposes to add oneway:bicycle=no to the way, which is basically what I am talking about.

**Comment by scaidermern** [comment]
> But that same wiki page also proposes to add oneway:bicycle=no to the way, which is basically what I am talking about.

Currently it says:

> also oneway:bicycle=no to make it easier for bicycle routers to see that the way can be used in two directions

... which I think is wrong. This is tagging for the router, i.e. using wrong tags just to make the router doing the right thing. The _road_ can't be used in two directions, only the bicycle _lane_ can. That's why `cycleway:right:oneway=no` has been used together with `cycleway:right=lane`. This is a property of the bicycle _lane_ only, not of the whole road.

**Comment by aceman444** [comment]
For routing purposes, until OsmAnd can show the precise lane you should be driving in, the whole road is oneway=no for a bicycle. It is just additional information that you need to do it in the right lane.

But it should be fairly trivial for OsmAnd to add support for cycleway:<dir>:oneway as a synonym for oneway:bicycle.

**Comment by scaidermern** [comment]
Thanks!

**Comment by aceman444** [comment]
@xmd5a2 thanks, but the patch does not seem to support the "no" value which this report was about. Can you please check it?
