### ISSUE TITLE
E-road numbers used preferentially in UK, but they are not signposted.

### ISSUE THREAD

**Issue by nb374** [osmandapp/OsmAnd#9796]
# 🐞 bug report

### Is this a regression?
Yes

Not noticed this problem before.

### Description
OsmAnd shows E-road number badges as well as national road numbers on roads in the UK. When navigating, OsmAnd preferentially uses the E-road number in voice prompts instead of the national road number, for example "Turn left onto E-15" instead of "Turn left onto A9". This is correct for countries where both numbers are signed on E-roads but in the UK it is a problem because E-road numbers are not signposted, and it is therefore difficult to know which road to turn onto.
[Example screenshot showing E15 badges as well as A9](https://user-images.githubusercontent.com/71180999/92997161-14c22500-f509-11ea-87c7-6db97c0d420f.jpg)

## 🔬 Minimal Reproduction
1. Open app
2. Browse to a UK road which forms part of an E-road network.
3. Observe the E-road badges along with national road number badges.
4. Set a destination which involves travelling along an E-road in the UK, with voice prompts on and follow the directions
5. When approaching the road which forms part of the E-road, listen to the voice prompts. Observe that the E-road number is used in the voice prompts despite not being shown on signposts.

## 🌍  Your Environment

**OsmAnd Version:**
<pre><code>

OsmAnd+ 3.7.4

</code></pre>

**Device and Android/iOS version:**
Samsung Galaxy A3 (2017), Android 8.0.0

**Maps used (online or offline):**

- [ x ] Offline maps offered within the OsmAnd app for download. 
Europe / United Kingdom / Scotland / 1 Sep 2020

- [ ] Online (tile / raster) maps 

**Anything else relevant?**

**Comment by njohnston** [comment]
This happened a while ago too but [it was fixed](https://github.com/osmandapp/OsmAnd-resources/blob/6494b640e81939e113daca6a9216f7b6c342482f/obf_creation/rendering_types.xml#L873):

```xml
<entity_convert pattern="tag_transform" from_tag="route_road_*_ref" if_tag1="route_road_*_road_network" if_value1="e-road" if_region_name="$gb,$germany,$uzbekistan,$ireland" seq="1:10" apply_to="way" notosm="true"/>
```

Hopefully @xmd5a2 can help.

**Comment by SomeoneElseOSM** [comment]
I'd argue that, separately from whatever OsmAnd does with the OSM data it gets given, mappers should not be adding routes that do not in any real sense exist on the ground to OSM.  To suggest that https://www.openstreetmap.org/relation/2332838 (to pick one that I am familiar with) is a route that people can follow is nonsense.  I've added name:signed=no and ref:signed=no to that so data consumers have at least half a chance of filtering out things that don't really exist, but in a different context (unsigned MTB routes) other people have suggested a stronger approach - see https://lists.openstreetmap.org/pipermail/talk-gb/2020-July/024849.html .

**Comment by vshcherb** [comment]
Certainly agree with Signed roads, though 1 Signed map could be enough sometimes - for example a big signpost with city "roundabout" road. Especially if it is maintained by government documents.
