### ISSUE TITLE
Regression: PT route relations disappeared

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#9803]
With our September 2020 maps it appears that tapping a PT stop does not show the (e.g. bus) route relations any more it is a member of.

Could possibly be related to the fix for #9672. I have tested with the same version of OsmAnd, I think the issue is in our latest obf files.

**Comment by vshcherb** [comment]
Can't reproduce it even more found another issue  -https://github.com/osmandapp/OsmAnd/issues/9807

**Comment by sonora** [comment]
I have just updated to our new beta,and it looks like the issue I report here is gone. Looks like maybe some missing backward compatibility of new obfs with previous apks, not sure. But maybe not a high prio issue then.

**Comment by vshcherb** [comment]
Well definitely not high but strange. Since I don't expect changes in obfs.
Issue is discarded
