### ISSUE TITLE
NPE crash when accessing Favorites

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#9809]
With the newest 3.8beta I consistently receive the enclosed NPE/crash when tapping on any favorite of a certain group (only) on the MyPlaces/Favorites screen.

[exception.log.txt](https://github.com/osmandapp/OsmAnd/files/5220390/exception.log.txt)

**Comment by Discostu36** [comment]
I have the same problem with 3.8.0. Not only when selecting the favorite from the menu but also when selecting it on the map. It does not happen fir newly created favorites in the same group.

**Comment by Chumva** [comment]
This should be fixed here - https://github.com/osmandapp/OsmAnd/commit/f543d40b1a1641a74675085a7cc866f436085823.

**Comment by sonora** [comment]
Yes, I guess that was it, thanks!
