### ISSUE TITLE
No more default Track appearance per map style?

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#9818]
Why did we remove the ability to select the default values (e.g. color) as they were researched for and specified in each render file as a suggested fit well visible in each respective renderer's day and night mode?

**Comment by vshcherb** [comment]
Default colors are available for selection and default value should be selected in case it is not specified. You can;t revert track color to default cause it is very technical and not obvious solution. In that case we would need specific UI to edit default color

**Comment by sonora** [comment]
Not  sure I understand, does this mean we create an irreversible situation where users playing with a setting once can never go back to what the renderer specifies in its xml?

**Comment by vshcherb** [comment]
Yes, user can't go back to original file cause color and other appearance settings are stored in the file
