### ISSUE TITLE
Wikimedia Commons Attribution

### ISSUE THREAD

**Issue by Discostu36** [osmandapp/OsmAnd#9819]
At the moment images from Wikimedia Commons are shown in the app without any attribution (author, license etc). I think this should be shown under the images when clicking on it, linking to the image description page on Wikimedia Commons.

**Comment by Discostu36** [comment]
As far as I know this should be at least possible to automate for all images that have license and author as structured data.

**Comment by Discostu36** [comment]
Example request: 

https://commons.wikimedia.org/w/api.php?action=query&format=json&prop=imageinfo&titles=File:Berliner_Tor_5_(Hamburg-St._Georg).ajb.jpg&iiprop=user|url|extmetadata|metadata&iilimit=1

Something like this (simplified pseudo code)
````
if (AttributionRequired.value==true) {
    figcaption.innerHTML= 'Artist.value(LicenseShortName.value)'
}
````

**Comment by Discostu36** [comment]
I think this should get a higher priority. At least there should be a link to the image description page on commons. Using these photos without attribution is a copyright violation that could lead to legal problems.

**Comment by vshcherb** [comment]
Agree, it should open a wikimedia html page at least with proper attributions.

**Comment by cepprice** [comment]
https://github.com/osmandapp/OsmAnd/compare/fix_wikipedia_attribution?expand=1
