### ISSUE TITLE
Add fuel LNG for amenity=fuel filter

### ISSUE THREAD

**Issue by De-Luxis** [osmandapp/OsmAnd#9823]
# 🚀 feature request

### Description

Прошу добавить в фильтр автомобильный заправо тип топлива Метан\LNG. Сжиженный природный газ. 
Для того чтоб не впутывать водителей, добавить уточнения:

- fuel:cng=yes Сжатый природный газ (метан)
- fuel:lng=yes Сжиженный природный газ (метан)

https://wiki.openstreetmap.org/wiki/Key:fuel тут есть описание. 

Сейчас в России активно внедряют такое топливо на метановых заправках. Из-за их редкости актуальна карта. Думаю osmand может завоевать некую популярность среди водителей если заправки с данным топливом начнут поддерживаться.

**Comment by vshcherb** [comment]
Yes, we already have support for cng (type cng in search) though we don't have "lng" yet.

**Comment by De-Luxis** [comment]
@vshcherb Yes, it's about lng
