### ISSUE TITLE
Add "avoid footways" switch for bicycle routing

### ISSUE THREAD

**Issue by theraser** [osmandapp/OsmAnd#9826]
I would like to promote this idea of adding an option to switch on/off usage of footways while using the bicycle routing. At the moment it is enabled by default (even if it is forbidden in the country) and without any notice or controllable switch for the user.

I stumbled across issue this while navigating in Germany and wondered why Osmand routes me via footways even if there is no i.e. "bicycle=yes" (which means it is forbidden) and there is an alternative route available. A simple switch (to be safe a default "yes" would be awesome) may be easier than respecting every country-specific legal rules.

The perfect addition would be a notice to dismount if you enable it in Germany, but that maybe is out of the scope of this issue ;-)

"Maybe, especially due to the regional differences, it might make sense here to have another setting in the 'avoid' menu, "avoid footways", here? If checked, a footway would get a priority of 0.1 (or so), rather than the current 0.75. (Fully excluding isn't a good idea I think as not all destinations can be reached without footways, but setting the priority so low would avoid them unless there really is no other option)"

_Originally posted by @Famlam in https://github.com/osmandapp/OsmAnd/issues/7372#issuecomment-518957824_

**Comment by carstenhag** [comment]
Hello, just stumbled across this issue thanks to the OSM DE telegram channel.

I was just having this exact problem yesterday. OsmAnd tried to route me via https://www.openstreetmap.org/way/491793444, despite it only being a footway. It would have been illegal for me to drive there. Would be the best for OsmAnd to know about the german rules, but a setting for this would be nice as well.

**Comment by carstenhag** [comment]
FYI, just tried it out on the osmand android nightly, on the profile setting I can now avoid footways. 
![Screenshot_20201017-135622](https://user-images.githubusercontent.com/3776997/96336549-f2c83f00-1080-11eb-9964-dd7179032bdb.jpg)

Seems sorta good, but ideally OsmAnd would know about the countries' laws. (see #10035).

**Comment by aceman444** [comment]
Great, thanks.
Yes, this is another candidate for OsmAnd to have table for per-country defaults, like access restrictions (like here), maxspeeds, etc.

**Comment by z3ntu** [comment]
For essentially this path: https://www.openstreetmap.org/directions?engine=fossgis_osrm_bike&route=48.20165%2C16.37101%3B48.19990%2C16.36822#map=18/48.20103/16.36901&layers=N

This is what osmand does by default:

<img src="https://github.com/osmandapp/OsmAnd/assets/3768500/9a72efbb-c702-4302-96af-e7f84f7eb97b" width="300">

The path it's taking there is https://www.openstreetmap.org/way/244103701 which is `highway=footway` which is definitely unsuitable for biking.

See also this brief discussion (in German) https://www.openstreetmap.org/note/3834561

**Comment by vshcherb** [comment]
This doesn't mean that you couldn't walk with bicycle for shot distance, so it should be a setting to avoid footways

**Comment by Helium314** [comment]
Walking 250 m instead of going 600 m on bicycle doesn't seem a good deal, unless you're really fast at pushing bicycles.

**Comment by aceman444** [comment]
The problem may be that OsmAnd does not calculate slow speed (like 5kph) on footways where you have to push a bike.

So this is not a problem of access restrictions (it is possible there are not any traffic signs in reality), but the behaviour on footways may depend on country laws. In some you may run bicycle on footways, in some you can't. But you can still push the bike with pedestrian speed and it maybe a good way to avoid a long detour. So OsmAnd should not avoid all footways unconditionally, it should just have proper routing parameters and road penalties to decide whether the shortcut is worth to take.

**Comment by scaidermern** [comment]
@aceman444 Exactly. That's also suggested in #18374.

**Comment by Velomeloman** [comment]
> This doesn't mean that you couldn't walk with bicycle for shot distance, so it should be a setting to avoid footways

And vice versa should be a setting to allow footways, that will decrease routing penalty. It's actual for countries without restrictions. The ban on riding on footways is established by separate tags.
