### ISSUE TITLE
Regression: Add favorite keyboard automaicly collapsing

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#9837]
In Add/Edit favorites screen in landscape mode taping on the text field will show the keyboard for a few seconds after that it will collapse automatically.

**Comment by anastasiia936** [comment]
Problem with description favorite on Huawei P20.

When user starts to describe a favorite the virtual keyboard jumps aside very quickly.
So it is impossible to keep writing.

**Comment by vshcherb** [comment]
It looks as Huawei problem https://www.reddit.com/r/Huawei/comments/bzpt40/p30_pro_closing_apps_while_using_the_keyboard/
