### ISSUE TITLE
oneway:yes not respected

### ISSUE THREAD

**Issue by kevinvincentsio** [osmandapp/OsmAnd#9844]
Hello,

I have made an edit to OSM by setting this road : https://www.openstreetmap.org/way/144398313 as "oneway".

But OSMAND keeps routing through this road in the wrong direction : 

![SmartSelect_20200918-140646_OsmAnd_](https://user-images.githubusercontent.com/32735319/93596311-63643900-f9b9-11ea-97d0-21f34f85cef1.jpg)

![SmartSelect_20200918-140623_OsmAnd_](https://user-images.githubusercontent.com/32735319/93596338-6e1ece00-f9b9-11ea-84d9-c7f7bfd93d88.jpg)

I am a beginner at OSM so maybe I am missing something ? Maybe can someone reproduce it ?

Thanks :)

**Comment by vshcherb** [comment]
Did you update the map?

**Comment by hakuchi** [comment]
@kevinvincentsio  You made the change 4 days ago and I think your card is from 9/1/2020
So wait until the next map update to see the correct execution in OsmAnd.

If you use Osmand + you will get a new update every month.
If you need more updates, you can buy the OsmAnd Live subscription.

**Comment by kevinvincentsio** [comment]
@vshcherb @hakuchi 
Actually I am using Osmand from "F-droid" with "Osmand Live", below is another screenshot from my app. And as you can see in the first screen the arrows on "Rue sous les saints" are in the correct direction (to the south) but despite this the routing engine says to take this street from south to north :sweat_smile:

![Screenshot_20200918-233614_OsmAnd_](https://user-images.githubusercontent.com/32735319/93647835-a948ed80-fa09-11ea-81e8-c8e4dfbdd2a1.jpg)
