### ISSUE TITLE
Search: same objects

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#9851]
![photo_2020-09-18 18 32 46](https://user-images.githubusercontent.com/9365308/93616391-5ce7b880-f9dd-11ea-944f-74d6d0d25dbf.jpeg)

**Comment by vshcherb** [comment]
1, 4 - should be filtered out by some rule cause they duplicate main place
3rd result - is not ordered correctly by distance

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd/pull/10518
https://github.com/osmandapp/OsmAnd-resources/pull/661
