### ISSUE TITLE
Bulk edit of favorites (group, color, icons ...)

### ISSUE THREAD

**Issue by GLLM** [osmandapp/OsmAnd#9861]
Hi all,

**Issue & context** 
I recently imported all of my G--glemaps points & addresses in OSMand, thanks to a gpx file I created with umap.
My addresses & points are sorted by categories, and each category has a dedicated icon & color (at least by default).

Unfortunately, my own "categories" were lost/not importable ... so  I lost my icons color & style in the process. However, I managed to import them into a group I created adhoc as a temporary group.

I looked for a way to select several points/favorites and move them into the same group ... to no avail.

I had to resort to selecting each imported point (100+), one by one, and change its group & color.

**Solution/feature request**
It would be great to be able to select a bunch of favorites and move them to a group, or assign them a color/icon etc ...

**Setup**
I'm using Fdroid latest 3.7.4 version, running Android 9 on a Samsung Galaxy S8+

Thanks
GLLM

**Comment by vshcherb** [comment]
As for now you can only do it via text-editors probably and later import into OsmAnd

**Comment by tradavyvy** [comment]
this issue seems linked to issue 9104

**Comment by readonly24** [comment]
I'm coming from Locus and I really miss this feature, especially because I just have imported a lot of POI.

**Comment by vshcherb** [comment]
I think it's now possible if you change default appearance group and click apply to existing.

**Comment by GLLM** [comment]
Hello @vshcherb !

I just tried on 2022.12.18 and did not find the solution you mention.
Shall I use a more recent version (not yet available on FDroid ?)

Or should this be kept opened ?

Thanks
GLLM

**Comment by readonly24** [comment]
Hello vshcherb, I can only change the color or icon for **all** POI in a group.

It would be nice to select any POI (that's alreasdy possible) and then move them to a different favourites group, or change the color or icon. For now, on can only delete the selected POI.
