### ISSUE TITLE
Different distance: Plan Route vs GPX Overview

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#9869]
Difference in distance calculation in first bottom sheet, and on bottom bar. [Car_Altitude.gpx.zip](https://github.com/osmandapp/OsmAnd-Issues/files/5209324/Car_Altitude.gpx.zip)

This is quite strange difference 3.12km vs 3.01 km. First assumption that distance is calculated with Elevation was wrong.

It's possible that distance is read from extensions of the route somehow but it's need to be checked.

**Comment by AnastasiaTiutina** [comment]
The problem still takes place. 
The total distance of the planned route is always shown in "Plan a route" at the bottom of the menu. But if you save that route, the length is no longer the same as in the menu

**Comment by vshcherb** [comment]
The problem takes place at creation! If you click modify track the distance starts matching in Plan Route UI

**Comment by dmpr0** [comment]
One more example:
[velik.gpx.zip](https://github.com/osmandapp/OsmAnd/files/5511690/velik.gpx.zip)
My places and open Plan a route, show correct distance.
Follow the track, Directions shows 0.
