### ISSUE TITLE
GPX track lines disappear on selecting "Join segments" on split track

### ISSUE THREAD

**Issue by 0x416c6578** [osmandapp/OsmAnd#9875]
# 🐞 bug report

### Is this a regression?
No
### Description
When opening a split GPX track and selecting "Join segments", opening a non-split track results in that new track's line not appearing on the map. The distance markers are still visible and the position tracker will move where the line should be when scrubbing along the graph. Opening a split track and reverting the setting change will cause the track line on non-split tracks to return upon opening.

## 🔬 Minimal Reproduction
1. Open split GPX track
2. Enable "Join segments"
3. Open non-split GPX track. The visual bug is observed
4. Open split track again and revert setting
5. Visual bug disappears

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>3.7.4 from FDroid</code></pre>

**Device and Android/iOS version:**
Oneplus 5t, Android 9
**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps

**Comment by Zirochkabila** [comment]
OsmAnd 4.2.7, released: 2022-07-13 and OsmAnd~ 4.3.0#13861mqta, released: 2022-10-11 **Not reproduced**
