### ISSUE TITLE
Make multiple track selections easier from My Places

### ISSUE THREAD

**Issue by akkana** [osmandapp/OsmAnd#9882]
I often want to show several GPX files on the map at once. For instance, two different track logs from different hikes, or a list of high peaks or other features for two nearby areas.

Currently, this requires many taps. For each track:
- Menu
- My Places
- Tracks
- scroll down to desired folder
- tap to open folder
- scroll down to desired track
- tap on track

Now I'm back in the map viewing the track I've just selected. To add the next one, I have to start from the beginning: My Places doesn't remember that I was in Tracks, or which folder was open, or where I was scrolled.

It would be so much easier if My Places would remember those things, so when I go back, I could be right where I was before.

Even better, I'd love to be able to open several tracks at once from My Places. This is possible from the _Show GPX Data..._ dialog, but that dialog isn't as usable because it doesn't have folders so the list is way too long and it's very difficult to find anything, and I agree with issue #8685 that it should be retired.

**Comment by dmpr0** [comment]
Hello! Thank you for the feedback.
We have plans to improve the Track dialog in Configure Map, with the possibility to switch between folders, as we do in the Plan a route track selection dialog

**Comment by pebogufi** [comment]
There is a way which is much faster:

- Menu
- My Places
- Tracks
- Map symbol in bottom panel (3rd from left)
- Then check all tracks you want to see
- Show on map in top panel
- back

**Comment by vshcherb** [comment]
It will be selectable from Configure Map -> Tracks ... So this issue is merged to https://github.com/osmandapp/OsmAnd/issues/10704
