### ISSUE TITLE
LightRS: city name should not be shown on high zoom levels

### ISSUE THREAD

**Issue by 532910** [osmandapp/OsmAnd#9884]
![image](https://user-images.githubusercontent.com/14617699/94090936-9d04cc00-fe1f-11ea-87a1-8baaee7d70e8.png)

**Comment by vshcherb** [comment]
City name demonstrates city center, so we prefer to show it

**Comment by 532910** [comment]
This way it must be shown on other styles on all zoom levels, the same as for LightRS.

**Comment by 532910** [comment]
In fact I was wrong and all styles behaves quite similar.
