### ISSUE TITLE
Broken text fields in Create POI screen

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#9893]
![Screenshot_20200925-122050](https://user-images.githubusercontent.com/9365308/94250288-b1cd8680-ff29-11ea-9415-8f0a18106e92.png)

**Comment by pebogufi** [comment]
This textfield is also insufficient for other tags, example to get an overview how a complex opening_hours is really tagged.
-> The textfiled should be able to scroll down (and up).

**Comment by pebogufi** [comment]
See also https://github.com/osmandapp/OsmAnd/issues/9938

**Comment by dmpr0** [comment]
### Review:
- [ ]  Text field jumps and loose underline.
<img width="2160" alt="Group 40" src="https://user-images.githubusercontent.com/9365308/96228099-c5569500-0f9d-11eb-9521-e38d20e45dc7.png">

**Comment by androiddevkotlin** [comment]
Already fixed - https://github.com/osmandapp/OsmAnd/pull/10032
