### ISSUE TITLE
Display of tracks ruined

### ISSUE THREAD

**Issue by frobijn** [osmandapp/OsmAnd#9896]
The latest OSMand update on Android ruined the display of tracks. I use tracks to keep track where I've been. Although I can set the track display to show a track as a line (without arrows; nice!), OSMand still adds a marker at the start and end of a track. I have not found a way to turn off the display of the marker. All these markers obscure the view of the map and there's no benefit of having them on the map, as it is also possible to click anywhere on the track to get to its info (that's very nice!).

![image](https://user-images.githubusercontent.com/13610628/94279697-c4a58280-ff4c-11ea-9a51-75eaad19387c.png)

This is a disaster. If I cannot hide the markers, how can I revert to the previous version of OSMand until this is fixed?

**Comment by pebogufi** [comment]
See also
https://github.com/osmandapp/OsmAnd/issues/9614

**Comment by vshcherb** [comment]
Currently the global option of display start/finish is introduced. It is global and you can tweak in 2 places in Configure Map -> Track and in Appearance

**Comment by frobijn** [comment]
Thank you, that will do nicely.
