### ISSUE TITLE
doubled icons in favorities - amenity

### ISSUE THREAD

**Issue by mariush444** [osmandapp/OsmAnd#9899]
just small bug.
Doubled icons in favorities.

![image](https://user-images.githubusercontent.com/66887280/94335800-442f6200-ffde-11ea-92ea-068269ecf5cc.png)

**Comment by dmpr0** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/3383ee587a7055f209f2e8269856b6495d8a8e15
