### ISSUE TITLE
Can't use public transports for routing

### ISSUE THREAD

**Issue by stemy2** [osmandapp/OsmAnd#9903]
### Description
When i'm using public transport for routing, i have an error message, no matter the start and endpoint:

"Unable to calculate route. While parsing a protocol message, the input ended unexpectedly in a middle of a field. This could mean that either than the input has been truncated, or that an embedded message misreported its own length."  

### How to reproduce?
1. Try to calculate a route with random start and endpoint.
2. Select public transport as a vehicle.

### Your Environment
OsmAnd Version: 3.7.4
Android/iOS version:7.1.2
Device model:Samsung Galaxy S7

**Maps used (online or offline):**   

Belgium standard offline map

**Comment by vshcherb** [comment]
This issue supposed to be fixed with 3.8.3
