### ISSUE TITLE
Better support for GPX files with multiple tracks

### ISSUE THREAD

**Issue by matobler** [osmandapp/OsmAnd#9905]
# 🚀 Better support of GPX files with multiple tracks

### Description

When I plan a trip I often compile a GPX files with tracks of backroads, off-road trails, hiking trails and points of interests (Waypoints). This includes tracks from various online resources such as AllTrails, FunTreck, and sometimes track logs uploaded somewhere by users. There can be 10-50 tracks for any given trip that are all stored in a single GPX file to make organization easy and so that they can easily be shared with other people in the group. **Here an example file.  [OSMtest.zip](https://github.com/osmandapp/OsmAnd/files/5287038/OSMtest.zip)**

While importing this file into OSMAnd works well, the tracks show up as a single track with different segments and I can't find a way of routing along just one segment. When selecting a track on the map (nice new feature in 3.8!) the statistics refer to all the tracks in the GPX file and not the specific track (segment) selected. There is also now way of seeing the metadata (name, description etc.) for each track which is useful when the metadata contains information on the trail. 

### Describe the solution you'd like
Tracks should be handled similar to Waypoints where multiple tracks in a single GPX file are handled as individual tracks that can be viewed, edited, assigned different colors, used for routing etc.. Track name and notes should show. Actually Locus Maps has solved this issue almost perfectly (OSMAnd is much better in many other ways so that I don't use Locus Map). Here some screenshots that show the desired functionality:

### List of tracks with names and metdata including notes.
![Screenshot_20200926-095843](https://user-images.githubusercontent.com/2934789/94347570-48617c80-ffea-11ea-9d38-64d8f518133b.png)

### Track details include description for the individual track along with a lot of the statistics that are already available in OSMAnd.:
![Screenshot_20200926-095759](https://user-images.githubusercontent.com/2934789/94347569-47c8e600-ffea-11ea-924e-bdc105cb4024.png)

### Clicking on a track shows the name and lets you go to a details page (this has been partially implemented in 3.8). Selecting a track on the map should be a bit easier than it currently is (some small buffer around the track should select the track, currently it is a bit difficult to select the exact pixel).
![Screenshot_20200926-095748](https://user-images.githubusercontent.com/2934789/94347566-45ff2280-ffea-11ea-97bd-b90f573b6332.png)

### Describe alternatives you've considered
While of course one could split up GPX files into single files for each track, that makes managing files much more complicated and difficult to share.

**Comment by sonora** [comment]
I concur that descriptive metadata matters and Isee increased usage in in GPX files available on download portals for all sorts of topics, e.g. for scientific or tourist content. I do agree that we should at least also display those text fields in our segment track analysis view.

**Comment by Chumva** [comment]
Multiple tracks import should be added here https://github.com/osmandapp/OsmAnd/pull/13640
