### ISSUE TITLE
Bug: Some ways are not rendered as intended by custom style

### ISSUE THREAD

**Issue by BigKananga** [osmandapp/OsmAnd#9906]
### Description
The problem is the following: Some ways are not rendered as intended by my custom style. 

### How to reproduce?
To make it a bit easier for you to reproduce it, I used the UniRS-Style as basis and modified it a bit. The custom render style (test.render.xml) is attached, my additions are from line 1278 to 1289 an you can see it here (added as picture because there seems some problems with inserting this code):

![code](https://user-images.githubusercontent.com/49197621/94353050-eeee6180-006c-11eb-8039-eebc6200169f.JPG)

These lines are looking like this in OsmAnd:
![test](https://user-images.githubusercontent.com/49197621/94352541-87351800-0066-11eb-8d12-6ead2c94181b.JPG)

The ways are the following in OSM:
1. https://www.openstreetmap.org/way/634019362#map=16/49.1559/8.4089
2. https://www.openstreetmap.org/way/10710425#map=16/49.1572/8.4099

The problem is, that way 1 should look like way 2 since the only difference in both filters is the tag and value, which both appears in both ways (way 1 is "highway=path" and way 2 is "highway=cycleway").

Here is how it looks with default/shipped UniRS style:
![unirs](https://user-images.githubusercontent.com/49197621/94352938-d6ca1280-006b-11eb-8d9c-4c656d02d875.JPG)

As you can see, way 1 has the same rendering style, but way 2 changed correctly.

Here is the custom style:
[test.render.zip](https://github.com/osmandapp/OsmAnd/files/5287566/test.render.zip)

The question is why doesn't my rendering style change way 1? What do I have to do get it changed or is it a bug in OsmAnd? I think it's a bug.

### Your Environment
OsmAnd Version: 3.7.4/3.8.3
Android/iOS version: 7.1 (LOS), 8.0
Device model: different

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
Detailed maps from Germany, Baden-Württemberg, dated September 2020.

**Comment by xmd5a2** [comment]
This is not a bug. Line 161 converts highway=path+foot=designated to highway=footway so you should use highway=footway instead of highway=path
https://github.com/osmandapp/OsmAnd-resources/blob/master/obf_creation/rendering_types.xml#L161

**Comment by xmd5a2** [comment]
![Screenshot from 2020-10-01 12-41-17](https://user-images.githubusercontent.com/5829014/94793628-6d3b6280-03e3-11eb-8d6d-4350f5fb6c5a.png)
```xml
			<filter tag="highway" value="footway" color="#0000ff" color_0="#400020ff" pathEffect="4_2" pathEffect_0="">
				<filter minzoom="11" maxzoom="13" strokeWidth="0.7" strokeWidth_0="4"/>
				<filter minzoom="14" maxzoom="15" strokeWidth="1" strokeWidth_0="5"/>
				<filter minzoom="16" strokeWidth="1.3" strokeWidth_0="6"/>
			</filter>
```

**Comment by BigKananga** [comment]
You won't call it a bug and maybe it isn't one. But if you ask me it's a bad design. Your workaround works for me, but it's not good because paths witch are also designated as cycleway are also treated as footway. In the rendering styles there should  be separate entry for "highway=path" together with "foot=designated" instead of the mentioned conversion line.
