### ISSUE TITLE
route/track analysis on map works in mirror image

### ISSUE THREAD

**Issue by tradavyvy** [osmandapp/OsmAnd#9907]
### Description
when I set a route to analysis on map and i move my finger from left to right the marker-line movers from right to left and visa versa. 
I do not remember this happening in pre Osmand 3.8.2

### How to reproduce?
see description

### Your Environment
OsmAnd Version: 3.8.2
Android/iOS version: 10
Device model: Samsung Galaxy A40

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

Offline map of the Netherlands

**Comment by sonora** [comment]
In deed, can confirm. Looks like it affects all GPX files, but only on the 'Analyze on map' screen. Only the direction of the swipe gesture is reversed, data and how the point on the map corresponds to it seems ok .

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/9854 - long description is here
