### ISSUE TITLE
Obsolete 'Import' duplication of GPX files

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#9908]
When in any Android file manager app you tap a GPX file already located in OsmAnd's 'Tracks' folder (or subfolders thereof), a copy of the file is nevertheless created in OsmAnd's 'Import' folder. This is, of course, unnecessary for any file already located in OsmAnd's folder space.

**Comment by vshcherb** [comment]
If file matches name & size that already exist in all tracks folder:
1. Toast "file is already imported in OsmAnd"
2. Open Track screen with that track

If file doesn't match leave the previous behsivor
