### ISSUE TITLE
Roundabout symbols when driving on left show as clockwise exits...

### ISSUE THREAD

**Issue by slackline** [osmandapp/OsmAnd#9912]
### Description

When driving on the left, e.g. in the UK, and using navigation when approaching a roundabout the symbol indicating which turn to take in the top left of the screen assumes you are driving on the right and will be going round the roundabout in an anti-clockwise which is *not* the case when you drive on the left.  You go round roundabouts anti-clockwise.

### How to reproduce?

Plan a route in a country that drives on the left (e.g. UK) that includes a roundabout.

### Your Environment
OsmAnd Version: 3.8.2
Android/iOS version: 9.0
Device model: Motorola Moto G7 Plus

**Maps used (online or offline):**   

N/A not a map issue.

**Comment by martenjj** [comment]
Possibly same as #7061, especially if moving between driving regions?

**Comment by slackline** [comment]
Yes, that looks very much like what I'm experiencing (was always driving so couldn't take screen shots).

Guess that makes this issue redundant so I'll close it and follow #7061.
