### ISSUE TITLE
Routing through barrier=gate

### ISSUE THREAD

**Issue by blackboxlogic** [osmandapp/OsmAnd#9914]
I've seen that car routing won't go through a gate. Are they any tags that can be added to a gate (access, opening_hours, fee) which the routing engine will understand to know that cars can pass through?

In the case I just encountered, a customer must stop and interact with a guard, but they can pass.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml#L854
I think tag "access=yes" will make it routable
