### ISSUE TITLE
Plan route / Open existing track stalls the app

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#9918]
Tapping 'Plan a route', then 'Open existing track' leads to an unresponsive behavior for me. Android warns after a minute or so that the app does not respond anymore.

No error log is created. Currently not sure if this is specific to the set of GPX files I have or not. This commit https://github.com/osmandapp/OsmAnd/commit/20a770fe82f32a1e846d9dd7d7cf5f1bae3b08db did not seem to fix this issue.

**Comment by sonora** [comment]
Same behavior for 'Add to a track', so looks like this has to do with displaying the list of existing GPX files.

**Comment by sonora** [comment]
I just notice that our code behind Plan a eoute's menu item 'Import track' works perfectly. So I guess we could rename that function to 'Open a track', (and maybe start the file dialog not at the system root but in OsmAnd's track folder), and we'd be done.

The menu item 'Open existing track' together with its faulty code could be deleted.

**Comment by vshcherb** [comment]
Yes planned to be reviewed and fixed this sprint

**Comment by androiddevkotlin** [comment]
> Currently not sure if this is specific to the set of GPX files I have or not.

**sonora**, tell me please:
1. How many tracks do you have and which phone model?
2. _Follow track screen, Plan route screen, Tracks dialog in configure map._ Do they open normally?

**Comment by sonora** [comment]
@androiddevkotlin Sorry about the late reply, I had not noticed there was a question. Answer as follows:

I observe this e.g. on a Samsung XCover 4s (320dpi), or also on a Samsung S4 mini (240dpi). On these devices there are about 2500 tracks organized in 50 sub-folders of the OsmAnd 'tracks' folder.

I have briefly re-named the tracks folder to tracks0, and can confirm it seems to be a number issue: Now OsmAnd does not stall when tapping 'Open existing track', instead shows me some sort of tracks dialog (which is of course empty now). 

So I guess instead of the button **"Plan a route/Open an existing track" just opening the system's file manager with start folder '<OsmAnd>/tracks'**, we are somehow trying to create a long list, which hits some overflow, or is just really slow?

**Comment by Chumva** [comment]
There is a problem with UI, this dialogue tries to create a view for every track (recyclerView has the wrong parameter for height and doesn't recycle views) so creating 2500 becomes very slow. Backend part works fine for most parts. It should be possible to fix this, but there was no solution which doesn't break UI behaviour with swipes.

**Comment by sonora** [comment]
In my oponion these flat list views are catatrophic anyway, we should maybe not invest in them at all (Configure maps/Tracks is a similar example). They work ok if you have a dozen or so items,  but they do not scale well and quickly become useless once the number of items increases.

Then you have to fall back to a file-system like representation like we have in MyPlaces/Tracks, or like we have it for button 'Plan a route/Import track'. I guess we could just use the latter, only use 'tracks' as the initially displayed folder? After all, all you do here is find one file and select it?

**Comment by sonora** [comment]
PS: True, if I wait long enough, the dialog appears all right, I've just tried. But then having to swipe through 50 folders horizontically is equally awkward. I relly vote for the UI the 'Import track' button produces, the swipe one seems obsolete.

**Comment by sonora** [comment]
PS2: I just notice we have **yet another** look&feel screen for a file/folder selection, it is under 'Plan a route', when you create a new gpx and are asked where to save it. (The mechanism there shows all sub-folders of 'tracks' as buttons and shortens all folder names to the first few characters followed by an ellipse (...), which is pretty useless when e.g. several folder names begin with the same word.)

All in all,  I guess we had better reuse screens and mechanisms on different dialogs and not always invent a new look and feel mechanism for every time we access a sinilar functionality, because that quite obviously is a severe roadblock for acceptable  user experience.
