### ISSUE TITLE
My Places / Tracks no longer sorts

### ISSUE THREAD

**Issue by akkana** [osmandapp/OsmAnd#9921]
I just updated to 3.8.2, and when I go to My Places, tap on Tracks and expand a folder underneath, the tracks inside are no longer sorted alphabetically; they're in a seemingly random order, and I don't see any UI that looks like it's related to sorting -- is there something there I'm missing? The unsorted list makes it extremely difficult to find anything in a long list of tracks.

**Comment by pebogufi** [comment]
It is a good idea first have a look on existing issue reports:
https://github.com/osmandapp/OsmAnd/issues/9808

**Comment by vshcherb** [comment]
Fixed in 3.8.3
