### ISSUE TITLE
[Feature request] OSM Edit: consider making advanced view key/value autocomplete multi-line

### ISSUE THREAD

**Issue by bkil** [osmandapp/OsmAnd#9923]
If I am using long keys or values (e.g., `internet_access:ssid`), the end of autocomplete choices are chopped off, making them useless if many choices exist having the same prefix.

**Comment by dmpr0** [comment]
I think it is partly fixed, by this task https://github.com/osmandapp/OsmAnd/issues/11445, we increase text field width.

**Comment by bkil** [comment]
Yes, that would be even better. If `internet_access:ssid` and its autocomplete can fit with that layout, I think we can close this.
