### ISSUE TITLE
[UX bug] If I enable instant actions, its icon hides the button for zooming out the map

### ISSUE THREAD

**Issue by bkil** [osmandapp/OsmAnd#9925]
OsmAnd~ 3.7.4

**Comment by njohnston** [comment]
If you mean the quick action button, it can be moved anywhere on screen by long-pressing it.

It would be better if the default location did not hide the zoom out button though.

**Comment by bkil** [comment]
Oh, thanks, that did work.

I've been using OSMAnd for many years now but just yesterday dived into all the features and customization opportunities. Because there are so many options, I quickly clicked through everything at the same time. I did recall seeing a popup explaining that something can be moved around after long pressing it, but I think I dismissed the hint quicker than I could read it, so I guess it's just user error.

I think we could mind as well close this issue.

**Comment by frasty** [comment]
This should be worked out or it should be stated clearer that the quick action button can be freely moved around. I didn't find a way to unhide the zoom out button until I stumbled upon this issue.
