### ISSUE TITLE
Navigation -> Destinations -> Sort: Allow to reverse all points

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#9931]
In the menu Navigation -> Destinations there is a button "Sort". There is already an option "Reverse starting point & destination". This doesn't make much sense when having intermediate destinations configured.

Either:
- reverse the order of all intermediate points, too, or
- add a new option "Reverse starting point & all destinations"

**Comment by androiddevkotlin** [comment]
Bugs with my location with reverse all points. Will be fixed today.

**Comment by dmpr0** [comment]
# Review 
- [ ] Show reverse even with one intermediate
- [ ] Swap button on the main screen should reverse all points order too.

**Comment by Chumva** [comment]
This should be added here - https://github.com/osmandapp/OsmAnd/pull/10475.

**Comment by dmpr0** [comment]
# Review 
- [ ] Show reverse even with one intermediate
