### ISSUE TITLE
Edit/Create POI, text in Value-field buggy

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#9938]
### Description
For smaller display (Samsung S7, 5,1") 
- the field for Value is too small
- in some cases it overwrites Text "Value", example: opening_hours, mail, fax

It looks like calculation of field height is wrong if text does not match into field.
The field should be scrollable vertically and/or horizontally.

### How to reproduce?

Just edit a POI. Example:
https://www.openstreetmap.org/node/2487635301
Pos: Standort: 48,0661404, 7,8858778

### Your Environment
OsmAnd Version: ccurrent, 3.9.0#30647
Android version: 8
Device model: Samsung S7

![Screenshot_20201003-122518_OsmAnd~~01](https://user-images.githubusercontent.com/18628183/94989481-79572980-0575-11eb-9619-698301674b56.jpg)

**Comment by vshcherb** [comment]
merged to https://github.com/osmandapp/OsmAnd/issues/9893#issuecomment-705363091
