### ISSUE TITLE
Support fuel:LH2=yes

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#9940]
It would be nice to have support for [`fuel:LH2=yes`](https://wiki.openstreetmap.org/wiki/Key:fuel:LH2) (hydrogen) at fuel stations.

**Comment by xmd5a2** [comment]
Already supported
https://github.com/osmandapp/OsmAnd-resources/blob/master/poi/poi_types.xml#L1674

**Comment by scaidermern** [comment]
Nope, please re-check. OsmAnd doesn't show it. Likewise OsmAnd doesn't show `fuel:HGV_diesel` which is also in this list. Maybe it is missing somewhere else? Might apply to other fuel values, too.

**Comment by scaidermern** [comment]
Thanks!
