### ISSUE TITLE
Unable to create new track/route folders from Plan a route, elsewhere

### ISSUE THREAD

**Issue by barteis** [osmandapp/OsmAnd#9941]
### Description
I think this is a bug, though it's possibly a "Nice to have"...or I'm just missing it.  
After creating a route in "Plan a route", or recording a route and saving it, I'm not seeing a way to create a new folder for it.

I've looked in:
- Plan a route/Save  changes & Save as new track, and
- My Places/Tracks.  

(I do see the option to create a folder in My Places if I want to move a track to a different folder.  But that's not a new track.) 
Also, when trying to save a route in Plan a route, I'm seeing folders I had previously deleted. 

### How to reproduce?
See above.
 
### Your Environment
OsmAnd Version: 3.8.3
Android/iOS version: Android 11
Device model:Pixel 3

**Maps used (online or offline):**   
online: California

**Comment by vshcherb** [comment]
Yes it's not possible, though it should be possible to save with name "New Folder/My Track" and it is supposed to create a folder

**Comment by barteis** [comment]
Thanks!

**Comment by vshcherb** [comment]
There is another open issue to create a UI for that
