### ISSUE TITLE
No points for the recorded track

### ISSUE THREAD

**Issue by 532910** [osmandapp/OsmAnd#9943]
### Description

I've recorded track with Trip recording plugin, it shows correctly on the map, but Points screen is empty.
![image](https://user-images.githubusercontent.com/14617699/95016616-bea25680-065c-11eb-8ad4-88ff79282fb9.png)

### How to reproduce?

I don't know. I can share the track with OsmAnd team, but not public.

### Your Environment
OsmAnd Version: 3.4.7 F-Droid
Android/iOS version: LineageOS on android 10
Device model: OP3T

**Comment by scaidermern** [comment]
Did you create any waypoints during track recording? Did you add these waypoints to the currently recording track or to some other track?

**Comment by 532910** [comment]
Definitely no!

**Comment by scaidermern** [comment]
Then this is expected behavior. Points are only explicitly created waypoints. If you didn't create any waypoints then the list of points will be empty.

**Comment by 532910** [comment]
Ups, my fault.
