### ISSUE TITLE
calibrated (by user) raster maps

### ISSUE THREAD

**Issue by mariush444** [osmandapp/OsmAnd#9944]
The idea is to have the possibility to use calibrated (by the user) raster offline maps.
It is very useful for backpackers or off road users.
I can calibrate my own map, scanned or downloaded jpg, gif and use offline on my smartphone.
e.g. The OruxMap has this feature.

The most popular, useful formats are: geopdf, geotiff and ozf2 (OziExplorer)
Some examples.
1. US National parks allows to download geopdf for backpackers
https://www.nps.gov/deva/planyourvisit/wildrose-peak.htm

2. I can get some maps as GeoTiff, GeoPdf or just jpg for calibration from
https://ngmdb.usgs.gov/topoview/viewer/#6/37.675/-122.772

3. Many companies (like http://www.mapstor.com/) sell oziexplorer format maps.
One can download from http://loadmap.net/en/m24428 for free.

Some of the maps can be used as downloaded in mbtiles format
but for individual users the self calibrated maps are the best solution. (in my opinion)

Routing is not needed in this case.

**Comment by mariush444** [comment]
I created script for this 
https://github.com/mariush444/raster2osmand

**Comment by mariush444** [comment]
@thompehw  I moved the discussion to my topic to be less "off topic"
Thanks a lot for advises. That's good idea about jpg but I found problem that jpg had no transparency so at the border of a map you can't see main map. But the set of files are smaller indeed. Then I tried to optimized the script for conversion raster2tiles.
The idea was to convert only the png files that are not at the borders and they didn't use transparency.
So I converted png -> jpg that are only in the middle of the map. But I found other problem. OSMAND can't displayed mixed tiles jpg&png. It can display png or jpg only.  Another observasion is that OSMAND can display sqlitedb with png only. It doesn't work with jpg inside sqlitedb.
About zoom - yes I know that. I delete not needed zoom but still it is not such effective as it should be in my opinion.
Any way thank you again for ideas.

@vshcherb  You can move or delete my comments in https://github.com/osmandapp/OsmAnd/discussions/11735 discussion if they are to much off topic.

**Comment by mariush444** [comment]
I added additional script to https://github.com/mariush444/raster2osmand 
This script converts tiles in directory to sqlitedb.

**Comment by vshcherb** [comment]
@mariush444 the effort is quite unclear how much to change & fix. The earliest priority for this feature would be Q3-Q4 2021.  Indeed it's better to start another more specific feature requests and everything else to focus on discussions pages

**Comment by mariush444** [comment]
@vshcherb I will create new topic as you advice but let me know what should be described in more details.
I would like to see geotif in OSMAND as Overlay/Underlay map. What is unclear from your point of view?

Q3-Q4 2021 is OK for me.
