### ISSUE TITLE
Hiking trails missing numbers

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd#9947]
### Description
In the previous app updates, all the hiking trails had the corresponded numbers. After the app update, some numbers are missing.

### How to reproduce?
OsmAnd menu - Configure map - Routes - SAC, enable the Hiking symbol overlay.

51.14984 13.65483
![image](https://user-images.githubusercontent.com/50198677/95059675-e0a1e480-0701-11eb-9329-bfb1284a0432.png)

45.906668,7.6261483
![image](https://user-images.githubusercontent.com/50198677/95059713-ec8da680-0701-11eb-937c-bf028ca905ee.png)

44.1188123,10.6431996
![image](https://user-images.githubusercontent.com/50198677/95059727-f4e5e180-0701-11eb-82c0-9dd38eee21e0.png)
![image](https://user-images.githubusercontent.com/50198677/95059749-ff07e000-0701-11eb-8d71-3f8b73ddcb32.png)

### Your Environment
OsmAnd Version: 3.8.3

**Comment by xmd5a2** [comment]
https://www.openstreetmap.org/way/475703956
```
Way types [highway-track (52), network_nwn (18), network_lwn (15), route_hiking (7), route_mtb (10)] add_types [bicycle-yes(31), mtb:scale-2(72), mtb:scale:uphill-2(81), tracktype-grade4(74), surface-dirt(58), smoothness-very_horrible(79), trail_visibility-good(16), sac_scale-hiking(65), osmand_highway_integrity-8(43), hiking_osmc_waycolor-red(3), hiking_osmc_foreground-red_triangle_line(32), hiking_osmc_background-white(33), hiking_network-iwn(44), route_hiking_1-(1), route_hiking_1_network-iwn(45), route_hiking_2-(22), route_hiking_2_network-nwn(63), route_hiking_2_osmc_foreground-red_triangle_line(40), route_hiking_2_osmc_background-white(41), route_hiking_2_osmc_waycolor-red(24), route_hiking_3-(35), route_hiking_3_network-lwn(53), route_hiking_3_osmc_foreground-white_stripe(37), route_hiking_3_osmc_background-red(38), route_hiking_3_osmc_waycolor-red(39), route_hiking_4-(46), route_hiking_4_network-lwn(66), route_hiking_4_osmc_foreground-white_stripe(49), route_hiking_4_osmc_background-red(50), route_hiking_4_osmc_waycolor-red(51)] Names [hiking_route_ref(19) - E1, route_hiking_1_ref(20) - E1, name(17) - CAI 102, hiking_route_name(5) - (SI L15) Abetone (Boscolungo) - Lago Santo Modenese, European Long distance path E1 - part Italy - Tuscany, Grande Escursione Appenninica, 102, route_hiking_1_name(6) - European Long distance path E1 - part Italy - Tuscany, route_hiking_2_name(34) - Grande Escursione Appenninica, route_hiking_3_name(42) - 102, route_hiking_4_name(48) - (SI L15) Abetone (Boscolungo) - Lago Santo Modenese, operator(54) - Club Alpino Italiano, osmc_stub_name(2) - ., hiking_route_name:de(26) - Europäischer Fernwanderweg E1 - Italienischer Abschnitt - Toskana, hiking_route_name:it(27) - Sentiero europeo E1, Italia - Toscana, route_hiking_1_name:de(28) - Europäischer Fernwanderweg E1 - Italienischer Abschnitt - Toskana, route_hiking_1_name:it(29) - Sentiero europeo E1, Italia - Toscana, route_hiking_2_osmc_stub_name(23) - ., route_hiking_3_osmc_stub_name(36) - ., route_hiking_4_osmc_stub_name(47) - .] id 60890106487 osmid 475703956
```
1)hiking_route_ref(19) - E1
There should be 4 refs because this way belongs to 4 hiking relations
2)Something should be done with rendering style because currently it renders only one ref as route name
<case tag="route_hiking" value="" nameTag="route_hiking_#SEQ_ref" textSize="13"/>
other refs are not displayed

**Comment by vshcherb** [comment]
This is correct cause there is no, route_hiking_2_ref, route_hiking_3_ref... 

I assume that 
route_hiking_3_name(42) - 102, route_hiking_4_name(48) - (SI L15) could represent Refs, but we should do it carefully with tag_transform and check the length of the name

**Comment by vshcherb** [comment]
@xmd5a2 
![image](https://user-images.githubusercontent.com/1042025/95597276-b5dfc500-0a4e-11eb-918f-775ab7ef4620.png)
![image](https://user-images.githubusercontent.com/1042025/95597297-ba0be280-0a4e-11eb-9947-54584b71280b.png)

**Comment by xmd5a2** [comment]
![Screenshot from 2020-10-23 15-33-51](https://user-images.githubusercontent.com/5829014/97008217-37554e00-154b-11eb-872c-cc43bc17c68f.png)
