### ISSUE TITLE
show 'drinking water' POI

### ISSUE THREAD

**Issue by AnastasiaTiutina** [osmandapp/OsmAnd#9950]
### Description
This tags should appear when we try to find all 'drinking water' POI 'amenity=drinking_water;man_made=water_well'

**Comment by vshcherb** [comment]
We already support 'amenity=drinking_water' but we don't support 'man_made=water_wel' cause this doesn't mean that water is present and publicly accessible

**Comment by scaidermern** [comment]
@AnastasiaTiutina You can create a custom filter for searching for drinking water + water wells.

**Comment by misterRaven** [comment]
@vshcherb but 'man_made=water_well' doesn't mean it's not publicly accessible, it's just a type of structure. There is [access tag](https://wiki.openstreetmap.org/wiki/Key:access#Facility_restrictions) for identifying accessibility.

**Comment by misterRaven** [comment]
so please reopen it

**Comment by misterRaven** [comment]
There can be misunderstanding of the issue:
when searching for drinking water POIs which have both 'amenity=drinking_water' and 'man_made=water_well' tags are not included into results.

**Comment by vshcherb** [comment]
Well it also depends on "cultural surroundings" and word translation. In OSM those 2 types are different. We don't provide both of them. 
"Drinking water" -> ["Drinking water tap" and "Water well"]. There is also no limitation to use both tags in OSM (at least I don't know). 
We follow OSM and provide 2 separate types which could be combined in a custom filter. We're not going to combine them and keep only 1 cause it will limit search possibilities.
