### ISSUE TITLE
Highway cross-under is not used in routing at A99 Feldmoching/Unterschleißheim 48.226085 N, 11.542580 E

### ISSUE THREAD

**Issue by hman2** [osmandapp/OsmAnd#9952]
# 🐞 routing report

### Routing engine

- [ x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, OpenRouteService, OSRM, etc.)

### Routing Profile

bike

### Start and end points

Lerchenstrasse, Feldmoching to Unterschleißheim

### Actual and expected routes

Routing should use the highway crossunder directly east of the railway line Munich-Regensburg (48.226085 N, 11.542580). In Open Street Map there is an issue (1392217) because the cross-under was blocked due to bridge maintenance. That was prolonged several times, but as of now (October 4th) the bridge maintenance is finished. Interestingly to the north of the former construction side there is still the two year old sign that blocks the road, but in the south it's gone. And the cross-under is freely usable, no contruction equipment or materials left. 

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

7.1.4

</code></pre>

**Device and Android/iOS version:**
Fairphone Open OS 19.11.2 (AOSP 7.1.2)

**Maps used (online or offline):**

- [x ] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

Street map of upper bavaria (Oberbayern) dated September 1st, 2020.

**Anything else relevant?**

**Comment by hman2** [comment]
Remark: The cross-under prolongs Raheinstrasse north and later joins Ferdinand-Schulz-Allee.

**Comment by hman2** [comment]
I should rather not have called it a road, it's merely a better field path with clay, some sand and gravel on it. Suitable for pedestrians and suitable for bicycles. Not ideal, but can be driven by bike.

**Comment by aceman444** [comment]
Well, that road (https://www.openstreetmap.org/way/9782622) was highway=construction until Oct 5th 2020, so that is what you have in the monthly maps. It is OK for OsmAnd to avoid it. Now somebody changed it to highway=track with bicycle=yes, so in the next map updates of OsmAnd (of Nov 1st), all should work fine.

**Comment by vshcherb** [comment]
Or you could use OsmAnd Live to get map updated faster

**Comment by hman2** [comment]
That road has never been a highway and will never be. It can't, physically impossible, because it crosses under two highways with just 6 or 7 meters or so between the east pillars of the bridge and the fenced off railway track! Yes, it was a construction site and therefore blocked, but the construction was a renovation of the bridges, not to built a highway...

**Comment by aceman444** [comment]
Then you have to get this fixed in OSM data itself (www.openstreetmap.org), OsmAnd can't do anything about it, it just consumes the OSM data.

**Comment by hman2** [comment]
I gave them a comment.
