### ISSUE TITLE
Plan route > add to a track original track disappears 

### ISSUE THREAD

**Issue by AnastasiaTiutina** [osmandapp/OsmAnd#9954]
when you try to add a new track to existed track. The previous part of the path disappeared
it does not reproduce when the route between points a straight line 
- [x] Edit Multiple routes
----
**Review:**

- [x] UI split/join segment

**Comment by dmpr0** [comment]
Also if the track contains waypoints before the edit, they will be lost after editing and saving changes.

**Comment by dmpr0** [comment]
Review:
Add to a track, working until the user tap the "Done" button, after that only a new part will be saved.
