### ISSUE TITLE
ETA miscalculated

### ISSUE THREAD

**Issue by grosjo** [osmandapp/OsmAnd#9960]
### Description
ETA is based on a "default" value per type of transport
Whereas the ETA shall be based on the current route (actual average speed, whatever is the type of vehicule)

### How to reproduce?

Any ETA calculation in the app

### Your Environment
OsmAnd Version: 3.8.3
Android/iOS version: 10
Device model: Xiaomi 9t Pro

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by grosjo** [comment]
@vshcherb  Not sure this is "nice to have" but a definite awful bug making the app barely usable !

**Comment by jorgk3** [comment]
I use OsmAnd on the plane. Normal passenger jets travel at about 900 km/h. The ETAs calculated in airplane mode are always totally wrong. Example: Speed 900 km/h, distance to destination 400 km, remaining travel time, no, not 27 minutes, but instead 2 hours, 46 minutes. Useless. I have more examples that this one. If I calculate the speed that is used for the calculation, I come to about 144 km/h. Come on, that's slower than the plane at take off :-(
Really makes the feature unusable.

**Comment by pebogufi** [comment]
I really think that calculating **ETA for an airplane** is not one of the main features of an  app for navigation, search for pois, orientation on maps and more...
So if you would like that feature, what about giving assistance by providing some formula for calculation ?

**Comment by jorgk3** [comment]
Sorry, I don't understand the answer. If I interpret the icons correctly, the app supports car, bike, by foot, bus and plane. A plane is to be assumed to take the direct path, hence: `v = s/t` or `t = s/v`, t:time, s:distance, v:velocity.

**Comment by pebogufi** [comment]
First of all: real live may differ from theory - nearly allways.
Did you ever hear of "air-line distance" or "linear distance" ? (I am not sure about the term, I am not a native english speaker).
The "Aircraft" profile is just intended to calculate distances with  "air-line distance" mode, so the name and symbol are funmy.
I don't think that it is indended to calculate a travel with an aircraft. Calculating such a travel needs much more information of the wind (with respect to direction, daytime,  temperature, air pressure, humidity, hight (FL=FlightLevel)) and much more. You need a very complicated weather forecast for commercial aviation.
I think the ETA calculated for "Air-line" profile is just funny - nothing more. It would be better to remove that nonsense.

**Comment by grosjo** [comment]
I don't understand why it is "funny"  ?

The issue exists fof all type of transport. Gow to het this fixed ? This is a core feature of any navigation app

**Comment by grosjo** [comment]
Attached some totally crazy wrong calculation. When this will be fixed ? Definitely not a "nice to have"  but a critical issue for a travelling app !![Screenshot_20210417-214315.png](https://user-images.githubusercontent.com/2287111/115125918-1b9ba380-9fd4-11eb-8f58-25128ff15198.png)![Screenshot_20210417-120520.png](https://user-images.githubusercontent.com/2287111/115125927-26eecf00-9fd4-11eb-8568-dc272bbc5269.png)![Screenshot_20210417-213852.png](https://user-images.githubusercontent.com/2287111/115125929-29512900-9fd4-11eb-853d-24941c604e13.png)

**Comment by vshcherb** [comment]
It looks correct to me, so I don't see an issue at all.

**Comment by jorgk3** [comment]
Sorry, the calculated ETA is totally incorrect, at least for plane travel, I hope https://github.com/osmandapp/OsmAnd/issues/11493 makes this very clear.
