### ISSUE TITLE
No way to edit or remove Map sources

### ISSUE THREAD

**Issue by vincentvdwal** [osmandapp/OsmAnd#9962]
### Description
In the new version 3.8.3, opposed to 3.7.4 it is not anymore possible to edit or remove added Map sources.

### How to reproduce?
Go to Configure Map -> Map Source... -> Add one
This new map cannot be edited or removed.

### Your Environment
OsmAnd Version: 3.8.3
Android/iOS version: 3.80

**Comment by scaidermern** [comment]
You can remove map sources at Menu -> Download Maps -> Local -> Online and cached tile maps -> three dots menu.
