### ISSUE TITLE
Timeout after wake-up: Overlapping text

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#9984]
App Profile -> General Settings -> Screen Control -> Timeout after wake-up

The text field for "Timeout after wake-up" overlaps with the timeout duration field (right above the slider):

![photo_2020-10-08_09-36-31](https://user-images.githubusercontent.com/1040784/95428864-e2f67f80-0949-11eb-96f3-6ce26c1223f4.jpg)

**Comment by Chumva** [comment]
This should be fixed here - https://github.com/osmandapp/OsmAnd/pull/9987.
