### ISSUE TITLE
flooded area in Ukraine

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd#9994]
The Ukrainian Kharkiv area map is flooded on 2km zoom level
50.0026503,36.8392006
![image](https://user-images.githubusercontent.com/50198677/95575559-94bfaa00-0a37-11eb-8ad5-a1c4f890de57.png)

### Your Environment
OsmAnd Version: 3.8.3

**Maps used (online or offline):**   

Ukraine Kharkiv oblast

**Comment by trofimich** [comment]
![Screenshot_20201009-131822](https://user-images.githubusercontent.com/36424453/95576839-cdf91980-0a39-11eb-88e8-186b656c941f.png)

**Comment by trofimich** [comment]
![IMG_20201009_141507_502](https://user-images.githubusercontent.com/36424453/95576872-dcdfcc00-0a39-11eb-82a6-8cd55b7d284c.jpg)

**Comment by xmd5a2** [comment]
Issue is reproducible only with full Ukraine map. Kherson oblast map doesn't affected. 
Problematic island: https://www.openstreetmap.org/way/835679609
In full Ukraine map (obf->osm) there is `natural=coastline` tag on it, but there is no such tag in Kherson oblast extract. OSM object doesn't contains natural=coastline and never contained.
![Screenshot from 2020-11-18 18-48-20](https://user-images.githubusercontent.com/5829014/99554559-60dd8a00-29d0-11eb-929a-720094755760.png)

**Comment by xmd5a2** [comment]
Recent maps doesn't have this issue. Looks like there was island with duplicate geometry. One geometry has natural=coastline, other not. Someone deleted geometry with natural=coastline and now maps are fine. I was looking at old Ukraine full map.
