### ISSUE TITLE
Looking for cities or street should be guessed, and found

### ISSUE THREAD

**Issue by tykayn** [osmandapp/OsmAnd#9997]
# 1) I am very confused with the results priorities returned by OSMand.
## looking for cities

Let's say i am around Paris and i look for an address somewhere in France.
I tap the "navigation" button, saying i want to get route to somewhere via car.
I am a often looking for rough estimation of travel time by entering only the city name, before looking for a more precise street adress, which i would enter with the explicit term "rue something".
So i expect to get a city result when there is only one city named after a research made by a single word.
if i search for "Lyon", i expect to get the city address first, not any street whose name contains the term "lyon" around, like all the "Rue de Lyon" that could exist.
For this example, Lyon city is after 30 results of street that could be found around 100km of my position, that's way too much.
This should be filtered by a few if the term matches exactly a city name.

If i want a street name in a particular city i would have some button to show "more results", or i would precise the city i want. 
If i am looking for a street saying "123 rue something" i want to find it first near my position.

This result behavior should be configured by default, or should be customizable.
we should not have to specify each time if we want to find something we have been searching before or not (we could do that by just scolling through history, i want to search for something, not filter the current history by default each time).

## 2) Often it does not returns a result
when i search for a well formatted adress "12 rue du temple, paris" is not found, but i can find it in the results on openstreetmap.org, which also uses Nominatim.

i also suspect that osmand is not aware of when it is able or not to join the network

device and soft infos:
osmand 3.7.4, lineageOS with microG cheeseburger android 9, oneplus A5000

**Comment by vshcherb** [comment]
1. There is a difference between intermediate search result & complete. I guess when you type "Lyon" and press search or type "Lyon ", it will produce better results.
2. "12 rue du temple, paris" - it is a first place result if you search in Paris. Unfortunately if you are in Lille you will need to hit "Search more" to see it in first place. 
The reason behind that search is localized by maps and it first searches in the current visible map, otherwise it takes too long. So this is a current limitation

P.S. OsmAnd doesn't use nominatim search.

**Comment by Zirochkabila** [comment]
If typed in 4600 Sugar Maple Lane, Little Rock, Arkansas, 72212; over 100 points came up to choose from but not the searched address.
For example [OSM](https://www.openstreetmap.org/way/12915162#map=17/34.79344/-92.42294) gives more accurate information

<details><summary>4600 Sugar Maple Lane, Little Rock, Arkansas, 72212</summary>
<img width="791"<img width="1099" alt="Screenshot 2023-02-02 at 14 26 58" src="https://user-images.githubusercontent.com/104760013/216325251-00da5721-68fb-4dae-a582-41d2cf31342d.png">">
</details>
